openapi: 3.0.0
info:
  title: Admission Application Supporting Items
  description: >
    The checklist items required for application of applicant's admission for
    the applicant and term being processed. The checklist rules are established
    in the SAACHKB page by the school to reflect the institution's policy on the
    documents, etc. required to substantiate an individual's application.


    Please refer to the section 'API Integration Configuration Settings' in Banner Ethos API Handbook for all the configuration settings needed for this API.
  version: "12.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Recruitment
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/admission-application-supporting-items:
    get:
      summary: Returns resources from SARCHKL
      description: >
        Returns all admission application's checklist items from SARCHKL table
        of the applicant and term being processed.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ADM_APPL_SUPP_ITEMS
      tags:
        - admission-application-supporting-items
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v12+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v12+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource in SARCHKL
      description: >
        Creates a checklist item record in the SARCHKL table for the applicant
        and term being processed for the admission application.

         POST requests must include a nil GUID value ("00000000-0000-0000-0000-000000000000") for the root id property.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ADM_APPL_SUPP_ITEMS
      tags:
        - admission-application-supporting-items
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v12+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v12+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v12+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v12+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
  /api/admission-application-supporting-items/{id}:
    get:
      summary: Return the requested resource from SARCHKL
      description: >
        Returns the detail of admission application's checklist item record from
        SARCHKL of the applicant and term being processed for the passed in
        identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ADM_APPL_SUPP_ITEMS
      tags:
        - admission-application-supporting-items
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v12+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v12+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v12+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource from SARCHKL
      description: >
        Updates the checklist item record in the SARCHKL table for the applicant
        and term being processed for the admission application.


        Properties that are not updatable: id, application.id, type.id
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ADM_APPL_SUPP_ITEMS
      tags:
        - admission-application-supporting-items
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Admission Application Supporting Items for
            use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v12+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v12+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v12+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v12+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-admission-application-supporting-items.json:
      title: Admission Application Supporting Items
      description: Supporting items required for application of student admission.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the admission application supplementary
            item.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: SARCHKL_GUID(SARCHKL)
        application:
          title: Application
          description: The application for which the supplementary items are required.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Application.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: admission-applications 
              x-lineageReferenceObject: SARADAP_GUID(SARADAP)
          additionalProperties: false
          required:
            - id
        type:
          title: Type
          description: The type of supplementary item.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Type.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: admission-application-supporting-item-types 
              x-lineageReferenceObject: SARCHKL_ADMR_CODE(SARCHKL)
          additionalProperties: false
          required:
            - id
        receivedOn:
          title: Received On
          description: The date when the supplementary item was received.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
              x-lineageReferenceObject: SARCHKL_RECEIVE_DATE(SARCHKL)
            - type: string
              maxLength: 0
        required:
          title: Required
          description: Requiredness of the supplementary item.
          x-lineageReferenceObject: derived
          x-lineageDerivedLogic: If SARCHKL_MANDATORY_IND = 'Y' then return 'mandatory' else no value.
          oneOf:
            - type: string
              enum:
                - mandatory
            - type: string
              maxLength: 0
        requiredByDate:
          title: Required By Date
          description: The date by which the supplementary item is required.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: SARCHKL_DEADLINE_DATE(SARCHKL)
            - type: string
              maxLength: 0
        assignedOn:
          title: Assigned On
          description: The date the supplementary item was assigned as a requirement.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: SARCHKL_SOURCE_DATE(SARCHKL)
            - type: string
              maxLength: 0
        externalReference:
          title: External Reference
          description: An external reference of the supplementary item.
          type: string
          x-lineageReferenceObject: SARCHKL_COMMENT(SARCHKL)
        status:
          title: Status
          description: The status of the supplementary item.
          type: object
          properties:
            type:
              title: Type
              description: Status type of the supplementary item.
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: Display 'notReceived' if the received date is null and the code is not mapped in GORICCR or not set else display 'received'.
              enum:
                - incomplete
                - received
                - waived
                - notReceived
              type: string
            detail:
              title: Detail
              description: Custom status type of the supplementary item.
              oneOf:
                - type: object
                  properties:
                    id:
                      title: ID
                      description: The global identifier for the Detail.
                      type: string
                      format: guid
                      pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                      x-lineageLookupReferenceObject: admission-application-supporting-item-statuses 
                      x-lineageReferenceObject: SARCHKL_CKST_CODE(SARCHKL)
                  additionalProperties: false
                  required:
                    - id
                - type: object
                  maxProperties: 0
          additionalProperties: false
          required:
            - type
      required:
        - id
        - application
        - type
        - status
      additionalProperties: false
