openapi: 3.0.0
info:
  title: Academic Disciplines
  description: >
    An academic discipline is a branch of knowledge that is researched and
    taught as a part of higher education. This entity is used to define academic
    programs.


    Please refer to "API Integration Configuration Settings" section in the Banner Ethos API Handbook for details on API configuration settings that needs to be configured for this API.
  version: "15.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/academic-disciplines:
    get:
      summary: Returns resources from STVMAJR
      description: >
        Returns a paged listing of all the academic discipline records of type
        major, minor and concentration from STVMAJR table
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v15+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Type  

            Returns all academic disciplines for the specific discipline type i.e. minor, major and concentration passed.

            ```

            /academic-disciplines?criteria={"type":"major"}

            ```
        - name: majorStatus
          in: query
          required: false
          schema:
            type: object
          description: |
            ### Major Status  
            Filter to return the major with the supplied status.
            ```
            /academic-disciplines?majorStatus={"majorStatus":"active"}
            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-academic-disciplines.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v15+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource in STVMAJR
      description: >
        POST requests must include a nil GUID value
        ("00000000-0000-0000-0000-000000000000") for the root id property.


        Creates a new academic discipline record in STVMAJR table


        Below is the API behavior details for reporting property on a create request:


        Reporting:


        - 'reporting' property is accepted only if STVMAJR_CIPC_CODE is sent in the create request.

        - The reporting country codes supported in the API are USA and CAN. Create request will be rejected with an error message if country code does not match USA or CAN.

        - The reporting country code sent in the request should match the home institution country code in GUBINST_ NATN_CODE. Create request will be rejected with an error message if the reported country code sent in request does not match the GUBINST_NATN_CODE.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v15+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v15+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v15+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v15+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-disciplines.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-academic-disciplines.json"
  /api/academic-disciplines/{id}:
    get:
      summary: Return the requested resource from STVMAJR
      description: >
        Returns a single academic discipline record from STVMAJR with the
        requested identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v15+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v15+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v15+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-disciplines.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource from STVMAJR
      description: >
        Updates the existing academic discipline record in STVMAJR table with
        the passed in identifier.


        Please refer to the notes in POST section of this document for API behavior details on 'reporting' property.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Academic Disciplines for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v15+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v15+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v15+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v15+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-disciplines.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-academic-disciplines.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-academic-disciplines.json:
      title: Academic Disciplines
      description: A range of academic disciplines offered by an organization.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: A global identifier for an academic discipline.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GORGUID_GUID(LDM_NAME= academic-disciplines) 
          x-lineageDerivedLogic: A record in GORGUID with GORGUID_LDM_NAME as 'academic-disciplines' will refer to each STVMAJR_CODE in STVMAJR.
        abbreviation:
          title: Abbreviation
          description: An abbreviation that identifies an academic discipline.
          type: string
          x-lineageReferenceObject: STVMAJR_CODE(STVMAJR)
        title:
          title: Title
          description: The full name of an academic discipline.
          type: string
          minLength: 1
          x-lineageReferenceObject: STVMAJR_DESC(STVMAJR)
        description:
          title: Description
          description: A full description of an academic discipline.
          type: string
          x-lineageReferenceObject: STVMAJR_MAJOR_DESC(STVMAJR) or STVMAJR_MINOR_DESC(STVMAJR) or STVMAJR_CONCENTRATION_DESC(STVMAJR)
        type:
          title: Type
          description: A type of academic discipline.
          x-lineageReferenceObject: derived  
          x-lineageDerivedLogic: If STVMAJR_VALID_MAJOR_IND = 'Y' then display 'major' and if  STVMAJR_VALID_MINOR_IND = 'Y' then display 'minor' and STVMAJR_VALID_CONCENTRATN_IND= 'Y' then display  'concentration'.
          enum:
            - minor
            - major
            - concentration
          type: string
        reporting:
          title: Reporting
          description: Properties required for governmental or other reporting.
          type: array
          items:
            type: object
            properties:
              country:
                title: Country
                description: The country with specific reporting requirements.
                oneOf:
                  - title: USA
                    description: Reporting requirements for the United States of America.
                    type: object
                    properties:
                      code:
                        title: Code
                        description: The ISO 3166 alpha-3 country code for the United States of America.
                        x-lineageReferenceObject: derived  
                        x-lineageDerivedLogic: Display the country code USA or CAN based on the GUBINST_NATN_CODE, if Classification of Instructional Programs (CIP) code is specified.
                        enum:
                          - USA
                        type: string
                      cipCode:
                        title: CIP Code
                        description: The discipline code in the Classification of Instructional Programs
                          (CIP) as specified for the United States of America.
                        type: string
                        x-lineageReferenceObject: STVMAJR_CIPC_CODE(STVMAJR)
                    additionalProperties: false
                    required:
                      - code
                  - title: Canada
                    description: Reporting requirements for Canada.
                    type: object
                    properties:
                      code:
                        title: Code
                        description: The ISO 3166 alpha-3 country code for Canada.
                        x-lineageReferenceObject: derived  
                        x-lineageDerivedLogic: Display the country code USA or CAN based on the GUBINST_NATN_CODE, if Classification of Instructional Programs (CIP) code is specified.
                        enum:
                          - CAN
                        type: string
                      cipCode:
                        title: Cip Code
                        description: The discipline code in the Classification of Instructional Programs
                          (CIP) as specified for Canada.
                        type: string
                        x-lineageReferenceObject: STVMAJR_CIPC_CODE(STVMAJR)
                    additionalProperties: false
                    required:
                      - code
            additionalProperties: false
      required:
        - id
        - title
        - type
      additionalProperties: false
