openapi: 3.0.0
info:
  title: direct-loan-originations-local-address
  description: API for RLADLOR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RLADLOR
  x-source-domain: Financial Aid
  x-source-title: Direct Loan Origination
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-loan-originations-local-address:
    get:
      tags:
        - direct-loan-originations-local-address
      summary: Return resources from RLADLOR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: true
          schema:
            type: string
        - name: rercodaAddrLine1
          in: query
          required: false
          schema:
            type: string
        - name: rercodaCdntCode
          in: query
          required: false
          schema:
            type: string
        - name: rercodaAddrLine2
          in: query
          required: false
          schema:
            type: string
        - name: rercodaStatus
          in: query
          required: false
          schema:
            type: string
        - name: rercodaAddrLine3
          in: query
          required: false
          schema:
            type: string
        - name: rercodaDateSent
          in: query
          required: false
          schema:
            type: string
        - name: rercodaCity
          in: query
          required: false
          schema:
            type: string
        - name: rercodaDocumentId
          in: query
          required: false
          schema:
            type: string
        - name: rercodaCdstCode
          in: query
          required: false
          schema:
            type: string
        - name: rercodaSeqNo
          in: query
          required: false
          schema:
            type: string
        - name: rercodaZip
          in: query
          required: false
          schema:
            type: string
        - name: rercdedRjctCode
          in: query
          description: Edit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCDED_RJCT_CODE
        - name: rercdedErrorField
          in: query
          description: Edit Field
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCDED_ERROR_FIELD
        - name: rercdedErrorValue
          in: query
          description: Edit Value
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCDED_ERROR_VALUE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-local-address-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/direct-loan-originations-local-address:
    post:
      tags:
        - direct-loan-originations-local-address QAPI (Query by POST)
      summary: Return resources from RLADLOR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-loan-originations-local-address-1.0.0_get_re\
                quest"
            example:
              keyblckAidyCode: 1718
              id: FASS30070
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-local-address-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    direct-loan-originations-local-address-1.0.0_qapi_post:
      required:
        - id
        - keyblckAidyCode
      type: object
      properties:
        id:
          type: string
        keyblckAidyCode:
          type: string
        rercodaAddrLine1:
          type: string
        rercodaCdntCode:
          type: string
        rercodaAddrLine2:
          type: string
        rercodaStatus:
          type: string
        rercodaAddrLine3:
          type: string
        rercodaDateSent:
          type: string
        rercodaCity:
          type: string
        rercodaDocumentId:
          type: string
        rercodaCdstCode:
          type: string
        rercodaSeqNo:
          type: string
        rercodaZip:
          type: string
        rercdedRjctCode:
          title: Edit
          maxLength: 3
          type: string
          description: "Lineage reference object : RERCDED_RJCT_CODE"
          x-lineageReferenceObject: RERCDED_RJCT_CODE
        rercdedErrorField:
          title: Edit Field
          maxLength: 200
          type: string
          description: "Lineage reference object : RERCDED_ERROR_FIELD"
          x-lineageReferenceObject: RERCDED_ERROR_FIELD
        rercdedErrorValue:
          title: Edit Value
          maxLength: 150
          type: string
          description: "Lineage reference object : RERCDED_ERROR_VALUE"
          x-lineageReferenceObject: RERCDED_ERROR_VALUE
    direct-loan-originations-local-address-1.0.0_get_response:
      type: object
      properties:
        rercoda_l:
          type: array
          items:
            required:
              - rercodaSeqNo
            type: object
            properties:
              rercodaCdstCode:
                title: State or Province
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODA_CDST_CODE, Lookup lineage
                  reference object : RTVCDST"
                x-lineageReferenceObject: RERCODA_CDST_CODE
                x-lineageLookupReferenceObject: RTVCDST
              rercodaDateSent:
                title: Date Sent
                type: string
                description: "Lineage reference object : RERCODA_DATE_SENT"
                format: date-time
                x-lineageReferenceObject: RERCODA_DATE_SENT
              rercodaSeqNo:
                title: Sequence
                maxLength: 3
                type: number
                description: "Lineage reference object : RERCODA_SEQ_NO"
                x-lineageReferenceObject: RERCODA_SEQ_NO
              rercodaZip:
                title: Zip or Postal Code
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODA_ZIP"
                x-lineageReferenceObject: RERCODA_ZIP
              rercodaCdntCode:
                title: Nation
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODA_CDNT_CODE, Lookup lineage
                  reference object : RTVCDNT"
                x-lineageReferenceObject: RERCODA_CDNT_CODE
                x-lineageLookupReferenceObject: RTVCDNT
              rercodaStatus:
                title: Status
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODA_STATUS"
                x-lineageReferenceObject: RERCODA_STATUS
              rercodaAddrLine3:
                title: Address Line 3
                maxLength: 75
                type: string
                description: "Lineage reference object : RERCODA_ADDR_LINE3"
                x-lineageReferenceObject: RERCODA_ADDR_LINE3
              rercodaAddrLine2:
                title: Address Line 2
                maxLength: 75
                type: string
                description: "Lineage reference object : RERCODA_ADDR_LINE2"
                x-lineageReferenceObject: RERCODA_ADDR_LINE2
              rercodaAddrLine1:
                title: Address
                maxLength: 75
                type: string
                description: "Lineage reference object : RERCODA_ADDR_LINE1"
                x-lineageReferenceObject: RERCODA_ADDR_LINE1
              rercodaDocumentId:
                title: Document ID
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODA_DOCUMENT_ID"
                x-lineageReferenceObject: RERCODA_DOCUMENT_ID
              rercodaCity:
                title: City
                maxLength: 50
                type: string
                description: "Lineage reference object : RERCODA_CITY"
                x-lineageReferenceObject: RERCODA_CITY
            x-lineageReferenceObject: rercoda_l
        rercded_rercoda_l:
          type: array
          items:
            type: object
            properties:
              rercdedRjctCode:
                title: Edit
                maxLength: 3
                type: string
                description: "Lineage reference object : RERCDED_RJCT_CODE"
                x-lineageReferenceObject: RERCDED_RJCT_CODE
              rercdedErrorField:
                title: Edit Field
                maxLength: 200
                type: string
                description: "Lineage reference object : RERCDED_ERROR_FIELD"
                x-lineageReferenceObject: RERCDED_ERROR_FIELD
              displayRjctDesc:
                title: Description
                maxLength: 65
                type: string
              rercdedErrorValue:
                title: Edit Value
                maxLength: 150
                type: string
                description: "Lineage reference object : RERCDED_ERROR_VALUE"
                x-lineageReferenceObject: RERCDED_ERROR_VALUE
            x-lineageReferenceObject: rercded_rercoda_l
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    direct-loan-originations-local-address-1.0.0_get_request:
      required:
        - rercodaSeqNo
      type: object
      properties:
        rercodaSeqNo:
          title: Sequence
          maxLength: 3
          type: number
          description: "Lineage reference object : RERCODA_SEQ_NO"
          x-lineageReferenceObject: RERCODA_SEQ_NO
        rercodaZip:
          title: Zip or Postal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODA_ZIP"
          x-lineageReferenceObject: RERCODA_ZIP
        rercodaCdntCode:
          title: Nation
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODA_CDNT_CODE, Lookup lineage
            reference object : RTVCDNT"
          x-lineageReferenceObject: RERCODA_CDNT_CODE
          x-lineageLookupReferenceObject: RTVCDNT
        rercodaStatus:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODA_STATUS"
          x-lineageReferenceObject: RERCODA_STATUS
        rercdedRjctCode:
          title: Edit
          maxLength: 3
          type: string
          description: "Lineage reference object : RERCDED_RJCT_CODE"
          x-lineageReferenceObject: RERCDED_RJCT_CODE
        rercdedErrorField:
          title: Edit Field
          maxLength: 200
          type: string
          description: "Lineage reference object : RERCDED_ERROR_FIELD"
          x-lineageReferenceObject: RERCDED_ERROR_FIELD
        rercodaDateSent:
          title: Date Sent
          type: string
          description: "Lineage reference object : RERCODA_DATE_SENT"
          format: date-time
          x-lineageReferenceObject: RERCODA_DATE_SENT
        rercodaCdstCode:
          title: State or Province
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODA_CDST_CODE, Lookup lineage
            reference object : RTVCDST"
          x-lineageReferenceObject: RERCODA_CDST_CODE
          x-lineageLookupReferenceObject: RTVCDST
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        rercodaAddrLine3:
          title: Address Line 3
          maxLength: 75
          type: string
          description: "Lineage reference object : RERCODA_ADDR_LINE3"
          x-lineageReferenceObject: RERCODA_ADDR_LINE3
        rercodaAddrLine2:
          title: Address Line 2
          maxLength: 75
          type: string
          description: "Lineage reference object : RERCODA_ADDR_LINE2"
          x-lineageReferenceObject: RERCODA_ADDR_LINE2
        rercodaAddrLine1:
          title: Address
          maxLength: 75
          type: string
          description: "Lineage reference object : RERCODA_ADDR_LINE1"
          x-lineageReferenceObject: RERCODA_ADDR_LINE1
        rercodaDocumentId:
          title: Document ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODA_DOCUMENT_ID"
          x-lineageReferenceObject: RERCODA_DOCUMENT_ID
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        rercodaCity:
          title: City
          maxLength: 50
          type: string
          description: "Lineage reference object : RERCODA_CITY"
          x-lineageReferenceObject: RERCODA_CITY
        rercdedErrorValue:
          title: Edit Value
          maxLength: 150
          type: string
          description: "Lineage reference object : RERCDED_ERROR_VALUE"
          x-lineageReferenceObject: RERCDED_ERROR_VALUE
      x-lineageReferenceObject: RERCDED_RERCODA_L
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
