openapi: 3.0.0
info:
  title: identification-additional-identification
  description: API for PPAIDEN administrative page
  version: 2.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PPAIDEN
  x-source-domain: Human Resources
  x-source-title: Identification
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/identification-additional-identification:
    get:
      tags:
        - identification-additional-identification
      summary: Return resources from PPAIDEN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: adidCode
          in: query
          description: ID Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GORADID_ADID_CODE
        - name: additionalId
          in: query
          description: Additional Identification
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GORADID_ADDITIONAL_ID
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GORADID_ACTIVITY_DATE
        - name: userId
          in: query
          description: User
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GORADID_USER_ID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v2.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/identification-additional-identification-2.0.0_get_\
                    response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/identification-additional-identification:
    post:
      tags:
        - identification-additional-identification QAPI (Query by POST)
      summary: Return resources from PPAIDEN
      requestBody:
        content:
          application/vnd.hedtech.integration.v2.0.0+json:
            schema:
              $ref: "#/components/schemas/identification-additional-identification-2.0.0_qapi\
                _post_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v2.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/identification-additional-identification-2.0.0_qapi\
                    _post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    identification-additional-identification-2.0.0_qapi_post_response:
      type: object
      properties:
        adidDesc:
          title: Description
          type: string
        additionalId:
          title: Additional Identification
          maxLength: 50
          type: string
          description: "Lineage reference object : GORADID_ADDITIONAL_ID"
          x-lineageReferenceObject: GORADID_ADDITIONAL_ID
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GORADID_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GORADID_ACTIVITY_DATE
        adidCode:
          title: ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GORADID_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GORADID_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        userId:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : GORADID_USER_ID"
          x-lineageReferenceObject: GORADID_USER_ID
      x-lineageReferenceObject: goradid
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    identification-additional-identification-2.0.0_get_response:
      type: object
      properties:
        adidDesc:
          title: Description
          type: string
        additionalId:
          title: Additional Identification
          maxLength: 50
          type: string
          description: "Lineage reference object : GORADID_ADDITIONAL_ID"
          x-lineageReferenceObject: GORADID_ADDITIONAL_ID
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GORADID_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GORADID_ACTIVITY_DATE
        adidCode:
          title: ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GORADID_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GORADID_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        userId:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : GORADID_USER_ID"
          x-lineageReferenceObject: GORADID_USER_ID
      x-lineageReferenceObject: goradid
    identification-additional-identification-2.0.0_qapi_post_request:
      type: object
      properties:
        additionalId:
          title: Additional Identification
          maxLength: 50
          type: string
          description: "Lineage reference object : GORADID_ADDITIONAL_ID"
          x-lineageReferenceObject: GORADID_ADDITIONAL_ID
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GORADID_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GORADID_ACTIVITY_DATE
        adidCode:
          title: ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GORADID_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GORADID_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        userId:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : GORADID_USER_ID"
          x-lineageReferenceObject: GORADID_USER_ID
      x-lineageReferenceObject: GORADID
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
