openapi: 3.0.0
info:
  title: activity-category-codes
  description: API for STVACCG administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: STVACCG
  x-source-domain: Student
  x-source-title: Telephone Type Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/activity-category-codes:
    post:
      tags:
        - activity-category-codes
      summary: Creates a new resource in STVACCG
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v2.0.0+json:
            schema:
              $ref: "#/components/schemas/activity-category-codes-2.0.0_post_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v2.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/activity-category-codes-2.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/activity-category-codes: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    activity-category-codes-2.0.0_post_request:
      type: object
      properties:
        stvaccg:
          type: array
          items:
            required:
              - code
              - desc
            type: object
            properties:
              code:
                title: Code
                maxLength: 5
                type: string
                description: "Lineage reference object : STVACCG_CODE"
                x-lineageReferenceObject: STVACCG_CODE
              desc:
                title: Description
                maxLength: 30
                type: string
                description: "Lineage reference object : STVACCG_DESC"
                x-lineageReferenceObject: STVACCG_DESC
            x-lineageReferenceObject: STVACCG
    activity-category-codes-2.0.0_post_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : STVACCG_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVACCG_ACTIVITY_DATE
        code:
          title: Code
          maxLength: 5
          type: string
          description: "Lineage reference object : STVACCG_CODE"
          x-lineageReferenceObject: STVACCG_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVACCG_DESC"
          x-lineageReferenceObject: STVACCG_DESC
      x-lineageReferenceObject: stvaccg
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
