openapi: 3.0.0
info:
  title: system-data-rules
  description: API for FTVSDAT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FTVSDAT
  x-source-domain: Finance
  x-source-title: System Data Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/system-data-rules:
    get:
      tags:
        - system-data-rules
      summary: Return resources from FTVSDAT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: coasCode
          in: query
          description: COA
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_COAS_CODE
        - name: codeLevel
          in: query
          description: Level
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_CODE_LEVEL
        - name: data
          in: query
          description: Data
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_DATA
        - name: effDate
          in: query
          description: Effective Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_EFF_DATE
        - name: sdatCodeAttr
          in: query
          description: Attribute
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ATTR
        - name: sdatCodeEntity
          in: query
          description: Entity
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ENTITY
        - name: sdatCodeOpt1
          in: query
          description: Option 1
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_1
        - name: sdatCodeOpt2
          in: query
          description: Option 2
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_2
        - name: shortTitle
          in: query
          description: Short Title
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_SHORT_TITLE
        - name: statusInd
          in: query
          description: Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_STATUS_IND
        - name: termDate
          in: query
          description: Termination Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSDAT_TERM_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/system-data-rules-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/system-data-rules:
    post:
      tags:
        - system-data-rules QAPI (Query by POST)
      summary: Return resources from FTVSDAT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/system-data-rules-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/system-data-rules-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    system-data-rules-1.0.0_get_request:
      type: object
      properties:
        effDate:
          title: Effective Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FTVSDAT_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVSDAT_EFF_DATE
        data:
          title: Data
          maxLength: 15
          type: string
          description: "Lineage reference object : FTVSDAT_DATA"
          x-lineageReferenceObject: FTVSDAT_DATA
        sdatCodeOpt2:
          title: Option 2
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_OPT_2"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_2
        codeLevel:
          title: Level
          maxLength: 2
          type: number
          description: "Lineage reference object : FTVSDAT_CODE_LEVEL"
          x-lineageReferenceObject: FTVSDAT_CODE_LEVEL
        sdatCodeEntity:
          title: Entity
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_ENTITY"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ENTITY
        statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVSDAT_STATUS_IND"
          x-lineageReferenceObject: FTVSDAT_STATUS_IND
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVSDAT_COAS_CODE"
          x-lineageReferenceObject: FTVSDAT_COAS_CODE
        sdatCodeOpt1:
          title: Option 1
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_OPT_1"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_1
        shortTitle:
          title: Short Title
          maxLength: 20
          type: string
          description: "Lineage reference object : FTVSDAT_SHORT_TITLE"
          x-lineageReferenceObject: FTVSDAT_SHORT_TITLE
        sdatCodeAttr:
          title: Attribute
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_ATTR"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ATTR
        termDate:
          title: Termination Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FTVSDAT_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVSDAT_TERM_DATE
      x-lineageReferenceObject: FTVSDAT
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    system-data-rules-1.0.0_get_response:
      type: object
      properties:
        effDate:
          title: Effective Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FTVSDAT_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVSDAT_EFF_DATE
        data:
          title: Data
          maxLength: 15
          type: string
          description: "Lineage reference object : FTVSDAT_DATA"
          x-lineageReferenceObject: FTVSDAT_DATA
        sdatCodeOpt2:
          title: Option 2
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_OPT_2"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_2
        codeLevel:
          title: Level
          maxLength: 2
          type: number
          description: "Lineage reference object : FTVSDAT_CODE_LEVEL"
          x-lineageReferenceObject: FTVSDAT_CODE_LEVEL
        sdatCodeEntity:
          title: Entity
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_ENTITY"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ENTITY
        statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVSDAT_STATUS_IND"
          x-lineageReferenceObject: FTVSDAT_STATUS_IND
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVSDAT_COAS_CODE"
          x-lineageReferenceObject: FTVSDAT_COAS_CODE
        sdatCodeOpt1:
          title: Option 1
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_OPT_1"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_1
        shortTitle:
          title: Short Title
          maxLength: 20
          type: string
          description: "Lineage reference object : FTVSDAT_SHORT_TITLE"
          x-lineageReferenceObject: FTVSDAT_SHORT_TITLE
        sdatCodeAttr:
          title: Attribute
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_ATTR"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ATTR
        termDate:
          title: Termination Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FTVSDAT_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVSDAT_TERM_DATE
      x-lineageReferenceObject: ftvsdat
    system-data-rules-1.0.0_qapi_post:
      type: object
      properties:
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVSDAT_COAS_CODE"
          x-lineageReferenceObject: FTVSDAT_COAS_CODE
        codeLevel:
          title: Level
          maxLength: 2
          type: number
          description: "Lineage reference object : FTVSDAT_CODE_LEVEL"
          x-lineageReferenceObject: FTVSDAT_CODE_LEVEL
        data:
          title: Data
          maxLength: 15
          type: string
          description: "Lineage reference object : FTVSDAT_DATA"
          x-lineageReferenceObject: FTVSDAT_DATA
        effDate:
          title: Effective Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FTVSDAT_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVSDAT_EFF_DATE
        sdatCodeAttr:
          title: Attribute
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_ATTR"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ATTR
        sdatCodeEntity:
          title: Entity
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_ENTITY"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_ENTITY
        sdatCodeOpt1:
          title: Option 1
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_OPT_1"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_1
        sdatCodeOpt2:
          title: Option 2
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSDAT_SDAT_CODE_OPT_2"
          x-lineageReferenceObject: FTVSDAT_SDAT_CODE_OPT_2
        shortTitle:
          title: Short Title
          maxLength: 20
          type: string
          description: "Lineage reference object : FTVSDAT_SHORT_TITLE"
          x-lineageReferenceObject: FTVSDAT_SHORT_TITLE
        statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVSDAT_STATUS_IND"
          x-lineageReferenceObject: FTVSDAT_STATUS_IND
        termDate:
          title: Termination Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FTVSDAT_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVSDAT_TERM_DATE
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
