openapi: 3.0.0
info:
  title: general-person-identification-alternate
  description: API for SPAIDEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SPAIDEN
  x-source-domain: Student
  x-source-title: General Person Identification
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/general-person-identification-alternate:
    get:
      tags:
        - general-person-identification-alternate
      summary: Return resources from SPAIDEN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: spridenId
          in: query
          description: ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_ID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-person-identification-alternate-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/general-person-identification-alternate:
    post:
      tags:
        - general-person-identification-alternate QAPI (Query by POST)
      summary: Return resources from SPAIDEN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-person-identification-alternate-1.0.0_get_r\
                equest"
            example:
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-person-identification-alternate-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    general-person-identification-alternate-1.0.0_get_request:
      type: object
      properties:
        spridenId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: SPRIDEN_CURRENT
    general-person-identification-alternate-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        spridenId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    general-person-identification-alternate-1.0.0_get_response:
      type: object
      properties:
        spridenActivityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SPRIDEN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRIDEN_ACTIVITY_DATE
        spridenCreateUser:
          title: Create User
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_CREATE_USER"
          x-lineageReferenceObject: SPRIDEN_CREATE_USER
        spridenOrigin:
          title: Origin
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_ORIGIN"
          x-lineageReferenceObject: SPRIDEN_ORIGIN
        spridenMi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
        previousNtypDesc:
          type: string
        spridenId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        spridenFirstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        spridenChangeInd:
          title: Change Type
          maxLength: 1
          type: string
          description: "Lineage reference object : SPRIDEN_CHANGE_IND"
          x-lineageReferenceObject: SPRIDEN_CHANGE_IND
        spridenUser:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_USER"
          x-lineageReferenceObject: SPRIDEN_USER
        spridenLastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        spridenNtypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage
            reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        spridenSurnamePrefix:
          title: Last Name Prefix
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_SURNAME_PREFIX"
          x-lineageReferenceObject: SPRIDEN_SURNAME_PREFIX
        spridenCreateDate:
          title: Create Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SPRIDEN_CREATE_DATE"
          format: date-time
          x-lineageReferenceObject: SPRIDEN_CREATE_DATE
      x-lineageReferenceObject: spriden_previous
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
