openapi: 3.0.0
info:
  title: ca-education-goals
  description: This API returns and does the basic operations for resources from SVREDGL
  version: 1.0.0-beta
  x-source-system: banner
  x-api-type: erp
  x-audience: all
  x-release-status: beta
  x-source-domain: Student
  x-source-title: CA Educational Goal
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-education-goals:
    post:
      tags:
        - ca-education-goals
      summary: Create a ca education goal with given data in the request body.
      description: Create a ca education goal with given data in the request body.
      requestBody:
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              $ref: '#/components/schemas/ca-education-goals-v1_post_request'
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response.
              required: true
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                $ref: '#/components/schemas/ca-education-goals-v1_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client's preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_CA_EDUCATION_GOALS
  /api/ca-education-goals/{termCode}{districtCode}:
    get:
      summary: Provide a ca education goal record for the given studentId, effectiveTermCode and districtIdCode.
      description: Provide a ca education goal record for the given studentId, effectiveTermCode and districtIdCode.
      tags:
        - ca-education-goals
      parameters:
        - name: studentId
          in: query
          required: false
          description: The student's ID used to define the MIS Success and Support Services Historical Data.
          schema:
            type: string
        - name: termCode
          in: path
          required: true
          description: Effective Term Code used to define the MIS Success and Support Services Historical Data.
          schema:
            type: string
        - name: districtCode
          in: path
          required: true
          description: District Code used to define the MIS Success and Support Services Historical Data.
          schema:
            type: string
      responses:
       '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response.
              required: true
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                $ref: '#/components/schemas/ca-education-goals-get_response'
       '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '401':
          description: Failure. Unauthorized.
       '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
       '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '406':
          description: Failure. Not Acceptable. Unable to generate any of the client's preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_CA_EDUCATION_GOALS
components:
  schemas:
    ca-education-goals-v1_post_request:
      type: object
      properties:
        termCode:
          "title": "effectiveTermCode"
          "description": "Effective Term Code used to define the MIS Success and Support Services Historical Data."
          "type": string
          "maxLength": 6
          "x-lineageReferenceObject": SVREDGL.SVREDGL_EFF_TERM
        districtCode:
          "title": "districtIdCode"
          "description": "The district or division associated with a student."
          "type": string
          "maxLength": 3
          "x-lineageReferenceObject": SVREDGL.SVREDGL_DICD_CODE
        data:
          "title": "Historical Data Details"
          "description": "Historical Data Details"
          "type": array
          "items": 
            "type": object
            "properties":
              studentId:
                "title": "This field defines the identification number used to access person on-line."
                "description": "The internal system student identification number."
                "type": string
                "maxLength": 9
                "x-lineageReferenceObject": SPRIDEN.SPRIDEN_ID
              educationGoals:
                "title": "Student Goal Code Details"
                "description": "Student Goal Code Details"
                "type": array
                "items": 
                  "type": object
                  "properties":
                    goalCode:
                      "title": "goalCode"
                      "description": "Student Goal Code. Validated by STVGOAL_CODE."
                      "type": string
                      "maxLength": 4
                      "x-lineageReferenceObject": SVREDGL.SVREDGL_GOAL_CODE
                    goalType:
                      "title": "goalType"
                      "description": "Code to identify the type of Student Goal Code. P = Primary, O = Other."
                      "type": string
                      "maxLength": 1
                      "x-lineageReferenceObject": SVREDGL.SVREDGL_GOAL_OPT
      required:
        - studentId
        - termCode
        - districtCode
    ca-education-goals-v1_response:
      type: object
      properties:
        termCode:
          "title": "effectiveTermCode"
          "description": "Effective Term Code used to define the MIS Success and Support Services Historical Data."
          "type": string
          "maxLength": 6
          "x-lineageReferenceObject": SVREDGL.SVREDGL_EFF_TERM
        districtCode:
          "title": "districtIdCode"
          "description": "The district or division associated with a student."
          "type": string
          "maxLength": 3
          "x-lineageReferenceObject": SVREDGL.SVREDGL_DICD_CODE
        dataGoals:
          "title": "Historical Data Details"
          "description": "Historical Data Details"
          "type": array
          "items": 
            "type": object
            "properties":
              studentId:
                "title": "This field defines the identification number used to access person on-line."
                "description": "The internal system student identification number."
                "type": string
                "maxLength": 9
                "x-lineageReferenceObject": SPRIDEN.SPRIDEN_ID
              educationGoals:
                "title": "Student Goal Code Details"
                "description": "Student Goal Code Details"
                "type": array
                "items": 
                  "type": object
                  "properties":
                    goalCode:
                      "title": "goalCode"
                      "description": "Student Goal Code. Validated by STVGOAL_CODE."
                      "type": string
                      "maxLength": 4
                      "x-lineageReferenceObject": SVREDGL.SVREDGL_GOAL_CODE
                    goalDescription:
                      "title": "Description of student goal code"
                      "description": "Description of student goal code."
                      "type": string
                      "maxLength": 30
                      "x-lineageReferenceObject": STVGOAL.STVGOAL_DESC
                      "x-lineageLookupReferenceObject": STVGOAL
                    goalType:
                      "title": "goalType"
                      "description": "Code to identify the type of Student Goal Code. P = Primary, O = Other."
                      "type": string
                      "maxLength": 1
                      "x-lineageReferenceObject": SVREDGL.SVREDGL_GOAL_OPT
              message:
                "title": "Response result"
                "description": "Response result"
                "type": string
      required:
        - studentId
        - termCode
        - districtCode
    ca-education-goals-get_response:
      type: object
      properties:
        termCode:
          "title": "effectiveTermCode"
          "description": "Effective Term Code used to define the MIS Success and Support Services Historical Data."
          "type": string
          "maxLength": 6
          "x-lineageReferenceObject": SVREDGL.SVREDGL_EFF_TERM
        districtCode:
          "title": "districtIdCode"
          "description": "The district or division associated with a student."
          "type": string
          "maxLength": 3
          "x-lineageReferenceObject": SVREDGL.SVREDGL_DICD_CODE
        dataGoals:
          "title": "Historical Data Details"
          "description": "Historical Data Details"
          "type": array
          "items": 
            "type": object
            "properties":
              studentId:
                "title": "This field defines the identification number used to access person on-line."
                "description": "The internal system student identification number."
                "type": string
                "maxLength": 9
                "x-lineageReferenceObject": SPRIDEN.SPRIDEN_ID
              educationGoals:
                "title": "Student Goal Code Details"
                "description": "Student Goal Code Details"
                "type": array
                "items": 
                  "type": object
                  "properties":
                    goalCode:
                      "title": "goalCode"
                      "description": "Student Goal Code. Validated by STVGOAL_CODE."
                      "type": string
                      "maxLength": 4
                      "x-lineageReferenceObject": SVREDGL.SVREDGL_GOAL_CODE
                    goalDescription:
                      "title": "Description of student goal code"
                      "description": "Description of student goal code."
                      "type": string
                      "maxLength": 30
                      "x-lineageReferenceObject": STVGOAL.STVGOAL_DESC
                      "x-lineageLookupReferenceObject": STVGOAL
                    goalType:
                      "title": "goalType"
                      "description": "Code to identify the type of Student Goal Code. P = Primary, O = Other."
                      "type": string
                      "maxLength": 1
                      "x-lineageReferenceObject": SVREDGL.SVREDGL_GOAL_OPT
      required:
        - studentId
        - termCode
        - districtCode
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic