openapi: 3.0.0
info:
  title: flexible-benefits-period-rule
  description: API for PTRFLEX administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PTRFLEX
  x-source-domain: Human Resources
  x-source-title: Flexible Benefits Period Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/flexible-benefits-period-rule:
    get:
      tags:
        - flexible-benefits-period-rule
      summary: Return resources from PTRFLEX
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: curPeriod
          in: query
          description: Current Benefit Period
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFLEX_CUR_PERIOD
        - name: newPeriod
          in: query
          description: Ending Benefit Period
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFLEX_NEW_PERIOD
        - name: calcFactor
          in: query
          description: Calculation Factor
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFLEX_CALC_FACTOR
        - name: bdcaOvgCode
          in: query
          description: Default Overage
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFLEX_BDCA_OVG_CODE
        - name: bdcaUndgCode
          in: query
          description: Default Underage
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFLEX_BDCA_UNDG_CODE
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFLEX_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/flexible-benefits-period-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/flexible-benefits-period-rule:
    post:
      tags:
        - flexible-benefits-period-rule QAPI (Query by POST)
      summary: Return resources from PTRFLEX
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/flexible-benefits-period-rule-1.0.0_get_request"
            example:
              curPeriod: 2021-01-01
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/flexible-benefits-period-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    flexible-benefits-period-rule-1.0.0_qapi_post:
      type: object
      properties:
        curPeriod:
          title: Current Benefit Period
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_CUR_PERIOD"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_CUR_PERIOD
        newPeriod:
          title: Ending Benefit Period
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_NEW_PERIOD"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_NEW_PERIOD
        calcFactor:
          title: Calculation Factor
          maxLength: 2
          type: string
          description: "Lineage reference object : PTRFLEX_CALC_FACTOR"
          x-lineageReferenceObject: PTRFLEX_CALC_FACTOR
        bdcaOvgCode:
          title: Default Overage
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFLEX_BDCA_OVG_CODE"
          x-lineageReferenceObject: PTRFLEX_BDCA_OVG_CODE
        bdcaUndgCode:
          title: Default Underage
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFLEX_BDCA_UNDG_CODE"
          x-lineageReferenceObject: PTRFLEX_BDCA_UNDG_CODE
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_ACTIVITY_DATE
    flexible-benefits-period-rule-1.0.0_get_response:
      required:
        - bdcaOvgCode
        - bdcaUndgCode
        - calcFactor
        - curPeriod
        - newPeriod
      type: object
      properties:
        bdcaUndgDesc:
          type: string
        calcFactor:
          title: Calculation Factor
          maxLength: 2
          type: string
          description: "Lineage reference object : PTRFLEX_CALC_FACTOR"
          x-lineageReferenceObject: PTRFLEX_CALC_FACTOR
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_ACTIVITY_DATE
        bdcaOvgCode:
          title: Default Overage
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFLEX_BDCA_OVG_CODE"
          x-lineageReferenceObject: PTRFLEX_BDCA_OVG_CODE
        bdcaUndgCode:
          title: Default Underage
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFLEX_BDCA_UNDG_CODE"
          x-lineageReferenceObject: PTRFLEX_BDCA_UNDG_CODE
        bdcaOvgDesc:
          type: string
        newPeriod:
          title: Ending Benefit Period
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_NEW_PERIOD"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_NEW_PERIOD
        curPeriod:
          title: Current Benefit Period
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_CUR_PERIOD"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_CUR_PERIOD
      x-lineageReferenceObject: ptrflex
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    flexible-benefits-period-rule-1.0.0_get_request:
      required:
        - curPeriod
        - newPeriod
        - calcFactor
        - bdcaOvgCode
        - bdcaUndgCode
      type: object
      properties:
        calcFactor:
          title: Calculation Factor
          maxLength: 2
          type: string
          description: "Lineage reference object : PTRFLEX_CALC_FACTOR"
          x-lineageReferenceObject: PTRFLEX_CALC_FACTOR
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_ACTIVITY_DATE
        bdcaOvgCode:
          title: Default Overage
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFLEX_BDCA_OVG_CODE"
          x-lineageReferenceObject: PTRFLEX_BDCA_OVG_CODE
        bdcaUndgCode:
          title: Default Underage
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFLEX_BDCA_UNDG_CODE"
          x-lineageReferenceObject: PTRFLEX_BDCA_UNDG_CODE
        newPeriod:
          title: Ending Benefit Period
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_NEW_PERIOD"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_NEW_PERIOD
        curPeriod:
          title: Current Benefit Period
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRFLEX_CUR_PERIOD"
          format: date-time
          x-lineageReferenceObject: PTRFLEX_CUR_PERIOD
      x-lineageReferenceObject: PTRFLEX
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
