openapi: 3.0.0
info:
  title: applicant-entry-by-requisition-or-position-status-log
  description: API for PAAAPOS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: PAAAPOS
  x-source-domain: Human Resources
  x-source-title: Applicant Entry by Requisition/Position
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-entry-by-requisition-or-position-status-log:
    get:
      tags:
        - applicant-entry-by-requisition-or-position-status-log
      summary: Return resources from PAAAPOS
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: reqNo
          in: query
          required: false
          schema:
            type: string
        - name: posn
          in: query
          required: false
          schema:
            type: string
        - name: pclsCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-entry-by-requisition-or-position-status-l\
                    og-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-entry-by-requisition-or-position-status-log:
    post:
      tags:
        - applicant-entry-by-requisition-or-position-status-log QAPI (Query by
          POST)
      summary: Return resources from PAAAPOS
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-entry-by-requisition-or-position-status-l\
                og-1.0.0_get_request"
            example:
              reqNo: 100
              pclsCode: AFP01
              posn: A00001
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-entry-by-requisition-or-position-status-l\
                    og-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    applicant-entry-by-requisition-or-position-status-log-1.0.0_get_request:
      type: object
      properties:
        reqNo:
          title: Requisition Number
          maxLength: 10
          type: string
          description: "Lineage reference object : reqNo"
          x-lineageReferenceObject: reqNo
        pclsCode:
          title: Position Class
          maxLength: 5
          type: string
          description: "Lineage reference object : pclsCode"
          x-lineageReferenceObject: pclsCode
        posn:
          title: Position Number
          maxLength: 6
          type: string
          description: "Lineage reference object : posn"
          x-lineageReferenceObject: posn
      x-lineageReferenceObject: KEY_BLOCK
    applicant-entry-by-requisition-or-position-status-log-1.0.0_qapi_post:
      type: object
      properties:
        reqNo:
          type: string
        posn:
          type: string
        pclsCode:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    applicant-entry-by-requisition-or-position-status-log-1.0.0_get_response:
      type: object
      properties:
        pabappl:
          type: array
          items:
            required:
              - currAppsDate
              - asrcCode
              - date
            type: object
            properties:
              date:
                title: Application Date
                maxLength: 11
                type: string
                description: "Lineage reference object : PABAPPL_DATE"
                format: date-time
                x-lineageReferenceObject: PABAPPL_DATE
              desiredHourly:
                title: Desired Hourly Rate
                maxLength: 14
                type: number
                description: "Lineage reference object : PABAPPL_DESIRED_HOURLY"
                x-lineageReferenceObject: PABAPPL_DESIRED_HOURLY
              prevEmpInd:
                title: Previous Employee
                maxLength: 1
                type: string
              asrcCode:
                title: Source
                maxLength: 30
                type: string
                description: "Lineage reference object : PABAPPL_ASRC_CODE, Lookup lineage
                  reference object : ptvasrc"
                x-lineageReferenceObject: PABAPPL_ASRC_CODE
                x-lineageLookupReferenceObject: ptvasrc
              esklDesc:
                maxLength: 31
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : PABAPPL_USER_ID"
                x-lineageReferenceObject: PABAPPL_USER_ID
              asrcDesc:
                type: string
              desiredSalary:
                title: Desired Salary
                maxLength: 14
                type: number
                description: "Lineage reference object : PABAPPL_DESIRED_SALARY"
                x-lineageReferenceObject: PABAPPL_DESIRED_SALARY
              currAppsCode:
                title: Current Status
                maxLength: 2
                type: string
              currAppsDate:
                title: Date
                maxLength: 11
                type: string
                format: date-time
              currComment:
                title: Comment
                maxLength: 32767
                type: string
              name3:
                maxLength: 0
                type: string
              activityDate:
                maxLength: 11
                type: string
                description: "Lineage reference object : PABAPPL_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: PABAPPL_ACTIVITY_DATE
              currAppsDesc:
                maxLength: 30
                type: string
              id2:
                title: Applicant ID
                maxLength: 0
                type: string
              esklCode:
                title: EEO Skill
                maxLength: 2
                type: string
                description: "Lineage reference object : PABAPPL_ESKL_CODE"
                x-lineageReferenceObject: PABAPPL_ESKL_CODE
              dispDesc:
                title: Disposition
                maxLength: 30
                type: string
              nname:
                maxLength: 230
                type: string
              id3:
                title: Applicant ID
                maxLength: 0
                type: string
              empInd:
                title: Current Employee
                maxLength: 1
                type: string
              id:
                title: Applicant ID
                maxLength: 9
                type: string
              name2:
                maxLength: 0
                type: string
              fullPartInd:
                title: Full or Part or No Preference
                maxLength: 1
                type: string
                description: "Lineage reference object : PABAPPL_FULL_PART_IND"
                x-lineageReferenceObject: PABAPPL_FULL_PART_IND
            x-lineageReferenceObject: pabappl
        parapst:
          type: array
          items:
            required:
              - appsDate
              - seqNo
            type: object
            properties:
              appsCode:
                title: Status
                maxLength: 2
                type: string
                description: "Lineage reference object : PARAPST_APPS_CODE"
                x-lineageReferenceObject: PARAPST_APPS_CODE
              activityDate:
                maxLength: 11
                type: string
                description: "Lineage reference object : PARAPST_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: PARAPST_ACTIVITY_DATE
              seqNo:
                title: Sequence Number
                maxLength: 3
                type: string
                description: "Lineage reference object : PARAPST_SEQ_NO"
                x-lineageReferenceObject: PARAPST_SEQ_NO
              comment:
                title: Comment
                maxLength: 32767
                type: string
                description: "Lineage reference object : PARAPST_COMMENT"
                x-lineageReferenceObject: PARAPST_COMMENT
              appsDesc:
                maxLength: 30
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : PARAPST_USER_ID"
                x-lineageReferenceObject: PARAPST_USER_ID
              appsDate:
                title: Status Date
                maxLength: 11
                type: string
                description: "Lineage reference object : PARAPST_APPS_DATE"
                format: date-time
                x-lineageReferenceObject: PARAPST_APPS_DATE
            x-lineageReferenceObject: parapst
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
