openapi: 3.0.0
info:
  title: term-control-structured-registration
  description: API for SOATERM administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SOATERM
  x-source-domain: Student
  x-source-title: Term Control
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/term-control-structured-registration:
    get:
      tags:
        - term-control-structured-registration
      summary: Return resources from SOATERM
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: xxxxxxxTermCode
          in: query
          required: false
          schema:
            type: string
        - name: copyBtn
          in: query
          required: false
          schema:
            type: string
        - name: crnOneup
          in: query
          required: false
          schema:
            type: string
        - name: ptrmCode
          in: query
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/term-control-structured-registration-1.0.0_get_resp\
                    onse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/term-control-structured-registration:
    post:
      tags:
        - term-control-structured-registration QAPI (Query by POST)
      summary: Return resources from SOATERM
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/term-control-structured-registration-1.0.0_get_requ\
                est"
            example:
              xxxxxxxTermCode: 201410
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/term-control-structured-registration-1.0.0_get_resp\
                    onse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    term-control-structured-registration-1.0.0_get_request:
      required:
        - crnOneup
        - ptrmCode
        - startDate
      type: object
      properties:
        ptrmCode:
          title: Part of Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBPTRM_PTRM_CODE, Lookup lineage
            reference object : stvptrm"
          x-lineageReferenceObject: SOBPTRM_PTRM_CODE
          x-lineageLookupReferenceObject: stvptrm
        xxxxxxxTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : xxxxxxxTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: xxxxxxxTermCode
          x-lineageLookupReferenceObject: stvterm
        crnOneup:
          title: CRN Starting Sequence Number
          maxLength: 5
          type: number
          description: "Lineage reference object : SOBTERM_CRN_ONEUP"
          x-lineageReferenceObject: SOBTERM_CRN_ONEUP
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORFTRM_START_DATE"
          format: date-time
          x-lineageReferenceObject: SORFTRM_START_DATE
      x-lineageReferenceObject: SORFTRM
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    term-control-structured-registration-1.0.0_qapi_post:
      type: object
      properties:
        xxxxxxxTermCode:
          type: string
        copyBtn:
          type: string
        crnOneup:
          type: string
        ptrmCode:
          type: string
        startDate:
          type: string
    term-control-structured-registration-1.0.0_get_response:
      type: object
      properties:
        stvprntLinksDesc:
          type: string
        inProgGrdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_IN_PROG_GRDE_IND"
          x-lineageReferenceObject: SOBSTRG_IN_PROG_GRDE_IND
        prntCodeTtext:
          maxLength: 6
          type: string
          description: "Lineage reference object : SOBSTRG_PRNT_CODE_TTEXT, Lookup lineage
            reference object : stvprnt"
          x-lineageReferenceObject: SOBSTRG_PRNT_CODE_TTEXT
          x-lineageLookupReferenceObject: stvprnt
        errorCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_ERROR_CDE"
          x-lineageReferenceObject: SOBSTRG_ERROR_CDE
        prntCodeLinks:
          maxLength: 6
          type: string
          description: "Lineage reference object : SOBSTRG_PRNT_CODE_LINKS, Lookup lineage
            reference object : stvprnt"
          x-lineageReferenceObject: SOBSTRG_PRNT_CODE_LINKS
          x-lineageLookupReferenceObject: stvprnt
        userId:
          type: string
          description: "Lineage reference object : SOBSTRG_USER_ID"
          x-lineageReferenceObject: SOBSTRG_USER_ID
        optionalRuleKey:
          maxLength: 10
          type: string
          description: "Lineage reference object : SOBSTRG_OPTIONAL_RULE_KEY"
          x-lineageReferenceObject: SOBSTRG_OPTIONAL_RULE_KEY
        stvrestDesc:
          type: string
        activityDate:
          type: string
          description: "Lineage reference object : SOBSTRG_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SOBSTRG_ACTIVITY_DATE
        acadHistCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_ACAD_HIST_CDE"
          x-lineageReferenceObject: SOBSTRG_ACAD_HIST_CDE
        electiveActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_ELECTIVE_ACTIVE_IND"
          x-lineageReferenceObject: SOBSTRG_ELECTIVE_ACTIVE_IND
        electiveRuleKey:
          maxLength: 10
          type: string
          description: "Lineage reference object : SOBSTRG_ELECTIVE_RULE_KEY"
          x-lineageReferenceObject: SOBSTRG_ELECTIVE_RULE_KEY
        stvprntTtextDesc:
          type: string
        dataOrigin:
          type: string
          description: "Lineage reference object : SOBSTRG_DATA_ORIGIN"
          x-lineageReferenceObject: SOBSTRG_DATA_ORIGIN
        inProgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_IN_PROG_IND"
          x-lineageReferenceObject: SOBSTRG_IN_PROG_IND
        restCode:
          maxLength: 4
          type: string
          description: "Lineage reference object : SOBSTRG_REST_CODE, Lookup lineage
            reference object : stvrest"
          x-lineageReferenceObject: SOBSTRG_REST_CODE
          x-lineageLookupReferenceObject: stvrest
        mandatoryRuleKey:
          maxLength: 10
          type: string
          description: "Lineage reference object : SOBSTRG_MANDATORY_RULE_KEY"
          x-lineageReferenceObject: SOBSTRG_MANDATORY_RULE_KEY
        mandatoryActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_MANDATORY_ACTIVE_IND"
          x-lineageReferenceObject: SOBSTRG_MANDATORY_ACTIVE_IND
        optionalActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBSTRG_OPTIONAL_ACTIVE_IND"
          x-lineageReferenceObject: SOBSTRG_OPTIONAL_ACTIVE_IND
        termCode:
          type: string
          description: "Lineage reference object : SOBSTRG_TERM_CODE"
          x-lineageReferenceObject: SOBSTRG_TERM_CODE
      x-lineageReferenceObject: sobstrg
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
