openapi: 3.0.0
info:
  title: compliance-results-inquiry
  description: API for SMICRLT administrative page
  version: 0.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: SMICRLT
  x-source-domain: Student
  x-source-title: Compliance Results Inquiry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/compliance-results-inquiry:
    get:
      tags:
        - compliance-results-inquiry
      summary: Return resources from SMICRLT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: requestNo
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/compliance-results-inquiry-0.1.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/compliance-results-inquiry:
    post:
      tags:
        - compliance-results-inquiry QAPI (Query by POST)
      summary: Return resources from SMICRLT
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/compliance-results-inquiry-0.1.0_get_request"
            example:
              id: SLSAP200
              requestNo: 20
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/compliance-results-inquiry-0.1.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    compliance-results-inquiry-0.1.0_get_response:
      type: object
      properties:
        programDesc:
          type: string
        origDesc:
          type: string
        origName:
          type: string
        program:
          title: Program
          maxLength: 12
          type: string
          description: "Lineage reference object : SMBPOGN_PROGRAM"
          x-lineageReferenceObject: SMBPOGN_PROGRAM
        termDesc:
          type: string
        termCodeCatlg:
          title: Catalog Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SMBPOGN_TERM_CODE_CATLG"
          x-lineageReferenceObject: SMBPOGN_TERM_CODE_CATLG
        origId:
          title: Originator ID
          maxLength: 9
          type: string
        origCode:
          title: Originator Code
          maxLength: 4
          type: string
      x-lineageReferenceObject: smbpogn
    compliance-results-inquiry-0.1.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        requestNo:
          type: string
    compliance-results-inquiry-0.1.0_get_request:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id, Lookup lineage reference object :
            spriden,smbpogn"
          x-lineageReferenceObject: id
          x-lineageLookupReferenceObject: spriden,smbpogn
        requestNo:
          title: Request Number
          maxLength: 30
          type: number
          description: "Lineage reference object : requestNo, Lookup lineage reference
            object : smbpogn"
          x-lineageReferenceObject: requestNo
          x-lineageLookupReferenceObject: smbpogn
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
