openapi: 3.0.0
info:
  title: invoice-credit-memo-list
  description: API for FAIINVL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FAIINVL
  x-source-domain: Finance
  x-source-title: Invoice/Credit Memo List
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/invoice-credit-memo-list:
    get:
      tags:
        - invoice-credit-memo-list
      summary: Return resources from FAIINVL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
        - name: code
          in: query
          description: Invoice
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_CODE
        - name: pohdCode
          in: query
          description: Purchase Order/Encumbrance
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_POHD_CODE
        - name: vendId
          in: query
          description: Vendor ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_VEND_ID
        - name: vendorName
          in: query
          description: Vendor Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_VENDOR_NAME
        - name: vendHoldRsnCode
          in: query
          description: Vendor Hold
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_VEND_HOLD_RSN_CODE
        - name: crMemoInd
          in: query
          description: Credit Memo
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_CR_MEMO_IND
        - name: completeInd
          in: query
          description: Completed
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_COMPLETE_IND
        - name: apprInd
          in: query
          description: Approved
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_APPR_IND
        - name: invoiceAmt
          in: query
          description: Invoice Total
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FAVINVQ_INVOICE_AMT
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/invoice-credit-memo-list-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/invoice-credit-memo-list:
    post:
      tags:
        - invoice-credit-memo-list QAPI (Query by POST)
      summary: Return resources from FAIINVL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/invoice-credit-memo-list-1.0.0_get_request"
            example:
              code: XT
              status: O
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/invoice-credit-memo-list-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    invoice-credit-memo-list-1.0.0_get_response:
      type: object
      properties:
        code:
          title: Invoice
          maxLength: 8
          type: string
          description: "Lineage reference object : FAVINVQ_CODE"
          x-lineageReferenceObject: FAVINVQ_CODE
        apprInd:
          title: Approved
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_APPR_IND"
          x-lineageReferenceObject: FAVINVQ_APPR_IND
        pohdCode:
          title: Purchase Order/Encumbrance
          maxLength: 8
          type: string
          description: "Lineage reference object : FAVINVQ_POHD_CODE"
          x-lineageReferenceObject: FAVINVQ_POHD_CODE
        vendHoldRsnCode:
          title: Vendor Hold
          maxLength: 4
          type: string
          description: "Lineage reference object : FAVINVQ_VEND_HOLD_RSN_CODE, Lookup
            lineage reference object : ftvhrsn"
          x-lineageReferenceObject: FAVINVQ_VEND_HOLD_RSN_CODE
          x-lineageLookupReferenceObject: ftvhrsn
        completeInd:
          title: Completed
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_COMPLETE_IND"
          x-lineageReferenceObject: FAVINVQ_COMPLETE_IND
        vendorName:
          title: Vendor Name
          maxLength: 230
          type: string
          description: "Lineage reference object : FAVINVQ_VENDOR_NAME"
          x-lineageReferenceObject: FAVINVQ_VENDOR_NAME
        vendId:
          title: Vendor ID
          maxLength: 9
          type: string
          description: "Lineage reference object : FAVINVQ_VEND_ID"
          x-lineageReferenceObject: FAVINVQ_VEND_ID
        crMemoInd:
          title: Credit Memo
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_CR_MEMO_IND"
          x-lineageReferenceObject: FAVINVQ_CR_MEMO_IND
        invoiceAmt:
          title: Invoice Total
          maxLength: 31
          type: number
          description: "Lineage reference object : FAVINVQ_INVOICE_AMT"
          x-lineageReferenceObject: FAVINVQ_INVOICE_AMT
      x-lineageReferenceObject: favinvq
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    invoice-credit-memo-list-1.0.0_get_request:
      type: object
      properties:
        code:
          title: Invoice
          maxLength: 8
          type: string
          description: "Lineage reference object : FAVINVQ_CODE"
          x-lineageReferenceObject: FAVINVQ_CODE
        apprInd:
          title: Approved
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_APPR_IND"
          x-lineageReferenceObject: FAVINVQ_APPR_IND
        pohdCode:
          title: Purchase Order/Encumbrance
          maxLength: 8
          type: string
          description: "Lineage reference object : FAVINVQ_POHD_CODE"
          x-lineageReferenceObject: FAVINVQ_POHD_CODE
        vendHoldRsnCode:
          title: Vendor Hold
          maxLength: 4
          type: string
          description: "Lineage reference object : FAVINVQ_VEND_HOLD_RSN_CODE, Lookup
            lineage reference object : ftvhrsn"
          x-lineageReferenceObject: FAVINVQ_VEND_HOLD_RSN_CODE
          x-lineageLookupReferenceObject: ftvhrsn
        completeInd:
          title: Completed
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_COMPLETE_IND"
          x-lineageReferenceObject: FAVINVQ_COMPLETE_IND
        vendorName:
          title: Vendor Name
          maxLength: 230
          type: string
          description: "Lineage reference object : FAVINVQ_VENDOR_NAME"
          x-lineageReferenceObject: FAVINVQ_VENDOR_NAME
        vendId:
          title: Vendor ID
          maxLength: 9
          type: string
          description: "Lineage reference object : FAVINVQ_VEND_ID"
          x-lineageReferenceObject: FAVINVQ_VEND_ID
        status:
          maxLength: 1
          type: string
          description: "Lineage reference object : invoiceStatus"
          x-lineageReferenceObject: invoiceStatus
        crMemoInd:
          title: Credit Memo
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_CR_MEMO_IND"
          x-lineageReferenceObject: FAVINVQ_CR_MEMO_IND
        invoiceAmt:
          title: Invoice Total
          maxLength: 31
          type: number
          description: "Lineage reference object : FAVINVQ_INVOICE_AMT"
          x-lineageReferenceObject: FAVINVQ_INVOICE_AMT
      x-lineageReferenceObject: FAVINVQ
    invoice-credit-memo-list-1.0.0_qapi_post:
      type: object
      properties:
        status:
          type: string
        code:
          title: Invoice
          maxLength: 8
          type: string
          description: "Lineage reference object : FAVINVQ_CODE"
          x-lineageReferenceObject: FAVINVQ_CODE
        pohdCode:
          title: Purchase Order/Encumbrance
          maxLength: 8
          type: string
          description: "Lineage reference object : FAVINVQ_POHD_CODE"
          x-lineageReferenceObject: FAVINVQ_POHD_CODE
        vendId:
          title: Vendor ID
          maxLength: 9
          type: string
          description: "Lineage reference object : FAVINVQ_VEND_ID"
          x-lineageReferenceObject: FAVINVQ_VEND_ID
        vendorName:
          title: Vendor Name
          maxLength: 230
          type: string
          description: "Lineage reference object : FAVINVQ_VENDOR_NAME"
          x-lineageReferenceObject: FAVINVQ_VENDOR_NAME
        vendHoldRsnCode:
          title: Vendor Hold
          maxLength: 4
          type: string
          description: "Lineage reference object : FAVINVQ_VEND_HOLD_RSN_CODE, Lookup
            lineage reference object : ftvhrsn"
          x-lineageReferenceObject: FAVINVQ_VEND_HOLD_RSN_CODE
          x-lineageLookupReferenceObject: ftvhrsn
        crMemoInd:
          title: Credit Memo
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_CR_MEMO_IND"
          x-lineageReferenceObject: FAVINVQ_CR_MEMO_IND
        completeInd:
          title: Completed
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_COMPLETE_IND"
          x-lineageReferenceObject: FAVINVQ_COMPLETE_IND
        apprInd:
          title: Approved
          maxLength: 1
          type: string
          description: "Lineage reference object : FAVINVQ_APPR_IND"
          x-lineageReferenceObject: FAVINVQ_APPR_IND
        invoiceAmt:
          title: Invoice Total
          maxLength: 31
          type: number
          description: "Lineage reference object : FAVINVQ_INVOICE_AMT"
          x-lineageReferenceObject: FAVINVQ_INVOICE_AMT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
