openapi: 3.0.0
info:
  title: curricula-summary-honors-departmental-honors
  description: >
    API for SHADEGR administrative page.<br> Allowed values for below fields are
    "Y" and null
     - transcPrtInd
     - commencePrtInd
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SHADEGR
  x-source-domain: Student
  x-source-title: Degree and Other Formal Awards
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/curricula-summary-honors-departmental-honors:
    put:
      tags:
        - curricula-summary-honors-departmental-honors
      summary: Updates an existing resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-departmental-honors-1.0.0_\
                put_request"
            example:
              commencePrtInd: Y
              transcPrtInd: Y
              id: HOSJ00002
              criteria.hondCode: H
              dgmrSeqNo: "1"
              criteria.commencePrtInd: Y
              hondCode: S
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-departmental-honors-1.0.0_\
                    put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - curricula-summary-honors-departmental-honors
      summary: Creates a new resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-departmental-honors-1.0.0_\
                post_request"
            example:
              SHRDGDH:
                - commencePrtInd: null
                  transcPrtInd: Y
                  hondCode: M
                - commencePrtInd: Y
                  transcPrtInd: null
                  hondCode: H
              id: HOSJ00002
              dgmrSeqNo: "1"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-departmental-honors-1.0.0_\
                    post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    delete:
      tags:
        - curricula-summary-honors-departmental-honors
      summary: Deletes an existing resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-departmental-honors-1.0.0_\
                delete_request"
            example:
              id: HOSJ00002
              dgmrSeqNo: "1"
              criteria.hondCode: L
              criteria.transcPrtInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-departmental-honors-1.0.0_\
                    delete_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/curricula-summary-honors-departmental-honors: {}
components:
  schemas:
    curricula-summary-honors-departmental-honors-1.0.0_put_request:
      required:
        - criteria.hondCode
      type: object
      properties:
        criteria.transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_TRANSC_PRT_IND
        commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_COMMENCE_PRT_IND
        transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_TRANSC_PRT_IND
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        criteria.hondCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGDH_HOND_CODE, Lookup lineage
            reference object : stvhond"
          x-lineageReferenceObject: SHRDGDH_HOND_CODE
          x-lineageLookupReferenceObject: stvhond
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
        criteria.commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_COMMENCE_PRT_IND
        hondCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGDH_HOND_CODE, Lookup lineage
            reference object : stvhond"
          x-lineageReferenceObject: SHRDGDH_HOND_CODE
          x-lineageLookupReferenceObject: stvhond
      x-lineageReferenceObject: SHRDGDH
    curricula-summary-honors-departmental-honors-1.0.0_delete_response:
      type: object
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    curricula-summary-honors-departmental-honors-1.0.0_delete_request:
      required:
        - criteria.hondCode
      type: object
      properties:
        criteria.transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_TRANSC_PRT_IND
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        criteria.hondCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGDH_HOND_CODE, Lookup lineage
            reference object : stvhond"
          x-lineageReferenceObject: SHRDGDH_HOND_CODE
          x-lineageLookupReferenceObject: stvhond
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
        criteria.commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_COMMENCE_PRT_IND
      x-lineageReferenceObject: SHRDGDH
    curricula-summary-honors-departmental-honors-1.0.0_post_request:
      required:
        - SHRDGDH
      type: object
      properties:
        SHRDGDH:
          type: array
          items:
            required:
              - hondCode
            type: object
            properties:
              commencePrtInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SHRDGDH_COMMENCE_PRT_IND"
                x-lineageReferenceObject: SHRDGDH_COMMENCE_PRT_IND
              transcPrtInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SHRDGDH_TRANSC_PRT_IND"
                x-lineageReferenceObject: SHRDGDH_TRANSC_PRT_IND
              hondCode:
                title: Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SHRDGDH_HOND_CODE, Lookup lineage
                  reference object : stvhond"
                x-lineageReferenceObject: SHRDGDH_HOND_CODE
                x-lineageLookupReferenceObject: stvhond
            x-lineageReferenceObject: SHRDGDH
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
      x-lineageReferenceObject: KEY_BLOCK
    curricula-summary-honors-departmental-honors-1.0.0_post_response:
      required:
        - hondCode
      type: object
      properties:
        stvhondDesc:
          title: Description
          type: string
        commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_COMMENCE_PRT_IND
        transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_TRANSC_PRT_IND
        hondCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGDH_HOND_CODE, Lookup lineage
            reference object : stvhond"
          x-lineageReferenceObject: SHRDGDH_HOND_CODE
          x-lineageLookupReferenceObject: stvhond
      x-lineageReferenceObject: shrdgdh
    curricula-summary-honors-departmental-honors-1.0.0_put_response:
      required:
        - hondCode
      type: object
      properties:
        stvhondDesc:
          title: Description
          type: string
        commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_COMMENCE_PRT_IND
        transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGDH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGDH_TRANSC_PRT_IND
        hondCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGDH_HOND_CODE, Lookup lineage
            reference object : stvhond"
          x-lineageReferenceObject: SHRDGDH_HOND_CODE
          x-lineageLookupReferenceObject: stvhond
      x-lineageReferenceObject: shrdgdh
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
