openapi: 3.0.0
info:
  title: catalog-of-federal-domestic-assistance-codes
  description: API for FRVCFDA administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FRVCFDA
  x-source-domain: Finance
  x-source-title: Catalog of Federal Domestic Assistance Codes
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/catalog-of-federal-domestic-assistance-codes:
    get:
      tags:
        - catalog-of-federal-domestic-assistance-codes
      summary: Return resources from FRVCFDA
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: displayAgcyCode
          in: query
          description: Agency
          required: false
          schema:
            type: string
        - name: cfdaCode
          in: query
          description: Assistance Listings Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVCFDA_CFDA_CODE
        - name: federalAgencyName
          in: query
          description: Federal Agency
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVCFDA_FEDERAL_AGENCY_NAME
        - name: status
          in: query
          description: Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVCFDA_STATUS
        - name: title
          in: query
          description: Assistance Listings Title
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVCFDA_TITLE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/catalog-of-federal-domestic-assistance-codes-1.0.0_\
                    get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/catalog-of-federal-domestic-assistance-codes:
    post:
      tags:
        - catalog-of-federal-domestic-assistance-codes QAPI (Query by POST)
      summary: Return resources from FRVCFDA
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/catalog-of-federal-domestic-assistance-codes-1.0.0_\
                get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/catalog-of-federal-domestic-assistance-codes-1.0.0_\
                    get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    catalog-of-federal-domestic-assistance-codes-1.0.0_get_request:
      required:
        - cfdaCode
        - federalAgencyName
        - status
        - title
      type: object
      properties:
        cfdaCode:
          title: Assistance Listings Code
          maxLength: 12
          type: string
          description: "Lineage reference object : FRVCFDA_CFDA_CODE"
          x-lineageReferenceObject: FRVCFDA_CFDA_CODE
        federalAgencyName:
          title: Federal Agency
          maxLength: 120
          type: string
          description: "Lineage reference object : FRVCFDA_FEDERAL_AGENCY_NAME"
          x-lineageReferenceObject: FRVCFDA_FEDERAL_AGENCY_NAME
        displayAgcyCode:
          title: Agency
          maxLength: 9
          type: string
        title:
          title: Assistance Listings Title
          maxLength: 240
          type: string
          description: "Lineage reference object : FRVCFDA_TITLE"
          x-lineageReferenceObject: FRVCFDA_TITLE
        status:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FRVCFDA_STATUS"
          x-lineageReferenceObject: FRVCFDA_STATUS
      x-lineageReferenceObject: FRVCFDA
    catalog-of-federal-domestic-assistance-codes-1.0.0_get_response:
      required:
        - cfdaCode
        - federalAgencyName
        - status
        - title
      type: object
      properties:
        cfdaCode:
          title: Assistance Listings Code
          maxLength: 12
          type: string
          description: "Lineage reference object : FRVCFDA_CFDA_CODE"
          x-lineageReferenceObject: FRVCFDA_CFDA_CODE
        federalAgencyName:
          title: Federal Agency
          maxLength: 120
          type: string
          description: "Lineage reference object : FRVCFDA_FEDERAL_AGENCY_NAME"
          x-lineageReferenceObject: FRVCFDA_FEDERAL_AGENCY_NAME
        displayAgcyCode:
          title: Agency
          maxLength: 9
          type: string
        title:
          title: Assistance Listings Title
          maxLength: 240
          type: string
          description: "Lineage reference object : FRVCFDA_TITLE"
          x-lineageReferenceObject: FRVCFDA_TITLE
        status:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FRVCFDA_STATUS"
          x-lineageReferenceObject: FRVCFDA_STATUS
      x-lineageReferenceObject: frvcfda
    catalog-of-federal-domestic-assistance-codes-1.0.0_qapi_post:
      type: object
      properties:
        displayAgcyCode:
          title: Agency
          maxLength: 9
          type: string
        cfdaCode:
          title: Assistance Listings Code
          maxLength: 12
          type: string
          description: "Lineage reference object : FRVCFDA_CFDA_CODE"
          x-lineageReferenceObject: FRVCFDA_CFDA_CODE
        federalAgencyName:
          title: Federal Agency
          maxLength: 120
          type: string
          description: "Lineage reference object : FRVCFDA_FEDERAL_AGENCY_NAME"
          x-lineageReferenceObject: FRVCFDA_FEDERAL_AGENCY_NAME
        status:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FRVCFDA_STATUS"
          x-lineageReferenceObject: FRVCFDA_STATUS
        title:
          title: Assistance Listings Title
          maxLength: 240
          type: string
          description: "Lineage reference object : FRVCFDA_TITLE"
          x-lineageReferenceObject: FRVCFDA_TITLE
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
