openapi: 3.0.0
info:
  title: applicant-gpa-types
  description: API for SOAGPAT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SOAGPAT
  x-source-domain: Student
  x-source-title: Applicant GPA Types
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-gpa-types:
    get:
      tags:
        - applicant-gpa-types
      summary: Return resources from SOAGPAT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckId
          in: query
          required: true
          schema:
            type: string
        - name: gpatCode
          in: query
          description: Sorgpat Gpat Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORGPAT_GPAT_CODE
        - name: gpaCode
          in: query
          required: false
          schema:
            type: string
        - name: plusminusInd
          in: query
          required: false
          schema:
            type: string
        - name: schoolCode
          in: query
          required: false
          schema:
            type: string
        - name: applNo
          in: query
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-gpa-types-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - applicant-gpa-types
      summary: Creates a new resource in SOAGPAT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-gpa-types-1.0.0_post_request"
            example:
              keyblckId: A00043337
              gpatCode: 5BCPM
              applNo: "3"
              termCode: "202201"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-gpa-types-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-gpa-types:
    post:
      tags:
        - applicant-gpa-types QAPI (Query by POST)
      summary: Return resources from SOAGPAT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-gpa-types-1.0.0_qapi_post_request"
            example:
              id: A00043337
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-gpa-types-1.0.0_qapi_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    applicant-gpa-types-1.0.0_qapi_post_response:
      required:
        - applNumber
        - gpa
        - gpatCode
        - sbgiCode
        - termCodeEntry
      type: object
      properties:
        sbgiDescription:
          title: School Description
          type: string
        applNumber:
          title: Sorgpat Appl Number
          maxLength: 30
          type: number
          description: "Lineage reference object : SORGPAT_APPL_NUMBER"
          x-lineageReferenceObject: SORGPAT_APPL_NUMBER
        gpatCode:
          title: Sorgpat Gpat Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_GPAT_CODE, Lookup lineage
            reference object : stvgpat"
          x-lineageReferenceObject: SORGPAT_GPAT_CODE
          x-lineageLookupReferenceObject: stvgpat
        activityDate:
          title: Sorgpat Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORGPAT_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORGPAT_ACTIVITY_DATE
        gpa:
          title: Sorgpat Gpa
          maxLength: 29
          type: number
          description: "Lineage reference object : SORGPAT_GPA"
          x-lineageReferenceObject: SORGPAT_GPA
        sbgiCode:
          title: Sorgpat Sbgi Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_SBGI_CODE"
          x-lineageReferenceObject: SORGPAT_SBGI_CODE
        gpaDesc:
          title: GPA Description
          type: string
        plusMinusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORGPAT_PLUS_MINUS_IND"
          x-lineageReferenceObject: SORGPAT_PLUS_MINUS_IND
        termCodeEntry:
          title: Sorgpat Term Code Entry
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_TERM_CODE_ENTRY, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORGPAT_TERM_CODE_ENTRY
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorgpat
    applicant-gpa-types-1.0.0_post_request:
      required:
        - gpatCode
        - gpaCode
        - schoolCode
        - applNo
        - termCode
      type: object
      properties:
        keyblckId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        gpatCode:
          title: Sorgpat Gpat Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_GPAT_CODE, Lookup lineage
            reference object : stvgpat"
          x-lineageReferenceObject: SORGPAT_GPAT_CODE
          x-lineageLookupReferenceObject: stvgpat
        gpaCode:
          title: Sorgpat Gpa
          maxLength: 29
          type: number
          description: "Lineage reference object : SORGPAT_GPA"
          x-lineageReferenceObject: SORGPAT_GPA
        plusminusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORGPAT_PLUS_MINUS_IND"
          x-lineageReferenceObject: SORGPAT_PLUS_MINUS_IND
        applNo:
          title: Sorgpat Appl Number
          maxLength: 30
          type: number
          description: "Lineage reference object : SORGPAT_APPL_NUMBER"
          x-lineageReferenceObject: SORGPAT_APPL_NUMBER
        schoolCode:
          title: Sorgpat Sbgi Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_SBGI_CODE"
          x-lineageReferenceObject: SORGPAT_SBGI_CODE
        termCode:
          title: Sorgpat Term Code Entry
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_TERM_CODE_ENTRY, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORGPAT_TERM_CODE_ENTRY
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SORGPAT
    applicant-gpa-types-1.0.0_post_response:
      required:
        - applNumber
        - gpa
        - gpatCode
        - sbgiCode
        - termCodeEntry
      type: object
      properties:
        sbgiDescription:
          title: School Description
          type: string
        applNumber:
          title: Sorgpat Appl Number
          maxLength: 30
          type: number
          description: "Lineage reference object : SORGPAT_APPL_NUMBER"
          x-lineageReferenceObject: SORGPAT_APPL_NUMBER
        gpatCode:
          title: Sorgpat Gpat Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_GPAT_CODE, Lookup lineage
            reference object : stvgpat"
          x-lineageReferenceObject: SORGPAT_GPAT_CODE
          x-lineageLookupReferenceObject: stvgpat
        activityDate:
          title: Sorgpat Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORGPAT_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORGPAT_ACTIVITY_DATE
        gpa:
          title: Sorgpat Gpa
          maxLength: 29
          type: number
          description: "Lineage reference object : SORGPAT_GPA"
          x-lineageReferenceObject: SORGPAT_GPA
        sbgiCode:
          title: Sorgpat Sbgi Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_SBGI_CODE"
          x-lineageReferenceObject: SORGPAT_SBGI_CODE
        gpaDesc:
          title: GPA Description
          type: string
        plusMinusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORGPAT_PLUS_MINUS_IND"
          x-lineageReferenceObject: SORGPAT_PLUS_MINUS_IND
        termCodeEntry:
          title: Sorgpat Term Code Entry
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_TERM_CODE_ENTRY, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORGPAT_TERM_CODE_ENTRY
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorgpat
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    applicant-gpa-types-1.0.0_get_response:
      required:
        - applNumber
        - gpa
        - gpatCode
        - sbgiCode
        - termCodeEntry
      type: object
      properties:
        sbgiDescription:
          title: School Description
          type: string
        applNumber:
          title: Sorgpat Appl Number
          maxLength: 30
          type: number
          description: "Lineage reference object : SORGPAT_APPL_NUMBER"
          x-lineageReferenceObject: SORGPAT_APPL_NUMBER
        gpatCode:
          title: Sorgpat Gpat Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_GPAT_CODE, Lookup lineage
            reference object : stvgpat"
          x-lineageReferenceObject: SORGPAT_GPAT_CODE
          x-lineageLookupReferenceObject: stvgpat
        activityDate:
          title: Sorgpat Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORGPAT_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORGPAT_ACTIVITY_DATE
        gpa:
          title: Sorgpat Gpa
          maxLength: 29
          type: number
          description: "Lineage reference object : SORGPAT_GPA"
          x-lineageReferenceObject: SORGPAT_GPA
        sbgiCode:
          title: Sorgpat Sbgi Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_SBGI_CODE"
          x-lineageReferenceObject: SORGPAT_SBGI_CODE
        gpaDesc:
          title: GPA Description
          type: string
        plusMinusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORGPAT_PLUS_MINUS_IND"
          x-lineageReferenceObject: SORGPAT_PLUS_MINUS_IND
        termCodeEntry:
          title: Sorgpat Term Code Entry
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_TERM_CODE_ENTRY, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORGPAT_TERM_CODE_ENTRY
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorgpat
    applicant-gpa-types-1.0.0_qapi_post_request:
      required:
        - gpatCode
        - gpaCode
        - schoolCode
        - applNo
        - termCode
      type: object
      properties:
        keyblckId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        gpatCode:
          title: Sorgpat Gpat Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_GPAT_CODE, Lookup lineage
            reference object : stvgpat"
          x-lineageReferenceObject: SORGPAT_GPAT_CODE
          x-lineageLookupReferenceObject: stvgpat
        gpaCode:
          title: Sorgpat Gpa
          maxLength: 29
          type: number
          description: "Lineage reference object : SORGPAT_GPA"
          x-lineageReferenceObject: SORGPAT_GPA
        plusminusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORGPAT_PLUS_MINUS_IND"
          x-lineageReferenceObject: SORGPAT_PLUS_MINUS_IND
        applNo:
          title: Sorgpat Appl Number
          maxLength: 30
          type: number
          description: "Lineage reference object : SORGPAT_APPL_NUMBER"
          x-lineageReferenceObject: SORGPAT_APPL_NUMBER
        schoolCode:
          title: Sorgpat Sbgi Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_SBGI_CODE"
          x-lineageReferenceObject: SORGPAT_SBGI_CODE
        termCode:
          title: Sorgpat Term Code Entry
          maxLength: 30
          type: string
          description: "Lineage reference object : SORGPAT_TERM_CODE_ENTRY, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORGPAT_TERM_CODE_ENTRY
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SORGPAT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
