openapi: 3.0.0
info:
  title: salary-rate-structures
  description: API for NTRSALA administrative page
  version: 1.0.0
  x-audience: all
  x-source-name: NTRSALA
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Human Resources
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/salary-rate-structures:
    get:
      summary: Return resources from NTRSALA
      description: Returns a paged listing of all the salary rate structure rules records from NTRSALA
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SALARY_RATE_STRUCTURES
      tags:
        - salary-rate-structures
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ``` 

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Pay Group  

            Returns all salary rate structures for the given pay group

            ```

            /salary-rate-structures?criteria={"payGroup":"2014"}

            ```   

            ### Pay Table 

             Returns all salary rate structures for the given pay table

            ```

            /salary-rate-structures?criteria={"payTable":"AD"}

            ```  

            ### Grade  
            
             Returns all salary rate structures for the given grade

            ```

            /salary-rate-structures?criteria={"grade":"02"}

            ```    
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-salary-rate-structures.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/salary-rate-structures/{id}:
    get:
      summary: Return the requested resource from NTRSALA
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SALARY_RATE_STRUCTURES  
      tags:
        - salary-rate-structures
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Salary Rate Structures for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-salary-rate-structures.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-salary-rate-structures.json:
      title: Salary Rate Structures
      description: Information on pay for employees at each level.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the salary rate structure rules.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: NTRSALB_GUID(NTRSALB)
        amountHigh:
          title: Annual Salary or Base Wage Rate High
          description: The high amount for annual salary or base wage rate 
          type: number
          example: 10000
          x-LineageReferenceObject: NTRSALB_HIGH
          maxLength: 16
        amountMidpoint:
          title: Annual Salary or Base Wage Rate Midpoint
          description: The Midpoint amount for annual salary or base wage rate 
          type: number
          example: 7000
          x-LineageReferenceObject: NTRSALB_MIDPOINT
          maxLength: 16
        amountLow:
          title: Annual Salary or Base Wage Rate Low
          description: The Low amount for annual salary or base wage rate 
          type: number
          example: 2000
          x-LineageReferenceObject: NTRSALB_LOW
          maxLength: 16
        scheduleTypeInd:
          title: Schedule Type Indicator
          description: >
           Indicates whether the person is paid hourly or salaried. Valid options are:
              • 'S' Salaried
              • 'H' Hourly
          type: string
          example: S  
          x-LineageReferenceObject: NTRSALB_IND
          maxLength: 1
        payGroup:
          title: Pay Group
          description: The Pay group for salary rate structure
          type: string
          minLength: 1
          x-lineageReferenceObject: NTRSALB_SGRP_CODE
        payTable:
          title: Pay Table
          description: The Pay table for salary rate structure
          type: string
          x-lineageReferenceObject: NTRSALB_TABLE
        grade:
          title: Grade
          description: The Grade for salary rate structure
          type: string
          minLength: 1
          x-lineageReferenceObject: NTRSALB_GRADE
        startOn:
          title: Start On
          description: The start date of the salary rate structure.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: unsupported
            - type: string
              maxLength: 0
        endOn:
          title: End On
          description: The end date of the salary rate structure.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: unsupported
            - type: string
              maxLength: 0
        classification:
          title: Classification
          description: The classification associated with the salary rate structure.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Classification.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: pay-classifications 
              x-lineageReferenceObject: NTRSGRP_GUID(NTRSGRP)
          additionalProperties: false
          required:
            - id
        stepStructures:
          title: Step Structures
          description: The pay structure based on grades with step levels.
          type: array
          minItems: 1
          items:
            type: object
            properties:
              step:
                title: Step
                description: The different level of compensation for a position
                type: string
                minLength: 1
                x-lineageReferenceObject: NTRSALA_STEP(NTRSALA)
              amount:
                title: Amount
                description: The amount associated with the specific salary rate structure.
                oneOf:
                  - type: object
                    format: currency
                    properties:
                      value:
                        title: Value
                        description: The monetary value
                        type: number
                        x-lineageReferenceObject: NTRSALA_AMOUNT(NTRSALA)
                      currency:
                        title: Currency
                        description: The ISO 4217 currency code
                        enum:
                          - AED
                          - AFN
                          - ALL
                          - AMD
                          - ANG
                          - AOA
                          - ARS
                          - AUD
                          - AWG
                          - AZN
                          - BAM
                          - BBD
                          - BDT
                          - BGN
                          - BHD
                          - BIF
                          - BMD
                          - BND
                          - BOB
                          - BRL
                          - BSD
                          - BTN
                          - BWP
                          - BYR
                          - BZD
                          - CAD
                          - CDF
                          - CHF
                          - CLP
                          - CNY
                          - COP
                          - CRC
                          - CUC
                          - CUP
                          - CVE
                          - CZK
                          - DJF
                          - DKK
                          - DOP
                          - DZD
                          - EGP
                          - ERN
                          - ETB
                          - EUR
                          - FJD
                          - FKP
                          - GBP
                          - GEL
                          - GHS
                          - GIP
                          - GMD
                          - GNF
                          - GTQ
                          - GYD
                          - HKD
                          - HNL
                          - HRK
                          - HTG
                          - HUF
                          - IDR
                          - ILS
                          - INR
                          - IQD
                          - IRR
                          - ISK
                          - JMD
                          - JOD
                          - JPY
                          - KES
                          - KGS
                          - KHR
                          - KMF
                          - KPW
                          - KRW
                          - KWD
                          - KYD
                          - KZT
                          - LAK
                          - LBP
                          - LKR
                          - LRD
                          - LSL
                          - LYD
                          - MAD
                          - MDL
                          - MGA
                          - MKD
                          - MMK
                          - MNT
                          - MOP
                          - MRO
                          - MUR
                          - MVR
                          - MWK
                          - MXN
                          - MYR
                          - MZN
                          - NAD
                          - NGN
                          - NIO
                          - NOK
                          - NPR
                          - NZD
                          - OMR
                          - PAB
                          - PEN
                          - PGK
                          - PHP
                          - PKR
                          - PLN
                          - PYG
                          - QAR
                          - RON
                          - RSD
                          - RUB
                          - RWF
                          - SAR
                          - SBD
                          - SCR
                          - SDG
                          - SEK
                          - SGD
                          - SHP
                          - SLL
                          - SOS
                          - SRD
                          - SSP
                          - STD
                          - SVC
                          - SYP
                          - SZL
                          - THB
                          - TJS
                          - TMT
                          - TND
                          - TOP
                          - TRY
                          - TTD
                          - TWD
                          - TZS
                          - UAH
                          - UGX
                          - USD
                          - UYU
                          - UZS
                          - VEF
                          - VND
                          - VUV
                          - WST
                          - XAF
                          - XCD
                          - XOF
                          - XPF
                          - YER
                          - ZAR
                          - ZMW
                          - ZWL
                        type: string
                        x-lineageReferenceObject: GUBINST_BASE_CURR_CODE(GUBINST)
                    additionalProperties: false
                    required:
                      - value
                      - currency
                  - type: object
                    maxProperties: 0
            additionalProperties: false
            required:
              - grade
              - step
      required:
        - id
        - title
        - classification
      additionalProperties: false
