openapi: 3.0.0
info:
  title: student-course-registrations-student-term
  description: API for SFAREGS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SFAREGS
  x-source-domain: Student
  x-source-title: Student Course Registration
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-course-registrations-student-term:
    put:
      tags:
        - student-course-registrations-student-term
      summary: Updates an existing resource in SFAREGS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-course-registrations-student-term-1.0.0_put\
                _request"
            example:
              ststCode: AS
              resdCode: R
              term: 201520
              id: A00034151
              stypCode: N
              rateCode: LOCAL
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-course-registrations-student-term-1.0.0_put\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/student-course-registrations-student-term: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    student-course-registrations-student-term-1.0.0_put_request:
      required:
        - ststCode
        - stypCode
        - resdCode
      type: object
      properties:
        xxxxxxxAstdCode:
          title: Academic Standing
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvastd"
          x-lineageLookupReferenceObject: stvastd
        xxxxxxxCastCode:
          title: Combined Academic Standing
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvcast"
          x-lineageLookupReferenceObject: stvcast
        printBill:
          title: Print Bill
          maxLength: 1
          type: string
          description: "Lineage reference object : printBill"
          x-lineageReferenceObject: printBill
        resdCode:
          title: Residence
          maxLength: 30
          type: string
          description: "Lineage reference object : SGBSTDN_RESD_CODE, Lookup lineage
            reference object : stvresd"
          x-lineageReferenceObject: SGBSTDN_RESD_CODE
          x-lineageLookupReferenceObject: stvresd
        printSchedule:
          title: Print Schedule
          maxLength: 1
          type: string
          description: "Lineage reference object : printSchedule"
          x-lineageReferenceObject: printSchedule
        xxxxxxxPrevCode:
          title: Progress Evaluation
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvprev"
          x-lineageLookupReferenceObject: stvprev
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        viewCurrent:
          title: View Current/Active Curricula
          maxLength: 30
          type: string
          description: "Lineage reference object : viewCurrent"
          x-lineageReferenceObject: viewCurrent
        rateCode:
          title: Fee Assessment Rate
          maxLength: 30
          type: string
          description: "Lineage reference object : SGBSTDN_RATE_CODE, Lookup lineage
            reference object : stvrate"
          x-lineageReferenceObject: SGBSTDN_RATE_CODE
          x-lineageLookupReferenceObject: stvrate
        scpcCode:
          title: Student Centric Cycle
          maxLength: 30
          type: string
          description: "Lineage reference object : SGBSTDN_SCPC_CODE, Lookup lineage
            reference object : stvscpc,sobscps,sorscpt"
          x-lineageReferenceObject: SGBSTDN_SCPC_CODE
          x-lineageLookupReferenceObject: stvscpc,sobscps,sorscpt
        holdPassword:
          title: Holds
          maxLength: 3
          type: string
          description: "Lineage reference object : holdPassword"
          x-lineageReferenceObject: holdPassword
        ststCode:
          title: Student Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SGBSTDN_STST_CODE, Lookup lineage
            reference object : stvstst"
          x-lineageReferenceObject: SGBSTDN_STST_CODE
          x-lineageLookupReferenceObject: stvstst
        blckCode:
          title: Block Schedule
          maxLength: 30
          type: string
          description: "Lineage reference object : SGBSTDN_BLCK_CODE, Lookup lineage
            reference object : stvblck"
          x-lineageReferenceObject: SGBSTDN_BLCK_CODE
          x-lineageLookupReferenceObject: stvblck
        term:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : term, Lookup lineage reference object :
            stvterm"
          x-lineageReferenceObject: term
          x-lineageLookupReferenceObject: stvterm
        rstsEstsDate:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : rstsEstsDate"
          format: date-time
          x-lineageReferenceObject: rstsEstsDate
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        stypCode:
          title: Student Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGBSTDN_STYP_CODE, Lookup lineage
            reference object : stvstyp"
          x-lineageReferenceObject: SGBSTDN_STYP_CODE
          x-lineageLookupReferenceObject: stvstyp
      x-lineageReferenceObject: SGBSTDN
    student-course-registrations-student-term-1.0.0_put_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              printBill:
                title: Print Bill
                maxLength: 1
                type: string
                description: "Lineage reference object : printBill"
                x-lineageReferenceObject: printBill
              printSchedule:
                title: Print Schedule
                maxLength: 1
                type: string
                description: "Lineage reference object : printSchedule"
                x-lineageReferenceObject: printSchedule
              holdDesc:
                maxLength: 2
                type: string
                description: "Lineage reference object : holdDesc"
                x-lineageReferenceObject: holdDesc
              confidInd:
                maxLength: 30
                type: string
                description: "Lineage reference object : confidInd"
                x-lineageReferenceObject: confidInd
              keyStudypath:
                title: Study Path
                maxLength: 2
                type: number
                description: "Lineage reference object : keyStudypath, Lookup lineage reference
                  object :
                  sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvst\
                  sp,sgrstsp,sovlcur"
                x-lineageReferenceObject: keyStudypath
                x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
              dcsdInd:
                maxLength: 30
                type: string
                description: "Lineage reference object : dcsdInd"
                x-lineageReferenceObject: dcsdInd
              viewCurrent:
                title: View Current/Active Curricula
                maxLength: 30
                type: string
                description: "Lineage reference object : viewCurrent"
                x-lineageReferenceObject: viewCurrent
              holdPassword:
                title: Holds
                maxLength: 3
                type: string
                description: "Lineage reference object : holdPassword"
                x-lineageReferenceObject: holdPassword
              rwname:
                maxLength: 230
                type: string
                description: "Lineage reference object : rwname"
                x-lineageReferenceObject: rwname
              rstsEstsDate:
                title: Date
                maxLength: 11
                type: string
                description: "Lineage reference object : rstsEstsDate"
                format: date-time
                x-lineageReferenceObject: rstsEstsDate
              term:
                title: Term
                maxLength: 30
                type: string
                description: "Lineage reference object : term, Lookup lineage reference object :
                  stvterm"
                x-lineageReferenceObject: term
                x-lineageLookupReferenceObject: stvterm
              id:
                title: ID
                maxLength: 9
                type: string
                description: "Lineage reference object : id"
                x-lineageReferenceObject: id
              lastAssessmentDate:
                title: Date
                maxLength: 11
                type: string
                description: "Lineage reference object : lastAssessmentDate"
                format: date-time
                x-lineageReferenceObject: lastAssessmentDate
            x-lineageReferenceObject: key_block
        sgbstdn:
          type: array
          items:
            required:
              - resdCode
              - ststCode
              - stypCode
            type: object
            properties:
              termCastDesc:
                type: string
              astdDesc:
                type: string
              advrName:
                title: Advisor
                maxLength: 98
                type: string
              termEffDesc:
                type: string
              xxxxxxxCastCode:
                title: Combined Academic Standing
                maxLength: 30
                type: string
                description: "Lookup lineage reference object : stvcast"
                x-lineageLookupReferenceObject: stvcast
              lastTermAttended:
                title: Last Term Attended
                maxLength: 6
                type: string
              ststDesc:
                type: string
              xxxxxxxPrevCode:
                title: Progress Evaluation
                maxLength: 30
                type: string
                description: "Lookup lineage reference object : stvprev"
                x-lineageLookupReferenceObject: stvprev
              rateCode:
                title: Fee Assessment Rate
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_RATE_CODE, Lookup lineage
                  reference object : stvrate"
                x-lineageReferenceObject: SGBSTDN_RATE_CODE
                x-lineageLookupReferenceObject: stvrate
              resdDesc:
                type: string
              xxxxxxxTermCodePrev:
                title: Override Term
                maxLength: 6
                type: string
              stypDesc:
                type: string
              stvscpcDesc:
                type: string
              fullPartDesc:
                type: string
              xxxxxxxTermCodeCast:
                title: Override Term
                maxLength: 6
                type: string
              termPrevDesc:
                type: string
              fullPartInd:
                title: Full or Part Time
                maxLength: 1
                type: string
                description: "Lineage reference object : SGBSTDN_FULL_PART_IND"
                x-lineageReferenceObject: SGBSTDN_FULL_PART_IND
              castDesc:
                type: string
              termAstdDesc:
                type: string
              termCodeEff:
                title: Effective Term
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_TERM_CODE_EFF"
                x-lineageReferenceObject: SGBSTDN_TERM_CODE_EFF
              xxxxxxxAstdCode:
                title: Academic Standing
                maxLength: 30
                type: string
                description: "Lookup lineage reference object : stvastd"
                x-lineageLookupReferenceObject: stvastd
              prevDesc:
                type: string
              resdCode:
                title: Residence
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_RESD_CODE, Lookup lineage
                  reference object : stvresd"
                x-lineageReferenceObject: SGBSTDN_RESD_CODE
                x-lineageLookupReferenceObject: stvresd
              blckDesc:
                type: string
              termaDesc:
                type: string
              scpcCode:
                title: Student Centric Cycle
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_SCPC_CODE, Lookup lineage
                  reference object : stvscpc,sobscps,sorscpt"
                x-lineageReferenceObject: SGBSTDN_SCPC_CODE
                x-lineageLookupReferenceObject: stvscpc,sobscps,sorscpt
              rateDesc:
                type: string
              ststCode:
                title: Student Status
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_STST_CODE, Lookup lineage
                  reference object : stvstst"
                x-lineageReferenceObject: SGBSTDN_STST_CODE
                x-lineageLookupReferenceObject: stvstst
              blckCode:
                title: Block Schedule
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_BLCK_CODE, Lookup lineage
                  reference object : stvblck"
                x-lineageReferenceObject: SGBSTDN_BLCK_CODE
                x-lineageLookupReferenceObject: stvblck
              stypCode:
                title: Student Type
                maxLength: 30
                type: string
                description: "Lineage reference object : SGBSTDN_STYP_CODE, Lookup lineage
                  reference object : stvstyp"
                x-lineageReferenceObject: SGBSTDN_STYP_CODE
                x-lineageLookupReferenceObject: stvstyp
              sgrclsrClasCode:
                title: Class
                maxLength: 2
                type: string
                description: "Lookup lineage reference object : stvclas"
                x-lineageLookupReferenceObject: stvclas
              clasDesc:
                type: string
              xxxxxxxTermCodeAstd:
                title: Override Term
                maxLength: 6
                type: string
            x-lineageReferenceObject: sgbstdn
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
