openapi: 3.0.0
info:
  title: general-person-identification-biographical-races
  description: API for SPAIDEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SPAIDEN
  x-source-domain: Student
  x-source-title: General Person Identification
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/general-person-identification-biographical-races:
    delete:
      tags:
      - general-person-identification-biographical-races
      summary: Deletes an existing resource in SPAIDEN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-person-identification-biographical-races-1.0.0_delete_request"
            example:
              criteria:
                activityDate: 2025-09-26
                raceCde: H
                userId: SAISUSR
              id: A00010018
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-person-identification-biographical-races-1.0.0_delete_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/general-person-identification-biographical-races: {}
components:
  schemas:
    general-person-identification-biographical-races-1.0.0_delete_request:
      type: object
      properties:
        criteria.raceCde:
          title: Race
          maxLength: 30
          type: string
          description: "Lineage reference object : GORPRAC_RACE_CDE, Lookup lineage\
            \ reference object : gorrace"
          x-lineageReferenceObject: GORPRAC_RACE_CDE
          x-lineageLookupReferenceObject: gorrace
        criteria.userId:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : GORPRAC_USER_ID"
          x-lineageReferenceObject: GORPRAC_USER_ID
        criteria.activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GORPRAC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GORPRAC_ACTIVITY_DATE
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: GORPRAC
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                description: 'The detailed actionable error message. '
              description:
                type: string
                description: The error description used to describe the error details.
    general-person-identification-biographical-races-1.0.0_delete_response:
      type: object
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer


