openapi: 3.0.0
info:
  title: receipt-queries
  description: API for TGIRCPT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TGIRCPT
  x-source-domain: Student
  x-source-title: Receipt Query
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/receipt-queries:
    get:
      tags:
        - receipt-queries
      summary: Return resources from TGIRCPT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: tagOption
          in: query
          required: false
          schema:
            type: string
        - name: receiptNumber
          in: query
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
        - name: user
          in: query
          required: false
          schema:
            type: string
        - name: sessionNumber
          in: query
          required: false
          schema:
            type: string
        - name: feedDocCode
          in: query
          required: false
          schema:
            type: string
        - name: acctFeedInd
          in: query
          required: false
          schema:
            type: string
        - name: feedDate
          in: query
          required: false
          schema:
            type: string
        - name: tranNumber
          in: query
          description: Tbvrcp2 Tran Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVRCP2_TRAN_NUMBER
        - name: termCode
          in: query
          description: Tbvrcp2 Term Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVRCP2_TERM_CODE
        - name: detailCode
          in: query
          description: Tbvrcp2 Detail Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVRCP2_DETAIL_CODE
        - name: desc
          in: query
          description: Tbvrcp2 Desc
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVRCP2_DESC
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/receipt-queries-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/receipt-queries:
    post:
      tags:
        - receipt-queries QAPI (Query by POST)
      summary: Return resources from TGIRCPT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/receipt-queries-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/receipt-queries-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    receipt-queries-1.0.0_get_response:
      type: object
      properties:
        tbvrcp1:
          type: array
          items:
            type: object
            properties:
              date:
                title: Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBVRCP1_DATE"
                format: date-time
                x-lineageReferenceObject: TBVRCP1_DATE
              feedDate:
                title: Feed Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBVRCP1_FEED_DATE"
                format: date-time
                x-lineageReferenceObject: TBVRCP1_FEED_DATE
              feedDocCode:
                title: Feed Document
                maxLength: 8
                type: string
                description: "Lineage reference object : TBVRCP1_FEED_DOC_CODE"
                x-lineageReferenceObject: TBVRCP1_FEED_DOC_CODE
              sessionNumber:
                title: Session
                maxLength: 38
                type: number
                description: "Lineage reference object : TBVRCP1_SESSION_NUMBER"
                x-lineageReferenceObject: TBVRCP1_SESSION_NUMBER
              acctFeedInd:
                title: Tbvrcp2 Type
                maxLength: 1
                type: string
                description: "Lineage reference object : TBVRCP1_ACCT_FEED_IND"
                x-lineageReferenceObject: TBVRCP1_ACCT_FEED_IND
              name:
                title: Name
                maxLength: 230
                type: string
              id:
                title: ID
                maxLength: 9
                type: string
              type:
                title: Tbvrcp2 Type
                maxLength: 1
                type: string
                description: "Lineage reference object : TBVRCP1_TYPE"
                x-lineageReferenceObject: TBVRCP1_TYPE
              user:
                title: User
                maxLength: 49
                type: string
                description: "Lineage reference object : TBVRCP1_USER"
                x-lineageReferenceObject: TBVRCP1_USER
              receiptNumber:
                title: Receipt Number
                maxLength: 8
                type: number
                description: "Lineage reference object : TBVRCP1_RECEIPT_NUMBER"
                x-lineageReferenceObject: TBVRCP1_RECEIPT_NUMBER
            x-lineageReferenceObject: tbvrcp1
        tbvrcp2:
          type: array
          items:
            type: object
            properties:
              charge:
                title: Charge
                maxLength: 14
                type: number
              tranNumber:
                title: Tbvrcp2 Tran Number
                maxLength: 42
                type: number
                description: "Lineage reference object : TBVRCP2_TRAN_NUMBER"
                x-lineageReferenceObject: TBVRCP2_TRAN_NUMBER
              payment:
                title: Payment
                maxLength: 14
                type: number
              detailCode:
                title: Tbvrcp2 Detail Code
                maxLength: 4
                type: string
                description: "Lineage reference object : TBVRCP2_DETAIL_CODE"
                x-lineageReferenceObject: TBVRCP2_DETAIL_CODE
              desc:
                title: Tbvrcp2 Desc
                maxLength: 30
                type: string
                description: "Lineage reference object : TBVRCP2_DESC"
                x-lineageReferenceObject: TBVRCP2_DESC
              termCode:
                title: Tbvrcp2 Term Code
                maxLength: 6
                type: string
                description: "Lineage reference object : TBVRCP2_TERM_CODE"
                x-lineageReferenceObject: TBVRCP2_TERM_CODE
            x-lineageReferenceObject: tbvrcp2
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    receipt-queries-1.0.0_get_request:
      type: object
      properties:
        date:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVRCP1_DATE"
          format: date-time
          x-lineageReferenceObject: TBVRCP1_DATE
        feedDate:
          title: Feed Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVRCP1_FEED_DATE"
          format: date-time
          x-lineageReferenceObject: TBVRCP1_FEED_DATE
        tranNumber:
          title: Tbvrcp2 Tran Number
          maxLength: 42
          type: number
          description: "Lineage reference object : TBVRCP2_TRAN_NUMBER"
          x-lineageReferenceObject: TBVRCP2_TRAN_NUMBER
        tagOption:
          title: Display By
          maxLength: 1
          type: number
          description: "Lineage reference object : tagOption"
          x-lineageReferenceObject: tagOption
        type:
          title: Tbvrcp2 Type
          maxLength: 1
          type: string
          description: "Lineage reference object : TBVRCP1_TYPE"
          x-lineageReferenceObject: TBVRCP1_TYPE
        detailCode:
          title: Tbvrcp2 Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBVRCP2_DETAIL_CODE"
          x-lineageReferenceObject: TBVRCP2_DETAIL_CODE
        sessionNumber:
          title: Session
          maxLength: 38
          type: number
          description: "Lineage reference object : TBVRCP1_SESSION_NUMBER"
          x-lineageReferenceObject: TBVRCP1_SESSION_NUMBER
        feedDocCode:
          title: Feed Document
          maxLength: 8
          type: string
          description: "Lineage reference object : TBVRCP1_FEED_DOC_CODE"
          x-lineageReferenceObject: TBVRCP1_FEED_DOC_CODE
        acctFeedInd:
          title: Tbvrcp2 Type
          maxLength: 1
          type: string
          description: "Lineage reference object : TBVRCP1_ACCT_FEED_IND"
          x-lineageReferenceObject: TBVRCP1_ACCT_FEED_IND
        name:
          title: Name
          maxLength: 230
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
        user:
          title: User
          maxLength: 49
          type: string
          description: "Lineage reference object : TBVRCP1_USER"
          x-lineageReferenceObject: TBVRCP1_USER
        receiptNumber:
          title: Receipt Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBVRCP1_RECEIPT_NUMBER"
          x-lineageReferenceObject: TBVRCP1_RECEIPT_NUMBER
        termCode:
          title: Tbvrcp2 Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : TBVRCP2_TERM_CODE"
          x-lineageReferenceObject: TBVRCP2_TERM_CODE
        desc:
          title: Tbvrcp2 Desc
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVRCP2_DESC"
          x-lineageReferenceObject: TBVRCP2_DESC
      x-lineageReferenceObject: TBVRCP2
    receipt-queries-1.0.0_qapi_post:
      type: object
      properties:
        tagOption:
          type: string
        receiptNumber:
          type: string
        id:
          type: string
        name:
          type: string
        type:
          type: string
        date:
          type: string
        user:
          type: string
        sessionNumber:
          type: string
        feedDocCode:
          type: string
        acctFeedInd:
          type: string
        feedDate:
          type: string
        tranNumber:
          title: Tbvrcp2 Tran Number
          maxLength: 42
          type: number
          description: "Lineage reference object : TBVRCP2_TRAN_NUMBER"
          x-lineageReferenceObject: TBVRCP2_TRAN_NUMBER
        termCode:
          title: Tbvrcp2 Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : TBVRCP2_TERM_CODE"
          x-lineageReferenceObject: TBVRCP2_TERM_CODE
        detailCode:
          title: Tbvrcp2 Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBVRCP2_DETAIL_CODE"
          x-lineageReferenceObject: TBVRCP2_DETAIL_CODE
        desc:
          title: Tbvrcp2 Desc
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVRCP2_DESC"
          x-lineageReferenceObject: TBVRCP2_DESC
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
