openapi: 3.0.0
info:
  title: fixed-asset-user-defined-system-codes
  description: API for FFVSDAT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FFVSDAT
  x-source-domain: Finance
  x-source-title: Fixed Asset User Defined System Codes Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/fixed-asset-user-defined-system-codes:
    get:
      tags:
        - fixed-asset-user-defined-system-codes
      summary: Return resources from FFVSDAT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: data
          in: query
          description: Frvsdat Data
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FFVSDAT_DATA
        - name: sdatCodeAttr
          in: query
          description: Frvsdat Sdat Code Attr
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_ATTR
        - name: sdatCodeOpt1
          in: query
          description: Frvsdat Sdat Code Opt 1
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_OPT_1
        - name: shortTitle
          in: query
          description: Frvsdat Short Title
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FFVSDAT_SHORT_TITLE
        - name: title
          in: query
          description: Frvsdat Title
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FFVSDAT_TITLE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/fixed-asset-user-defined-system-codes-1.0.0_get_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/fixed-asset-user-defined-system-codes:
    post:
      tags:
        - fixed-asset-user-defined-system-codes QAPI (Query by POST)
      summary: Return resources from FFVSDAT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/fixed-asset-user-defined-system-codes-1.0.0_get_req\
                uest"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/fixed-asset-user-defined-system-codes-1.0.0_get_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    fixed-asset-user-defined-system-codes-1.0.0_qapi_post:
      type: object
      properties:
        data:
          title: Frvsdat Data
          maxLength: 15
          type: string
          description: "Lineage reference object : FFVSDAT_DATA"
          x-lineageReferenceObject: FFVSDAT_DATA
        sdatCodeAttr:
          title: Frvsdat Sdat Code Attr
          maxLength: 30
          type: string
          description: "Lineage reference object : FFVSDAT_SDAT_CODE_ATTR"
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_ATTR
        sdatCodeOpt1:
          title: Frvsdat Sdat Code Opt 1
          maxLength: 8
          type: string
          description: "Lineage reference object : FFVSDAT_SDAT_CODE_OPT_1"
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_OPT_1
        shortTitle:
          title: Frvsdat Short Title
          maxLength: 20
          type: string
          description: "Lineage reference object : FFVSDAT_SHORT_TITLE"
          x-lineageReferenceObject: FFVSDAT_SHORT_TITLE
        title:
          title: Frvsdat Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FFVSDAT_TITLE"
          x-lineageReferenceObject: FFVSDAT_TITLE
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    fixed-asset-user-defined-system-codes-1.0.0_get_response:
      required:
        - sdatCodeAttr
        - sdatCodeOpt1
        - title
      type: object
      properties:
        data:
          title: Frvsdat Data
          maxLength: 15
          type: string
          description: "Lineage reference object : FFVSDAT_DATA"
          x-lineageReferenceObject: FFVSDAT_DATA
        sdatCodeOpt1:
          title: Frvsdat Sdat Code Opt 1
          maxLength: 8
          type: string
          description: "Lineage reference object : FFVSDAT_SDAT_CODE_OPT_1"
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_OPT_1
        shortTitle:
          title: Frvsdat Short Title
          maxLength: 20
          type: string
          description: "Lineage reference object : FFVSDAT_SHORT_TITLE"
          x-lineageReferenceObject: FFVSDAT_SHORT_TITLE
        sdatCodeAttr:
          title: Frvsdat Sdat Code Attr
          maxLength: 30
          type: string
          description: "Lineage reference object : FFVSDAT_SDAT_CODE_ATTR"
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_ATTR
        title:
          title: Frvsdat Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FFVSDAT_TITLE"
          x-lineageReferenceObject: FFVSDAT_TITLE
      x-lineageReferenceObject: ffvsdat
    fixed-asset-user-defined-system-codes-1.0.0_get_request:
      required:
        - sdatCodeAttr
        - sdatCodeOpt1
        - title
      type: object
      properties:
        data:
          title: Frvsdat Data
          maxLength: 15
          type: string
          description: "Lineage reference object : FFVSDAT_DATA"
          x-lineageReferenceObject: FFVSDAT_DATA
        sdatCodeOpt1:
          title: Frvsdat Sdat Code Opt 1
          maxLength: 8
          type: string
          description: "Lineage reference object : FFVSDAT_SDAT_CODE_OPT_1"
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_OPT_1
        shortTitle:
          title: Frvsdat Short Title
          maxLength: 20
          type: string
          description: "Lineage reference object : FFVSDAT_SHORT_TITLE"
          x-lineageReferenceObject: FFVSDAT_SHORT_TITLE
        sdatCodeAttr:
          title: Frvsdat Sdat Code Attr
          maxLength: 30
          type: string
          description: "Lineage reference object : FFVSDAT_SDAT_CODE_ATTR"
          x-lineageReferenceObject: FFVSDAT_SDAT_CODE_ATTR
        title:
          title: Frvsdat Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FFVSDAT_TITLE"
          x-lineageReferenceObject: FFVSDAT_TITLE
      x-lineageReferenceObject: FFVSDAT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
