openapi: 3.0.0
info:
  title: general-text-entry
  description: API for FOATEXT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FOATEXT
  x-source-domain: Finance
  x-source-title: General Text Entry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/general-text-entry:
    get:
      tags:
        - general-text-entry
      summary: Return resources from FOATEXT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblokDtypCode
          in: query
          required: true
          schema:
            type: string
        - name: keyblokDocCode
          in: query
          required: false
          schema:
            type: string
        - name: text
          in: query
          description: Text
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FOBTEXT_TEXT
        - name: prtInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        - name: seqNum
          in: query
          description: Line
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-text-entry-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - general-text-entry
      summary: Updates an existing resource in FOATEXT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-text-entry-1.0.0_put_request"
            example:
              keyblokDocCode: E0000271
              keyblokDtypCode: ADJ
              seqNum: 13
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-text-entry-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - general-text-entry
      summary: Creates a new resource in FOATEXT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-text-entry-1.0.0_post_request"
            example:
              keyblokDocCode: E0000271
              keyblokDtypCode: ADJ
              prtInd: N
              seqNum: 12
              text: TEST5
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-text-entry-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/general-text-entry:
    post:
      tags:
        - general-text-entry QAPI (Query by POST)
      summary: Return resources from FOATEXT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-text-entry-1.0.0_get_request"
            example:
              keyblokDocCode: E0000271
              keyblokDtypCode: ADJ
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-text-entry-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    general-text-entry-1.0.0_post_request:
      required:
        - keyblokDtypCode
      type: object
      properties:
        keyblokDocCode:
          title: Code
          maxLength: 20
          type: string
          description: "Lineage reference object : keyblokDocCode"
          x-lineageReferenceObject: keyblokDocCode
        keyblokDtypCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblokDtypCode, Lookup lineage
            reference object : ftvdtyp"
          x-lineageReferenceObject: keyblokDtypCode
          x-lineageLookupReferenceObject: ftvdtyp
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
      x-lineageReferenceObject: FOBTEXT
    general-text-entry-1.0.0_put_request:
      required:
        - keyblokDtypCode
      type: object
      properties:
        keyblokDocCode:
          title: Code
          maxLength: 20
          type: string
          description: "Lineage reference object : keyblokDocCode"
          x-lineageReferenceObject: keyblokDocCode
        keyblokDtypCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblokDtypCode, Lookup lineage
            reference object : ftvdtyp"
          x-lineageReferenceObject: keyblokDtypCode
          x-lineageLookupReferenceObject: ftvdtyp
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        criteria.text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
        criteria.prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        criteria.seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
      x-lineageReferenceObject: FOBTEXT
    general-text-entry-1.0.0_put_response:
      type: object
      properties:
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
      x-lineageReferenceObject: fobtext
    general-text-entry-1.0.0_post_response:
      type: object
      properties:
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
      x-lineageReferenceObject: fobtext
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    general-text-entry-1.0.0_qapi_post:
      required:
        - keyblokDtypCode
      type: object
      properties:
        keyblokDtypCode:
          type: string
        keyblokDocCode:
          type: string
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
    general-text-entry-1.0.0_get_request:
      required:
        - keyblokDtypCode
      type: object
      properties:
        keyblokDocCode:
          title: Code
          maxLength: 20
          type: string
          description: "Lineage reference object : keyblokDocCode"
          x-lineageReferenceObject: keyblokDocCode
        keyblokDtypCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblokDtypCode, Lookup lineage
            reference object : ftvdtyp"
          x-lineageReferenceObject: keyblokDtypCode
          x-lineageLookupReferenceObject: ftvdtyp
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
      x-lineageReferenceObject: FOBTEXT
    general-text-entry-1.0.0_get_response:
      type: object
      properties:
        prtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FOBTEXT_PRT_IND"
          x-lineageReferenceObject: FOBTEXT_PRT_IND
        seqNum:
          title: Line
          maxLength: 4
          type: number
          description: "Lineage reference object : FOBTEXT_SEQ_NUM"
          x-lineageReferenceObject: FOBTEXT_SEQ_NUM
        text:
          title: Text
          maxLength: 50
          type: string
          description: "Lineage reference object : FOBTEXT_TEXT"
          x-lineageReferenceObject: FOBTEXT_TEXT
      x-lineageReferenceObject: fobtext
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
