openapi: 3.0.0
info:
  title: section-restriction-department-and-field-of-study
  description: API for SSARRES administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SSARRES
  x-source-domain: Student
  x-source-title: Schedule Restrictions
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/section-restriction-department-and-field-of-study:
    get:
      tags:
        - section-restriction-department-and-field-of-study
      summary: Return resources from SSARRES
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: ssasectTermCode
          in: query
          required: true
          schema:
            type: string
        - name: ssasectCrn
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-restriction-department-and-field-of-study-1\
                    .0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - section-restriction-department-and-field-of-study
      summary: Creates a new resource in SSARRES
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-restriction-department-and-field-of-study-1\
                .0.0_post_request"
            example:
              ssasectTermCode: 12011
              ssasectCrn: 1009
              ssrrmajLfstCode: CONCENTRATION
              majrCode: 101
              deptCode: 1
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-restriction-department-and-field-of-study-1\
                    .0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/section-restriction-department-and-field-of-study:
    post:
      tags:
        - section-restriction-department-and-field-of-study QAPI (Query by POST)
      summary: Return resources from SSARRES
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-restriction-department-and-field-of-study-1\
                .0.0_get_request"
            example:
              ssasectTermCode: 1010
              ssasectCrn: 10014
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-restriction-department-and-field-of-study-1\
                    .0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    section-restriction-department-and-field-of-study-1.0.0_get_response:
      type: object
      properties:
        rdep_ctrl_block:
          type: array
          items:
            required:
              - ssrrdepDeptIeCde
            type: object
            properties:
              ssrrdepDeptIeCde:
                title: "Include/Exclude (I/E):"
                maxLength: 1
                type: string
                description: "Lineage reference object : ssrrdepDeptIeCde"
                x-lineageReferenceObject: ssrrdepDeptIeCde
            x-lineageReferenceObject: rdep_ctrl_block
        rmaj_ctrl_block:
          type: array
          items:
            required:
              - ssrrmajMajorIndVit
            type: object
            properties:
              lfstDesc:
                title: Description
                type: string
              fosAll:
                maxLength: 1
                type: string
              ssrrmajMajorIndVit:
                maxLength: 1
                type: string
              ssrrmajLfstCode:
                title: Type
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRMAJ_LFST_CODE, Lookup lineage
                  reference object : gtvlfst"
                x-lineageReferenceObject: SSRRMAJ_LFST_CODE
                x-lineageLookupReferenceObject: gtvlfst
            x-lineageReferenceObject: rmaj_ctrl_block
        ssrrdep:
          type: array
          items:
            type: object
            properties:
              deptDesc:
                title: Description
                type: string
              userId:
                title: Ssrrdep User Id
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRDEP_USER_ID"
                x-lineageReferenceObject: SSRRDEP_USER_ID
              deptCode:
                title: Department
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRDEP_DEPT_CODE, Lookup lineage
                  reference object : stvdept"
                x-lineageReferenceObject: SSRRDEP_DEPT_CODE
                x-lineageLookupReferenceObject: stvdept
            x-lineageReferenceObject: ssrrdep
        ssrrmaj:
          type: array
          items:
            type: object
            properties:
              majorDescription:
                title: Description
                type: string
              majrCode:
                title: Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRMAJ_MAJR_CODE, Lookup lineage
                  reference object : stvmajr"
                x-lineageReferenceObject: SSRRMAJ_MAJR_CODE
                x-lineageLookupReferenceObject: stvmajr
            x-lineageReferenceObject: ssrrmaj
    section-restriction-department-and-field-of-study-1.0.0_post_request:
      required:
        - ssasectTermCode
        - ssrrdepDeptIeCde
        - ssrrmajMajorIndVit
      type: object
      properties:
        ssasectTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: ssasectTermCode
          x-lineageLookupReferenceObject: stvterm
        ssasectCrn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectCrn"
          x-lineageReferenceObject: ssasectCrn
        fosAll:
          maxLength: 1
          type: string
        ssrrmajMajorIndVit:
          maxLength: 1
          type: string
        ssrrmajLfstCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SSRRMAJ_LFST_CODE, Lookup lineage
            reference object : gtvlfst"
          x-lineageReferenceObject: SSRRMAJ_LFST_CODE
          x-lineageLookupReferenceObject: gtvlfst
        ssrrdepDeptIeCde:
          title: "Include/Exclude (I/E):"
          maxLength: 1
          type: string
          description: "Lineage reference object : ssrrdepDeptIeCde"
          x-lineageReferenceObject: ssrrdepDeptIeCde
        majrCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SSRRMAJ_MAJR_CODE, Lookup lineage
            reference object : stvmajr"
          x-lineageReferenceObject: SSRRMAJ_MAJR_CODE
          x-lineageLookupReferenceObject: stvmajr
        deptCode:
          title: Department
          maxLength: 30
          type: string
          description: "Lineage reference object : SSRRDEP_DEPT_CODE, Lookup lineage
            reference object : stvdept"
          x-lineageReferenceObject: SSRRDEP_DEPT_CODE
          x-lineageLookupReferenceObject: stvdept
      x-lineageReferenceObject: SSRRMAJ
    section-restriction-department-and-field-of-study-1.0.0_qapi_post:
      required:
        - ssasectTermCode
      type: object
      properties:
        ssasectTermCode:
          type: string
        ssasectCrn:
          type: string
    section-restriction-department-and-field-of-study-1.0.0_get_request:
      required:
        - ssasectTermCode
      type: object
      properties:
        ssasectTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: ssasectTermCode
          x-lineageLookupReferenceObject: stvterm
        ssasectCrn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectCrn"
          x-lineageReferenceObject: ssasectCrn
      x-lineageReferenceObject: KEY_BLOCK
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    section-restriction-department-and-field-of-study-1.0.0_post_response:
      type: object
      properties:
        rmaj_ctrl_block:
          type: array
          items:
            required:
              - ssrrmajMajorIndVit
            type: object
            properties:
              lfstDesc:
                title: Description
                type: string
              fosAll:
                maxLength: 1
                type: string
              ssrrmajMajorIndVit:
                maxLength: 1
                type: string
              ssrrmajLfstCode:
                title: Type
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRMAJ_LFST_CODE, Lookup lineage
                  reference object : gtvlfst"
                x-lineageReferenceObject: SSRRMAJ_LFST_CODE
                x-lineageLookupReferenceObject: gtvlfst
            x-lineageReferenceObject: rmaj_ctrl_block
        ssrrdep:
          type: array
          items:
            type: object
            properties:
              deptDesc:
                title: Description
                type: string
              userId:
                title: Ssrrdep User Id
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRDEP_USER_ID"
                x-lineageReferenceObject: SSRRDEP_USER_ID
              deptCode:
                title: Department
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRDEP_DEPT_CODE, Lookup lineage
                  reference object : stvdept"
                x-lineageReferenceObject: SSRRDEP_DEPT_CODE
                x-lineageLookupReferenceObject: stvdept
            x-lineageReferenceObject: ssrrdep
        ssrrmaj:
          type: array
          items:
            type: object
            properties:
              majorDescription:
                title: Description
                type: string
              majrCode:
                title: Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRMAJ_MAJR_CODE, Lookup lineage
                  reference object : stvmajr"
                x-lineageReferenceObject: SSRRMAJ_MAJR_CODE
                x-lineageLookupReferenceObject: stvmajr
            x-lineageReferenceObject: ssrrmaj
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
