openapi: 3.0.0
info:
  title: direct-loan-originations-identifier
  description: API for RLADLOR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RLADLOR
  x-source-domain: Financial Aid
  x-source-title: Direct Loan Origination
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-loan-originations-identifier:
    get:
      tags:
        - direct-loan-originations-identifier
      summary: Return resources from RLADLOR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: true
          schema:
            type: string
        - name: ssn
          in: query
          description: Social Security Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCSID_SSN
        - name: statusCde
          in: query
          description: Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCSID_STATUS_CDE
        - name: birthDate
          in: query
          description: Date of Birth
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCSID_BIRTH_DATE
        - name: documentId
          in: query
          description: Document ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCSID_DOCUMENT_ID
        - name: lastName
          in: query
          description: Last Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCSID_LAST_NAME
        - name: seqNo
          in: query
          description: Sequence
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCSID_SEQ_NO
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-identifier-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/direct-loan-originations-identifier:
    post:
      tags:
        - direct-loan-originations-identifier QAPI (Query by POST)
      summary: Return resources from RLADLOR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-loan-originations-identifier-1.0.0_get_reque\
                st"
            example:
              keyblckAidyCode: 1718
              id: FASS30070
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-identifier-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    direct-loan-originations-identifier-1.0.0_get_request:
      required:
        - seqNo
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : RERCSID_LAST_NAME"
          x-lineageReferenceObject: RERCSID_LAST_NAME
        seqNo:
          title: Sequence
          maxLength: 3
          type: number
          description: "Lineage reference object : RERCSID_SEQ_NO"
          x-lineageReferenceObject: RERCSID_SEQ_NO
        statusCde:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_STATUS_CDE"
          x-lineageReferenceObject: RERCSID_STATUS_CDE
        documentId:
          title: Document ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_DOCUMENT_ID"
          x-lineageReferenceObject: RERCSID_DOCUMENT_ID
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        birthDate:
          title: Date of Birth
          type: string
          description: "Lineage reference object : RERCSID_BIRTH_DATE"
          format: date-time
          x-lineageReferenceObject: RERCSID_BIRTH_DATE
        ssn:
          title: Social Security Number
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_SSN"
          x-lineageReferenceObject: RERCSID_SSN
      x-lineageReferenceObject: RERCSID
    direct-loan-originations-identifier-1.0.0_get_response:
      required:
        - seqNo
      type: object
      properties:
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : RERCSID_LAST_NAME"
          x-lineageReferenceObject: RERCSID_LAST_NAME
        seqNo:
          title: Sequence
          maxLength: 3
          type: number
          description: "Lineage reference object : RERCSID_SEQ_NO"
          x-lineageReferenceObject: RERCSID_SEQ_NO
        statusCde:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_STATUS_CDE"
          x-lineageReferenceObject: RERCSID_STATUS_CDE
        documentId:
          title: Document ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_DOCUMENT_ID"
          x-lineageReferenceObject: RERCSID_DOCUMENT_ID
        birthDate:
          title: Date of Birth
          type: string
          description: "Lineage reference object : RERCSID_BIRTH_DATE"
          format: date-time
          x-lineageReferenceObject: RERCSID_BIRTH_DATE
        ssn:
          title: Social Security Number
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_SSN"
          x-lineageReferenceObject: RERCSID_SSN
      x-lineageReferenceObject: rercsid
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    direct-loan-originations-identifier-1.0.0_qapi_post:
      required:
        - id
        - keyblckAidyCode
      type: object
      properties:
        id:
          type: string
        keyblckAidyCode:
          type: string
        ssn:
          title: Social Security Number
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_SSN"
          x-lineageReferenceObject: RERCSID_SSN
        statusCde:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_STATUS_CDE"
          x-lineageReferenceObject: RERCSID_STATUS_CDE
        birthDate:
          title: Date of Birth
          type: string
          description: "Lineage reference object : RERCSID_BIRTH_DATE"
          format: date-time
          x-lineageReferenceObject: RERCSID_BIRTH_DATE
        documentId:
          title: Document ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCSID_DOCUMENT_ID"
          x-lineageReferenceObject: RERCSID_DOCUMENT_ID
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : RERCSID_LAST_NAME"
          x-lineageReferenceObject: RERCSID_LAST_NAME
        seqNo:
          title: Sequence
          maxLength: 3
          type: number
          description: "Lineage reference object : RERCSID_SEQ_NO"
          x-lineageReferenceObject: RERCSID_SEQ_NO
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
