openapi: 3.0.0
info:
  title: direct-loan-origination-student-data
  description: API for RLADLOR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: RLADLOR
  x-source-domain: Financial Aid
  x-source-title: Direct Loan Origination
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-loan-origination-student-data:
    get:
      tags:
        - direct-loan-origination-student-data
      summary: Return resources from RLADLOR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: true
          schema:
            type: string
        - name: firstName
          in: query
          required: false
          schema:
            type: string
        - name: email
          in: query
          required: false
          schema:
            type: string
        - name: mi
          in: query
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
        - name: displayRercsidLastName
          in: query
          required: false
          schema:
            type: string
        - name: dateSent
          in: query
          required: false
          schema:
            type: string
        - name: citzInd
          in: query
          required: false
          schema:
            type: string
        - name: documentId
          in: query
          required: false
          schema:
            type: string
        - name: driverLicNo
          in: query
          required: false
          schema:
            type: string
        - name: seqNo
          in: query
          required: false
          schema:
            type: string
        - name: cdstCodeLic
          in: query
          required: false
          schema:
            type: string
        - name: phoneNo
          in: query
          required: false
          schema:
            type: string
        - name: rercdedRjctCode
          in: query
          description: Edit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCDED_RJCT_CODE
        - name: rercdedErrorField
          in: query
          description: Edit Field
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCDED_ERROR_FIELD
        - name: rercdedErrorValue
          in: query
          description: Edit Value
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RERCDED_ERROR_VALUE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-origination-student-data-1.0.0_get_resp\
                    onse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/direct-loan-origination-student-data:
    post:
      tags:
        - direct-loan-origination-student-data QAPI (Query by POST)
      summary: Return resources from RLADLOR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-loan-origination-student-data-1.0.0_get_requ\
                est"
            example:
              keyblckAidyCode: 1718
              id: FASS30070
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-origination-student-data-1.0.0_get_resp\
                    onse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    direct-loan-origination-student-data-1.0.0_get_response:
      type: object
      properties:
        rercods:
          type: array
          items:
            required:
              - firstName
              - seqNo
            type: object
            properties:
              displayRercsidLastName:
                title: Last Name
                maxLength: 60
                type: string
              firstName:
                title: First Name
                maxLength: 60
                type: string
                description: "Lineage reference object : RERCODS_FIRST_NAME"
                x-lineageReferenceObject: RERCODS_FIRST_NAME
              citzInd:
                title: Citizenship Status Code
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODS_CITZ_IND"
                x-lineageReferenceObject: RERCODS_CITZ_IND
              cdstCodeLic:
                title: State or Province
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODS_CDST_CODE_LIC, Lookup lineage
                  reference object : RTVCDST"
                x-lineageReferenceObject: RERCODS_CDST_CODE_LIC
                x-lineageLookupReferenceObject: RTVCDST
              seqNo:
                title: Sequence
                maxLength: 3
                type: number
                description: "Lineage reference object : RERCODS_SEQ_NO"
                x-lineageReferenceObject: RERCODS_SEQ_NO
              documentId:
                title: Document ID
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODS_DOCUMENT_ID"
                x-lineageReferenceObject: RERCODS_DOCUMENT_ID
              driverLicNo:
                title: Driver's License Number
                maxLength: 20
                type: string
                description: "Lineage reference object : RERCODS_DRIVER_LIC_NO"
                x-lineageReferenceObject: RERCODS_DRIVER_LIC_NO
              dateSent:
                title: Date Sent
                type: string
                description: "Lineage reference object : RERCODS_DATE_SENT"
                format: date-time
                x-lineageReferenceObject: RERCODS_DATE_SENT
              mi:
                title: Middle Initial
                maxLength: 60
                type: string
                description: "Lineage reference object : RERCODS_MI"
                x-lineageReferenceObject: RERCODS_MI
              email:
                title: Email Address
                maxLength: 128
                type: string
                description: "Lineage reference object : RERCODS_EMAIL"
                x-lineageReferenceObject: RERCODS_EMAIL
              phoneNo:
                title: Phone
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODS_PHONE_NO"
                x-lineageReferenceObject: RERCODS_PHONE_NO
              status:
                title: Status
                maxLength: 30
                type: string
                description: "Lineage reference object : RERCODS_STATUS"
                x-lineageReferenceObject: RERCODS_STATUS
            x-lineageReferenceObject: rercods
        rercded_rercods:
          type: array
          items:
            type: object
            properties:
              rercdedRjctCode:
                title: Edit
                maxLength: 3
                type: string
                description: "Lineage reference object : RERCDED_RJCT_CODE"
                x-lineageReferenceObject: RERCDED_RJCT_CODE
              rercdedErrorField:
                title: Edit Field
                maxLength: 200
                type: string
                description: "Lineage reference object : RERCDED_ERROR_FIELD"
                x-lineageReferenceObject: RERCDED_ERROR_FIELD
              displayRjctDesc:
                title: Description
                maxLength: 65
                type: string
              rercdedErrorValue:
                title: Edit Value
                maxLength: 150
                type: string
                description: "Lineage reference object : RERCDED_ERROR_VALUE"
                x-lineageReferenceObject: RERCDED_ERROR_VALUE
            x-lineageReferenceObject: rercded_rercods
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    direct-loan-origination-student-data-1.0.0_qapi_post:
      required:
        - id
        - keyblckAidyCode
      type: object
      properties:
        id:
          type: string
        keyblckAidyCode:
          type: string
        firstName:
          type: string
        email:
          type: string
        mi:
          type: string
        status:
          type: string
        displayRercsidLastName:
          type: string
        dateSent:
          type: string
        citzInd:
          type: string
        documentId:
          type: string
        driverLicNo:
          type: string
        seqNo:
          type: string
        cdstCodeLic:
          type: string
        phoneNo:
          type: string
        rercdedRjctCode:
          title: Edit
          maxLength: 3
          type: string
          description: "Lineage reference object : RERCDED_RJCT_CODE"
          x-lineageReferenceObject: RERCDED_RJCT_CODE
        rercdedErrorField:
          title: Edit Field
          maxLength: 200
          type: string
          description: "Lineage reference object : RERCDED_ERROR_FIELD"
          x-lineageReferenceObject: RERCDED_ERROR_FIELD
        rercdedErrorValue:
          title: Edit Value
          maxLength: 150
          type: string
          description: "Lineage reference object : RERCDED_ERROR_VALUE"
          x-lineageReferenceObject: RERCDED_ERROR_VALUE
    direct-loan-origination-student-data-1.0.0_get_request:
      required:
        - firstName
        - seqNo
      type: object
      properties:
        citzInd:
          title: Citizenship Status Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODS_CITZ_IND"
          x-lineageReferenceObject: RERCODS_CITZ_IND
        seqNo:
          title: Sequence
          maxLength: 3
          type: number
          description: "Lineage reference object : RERCODS_SEQ_NO"
          x-lineageReferenceObject: RERCODS_SEQ_NO
        rercdedRjctCode:
          title: Edit
          maxLength: 3
          type: string
          description: "Lineage reference object : RERCDED_RJCT_CODE"
          x-lineageReferenceObject: RERCDED_RJCT_CODE
        rercdedErrorField:
          title: Edit Field
          maxLength: 200
          type: string
          description: "Lineage reference object : RERCDED_ERROR_FIELD"
          x-lineageReferenceObject: RERCDED_ERROR_FIELD
        phoneNo:
          title: Phone
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODS_PHONE_NO"
          x-lineageReferenceObject: RERCODS_PHONE_NO
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : RERCODS_FIRST_NAME"
          x-lineageReferenceObject: RERCODS_FIRST_NAME
        displayRercsidLastName:
          title: Last Name
          maxLength: 60
          type: string
        cdstCodeLic:
          title: State or Province
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODS_CDST_CODE_LIC, Lookup lineage
            reference object : RTVCDST"
          x-lineageReferenceObject: RERCODS_CDST_CODE_LIC
          x-lineageLookupReferenceObject: RTVCDST
        documentId:
          title: Document ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODS_DOCUMENT_ID"
          x-lineageReferenceObject: RERCODS_DOCUMENT_ID
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        driverLicNo:
          title: Driver's License Number
          maxLength: 20
          type: string
          description: "Lineage reference object : RERCODS_DRIVER_LIC_NO"
          x-lineageReferenceObject: RERCODS_DRIVER_LIC_NO
        mi:
          title: Middle Initial
          maxLength: 60
          type: string
          description: "Lineage reference object : RERCODS_MI"
          x-lineageReferenceObject: RERCODS_MI
        dateSent:
          title: Date Sent
          type: string
          description: "Lineage reference object : RERCODS_DATE_SENT"
          format: date-time
          x-lineageReferenceObject: RERCODS_DATE_SENT
        email:
          title: Email Address
          maxLength: 128
          type: string
          description: "Lineage reference object : RERCODS_EMAIL"
          x-lineageReferenceObject: RERCODS_EMAIL
        rercdedErrorValue:
          title: Edit Value
          maxLength: 150
          type: string
          description: "Lineage reference object : RERCDED_ERROR_VALUE"
          x-lineageReferenceObject: RERCDED_ERROR_VALUE
        status:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RERCODS_STATUS"
          x-lineageReferenceObject: RERCODS_STATUS
      x-lineageReferenceObject: RERCDED_RERCODS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
