openapi: 3.0.0
info:
  title: Academic Disciplines
  description: A range of academic disciplines offered by an organization.
  version: "7.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/academic-disciplines:
    get:
      summary: Return all resources
      description: Returns a paged listing of all the resources in the system.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-academic-disciplines.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource
      description: Create a new resource
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v7.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-disciplines.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v7+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-academic-disciplines.json"
  /api/academic-disciplines/{id}:
    get:
      summary: Return the requested resource
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Academic Disciplines for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v7.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-disciplines.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource
      description: Update the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_DISCIPLINES
      tags:
        - academic-disciplines
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Academic Disciplines for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v7.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-disciplines.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v7+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-academic-disciplines.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-academic-disciplines.json:
      title: Academic Disciplines
      description: A range of academic disciplines offered by an organization.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: A global identifier for an academic discipline.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
        abbreviation:
          title: Abbreviation
          description: An abbreviation that identifies an academic discipline.
          type: string
        title:
          title: Title
          description: The full name of an academic discipline.
          type: string
          minLength: 1
        description:
          title: Description
          description: A full description of an academic discipline.
          type: string
        type:
          title: Type
          description: A type of academic discipline.
          enum:
            - minor
            - major
            - concentration
          type: string
        reporting:
          title: Reporting
          description: Properties required for governmental or other reporting
          type: array
          items:
            type: object
            properties:
              country:
                title: Country
                description: The country with specific reporting requirements
                oneOf:
                  - title: USA
                    description: Reporting requirements for the United States of America
                    type: object
                    properties:
                      code:
                        title: Code
                        description: The ISO 3166 alpha-3 country code for the United States of America.
                        enum:
                          - USA
                        type: string
                      cipCode:
                        title: CIP Code
                        description: The discipline code in the Classification of Instructional Programs
                          (CIP)
                        type: string
                    additionalProperties: false
                    required:
                      - code
            additionalProperties: false
      required:
        - id
        - title
        - type
      additionalProperties: false
