openapi: 3.0.0
info:
  title: ca-schedule-calendars
  description: API for SSAACCL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SSAACCL
  x-source-domain: Student
  x-source-title: Schedule Calendar (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-schedule-calendars:
    get:
      tags:
        - ca-schedule-calendars
      summary: Return resources from SSAACCL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckTermCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckCrn
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-schedule-calendars-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-schedule-calendars:
    post:
      tags:
        - ca-schedule-calendars QAPI (Query by POST)
      summary: Return resources from SSAACCL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-schedule-calendars-1.0.0_get_request"
            example:
              keyblckTermCode: 200323
              keyblckCrn: 30030
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-schedule-calendars-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    ca-schedule-calendars-1.0.0_get_response:
      required:
        - censusEnrlDate
      type: object
      properties:
        acclDesc:
          type: string
        census2Enrl:
          title: Census Two Enrollment
          maxLength: 6
          type: number
          description: "Lineage reference object : SSBSECT_CENSUS_2_ENRL"
          x-lineageReferenceObject: SSBSECT_CENSUS_2_ENRL
        acclCode:
          title: Academic Calendar Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SSBSECT_ACCL_CODE, Lookup lineage
            reference object : stvaccl"
          x-lineageReferenceObject: SSBSECT_ACCL_CODE
          x-lineageLookupReferenceObject: stvaccl
        rfndCutOffDate:
          title: Last Date for Refund
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_REFUND_CUTOFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_REFUND_CUTOFF_DATE
        sectStartDate:
          title: Calculated Section Start Date
          maxLength: 11
          type: string
          format: date-time
        census2Date:
          title: Census Two Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_CENSUS_2_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_CENSUS_2_DATE
        enrl:
          title: Enrollment
          maxLength: 6
          type: number
          description: "Lineage reference object : SSBSECT_ENRL"
          x-lineageReferenceObject: SSBSECT_ENRL
        ptrmDesc:
          type: string
        ptrmCode:
          title: Part of Term
          maxLength: 3
          type: string
          description: "Lineage reference object : SSBSECT_PTRM_CODE, Lookup lineage
            reference object : stvptrm"
          x-lineageReferenceObject: SSBSECT_PTRM_CODE
          x-lineageLookupReferenceObject: stvptrm
        sectBeginDate:
          title: Session Begin Date
          maxLength: 11
          type: string
          format: date-time
        ptrmWeeks:
          title: Part of Term Number of Weeks
          maxLength: 4
          type: number
          description: "Lineage reference object : SSBSECT_PTRM_WEEKS"
          x-lineageReferenceObject: SSBSECT_PTRM_WEEKS
        censusEnrl:
          title: Census One Enrollment
          maxLength: 6
          type: number
          description: "Lineage reference object : SSBSECT_CENSUS_ENRL"
          x-lineageReferenceObject: SSBSECT_CENSUS_ENRL
        censusEnrlDate:
          title: Census One Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_CENSUS_ENRL_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_CENSUS_ENRL_DATE
        ptrmEndDate:
          title: Section End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_PTRM_END_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_PTRM_END_DATE
        acadCutOffDate:
          title: Last Date to Record Academic History
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_ACAD_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_ACAD_CUT_OFF_DATE
        dropCutOffDate:
          title: Last Date to Drop without a Penalty
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_DROP_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_DROP_CUT_OFF_DATE
        enrlCutOffDate:
          title: Last Date to Enroll
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_ENRL_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_ENRL_CUT_OFF_DATE
        sectNumDay:
          title: Number of Days
          maxLength: 6
          type: number
        sectNumWeek:
          title: Session Number of Weeks
          maxLength: 6
          type: number
        sectEndDate:
          title: Session End Date
          maxLength: 11
          type: string
          format: date-time
        ptrmStartDate:
          title: Section Begin Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBSECT_PTRM_START_DATE"
          format: date-time
          x-lineageReferenceObject: SSBSECT_PTRM_START_DATE
      x-lineageReferenceObject: ssbsect
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-schedule-calendars-1.0.0_get_request:
      type: object
      properties:
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        keyblckCrn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckCrn"
          x-lineageReferenceObject: keyblckCrn
      x-lineageReferenceObject: KEY_BLOCK
    ca-schedule-calendars-1.0.0_qapi_post:
      type: object
      properties:
        keyblckTermCode:
          type: string
        keyblckCrn:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
