openapi: 3.0.0
info:
  title: active-cashier-sessions
  description: API for TGACSPV administrative page
  version: 1.0.0
  extensions:
    x-audience: all
    x-release-status: beta
    x-source-name: TGACSPV
    x-source-domain: Student
    x-source-title: Cashier Supervisory Form
    x-source-system: banner
    x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/active-cashier-sessions:
    get:
      tags:
      - active-cashier-sessions
      summary: Return resources from TGACSPV
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
          exampleSetFlag: false
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
          exampleSetFlag: false
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
          exampleSetFlag: false
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
          exampleSetFlag: false
      - name: user
        in: query
        description: User
        required: false
        schema:
          type: string
          exampleSetFlag: false
        extensions:
          x-lineageReferenceObject: TBVSESS_USER
      - name: startDate
        in: query
        description: Start Date
        required: false
        schema:
          type: string
          exampleSetFlag: false
        extensions:
          x-lineageReferenceObject: TBVSESS_START_DATE
      - name: endDate
        in: query
        description: End Date
        required: false
        schema:
          type: string
          exampleSetFlag: false
        extensions:
          x-lineageReferenceObject: TBVSESS_END_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
                exampleSetFlag: false
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
                exampleSetFlag: false
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
                exampleSetFlag: false
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/active-cashier-sessions-1.0.0_get_response"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/active-cashier-sessions:
    post:
      tags:
      - active-cashier-sessions QAPI (Query by POST)
      summary: Return resources from TGACSPV
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/active-cashier-sessions-1.0.0_qapi_post_request"
              exampleSetFlag: false
            example:
              endDate: 2024-07-24
              user: BATCHUSER
              startDate: 2024-07-24
            exampleSetFlag: true
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
                exampleSetFlag: false
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
                exampleSetFlag: false
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
                exampleSetFlag: false
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/active-cashier-sessions-1.0.0_qapi_post_response"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          exampleSetFlag: false
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
                exampleSetFlag: false
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
                exampleSetFlag: false
              code:
                type: string
                description: The error message code used to describe the error details.
                exampleSetFlag: false
              description:
                type: string
                description: The error description used to describe the error details.
                exampleSetFlag: false
              message:
                type: string
                description: 'The detailed actionable error message. '
                exampleSetFlag: false
            exampleSetFlag: false
            types:
            - object
          types:
          - array
      exampleSetFlag: false
      types:
      - object
    active-cashier-sessions-1.0.0_qapi_post_request:
      type: object
      properties:
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVSESS_END_DATE"
          format: date-time
          extensions:
            x-lineageReferenceObject: TBVSESS_END_DATE
          exampleSetFlag: false
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVSESS_USER"
          extensions:
            x-lineageReferenceObject: TBVSESS_USER
          exampleSetFlag: false
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVSESS_START_DATE"
          format: date-time
          extensions:
            x-lineageReferenceObject: TBVSESS_START_DATE
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: TBVSESS
      exampleSetFlag: false
    active-cashier-sessions-1.0.0_get_response:
      type: object
      properties:
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVSESS_END_DATE"
          format: date-time
          extensions:
            x-lineageReferenceObject: TBVSESS_END_DATE
          exampleSetFlag: false
        startTime:
          title: Start Time
          maxLength: 8
          type: string
          description: "Lineage reference object : TBVSESS_START_TIME"
          extensions:
            x-lineageReferenceObject: TBVSESS_START_TIME
          exampleSetFlag: false
        endTime:
          title: End Time
          maxLength: 8
          type: string
          description: "Lineage reference object : TBVSESS_END_TIME"
          extensions:
            x-lineageReferenceObject: TBVSESS_END_TIME
          exampleSetFlag: false
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVSESS_USER"
          extensions:
            x-lineageReferenceObject: TBVSESS_USER
          exampleSetFlag: false
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVSESS_START_DATE"
          format: date-time
          extensions:
            x-lineageReferenceObject: TBVSESS_START_DATE
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: tbvsess
      exampleSetFlag: false
    active-cashier-sessions-1.0.0_qapi_post_response:
      type: object
      properties:
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVSESS_END_DATE"
          format: date-time
          extensions:
            x-lineageReferenceObject: TBVSESS_END_DATE
          exampleSetFlag: false
        startTime:
          title: Start Time
          maxLength: 8
          type: string
          description: "Lineage reference object : TBVSESS_START_TIME"
          extensions:
            x-lineageReferenceObject: TBVSESS_START_TIME
          exampleSetFlag: false
        endTime:
          title: End Time
          maxLength: 8
          type: string
          description: "Lineage reference object : TBVSESS_END_TIME"
          extensions:
            x-lineageReferenceObject: TBVSESS_END_TIME
          exampleSetFlag: false
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVSESS_USER"
          extensions:
            x-lineageReferenceObject: TBVSESS_USER
          exampleSetFlag: false
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVSESS_START_DATE"
          format: date-time
          extensions:
            x-lineageReferenceObject: TBVSESS_START_DATE
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: tbvsess
      exampleSetFlag: false
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
