openapi: 3.0.0
info:
  title: special-interest-course-data-copy
  description: API for SKADRCO administrative page
  version: 1.0.0
  x-source-name: SKADRCO
  x-source-title: Course File Data
  x-source-system: banner
  x-api-type: bus-poc
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/special-interest-course-data-copy:
    post:
      tags:
        - special-interest-course-data-copy
      summary: Creates a new resource in SKADRCO
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/special-interest-course-data-copy-1.0.0_post_reques\
                t"
            example:
              termCodeEff: 202002
              smrprleProgram: BN-BPARAMED
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/special-interest-course-data-copy-1.0.0_post_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/special-interest-course-data-copy: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    special-interest-course-data-copy-1.0.0_post_response:
      required:
        - specialCrsType
        - specialEffFromDate
      type: object
      properties:
        activityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : SORCSPL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORCSPL_ACTIVITY_DATE
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORCSPL_ACTIVE_IND"
          x-lineageReferenceObject: SORCSPL_ACTIVE_IND
        courseCde:
          type: string
          description: "Lineage reference object : SORCSPL_COURSE_CDE"
          x-lineageReferenceObject: SORCSPL_COURSE_CDE
        statusCde:
          title: Status
          type: string
          description: "Lineage reference object : SORCSPL_STATUS_CDE"
          x-lineageReferenceObject: SORCSPL_STATUS_CDE
        specialCrsTypeDesc:
          type: string
        specialEffFromDate:
          title: Effective From Date
          type: string
          description: "Lineage reference object : SORCSPL_SPECIAL_EFF_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORCSPL_SPECIAL_EFF_FROM_DATE
        specialCrsType:
          title: Special Interest Course Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SORCSPL_SPECIAL_CRS_TYPE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORCSPL_SPECIAL_CRS_TYPE
          x-lineageLookupReferenceObject: SKRRVAL
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SORCSPL_USER_ID"
          x-lineageReferenceObject: SORCSPL_USER_ID
        specialEffToDate:
          title: Effective To Date
          type: string
          description: "Lineage reference object : SORCSPL_SPECIAL_EFF_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORCSPL_SPECIAL_EFF_TO_DATE
      x-lineageReferenceObject: sorcspl
    special-interest-course-data-copy-1.0.0_post_request:
      type: object
      properties:
        termCodeEff:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : termCodeEff, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCodeEff
          x-lineageLookupReferenceObject: stvterm
        smrprleProgram:
          title: Program
          maxLength: 12
          type: string
          description: "Lineage reference object : smrprleProgram, Lookup lineage
            reference object : smrprle"
          x-lineageReferenceObject: smrprleProgram
          x-lineageLookupReferenceObject: smrprle
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
