openapi: 3.0.0
info:
  title: contract-authorization-contract-number-text
  description: API for TSACONT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TSACONT
  x-source-domain: Student
  x-source-title: Contract Authorization
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/contract-authorization-contract-number-text:
    get:
      tags:
        - contract-authorization-contract-number-text
      summary: Return resources from TSACONT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: contractNumber
          in: query
          required: false
          schema:
            type: string
        - name: keyblocTermCode
          in: query
          required: false
          schema:
            type: string
        - name: text
          in: query
          description: Additional Text
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBBCCTX_TEXT
        - name: printInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBBCCTX_PRINT_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-authorization-contract-number-text-1.0.0_g\
                    et_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/contract-authorization-contract-number-text:
    post:
      tags:
        - contract-authorization-contract-number-text QAPI (Query by POST)
      summary: Return resources from TSACONT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/contract-authorization-contract-number-text-1.0.0_g\
                et_request"
            example:
              keyblocTermCode: 201610
              contractNumber: 1
              id: 123INC
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-authorization-contract-number-text-1.0.0_g\
                    et_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    contract-authorization-contract-number-text-1.0.0_get_response:
      type: object
      properties:
        printInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCCTX_PRINT_IND"
          x-lineageReferenceObject: TBBCCTX_PRINT_IND
        text:
          title: Additional Text
          maxLength: 60
          type: string
          description: "Lineage reference object : TBBCCTX_TEXT"
          x-lineageReferenceObject: TBBCCTX_TEXT
      x-lineageReferenceObject: tbbcctx
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    contract-authorization-contract-number-text-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        contractNumber:
          type: string
        keyblocTermCode:
          type: string
        text:
          title: Additional Text
          maxLength: 60
          type: string
          description: "Lineage reference object : TBBCCTX_TEXT"
          x-lineageReferenceObject: TBBCCTX_TEXT
        printInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCCTX_PRINT_IND"
          x-lineageReferenceObject: TBBCCTX_PRINT_IND
    contract-authorization-contract-number-text-1.0.0_get_request:
      type: object
      properties:
        keyblocTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCode
          x-lineageLookupReferenceObject: stvterm
        printInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCCTX_PRINT_IND"
          x-lineageReferenceObject: TBBCCTX_PRINT_IND
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Lineage reference object : contractNumber"
          x-lineageReferenceObject: contractNumber
        id:
          title: Contract ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        text:
          title: Additional Text
          maxLength: 60
          type: string
          description: "Lineage reference object : TBBCCTX_TEXT"
          x-lineageReferenceObject: TBBCCTX_TEXT
      x-lineageReferenceObject: TBBCCTX
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
