openapi: 3.0.0
info:
  title: Enrollment Student Steps
  description: This QAPI returns the applicant information by step to be used in the ARSAESA process.
  version: 1.0.0
  x-source-domain: Student
  x-source-system: Banner
  x-api-type: erp
  x-release-status: ga
  x-audience: all
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /qapi/enrollment-student-steps:
    post:
      tags:
        - enrollment-student-steps QAPI
      summary: Return the applicant information by step.
      description: Queries for the requested resource using a set of attributes provided in the post
        request body.  Please note the path to the server is overridden to use /qapi/{resource} 
        in the URL and not /api/{resource}.

        Return the applicant information by step.
      parameters:
        - name: limit
          in: query
          description:
            The maximum number of resources requesting for this result set.
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/enrollment-student-steps-1.0.0_qapi_post_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client�s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - BearerAuth: []
        - BasicAuth: []
      x-method-permission: API_ENROLLMENT_STUDENT_STEPS
components:
  schemas:
    enrollment-student-steps-1.0.0_qapi_post_request:
      type: object
      required:
        - guid   
        - termCode     
        - program
      properties:              
        guid:
          title: GUID
          maxLength: 36
          type: string
          description: Student's GUID.
          x-lineageReferenceObject: GORGUID_GUID
        termCode: 
          title: Term Code
          maxLength: 6
          type: string
          description: The term code associated with the applicant.
          x-lineageReferenceObject: STVTERM_CODE
        program:
          title: Program
          maxLength: 12
          type: string
          description: The program selected by the applicant.      
          x-lineageLookupReferenceObject: SMPRPRLE_PROGRAM
        lcurSeqNo:
          title: Base Rule Number
          maxLength: 8
          type: string
          description: The base rule number associated to the applicant.        
          x-lineageLookupReferenceObject: SORLCUR_SEQNO
        lfosSeqNo:
          title: Field of Study
          maxLength: 22
          type: string
          description: The field of study associated to the applicant.         
          x-lineageLookupReferenceObject: SORLFOS_SEQNO
        levlCode:
          title: Level Code
          maxLength: 8
          type: string
          description: The level code associated to the applicant.      
          x-lineageLookupReferenceObject: STVLEVL_CODE
        stypCode:
          title: Student Type Code 
          maxLength: 4
          type: string
          description: The student type code associated to the applicant.        
          x-lineageLookupReferenceObject: SARADAP_STYP_CODE
        fieldOfStudy:
          title: Field of Study
          type: array
          items:
            type: object
            properties:
              majorCode:
                  title: Field of Study
                  maxLength: 30
                  type: string
                  description: The major code associated to the applicant.
                  x-lineageReferenceObject: SOVLFOS_MAJR_CODE
              sequenceNumber:
                  title: Sequence Number
                  type: integer
                  description: The sequence number associated to the applicant's field of study.
                  x-lineageReferenceObject: SOVLFOS_SEQNO
              typeCode:
                  title: Type Code
                  maxLength: 4
                  type: string
                  description: The type code associated to the applicant's field of study.
                  x-lineageReferenceObject: SOVLFOS_LFST_CODE
    enrollment-student-steps-1.0.0_qapi_post_response:
      type: object
      required:
        - studentTypeByStep
        - gurocfgConfigurations
        - installmentPlan    
      properties:
        studentTypeByStep:
          title: Header
          type: object
          properties:
            TVRRSST_STU_TYPE:
              title: Student Type
              type: string
              description: The student type associated with the applicant.
              x-lineageReferenceObject: TVRRSST_STU_TYPE
            TVRRSST_LCUR_SEQNO:
              title: Current Rule
              type: integer
              description: The current rule number associated with the applicant.
              x-lineageReferenceObject: TVRRSST_LCUR_SEQNO
            TVRRSST_LFOS_SEQNO:
              title: Field of Study Rule
              type: integer
              description: The field of study rule associated with the applicant.
              x-lineageReferenceObject: TVRRSST_LFOS_SEQNO
            TVRRSST_STSP_KEY_SEQUENCE:
              title: Step Key Sequence
              type: integer
              description: The step key sequence associated with the applicant.
              x-lineageReferenceObject: TVRRSST_STSP_KEY_SEQUENCE
            LEARNER:
              title: Learner
              type: string
              description: The learner type associated with the applicant.
              x-lineageReferenceObject: LEARNER
            ADMISSIONS:
              title: Admissions
              type: string
              description: The admissions type associated with the applicant.
              x-lineageReferenceObject: ADMISSIONS
            MAJOR:
              title: Major
              type: string
              description: The major associated with the applicant.
              x-lineageReferenceObject: MAJOR
        gurocfgConfigurations: 
          title: Gurocfg Configurations
          type: object
          properties:
            admissionToEnroll.finance.enrollment.status:
              title: Admission To Enroll Finance Enrollment Status
              type: string
              description: Admission to enroll finance enrollment status benefit.
            admissionToEnroll.finance.inactive.registration.type:
              title: Admission To Enroll Finance Inactive Registration Type
              type: string
              description: Admission to enroll finance inactive registration type benefit.
            admissionToEnroll.student.new:
              title: Admission To Enroll Student New
              type: string
              description: Admission to enroll student new benefit.
            admissionToEnroll.student.old:
              title: Admission To Enroll Student Old
              type: string
              description: Admission to enroll student old benefit.
            admissionToEnroll.tvperol.student.enrolled:
              title: Admission To Enroll TVPEROL Student Enrolled
              type: string
              description: Admission to enroll TVPEROL student enrolled benefit.

        installmentPlan:
          title: Installment Plan
          type: object
          required:
            - isValidPlan
          properties:
            installmentPlan: 
              title: Installment Plan
              type: string
              description: Installment plan benefit.
              x-lineageReferenceObject: TVRTRDP_INSTALLMENT_PLAN
            isValidPlan:
              title: Is Valid Plan
              type: boolean
              description: Indicates if the installment plan is valid.
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: The detailed actionable error message.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic
