openapi: 3.0.0
info:
  title: person-identifications
  description: >
    Retrieves the list of all the various identification information for persons
    matching the identifiers provided.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Foundation
  x-source-title: Person Identifications
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: person-identifications
paths:
  /api/person-identifications:
    get:
      description: >
        __Paging:__ Pagination is not supported.

          __Sorting:__ Sorting is not supported.
            
          __Filtering:__ Filtering is not supported.
         
         All parameters are __optional__ and __repeatable__. At least one of the optional parameters should be provided.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_IDENTIFICATIONS
      tags:
        - person-identifications
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
        - name: bannerId
          in: query
          required: false
          schema:
            type: string
          example: S12345678
          description: The identification number used to access a person
        - name: enterpriseId
          in: query
          required: false
          schema:
            type: string
          example: XXXX-XXXX
          description: The identifier used by BEIS for identity synchronization
        - name: ldapUserMapping
          in: query
          required: false
          schema:
            type: string
          example: rjones
          description: The identifier used in GOBTPAC for mapping ldap authentication
            (GOBTPAC_LDAP_USER)
        - name: externalUser
          in: query
          required: false
          schema:
            type: string
          example: rsmith1
          description: The username generated by Banner for new accounts
            (GOBTPAC_EXTERNAL_USER)
        - name: sourcedId
          in: query
          required: false
          schema:
            type: string
          example: S87654321
          description: >-
            The Permanent, unique identifier for a person required for IMS data
            transfers

                 /api/person-identifications?bannerId=S12345678&enterpriseId=XXXX-XXXX&ldapUserMapping=rjones&externalUser=rsmith1&sourcedId=S87654321
      responses:
        "200":
          description: Success
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/person-identifications"
            application/vnd.hedtech.integration.v1.0.0+xml:
              schema:
                type: object
                $ref: "#/components/schemas/person-identifications"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    person-identifications:
      type: array
      items:
        type: object
        properties:
          bannerId:
            type: string
          dataOrigin:
            type: string
          enterpriseId:
            type: string
          firstName:
            type: string
          fullName:
            type: string
          guid:
            type: string
          imsSourcedIdBase:
            type: object
            properties:
              sourcedId:
                type: string
          lastName:
            type: string
          middleName:
            type: string
          surnamePrefix:
            type: string
          thirdPartyAccess:
            type: object
            properties:
              externalUser:
                type: string
              ldapUserMapping:
                type: string
