openapi: 3.0.0
info:
  title: research-accounting-billing-detail-inquiry
  description: API for FRIBDET administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FRIBDET
  x-source-domain: Finance
  x-source-title: Research Accounting Billing Detail Inquiry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/research-accounting-billing-detail-inquiry:
    get:
      tags:
        - research-accounting-billing-detail-inquiry
      summary: Return resources from FRIBDET
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckGrntCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckCoasCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckPmsCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckFundCode
          in: query
          required: false
          schema:
            type: string
        - name: code
          in: query
          required: false
          schema:
            type: string
        - name: title
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/research-accounting-billing-detail-inquiry-1.0.0_ge\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/research-accounting-billing-detail-inquiry:
    post:
      tags:
        - research-accounting-billing-detail-inquiry QAPI (Query by POST)
      summary: Return resources from FRIBDET
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/research-accounting-billing-detail-inquiry-1.0.0_ge\
                t_request"
            example:
              keyblckFundCode: 1
              keyblckCoasCode: B
              keyblckGrntCode: 146161
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/research-accounting-billing-detail-inquiry-1.0.0_ge\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    research-accounting-billing-detail-inquiry-1.0.0_get_request:
      required:
        - keyblckCoasCode
        - code
      type: object
      properties:
        keyblckFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckFundCode"
          x-lineageReferenceObject: keyblckFundCode
        keyblckPmsCode:
          title: PMS Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckPmsCode"
          x-lineageReferenceObject: keyblckPmsCode
        keyblckCoasCode:
          title: COA
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckCoasCode"
          x-lineageReferenceObject: keyblckCoasCode
        code:
          title: Frbgrnt Code
          maxLength: 9
          type: string
          description: "Lineage reference object : FRBGRNT_CODE"
          x-lineageReferenceObject: FRBGRNT_CODE
        keyblckGrntCode:
          title: Grant
          maxLength: 9
          type: string
          description: "Lineage reference object : keyblckGrntCode"
          x-lineageReferenceObject: keyblckGrntCode
        title:
          title: Frbgrnt Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FRBGRNT_TITLE"
          x-lineageReferenceObject: FRBGRNT_TITLE
      x-lineageReferenceObject: FRBGRNT
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    research-accounting-billing-detail-inquiry-1.0.0_get_response:
      type: object
      properties:
        frbgrnt:
          type: array
          items:
            required:
              - code
            type: object
            properties:
              code:
                title: Frbgrnt Code
                maxLength: 9
                type: string
                description: "Lineage reference object : FRBGRNT_CODE"
                x-lineageReferenceObject: FRBGRNT_CODE
              title:
                title: Frbgrnt Title
                maxLength: 35
                type: string
                description: "Lineage reference object : FRBGRNT_TITLE"
                x-lineageReferenceObject: FRBGRNT_TITLE
            x-lineageReferenceObject: frbgrnt
        total_block:
          type: array
          items:
            type: object
            properties:
              billedTotalAmtPms:
                title: Total Billed
                maxLength: 25
                type: number
                description: "Lineage reference object : billedTotalAmtPms"
                x-lineageReferenceObject: billedTotalAmtPms
              refundsTotalAmt:
                title: Total Refunds
                maxLength: 31
                type: number
                description: "Lineage reference object : refundsTotalAmt"
                x-lineageReferenceObject: refundsTotalAmt
              witholdPmtTotalAmt:
                title: Payment Withholding
                maxLength: 31
                type: number
                description: "Lineage reference object : witholdPmtTotalAmt"
                x-lineageReferenceObject: witholdPmtTotalAmt
              expenditureTotalAmt:
                title: Total Expenditures
                maxLength: 31
                type: number
                description: "Lineage reference object : expenditureTotalAmt"
                x-lineageReferenceObject: expenditureTotalAmt
              unbilledTotalAmtPms:
                title: Total Unbilled
                maxLength: 25
                type: number
                description: "Lineage reference object : unbilledTotalAmtPms"
                x-lineageReferenceObject: unbilledTotalAmtPms
              billedTotalAmt:
                title: Total Billed
                maxLength: 31
                type: number
                description: "Lineage reference object : billedTotalAmt"
                x-lineageReferenceObject: billedTotalAmt
              paymentsTotalAmt:
                title: Payments and Transfers
                maxLength: 31
                type: number
                description: "Lineage reference object : paymentsTotalAmt"
                x-lineageReferenceObject: paymentsTotalAmt
              witholdPmtTotalAmtPms:
                title: Total Payment Withholding
                maxLength: 25
                type: number
                description: "Lineage reference object : witholdPmtTotalAmtPms"
                x-lineageReferenceObject: witholdPmtTotalAmtPms
              expenditureTotalAmtPms:
                title: Total Expenditures
                maxLength: 25
                type: number
                description: "Lineage reference object : expenditureTotalAmtPms"
                x-lineageReferenceObject: expenditureTotalAmtPms
              paymentsTotalAmtPms:
                title: Total Payments and Transfers
                maxLength: 25
                type: number
                description: "Lineage reference object : paymentsTotalAmtPms"
                x-lineageReferenceObject: paymentsTotalAmtPms
              dispTotalAmt10:
                title: Total
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt10"
                x-lineageReferenceObject: dispTotalAmt10
              witholdChrgTotalAmtPms:
                title: Total Retainage Withholding
                maxLength: 25
                type: number
                description: "Lineage reference object : witholdChrgTotalAmtPms"
                x-lineageReferenceObject: witholdChrgTotalAmtPms
              dispTotalAmt1:
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt1"
                x-lineageReferenceObject: dispTotalAmt1
              holdTotalAmtPms:
                title: Total On-Hold
                maxLength: 25
                type: number
                description: "Lineage reference object : holdTotalAmtPms"
                x-lineageReferenceObject: holdTotalAmtPms
              witholdChrgTotalAmt:
                title: Retainage Withholding
                maxLength: 31
                type: number
                description: "Lineage reference object : witholdChrgTotalAmt"
                x-lineageReferenceObject: witholdChrgTotalAmt
              dispTotalAmt4:
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt4"
                x-lineageReferenceObject: dispTotalAmt4
              dispTotalAmt5:
                title: Total
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt5"
                x-lineageReferenceObject: dispTotalAmt5
              dispTotalAmt2:
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt2"
                x-lineageReferenceObject: dispTotalAmt2
              dispTotalAmt3:
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt3"
                x-lineageReferenceObject: dispTotalAmt3
              unbilledTotalAmt:
                title: Total Unbilled
                maxLength: 31
                type: number
                description: "Lineage reference object : unbilledTotalAmt"
                x-lineageReferenceObject: unbilledTotalAmt
              refundsTotalAmtPms:
                title: Total Refunds
                maxLength: 25
                type: number
                description: "Lineage reference object : refundsTotalAmtPms"
                x-lineageReferenceObject: refundsTotalAmtPms
              dispTotalAmt:
                title: Total
                maxLength: 31
                type: number
                description: "Lineage reference object : dispTotalAmt"
                x-lineageReferenceObject: dispTotalAmt
              dispTotalAmt8:
                title: Total
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt8"
                x-lineageReferenceObject: dispTotalAmt8
              dispTotalAmt9:
                title: Total
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt9"
                x-lineageReferenceObject: dispTotalAmt9
              dispTotalAmt6:
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt6"
                x-lineageReferenceObject: dispTotalAmt6
              dispTotalAmt7:
                title: Total
                maxLength: 25
                type: number
                description: "Lineage reference object : dispTotalAmt7"
                x-lineageReferenceObject: dispTotalAmt7
              holdTotalAmt:
                title: Total On-Hold
                maxLength: 31
                type: number
                description: "Lineage reference object : holdTotalAmt"
                x-lineageReferenceObject: holdTotalAmt
            x-lineageReferenceObject: total_block
    research-accounting-billing-detail-inquiry-1.0.0_qapi_post:
      type: object
      properties:
        keyblckGrntCode:
          type: string
        keyblckCoasCode:
          type: string
        keyblckPmsCode:
          type: string
        keyblckFundCode:
          type: string
        code:
          type: string
        title:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
