openapi: 3.0.0
info:
  title: Person Visas
  description: >
    Person visas API processes the details of visas issued to a person.


    Please refer to "API Integration Configuration Settings" section in the Banner Ethos API Handbook" for details on API configuration settings that needs to be configured for this API.
  version: "11.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/person-visas:
    get:
      summary: Returns resources from GORVISA
      description: >
        Returns a paged listing of all the person visa records from GORVISA
        table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_VISAS
      tags:
        - person-visas
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Person  

            Returns all visa records for the person guid passed.

            ```

            /person-visas?criteria={"person":{"id":"2582835d-3e14-435b-b74f-4311746987ce"}}

            ```

            ### Visa Type Category  

            Returns all visa records for the visa type category passed.

            ```

            /person-visas?criteria={"visaType":{"category":"nonImmigrant"}}

            ```

            ### Visa Type Detail  

            Returns all visa records for the visa type detail guid passed.

            ```

            /person-visas?criteria={"visaType":{"detail":{"id":"99b0f599-38d3-4809-b19f-15cad248fd24"}}}

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-person-visas.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource in GORVISA
      description: >
        POST requests must include a nil GUID value
        ("00000000-0000-0000-0000-000000000000") for the root id property.


        Creates a new person visa record in GORVISA table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_VISAS
      tags:
        - person-visas
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v11+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-visas.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-person-visas.json"
  /api/person-visas/{id}:
    get:
      summary: Return the requested resource from GORVISA
      description: |
        Returns a single person visa record with the requested identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_VISAS
      tags:
        - person-visas
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v11+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-visas.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource from GORVISA
      description: >
        Updates the person visa record in GORVISA table with the requested
        identifier. Note that the person and visaType properties cannot be
        changed.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_VISAS
      tags:
        - person-visas
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Person Visas for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v11+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-visas.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-person-visas.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-person-visas.json:
      title: Person Visas
      description: Visas issued to a person.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: A global identifier of a visa record
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GORVISA_GUID(GORVISA)
        person:
          title: Person
          description: The person to whom the visa was issued
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Person.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: persons 
              x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = persons) 
              x-lineageDerivedLogic: A record in GORGUID with GORGUID_LDM_NAME as 'persons' will refer to each SPRIDEN_PIDM in SPRIDEN.
          additionalProperties: false
          required:
            - id
        visaType:
          title: Visa Type
          description: A type of a visa
          type: object
          properties:
            category:
              title: Category
              description: A global category of visa types
              enum:
                - immigrant
                - nonImmigrant
              type: string
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: For the value in GORVISA_VTYP_CODE, if STVVTYP_NON_RES_IND is 'Y' display as 'nonImmigrant' and if STVVTYP_NON_RES_IND is not 'Y' then display as 'immigrant'
            detail:
              title: Detail
              description: ""
              oneOf:
                - type: object
                  properties:
                    id:
                      title: ID
                      description: The global identifier for the Detail.
                      type: string
                      format: guid
                      pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                      x-lineageLookupReferenceObject: visa-types 
                      x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = visa-types) 
                      x-lineageDerivedLogic: A record in GORGUID with GORGUID_LDM_NAME as 'visa-types' will refer to the GORVISA_VTYP_CODE in GORVISA.
                  additionalProperties: false
                  required:
                    - id
                - type: object
                  maxProperties: 0
          additionalProperties: false
          minProperties: 1
          required:
            - category
        visaId:
          title: Visa Identifier
          description: The identifier of the visa
          type: string
          x-lineageReferenceObject: GORVISA_VISA_NUMBER(GORVISA)
        status:
          title: Status
          description: Visa status
          oneOf:
            - type: string
              enum:
                - current
                - expired
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: If the current date is greater than GORVISA_VISA_EXPIRE_DATE then display as 'expired', else display as  'current'
            - type: string
              maxLength: 0
        requestedOn:
          title: Date Requested
          description: The date when the visa was requested
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: GORVISA_VISA_REQ_DATE(GORVISA)
            - type: string
              maxLength: 0
        issuedOn:
          title: Date Issued
          description: The date when the visa was issued
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: GORVISA_VISA_ISSUE_DATE(GORVISA)
            - type: string
              maxLength: 0
        expiresOn:
          title: Expires On
          description: The visa expiration date
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: GORVISA_VISA_EXPIRE_DATE(GORVISA)
            - type: string
              maxLength: 0
        entries:
          title: Entries
          description: Entries into the country on this visa
          type: array
          items:
            type: object
            properties:
              enteredOn:
                title: Entered On
                description: The date of entry
                oneOf:
                  - type: string
                    format: date-time
                    pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                    x-lineageReferenceObject: GORVISAM_ENTERED_ON(GORVISAM)
                  - type: string
                    maxLength: 0
            additionalProperties: false
      required:
        - id
        - person
        - visaType
      additionalProperties: false

