openapi: 3.0.0
info:
  title: Room Types
  description: A list of custom room types.
  version: "6.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhostn
paths:
  /api/room-types:
    get:
      summary: Return all resources
      description: Returns the room type record of type 'classroom'
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ROOM_TYPES
      tags:
        - room-types
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-room-types.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/room-types/{id}:
    get:
      summary: Return the requested resource
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ROOM_TYPES
      tags:
        - room-types
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Room Types for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-room-types.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-room-types.json:
      title: Room Types
      description: A list of custom room types.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: A globally unique identifier of a room type.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
        title:
          title: Title
          description: The full name of a room type
          type: string
          minLength: 1
        description:
          title: Description
          description: The description of a room type.
          type: string
        code:
          title: Room Type Code
          description: ""
          type: string
        type:
          title: Type
          description: The type or style of a of room's layout. For example, "Classroom"
            or "Banquet" style.
          enum:
            - residencehallroom
            - residentialsingleroom
            - residentialdoubleroom
            - residentialtripleroom
            - residentialsuiteroom
            - apartment
            - house
            - classroom
            - lecturehall
            - seminarroom
            - conferenceroom
            - sciencelaboratory
            - computerlaboratory
            - mechanicslab
            - audiovisuallab
            - artstudio
            - musicroom
            - performingartsstudio
            - ballroom
            - office
            - studyfacility
            - clinic
            - animalquarters
            - greenhouse
            - specialusefacility
            - generalusefacility
            - foodfacility
            - daycare
            - lounge
            - merchandisingroom
            - supportfacility
            - healthcarefacility
            - atrium
            - amphitheater
            - auditorium
            - booth
            - other
          type: string
      required:
        - id
        - title
        - type
      additionalProperties: false

