openapi: 3.0.0
info:
  title: award-maintenance-direct-loan-interface
  description: API for RPAAWRD administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RPAAWRD
  x-source-domain: Financial Aid
  x-source-title: Award Maintenance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/award-maintenance-direct-loan-interface:
    get:
      tags:
        - award-maintenance-direct-loan-interface
      summary: Return resources from RPAAWRD
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: rpratrmFundCode
          in: query
          required: false
          schema:
            type: string
        - name: rpratrmAwstCode
          in: query
          required: false
          schema:
            type: string
        - name: rpratrmPeriod
          in: query
          required: false
          schema:
            type: string
        - name: rpratrmAcceptAmt
          in: query
          required: false
          schema:
            type: string
        - name: displayLoanAmt
          in: query
          required: false
          schema:
            type: string
        - name: rlvalinDiffAmt
          in: query
          required: false
          schema:
            type: string
        - name: rlvalinFeeChangeInd
          in: query
          required: false
          schema:
            type: string
        - name: rlvalinBbayDiffInd
          in: query
          required: false
          schema:
            type: string
        - name: rlvalinSayrDiffInd
          in: query
          required: false
          schema:
            type: string
        - name: displayOrigNumber
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/award-maintenance-direct-loan-interface-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/award-maintenance-direct-loan-interface:
    post:
      tags:
        - award-maintenance-direct-loan-interface QAPI (Query by POST)
      summary: Return resources from RPAAWRD
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/award-maintenance-direct-loan-interface-1.0.0_get_r\
                equest"
            example:
              keyblckAidyCode: 2122
              fundCode: AJASST
              id: GENSTU001
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/award-maintenance-direct-loan-interface-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    award-maintenance-direct-loan-interface-1.0.0_get_response:
      type: object
      properties:
        rpratrm2:
          type: array
          items:
            required:
              - rpratrmFundCode
              - rpratrmPeriod
            type: object
            properties:
              rpratrmAcceptAmt:
                title: Accepted Award
                maxLength: 14
                type: number
                description: "Lineage reference object : RPRATRM_ACCEPT_AMT"
                x-lineageReferenceObject: RPRATRM_ACCEPT_AMT
              rlvalinBbayDiffInd:
                maxLength: 1
                type: string
              rlvalinDiffAmt:
                title: Discrepancy
                maxLength: 14
                type: number
              rpratrmFundCode:
                title: Fund
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRATRM_FUND_CODE, Lookup lineage
                  reference object : rfrbase,rfraspc"
                x-lineageReferenceObject: RPRATRM_FUND_CODE
                x-lineageLookupReferenceObject: rfrbase,rfraspc
              rpratrmAwstCode:
                title: Status
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRATRM_AWST_CODE, Lookup lineage
                  reference object : rtvawst"
                x-lineageReferenceObject: RPRATRM_AWST_CODE
                x-lineageLookupReferenceObject: rtvawst
              displayLoanAmt:
                title: Origination
                maxLength: 14
                type: number
              rpratrmPeriod:
                title: Period
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRATRM_PERIOD"
                x-lineageReferenceObject: RPRATRM_PERIOD
              displayOrigNumber:
                title: Originations
                maxLength: 2
                type: number
              rlvalinSayrDiffInd:
                maxLength: 1
                type: string
              rlvalinFeeChangeInd:
                maxLength: 1
                type: string
            x-lineageReferenceObject: rpratrm2
        rlrdlps:
          type: array
          items:
            required:
              - displayBbaySayrCode
              - rlrdlorAcadYrEndDate
              - rlrdlorAcadYrStartDate
              - rlrdlorAwardEndDate
              - rlrdlorAwardStartDate
              - fundCode
              - period
            type: object
            properties:
              rlrdlorAcadYrEndDate:
                title: Academic Year End
                maxLength: 11
                type: string
                format: date-time
              rlrdlorLoanAmt:
                title: Loan Amount
                maxLength: 14
                type: number
              period:
                title: Period
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDLPS_PERIOD"
                x-lineageReferenceObject: RLRDLPS_PERIOD
              loanNo:
                title: Loan Number
                maxLength: 4
                type: number
                description: "Lineage reference object : RLRDLPS_LOAN_NO"
                x-lineageReferenceObject: RLRDLPS_LOAN_NO
              fundCode:
                title: Fund
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDLPS_FUND_CODE, Lookup lineage
                  reference object : rfrbase,rfraspc"
                x-lineageReferenceObject: RLRDLPS_FUND_CODE
                x-lineageLookupReferenceObject: rfrbase,rfraspc
              rlrdlorAcadYrStartDate:
                title: Academic Year Start
                maxLength: 11
                type: string
                format: date-time
              rlrdlorAwardStartDate:
                title: Loan Start
                maxLength: 11
                type: string
                format: date-time
              loanAmt:
                title: Period Amount
                maxLength: 14
                type: number
                description: "Lineage reference object : RLRDLPS_LOAN_AMT"
                x-lineageReferenceObject: RLRDLPS_LOAN_AMT
              displayBbaySayrCode:
                title: BBAY/SAY Code
                maxLength: 30
                type: string
              rlrdlorAwardEndDate:
                title: Loan End
                maxLength: 11
                type: string
                format: date-time
            x-lineageReferenceObject: rlrdlps
    award-maintenance-direct-loan-interface-1.0.0_qapi_post:
      type: object
      properties:
        keyblckAidyCode:
          type: string
        id:
          type: string
        rpratrmFundCode:
          type: string
        rpratrmAwstCode:
          type: string
        rpratrmPeriod:
          type: string
        rpratrmAcceptAmt:
          type: string
        displayLoanAmt:
          type: string
        rlvalinDiffAmt:
          type: string
        rlvalinFeeChangeInd:
          type: string
        rlvalinBbayDiffInd:
          type: string
        rlvalinSayrDiffInd:
          type: string
        displayOrigNumber:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    award-maintenance-direct-loan-interface-1.0.0_get_request:
      required:
        - rpratrmFundCode
        - rpratrmPeriod
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        rpratrmAcceptAmt:
          title: Accepted Award
          maxLength: 14
          type: number
          description: "Lineage reference object : RPRATRM_ACCEPT_AMT"
          x-lineageReferenceObject: RPRATRM_ACCEPT_AMT
        rlvalinBbayDiffInd:
          maxLength: 1
          type: string
        rlvalinDiffAmt:
          title: Discrepancy
          maxLength: 14
          type: number
        rpratrmFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : RPRATRM_FUND_CODE, Lookup lineage
            reference object : rfrbase,rfraspc"
          x-lineageReferenceObject: RPRATRM_FUND_CODE
          x-lineageLookupReferenceObject: rfrbase,rfraspc
        rpratrmAwstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RPRATRM_AWST_CODE, Lookup lineage
            reference object : rtvawst"
          x-lineageReferenceObject: RPRATRM_AWST_CODE
          x-lineageLookupReferenceObject: rtvawst
        rpratrmPeriod:
          title: Period
          maxLength: 30
          type: string
          description: "Lineage reference object : RPRATRM_PERIOD"
          x-lineageReferenceObject: RPRATRM_PERIOD
        displayLoanAmt:
          title: Origination
          maxLength: 14
          type: number
        displayOrigNumber:
          title: Originations
          maxLength: 2
          type: number
        rlvalinSayrDiffInd:
          maxLength: 1
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        rlvalinFeeChangeInd:
          maxLength: 1
          type: string
      x-lineageReferenceObject: RPRATRM2
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
