openapi: 3.0.0
info:
  title: user-profile-definition-cashier-permissions
  description: API for TGAUPRF administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TGAUPRF
  x-source-domain: Student
  x-source-title: User Profile Definition
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/user-profile-definition-cashier-permissions:
    post:
      tags:
        - user-profile-definition-cashier-permissions
      summary: Creates a new resource in TGAUPRF
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              type: object
              properties:
                TBRCASN:
                  type: array
                  items:
                    required:
                      - cashierUserid
                    type: object
                    properties:
                      cashierUserid:
                        title: Cashier
                        maxLength: 30
                        type: string
                        description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                        x-lineageReferenceObject: TBRCASN_CASHIER_USERID
                    x-lineageReferenceObject: TBRCASN
                kbUserid:
                  title: User ID
                  maxLength: 30
                  type: string
                  description: "Lineage reference object : kbUserid"
                  x-lineageReferenceObject: kbUserid
              x-lineageReferenceObject: KEY_BLOCK
            example:
              TBRCASN:
                - cashierUserid: DDD
                - cashierUserid: SAISUSR
              kbUserid: SSS
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tbrcasn:
                      type: array
                      items:
                        required:
                          - cashierUserid
                        type: object
                        properties:
                          activityDate:
                            title: Activity Date
                            maxLength: 11
                            type: string
                            description: "Lineage reference object : TBRCASN_ACTIVITY_DATE"
                            format: date-time
                            x-lineageReferenceObject: TBRCASN_ACTIVITY_DATE
                          cashierUserid:
                            title: Cashier
                            maxLength: 30
                            type: string
                            description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                            x-lineageReferenceObject: TBRCASN_CASHIER_USERID
                          cashierName:
                            title: Cashier Name
                            maxLength: 50
                            type: string
                        x-lineageReferenceObject: tbrcasn
                    tbbuprf:
                      type: array
                      items:
                        required:
                          - userName
                        type: object
                        properties:
                          restrictInd:
                            title: Restricted User
                            maxLength: 1
                            type: string
                            description: "Lineage reference object : TBBUPRF_RESTRICT_IND"
                            x-lineageReferenceObject: TBBUPRF_RESTRICT_IND
                          supervInd:
                            title: Supervisor
                            maxLength: 1
                            type: string
                            description: "Lineage reference object : TBBUPRF_SUPERV_IND"
                            x-lineageReferenceObject: TBBUPRF_SUPERV_IND
                          userName:
                            title: User Name
                            maxLength: 50
                            type: string
                            description: "Lineage reference object : TBBUPRF_USER_NAME"
                            x-lineageReferenceObject: TBBUPRF_USER_NAME
                        x-lineageReferenceObject: tbbuprf
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  required:
                    - errors
                  type: object
                  properties:
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          message:
                            type: string
                          description:
                            type: string
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    delete:
      tags:
        - user-profile-definition-cashier-permissions
      summary: Deletes an existing resource in TGAUPRF
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              required:
                - criteria.cashierUserid
              type: object
              properties:
                criteria.cashierUserid:
                  title: Cashier
                  maxLength: 30
                  type: string
                  description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                  x-lineageReferenceObject: TBRCASN_CASHIER_USERID
                kbUserid:
                  title: User ID
                  maxLength: 30
                  type: string
                  description: "Lineage reference object : kbUserid"
                  x-lineageReferenceObject: kbUserid
              x-lineageReferenceObject: TBRCASN
            example:
              criteria.cashierUserid: SAISUSR
              kbUserid: SSS
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tbrcasn:
                      type: array
                      items:
                        required:
                          - cashierUserid
                        type: object
                        properties:
                          activityDate:
                            title: Activity Date
                            maxLength: 11
                            type: string
                            description: "Lineage reference object : TBRCASN_ACTIVITY_DATE"
                            format: date-time
                            x-lineageReferenceObject: TBRCASN_ACTIVITY_DATE
                          cashierUserid:
                            title: Cashier
                            maxLength: 30
                            type: string
                            description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                            x-lineageReferenceObject: TBRCASN_CASHIER_USERID
                          cashierName:
                            title: Cashier Name
                            maxLength: 50
                            type: string
                        x-lineageReferenceObject: tbrcasn
                    tbbuprf:
                      type: array
                      items:
                        required:
                          - userName
                        type: object
                        properties:
                          restrictInd:
                            title: Restricted User
                            maxLength: 1
                            type: string
                            description: "Lineage reference object : TBBUPRF_RESTRICT_IND"
                            x-lineageReferenceObject: TBBUPRF_RESTRICT_IND
                          supervInd:
                            title: Supervisor
                            maxLength: 1
                            type: string
                            description: "Lineage reference object : TBBUPRF_SUPERV_IND"
                            x-lineageReferenceObject: TBBUPRF_SUPERV_IND
                          userName:
                            title: User Name
                            maxLength: 50
                            type: string
                            description: "Lineage reference object : TBBUPRF_USER_NAME"
                            x-lineageReferenceObject: TBBUPRF_USER_NAME
                        x-lineageReferenceObject: tbbuprf
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  required:
                    - errors
                  type: object
                  properties:
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          message:
                            type: string
                          description:
                            type: string
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/user-profile-definition-cashier-permissions: {}
components:
  schemas:
    user-profile-definition-cashier-permissions-1.0.0_post_response:
      type: object
      properties:
        tbrcasn:
          type: array
          items:
            required:
              - cashierUserid
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRCASN_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: TBRCASN_ACTIVITY_DATE
              cashierUserid:
                title: Cashier
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                x-lineageReferenceObject: TBRCASN_CASHIER_USERID
              cashierName:
                title: Cashier Name
                maxLength: 50
                type: string
            x-lineageReferenceObject: tbrcasn
        tbbuprf:
          type: array
          items:
            required:
              - userName
            type: object
            properties:
              restrictInd:
                title: Restricted User
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBUPRF_RESTRICT_IND"
                x-lineageReferenceObject: TBBUPRF_RESTRICT_IND
              supervInd:
                title: Supervisor
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBUPRF_SUPERV_IND"
                x-lineageReferenceObject: TBBUPRF_SUPERV_IND
              userName:
                title: User Name
                maxLength: 50
                type: string
                description: "Lineage reference object : TBBUPRF_USER_NAME"
                x-lineageReferenceObject: TBBUPRF_USER_NAME
            x-lineageReferenceObject: tbbuprf
    user-profile-definition-cashier-permissions-1.0.0_delete_response:
      type: object
      properties:
        tbrcasn:
          type: array
          items:
            required:
              - cashierUserid
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRCASN_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: TBRCASN_ACTIVITY_DATE
              cashierUserid:
                title: Cashier
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                x-lineageReferenceObject: TBRCASN_CASHIER_USERID
              cashierName:
                title: Cashier Name
                maxLength: 50
                type: string
            x-lineageReferenceObject: tbrcasn
        tbbuprf:
          type: array
          items:
            required:
              - userName
            type: object
            properties:
              restrictInd:
                title: Restricted User
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBUPRF_RESTRICT_IND"
                x-lineageReferenceObject: TBBUPRF_RESTRICT_IND
              supervInd:
                title: Supervisor
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBUPRF_SUPERV_IND"
                x-lineageReferenceObject: TBBUPRF_SUPERV_IND
              userName:
                title: User Name
                maxLength: 50
                type: string
                description: "Lineage reference object : TBBUPRF_USER_NAME"
                x-lineageReferenceObject: TBBUPRF_USER_NAME
            x-lineageReferenceObject: tbbuprf
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    user-profile-definition-cashier-permissions-1.0.0_post_request:
      type: object
      properties:
        TBRCASN:
          type: array
          items:
            required:
              - cashierUserid
            type: object
            properties:
              cashierUserid:
                title: Cashier
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRCASN_CASHIER_USERID"
                x-lineageReferenceObject: TBRCASN_CASHIER_USERID
            x-lineageReferenceObject: TBRCASN
        kbUserid:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : kbUserid"
          x-lineageReferenceObject: kbUserid
      x-lineageReferenceObject: KEY_BLOCK
    user-profile-definition-cashier-permissions-1.0.0_delete_request:
      required:
        - criteria.cashierUserid
      type: object
      properties:
        criteria.cashierUserid:
          title: Cashier
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRCASN_CASHIER_USERID"
          x-lineageReferenceObject: TBRCASN_CASHIER_USERID
        kbUserid:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : kbUserid"
          x-lineageReferenceObject: kbUserid
      x-lineageReferenceObject: TBRCASN
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
