openapi: 3.0.0
info:
  title: ca-ccpg-processing-options-other-resource
  description: API for RVAPROP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RVAPROP
  x-source-domain: Financial Aid
  x-source-title: CCPG Processing Options (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-ccpg-processing-options-other-resource:
    post:
      tags:
        - ca-ccpg-processing-options-other-resource
      summary: Creates a new resource in RVAPROP
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-ccpg-processing-options-other-resource-1.0.0_pos\
                t_request"
            example:
              estAmt: 100
              eligCode: FW-1
              aidyCode: 2021
              arscCode: BOGD
              rsrceStartDate: 06/01/2021
              collCode: AH
              misSumrAidyCode: 2122
              termCode: 202120
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-ccpg-processing-options-other-resource-1.0.0_pos\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-ccpg-processing-options-other-resource: {}
components:
  schemas:
    ca-ccpg-processing-options-other-resource-1.0.0_post_response:
      type: object
      properties:
        rvrrsmc:
          type: array
          items:
            required:
              - arscCode
              - eligCode
            type: object
            properties:
              eligCode:
                title: Eligibility Code
                maxLength: 6
                type: string
                description: "Lineage reference object : RVRRSMC_ELIG_CODE, Lookup lineage
                  reference object : RVVELIG"
                x-lineageReferenceObject: RVRRSMC_ELIG_CODE
                x-lineageLookupReferenceObject: RVVELIG
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : RVRRSMC_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: RVRRSMC_ACTIVITY_DATE
              eligDesc:
                title: Eligibility Code Description
                type: string
              arscCode:
                title: Resource Code
                maxLength: 30
                type: string
                description: "Lineage reference object : RVRRSMC_ARSC_CODE, Lookup lineage
                  reference object : rtvarsc"
                x-lineageReferenceObject: RVRRSMC_ARSC_CODE
                x-lineageLookupReferenceObject: rtvarsc
              arscDesc:
                title: Resource Code Description
                type: string
              userId:
                title: User
                maxLength: 30
                type: string
                description: "Lineage reference object : RVRRSMC_USER_ID"
                x-lineageReferenceObject: RVRRSMC_USER_ID
            x-lineageReferenceObject: rvrrsmc
        rvrrtrm:
          type: array
          items:
            required:
              - estAmt
              - rsrceStartDate
              - termCode
            type: object
            properties:
              estAmt:
                title: Amount
                maxLength: 14
                type: number
                description: "Lineage reference object : RVRRTRM_EST_AMT"
                x-lineageReferenceObject: RVRRTRM_EST_AMT
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : RVRRTRM_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: RVRRTRM_ACTIVITY_DATE
              rsrceStartDate:
                title: Processing Start Date
                maxLength: 11
                type: string
                description: "Lineage reference object : RVRRTRM_RSRCE_START_DATE"
                format: date-time
                x-lineageReferenceObject: RVRRTRM_RSRCE_START_DATE
              termDesc:
                title: Term Description
                type: string
              misSumrAidyCode:
                title: MIS Reporting Aid Year
                maxLength: 30
                type: string
                description: "Lineage reference object : RVRRTRM_MIS_SUMR_AIDY_CODE, Lookup
                  lineage reference object : robinst,ROBINST"
                x-lineageReferenceObject: RVRRTRM_MIS_SUMR_AIDY_CODE
                x-lineageLookupReferenceObject: robinst,ROBINST
              userId:
                title: User
                maxLength: 30
                type: string
                description: "Lineage reference object : RVRRTRM_USER_ID"
                x-lineageReferenceObject: RVRRTRM_USER_ID
              termCode:
                title: Term
                maxLength: 6
                type: string
                description: "Lineage reference object : RVRRTRM_TERM_CODE, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: RVRRTRM_TERM_CODE
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: rvrrtrm
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-ccpg-processing-options-other-resource-1.0.0_post_request:
      required:
        - eligCode
        - arscCode
        - termCode
        - rsrceStartDate
        - estAmt
      type: object
      properties:
        estAmt:
          title: Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : RVRRTRM_EST_AMT"
          x-lineageReferenceObject: RVRRTRM_EST_AMT
        eligCode:
          title: Eligibility Code
          maxLength: 6
          type: string
          description: "Lineage reference object : RVRRSMC_ELIG_CODE, Lookup lineage
            reference object : RVVELIG"
          x-lineageReferenceObject: RVRRSMC_ELIG_CODE
          x-lineageLookupReferenceObject: RVVELIG
        aidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : aidyCode, Lookup lineage reference
            object : robinst,rvbbogw"
          x-lineageReferenceObject: aidyCode
          x-lineageLookupReferenceObject: robinst,rvbbogw
        arscCode:
          title: Resource Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRRSMC_ARSC_CODE, Lookup lineage
            reference object : rtvarsc"
          x-lineageReferenceObject: RVRRSMC_ARSC_CODE
          x-lineageLookupReferenceObject: rtvarsc
        rsrceStartDate:
          title: Processing Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RVRRTRM_RSRCE_START_DATE"
          format: date-time
          x-lineageReferenceObject: RVRRTRM_RSRCE_START_DATE
        collCode:
          title: College
          maxLength: 30
          type: string
          description: "Lineage reference object : collCode, Lookup lineage reference
            object : stvcoll"
          x-lineageReferenceObject: collCode
          x-lineageLookupReferenceObject: stvcoll
        misSumrAidyCode:
          title: MIS Reporting Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRRTRM_MIS_SUMR_AIDY_CODE, Lookup
            lineage reference object : robinst,ROBINST"
          x-lineageReferenceObject: RVRRTRM_MIS_SUMR_AIDY_CODE
          x-lineageLookupReferenceObject: robinst,ROBINST
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : RVRRTRM_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: RVRRTRM_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: RVRRTRM
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
