openapi: 3.0.0
info:
  title: ca-mis-special-historical-data-military-copy
  description: API for SVAMISH administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SVAMISH
  x-source-domain: Student
  x-source-title: Student MIS Special Historical Data (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-mis-special-historical-data-military-copy:
    post:
      tags:
        - ca-mis-special-historical-data-military-copy
      summary: Creates a new resource in SVAMISH
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-special-historical-data-military-copy-1.0.0_\
                post_request"
            example:
              statCode: CA
              guardianActiveInd: Y
              guardianReserveInd: Y
              id: A00027372
              studentActiveInd: Y
              studentReserveInd: Y
              svamishEffTerm: 202220
              svamishDicdCode: 123
              studentVeteranInd: Y
              guardianVeteranInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response\ \ body
                is associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-special-historical-data-military-copy-1.0.0_\
                    post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-mis-special-historical-data-military-copy: {}
components:
  schemas:
    ca-mis-special-historical-data-military-copy-1.0.0_post_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              rwname:
                maxLength: 230
                type: string
                description: "Lineage reference object : rwname"
                x-lineageReferenceObject: rwname
              termDescription:
                type: string
                description: "Lineage reference object : termDescription"
                x-lineageReferenceObject: termDescription
              dicdDescription:
                type: string
                description: "Lineage reference object : dicdDescription"
                x-lineageReferenceObject: dicdDescription
              id:
                title: ID
                maxLength: 9
                type: string
                description: "Lineage reference object : id"
                x-lineageReferenceObject: id
              confidInfo:
                maxLength: 16
                type: string
                description: "Lineage reference object : confidInfo"
                x-lineageReferenceObject: confidInfo
              svamishEffTerm:
                title: Term
                maxLength: 30
                type: string
                description: "Lineage reference object : svamishEffTerm, Lookup lineage\\ \\
                  reference object : stvterm"
                x-lineageReferenceObject: svamishEffTerm
                x-lineageLookupReferenceObject: stvterm
              svamishDicdCode:
                title: District/College ID
                maxLength: 3
                type: string
                description: "Lineage reference object : svamishDicdCode, Lookup lineage\\ \\
                  reference object : gtvdicd"
                x-lineageReferenceObject: svamishDicdCode
                x-lineageLookupReferenceObject: gtvdicd
              deceasedInd:
                maxLength: 12
                type: string
                description: "Lineage reference object : deceasedInd"
                x-lineageReferenceObject: deceasedInd
            x-lineageReferenceObject: key_block
        svbsmss:
          type: array
          items:
            type: object
            properties:
              studentNatlGrdInd:
                title: Member of the National Guard
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_STUDENT_NATL_GRD_IND"
                x-lineageReferenceObject: SVBSMSS_STUDENT_NATL_GRD_IND
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SVBSMSS_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SVBSMSS_ACTIVITY_DATE
              statCode:
                title: Military Home State
                maxLength: 6
                type: string
                description: "Lineage reference object : SVBSMSS_STAT_CODE, Lookup\\ \\ lineage
                  reference object : STVSTAT"
                x-lineageReferenceObject: SVBSMSS_STAT_CODE
                x-lineageLookupReferenceObject: STVSTAT
              guardianActiveInd:
                title: Guardian Currently Serving on Active Duty
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_GUARDIAN_ACTIVE_IND"
                x-lineageReferenceObject: SVBSMSS_GUARDIAN_ACTIVE_IND
              statCodeSt:
                type: string
              guardianReserveInd:
                title: Guardian Member of the Active Reserve
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_GUARDIAN_RESERVE_IND"
                x-lineageReferenceObject: SVBSMSS_GUARDIAN_RESERVE_IND
              guardianNatlGrdInd:
                title: Guardian Member of the National Guard
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_GUARDIAN_NATL_GRD_IND"
                x-lineageReferenceObject: SVBSMSS_GUARDIAN_NATL_GRD_IND
              studentActiveInd:
                title: Currently Serving on Active Duty
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_STUDENT_ACTIVE_IND"
                x-lineageReferenceObject: SVBSMSS_STUDENT_ACTIVE_IND
              studentReserveInd:
                title: Member of the Active Reserve
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_STUDENT_RESERVE_IND"
                x-lineageReferenceObject: SVBSMSS_STUDENT_RESERVE_IND
              userId:
                title: User
                maxLength: 30
                type: string
                description: "Lineage reference object : SVBSMSS_USER_ID"
                x-lineageReferenceObject: SVBSMSS_USER_ID
              guardianVeteranInd:
                title: Guardian Veteran
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_GUARDIAN_VETERAN_IND"
                x-lineageReferenceObject: SVBSMSS_GUARDIAN_VETERAN_IND
              studentVeteranInd:
                title: Veteran
                maxLength: 1
                type: string
                description: "Lineage reference object : SVBSMSS_STUDENT_VETERAN_IND"
                x-lineageReferenceObject: SVBSMSS_STUDENT_VETERAN_IND
            x-lineageReferenceObject: svbsmss
        psid_ctrl_block:
          type: array
          items:
            type: object
            properties:
              svrpsidTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : svrpsidTermCodeFrom"
                x-lineageReferenceObject: svrpsidTermCodeFrom
              svrpsidTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : svrpsidTermCodeTo"
                x-lineageReferenceObject: svrpsidTermCodeTo
            x-lineageReferenceObject: psid_ctrl_block
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    ca-mis-special-historical-data-military-copy-1.0.0_post_request:
      type: object
      properties:
        studentNatlGrdInd:
          title: Member of the National Guard
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_STUDENT_NATL_GRD_IND"
          x-lineageReferenceObject: SVBSMSS_STUDENT_NATL_GRD_IND
        statCode:
          title: Military Home State
          maxLength: 6
          type: string
          description: "Lineage reference object : SVBSMSS_STAT_CODE, Lookup lineage\\ \\
            reference object : STVSTAT"
          x-lineageReferenceObject: SVBSMSS_STAT_CODE
          x-lineageLookupReferenceObject: STVSTAT
        guardianActiveInd:
          title: Guardian Currently Serving on Active Duty
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_GUARDIAN_ACTIVE_IND"
          x-lineageReferenceObject: SVBSMSS_GUARDIAN_ACTIVE_IND
        guardianReserveInd:
          title: Guardian Member of the Active Reserve
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_GUARDIAN_RESERVE_IND"
          x-lineageReferenceObject: SVBSMSS_GUARDIAN_RESERVE_IND
        guardianNatlGrdInd:
          title: Guardian Member of the National Guard
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_GUARDIAN_NATL_GRD_IND"
          x-lineageReferenceObject: SVBSMSS_GUARDIAN_NATL_GRD_IND
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        studentActiveInd:
          title: Currently Serving on Active Duty
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_STUDENT_ACTIVE_IND"
          x-lineageReferenceObject: SVBSMSS_STUDENT_ACTIVE_IND
        studentReserveInd:
          title: Member of the Active Reserve
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_STUDENT_RESERVE_IND"
          x-lineageReferenceObject: SVBSMSS_STUDENT_RESERVE_IND
        svamishEffTerm:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : svamishEffTerm, Lookup lineage\\ \\
            reference object : stvterm"
          x-lineageReferenceObject: svamishEffTerm
          x-lineageLookupReferenceObject: stvterm
        svamishDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamishDicdCode, Lookup lineage\\ \\
            reference object : gtvdicd"
          x-lineageReferenceObject: svamishDicdCode
          x-lineageLookupReferenceObject: gtvdicd
        studentVeteranInd:
          title: Veteran
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_STUDENT_VETERAN_IND"
          x-lineageReferenceObject: SVBSMSS_STUDENT_VETERAN_IND
        guardianVeteranInd:
          title: Guardian Veteran
          maxLength: 1
          type: string
          description: "Lineage reference object : SVBSMSS_GUARDIAN_VETERAN_IND"
          x-lineageReferenceObject: SVBSMSS_GUARDIAN_VETERAN_IND
      x-lineageReferenceObject: SVBSMSS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
