openapi: 3.0.0
info:
  title: account-review-form-account-status
  description: API for TSAACCT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: TSAACCT
  x-source-domain: Student
  x-source-title: Account Review Form - Student
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/account-review-form-account-status:
    put:
      tags:
        - account-review-form-account-status
      summary: Updates an existing resource in TSAACCT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/account-review-form-account-status-1.0.0_put_reques\
                t"
            example:
              criteria.deliCode: CO
              deliCode: "30"
              criteria.refundInd: Y
              refundInd: N
              billCode: IN
              id: "210009103"
              criteria.billCode: SP
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/account-review-form-account-status-1.0.0_put_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/account-review-form-account-status: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    account-review-form-account-status-1.0.0_put_response:
      type: object
      properties:
        deliDesc:
          type: string
        deliCode:
          title: Delinquency
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBACCT_DELI_CODE, Lookup lineage
            reference object : ttvdeli"
          x-lineageReferenceObject: TBBACCT_DELI_CODE
          x-lineageLookupReferenceObject: ttvdeli
        refundInd:
          title: Refund Account
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBACCT_REFUND_IND"
          x-lineageReferenceObject: TBBACCT_REFUND_IND
        billCodeDesc:
          type: string
        billCode:
          title: Bill Code
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBACCT_BILL_CODE, Lookup lineage
            reference object : ttvbill"
          x-lineageReferenceObject: TBBACCT_BILL_CODE
          x-lineageLookupReferenceObject: ttvbill
      x-lineageReferenceObject: tbbacct
    account-review-form-account-status-1.0.0_put_request:
      type: object
      properties:
        criteria.deliCode:
          title: Delinquency
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBACCT_DELI_CODE, Lookup lineage
            reference object : ttvdeli"
          x-lineageReferenceObject: TBBACCT_DELI_CODE
          x-lineageLookupReferenceObject: ttvdeli
        deliCode:
          title: Delinquency
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBACCT_DELI_CODE, Lookup lineage
            reference object : ttvdeli"
          x-lineageReferenceObject: TBBACCT_DELI_CODE
          x-lineageLookupReferenceObject: ttvdeli
        criteria.refundInd:
          title: Refund Account
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBACCT_REFUND_IND"
          x-lineageReferenceObject: TBBACCT_REFUND_IND
        refundInd:
          title: Refund Account
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBACCT_REFUND_IND"
          x-lineageReferenceObject: TBBACCT_REFUND_IND
        billCode:
          title: Bill Code
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBACCT_BILL_CODE, Lookup lineage
            reference object : ttvbill"
          x-lineageReferenceObject: TBBACCT_BILL_CODE
          x-lineageLookupReferenceObject: ttvbill
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.billCode:
          title: Bill Code
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBACCT_BILL_CODE, Lookup lineage
            reference object : ttvbill"
          x-lineageReferenceObject: TBBACCT_BILL_CODE
          x-lineageLookupReferenceObject: ttvbill
      x-lineageReferenceObject: TBBACCT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
