openapi: 3.0.0
info:
  title: applicant-need-analysis-application-inquiry
  description: API for RNIAPPL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: RNIAPPL
  x-source-domain: Financial Aid
  x-source-title: Applicant Need Analysis Application Inquiry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-need-analysis-application-inquiry:
    get:
      tags:
        - applicant-need-analysis-application-inquiry
      summary: Return resources from RNIAPPL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckStudentId
          in: query
          required: false
          schema:
            type: string
        - name: infcCode
          in: query
          description: Application Source
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_INFC_CODE
        - name: seqNo
          in: query
          description: Sequence Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_SEQ_NO
        - name: currRecInd
          in: query
          description: Current Record
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_CURR_REC_IND
        - name: pellPgi
          in: query
          description: SAR EFC
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_PELL_PGI
        - name: usedTransNo
          in: query
          description: Transaction Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_USED_TRANS_NO
        - name: activeInd
          in: query
          description: CSS Active
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_ACTIVE_IND
        - name: pgi
          in: query
          description: Primary Pell EFC
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_PGI
        - name: tfc
          in: query
          description: Primary System EFC
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_TFC
        - name: collChoice
          in: query
          description: College Choice
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_COLL_CHOICE
        - name: createDate
          in: query
          description: Date Created
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_CREATE_DATE
        - name: activityDate
          in: query
          description: Date Updated
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RCVAPPL_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-need-analysis-application-inquiry-1.0.0_g\
                    et_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-need-analysis-application-inquiry:
    post:
      tags:
        - applicant-need-analysis-application-inquiry QAPI (Query by POST)
      summary: Return resources from RNIAPPL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-need-analysis-application-inquiry-1.0.0_g\
                et_request"
            example:
              keyblckAidyCode: 2122
              keyblckStudentId: 212290090
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-need-analysis-application-inquiry-1.0.0_g\
                    et_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    applicant-need-analysis-application-inquiry-1.0.0_get_request:
      type: object
      properties:
        seqNo:
          title: Sequence Number
          maxLength: 3
          type: number
          description: "Lineage reference object : RCVAPPL_SEQ_NO"
          x-lineageReferenceObject: RCVAPPL_SEQ_NO
        infcCode:
          title: Application Source
          maxLength: 7
          type: string
          description: "Lineage reference object : RCVAPPL_INFC_CODE"
          x-lineageReferenceObject: RCVAPPL_INFC_CODE
        currRecInd:
          title: Current Record
          maxLength: 1
          type: string
          description: "Lineage reference object : RCVAPPL_CURR_REC_IND"
          x-lineageReferenceObject: RCVAPPL_CURR_REC_IND
        pellPgi:
          title: SAR EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_PELL_PGI"
          x-lineageReferenceObject: RCVAPPL_PELL_PGI
        tfc:
          title: Primary System EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_TFC"
          x-lineageReferenceObject: RCVAPPL_TFC
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        pgi:
          title: Primary Pell EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_PGI"
          x-lineageReferenceObject: RCVAPPL_PGI
        activityDate:
          title: Date Updated
          maxLength: 11
          type: string
          description: "Lineage reference object : RCVAPPL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RCVAPPL_ACTIVITY_DATE
        keyblckStudentId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : keyblckStudentId"
          x-lineageReferenceObject: keyblckStudentId
        activeInd:
          title: CSS Active
          maxLength: 1
          type: string
          description: "Lineage reference object : RCVAPPL_ACTIVE_IND"
          x-lineageReferenceObject: RCVAPPL_ACTIVE_IND
        collChoice:
          title: College Choice
          maxLength: 6
          type: string
          description: "Lineage reference object : RCVAPPL_COLL_CHOICE"
          x-lineageReferenceObject: RCVAPPL_COLL_CHOICE
        usedTransNo:
          title: Transaction Number
          maxLength: 2
          type: string
          description: "Lineage reference object : RCVAPPL_USED_TRANS_NO"
          x-lineageReferenceObject: RCVAPPL_USED_TRANS_NO
        createDate:
          title: Date Created
          maxLength: 11
          type: string
          description: "Lineage reference object : RCVAPPL_CREATE_DATE"
          format: date-time
          x-lineageReferenceObject: RCVAPPL_CREATE_DATE
      x-lineageReferenceObject: RCVAPPL
    applicant-need-analysis-application-inquiry-1.0.0_qapi_post:
      type: object
      properties:
        keyblckAidyCode:
          type: string
        keyblckStudentId:
          type: string
        infcCode:
          title: Application Source
          maxLength: 7
          type: string
          description: "Lineage reference object : RCVAPPL_INFC_CODE"
          x-lineageReferenceObject: RCVAPPL_INFC_CODE
        seqNo:
          title: Sequence Number
          maxLength: 3
          type: number
          description: "Lineage reference object : RCVAPPL_SEQ_NO"
          x-lineageReferenceObject: RCVAPPL_SEQ_NO
        currRecInd:
          title: Current Record
          maxLength: 1
          type: string
          description: "Lineage reference object : RCVAPPL_CURR_REC_IND"
          x-lineageReferenceObject: RCVAPPL_CURR_REC_IND
        pellPgi:
          title: SAR EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_PELL_PGI"
          x-lineageReferenceObject: RCVAPPL_PELL_PGI
        usedTransNo:
          title: Transaction Number
          maxLength: 2
          type: string
          description: "Lineage reference object : RCVAPPL_USED_TRANS_NO"
          x-lineageReferenceObject: RCVAPPL_USED_TRANS_NO
        activeInd:
          title: CSS Active
          maxLength: 1
          type: string
          description: "Lineage reference object : RCVAPPL_ACTIVE_IND"
          x-lineageReferenceObject: RCVAPPL_ACTIVE_IND
        pgi:
          title: Primary Pell EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_PGI"
          x-lineageReferenceObject: RCVAPPL_PGI
        tfc:
          title: Primary System EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_TFC"
          x-lineageReferenceObject: RCVAPPL_TFC
        collChoice:
          title: College Choice
          maxLength: 6
          type: string
          description: "Lineage reference object : RCVAPPL_COLL_CHOICE"
          x-lineageReferenceObject: RCVAPPL_COLL_CHOICE
        createDate:
          title: Date Created
          maxLength: 11
          type: string
          description: "Lineage reference object : RCVAPPL_CREATE_DATE"
          format: date-time
          x-lineageReferenceObject: RCVAPPL_CREATE_DATE
        activityDate:
          title: Date Updated
          maxLength: 11
          type: string
          description: "Lineage reference object : RCVAPPL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RCVAPPL_ACTIVITY_DATE
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    applicant-need-analysis-application-inquiry-1.0.0_get_response:
      type: object
      properties:
        tfc:
          title: Primary System EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_TFC"
          x-lineageReferenceObject: RCVAPPL_TFC
        rcrapp1VerificationMsg:
          title: Verification Indicator
          maxLength: 2
          type: string
        activityDate:
          title: Date Updated
          maxLength: 11
          type: string
          description: "Lineage reference object : RCVAPPL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RCVAPPL_ACTIVITY_DATE
        pgi:
          title: Primary Pell EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_PGI"
          x-lineageReferenceObject: RCVAPPL_PGI
        seqNo:
          title: Sequence Number
          maxLength: 3
          type: number
          description: "Lineage reference object : RCVAPPL_SEQ_NO"
          x-lineageReferenceObject: RCVAPPL_SEQ_NO
        currRecInd:
          title: Current Record
          maxLength: 1
          type: string
          description: "Lineage reference object : RCVAPPL_CURR_REC_IND"
          x-lineageReferenceObject: RCVAPPL_CURR_REC_IND
        infcCode:
          title: Application Source
          maxLength: 7
          type: string
          description: "Lineage reference object : RCVAPPL_INFC_CODE"
          x-lineageReferenceObject: RCVAPPL_INFC_CODE
        activeInd:
          title: CSS Active
          maxLength: 1
          type: string
          description: "Lineage reference object : RCVAPPL_ACTIVE_IND"
          x-lineageReferenceObject: RCVAPPL_ACTIVE_IND
        collChoice:
          title: College Choice
          maxLength: 6
          type: string
          description: "Lineage reference object : RCVAPPL_COLL_CHOICE"
          x-lineageReferenceObject: RCVAPPL_COLL_CHOICE
        pellPgi:
          title: SAR EFC
          maxLength: 6
          type: number
          description: "Lineage reference object : RCVAPPL_PELL_PGI"
          x-lineageReferenceObject: RCVAPPL_PELL_PGI
        usedTransNo:
          title: Transaction Number
          maxLength: 2
          type: string
          description: "Lineage reference object : RCVAPPL_USED_TRANS_NO"
          x-lineageReferenceObject: RCVAPPL_USED_TRANS_NO
        createDate:
          title: Date Created
          maxLength: 11
          type: string
          description: "Lineage reference object : RCVAPPL_CREATE_DATE"
          format: date-time
          x-lineageReferenceObject: RCVAPPL_CREATE_DATE
      x-lineageReferenceObject: rcvappl
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
