openapi: 3.0.0
info:
  title: common-matching-entry
  description: API for GOAMTCH administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: GOAMTCH
  x-source-domain: Foundation
  x-source-title: Common Matching Entry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/common-matching-entry:
    post:
      tags:
        - common-matching-entry
      summary: Creates a new resource in GOAMTCH
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/common-matching-entry-1.0.0_post_request"
            example:
              streetLine2: .
              cntyCode: 29
              lastName: Data Post
              streetLine1: .
              adidCode: AUT1
              city: .
              streetLine3: .
              ssn: 1205712
              keyblockId: FISH
              emailAddress: sampleTest@frog.com
              emalCode: PERS
              mi: test
              zip: 0001AAA
              birthDay: 23
              phoneExt: 77
              statCode: 123
              natnCode: 91
              sex: M
              teleCode: PR
              birthMon: 7
              firstName: Sample
              keyblockSourceCode: PERSON
              phoneNumber: 2122586
              birthYear: 1985
              phoneArea: 321
              atypCode: PR
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/common-matching-entry-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/common-matching-entry: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    common-matching-entry-1.0.0_post_response:
      type: object
      properties:
        cntyCode:
          title: County
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_CNTY_CODE, Lookup lineage
            reference object : stvcnty"
          x-lineageReferenceObject: GOTCMME_CNTY_CODE
          x-lineageLookupReferenceObject: stvcnty
        streetLine2:
          title: Street Line 2
          maxLength: 75
          type: string
          description: "Lineage reference object : GOTCMME_STREET_LINE2"
          x-lineageReferenceObject: GOTCMME_STREET_LINE2
        streetLine1:
          title: Street Line 1
          maxLength: 75
          type: string
          description: "Lineage reference object : GOTCMME_STREET_LINE1"
          x-lineageReferenceObject: GOTCMME_STREET_LINE1
        lastName:
          title: Last Name
          maxLength: 60
          type: string
        adidCode:
          title: Additional ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GOTCMME_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GOTCMME_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        nonpersonName:
          title: Non-Person Name
          maxLength: 60
          type: string
        city:
          title: City
          maxLength: 50
          type: string
          description: "Lineage reference object : GOTCMME_CITY"
          x-lineageReferenceObject: GOTCMME_CITY
        streetLine3:
          title: Street Line 3
          maxLength: 75
          type: string
          description: "Lineage reference object : GOTCMME_STREET_LINE3"
          x-lineageReferenceObject: GOTCMME_STREET_LINE3
        sourceComment:
          maxLength: 24765
          type: string
        ssn:
          title: SSN/SIN/TIN
          maxLength: 15
          type: string
          description: "Lineage reference object : GOTCMME_SSN"
          x-lineageReferenceObject: GOTCMME_SSN
        greenDataBar1:
          type: string
        emailAddress:
          title: E-mail
          maxLength: 128
          type: string
          description: "Lineage reference object : GOTCMME_EMAIL_ADDRESS"
          x-lineageReferenceObject: GOTCMME_EMAIL_ADDRESS
        emalCode:
          title: E-mail Type
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_EMAL_CODE, Lookup lineage
            reference object : gtvemal"
          x-lineageReferenceObject: GOTCMME_EMAL_CODE
          x-lineageLookupReferenceObject: gtvemal
        teleDescription:
          type: string
        statDescription:
          type: string
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : GOTCMME_MI"
          x-lineageReferenceObject: GOTCMME_MI
        emalDescription:
          type: string
        adidDesc:
          type: string
        zip:
          title: ZIP or Postal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_ZIP"
          x-lineageReferenceObject: GOTCMME_ZIP
        additionalId:
          title: Additional ID
          maxLength: 50
          type: string
          description: "Lineage reference object : GOTCMME_ADDITIONAL_ID"
          x-lineageReferenceObject: GOTCMME_ADDITIONAL_ID
        birthDay:
          title: Day
          maxLength: 2
          type: string
          description: "Lineage reference object : GOTCMME_BIRTH_DAY"
          x-lineageReferenceObject: GOTCMME_BIRTH_DAY
        phoneExt:
          maxLength: 10
          type: string
          description: "Lineage reference object : GOTCMME_PHONE_EXT"
          x-lineageReferenceObject: GOTCMME_PHONE_EXT
        statCode:
          title: State or Province
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_STAT_CODE, Lookup lineage
            reference object : stvstat"
          x-lineageReferenceObject: GOTCMME_STAT_CODE
          x-lineageLookupReferenceObject: stvstat
        natnCode:
          title: Nation
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_NATN_CODE, Lookup lineage
            reference object : stvnatn"
          x-lineageReferenceObject: GOTCMME_NATN_CODE
          x-lineageLookupReferenceObject: stvnatn
        sex:
          title: Gender
          maxLength: 1
          type: string
          description: "Lineage reference object : GOTCMME_SEX"
          x-lineageReferenceObject: GOTCMME_SEX
        natnDescription:
          type: string
        teleCode:
          title: Telephone Type
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_TELE_CODE, Lookup lineage
            reference object : stvtele"
          x-lineageReferenceObject: GOTCMME_TELE_CODE
          x-lineageLookupReferenceObject: stvtele
        cntyDescription:
          type: string
        birthMon:
          title: Month
          maxLength: 2
          type: string
          description: "Lineage reference object : GOTCMME_BIRTH_MON"
          x-lineageReferenceObject: GOTCMME_BIRTH_MON
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : GOTCMME_FIRST_NAME"
          x-lineageReferenceObject: GOTCMME_FIRST_NAME
        phoneNumber:
          maxLength: 12
          type: string
          description: "Lineage reference object : GOTCMME_PHONE_NUMBER"
          x-lineageReferenceObject: GOTCMME_PHONE_NUMBER
        birthYear:
          title: Year
          maxLength: 4
          type: string
          description: "Lineage reference object : GOTCMME_BIRTH_YEAR"
          x-lineageReferenceObject: GOTCMME_BIRTH_YEAR
        phoneArea:
          title: Telephone
          maxLength: 6
          type: string
          description: "Lineage reference object : GOTCMME_PHONE_AREA"
          x-lineageReferenceObject: GOTCMME_PHONE_AREA
        atypDescription:
          type: string
        atypCode:
          title: Address Type
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_ATYP_CODE, Lookup lineage
            reference object : stvatyp"
          x-lineageReferenceObject: GOTCMME_ATYP_CODE
          x-lineageLookupReferenceObject: stvatyp
      x-lineageReferenceObject: gotcmme
    common-matching-entry-1.0.0_post_request:
      type: object
      properties:
        streetLine2:
          title: Street Line 2
          maxLength: 75
          type: string
          description: "Lineage reference object : GOTCMME_STREET_LINE2"
          x-lineageReferenceObject: GOTCMME_STREET_LINE2
        cntyCode:
          title: County
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_CNTY_CODE, Lookup lineage
            reference object : stvcnty"
          x-lineageReferenceObject: GOTCMME_CNTY_CODE
          x-lineageLookupReferenceObject: stvcnty
        lastName:
          title: Last Name
          maxLength: 60
          type: string
        streetLine1:
          title: Street Line 1
          maxLength: 75
          type: string
          description: "Lineage reference object : GOTCMME_STREET_LINE1"
          x-lineageReferenceObject: GOTCMME_STREET_LINE1
        adidCode:
          title: Additional ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GOTCMME_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GOTCMME_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        city:
          title: City
          maxLength: 50
          type: string
          description: "Lineage reference object : GOTCMME_CITY"
          x-lineageReferenceObject: GOTCMME_CITY
        streetLine3:
          title: Street Line 3
          maxLength: 75
          type: string
          description: "Lineage reference object : GOTCMME_STREET_LINE3"
          x-lineageReferenceObject: GOTCMME_STREET_LINE3
        ssn:
          title: SSN/SIN/TIN
          maxLength: 15
          type: string
          description: "Lineage reference object : GOTCMME_SSN"
          x-lineageReferenceObject: GOTCMME_SSN
        keyblockId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        emailAddress:
          title: E-mail
          maxLength: 128
          type: string
          description: "Lineage reference object : GOTCMME_EMAIL_ADDRESS"
          x-lineageReferenceObject: GOTCMME_EMAIL_ADDRESS
        emalCode:
          title: E-mail Type
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_EMAL_CODE, Lookup lineage
            reference object : gtvemal"
          x-lineageReferenceObject: GOTCMME_EMAL_CODE
          x-lineageLookupReferenceObject: gtvemal
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : GOTCMME_MI"
          x-lineageReferenceObject: GOTCMME_MI
        zip:
          title: ZIP or Postal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_ZIP"
          x-lineageReferenceObject: GOTCMME_ZIP
        birthDay:
          title: Day
          maxLength: 2
          type: string
          description: "Lineage reference object : GOTCMME_BIRTH_DAY"
          x-lineageReferenceObject: GOTCMME_BIRTH_DAY
        phoneExt:
          maxLength: 10
          type: string
          description: "Lineage reference object : GOTCMME_PHONE_EXT"
          x-lineageReferenceObject: GOTCMME_PHONE_EXT
        statCode:
          title: State or Province
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_STAT_CODE, Lookup lineage
            reference object : stvstat"
          x-lineageReferenceObject: GOTCMME_STAT_CODE
          x-lineageLookupReferenceObject: stvstat
        natnCode:
          title: Nation
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_NATN_CODE, Lookup lineage
            reference object : stvnatn"
          x-lineageReferenceObject: GOTCMME_NATN_CODE
          x-lineageLookupReferenceObject: stvnatn
        sex:
          title: Gender
          maxLength: 1
          type: string
          description: "Lineage reference object : GOTCMME_SEX"
          x-lineageReferenceObject: GOTCMME_SEX
        teleCode:
          title: Telephone Type
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_TELE_CODE, Lookup lineage
            reference object : stvtele"
          x-lineageReferenceObject: GOTCMME_TELE_CODE
          x-lineageLookupReferenceObject: stvtele
        birthMon:
          title: Month
          maxLength: 2
          type: string
          description: "Lineage reference object : GOTCMME_BIRTH_MON"
          x-lineageReferenceObject: GOTCMME_BIRTH_MON
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : GOTCMME_FIRST_NAME"
          x-lineageReferenceObject: GOTCMME_FIRST_NAME
        keyblockSourceCode:
          title: Matching Source
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblockSourceCode, Lookup lineage
            reference object : gtvcmsc"
          x-lineageReferenceObject: keyblockSourceCode
          x-lineageLookupReferenceObject: gtvcmsc
        phoneNumber:
          maxLength: 12
          type: string
          description: "Lineage reference object : GOTCMME_PHONE_NUMBER"
          x-lineageReferenceObject: GOTCMME_PHONE_NUMBER
        birthYear:
          title: Year
          maxLength: 4
          type: string
          description: "Lineage reference object : GOTCMME_BIRTH_YEAR"
          x-lineageReferenceObject: GOTCMME_BIRTH_YEAR
        phoneArea:
          title: Telephone
          maxLength: 6
          type: string
          description: "Lineage reference object : GOTCMME_PHONE_AREA"
          x-lineageReferenceObject: GOTCMME_PHONE_AREA
        atypCode:
          title: Address Type
          maxLength: 30
          type: string
          description: "Lineage reference object : GOTCMME_ATYP_CODE, Lookup lineage
            reference object : stvatyp"
          x-lineageReferenceObject: GOTCMME_ATYP_CODE
          x-lineageLookupReferenceObject: stvatyp
      x-lineageReferenceObject: GOTCMME
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
