openapi: 3.0.0
info:
  title: term-control-add-authorizations
  description: API for SOATERM administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SOATERM
  x-source-domain: Student
  x-source-title: Term Control Form
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: '{server_url}'
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/term-control-add-authorizations:
    put:
      tags:
      - term-control-add-authorizations
      summary: Updates an existing resource in SOATERM
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/term-control-add-authorizations-1.0.0_put_request"
            example:
              regAuthClosedInd: "Y"
              xxxxxxxTermCode: 202509
              rovrCode: ALL
              daysRequired: 10
              regAuthActiveInd: "Y"
              daysReusable: 10
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/term-control-add-authorizations-1.0.0_put_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/term-control-add-authorizations: {}
components:
  schemas:
    term-control-add-authorizations-1.0.0_put_response:
      type: object
      properties:
        SobauthRegAuthClosedInd:
          title: Disable Before Start Date
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBAUTH_REG_AUTH_CLOSED_IND"
          x-lineageReferenceObject: SOBAUTH_REG_AUTH_CLOSED_IND
        stvrovrDesc:
          type: string
        daysRequired:
          title: Days Required Relative to Start Date
          maxLength: 4
          type: number
          description: "Lineage reference object : SOBAUTH_DAYS_REQUIRED"
          x-lineageReferenceObject: SOBAUTH_DAYS_REQUIRED
        rovrCode:
          title: Permit-Override Code
          maxLength: 10
          type: string
          description: "Lineage reference object : SOBAUTH_ROVR_CODE, Lookup lineage\
            \ reference object : stvrovr,sfrrovr"
          x-lineageReferenceObject: SOBAUTH_ROVR_CODE
          x-lineageLookupReferenceObject: "stvrovr,sfrrovr"
        daysReusable:
          title: Days Reusable after Assignment
          maxLength: 3
          type: number
          description: "Lineage reference object : SOBAUTH_DAYS_REUSABLE"
          x-lineageReferenceObject: SOBAUTH_DAYS_REUSABLE
        regAuthActiveInd:
          title: Active for Term
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBAUTH_REG_AUTH_ACTIVE_IND"
          x-lineageReferenceObject: SOBAUTH_REG_AUTH_ACTIVE_IND
      x-lineageReferenceObject: sobauth
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
    term-control-add-authorizations-1.0.0_put_request:
      type: object
      properties:
        termCodeDef:
          title: Copy From Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTermCodedef, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCodedef
          x-lineageLookupReferenceObject: stvterm
        regAuthClosedInd:
          title: Disable Before Start Date
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBAUTH_REG_AUTH_CLOSED_IND"
          x-lineageReferenceObject: SOBAUTH_REG_AUTH_CLOSED_IND
        xxxxxxxTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : xxxxxxxTermCode, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: xxxxxxxTermCode
          x-lineageLookupReferenceObject: stvterm
        rovrCode:
          title: Permit-Override Code
          maxLength: 10
          type: string
          description: "Lineage reference object : SOBAUTH_ROVR_CODE, Lookup lineage\
            \ reference object : stvrovr,sfrrovr"
          x-lineageReferenceObject: SOBAUTH_ROVR_CODE
          x-lineageLookupReferenceObject: "stvrovr,sfrrovr"
        daysRequired:
          title: Days Required Relative to Start Date
          maxLength: 4
          type: number
          description: "Lineage reference object : SOBAUTH_DAYS_REQUIRED"
          x-lineageReferenceObject: SOBAUTH_DAYS_REQUIRED
        regAuthActiveInd:
          title: Active for Term
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBAUTH_REG_AUTH_ACTIVE_IND"
          x-lineageReferenceObject: SOBAUTH_REG_AUTH_ACTIVE_IND
        daysReusable:
          title: Days Reusable after Assignment
          maxLength: 3
          type: number
          description: "Lineage reference object : SOBAUTH_DAYS_REUSABLE"
          x-lineageReferenceObject: SOBAUTH_DAYS_REUSABLE
      x-lineageReferenceObject: SOBAUTH
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer