openapi: 3.0.0
info:
  title: finance-refund-review
  description: API for TFARFND administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TFARFND
  x-source-domain: Finance
  x-source-title: Refund Review - Finance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/finance-refund-review:
    get:
      tags:
        - finance-refund-review
      summary: Return resources from TFARFND
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          description: ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: ID
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: accountBalance
          in: query
          description: Account Balance
          required: false
          schema:
            type: string
          x-lineageReferenceObject: ACCOUNT_BALANCE
        - name: pending
          in: query
          description: Pending
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PENDING
        - name: refund
          in: query
          description: Refund
          required: false
          schema:
            type: string
          x-lineageReferenceObject: REFUND
        - name: refundInd
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finance-refund-review-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - finance-refund-review
      summary: Updates an existing resource in TFARFND
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/finance-refund-review-1.0.0_put_request"
            example:
              refundInd: N
              id: MATC3
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finance-refund-review-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/finance-refund-review:
    post:
      tags:
        - finance-refund-review QAPI (Query by POST)
      summary: Return resources from TFARFND
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/finance-refund-review-1.0.0_qapi_post_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finance-refund-review-1.0.0_qapi_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    finance-refund-review-1.0.0_put_request:
      type: object
      properties:
        criteria.accountBalance:
          title: Account Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : ACCOUNT_BALANCE"
          x-lineageReferenceObject: ACCOUNT_BALANCE
        criteria.refund:
          title: Refund
          maxLength: 17
          type: number
          description: "Lineage reference object : REFUND"
          x-lineageReferenceObject: REFUND
        criteria.refundInd:
          maxLength: 9
          type: string
        refundInd:
          maxLength: 9
          type: string
        criteria.id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        criteria.name:
          maxLength: 230
          type: string
          description: "Lineage reference object : NAME"
          x-lineageReferenceObject: NAME
        criteria.pending:
          title: Pending
          maxLength: 17
          type: number
          description: "Lineage reference object : PENDING"
          x-lineageReferenceObject: PENDING
      x-lineageReferenceObject: TBVRFND
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    finance-refund-review-1.0.0_qapi_post_request:
      type: object
      properties:
        pending:
          title: Pending
          maxLength: 17
          type: number
          description: "Lineage reference object : PENDING"
          x-lineageReferenceObject: PENDING
        name:
          maxLength: 230
          type: string
          description: "Lineage reference object : NAME"
          x-lineageReferenceObject: NAME
        refundInd:
          maxLength: 9
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        accountBalance:
          title: Account Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : ACCOUNT_BALANCE"
          x-lineageReferenceObject: ACCOUNT_BALANCE
        refund:
          title: Refund
          maxLength: 17
          type: number
          description: "Lineage reference object : REFUND"
          x-lineageReferenceObject: REFUND
      x-lineageReferenceObject: TBVRFND
    finance-refund-review-1.0.0_put_response:
      type: object
      properties:
        pending:
          title: Pending
          maxLength: 17
          type: number
          description: "Lineage reference object : PENDING"
          x-lineageReferenceObject: PENDING
        rwname:
          maxLength: 230
          type: string
          description: "Lineage reference object : NAME"
          x-lineageReferenceObject: NAME
        refundInd:
          maxLength: 9
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        accountBalance:
          title: Account Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : ACCOUNT_BALANCE"
          x-lineageReferenceObject: ACCOUNT_BALANCE
        refund:
          title: Refund
          maxLength: 17
          type: number
          description: "Lineage reference object : REFUND"
          x-lineageReferenceObject: REFUND
      x-lineageReferenceObject: tbvrfnd
    finance-refund-review-1.0.0_get_response:
      type: object
      properties:
        pending:
          title: Pending
          maxLength: 17
          type: number
          description: "Lineage reference object : PENDING"
          x-lineageReferenceObject: PENDING
        rwname:
          maxLength: 230
          type: string
          description: "Lineage reference object : NAME"
          x-lineageReferenceObject: NAME
        refundInd:
          maxLength: 9
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        accountBalance:
          title: Account Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : ACCOUNT_BALANCE"
          x-lineageReferenceObject: ACCOUNT_BALANCE
        refund:
          title: Refund
          maxLength: 17
          type: number
          description: "Lineage reference object : REFUND"
          x-lineageReferenceObject: REFUND
      x-lineageReferenceObject: tbvrfnd
    finance-refund-review-1.0.0_qapi_post:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        name:
          type: string
        accountBalance:
          title: Account Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : ACCOUNT_BALANCE"
          x-lineageReferenceObject: ACCOUNT_BALANCE
        pending:
          title: Pending
          maxLength: 17
          type: number
          description: "Lineage reference object : PENDING"
          x-lineageReferenceObject: PENDING
        refund:
          title: Refund
          maxLength: 17
          type: number
          description: "Lineage reference object : REFUND"
          x-lineageReferenceObject: REFUND
        refundInd:
          maxLength: 9
          type: string
    finance-refund-review-1.0.0_qapi_post_response:
      type: object
      properties:
        pending:
          title: Pending
          maxLength: 17
          type: number
          description: "Lineage reference object : PENDING"
          x-lineageReferenceObject: PENDING
        rwname:
          maxLength: 230
          type: string
          description: "Lineage reference object : NAME"
          x-lineageReferenceObject: NAME
        refundInd:
          maxLength: 9
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        accountBalance:
          title: Account Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : ACCOUNT_BALANCE"
          x-lineageReferenceObject: ACCOUNT_BALANCE
        refund:
          title: Refund
          maxLength: 17
          type: number
          description: "Lineage reference object : REFUND"
          x-lineageReferenceObject: REFUND
      x-lineageReferenceObject: tbvrfnd
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
