openapi: 3.0.0
info:
  title: student-course-registration-time-status
  description: API for SFAREGS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SFAREGS
  x-source-domain: Student
  x-source-title: Student Course Registration
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-course-registration-time-status:
    get:
      tags:
        - student-course-registration-time-status
      summary: Return resources from SFAREGS
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: term
          in: query
          required: false
          schema:
            type: string
        - name: rstsEstsDate
          in: query
          required: false
          schema:
            type: string
        - name: holdPassword
          in: query
          required: false
          schema:
            type: string
        - name: viewCurrent
          in: query
          required: false
          schema:
            type: string
        - name: printBill
          in: query
          required: false
          schema:
            type: string
        - name: printSchedule
          in: query
          required: false
          schema:
            type: string
        - name: keyStudypath
          in: query
          required: false
          schema:
            type: string
        - name: tmstCode
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFRTHST_TMST_CODE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-course-registration-time-status-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/student-course-registration-time-status:
    post:
      tags:
        - student-course-registration-time-status QAPI (Query by POST)
      summary: Return resources from SFAREGS
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-course-registration-time-status-1.0.0_get_r\
                equest"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-course-registration-time-status-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    student-course-registration-time-status-1.0.0_get_request:
      required:
        - tmstCode
      type: object
      properties:
        holdPassword:
          title: Holds
          maxLength: 3
          type: string
          description: "Lineage reference object : holdPassword"
          x-lineageReferenceObject: holdPassword
        printBill:
          title: Print Bill
          maxLength: 1
          type: string
          description: "Lineage reference object : printBill"
          x-lineageReferenceObject: printBill
        tmstCode:
          title: Time Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRTHST_TMST_CODE, Lookup lineage
            reference object : stvtmst"
          x-lineageReferenceObject: SFRTHST_TMST_CODE
          x-lineageLookupReferenceObject: stvtmst
        printSchedule:
          title: Print Schedule
          maxLength: 1
          type: string
          description: "Lineage reference object : printSchedule"
          x-lineageReferenceObject: printSchedule
        term:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : term, Lookup lineage reference object :
            stvterm"
          x-lineageReferenceObject: term
          x-lineageLookupReferenceObject: stvterm
        rstsEstsDate:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : rstsEstsDate"
          format: date-time
          x-lineageReferenceObject: rstsEstsDate
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        viewCurrent:
          title: View Current/Active Curricula
          maxLength: 30
          type: string
          description: "Lineage reference object : viewCurrent"
          x-lineageReferenceObject: viewCurrent
      x-lineageReferenceObject: SFRTHST
    student-course-registration-time-status-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        term:
          title: Term
          maxLength: 6
          type: string
        rstsEstsDate:
          type: string
        holdPassword:
          type: string
        viewCurrent:
          type: string
        printBill:
          type: string
        printSchedule:
          type: string
        keyStudypath:
          type: string
        tmstCode:
          title: Time Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRTHST_TMST_CODE, Lookup lineage
            reference object : stvtmst"
          x-lineageReferenceObject: SFRTHST_TMST_CODE
          x-lineageLookupReferenceObject: stvtmst
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    student-course-registration-time-status-1.0.0_get_response:
      required:
        - tmstCode
      type: object
      properties:
        holdTmstDate:
          title: Date
          maxLength: 11
          type: string
          format: date-time
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRTHST_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRTHST_ACTIVITY_DATE
        tmstMaintIndDesc:
          title: Source
          maxLength: 6
          type: string
        tmstCode:
          title: Time Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRTHST_TMST_CODE, Lookup lineage
            reference object : stvtmst"
          x-lineageReferenceObject: SFRTHST_TMST_CODE
          x-lineageLookupReferenceObject: stvtmst
        term:
          title: Term
          maxLength: 6
          type: string
        holdTmstTime:
          title: Time
          maxLength: 26
          type: string
        stvtmstDesc:
          title: Description
          type: string
      x-lineageReferenceObject: sfrthst
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
