openapi: 3.0.0
info:
  title: cross-list-waitlist-priority-management
  description: API for SFAXWLP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SFAXWLP
  x-source-domain: Student
  x-source-title: Cross List Waitlist Priority Management
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/cross-list-waitlist-priority-management:
    get:
      tags:
      - cross-list-waitlist-priority-management
      summary: Return resources from SFAXWLP
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
      - name: xlstGroup
        in: query
        required: false
        schema:
          type: string
      - name: termCode
        in: query
        required: false
        schema:
          type: string
      - name: crn
        in: query
        description: CRN
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_CRN
      - name: regSeq
        in: query
        description: Sequence
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_REG_SEQ
      - name: rstsCode
        in: query
        description: Status
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_RSTS_CODE
      - name: rstsDate
        in: query
        description: Registration Date-Time
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_RSTS_DATE
      - name: wlPriority
        in: query
        description: Waitlist Priority
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_WL_PRIORITY
      - name: user
        in: query
        description: User
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_USER
      - name: activityDate
        in: query
        description: Activity Date
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SFRSTCR_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cross-list-waitlist-priority-management-1.0.0_get_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/cross-list-waitlist-priority-management:
    post:
      tags:
      - cross-list-waitlist-priority-management QAPI (Query by POST)
      summary: Return resources from SFAXWLP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/cross-list-waitlist-priority-management-1.0.0_qapi_post_request'
            example:
              xlstGroup: W1
              termCode: 199610
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cross-list-waitlist-priority-management-1.0.0_qapi_post_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
components:
  schemas:
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
    cross-list-waitlist-priority-management-1.0.0_get_response:
      required:
      - wlPriority
      type: object
      properties:
        ssbsectCourseAlias:
          title: Course Alias
          maxLength: 20
          type: string
        ssbsectSeqNumb:
          title: Section
          maxLength: 3
          type: string
        fullName:
          title: Name
          maxLength: 150
          type: string
        ssbsectSubjCode:
          title: Subject
          maxLength: 4
          type: string
        regSeq:
          title: Sequence
          maxLength: 4
          type: number
          description: "Lineage reference object : SFRSTCR_REG_SEQ"
          x-lineageReferenceObject: SFRSTCR_REG_SEQ
        ssbsectCrseNumb:
          title: Course Number
          maxLength: 5
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRSTCR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRSTCR_ACTIVITY_DATE
        rstsCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SFRSTCR_RSTS_CODE"
          x-lineageReferenceObject: SFRSTCR_RSTS_CODE
        rstsDate:
          title: Registration Date-Time
          maxLength: 26
          type: string
          description: "Lineage reference object : SFRSTCR_RSTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRSTCR_RSTS_DATE
        id:
          title: ID
          maxLength: 9
          type: string
        wlPriority:
          title: Waitlist Priority
          maxLength: 12
          type: number
          description: "Lineage reference object : SFRSTCR_WL_PRIORITY"
          x-lineageReferenceObject: SFRSTCR_WL_PRIORITY
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRSTCR_USER"
          x-lineageReferenceObject: SFRSTCR_USER
        wlPrioOriginDesc:
          title: Waitlist Origin
          maxLength: 30
          type: string
        crn:
          title: CRN
          maxLength: 5
          type: string
          description: "Lineage reference object : SFRSTCR_CRN"
          x-lineageReferenceObject: SFRSTCR_CRN
      x-lineageReferenceObject: sfrstcr
    cross-list-waitlist-priority-management-1.0.0_qapi_post_request:
      required:
      - wlPriority
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRSTCR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRSTCR_ACTIVITY_DATE
        rstsCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SFRSTCR_RSTS_CODE"
          x-lineageReferenceObject: SFRSTCR_RSTS_CODE
        xlstGroup:
          title: Cross List Group Identifier
          maxLength: 15
          type: string
          description: "Lineage reference object : xlstGroup"
          x-lineageReferenceObject: xlstGroup
        rstsDate:
          title: Registration Date-Time
          maxLength: 26
          type: string
          description: "Lineage reference object : SFRSTCR_RSTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRSTCR_RSTS_DATE
        regSeq:
          title: Sequence
          maxLength: 4
          type: number
          description: "Lineage reference object : SFRSTCR_REG_SEQ"
          x-lineageReferenceObject: SFRSTCR_REG_SEQ
        wlPriority:
          title: Waitlist Priority
          maxLength: 12
          type: number
          description: "Lineage reference object : SFRSTCR_WL_PRIORITY"
          x-lineageReferenceObject: SFRSTCR_WL_PRIORITY
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRSTCR_USER"
          x-lineageReferenceObject: SFRSTCR_USER
        crn:
          title: CRN
          maxLength: 5
          type: string
          description: "Lineage reference object : SFRSTCR_CRN"
          x-lineageReferenceObject: SFRSTCR_CRN
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference\
            \ object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SFRSTCR
    cross-list-waitlist-priority-management-1.0.0_qapi_post_response:
      required:
      - wlPriority
      type: object
      properties:
        ssbsectCourseAlias:
          title: Course Alias
          maxLength: 20
          type: string
        ssbsectSeqNumb:
          title: Section
          maxLength: 3
          type: string
        fullName:
          title: Name
          maxLength: 150
          type: string
        ssbsectSubjCode:
          title: Subject
          maxLength: 4
          type: string
        regSeq:
          title: Sequence
          maxLength: 4
          type: number
          description: "Lineage reference object : SFRSTCR_REG_SEQ"
          x-lineageReferenceObject: SFRSTCR_REG_SEQ
        ssbsectCrseNumb:
          title: Course Number
          maxLength: 5
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRSTCR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRSTCR_ACTIVITY_DATE
        rstsCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SFRSTCR_RSTS_CODE"
          x-lineageReferenceObject: SFRSTCR_RSTS_CODE
        rstsDate:
          title: Registration Date-Time
          maxLength: 26
          type: string
          description: "Lineage reference object : SFRSTCR_RSTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRSTCR_RSTS_DATE
        id:
          title: ID
          maxLength: 9
          type: string
        wlPriority:
          title: Waitlist Priority
          maxLength: 12
          type: number
          description: "Lineage reference object : SFRSTCR_WL_PRIORITY"
          x-lineageReferenceObject: SFRSTCR_WL_PRIORITY
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRSTCR_USER"
          x-lineageReferenceObject: SFRSTCR_USER
        wlPrioOriginDesc:
          title: Waitlist Origin
          maxLength: 30
          type: string
        crn:
          title: CRN
          maxLength: 5
          type: string
          description: "Lineage reference object : SFRSTCR_CRN"
          x-lineageReferenceObject: SFRSTCR_CRN
      x-lineageReferenceObject: sfrstcr
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer