openapi: 3.0.0
info:
  title: complementary-activities-program-rules-categories
  description: API for SOACAPR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SOACAPR
  x-source-domain: Student
  x-source-title: Complementary Activities Program Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/complementary-activities-program-rules-categories:
    get:
      tags:
        - complementary-activities-program-rules-categories
      summary: Return resources from SOACAPR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: program
          in: query
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          required: false
          schema:
            type: string
        - name: accgCode
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORCACR_ACCG_CODE
        - name: reqHoursCategory
          in: query
          required: false
          schema:
            type: string
        - name: reqCreditsCategory
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORCACR_REQ_CREDITS_CATEGORY
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/complementary-activities-program-rules-categories-1\
                    .0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/complementary-activities-program-rules-categories:
    post:
      tags:
        - complementary-activities-program-rules-categories QAPI (Query by POST)
      summary: Return resources from SOACAPR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/complementary-activities-program-rules-categories-1\
                .0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/complementary-activities-program-rules-categories-1\
                    .0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    complementary-activities-program-rules-categories-1.0.0_get_response:
      type: object
      properties:
        sobcarp_ctrl_block:
          type: array
          items:
            required:
              - sobcarpTermCodeEnd
              - sobcarpTermCodeStart
            type: object
            properties:
              sobcarpTermCodeEnd:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sobcarpTermCodeEnd"
                x-lineageReferenceObject: sobcarpTermCodeEnd
              sobcarpTermCodeStart:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sobcarpTermCodeStart"
                x-lineageReferenceObject: sobcarpTermCodeStart
            x-lineageReferenceObject: sobcarp_ctrl_block
        sobcarp:
          type: array
          items:
            type: object
            properties:
              activityDate:
                maxLength: 11
                type: string
                description: "Lineage reference object : SOBCARP_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SOBCARP_ACTIVITY_DATE
              reqCreditsProgram:
                title: Required Credits
                type: number
                description: "Lineage reference object : SOBCARP_REQ_CREDITS_PROGRAM"
                x-lineageReferenceObject: SOBCARP_REQ_CREDITS_PROGRAM
              creditEquivalent:
                title: Equivalent Credits
                type: number
                description: "Lineage reference object : SOBCARP_CREDIT_EQUIVALENT"
                x-lineageReferenceObject: SOBCARP_CREDIT_EQUIVALENT
              reqHrsProgram:
                type: number
                description: "Lineage reference object : SOBCARP_REQ_HOURS_PROGRAM"
                x-lineageReferenceObject: SOBCARP_REQ_HOURS_PROGRAM
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SOBCARP_USER_ID"
                x-lineageReferenceObject: SOBCARP_USER_ID
            x-lineageReferenceObject: sobcarp
        sorcacr:
          type: array
          items:
            required:
              - accgCode
            type: object
            properties:
              activityDate:
                maxLength: 11
                type: string
                description: "Lineage reference object : SORCACR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCACR_ACTIVITY_DATE
              accgCode:
                type: string
                description: "Lineage reference object : SORCACR_ACCG_CODE"
                x-lineageReferenceObject: SORCACR_ACCG_CODE
              reqHrsCategory:
                type: number
                description: "Lineage reference object : SORCACR_REQ_HOURS_CATEGORY"
                x-lineageReferenceObject: SORCACR_REQ_HOURS_CATEGORY
              stvaccgDesc:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCACR_USER_ID"
                x-lineageReferenceObject: SORCACR_USER_ID
              reqCreditsCategory:
                type: number
                description: "Lineage reference object : SORCACR_REQ_CREDITS_CATEGORY"
                x-lineageReferenceObject: SORCACR_REQ_CREDITS_CATEGORY
            x-lineageReferenceObject: sorcacr
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    complementary-activities-program-rules-categories-1.0.0_qapi_post:
      type: object
      properties:
        program:
          type: string
        termCode:
          type: string
        accgCode:
          type: string
          description: "Lineage reference object : SORCACR_ACCG_CODE"
          x-lineageReferenceObject: SORCACR_ACCG_CODE
        reqHoursCategory:
          type: string
        reqCreditsCategory:
          type: number
          description: "Lineage reference object : SORCACR_REQ_CREDITS_CATEGORY"
          x-lineageReferenceObject: SORCACR_REQ_CREDITS_CATEGORY
    complementary-activities-program-rules-categories-1.0.0_get_request:
      required:
        - accgCode
      type: object
      properties:
        accgCode:
          type: string
          description: "Lineage reference object : SORCACR_ACCG_CODE"
          x-lineageReferenceObject: SORCACR_ACCG_CODE
        program:
          type: string
          description: "Lineage reference object : program"
          x-lineageReferenceObject: program
        reqHoursCategory:
          type: number
          description: "Lineage reference object : SORCACR_REQ_HOURS_CATEGORY"
          x-lineageReferenceObject: SORCACR_REQ_HOURS_CATEGORY
        reqCreditsCategory:
          type: number
          description: "Lineage reference object : SORCACR_REQ_CREDITS_CATEGORY"
          x-lineageReferenceObject: SORCACR_REQ_CREDITS_CATEGORY
        termCode:
          type: string
          description: "Lineage reference object : termCode"
          x-lineageReferenceObject: termCode
      x-lineageReferenceObject: SORCACR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
