openapi: 3.0.0
info:
  title: data-privacy-retention-collection-maintenance-retention-collection-details
  description: API for GUARETC administrative page
  version: 0.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: GUARETC
  x-source-domain: Foundation
  x-source-title: Retention Collection Attributes
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/data-privacy-retention-collection-maintenance-retention-collection-details:
    post:
      tags:
        - data-privacy-retention-collection-maintenance-retention-collection-details
      summary: Creates a new resource in GUARETC
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-retention-collection-maintenance-reten\
                tion-collection-details-0.1.0_post_request"
            example:
              executeBtn: 011_CODE
              id: ZIPP-3
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-collection-maintenance-reten\
                    tion-collection-details-0.1.0_post_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/data-privacy-retention-collection-maintenance-retention-collection-details: {}
components:
  schemas:
    data-privacy-retention-collection-maintenance-retention-collection-details-0.1.0_post_request:
      required:
        - collection
      type: object
      properties:
        collection:
          title: Retention Collection
          type: string
          description: "Lineage reference object : collection, Lookup lineage reference
            object : gubretc"
          x-lineageReferenceObject: collection
          x-lineageLookupReferenceObject: gubretc
        id:
          title: ID
          type: string
      x-lineageReferenceObject: GURRETC
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    data-privacy-retention-collection-maintenance-retention-collection-details-0.1.0_post_response:
      type: object
      properties:
        activityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRETC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GURRETC_ACTIVITY_DATE
        name:
          title: Name
          type: string
        id:
          title: ID
          type: string
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRETC_USER_ID"
          x-lineageReferenceObject: GURRETC_USER_ID
        status:
          title: Status
          type: string
          description: "Lineage reference object : GURRETC_STATUS"
          x-lineageReferenceObject: GURRETC_STATUS
      x-lineageReferenceObject: gurretc
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
