openapi: 3.0.0
info:
  title: curriculum-rules-major-and-departments
  description: API for SOACURR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SOACURR
  x-source-domain: Student
  x-source-title: Curriculum Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/curriculum-rules-major-and-departments:
    get:
      tags:
        - curriculum-rules-major-and-departments
      summary: Return resources from SOACURR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          required: false
          schema:
            type: string
        - name: currRule
          in: query
          required: false
          schema:
            type: string
        - name: program
          in: query
          required: false
          schema:
            type: string
        - name: levlCode
          in: query
          required: false
          schema:
            type: string
        - name: campCode
          in: query
          required: false
          schema:
            type: string
        - name: termCodeInit
          in: query
          required: false
          schema:
            type: string
        - name: collCode
          in: query
          required: false
          schema:
            type: string
        - name: degcCode
          in: query
          required: false
          schema:
            type: string
        - name: primRollInd
          in: query
          required: false
          schema:
            type: string
        - name: secdRollInd
          in: query
          required: false
          schema:
            type: string
        - name: lockInd
          in: query
          required: false
          schema:
            type: string
        - name: studyPathInd
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curriculum-rules-major-and-departments-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/curriculum-rules-major-and-departments:
    post:
      tags:
        - curriculum-rules-major-and-departments QAPI (Query by POST)
      summary: Return resources from SOACURR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curriculum-rules-major-and-departments-1.0.0_get_re\
                quest"
            example:
              program: 1-5KZXTO
              termCode: 1010
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curriculum-rules-major-and-departments-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    curriculum-rules-major-and-departments-1.0.0_get_response:
      type: object
      properties:
        sorcmjr_ctrl:
          type: array
          items:
            type: object
            properties:
              majrTotermDisp:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : majrTotermDisp"
                x-lineageReferenceObject: majrTotermDisp
              majrFrtermDisp:
                title: From Term
                maxLength: 30
                type: string
                description: "Lineage reference object : majrFrtermDisp, Lookup lineage
                  reference object : sorcmjr,stvterm"
                x-lineageReferenceObject: majrFrtermDisp
                x-lineageLookupReferenceObject: sorcmjr,stvterm
              cmjrMultipleMsg:
                maxLength: 50
                type: string
                description: "Lineage reference object : cmjrMultipleMsg"
                x-lineageReferenceObject: cmjrMultipleMsg
            x-lineageReferenceObject: sorcmjr_ctrl
        sorcmjr:
          type: array
          items:
            type: object
            properties:
              displayConc:
                title: Concentration
                maxLength: 4
                type: string
              cmjrRule:
                title: Major Rule
                maxLength: 8
                type: number
                description: "Lineage reference object : SORCMJR_CMJR_RULE"
                x-lineageReferenceObject: SORCMJR_CMJR_RULE
              majorDisplay:
                type: string
              recInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_REC_IND"
                x-lineageReferenceObject: SORCMJR_REC_IND
              admInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_ADM_IND"
                x-lineageReferenceObject: SORCMJR_ADM_IND
              majrCode:
                title: Major
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCMJR_MAJR_CODE, Lookup lineage
                  reference object : stvmajr"
                x-lineageReferenceObject: SORCMJR_MAJR_CODE
                x-lineageLookupReferenceObject: stvmajr
              degrCde:
                title: EDI Degree
                maxLength: 3
                type: string
                description: "Lineage reference object : SORCMJR_DEGR_CDE, Lookup lineage
                  reference object : sorxref"
                x-lineageReferenceObject: SORCMJR_DEGR_CDE
                x-lineageLookupReferenceObject: sorxref
              autoDecInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_AUTO_DEC_IND"
                x-lineageReferenceObject: SORCMJR_AUTO_DEC_IND
              dauInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_DAU_IND"
                x-lineageReferenceObject: SORCMJR_DAU_IND
              dispWebInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_DISP_WEB_IND"
                x-lineageReferenceObject: SORCMJR_DISP_WEB_IND
              hisInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_HIS_IND"
                x-lineageReferenceObject: SORCMJR_HIS_IND
              ediQlfr:
                title: EDI Level
                maxLength: 2
                type: string
                description: "Lineage reference object : SORCMJR_EDI_QLFR, Lookup lineage
                  reference object : sorxref"
                x-lineageReferenceObject: SORCMJR_EDI_QLFR
                x-lineageLookupReferenceObject: sorxref
              deptDisplay:
                type: string
              ediValue:
                title: EDI Identification
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCMJR_EDI_VALUE, Lookup lineage
                  reference object : sorxref"
                x-lineageReferenceObject: SORCMJR_EDI_VALUE
                x-lineageLookupReferenceObject: sorxref
              stuInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SORCMJR_STU_IND"
                x-lineageReferenceObject: SORCMJR_STU_IND
              deptCode:
                title: Department
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCMJR_DEPT_CODE, Lookup lineage
                  reference object : stvdept"
                x-lineageReferenceObject: SORCMJR_DEPT_CODE
                x-lineageLookupReferenceObject: stvdept
              desc:
                title: Self Service Description
                maxLength: 60
                type: string
                description: "Lineage reference object : SORCMJR_DESC"
                x-lineageReferenceObject: SORCMJR_DESC
            x-lineageReferenceObject: sorcmjr
    curriculum-rules-major-and-departments-1.0.0_get_request:
      type: object
      properties:
        secdRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBCURR_SECD_ROLL_IND"
          x-lineageReferenceObject: SOBCURR_SECD_ROLL_IND
        termCodeInit:
          title: Effective Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBCURR_TERM_CODE_INIT, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOBCURR_TERM_CODE_INIT
          x-lineageLookupReferenceObject: stvterm
        campCode:
          title: Campus
          maxLength: 3
          type: string
          description: "Lineage reference object : SOBCURR_CAMP_CODE, Lookup lineage
            reference object : stvcamp"
          x-lineageReferenceObject: SOBCURR_CAMP_CODE
          x-lineageLookupReferenceObject: stvcamp
        studyPathInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBCURR_STUDY_PATH_IND"
          x-lineageReferenceObject: SOBCURR_STUDY_PATH_IND
        program:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBCURR_PROGRAM, Lookup lineage
            reference object : smrprle"
          x-lineageReferenceObject: SOBCURR_PROGRAM
          x-lineageLookupReferenceObject: smrprle
        degcCode:
          title: Degree
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBCURR_DEGC_CODE, Lookup lineage
            reference object : stvdegc"
          x-lineageReferenceObject: SOBCURR_DEGC_CODE
          x-lineageLookupReferenceObject: stvdegc
        lockInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBCURR_LOCK_IND"
          x-lineageReferenceObject: SOBCURR_LOCK_IND
        collCode:
          title: College
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBCURR_COLL_CODE, Lookup lineage
            reference object : stvcoll"
          x-lineageReferenceObject: SOBCURR_COLL_CODE
          x-lineageLookupReferenceObject: stvcoll
        currRule:
          title: Base Rule Number
          maxLength: 8
          type: number
          description: "Lineage reference object : SOBCURR_CURR_RULE"
          x-lineageReferenceObject: SOBCURR_CURR_RULE
        primRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBCURR_PRIM_ROLL_IND"
          x-lineageReferenceObject: SOBCURR_PRIM_ROLL_IND
        levlCode:
          title: Level
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBCURR_LEVL_CODE, Lookup lineage
            reference object : stvlevl"
          x-lineageReferenceObject: SOBCURR_LEVL_CODE
          x-lineageLookupReferenceObject: stvlevl
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SOBCURR
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    curriculum-rules-major-and-departments-1.0.0_qapi_post:
      type: object
      properties:
        termCode:
          type: string
        currRule:
          type: string
        program:
          type: string
        levlCode:
          type: string
        campCode:
          type: string
        termCodeInit:
          type: string
        collCode:
          type: string
        degcCode:
          type: string
        primRollInd:
          type: string
        secdRollInd:
          type: string
        lockInd:
          type: string
        studyPathInd:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
