openapi: 3.0.0
info:
  title: transactions-in-process-status
  description: API for FGITINP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FGITINP
  x-source-domain: Finance
  x-source-title: Transaction In Process Status
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/transactions-in-process-status:
    get:
      tags:
        - transactions-in-process-status
      summary: Return resources from FGITINP
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblocCoasCode
          in: query
          required: true
          schema:
            type: string
        - name: keyblocFsyrCode
          in: query
          required: true
          schema:
            type: string
        - name: keyblocAcciCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblocCmtType
          in: query
          required: false
          schema:
            type: string
        - name: keyblocFundCode
          in: query
          required: true
          schema:
            type: string
        - name: keyblocOrgnCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblocAcctCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblocProgCode
          in: query
          required: false
          schema:
            type: string
        - name: docNum
          in: query
          required: false
          schema:
            type: string
        - name: displaySumAdjt
          in: query
          required: false
          schema:
            type: string
        - name: ytdAmt
          in: query
          required: false
          schema:
            type: string
        - name: displaySumRsvr
          in: query
          required: false
          schema:
            type: string
        - name: displayStatus
          in: query
          required: false
          schema:
            type: string
        - name: fundTran
          in: query
          required: false
          schema:
            type: string
        - name: orgnTran
          in: query
          required: false
          schema:
            type: string
        - name: acctTran
          in: query
          required: false
          schema:
            type: string
        - name: progTran
          in: query
          required: false
          schema:
            type: string
        - name: displayDescription
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transactions-in-process-status-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/transactions-in-process-status:
    post:
      tags:
        - transactions-in-process-status QAPI (Query by POST)
      summary: Return resources from FGITINP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/transactions-in-process-status-1.0.0_get_request"
            example:
              keyblocOrgnCode: 100-3
              keyblocAcctCode: 10
              keyblocProgCode: 200
              keyblocFundCode: 100
              keyblocFsyrCode: 22
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transactions-in-process-status-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    transactions-in-process-status-1.0.0_qapi_post:
      required:
        - keyblocCoasCode
        - keyblocFsyrCode
        - keyblocFundCode
      type: object
      properties:
        keyblocCoasCode:
          type: string
        keyblocFsyrCode:
          type: string
        keyblocAcciCode:
          type: string
        keyblocCmtType:
          type: string
        keyblocFundCode:
          type: string
        keyblocOrgnCode:
          type: string
        keyblocAcctCode:
          type: string
        keyblocProgCode:
          type: string
        docNum:
          type: string
        displaySumAdjt:
          type: string
        ytdAmt:
          type: string
        displaySumRsvr:
          type: string
        displayStatus:
          type: string
        fundTran:
          type: string
        orgnTran:
          type: string
        acctTran:
          type: string
        progTran:
          type: string
        displayDescription:
          type: string
    transactions-in-process-status-1.0.0_get_response:
      type: object
      properties:
        fgrbako:
          type: array
          items:
            type: object
            properties:
              displayDescription:
                title: Description
                maxLength: 60
                type: string
              displaySumRsvr:
                title: Commitments
                maxLength: 25
                type: number
              docNum:
                title: Document
                maxLength: 30
                type: string
                description: "Lineage reference object : FGRBAKO_DOC_NUM"
                x-lineageReferenceObject: FGRBAKO_DOC_NUM
              itemNum:
                title: Item
                maxLength: 30
                type: number
                description: "Lineage reference object : FGRBAKO_ITEM_NUM"
                x-lineageReferenceObject: FGRBAKO_ITEM_NUM
              progTran:
                title: Program
                maxLength: 30
                type: string
                description: "Lineage reference object : FGRBAKO_PROG_TRAN"
                x-lineageReferenceObject: FGRBAKO_PROG_TRAN
              ytdAmt:
                title: YTD Activity
                maxLength: 25
                type: number
                description: "Lineage reference object : FGRBAKO_YTD_AMT"
                x-lineageReferenceObject: FGRBAKO_YTD_AMT
              seqNum:
                title: Sequence
                maxLength: 30
                type: number
                description: "Lineage reference object : FGRBAKO_SEQ_NUM"
                x-lineageReferenceObject: FGRBAKO_SEQ_NUM
              orgnTran:
                title: Organization
                maxLength: 30
                type: string
                description: "Lineage reference object : FGRBAKO_ORGN_TRAN"
                x-lineageReferenceObject: FGRBAKO_ORGN_TRAN
              displaySumAdjt:
                title: Adjusted Budget
                maxLength: 25
                type: number
              displayStatus:
                title: Status
                maxLength: 3
                type: string
              acctTran:
                title: Account
                maxLength: 30
                type: string
                description: "Lineage reference object : FGRBAKO_ACCT_TRAN"
                x-lineageReferenceObject: FGRBAKO_ACCT_TRAN
              fundTran:
                title: Fund
                maxLength: 30
                type: string
                description: "Lineage reference object : FGRBAKO_FUND_TRAN"
                x-lineageReferenceObject: FGRBAKO_FUND_TRAN
            x-lineageReferenceObject: fgrbako
        total_block:
          type: array
          items:
            type: object
            properties:
              totalBudgetRsvrtn:
                maxLength: 25
                type: number
                description: "Lineage reference object : totalBudgetRsvrtn"
                x-lineageReferenceObject: totalBudgetRsvrtn
              displayAvailBal:
                title: Available Balance In Process
                maxLength: 25
                type: number
                description: "Lineage reference object : displayAvailBal"
                x-lineageReferenceObject: displayAvailBal
              totalYtdActivity:
                maxLength: 25
                type: number
                description: "Lineage reference object : totalYtdActivity"
                x-lineageReferenceObject: totalYtdActivity
              totalAdjustedBudget:
                title: Total
                maxLength: 25
                type: number
                description: "Lineage reference object : totalAdjustedBudget"
                x-lineageReferenceObject: totalAdjustedBudget
            x-lineageReferenceObject: total_block
    transactions-in-process-status-1.0.0_get_request:
      required:
        - keyblocCoasCode
        - keyblocFsyrCode
      type: object
      properties:
        displayDescription:
          title: Description
          maxLength: 60
          type: string
        docNum:
          title: Document
          maxLength: 30
          type: string
          description: "Lineage reference object : FGRBAKO_DOC_NUM"
          x-lineageReferenceObject: FGRBAKO_DOC_NUM
        displaySumRsvr:
          title: Commitments
          maxLength: 25
          type: number
        progTran:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : FGRBAKO_PROG_TRAN"
          x-lineageReferenceObject: FGRBAKO_PROG_TRAN
        keyblocCoasCode:
          title: Chart
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocCoasCode, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: keyblocCoasCode
          x-lineageLookupReferenceObject: ftvcoas
        displaySumAdjt:
          title: Adjusted Budget
          maxLength: 25
          type: number
        keyblocAcctCode:
          title: Account
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocAcctCode"
          x-lineageReferenceObject: keyblocAcctCode
        displayStatus:
          title: Status
          maxLength: 3
          type: string
        acctTran:
          title: Account
          maxLength: 30
          type: string
          description: "Lineage reference object : FGRBAKO_ACCT_TRAN"
          x-lineageReferenceObject: FGRBAKO_ACCT_TRAN
        keyblocProgCode:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocProgCode"
          x-lineageReferenceObject: keyblocProgCode
        keyblocAcciCode:
          title: Index
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocAcciCode, Lookup lineage
            reference object : ftvacci"
          x-lineageReferenceObject: keyblocAcciCode
          x-lineageLookupReferenceObject: ftvacci
        keyblocOrgnCode:
          title: Organization
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocOrgnCode"
          x-lineageReferenceObject: keyblocOrgnCode
        ytdAmt:
          title: YTD Activity
          maxLength: 25
          type: number
          description: "Lineage reference object : FGRBAKO_YTD_AMT"
          x-lineageReferenceObject: FGRBAKO_YTD_AMT
        keyblocCmtType:
          title: Commit Type
          maxLength: 1
          type: string
          description: "Lineage reference object : keyblocCmtType"
          x-lineageReferenceObject: keyblocCmtType
        orgnTran:
          title: Organization
          maxLength: 30
          type: string
          description: "Lineage reference object : FGRBAKO_ORGN_TRAN"
          x-lineageReferenceObject: FGRBAKO_ORGN_TRAN
        keyblocFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocFundCode"
          x-lineageReferenceObject: keyblocFundCode
        keyblocFsyrCode:
          title: Fiscal Year
          maxLength: 2
          type: string
          description: "Lineage reference object : keyblocFsyrCode, Lookup lineage
            reference object : ftvfspd,ftvfsyr,ftvfspd"
          x-lineageReferenceObject: keyblocFsyrCode
          x-lineageLookupReferenceObject: ftvfspd,ftvfsyr,ftvfspd
        fundTran:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : FGRBAKO_FUND_TRAN"
          x-lineageReferenceObject: FGRBAKO_FUND_TRAN
      x-lineageReferenceObject: FGRBAKO
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
