openapi: 3.0.0
info:
  title: ca-economically-disadvantages
  description: This API returns the economically disadvantages related to the students.
  version: 1.0.0-beta
  x-api-type: erp
  x-audience: all
  x-release-status: beta
  x-source-domain: Student
  x-source-title: Ca Economically Disadvantage
  x-source-system: Banner
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-economically-disadvantages:
    get:
      tags:
        - ca-economically-disadvantages
      summary: Provide the list of ca economically disadvantage.
      description: Provide the list of ca economically disadvantage.
      parameters:
        - name: stuTermCode
          in: query
          description:
            The term code to search values
          required: true
          schema:
            type: string
        - name: stuDicdCode
          in: query
          description:
            The district to search values
          required: true
          schema:
            type: string
        - name: stuEcdvCode
          in: query
          description:
            The economically disadvantaged code to search values
          required: false
          schema:
            type: string
        - name: stuId
          in: query
          description:
            The stuedent identification code to seach values
          required: true
          schema:
            type: string
        - name: criteria
          in: query
          required: false
          schema:
            type: object
        - name: limit
          in: query
          description:
            The maximum number of resources requesting for this result set.
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ca-economically-disadvantages-v1_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client�s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permission: API_ECONOMICALLY_DISADVANTAGES
  /api/ca-economically-disadvantages/:
    post:
      tags:
        - ca-economically-disadvantages
      summary: Store an economically disadvantage record for the given set of Students.
      description: Store an economically disadvantage record for the given set of Students.
      requestBody:
        description: Create a new set of records for the Student's economically disadvanged information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ca-economically-disadvantages-post-request'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ca-economically-disadvantages-post-response'
        '405':
          description: Invalid input
      security:
        - EthosIntegrationBearer: []
components:
  schemas:
    ca-economically-disadvantages-v1_response:
      title: Student Economically Disadvantaged 
      description: The list of the Student's Economically Disadvantaged information.
      type: object
      properties:
        economicallyDisadvantagedStatuses:
           type: object
           properties:
             stuTermCode:
                "title": "effectiveTermCode"
                "description": "EFFECTIVE TERM CODE Effective Term Code used to define the Economically Disadvantaged Data."
                "type": string
                "maxLength": 6
                "x-lineageReferenceObject": SVRECDV.SVRECDV_TERM_CODE_EFF
             stuDicdCode:
                "title": "districtId"
                "description": "DISTRICT ID: The district or division associated with the Economically Disadvantaged Data."
                "type": string
                "maxLength": 3
                "x-lineageReferenceObject": SVRECDV.SVRECDV_DICD_CODE
             stuEcdvCodes:
                title: stuEcdvCodes
                type: array
                items: 
                   type: object
                   properties:
                     stuId:
                        "title": "STUDENT ID: Banner ID of the student."
                        "description": "STUDENT ID: Banner ID of the student."
                        "type": string
                     stuEcdvCodes:
                        title: speTerm
                        type: array
                        items: 
                           type: string
      required:
        - stuId
        - stuTermCode
        - stuDicdCode
    ca-economically-disadvantages-post-request:
      title: Student Economically Disadvantaged List to store
      description: The list of the Student's Economically Disadvantaged information.
      type: object
      properties:
        economicallyDisadvantagedStatuses:
          type: object
          properties:
            stuTermCode:
               "title": "effectiveTermCode"
               "description": "EFFECTIVE TERM CODE: Effective Term Code used to define the Economically Disadvantaged Data."
               "type": string
               "maxLength": 6
               "x-lineageReferenceObject": SVRECDV.SVRECDV_TERM_CODE_EFF
            stuDicdCode:
               "title": "districtId"
               "description": "DISTRICT ID: The district or division associated with the Economically Disadvantaged Data."
               "type": string
               "maxLength": 3
               "x-lineageReferenceObject": SVRECDV.SVRECDV_DICD_CODE
            dataList:
              title: stuEcdvCodes
              type: array
              items: 
                type: object
                properties:
                  stuId:
                    "title": "STUDENT ID: Banner ID of the student."
                    "description": "STUDENT ID: Banner ID of the student."
                    "type": string
                  econDisadvantagedStatusList:
                    title: speTerm
                    type: array
                    items: 
                       type: string
    ca-economically-disadvantages-post-response:
      title: Student Economically Disadvantaged List processed 
      description: The list of the Student's Economically Disadvantaged information.
      type: object
      properties:
        economicallyDisadvantagedStatuses:
          type: object
          properties:
            stuTermCode:
               "title": "effectiveTermCode"
               "description": "EFFECTIVE TERM CODE: Effective Term Code used to define the Economically Disadvantaged Data."
               "type": string
               "maxLength": 6
               "x-lineageReferenceObject": SVRECDV.SVRECDV_TERM_CODE_EFF
            stuDicdCode:
               "title": "districtId"
               "description": "DISTRICT ID: The district or division associated with the Economically Disadvantaged Data."
               "type": string
               "maxLength": 3
               "x-lineageReferenceObject": SVRECDV.SVRECDV_DICD_CODE
            bannerId:
               "title": "STUDENT ID: Banner ID of the student."
               "description": "STUDENT ID: Banner ID of the student."
               "type": string
            econDisadvantagedStatus:
              title: stuEcdvCodes
              type: array
              items: 
                type: object
                properties:
                  message:
                    "title": "message"
                    "description": "The result of the process of this item."
                    "type": string
                  econDisadvantagedStatus:
                    title: econDisadvantagedStatus
                    type: string
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic