openapi: 3.0.0
info:
  title: student-gradable-components-subcomponents
  description: >
    This API allows to update student gradable components and sub components of
    gradebooks.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: Student Gradable Components Subcomponents
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: student-gradable-components-subcomponents
paths:
  /api/student-gradable-components-subcomponents/1:
    put:
      description: >
        __Paging__ Pagination is supported using parameters limit and offset.
        Default value for limit is 500 and upper limit is 1000.

          __Sorting__ NA

        __Filtering__ Filtering is supported using url parameters
        [‘assessmentType’, ‘crn’, ‘term’, ‘componentId’, ‘subComponentId’].
          
        __Example:__
        /api/student-gradable-subcomponents?crn=35002&term=201440&componentId=43&subComponentId=41 
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUD_GRAD_COMP_SUBCOMPS
      tags:
        - student-gradable-components-subcomponents
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/vnd.hedtech.integration.v1.0.0+json
            ```
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
          description: |
            application/vnd.hedtech.integration.v1.0.0+json
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              type: object
              $ref: "#/components/schemas/student-gradable-components-subcomponents-request"
            examples:
              student-gradable-components-subcomponents-request:
                $ref: "#/components/examples/student-gradable-components-subcomponents-request"
      responses:
        "200":
          description: Success
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/student-gradable-components-subcomponents-response"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    student-gradable-components-subcomponents-request:
      type: array
      items:
        type: object
        properties:
          assessmentType:
            type: string
          crn:
            type: string
          term:
            type: string
          componentId:
            type: string
          grades:
            type: array
            items:
              type: object
              properties:
                bannerId:
                  type: string
                completedDate:
                  type: string
                  format: date
                currentReason:
                  type: string
                extensionDate:
                  type: string
                  format: date
                score:
                  type: string
                grade:
                  type: string
                comment:
                  type: string
              required:
                - bannerId
                - completedDate
                - currentReason
        required:
          - crn
          - assessmentType
          - term
          - componentId
    student-gradable-components-subcomponents-response:
      type: array
      items:
        type: object
        properties:
          assessmentType:
            type: string
          crn:
            type: string
          term:
            type: string
          componentId:
            type: string
          successList:
            type: array
            items:
              type: object
              properties:
                bannerId:
                  type: string
                completedDate:
                  type: string
                currentReason:
                  type: string
                extensionDate:
                  type: string
                score:
                  type: string
                grade:
                  type: string
                comment:
                  type: string
                successMessage:
                  type: string
          failureList:
            type: array
            items:
              type: object
              properties:
                bannerId:
                  type: string
                completedDate:
                  type: string
                currentReason:
                  type: string
                extensionDate:
                  type: string
                score:
                  type: string
                grade:
                  type: string
                comment:
                  type: string
                errorMessage:
                  type: string
  examples:
    student-gradable-components-subcomponents-request:
      value: "{

        \   \"assessmentType\": \"assessment\",

        \   \"crn\": \"20489\",

        \   \"term\": \"201410\",

        \   \"componentId\": 70,

        \   \"grades\": [

        \       {

        \           \"bannerId\": \"HOSH00072\",

        \           \"completedDate\": \"2014-10-10\",

        \           \"currentReason\": \"SG\",

        \           \"extensionDate\": \"2018-10-10\",

        \           \"score\":75,

        \           \"grade\": \"A\",

        \           \"comment\": \"Component Comment 1\"

        \       },

        \       {

        \           \"bannerId\": \"HOSH00070\",

        \           \"completedDate\": \"2014-10-10\",

        \           \"extensionDate\": \"2018-10-10\",

        \           \"currentReason\": \"TP\",

        \           \"score\":75,

        \           \"grade\": \"C\",

        \           \"comment\": \"Component Comment 2\"

        \       },

        \       {

        \           \"bannerId\": \"HOSH00001\",

        \           \"completedDate\": \"2015-10-10\",

        \           \"extensionDate\": \"2022-10-10\",

        \           \"currentReason\": \"CA\",

        \           \"score\":100,

        \           \"grade\": \"A\",

        \           \"comment\": \"Component Comment 3\"

        \       }

        \   ]

        }

        \      "
