openapi: 3.0.0
info:
  title: attribute-types-selection
  description: API for FTQATTS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FTQATTS
  x-source-domain: Finance
  x-source-title: Attribute Types Selection
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/attribute-types-selection:
    get:
      tags:
        - attribute-types-selection
      summary: Return resources from FTQATTS
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: coasCode
          in: query
          required: false
          schema:
            type: string
        - name: attsCode
          in: query
          required: false
          schema:
            type: string
        - name: foapalInd
          in: query
          required: false
          schema:
            type: string
        - name: code
          in: query
          description: Ftvattt Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_CODE
        - name: desc
          in: query
          description: Ftvattt Desc
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_DESC
        - name: validAllInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_ALL_IND
        - name: validFundInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_FUND_IND
        - name: validOrgnInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_ORGN_IND
        - name: validAcctInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_ACCT_IND
        - name: validProgInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_PROG_IND
        - name: validActvInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_ACTV_IND
        - name: validLocnInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_VALID_LOCN_IND
        - name: statusInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVATTT_STATUS_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/attribute-types-selection-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/attribute-types-selection:
    post:
      tags:
        - attribute-types-selection QAPI (Query by POST)
      summary: Return resources from FTQATTS
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/attribute-types-selection-1.0.0_get_request"
            example:
              foapalInd: FUND
              coasCode: B
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/attribute-types-selection-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    attribute-types-selection-1.0.0_get_request:
      type: object
      properties:
        code:
          title: Ftvattt Code
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVATTT_CODE"
          x-lineageReferenceObject: FTVATTT_CODE
        validLocnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_LOCN_IND"
          x-lineageReferenceObject: FTVATTT_VALID_LOCN_IND
        validActvInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ACTV_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ACTV_IND
        statusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_STATUS_IND"
          x-lineageReferenceObject: FTVATTT_STATUS_IND
        validOrgnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ORGN_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ORGN_IND
        validFundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_FUND_IND"
          x-lineageReferenceObject: FTVATTT_VALID_FUND_IND
        validAcctInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ACCT_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ACCT_IND
        validProgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_PROG_IND"
          x-lineageReferenceObject: FTVATTT_VALID_PROG_IND
        validAllInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ALL_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ALL_IND
        desc:
          title: Ftvattt Desc
          maxLength: 50
          type: string
          description: "Lineage reference object : FTVATTT_DESC"
          x-lineageReferenceObject: FTVATTT_DESC
      x-lineageReferenceObject: FTVATTT
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    attribute-types-selection-1.0.0_get_response:
      type: object
      properties:
        code:
          title: Ftvattt Code
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVATTT_CODE"
          x-lineageReferenceObject: FTVATTT_CODE
        validLocnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_LOCN_IND"
          x-lineageReferenceObject: FTVATTT_VALID_LOCN_IND
        validActvInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ACTV_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ACTV_IND
        statusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_STATUS_IND"
          x-lineageReferenceObject: FTVATTT_STATUS_IND
        validOrgnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ORGN_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ORGN_IND
        validAcctInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ACCT_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ACCT_IND
        validFundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_FUND_IND"
          x-lineageReferenceObject: FTVATTT_VALID_FUND_IND
        validProgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_PROG_IND"
          x-lineageReferenceObject: FTVATTT_VALID_PROG_IND
        addInd:
          maxLength: 1
          type: string
        validAllInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ALL_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ALL_IND
        desc:
          title: Ftvattt Desc
          maxLength: 50
          type: string
          description: "Lineage reference object : FTVATTT_DESC"
          x-lineageReferenceObject: FTVATTT_DESC
      x-lineageReferenceObject: ftvattt
    attribute-types-selection-1.0.0_qapi_post:
      type: object
      properties:
        coasCode:
          type: string
        attsCode:
          type: string
        foapalInd:
          type: string
        code:
          title: Ftvattt Code
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVATTT_CODE"
          x-lineageReferenceObject: FTVATTT_CODE
        desc:
          title: Ftvattt Desc
          maxLength: 50
          type: string
          description: "Lineage reference object : FTVATTT_DESC"
          x-lineageReferenceObject: FTVATTT_DESC
        validAllInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ALL_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ALL_IND
        validFundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_FUND_IND"
          x-lineageReferenceObject: FTVATTT_VALID_FUND_IND
        validOrgnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ORGN_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ORGN_IND
        validAcctInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ACCT_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ACCT_IND
        validProgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_PROG_IND"
          x-lineageReferenceObject: FTVATTT_VALID_PROG_IND
        validActvInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_ACTV_IND"
          x-lineageReferenceObject: FTVATTT_VALID_ACTV_IND
        validLocnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_VALID_LOCN_IND"
          x-lineageReferenceObject: FTVATTT_VALID_LOCN_IND
        statusInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVATTT_STATUS_IND"
          x-lineageReferenceObject: FTVATTT_STATUS_IND
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
