openapi: 3.0.0
info:
  title: Student Advisor Relationships Submission Process
  description: Process student advisor relationship adjustments and deletions.
  version: 1.0.0
  x-api-type: ethos
  x-release-status: ga
  x-source-system: banner
  x-audience: all
  x-source-domain: Student
  x-source-name: SGRADVR
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/student-advisor-relationships-submission-process:
    post:
      tags:
        - student-advisor-relationships-submission-process
      summary: The student-advisor-relationships-submission-process API will allow the advisor record for the student (SubjectPerson) to be modified, ended, or removed from the SGRADVR table.
      description: > 
        The student-advisor-relationships-submission-process API will allow the advisor record for the student (SubjectPerson) to be modified, ended, or removed from the SGRADVR table.  
        This is a companion API to student-advisor-relationships to retrieve advising assignments.
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
      requestBody:
        content:
          application/vnd.hedtech.integration.1.0.0+json:
            schema:
              type: object
              $ref: '#/components/schemas/student-advisor-relationships-submission-process-1.0.0_post_request'
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response.
              required: true
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1-WholeVersion+json:
              schema:
                type: object
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client’s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
      - EthosIntegrationBearer: []
      - BasicAuth: []
      x-method-permissions: API_STUD_ADVR_RELS_SUBM_PRCS
components:
  schemas:
    student-advisor-relationships-submission-process-1.0.0_post_request:
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This
                is informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
              - type: string
                format: date-time
                pattern: "^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$"
              - type: string
                maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
              - type: string
                format: date-time
                pattern: "^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$"
              - type: string
                maxLength: 0
          additionalProperties: false
        student:
          title: Student
          description: The unique person identifier for the student for whom the advisor
            relationships will be adjusted.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Student.
              type: string
              format: guid
              pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
              example: "cefeacb8-4fca-43b3-9331-c0228ff3ee55"
          additionalProperties: false
          required:
          - id
        advisorRelationshipAdjustments:
          title: Advisor Relationship Adjustments
          description: Adjustments to be made to the student's advisor relationships
          oneOf:
          - title: Adjust Advisors
            description: Insert or replace all advisors as of a specified time period
            type: object
            properties:
              startPeriod:
                title: Start Period
                description: The effective start period of the advisor adjustments
                oneOf:
                - title: Start Date
                  description: The date the advisor adjustments should start.
                  type: string
                  format: date
                  pattern: "^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$"
                  example: "15f65b3c-3729-4fb9-9d3b-743b3f110c14"
                - title: Start Academic Period
                  description: The Academic Period the advisor adjustments should start
                  type: object
                  properties:
                    id:
                      title: ID
                      description: The global identifier for the Start Academic Period.
                      type: string
                      format: guid
                      pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
                      example: "2ec005eb-1216-4d7b-86a5-8839d9d2cf25"
                  additionalProperties: false
                  required:
                  - id
              advisors:
                title: Advisors
                description: The advisors that will replace existing advisors or be inserted
                  if no active advisors exists for the student.
                type: array
                items:
                  type: object
                  properties:
                    advisor:
                      title: Advisor
                      description: The unique person identifier for the advisor.
                      type: object
                      properties:
                        id:
                          title: ID
                          description: The global identifier for the Advisor.
                          type: string
                          format: guid
                          pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
                          example: "d9c471eb-8e11-4263-9e64-499308e6c758"
                      additionalProperties: false
                    advisorType:
                      title: Advisor Type
                      description: The advisor type assigned to this student/advisor relationship
                      type: object
                      properties:
                        id:
                          title: ID
                          description: The global identifier for the Advisor Type.
                          type: string
                          format: guid
                          pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
                          example: "a3442978-a1a6-4fa5-bef0-8a1dfb87bd28"
                      additionalProperties: false
                    academicProgram:
                      title: Academic Program
                      description: The academic program associated with this student/advisor
                        relationship
                      type: object
                      properties:
                        id:
                          title: ID
                          description: The global identifier for the Academic Program.
                          type: string
                          format: guid
                          pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
                          example: "b49e91a8-416d-4c39-9726-834eb379108f"
                      additionalProperties: false
                    assignedPriority:
                      title: Assigned Priority
                      description: The assignment priority to this student/advisor relationship.
                      enum:
                      - primary
                      type: string
                      example: "primary"
                  additionalProperties: false
            required: 
              - startPeriod
              - advisors
            additionalProperties: false
          - title: End Advisor Assignments
            description: End all student/advisor assignments as of specified time period
            type: object
            properties:
              endPeriod:
                title: endPeriod
                description: The effective ending period for all advisor relationships.
                oneOf:
                - title: End Date
                  description: The ending date of all the student/advisor relationships
                    for the student.
                  type: string
                  format: date
                  pattern: "^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$"
                  example: "2024-05-01"
                - title: End Academic Period
                  description: The effective academic period when all the student/advisor
                    relationships should end.
                  type: object
                  properties:
                    id:
                      title: ID
                      description: The global identifier for the End Academic Period.
                      type: string
                      format: guid
                      pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
                      example: db795470-57da-4099-849c-8fb792903422
                  additionalProperties: false
                  required:
                  - id
                  - endAcademicPeriod
            required:
              - endPeriod
            additionalProperties: false
          - title: Delete Advisor
            description: Delete a specified advisor from the student's advisor relationships
              regardless of time periods.
            type: object
            properties:
              advisor:
                title: Advisor
                description: The unique person identifier of the advisor to be deleted from
                  the student's advisor relationships.
                type: object
                properties:
                  id:
                    title: ID
                    description: The global identifier for the Advisor.
                    type: string
                    format: guid
                    pattern: "^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$"
                    example: 9e93a647-9bb3-46c7-9b76-56a230c72928
                required:
                - id
            required:
              - advisor
            additionalProperties: false
      required:
      - student
      - advisorRelationshipAdjustments
      additionalProperties: false
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
              type: object
              properties:
                id:
                  type: string
                  description: The global identifier of the resource in error.
                sourceId:
                  type: string
                  description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
                code:
                  type: string
                  description: The error message code used to describe the error details.
                description:
                  type: string
                  description: The error description used to describe the error details.
                message:
                  type: string
                  description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic