openapi: 3.0.0
info:
  title: curricula-summary-honors-institutional-honors
  description: >
    API for SHADEGR administrative page.<br> Allowed values for below fields are
    "Y" and null
     - transcPrtInd
     - commencePrtInd
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SHADEGR
  x-source-domain: Student
  x-source-title: Degree and Other Formal Awards
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/curricula-summary-honors-institutional-honors:
    put:
      tags:
        - curricula-summary-honors-institutional-honors
      summary: Updates an existing resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-institutional-honors-1.0.0\
                _put_request"
            example:
              criteria.honrCode: C
              honrCode: N
              criteria.transcPrtInd: Y
              commencePrtInd: Y
              transcPrtInd: Y
              id: HOSJ00002
              ediDefault: null
              dgmrSeqNo: "1"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-institutional-honors-1.0.0\
                    _put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - curricula-summary-honors-institutional-honors
      summary: Creates a new resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-institutional-honors-1.0.0\
                _post_request"
            example:
              SHRDGIH:
                - honrCode: M
                  commencePrtInd: Y
                  transcPrtInd: null
                - honrCode: C
                  commencePrtInd: null
                  transcPrtInd: Y
              id: HOSJ00002
              dgmrSeqNo: "1"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-institutional-honors-1.0.0\
                    _post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    delete:
      tags:
        - curricula-summary-honors-institutional-honors
      summary: Deletes an existing resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-institutional-honors-1.0.0\
                _delete_request"
            example:
              id: HOSJ00002
              dgmrSeqNo: "1"
              criteria.honrCode: C
              criteria.commencePrtInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-institutional-honors-1.0.0\
                    _delete_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/curricula-summary-honors-institutional-honors: {}
components:
  schemas:
    curricula-summary-honors-institutional-honors-1.0.0_delete_request:
      required:
        - criteria.honrCode
      type: object
      properties:
        criteria.honrCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGIH_HONR_CODE, Lookup lineage
            reference object : stvhonr"
          x-lineageReferenceObject: SHRDGIH_HONR_CODE
          x-lineageLookupReferenceObject: stvhonr
        criteria.ediDefault:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_EDI_DEFAULT"
          x-lineageReferenceObject: SHRDGIH_EDI_DEFAULT
        criteria.transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_TRANSC_PRT_IND
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
        criteria.commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_COMMENCE_PRT_IND
      x-lineageReferenceObject: SHRDGIH
    curricula-summary-honors-institutional-honors-1.0.0_put_response:
      required:
        - honrCode
      type: object
      properties:
        honrCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGIH_HONR_CODE, Lookup lineage
            reference object : stvhonr"
          x-lineageReferenceObject: SHRDGIH_HONR_CODE
          x-lineageLookupReferenceObject: stvhonr
        commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_COMMENCE_PRT_IND
        stvhonrDesc:
          title: Institutional Honors Description
          type: string
        transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_TRANSC_PRT_IND
        ediDefault:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_EDI_DEFAULT"
          x-lineageReferenceObject: SHRDGIH_EDI_DEFAULT
      x-lineageReferenceObject: shrdgih
    curricula-summary-honors-institutional-honors-1.0.0_post_request:
      required:
        - SHRDGIH
      type: object
      properties:
        SHRDGIH:
          type: array
          items:
            required:
              - honrCode
            type: object
            properties:
              honrCode:
                title: Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SHRDGIH_HONR_CODE, Lookup lineage
                  reference object : stvhonr"
                x-lineageReferenceObject: SHRDGIH_HONR_CODE
                x-lineageLookupReferenceObject: stvhonr
              commencePrtInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SHRDGIH_COMMENCE_PRT_IND"
                x-lineageReferenceObject: SHRDGIH_COMMENCE_PRT_IND
              transcPrtInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SHRDGIH_TRANSC_PRT_IND"
                x-lineageReferenceObject: SHRDGIH_TRANSC_PRT_IND
              ediDefault:
                maxLength: 1
                type: string
                description: "Lineage reference object : SHRDGIH_EDI_DEFAULT"
                x-lineageReferenceObject: SHRDGIH_EDI_DEFAULT
            x-lineageReferenceObject: SHRDGIH
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
      x-lineageReferenceObject: KEY_BLOCK
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    curricula-summary-honors-institutional-honors-1.0.0_delete_response:
      type: object
    curricula-summary-honors-institutional-honors-1.0.0_post_response:
      required:
        - honrCode
      type: object
      properties:
        honrCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGIH_HONR_CODE, Lookup lineage
            reference object : stvhonr"
          x-lineageReferenceObject: SHRDGIH_HONR_CODE
          x-lineageLookupReferenceObject: stvhonr
        commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_COMMENCE_PRT_IND
        stvhonrDesc:
          title: Institutional Honors Description
          type: string
        transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_TRANSC_PRT_IND
        ediDefault:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_EDI_DEFAULT"
          x-lineageReferenceObject: SHRDGIH_EDI_DEFAULT
      x-lineageReferenceObject: shrdgih
    curricula-summary-honors-institutional-honors-1.0.0_put_request:
      required:
        - criteria.honrCode
      type: object
      properties:
        criteria.honrCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGIH_HONR_CODE, Lookup lineage
            reference object : stvhonr"
          x-lineageReferenceObject: SHRDGIH_HONR_CODE
          x-lineageLookupReferenceObject: stvhonr
        criteria.ediDefault:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_EDI_DEFAULT"
          x-lineageReferenceObject: SHRDGIH_EDI_DEFAULT
        honrCode:
          title: Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SHRDGIH_HONR_CODE, Lookup lineage
            reference object : stvhonr"
          x-lineageReferenceObject: SHRDGIH_HONR_CODE
          x-lineageLookupReferenceObject: stvhonr
        criteria.transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_TRANSC_PRT_IND
        commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_COMMENCE_PRT_IND
        transcPrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_TRANSC_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_TRANSC_PRT_IND
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        ediDefault:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_EDI_DEFAULT"
          x-lineageReferenceObject: SHRDGIH_EDI_DEFAULT
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
        criteria.commencePrtInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SHRDGIH_COMMENCE_PRT_IND"
          x-lineageReferenceObject: SHRDGIH_COMMENCE_PRT_IND
      x-lineageReferenceObject: SHRDGIH
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
