openapi: 3.0.0
info:
  title: installation-controls
  description: API for GUAINST administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: GUAINST
  x-source-domain: Foundation
  x-source-title: Installation Controls
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/installation-controls:
    get:
      tags:
        - installation-controls
      summary: Return resources from GUAINST
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/installation-controls-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/installation-controls:
    post:
      tags:
        - installation-controls QAPI (Query by POST)
      summary: Return resources from GUAINST
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/installation-controls-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/installation-controls-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    installation-controls-1.0.0_qapi_post:
      type: object
    installation-controls-1.0.0_get_response:
      required:
        - baseCurrCode
        - city
        - highedGovtInd
        - name
        - operatingSystemInd
        - sinMsgType
        - ssnMaxLength
      type: object
      properties:
        streetLine2:
          title: Street Line 2
          maxLength: 75
          type: string
          description: "Lineage reference object : GUBINST_STREET_LINE2"
          x-lineageReferenceObject: GUBINST_STREET_LINE2
        streetLine1:
          title: Street Line 1
          maxLength: 75
          type: string
          description: "Lineage reference object : GUBINST_STREET_LINE1"
          x-lineageReferenceObject: GUBINST_STREET_LINE1
        finaidInstalled:
          title: Financial Aid
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_FINAID_INSTALLED"
          x-lineageReferenceObject: GUBINST_FINAID_INSTALLED
        posbudRelease:
          maxLength: 10
          type: string
        currTitle:
          type: string
        highedGovtInd:
          title: Installation Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_HIGHED_GOVT_IND"
          x-lineageReferenceObject: GUBINST_HIGHED_GOVT_IND
        streetLine3:
          title: Street Line 3
          maxLength: 75
          type: string
          description: "Lineage reference object : GUBINST_STREET_LINE3"
          x-lineageReferenceObject: GUBINST_STREET_LINE3
        zipDefaultLength:
          title: ZIP/Postal Code Length
          maxLength: 2
          type: number
          description: "Lineage reference object : GUBINST_ZIP_DEFAULT_LENGTH"
          x-lineageReferenceObject: GUBINST_ZIP_DEFAULT_LENGTH
        posbudStageDate:
          maxLength: 11
          type: string
          format: date-time
        baseCurrCode:
          title: Base Currency
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBINST_BASE_CURR_CODE, Lookup lineage
            reference object : gtvcurr"
          x-lineageReferenceObject: GUBINST_BASE_CURR_CODE
          x-lineageLookupReferenceObject: gtvcurr
        persistProfileInd:
          title: User Preferences for Admin Enabled
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_PERSIST_PROFILE_IND"
          x-lineageReferenceObject: GUBINST_PERSIST_PROFILE_IND
        humanreRelease:
          maxLength: 10
          type: string
        finaidRelease:
          maxLength: 10
          type: string
        onlineMatchInd:
          title: Online Matching Process Enabled
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_ONLINE_MATCH_IND"
          x-lineageReferenceObject: GUBINST_ONLINE_MATCH_IND
        finaidStageDate:
          maxLength: 11
          type: string
          format: date-time
        zip:
          title: Zip
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBINST_ZIP, Lookup lineage reference
            object : gtvzipc"
          x-lineageReferenceObject: GUBINST_ZIP
          x-lineageLookupReferenceObject: gtvzipc
        generalStageDate:
          maxLength: 11
          type: string
          format: date-time
        ssnMaxLength:
          title: SSN/SIN/TIN Maximum Length
          maxLength: 2
          type: number
          description: "Lineage reference object : GUBINST_SSN_MAX_LENGTH"
          x-lineageReferenceObject: GUBINST_SSN_MAX_LENGTH
        utcOffset:
          title: UTC Offset
          maxLength: 6
          type: string
          description: "Lineage reference object : GUBINST_UTC_OFFSET"
          x-lineageReferenceObject: GUBINST_UTC_OFFSET
        financeStageDate:
          title: Date
          maxLength: 11
          type: string
          format: date-time
        generalRelease:
          maxLength: 10
          type: string
        humanreStageDate:
          maxLength: 11
          type: string
          format: date-time
        studentInstalled:
          title: Student
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_STUDENT_INSTALLED"
          x-lineageReferenceObject: GUBINST_STUDENT_INSTALLED
        timeZoneName:
          maxLength: 100
          type: string
          description: "Lineage reference object : GUBINST_TIMEZONE_NAME, Lookup lineage
            reference object : V,TIMEZONE_NAMES"
          x-lineageReferenceObject: GUBINST_TIMEZONE_NAME
          x-lineageLookupReferenceObject: V,TIMEZONE_NAMES
        posbudInstalled:
          title: Position Control
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_POSBUD_INSTALLED"
          x-lineageReferenceObject: GUBINST_POSBUD_INSTALLED
        phone:
          title: Phone Number
          maxLength: 12
          type: string
          description: "Lineage reference object : GUBINST_PHONE"
          x-lineageReferenceObject: GUBINST_PHONE
        name:
          title: Name
          maxLength: 60
          type: string
          description: "Lineage reference object : GUBINST_NAME"
          x-lineageReferenceObject: GUBINST_NAME
        utcWithOffset:
          title: "With Offset:"
          type: string
          format: date-time
        phoneArea:
          title: Area Code
          maxLength: 6
          type: string
          description: "Lineage reference object : GUBINST_PHONE_AREA"
          x-lineageReferenceObject: GUBINST_PHONE_AREA
        convRateMethodInd:
          title: Display Conversion Rate Multiplier Method
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBINST_CONV_RATE_METHOD_IND"
          x-lineageReferenceObject: GUBINST_CONV_RATE_METHOD_IND
        financeInstalled:
          title: Finance
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_FINANCE_INSTALLED"
          x-lineageReferenceObject: GUBINST_FINANCE_INSTALLED
        sinMsgType:
          title: SIN Validation
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_SIN_MSG_TYPE"
          x-lineageReferenceObject: GUBINST_SIN_MSG_TYPE
        city:
          title: City
          maxLength: 50
          type: string
          description: "Lineage reference object : GUBINST_CITY"
          x-lineageReferenceObject: GUBINST_CITY
        instanceName:
          title: Instance Name
          maxLength: 8
          type: string
          description: "Lineage reference object : GUBINST_INSTANCE_NAME"
          x-lineageReferenceObject: GUBINST_INSTANCE_NAME
        operatingSystemInd:
          title: Operating/System
          maxLength: 3
          type: string
          description: "Lineage reference object : GUBINST_OPERATING_SYSTEM_IND"
          x-lineageReferenceObject: GUBINST_OPERATING_SYSTEM_IND
        finaidInd:
          title: Other Financial Aid
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_FINAID_IND"
          x-lineageReferenceObject: GUBINST_FINAID_IND
        bilcshInstalled:
          title: Accounts Receivable
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_BILCSH_INSTALLED"
          x-lineageReferenceObject: GUBINST_BILCSH_INSTALLED
        dateDefaultFormat:
          title: Default Date Format
          maxLength: 1
          type: number
          description: "Lineage reference object : GUBINST_DATE_DEFAULT_FORMAT"
          x-lineageReferenceObject: GUBINST_DATE_DEFAULT_FORMAT
        humanreInstalled:
          title: Human Resources
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_HUMANRE_INSTALLED"
          x-lineageReferenceObject: GUBINST_HUMANRE_INSTALLED
        ssnSearchEnabledInd:
          title: SSN/SIN/TIN Search Enabled
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_SSN_SEARCH_ENABLED_IND"
          x-lineageReferenceObject: GUBINST_SSN_SEARCH_ENABLED_IND
        centuryPivot:
          title: Batch Century Pivot
          maxLength: 2
          type: number
          description: "Lineage reference object : GUBINST_CENTURY_PIVOT"
          x-lineageReferenceObject: GUBINST_CENTURY_PIVOT
        bilcshStageDate:
          maxLength: 11
          type: string
          format: date-time
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBINST_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GUBINST_ACTIVITY_DATE
        alumniInstalled:
          title: Advancement
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_ALUMNI_INSTALLED"
          x-lineageReferenceObject: GUBINST_ALUMNI_INSTALLED
        utcTime:
          title: "Current UTC:"
          type: string
          format: date-time
        messageEnabledInd:
          title: Messaging Enabled
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_MESSAGE_ENABLED_IND"
          x-lineageReferenceObject: GUBINST_MESSAGE_ENABLED_IND
        generalInstalled:
          title: General
          maxLength: 1
          type: string
        studentStageDate:
          maxLength: 11
          type: string
          format: date-time
        phoneExt:
          title: Extension
          maxLength: 10
          type: string
          description: "Lineage reference object : GUBINST_PHONE_EXT"
          x-lineageReferenceObject: GUBINST_PHONE_EXT
        financeRelease:
          title: Release
          maxLength: 10
          type: string
        statCode:
          title: State
          maxLength: 3
          type: string
          description: "Lineage reference object : GUBINST_STAT_CODE, Lookup lineage
            reference object : stvstat"
          x-lineageReferenceObject: GUBINST_STAT_CODE
          x-lineageLookupReferenceObject: stvstat
        natnCode:
          title: Nation
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBINST_NATN_CODE, Lookup lineage
            reference object : stvnatn"
          x-lineageReferenceObject: GUBINST_NATN_CODE
          x-lineageLookupReferenceObject: stvnatn
        studentRelease:
          maxLength: 10
          type: string
        wfEnabledInd:
          title: Workflow Enabled
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_WF_ENABLED_IND"
          x-lineageReferenceObject: GUBINST_WF_ENABLED_IND
        alumniStageDate:
          title: Date
          maxLength: 11
          type: string
          format: date-time
        natnDescription:
          type: string
        bilcshRelease:
          maxLength: 10
          type: string
        maxOpenForms:
          title: Maximum Number of Open Forms
          maxLength: 3
          type: number
          description: "Lineage reference object : GUBINST_MAX_OPEN_FORMS"
          x-lineageReferenceObject: GUBINST_MAX_OPEN_FORMS
        sqltraceEnabledInd:
          title: SQL Trace Enabled
          maxLength: 1
          type: string
          description: "Lineage reference object : GUBINST_SQLTRACE_ENABLED_IND"
          x-lineageReferenceObject: GUBINST_SQLTRACE_ENABLED_IND
        alumniRelease:
          title: Release
          maxLength: 10
          type: string
      x-lineageReferenceObject: gubinst
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    installation-controls-1.0.0_get_request:
      type: object
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
