openapi: 3.0.0
info:
  title: curricula-summary-honors-comments
  description: >
    API for SHADEGR administrative page.<br> While adding new comment in Honors
    section, the comment would be added after the first existing comment. If a
    filter is used to identify a single row before adding a new comment then the
    new comment will be added below the existing comments. In case the filter is
    used to identify multiple rows then it will be placed after the first
    comment filtered.
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SHADEGR
  x-source-domain: Student
  x-source-title: Degree and Other Formal Awards
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/curricula-summary-honors-comments:
    put:
      tags:
        - curricula-summary-honors-comments
      summary: Updates an existing resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-comments-1.0.0_put_request"
            example:
              comment: AAA
              id: HOSJ00002
              criteria.comment: please%
              dgmrSeqNo: "1"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-comments-1.0.0_put_respons\
                    e"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - curricula-summary-honors-comments
      summary: Creates a new resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-comments-1.0.0_post_reques\
                t"
            example:
              id: HOSJ00002
              dgmrSeqNo: "1"
              SHRDGCM:
                - comment: please review the honors, posted using multiple post method
                - comment: great work done
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-comments-1.0.0_post_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    delete:
      tags:
        - curricula-summary-honors-comments
      summary: Deletes an existing resource in SHADEGR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/curricula-summary-honors-comments-1.0.0_delete_requ\
                est"
            example:
              id: HOSJ00002
              dgmrSeqNo: "1"
              criteria.comment: gap
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/curricula-summary-honors-comments-1.0.0_delete_resp\
                    onse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/curricula-summary-honors-comments: {}
components:
  schemas:
    curricula-summary-honors-comments-1.0.0_post_request:
      required:
        - SHRDGCM
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        criteria.comment:
          title: Degree Comments
          maxLength: 60
          type: string
          description: "Lineage reference object : SHRDGCM_COMMENT"
          x-lineageReferenceObject: SHRDGCM_COMMENT
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
        SHRDGCM:
          type: array
          items:
            required:
              - comment
            type: object
            properties:
              comment:
                title: Degree Comments
                maxLength: 60
                type: string
                description: "Lineage reference object : SHRDGCM_COMMENT"
                x-lineageReferenceObject: SHRDGCM_COMMENT
            x-lineageReferenceObject: SHRDGCM
      x-lineageReferenceObject: SHRDGCM
    curricula-summary-honors-comments-1.0.0_delete_response:
      type: object
    curricula-summary-honors-comments-1.0.0_put_response:
      required:
        - comment
      type: object
      properties:
        comment:
          title: Degree Comments
          maxLength: 60
          type: string
          description: "Lineage reference object : SHRDGCM_COMMENT"
          x-lineageReferenceObject: SHRDGCM_COMMENT
      x-lineageReferenceObject: shrdgcm
    curricula-summary-honors-comments-1.0.0_put_request:
      required:
        - comment
        - criteria.comment
      type: object
      properties:
        comment:
          title: Degree Comments
          maxLength: 60
          type: string
          description: "Lineage reference object : SHRDGCM_COMMENT"
          x-lineageReferenceObject: SHRDGCM_COMMENT
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        criteria.comment:
          title: Degree Comments
          maxLength: 60
          type: string
          description: "Lineage reference object : SHRDGCM_COMMENT"
          x-lineageReferenceObject: SHRDGCM_COMMENT
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
      x-lineageReferenceObject: SHRDGCM
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    curricula-summary-honors-comments-1.0.0_delete_request:
      required:
        - criteria.comment
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        holdOverrideInd:
          title: Override Hold
          maxLength: 1
          type: string
          description: "Lineage reference object : holdOverrideInd"
          x-lineageReferenceObject: holdOverrideInd
        criteria.comment:
          title: Degree Comments
          maxLength: 60
          type: string
          description: "Lineage reference object : SHRDGCM_COMMENT"
          x-lineageReferenceObject: SHRDGCM_COMMENT
        dgmrSeqNo:
          title: Degree Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : dgmrSeqNo"
          x-lineageReferenceObject: dgmrSeqNo
      x-lineageReferenceObject: SHRDGCM
    curricula-summary-honors-comments-1.0.0_post_response:
      required:
        - comment
      type: object
      properties:
        comment:
          title: Degree Comments
          maxLength: 60
          type: string
          description: "Lineage reference object : SHRDGCM_COMMENT"
          x-lineageReferenceObject: SHRDGCM_COMMENT
      x-lineageReferenceObject: shrdgcm
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
