openapi: 3.0.0
info:
  title: electronic-personnel-action-other-information-and-comments
  description: API for NOAEPAF administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: NOAEPAF
  x-source-domain: Human Resources
  x-source-title: Electronic Personnel Action
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/electronic-personnel-action-other-information-and-comments:
    get:
      tags:
        - electronic-personnel-action-other-information-and-comments
      summary: Return resources from NOAEPAF
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: transNo
          in: query
          required: false
          schema:
            type: string
        - name: effectiveDate
          in: query
          required: false
          schema:
            type: string
        - name: acatCode
          in: query
          required: true
          schema:
            type: string
        - name: aptyCode
          in: query
          required: true
          schema:
            type: string
        - name: posn
          in: query
          required: false
          schema:
            type: string
        - name: suffix
          in: query
          required: false
          schema:
            type: string
        - name: proxyForUserId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/electronic-personnel-action-other-information-and-c\
                    omments-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
    post:
      tags:
        - electronic-personnel-action-other-information-and-comments
      summary: Creates a new resource in NOAEPAF
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/electronic-personnel-action-other-information-and-c\
                omments-1.0.0_post_request"
            example:
              acatCode: IDEN
              comments: test
              aptyCode: IDEN
              id: GENERATED
              transNo: 439
              effectiveDate: 2005-09-20
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/electronic-personnel-action-other-information-and-c\
                    omments-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
  /qapi/electronic-personnel-action-other-information-and-comments:
    post:
      tags:
        - electronic-personnel-action-other-information-and-comments QAPI (Query
          by POST)
      summary: Return resources from NOAEPAF
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/electronic-personnel-action-other-information-and-c\
                omments-1.0.0_get_request"
            example:
              acatCode: 2ADDR
              aptyCode: ADDR
              id: LMRFND002
              transNo: 6619
              effectiveDate: 2021-09-08
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/electronic-personnel-action-other-information-and-c\
                    omments-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    electronic-personnel-action-other-information-and-comments-1.0.0_post_request:
      type: object
      properties:
        proxyForUserId:
          title: Proxy For
          maxLength: 30
          type: string
          description: "Lineage reference object : proxyForUserId"
          x-lineageReferenceObject: proxyForUserId
        acatCode:
          title: Approval Category
          maxLength: 6
          type: string
          description: "Lineage reference object : acatCode"
          x-lineageReferenceObject: acatCode
        comments:
          title: Comments
          maxLength: 4000
          type: string
          description: "Lineage reference object : NORCMNT_COMMENTS"
          x-lineageReferenceObject: NORCMNT_COMMENTS
        aptyCode:
          title: Approval Type
          maxLength: 6
          type: string
          description: "Lineage reference object : aptyCode, Lookup lineage reference
            object : ntracat,ntvapty"
          x-lineageReferenceObject: aptyCode
          x-lineageLookupReferenceObject: ntracat,ntvapty
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        transNo:
          title: Transaction
          maxLength: 15
          type: number
          description: "Lineage reference object : transNo"
          x-lineageReferenceObject: transNo
        suffix:
          title: Suffix
          maxLength: 2
          type: string
          description: "Lineage reference object : suffix"
          x-lineageReferenceObject: suffix
        effectiveDate:
          title: Query Date
          maxLength: 11
          type: string
          description: "Lineage reference object : effectiveDate"
          format: date-time
          x-lineageReferenceObject: effectiveDate
        posn:
          title: Position
          maxLength: 6
          type: string
          description: "Lineage reference object : posn"
          x-lineageReferenceObject: posn
      x-lineageReferenceObject: NORCMNT
    electronic-personnel-action-other-information-and-comments-1.0.0_get_response:
      required:
        - activityDate
      type: object
      properties:
        activityDate:
          title: Date and Time
          maxLength: 26
          type: string
          description: "Lineage reference object : NORCMNT_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: NORCMNT_ACTIVITY_DATE
        comments:
          title: Comments
          maxLength: 4000
          type: string
          description: "Lineage reference object : NORCMNT_COMMENTS"
          x-lineageReferenceObject: NORCMNT_COMMENTS
        userId:
          title: Made By
          maxLength: 30
          type: string
          description: "Lineage reference object : NORCMNT_USER_ID"
          x-lineageReferenceObject: NORCMNT_USER_ID
      x-lineageReferenceObject: norcmnt
    electronic-personnel-action-other-information-and-comments-1.0.0_post_response:
      type: object
      properties:
        nobtran_info_1:
          type: array
          items:
            required:
              - nobtranCreatedDate
              - nobtranOriginatorUserId
            type: object
            properties:
              nobtranApplyUserId:
                title: Applied to Database By
                maxLength: 30
                type: string
                description: "Lineage reference object : NOBTRAN_APPLY_USER_ID"
                x-lineageReferenceObject: NOBTRAN_APPLY_USER_ID
              nobtranOriginatorUserId:
                title: Originator ID
                maxLength: 30
                type: string
                description: "Lineage reference object : NOBTRAN_ORIGINATOR_USER_ID"
                x-lineageReferenceObject: NOBTRAN_ORIGINATOR_USER_ID
              dataSeparatorLine0:
                type: string
              nobtranSubmissionDate:
                title: Submitted Date
                maxLength: 11
                type: string
                description: "Lineage reference object : NOBTRAN_SUBMISSION_DATE"
                format: date-time
                x-lineageReferenceObject: NOBTRAN_SUBMISSION_DATE
              nobtranSubmittorUserId:
                title: Submitter ID
                maxLength: 30
                type: string
                description: "Lineage reference object : NOBTRAN_SUBMITTOR_USER_ID"
                x-lineageReferenceObject: NOBTRAN_SUBMITTOR_USER_ID
              nobtranApplyDate:
                title: Application Date
                maxLength: 11
                type: string
                description: "Lineage reference object : NOBTRAN_APPLY_DATE"
                format: date-time
                x-lineageReferenceObject: NOBTRAN_APPLY_DATE
              nobtranCreatedDate:
                title: Created Date
                maxLength: 11
                type: string
                description: "Lineage reference object : NOBTRAN_CREATED_DATE"
                format: date-time
                x-lineageReferenceObject: NOBTRAN_CREATED_DATE
            x-lineageReferenceObject: nobtran_info_1
        norcmnt:
          type: array
          items:
            required:
              - activityDate
            type: object
            properties:
              activityDate:
                title: Date and Time
                maxLength: 26
                type: string
                description: "Lineage reference object : NORCMNT_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: NORCMNT_ACTIVITY_DATE
              comments:
                title: Comments
                maxLength: 4000
                type: string
                description: "Lineage reference object : NORCMNT_COMMENTS"
                x-lineageReferenceObject: NORCMNT_COMMENTS
              userId:
                title: Made By
                maxLength: 30
                type: string
                description: "Lineage reference object : NORCMNT_USER_ID"
                x-lineageReferenceObject: NORCMNT_USER_ID
            x-lineageReferenceObject: norcmnt
    electronic-personnel-action-other-information-and-comments-1.0.0_qapi_post:
      required:
        - acatCode
        - aptyCode
      type: object
      properties:
        id:
          type: string
        transNo:
          type: string
        effectiveDate:
          type: string
        acatCode:
          type: string
        aptyCode:
          type: string
        posn:
          type: string
        suffix:
          type: string
        proxyForUserId:
          type: string
    electronic-personnel-action-other-information-and-comments-1.0.0_get_request:
      type: object
      properties:
        proxyForUserId:
          title: Proxy For
          maxLength: 30
          type: string
          description: "Lineage reference object : proxyForUserId"
          x-lineageReferenceObject: proxyForUserId
        acatCode:
          title: Approval Category
          maxLength: 6
          type: string
          description: "Lineage reference object : acatCode"
          x-lineageReferenceObject: acatCode
        aptyCode:
          title: Approval Type
          maxLength: 6
          type: string
          description: "Lineage reference object : aptyCode, Lookup lineage reference
            object : ntracat,ntvapty"
          x-lineageReferenceObject: aptyCode
          x-lineageLookupReferenceObject: ntracat,ntvapty
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        transNo:
          title: Transaction
          maxLength: 15
          type: number
          description: "Lineage reference object : transNo"
          x-lineageReferenceObject: transNo
        suffix:
          title: Suffix
          maxLength: 2
          type: string
          description: "Lineage reference object : suffix"
          x-lineageReferenceObject: suffix
        effectiveDate:
          title: Query Date
          maxLength: 11
          type: string
          description: "Lineage reference object : effectiveDate"
          format: date-time
          x-lineageReferenceObject: effectiveDate
        posn:
          title: Position
          maxLength: 6
          type: string
          description: "Lineage reference object : posn"
          x-lineageReferenceObject: posn
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
