openapi: 3.0.0
info:
  title: cost-type-code-maintenance
  description: API for FTMCTYP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FTMCTYP
  x-source-domain: Finance
  x-source-title: Cost Type Code Maintenance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/cost-type-code-maintenance:
    get:
      tags:
        - cost-type-code-maintenance
      summary: Return resources from FTMCTYP
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: code
          in: query
          description: Cost Type Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVCTYP_CODE
        - name: shortDesc
          in: query
          description: Short Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        - name: longDesc
          in: query
          description: Long Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - cost-type-code-maintenance
      summary: Updates an existing resource in FTMCTYP
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_put_request"
            example:
              criteria.ftvctypCode: B1
              shortDesc: Bill Test
              longDesc: Bill Test 2
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - cost-type-code-maintenance
      summary: Creates a new resource in FTMCTYP
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_post_request"
            example:
              code: AA
              longDesc: test
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/cost-type-code-maintenance:
    post:
      tags:
        - cost-type-code-maintenance QAPI (Query by POST)
      summary: Return resources from FTMCTYP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cost-type-code-maintenance-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    cost-type-code-maintenance-1.0.0_get_response:
      required:
        - code
        - longDesc
      type: object
      properties:
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      x-lineageReferenceObject: ftvctyp
    cost-type-code-maintenance-1.0.0_qapi_post:
      type: object
      properties:
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    cost-type-code-maintenance-1.0.0_get_request:
      required:
        - code
        - longDesc
      type: object
      properties:
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      x-lineageReferenceObject: FTVCTYP
    cost-type-code-maintenance-1.0.0_post_request:
      required:
        - code
        - longDesc
      type: object
      properties:
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      x-lineageReferenceObject: FTVCTYP
    cost-type-code-maintenance-1.0.0_put_response:
      required:
        - code
        - longDesc
      type: object
      properties:
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      x-lineageReferenceObject: ftvctyp
    cost-type-code-maintenance-1.0.0_post_response:
      required:
        - code
        - longDesc
      type: object
      properties:
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      x-lineageReferenceObject: ftvctyp
    cost-type-code-maintenance-1.0.0_put_request:
      required:
        - criteria.ftvctypCode
        - criteria.ftvctypLongDesc
        - code
        - longDesc
      type: object
      properties:
        criteria.ftvctypShortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        criteria.ftvctypCode:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        code:
          title: Cost Type Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVCTYP_CODE"
          x-lineageReferenceObject: FTVCTYP_CODE
        criteria.ftvctypLongDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
        shortDesc:
          title: Short Description
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVCTYP_SHORT_DESC"
          x-lineageReferenceObject: FTVCTYP_SHORT_DESC
        longDesc:
          title: Long Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVCTYP_LONG_DESC"
          x-lineageReferenceObject: FTVCTYP_LONG_DESC
      x-lineageReferenceObject: FTVCTYP
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
