openapi: 3.0.0
info:
  title: check-number-validation
  description: API for FTICHKS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FTICHKS
  x-source-domain: Finance
  x-source-title: Check Number Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/check-number-validation:
    get:
      tags:
        - check-number-validation
      summary: Return resources from FTICHKS
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: checkNum
          in: query
          description: |-
            Check  
            Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FABCHKS_CHECK_NUM
        - name: bankCode
          in: query
          description: |-
            Bank
            Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FABCHKS_BANK_CODE
        - name: cancelInd
          in: query
          description: |-
            Cancel
            Indicator
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FABCHKS_CANCEL_IND
        - name: checkDate
          in: query
          description: |-
            Check
            Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FABCHKS_CHECK_DATE
        - name: checkAmt
          in: query
          description: |-
            Check
            Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FABCHKS_CHECK_AMT
        - name: checkTypeInd
          in: query
          description: |-
            Check
            Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FABCHKS_CHECK_TYPE_IND
        - name: payType
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/check-number-validation-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/check-number-validation:
    post:
      tags:
        - check-number-validation QAPI (Query by POST)
      summary: Return resources from FTICHKS
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/check-number-validation-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/check-number-validation-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    check-number-validation-1.0.0_get_request:
      type: object
      properties:
        bankCode:
          title: |-
            Bank
            Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FABCHKS_BANK_CODE, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: FABCHKS_BANK_CODE
          x-lineageLookupReferenceObject: gxvbank
        cancelInd:
          title: |-
            Cancel
            Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : FABCHKS_CANCEL_IND"
          x-lineageReferenceObject: FABCHKS_CANCEL_IND
        payType:
          title: |-
            Pay
            Type
          maxLength: 30
          type: string
          description: "Lineage reference object : FABCHKS_PAY_TYPE"
          x-lineageReferenceObject: FABCHKS_PAY_TYPE
        checkNum:
          title: |-
            Check  
            Number
          maxLength: 8
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_NUM"
          x-lineageReferenceObject: FABCHKS_CHECK_NUM
        checkTypeInd:
          title: |-
            Check
            Type
          maxLength: 1
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_TYPE_IND"
          x-lineageReferenceObject: FABCHKS_CHECK_TYPE_IND
        checkAmt:
          title: |-
            Check
            Amount
          maxLength: 25
          type: number
          description: "Lineage reference object : FABCHKS_CHECK_AMT"
          x-lineageReferenceObject: FABCHKS_CHECK_AMT
        checkDate:
          title: |-
            Check
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_DATE"
          format: date-time
          x-lineageReferenceObject: FABCHKS_CHECK_DATE
      x-lineageReferenceObject: FABCHKS
    check-number-validation-1.0.0_get_response:
      type: object
      properties:
        bankCode:
          title: |-
            Bank
            Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FABCHKS_BANK_CODE, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: FABCHKS_BANK_CODE
          x-lineageLookupReferenceObject: gxvbank
        payeeName:
          title: Payee Name
          maxLength: 230
          type: string
        cancelInd:
          title: |-
            Cancel
            Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : FABCHKS_CANCEL_IND"
          x-lineageReferenceObject: FABCHKS_CANCEL_IND
        checkNum:
          title: |-
            Check  
            Number
          maxLength: 8
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_NUM"
          x-lineageReferenceObject: FABCHKS_CHECK_NUM
        checkTypeInd:
          title: |-
            Check
            Type
          maxLength: 1
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_TYPE_IND"
          x-lineageReferenceObject: FABCHKS_CHECK_TYPE_IND
        checkAmt:
          title: |-
            Check
            Amount
          maxLength: 25
          type: number
          description: "Lineage reference object : FABCHKS_CHECK_AMT"
          x-lineageReferenceObject: FABCHKS_CHECK_AMT
        checkDate:
          title: |-
            Check
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_DATE"
          format: date-time
          x-lineageReferenceObject: FABCHKS_CHECK_DATE
      x-lineageReferenceObject: fabchks
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    check-number-validation-1.0.0_qapi_post:
      type: object
      properties:
        checkNum:
          title: |-
            Check  
            Number
          maxLength: 8
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_NUM"
          x-lineageReferenceObject: FABCHKS_CHECK_NUM
        bankCode:
          title: |-
            Bank
            Code
          maxLength: 2
          type: string
          description: "Lineage reference object : FABCHKS_BANK_CODE, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: FABCHKS_BANK_CODE
          x-lineageLookupReferenceObject: gxvbank
        cancelInd:
          title: |-
            Cancel
            Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : FABCHKS_CANCEL_IND"
          x-lineageReferenceObject: FABCHKS_CANCEL_IND
        checkDate:
          title: |-
            Check
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_DATE"
          format: date-time
          x-lineageReferenceObject: FABCHKS_CHECK_DATE
        checkAmt:
          title: |-
            Check
            Amount
          maxLength: 25
          type: number
          description: "Lineage reference object : FABCHKS_CHECK_AMT"
          x-lineageReferenceObject: FABCHKS_CHECK_AMT
        checkTypeInd:
          title: |-
            Check
            Type
          maxLength: 1
          type: string
          description: "Lineage reference object : FABCHKS_CHECK_TYPE_IND"
          x-lineageReferenceObject: FABCHKS_CHECK_TYPE_IND
        payType:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
