openapi: 3.0.0
info:
  title: course-syllabus
  description: API for SCASYLB administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SCASYLB
  x-source-domain: Student
  x-source-title: Course Syllabus
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/course-syllabus:
    get:
      tags:
        - course-syllabus
      summary: Return resources from SCASYLB
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: subjCode
          in: query
          required: false
          schema:
            type: string
        - name: crseNumb
          in: query
          required: false
          schema:
            type: string
        - name: termCodeEff
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/course-syllabus-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - course-syllabus
      summary: Updates an existing resource in SCASYLB
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/course-syllabus-1.0.0_put_request"
            example:
              crseNumb: 1102
              technicalRequirement: Describe technical requirements
              termCodeEff: 200120
              subjCode: ACCT
              learningObjectives: Describe learning objectives
              longCourseTitle: Long Course Title
              courseUrl: www.ellucian.com
              requiredMaterials: Describe required materials
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/course-syllabus-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/course-syllabus:
    post:
      tags:
        - course-syllabus QAPI (Query by POST)
      summary: Return resources from SCASYLB
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/course-syllabus-1.0.0_get_request"
            example:
              crseNumb: 1102
              termCodeEff: 200120
              subjCode: ACCT
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/course-syllabus-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    course-syllabus-1.0.0_get_response:
      type: object
      properties:
        scrsylo:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYLO_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYLO_ACTIVITY_DATE
              learningObjectives:
                maxLength: 32767
                description: "Lineage reference object : SCRSYLO_LEARNING_OBJECTIVES"
                x-lineageReferenceObject: SCRSYLO_LEARNING_OBJECTIVES
              endcopy:
                maxLength: 1
                type: string
            x-lineageReferenceObject: scrsylo
        scrsyln:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYLN_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYLN_ACTIVITY_DATE
              longCourseTitle:
                title: Title
                maxLength: 100
                type: string
                description: "Lineage reference object : SCRSYLN_LONG_COURSE_TITLE"
                x-lineageReferenceObject: SCRSYLN_LONG_COURSE_TITLE
              courseUrl:
                title: URL
                maxLength: 100
                type: string
                description: "Lineage reference object : SCRSYLN_COURSE_URL"
                x-lineageReferenceObject: SCRSYLN_COURSE_URL
              endcopy:
                maxLength: 1
                type: string
            x-lineageReferenceObject: scrsyln
        scrsyrm:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYRM_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYRM_ACTIVITY_DATE
              endcopy:
                maxLength: 1
                type: string
              requiredMaterials:
                maxLength: 32767
                description: "Lineage reference object : SCRSYRM_REQUIRED_MATERIALS"
                x-lineageReferenceObject: SCRSYRM_REQUIRED_MATERIALS
            x-lineageReferenceObject: scrsyrm
        scrsytr:
          type: array
          items:
            type: object
            properties:
              technicalRequirement:
                maxLength: 32767
                description: "Lineage reference object : SCRSYTR_TECHNICAL_REQUIREMENT"
                x-lineageReferenceObject: SCRSYTR_TECHNICAL_REQUIREMENT
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYTR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYTR_ACTIVITY_DATE
              endcopy:
                maxLength: 1
                type: string
            x-lineageReferenceObject: scrsytr
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    course-syllabus-1.0.0_put_request:
      type: object
      properties:
        crseNumb:
          title: Course
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseCrseNumb, Lookup lineage
            reference object : scbcrse,scbcrky"
          x-lineageReferenceObject: scacrseCrseNumb
          x-lineageLookupReferenceObject: scbcrse,scbcrky
        technicalRequirement:
          maxLength: 32767
          description: "Lineage reference object : SCRSYTR_TECHNICAL_REQUIREMENT"
          x-lineageReferenceObject: SCRSYTR_TECHNICAL_REQUIREMENT
        termCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseTermCodeEff, Lookup lineage
            reference object : stvterm,scbcrky,scbcrky"
          x-lineageReferenceObject: scacrseTermCodeEff
          x-lineageLookupReferenceObject: stvterm,scbcrky,scbcrky
        subjCode:
          title: Subject
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseSubjCode, Lookup lineage
            reference object : stvsubj"
          x-lineageReferenceObject: scacrseSubjCode
          x-lineageLookupReferenceObject: stvsubj
        learningObjectives:
          maxLength: 32767
          description: "Lineage reference object : SCRSYLO_LEARNING_OBJECTIVES"
          x-lineageReferenceObject: SCRSYLO_LEARNING_OBJECTIVES
        longCourseTitle:
          title: Title
          maxLength: 100
          type: string
          description: "Lineage reference object : SCRSYLN_LONG_COURSE_TITLE"
          x-lineageReferenceObject: SCRSYLN_LONG_COURSE_TITLE
        courseUrl:
          title: URL
          maxLength: 100
          type: string
          description: "Lineage reference object : SCRSYLN_COURSE_URL"
          x-lineageReferenceObject: SCRSYLN_COURSE_URL
        requiredMaterials:
          maxLength: 32767
          description: "Lineage reference object : SCRSYRM_REQUIRED_MATERIALS"
          x-lineageReferenceObject: SCRSYRM_REQUIRED_MATERIALS
      x-lineageReferenceObject: SCRSYTR
    course-syllabus-1.0.0_put_response:
      type: object
      properties:
        scrsylo:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYLO_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYLO_ACTIVITY_DATE
              learningObjectives:
                maxLength: 32767
                description: "Lineage reference object : SCRSYLO_LEARNING_OBJECTIVES"
                x-lineageReferenceObject: SCRSYLO_LEARNING_OBJECTIVES
              endcopy:
                maxLength: 1
                type: string
            x-lineageReferenceObject: scrsylo
        scrsyln:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYLN_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYLN_ACTIVITY_DATE
              longCourseTitle:
                title: Title
                maxLength: 100
                type: string
                description: "Lineage reference object : SCRSYLN_LONG_COURSE_TITLE"
                x-lineageReferenceObject: SCRSYLN_LONG_COURSE_TITLE
              courseUrl:
                title: URL
                maxLength: 100
                type: string
                description: "Lineage reference object : SCRSYLN_COURSE_URL"
                x-lineageReferenceObject: SCRSYLN_COURSE_URL
              endcopy:
                maxLength: 1
                type: string
            x-lineageReferenceObject: scrsyln
        scrsyrm:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYRM_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYRM_ACTIVITY_DATE
              endcopy:
                maxLength: 1
                type: string
              requiredMaterials:
                maxLength: 32767
                description: "Lineage reference object : SCRSYRM_REQUIRED_MATERIALS"
                x-lineageReferenceObject: SCRSYRM_REQUIRED_MATERIALS
            x-lineageReferenceObject: scrsyrm
        scrsytr:
          type: array
          items:
            type: object
            properties:
              technicalRequirement:
                maxLength: 32767
                description: "Lineage reference object : SCRSYTR_TECHNICAL_REQUIREMENT"
                x-lineageReferenceObject: SCRSYTR_TECHNICAL_REQUIREMENT
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SCRSYTR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SCRSYTR_ACTIVITY_DATE
              endcopy:
                maxLength: 1
                type: string
            x-lineageReferenceObject: scrsytr
    course-syllabus-1.0.0_qapi_post:
      type: object
      properties:
        subjCode:
          type: string
        crseNumb:
          type: string
        termCodeEff:
          type: string
    course-syllabus-1.0.0_get_request:
      type: object
      properties:
        crseNumb:
          title: Course
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseCrseNumb, Lookup lineage
            reference object : scbcrse,scbcrky"
          x-lineageReferenceObject: scacrseCrseNumb
          x-lineageLookupReferenceObject: scbcrse,scbcrky
        termCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseTermCodeEff, Lookup lineage
            reference object : stvterm,scbcrky,scbcrky"
          x-lineageReferenceObject: scacrseTermCodeEff
          x-lineageLookupReferenceObject: stvterm,scbcrky,scbcrky
        subjCode:
          title: Subject
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseSubjCode, Lookup lineage
            reference object : stvsubj"
          x-lineageReferenceObject: scacrseSubjCode
          x-lineageLookupReferenceObject: stvsubj
      x-lineageReferenceObject: SCACRSE_KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
