openapi: 3.0.0
info:
  title: Custom Table Configurations
  description: The configurations of the custom-table-configurations table
    definition which resides in the GORCSTT Banner configuration table.
  version: 1.1.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/custom-table-configurations:
    get:
      summary: Return all resources
      description: Returns a paged listing of all the resources in the system.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_CUSTOM_TABLE_CONFIG
      tags:
        - custom-table-configurations
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/custom-table-configurations.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.1.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource
      description: Create a new resource
      security:
        - EthosIntegrationBearer: []
      tags:
        - custom-table-configurations
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/custom-table-configurations.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              type: object
              $ref: "#/components/schemas/custom-table-configurations.json"
  /api/custom-table-configurations/{id}:
    get:
      summary: Return the requested resource
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      tags:
        - custom-table-configurations
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Custom Table Configurations for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/custom-table-configurations.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    delete:
      summary: Removes the requested resource
      tags:
        - custom-table-configurations
      description: >
        Deletes the existing custom table configuration record from GORCSTT
        table with the passed in identifier.
      security:
        - EthosIntegrationBearer: []
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    custom-table-configurations.json:
      title: Custom Table Configurations
      description: The API returns the list of the custom table configurations in
        GORRSDE table.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the custom-table-configurations.
          type: string
          format: guid
          pattern: ^a-f0-9]8(?:-a-f0-9]4)3-a-f0-9]12$
        customTableName:
          title: Custom Table Name
          description: The name of the custom-table-configurations table to hold the
            custom-table-configurations data.
          type: string
        customTableDescription:
          title: Custom Table Description
          description: The description of the custom-table-configurations table to hold
            the custom-table-configurations data.
          type: string
        customTableSecurityObject:
          title: Custom Table Security Object
          description: The security object for the custom-table-configurations table API
          type: string
        customTableAPIName:
          title: Custom Table API Name
          description: The name of the API that would be generated for the
            custom-table-configurations table to hold the
            custom-table-configurations data.
          type: string
        customTableAPISpec:
          title: Custom Table API Specification
          description: The api-specifications configuration details for the
            specification-driven custom-table-configurations table API.
          type: string
          format: guid
          pattern: ^a-f0-9]8(?:-a-f0-9]4)3-a-f0-9]12$
        customTableColumns:
          title: Custom Table Columns
          description: The custom-table-configurations column details for configuration.
          type: array
          items:
            type: object
            properties:
              columnName:
                title: Custom Table Column Name
                description: The name of the custom column.
                type: string
              attributeKeyColumn:
                title: Attribute Key Column
                description: The column to be considered as key column.
                type: string
                enum:
                  - true
                  - false
              attributeDataType:
                title: Attribute Data Type
                description: The data type of the custom column.
                type: string
                enum:
                  - varchar2
                  - date
                  - numeric
              attributeDataLength:
                title: Attribute Data Length
                description: The data length of the custom column.
                type: string
              attributeDataScale:
                title: Attribute Data Scale
                description: The data scale of the custom column.
                type: string
              rangeLow:
                title: Range Low
                description: The lowest range for the column value
                type: string
              rangeHigh:
                title: Range High
                description: The highest range for the column value
                type: string
              attributeDisplay:
                title: Attribute Display
                description: An indicator if the custom column is to be displayed or not.
                type: string
                enum:
                  - true
                  - false
              attributeRequired:
                title: Attribute Required
                description: An indicator if the custom column is required column or not.
                type: string
                enum:
                  - true
                  - false
              attributePrompt:
                title: Attribute Prompt
                description: The prompt name of the custom column when displayed.
                type: string
              validationAPIName:
                title: Validation API Name
                description: The validation table's API for the custom column
                type: string
              validationTable:
                title: Validation Table
                description: The custom-table-configurations table for which the custom data is
                  to be validated.
                type: string
              validationColumn:
                title: Validation Column
                description: The custom-table-configurations table's column for which the custom
                  data is to be validated.
            additionalProperties: false
            required:
              - columnName
              - attributeKeyColumn
              - attributeDataType
              - attributeDisplay
              - attributePrompt
        MEPIndicator:
          title: MEP Indicator
          description: An indicator if the custom-table-configurations table is to be MEP
            enabled
          type: string
          enum:
            - Y
            - N
      required:
        - id
        - customTableName
        - customTableDescription
        - customTableColumns
      additionalProperties: false
