openapi: 3.0.0
info:
  title: area-requirements-general-requirements
  description: API for SMAAREA administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SMAAREA
  x-source-domain: Student
  x-source-title: Area Requirements
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/area-requirements-general-requirements:
    get:
      tags:
        - area-requirements-general-requirements
      summary: Return resources from SMAAREA
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: area
          in: query
          required: false
          schema:
            type: string
        - name: keyblckTermCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/area-requirements-general-requirements-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/area-requirements-general-requirements:
    post:
      tags:
        - area-requirements-general-requirements QAPI (Query by POST)
      summary: Return resources from SMAAREA
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/area-requirements-general-requirements-1.0.0_get_re\
                quest"
            example:
              area: AREAAP1
              keyblckTermCode: 202100
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/area-requirements-general-requirements-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    area-requirements-general-requirements-1.0.0_get_response:
      type: object
      properties:
        smbagen:
          type: array
          items:
            required:
              - activeInd
              - attrReuseInd
              - connectorInst
              - connectorINontrad
              - connectorITrad
              - connectorOverall
              - connectorTransfer
              - crseReuseInd
              - gcInd
            type: object
            properties:
              reqCreditsITrad:
                title: Required Institutional Traditional
                maxLength: 12
                type: number
                description: "Lineage reference object : SMBAGEN_REQ_CREDITS_I_TRAD"
                x-lineageReferenceObject: SMBAGEN_REQ_CREDITS_I_TRAD
              reqCreditsOverall:
                title: Total Required
                maxLength: 12
                type: number
                description: "Lineage reference object : SMBAGEN_REQ_CREDITS_OVERALL"
                x-lineageReferenceObject: SMBAGEN_REQ_CREDITS_OVERALL
              complCredits:
                title: Compliance
                maxLength: 12
                type: number
                description: "Lineage reference object : SMBAGEN_COMPL_CREDITS"
                x-lineageReferenceObject: SMBAGEN_COMPL_CREDITS
              crseReuseInd:
                title: Default Course Reuse
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_CRSE_REUSE_IND"
                x-lineageReferenceObject: SMBAGEN_CRSE_REUSE_IND
              withinInd:
                title: Default Within Indicator
                maxLength: 2
                type: string
                description: "Lineage reference object : SMBAGEN_WITHIN_IND"
                x-lineageReferenceObject: SMBAGEN_WITHIN_IND
              maxCreditsINontrad:
                title: Maximum Institutional Non-Traditional
                maxLength: 12
                type: number
                description: "Lineage reference object : SMBAGEN_MAX_CREDITS_I_NONTRAD"
                x-lineageReferenceObject: SMBAGEN_MAX_CREDITS_I_NONTRAD
              maxCreditsTransfer:
                title: Maximum Transfer
                maxLength: 12
                type: number
                description: "Lineage reference object : SMBAGEN_MAX_CREDITS_TRANSFER"
                x-lineageReferenceObject: SMBAGEN_MAX_CREDITS_TRANSFER
              minAreaGpa:
                title: Minimum Area GPA
                maxLength: 29
                type: number
                description: "Lineage reference object : SMBAGEN_MIN_AREA_GPA"
                x-lineageReferenceObject: SMBAGEN_MIN_AREA_GPA
              connectorInst:
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_CONNECTOR_INST"
                x-lineageReferenceObject: SMBAGEN_CONNECTOR_INST
              attrReuseInd:
                title: Default Attribute Reuse
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_ATTR_REUSE_IND"
                x-lineageReferenceObject: SMBAGEN_ATTR_REUSE_IND
              connectorOverall:
                title: Connector
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_CONNECTOR_OVERALL"
                x-lineageReferenceObject: SMBAGEN_CONNECTOR_OVERALL
              activeInd:
                title: Active / Inactive
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_ACTIVE_IND"
                x-lineageReferenceObject: SMBAGEN_ACTIVE_IND
              connectorTransfer:
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_CONNECTOR_TRANSFER"
                x-lineageReferenceObject: SMBAGEN_CONNECTOR_TRANSFER
              connectorINontrad:
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_CONNECTOR_I_NONTRAD"
                x-lineageReferenceObject: SMBAGEN_CONNECTOR_I_NONTRAD
              complCourses:
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_COMPL_COURSES"
                x-lineageReferenceObject: SMBAGEN_COMPL_COURSES
              areaPriority:
                title: Default Priority
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_AREA_PRIORITY"
                x-lineageReferenceObject: SMBAGEN_AREA_PRIORITY
              maxCoursesTransfer:
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_MAX_COURSES_TRANSFER"
                x-lineageReferenceObject: SMBAGEN_MAX_COURSES_TRANSFER
              connectorITrad:
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_CONNECTOR_I_TRAD"
                x-lineageReferenceObject: SMBAGEN_CONNECTOR_I_TRAD
              yearRule:
                title: Default Year Limit
                maxLength: 2
                type: number
                description: "Lineage reference object : SMBAGEN_YEAR_RULE"
                x-lineageReferenceObject: SMBAGEN_YEAR_RULE
              reqCoursesOverall:
                title: Courses
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_REQ_COURSES_OVERALL"
                x-lineageReferenceObject: SMBAGEN_REQ_COURSES_OVERALL
              maxCoursesINontrad:
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_MAX_COURSES_I_NONTRAD"
                x-lineageReferenceObject: SMBAGEN_MAX_COURSES_I_NONTRAD
              reqCoursesITrad:
                title: Courses
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_REQ_COURSES_I_TRAD"
                x-lineageReferenceObject: SMBAGEN_REQ_COURSES_I_TRAD
              reqCreditsInst:
                title: Required Institutional
                maxLength: 12
                type: number
                description: "Lineage reference object : SMBAGEN_REQ_CREDITS_INST"
                x-lineageReferenceObject: SMBAGEN_REQ_CREDITS_INST
              gcInd:
                title: Attached
                maxLength: 1
                type: string
                description: "Lineage reference object : SMBAGEN_GC_IND"
                x-lineageReferenceObject: SMBAGEN_GC_IND
              reqCoursesInst:
                title: Credits
                maxLength: 3
                type: number
                description: "Lineage reference object : SMBAGEN_REQ_COURSES_INST"
                x-lineageReferenceObject: SMBAGEN_REQ_COURSES_INST
              grdeCodeMin:
                title: Minimum Course Grade
                maxLength: 6
                type: string
                description: "Lineage reference object : SMBAGEN_GRDE_CODE_MIN"
                x-lineageReferenceObject: SMBAGEN_GRDE_CODE_MIN
            x-lineageReferenceObject: smbagen
        smbagen_ctrl_block:
          type: array
          items:
            type: object
            properties:
              smbagenTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : SMBAGEN_TERM_CODE_TO"
                x-lineageReferenceObject: SMBAGEN_TERM_CODE_TO
              smbagenTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : SMBAGEN_TERM_CODE_FROM"
                x-lineageReferenceObject: SMBAGEN_TERM_CODE_FROM
            x-lineageReferenceObject: smbagen_ctrl_block
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    area-requirements-general-requirements-1.0.0_qapi_post:
      type: object
      properties:
        area:
          type: string
        keyblckTermCode:
          type: string
    area-requirements-general-requirements-1.0.0_get_request:
      type: object
      properties:
        area:
          title: Area
          maxLength: 30
          type: string
          description: "Lineage reference object : AREA, Lookup lineage reference object :
            smbagen,smralib"
          x-lineageReferenceObject: AREA
          x-lineageLookupReferenceObject: smbagen,smralib
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : KEYBLCK_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: KEYBLCK_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
