openapi: 3.0.0
info:
  title: Person Holds
  description: >
    Persons holds API processes the holds that are defined for an individual
    person.
  version: 6.1.0
  x-source-system: banner
  x-api-type: ethos
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: person-holds
paths:
  /api/person-holds:
    get:
      summary: Returns resources from SPRHOLD
      description: >
        Returns a paged listing of all the person hold records from SPRHOLD
        table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_HOLDS
      tags:
        - person-holds
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v6.1.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: |
            ### Person  
            Returns all person holds for the person ID passed.
            ```
            /api/person-holds?person=6729a17e-3dfa-4517-95df-acdf160c24ab
            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-person-holds.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.1.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource in SPRHOLD
      description: >
        POST requests must include a nil GUID value
        ("00000000-0000-0000-0000-000000000000") for the root id property.


        Creates a new person hold record in SPRHOLD table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_HOLDS
      tags:
        - person-holds
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6.1.0+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-holds.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-person-holds.json"
  /api/person-holds/{id}:
    get:
      summary: Return the requested resource from SPRHOLD
      description: |
        Returns a single person hold record with the requested identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_HOLDS
      tags:
        - person-holds
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6.1.0+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-holds.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource from SPRHOLD
      description: >
        Updates the existing person hold record from SPRHOLD table with the
        passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_HOLDS
      tags:
        - person-holds
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Person Holds for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6.1.0+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-holds.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-person-holds.json"
    delete:
      summary: Removes a resource from SPRHOLD
      description: >
        Deletes the existing person hold record  from SPRHOLD table with the
        passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_HOLDS
      tags:
        - person-holds
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Person Holds for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-person-holds.json:
      title: Person Holds
      description: A customized list of holds that may be applied to a person.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the person hold.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GORGUID_GUID(LDM_NAME= person-holds) 
          x-lineageDerivedLogic: A record from GORGUID where GORGUID_LDM_NAME = 'person-holds' is displayed
        person:
          title: Person
          description: The person for whom the hold has been recorded.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Person.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: persons 
              x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = persons) 
              x-lineageDerivedLogic: All records from GORGUID where GORGUID_LDM_NAME = 'persons'  and GORGUID_DOMAIN_KEY = SPRHOLD_PIDM are displayed
          additionalProperties: false
          required:
            - id
        type:
          title: Type
          description: The type of the hold.
          type: object
          properties:
            category:
              title: Category
              description: A global category for person hold.
              enum:
                - academic
                - administrative
                - disciplinary
                - financial
                - health
              type: string
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: For SPRHOLD_HLDD_CODE = STVHLD_CODE,Display 'academic' if STVHLDD_REG_HOLD_IND is Y and/or STVHLDD_TRANS_HOLD_IND is Y and/or STVHLDD_GRAD_HOLD_IND is Y and/or STVHLDD_GRADE_HOLD_IND is  Y and/or STVHLDD_ENV_HOLD_IND is  Y and/or STVHLDD_APPLICATION_HOLD_IND is Y and/or STVHLDD_COMPLIANCE_HOLD_IND is Y. Display  'financial' if STVHLDD_AR_HOLD_IND is Y . Only 'academic' and 'financial' categories are supported.
            detail:
              title: Detail
              description: A custom category for the person hold.
              oneOf:
                - type: object
                  properties:
                    id:
                      title: ID
                      description: The global identifier for the Detail.
                      type: string
                      format: guid
                      pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                      x-lineageLookupReferenceObject: person-hold-types 
                      x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = restriction-types) 
                      x-lineageDerivedLogic: All records from GORGUID where GORGUID_LDM_NAME = 'restriction-types'  and GORGUID_DOMAIN_KEY = SPRHOLD_HLDD_CODE are displayed
                  additionalProperties: false
                  required:
                    - id
                - type: object
                  maxProperties: 0
          additionalProperties: false
          minProperties: 1
          required:
            - category
        notificationIndicator:
          title: Notification Indicator
          description: Indicates if the person should be notified of the hold being placed.
          oneOf:
            - type: string
              enum:
                - notify
                - watch
              x-lineageReferenceObject: SPRHOLEA_NOTIFICATION_IND(SPRHOLEA)
            - type: string
              maxLength: 0
        startOn:
          title: Start On
          description: The date when the hold goes into effect.
          type: string
          format: date-time
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          x-lineageReferenceObject: SPRHOLD_FROM_DATE(SPRHOLD)
        endOn:
          title: End On
          description: The date when the hold ends.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
              x-lineageReferenceObject: SPRHOLD_TO_DATE(SPRHOLD)
            - type: string
              maxLength: 0
        comment:
          title: Comment
          description: A comment for the hold.
          type: string
          x-lineageReferenceObject: SPRHOLEA_HOLD_COMMENT(SPRHOLEA)
        reason:
          title: Reason
          description: A brief reason for the person hold.
          type: string
          x-lineageReferenceObject: SPRHOLD_REASON(SPRHOLD)
      required:
        - id
        - person
        - type
        - startOn
      additionalProperties: false
