openapi: 3.0.0
info:
  title: ca-report-engine-extract-column-definition
  description: API for GVAMAPD administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: GVAMAPD
  x-source-domain: Foundation
  x-source-title: Report Engine Extract Column Definition Form (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-report-engine-extract-column-definition:
    get:
      tags:
        - ca-report-engine-extract-column-definition
      summary: Return resources from GVAMAPD
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyReport
          in: query
          required: false
          schema:
            type: string
        - name: column
          in: query
          description: Column
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GVBMAPD_COLUMN
        - name: concept
          in: query
          description: Concept
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        - name: typeInd
          in: query
          description: Column Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_ge\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - ca-report-engine-extract-column-definition
      summary: Updates an existing resource in GVAMAPD
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_pu\
                t_request"
            example:
              typeInd: U
              keyReport: CB
              criteria.column: A.SCBCRSE_CREDIT_HR_MID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_pu\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - ca-report-engine-extract-column-definition
      summary: Creates a new resource in GVAMAPD
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_po\
                st_request"
            example:
              typeInd: D
              keyReport: CB
              concept: CREDIT_HR_MID
              column: A.SCBCRSE_CREDIT_HR_MID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_po\
                    st_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-report-engine-extract-column-definition:
    post:
      tags:
        - ca-report-engine-extract-column-definition QAPI (Query by POST)
      summary: Return resources from GVAMAPD
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_ge\
                t_request"
            example:
              keyReport: CB
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-report-engine-extract-column-definition-1.0.0_ge\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    ca-report-engine-extract-column-definition-1.0.0_get_request:
      required:
        - column
        - concept
        - typeInd
      type: object
      properties:
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GVBMAPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
        keyReport:
          title: Report
          maxLength: 30
          type: string
          description: "Lineage reference object : keyReport, Lookup lineage reference
            object : gvvrpdf"
          x-lineageReferenceObject: keyReport
          x-lineageLookupReferenceObject: gvvrpdf
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
      x-lineageReferenceObject: GVBMAPD
    ca-report-engine-extract-column-definition-1.0.0_post_request:
      required:
        - column
        - concept
        - typeInd
      type: object
      properties:
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        keyReport:
          title: Report
          maxLength: 30
          type: string
          description: "Lineage reference object : keyReport, Lookup lineage reference
            object : gvvrpdf"
          x-lineageReferenceObject: keyReport
          x-lineageLookupReferenceObject: gvvrpdf
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
      x-lineageReferenceObject: GVBMAPD
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-report-engine-extract-column-definition-1.0.0_get_response:
      required:
        - column
        - concept
        - typeInd
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GVBMAPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
      x-lineageReferenceObject: gvbmapd
    ca-report-engine-extract-column-definition-1.0.0_put_response:
      required:
        - column
        - concept
        - typeInd
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GVBMAPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
      x-lineageReferenceObject: gvbmapd
    ca-report-engine-extract-column-definition-1.0.0_put_request:
      required:
        - criteria.column
        - criteria.concept
        - criteria.typeInd
        - column
        - concept
        - typeInd
      type: object
      properties:
        criteria.activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GVBMAPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        keyReport:
          title: Report
          maxLength: 30
          type: string
          description: "Lineage reference object : keyReport, Lookup lineage reference
            object : gvvrpdf"
          x-lineageReferenceObject: keyReport
          x-lineageLookupReferenceObject: gvvrpdf
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
        criteria.typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        criteria.concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        criteria.column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
      x-lineageReferenceObject: GVBMAPD
    ca-report-engine-extract-column-definition-1.0.0_post_response:
      required:
        - column
        - concept
        - typeInd
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GVBMAPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
      x-lineageReferenceObject: gvbmapd
    ca-report-engine-extract-column-definition-1.0.0_qapi_post:
      type: object
      properties:
        keyReport:
          type: string
        column:
          title: Column
          maxLength: 50
          type: string
          description: "Lineage reference object : GVBMAPD_COLUMN"
          x-lineageReferenceObject: GVBMAPD_COLUMN
        concept:
          title: Concept
          maxLength: 30
          type: string
          description: "Lineage reference object : GVBMAPD_CONCEPT"
          x-lineageReferenceObject: GVBMAPD_CONCEPT
        typeInd:
          title: Column Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GVBMAPD_TYPE_IND"
          x-lineageReferenceObject: GVBMAPD_TYPE_IND
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GVBMAPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GVBMAPD_ACTIVITY_DATE
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
