openapi: 3.0.0
info:
  title: general-person-identification-current-identification
  description: API for SPAIDEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SPAIDEN
  x-source-domain: Student
  x-source-title: General Person Identification
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/general-person-identification-current-identification:
    put:
      tags:
        - general-person-identification-current-identification
      summary: Updates an existing resource in SPAIDEN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-person-identification-current-identification-1.0.0_put_request"
            example:
              spridenNtypCode: BRTH
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-person-identification-current-identification-1.0.0_put_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
    post:
      tags:
        - general-person-identification-current-identification
      summary: Creates a new resource in SPAIDEN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-person-identification-current-identification-1.0.0_post_request"
            example:
              persLastName: LastName
              persFirstName: FirstName
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-person-identification-current-identification-1.0.0_post_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
  /qapi/general-person-identification-current-identification: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                description: 'The detailed actionable error message. '
              description:
                type: string
                description: The error description used to describe the error details.
    general-person-identification-current-identification-1.0.0_put_response:
      type: object
      properties:
        persPrefFname:
          title: Preferred First Name
          maxLength: 60
          type: string
        persPrefMname:
          title: Preferred Middle Name
          maxLength: 60
          type: string
        spridenActivityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SPRIDEN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRIDEN_ACTIVITY_DATE
        persPrefix:
          title: Prefix
          maxLength: 20
          type: string
        spridenCreateUser:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_CREATE_USER"
          x-lineageReferenceObject: SPRIDEN_CREATE_USER
        greenDataBar2:
          type: string
        persLastName:
          title: Last Name
          maxLength: 60
          type: string
        greenDataBar3:
          type: string
        persLegalName:
          title: Full Legal Name
          maxLength: 500
          type: string
        currentNtypDesc:
          type: string
        spridenOrigin:
          title: Origin
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_ORIGIN"
          x-lineageReferenceObject: SPRIDEN_ORIGIN
        greenDataBar1:
          type: string
        persMi:
          title: Middle Name
          maxLength: 60
          type: string
        persSuffix:
          title: Suffix
          maxLength: 20
          type: string
        spridenId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        persPrefLname:
          title: Preferred Last Name
          maxLength: 60
          type: string
        spridenUser:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_USER"
          x-lineageReferenceObject: SPRIDEN_USER
        nonPersName:
          title: Name
          maxLength: 60
          type: string
        spridenNtypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage\
            \ reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        persFirstName:
          title: First Name
          maxLength: 60
          type: string
        spridenCreateDate:
          title: Create Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SPRIDEN_CREATE_DATE"
          format: date-time
          x-lineageReferenceObject: SPRIDEN_CREATE_DATE
      x-lineageReferenceObject: spriden_current
    general-person-identification-current-identification-1.0.0_post_request:
      type: object
      properties:
        persPrefFname:
          title: Preferred First Name
          maxLength: 60
          type: string
        persPrefMname:
          title: Preferred Middle Name
          maxLength: 60
          type: string
        persPrefix:
          title: Prefix
          maxLength: 20
          type: string
        persLastName:
          title: Last Name
          maxLength: 60
          type: string
        persLegalName:
          title: Full Legal Name
          maxLength: 500
          type: string
        persMi:
          title: Middle Name
          maxLength: 60
          type: string
        persSuffix:
          title: Suffix
          maxLength: 20
          type: string
        persPrefLname:
          title: Preferred Last Name
          maxLength: 60
          type: string
        persSurnamePrefix:
          title: Last Name Prefix
          maxLength: 60
          type: string
        nonPersName:
          title: Name
          maxLength: 60
          type: string
        spridenNtypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage\
            \ reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        persFirstName:
          title: First Name
          maxLength: 60
          type: string
      x-lineageReferenceObject: SPRIDEN_CURRENT
    general-person-identification-current-identification-1.0.0_put_request:
      type: object
      properties:
        persPrefFname:
          title: Preferred First Name
          maxLength: 60
          type: string
        persPrefMname:
          title: Preferred Middle Name
          maxLength: 60
          type: string
        persPrefix:
          title: Prefix
          maxLength: 20
          type: string
        persLastName:
          title: Last Name
          maxLength: 60
          type: string
        persLegalName:
          title: Full Legal Name
          maxLength: 500
          type: string
        spridenId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        persMi:
          title: Middle Name
          maxLength: 60
          type: string
        persSuffix:
          title: Suffix
          maxLength: 20
          type: string
        persPrefLname:
          title: Preferred Last Name
          maxLength: 60
          type: string
        persSurnamePrefix:
          title: Last Name Prefix
          maxLength: 60
          type: string
        nonPersName:
          title: Name
          maxLength: 60
          type: string
        spridenNtypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage\
            \ reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        persFirstName:
          title: First Name
          maxLength: 60
          type: string
      x-lineageReferenceObject: SPRIDEN_CURRENT
    general-person-identification-current-identification-1.0.0_post_response:
      type: object
      properties:
        persPrefFname:
          title: Preferred First Name
          maxLength: 60
          type: string
        persPrefMname:
          title: Preferred Middle Name
          maxLength: 60
          type: string
        spridenActivityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SPRIDEN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRIDEN_ACTIVITY_DATE
        persPrefix:
          title: Prefix
          maxLength: 20
          type: string
        spridenCreateUser:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_CREATE_USER"
          x-lineageReferenceObject: SPRIDEN_CREATE_USER
        greenDataBar2:
          type: string
        persLastName:
          title: Last Name
          maxLength: 60
          type: string
        greenDataBar3:
          type: string
        persLegalName:
          title: Full Legal Name
          maxLength: 500
          type: string
        currentNtypDesc:
          type: string
        spridenOrigin:
          title: Origin
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_ORIGIN"
          x-lineageReferenceObject: SPRIDEN_ORIGIN
        greenDataBar1:
          type: string
        persMi:
          title: Middle Name
          maxLength: 60
          type: string
        persSuffix:
          title: Suffix
          maxLength: 20
          type: string
        spridenId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        persPrefLname:
          title: Preferred Last Name
          maxLength: 60
          type: string
        spridenUser:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_USER"
          x-lineageReferenceObject: SPRIDEN_USER
        nonPersName:
          title: Name
          maxLength: 60
          type: string
        spridenNtypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage\
            \ reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        persFirstName:
          title: First Name
          maxLength: 60
          type: string
        spridenCreateDate:
          title: Create Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SPRIDEN_CREATE_DATE"
          format: date-time
          x-lineageReferenceObject: SPRIDEN_CREATE_DATE
      x-lineageReferenceObject: spriden_current
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
