openapi: 3.0.0
info:
  title: data-privacy-retention-collection-maintenance
  description: API for GUARETC administrative page
  version: 0.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: GUARETC
  x-source-domain: Foundation
  x-source-title: Retention Collection Attributes
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/data-privacy-retention-collection-maintenance:
    get:
      tags:
        - data-privacy-retention-collection-maintenance
      summary: Return resources from GUARETC
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: collection
          in: query
          required: true
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRETC_STATUS
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-collection-maintenance-0.1.0\
                    _get_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/data-privacy-retention-collection-maintenance:
    post:
      tags:
        - data-privacy-retention-collection-maintenance QAPI (Query by POST)
      summary: Return resources from GUARETC
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-retention-collection-maintenance-0.1.0\
                _get_request"
            example:
              collection: EXAMPLE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-collection-maintenance-0.1.0\
                    _get_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    data-privacy-retention-collection-maintenance-0.1.0_get_response:
      type: object
      properties:
        gubretc:
          type: array
          items:
            required:
              - desc
              - expireDate
              - retrCode
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : GUBRETC_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: GUBRETC_ACTIVITY_DATE
              holdNumReqApprovers:
                type: number
              holdNumRecApprovers:
                type: number
              creatorId:
                title: Creator ID
                type: string
                description: "Lineage reference object : GUBRETC_CREATOR_ID"
                x-lineageReferenceObject: GUBRETC_CREATOR_ID
              expireDate:
                title: Expiration Date
                type: string
                description: "Lineage reference object : GUBRETC_EXPIRE_DATE"
                format: date-time
                x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
              retrCode:
                title: Retention Rule Code
                type: string
                description: "Lineage reference object : GUBRETC_RETR_CODE"
                x-lineageReferenceObject: GUBRETC_RETR_CODE
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : GUBRETC_USER_ID"
                x-lineageReferenceObject: GUBRETC_USER_ID
              desc:
                title: Description
                type: string
                description: "Lineage reference object : GUBRETC_DESC"
                x-lineageReferenceObject: GUBRETC_DESC
              status:
                title: Collection Status
                type: string
                description: "Lineage reference object : GUBRETC_STATUS"
                x-lineageReferenceObject: GUBRETC_STATUS
            x-lineageReferenceObject: gubretc
        gurretc:
          type: array
          items:
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : GURRETC_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: GURRETC_ACTIVITY_DATE
              name:
                title: Name
                type: string
              id:
                title: ID
                type: string
              userId:
                title: User ID
                maxLength: 30
                type: string
                description: "Lineage reference object : GURRETC_USER_ID"
                x-lineageReferenceObject: GURRETC_USER_ID
              status:
                title: Status
                type: string
                description: "Lineage reference object : GURRETC_STATUS"
                x-lineageReferenceObject: GURRETC_STATUS
            x-lineageReferenceObject: gurretc
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    data-privacy-retention-collection-maintenance-0.1.0_qapi_post:
      required:
        - collection
      type: object
      properties:
        collection:
          type: string
        id:
          title: ID
          type: string
        name:
          title: Name
          type: string
        status:
          title: Status
          type: string
          description: "Lineage reference object : GURRETC_STATUS"
          x-lineageReferenceObject: GURRETC_STATUS
    data-privacy-retention-collection-maintenance-0.1.0_get_request:
      required:
        - collection
      type: object
      properties:
        name:
          title: Name
          type: string
        collection:
          title: Retention Collection
          type: string
          description: "Lineage reference object : collection, Lookup lineage reference
            object : gubretc"
          x-lineageReferenceObject: collection
          x-lineageLookupReferenceObject: gubretc
        id:
          title: ID
          type: string
        status:
          title: Status
          type: string
          description: "Lineage reference object : GURRETC_STATUS"
          x-lineageReferenceObject: GURRETC_STATUS
      x-lineageReferenceObject: GURRETC
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
