openapi: 3.0.0
info:
  title: ca-import-mass-special-term-data
  description: API for Mass import special term data
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-source-domain: Student
  x-release-status: beta
  x-source-title: API for Mass import special term data
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: ca-import-mass-special-term-data
paths:
  /api/ca-import-mass-special-term-data:
    post:
      tags:
        - ca-import-mass-special-term-data
      summary: Store mass set of records for special term data
      description: Store mass set of records for special term data
      requestBody:
        description: Create a new set of records for special term data for the given tab.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ca-import-mass-special-term-data-request"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ca-import-mass-special-term-data-response"
        "405":
          description: Invalid input
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_IMPORT_MASS_SPE_TERM_DATA
components:
  schemas:
    ca-import-mass-special-term-data-request:
      type: object
      properties:
        stuTermCode:
          title: stuTermCode
          type: string
          description: Student term code parameter
        stuDicdCode:
          title: stuDicdCode
          type: string
          description: Student district code parameter
        fileCode:
          title: fileCode
          type: string
          description: Type of record
        speTerm:
          title: speTerm
          type: array
          items:
            type: object
            properties:
              BannerId:
                type: string
                description: Student Banner ID
              sistcCode:
                type: string
                description: Student Incarcerated Status Code
              justiceCode:
                type: string
                description: Student Youth Justice Status Code
              mesaCode:
                type: string
                description: MESA/ASEM Status Code
              pnteCode:
                type: string
                description: Puente Program Status Code
              mchsCode:
                type: string
                description: MCHS/ECHS Status Code
              sustCode:
                type: string
                description: Umoja Program Status Code
              caasCode:
                type: string
                description: Career Advancement Academy (CAA) Participant Code
              cafyesInd:
                type: string
                description: Cooperating Agencies Foster Youth Educational Support (CAFYES)
                  Participant Indicator
              ccapInd:
                type: string
                description: College and Career Access Pathways (CCAP) Participant Indicator
              wblnCode:
                type: string
                description: Student Work-based Learning Status Code
    ca-import-mass-special-term-data-response:
      type: array
      items:
        type: object
        properties:
          stuTermCode:
            type: string
            description: Student Term Code
          stuDicdCode:
            type: string
            description: Student District Code
          stuId:
            type: string
            description: Student Banner ID
          sistcCode:
            type: string
            description: Student Incarcerated Status Code
          justiceCode:
            type: string
            description: Student Youth Justice Status Code
          mesaCode:
            type: string
            description: MESA/ASEM Status Code
          pnteCode:
            type: string
            description: Puente Program Status Code
          mchsCode:
            type: string
            description: MCHS/ECHS Status Code
          sustCode:
            type: string
            description: Umoja Program Status Code
          caasCode:
            type: string
            description: Career Advancement Academy (CAA) Participant Code
          cafyesInd:
            type: string
            description: Cooperating Agencies Foster Youth Educational Support (CAFYES)
              Participant Indicator
          ccapInd:
            type: string
            description: College and Career Access Pathways (CCAP) Participant Indicator
          wblnCode:
            type: string
            description: Student Work-based Learning Status Code
          message:
            type: string
            description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
