openapi: 3.0.0
info:
  title: complementary-activities-submission
  description: |
    To post the student activity details to SOACASA page
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: complementary Activities Submission
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: complementary-activities-submission
paths:
  /api/complementary-activities-submission:
    post:
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_COMP_ACT_SUB
      tags:
        - complementary-activities-submission
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```
             application/json
            ```
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/complementary-activities-submission-response"
          headers:
            X-Media-Type:
              description: application/json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              type: object
              $ref: "#/components/schemas/complementary-activities-submission-request"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    complementary-activities-submission-request:
      type: array
      items:
        type: object
        properties:
          studentId:
            type: string
            example: A00019908
          id:
            type: string
            example: 00000000-0000-0000-0000-000000000000
          term:
            type: string
            example: 202108
          activity:
            type: string
            example: DA_MAA
          category:
            type: string
            example: CORP
          documentSubmitInd:
            type: string
            example: N
          program:
            type: string
            example: DA_PCDA
          submitDate:
            type: string
            format: date
            example: 2022-08-09
          submittedHours:
            type: integer
            example: 8
          studentComment:
            type: string
            example: Comment
          approvalComment:
            type: string
            example: approvalComment
          approvedCredits:
            type: string
            example: 4
          approvedHrs:
            type: string
            example: 6
          completionDate:
            type: string
            format: date
            example: 2022-08-09
          approvedDate:
            type: string
            format: date
            example: 2022-09-09
          desc:
            type: string
            example: description
      required:
        - studentId
        - term
        - id
        - program
        - submitDate
        - submittedHours
    complementary-activities-submission-response:
      type: object
      properties:
        studentId:
          type: string
          example: A00019908
        id:
          type: string
          example: d53bc6cc-0000-4460-0000-c4bdd2d8e4f7
        term:
          type: string
          example: 202108
        category:
          type: string
          example: CORP
        decesion:
          type: string
          example: UVE
        activity:
          type: string
          example: DA_MAA
        program:
          type: string
          example: DA_PCDA
        documentSubmitInd:
          type: string
          example: N
        submitDate:
          type: string
          format: date
          example: 2022-08-09
        submittedHours:
          type: integer
          example: 8
        studentComment:
          type: string
          example: Comment
