openapi: 3.0.0
info:
  title: section-syllabus-required-materials-and-technical-requirements
  description: API for SSASYLB administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SSASYLB
  x-source-domain: Student
  x-source-title: Section Syllabus
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/section-syllabus-required-materials-and-technical-requirements:
    get:
      tags:
        - section-syllabus-required-materials-and-technical-requirements
      summary: Return resources from SSASYLB
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          required: false
          schema:
            type: string
        - name: crn
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-syllabus-required-materials-and-technical-r\
                    equirements-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - section-syllabus-required-materials-and-technical-requirements
      summary: Updates an existing resource in SSASYLB
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-syllabus-required-materials-and-technical-r\
                equirements-1.0.0_put_request"
            example:
              technicalRequirement: Detailed technical materials
              requiredMaterials: Course required materials
              crn: 10012
              termCode: 200120
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-syllabus-required-materials-and-technical-r\
                    equirements-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/section-syllabus-required-materials-and-technical-requirements:
    post:
      tags:
        - section-syllabus-required-materials-and-technical-requirements QAPI
          (Query by POST)
      summary: Return resources from SSASYLB
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-syllabus-required-materials-and-technical-r\
                equirements-1.0.0_get_request"
            example:
              crn: 10012
              termCode: 200120
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-syllabus-required-materials-and-technical-r\
                    equirements-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    section-syllabus-required-materials-and-technical-requirements-1.0.0_get_response:
      type: object
      properties:
        ssrsytr:
          type: array
          items:
            type: object
            properties:
              technicalRequirement:
                maxLength: 32767
                description: "Lineage reference object : SSRSYTR_TECHNICAL_REQUIREMENT"
                x-lineageReferenceObject: SSRSYTR_TECHNICAL_REQUIREMENT
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SSRSYTR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SSRSYTR_ACTIVITY_DATE
            x-lineageReferenceObject: ssrsytr
        ssrsyrm:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SSRSYRM_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SSRSYRM_ACTIVITY_DATE
              requiredMaterials:
                maxLength: 32767
                description: "Lineage reference object : SSRSYRM_REQUIRED_MATERIALS"
                x-lineageReferenceObject: SSRSYRM_REQUIRED_MATERIALS
            x-lineageReferenceObject: ssrsyrm
    section-syllabus-required-materials-and-technical-requirements-1.0.0_put_response:
      type: object
      properties:
        ssrsytr:
          type: array
          items:
            type: object
            properties:
              technicalRequirement:
                maxLength: 32767
                description: "Lineage reference object : SSRSYTR_TECHNICAL_REQUIREMENT"
                x-lineageReferenceObject: SSRSYTR_TECHNICAL_REQUIREMENT
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SSRSYTR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SSRSYTR_ACTIVITY_DATE
            x-lineageReferenceObject: ssrsytr
        ssrsyrm:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SSRSYRM_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SSRSYRM_ACTIVITY_DATE
              requiredMaterials:
                maxLength: 32767
                description: "Lineage reference object : SSRSYRM_REQUIRED_MATERIALS"
                x-lineageReferenceObject: SSRSYRM_REQUIRED_MATERIALS
            x-lineageReferenceObject: ssrsyrm
    section-syllabus-required-materials-and-technical-requirements-1.0.0_qapi_post:
      type: object
      properties:
        termCode:
          type: string
        crn:
          type: string
    section-syllabus-required-materials-and-technical-requirements-1.0.0_get_request:
      type: object
      properties:
        crn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : crn"
          x-lineageReferenceObject: crn
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: KEY_BLOCK
    section-syllabus-required-materials-and-technical-requirements-1.0.0_put_request:
      type: object
      properties:
        technicalRequirement:
          maxLength: 32767
          description: "Lineage reference object : SSRSYTR_TECHNICAL_REQUIREMENT"
          x-lineageReferenceObject: SSRSYTR_TECHNICAL_REQUIREMENT
        requiredMaterials:
          maxLength: 32767
          description: "Lineage reference object : SSRSYRM_REQUIRED_MATERIALS"
          x-lineageReferenceObject: SSRSYRM_REQUIRED_MATERIALS
        crn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : crn"
          x-lineageReferenceObject: crn
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SSRSYTR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
