openapi: 3.0.0
info:
  title: ca-import-mass-student-disability-services
  description: API for Mass Import for the Student Disability Services
  version: 1.0.0-beta
  x-source-title: Ca Import Mass Student Disability Services
  x-source-system: banner
  x-api-type: erp
  x-audience: all
  x-release-status: beta
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-import-mass-student-disability-services:
    get:
      tags:
        - ca-import-mass-student-disability-services
      summary: Provide the list of ca import mass student disability service.
      description: Provide the list of ca import mass student disability service.
      parameters:
        - name: limit
          in: query
          description:
            The maximum number of resources requesting for this result set.
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ca-import-mass-student-disability-services-v1_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the clients preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - BasicAuth: []
        - EthosIntegrationBearer: []
      x-method-permission:
    post:
      tags:
        - ca-import-mass-student-disability-services
      summary: Create a ca import mass student disability service with given data in the request body.
      description: Create a ca import mass student disability service with given data in the request body.
      requestBody:
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              $ref: '#/components/schemas/ca-import-mass-student-disability-services-v1_post_request'
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response.
              required: true
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                $ref: '#/components/schemas/ca-import-mass-student-disability-services-v1_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the clients preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
      - BasicAuth: []
      - EthosIntegrationBearer: []
      
components:
  schemas:
    ca-import-mass-student-disability-services-v1_post_request:
      type: object
      properties:
        termCode:
          "title": "Disability Term Code"
          "description": "Disability Term Code."
          "type": string
          "maxLength": 6
          "x-lineageReferenceObject": SGRDISA.SGRDISA_TERM_CODE
        disa:
          "title": "Student Disability Services Details"
          "description": "Student Disability Services Details"
          "type": array
          "items": 
            "type": object
            "properties":
              stuId:
                "title": "Person Internal Identification Number"
                "description": "Person Internal Identification Number."
                "type": string
                "x-lineageReferenceObject": SGRDISA.SGRDISA_PIDM
              disaCode:
                "title": "Disability Code"
                "description": "Disability Code."
                "type": string
                "maxLength": 2
                "x-lineageReferenceObject": SGRDISA.SGRDISA_DISA_CODE
              mediCode:
                "title": "Medical Code"
                "description": "Medical Code."
                "type": string
                "maxLength": 10
                "x-lineageReferenceObject": SGRDISA.SGRDISA_MEDI_CODE
              spsrCode:
                "title": "Disablity Service Code"
                "description": "Disablity Service Code."
                "type": string
                "maxLength": 2
                "x-lineageReferenceObject": SGRDISA.SGRDISA_SPSR_CODE
              primaryInd:
                "title": "Primary Disability Indicator"
                "description": "Primary Disability Indicator."
                "type": string
                "maxLength": 1
                "x-lineageReferenceObject": SGRDISA.SGRDISA_PRIMARY_IND
              disaEffFromDate:
                "title": "disabilityEffectiveFromDate"
                "description": "The date from which the specific piece of data is valid."
                "type": string
                "x-lineageReferenceObject": SGRDISA.SGRDISA_DISA_EFF_FROM_DATE
              disaEffToDate:
                "title": "disabilityEffectiveToDate"
                "description": "The date up to which the specific piece of data is valid."
                "type": string
                "x-lineageReferenceObject": SGRDISA.SGRDISA_DISA_EFF_TO_DATE
              sserCode:
                "title": "Service Type Code"
                "description": "Service Type Code."
                "type": string
                "maxLength": 4
                "x-lineageReferenceObject": SGRDSER.SGRDSER_SSER_CODE
              nbrContacts:
                "title": "Number of Contacts for service"
                "description": "Number of Contacts for service."
                "type": string
                "x-lineageReferenceObject": SGRDSER.SGRDSER_NBR_CONTACTS
              sstCode:
                "title": "Service Status Code"
                "description": "Service Status Code."
                "type": string
                "maxLength": 2
                "x-lineageReferenceObject": SGRDSER.SGRDSER_SSST_CODE
              seprCode:
                "title": "Service Provided Code"
                "description": "Service Provided Code."
                "type": string
                "maxLength": 2
                "x-lineageReferenceObject": SGRDSER.SGRDSER_SEPR_CODE
              sprvCode:
                "title": "Service Provider Code"
                "description": "Service Provider Code."
                "type": string
                "maxLength": 6
                "x-lineageReferenceObject": SGRDSER.SGRDSER_SPRV_CODE
              ssepCode:
                "title": "Service Exemption Code"
                "description": "Service Exemption Code."
                "type": string
                "maxLength": 4
                "x-lineageReferenceObject": SGRDSER.SGRDSER_SSEP_CODE
              beginDate:
                "title": "Service Begin Date"
                "description": "Service Begin Date."
                "type": string
                "x-lineageReferenceObject": SGRDSER.SGRDSER_BEGIN_DATE
              endDate:
                "title": "Service End Date"
                "description": "Service End Date."
                "type": string
                "x-lineageReferenceObject": SGRDSER.SGRDSER_END_DATE
              ssrsCode:
                "title": "Service Result Code"
                "description": "Service Result Code."
                "type": string
                "maxLength": 2
                "x-lineageReferenceObject": SGRDSER.SGRDSER_SSRS_CODE
              origCode:
                "title": "Originator Code"
                "description": "Originator Code."
                "type": string
                "maxLength": 4
                "x-lineageReferenceObject": SGRDSER.SGRDSER_ORIG_CODE
              campCode:
                "title": "Campus Code"
                "description": "Campus Code."
                "type": string
                "maxLength": 3
                "x-lineageReferenceObject": SGRDSER.SGRDSER_CAMP_CODE
      required:
        - id
        - termCode
        - stuId
        - disaCode
    ca-import-mass-student-disability-services-v1_response:
      type: object
      properties:
        termCode:
          "title": "Disability Term"
          "description": "Disability Term Code."
          "type": string
          "maxLength": 6
          "x-lineageReferenceObject": SGRDISA.SGRDISA_TERM_CODE
        stuId:
          "title": "Person Internal Identification Number"
          "description": "Person Internal Identification Number."
          "type": string
          "x-lineageReferenceObject": SGRDISA.SGRDISA_PIDM
        disaCode:
          "title": "Disability Code"
          "description": "Disability Code."
          "type": string
          "maxLength": 2
          "x-lineageReferenceObject": SGRDISA.SGRDISA_DISA_CODE
        mediCode:
          "title": "Medical Code"
          "description": "Medical Code."
          "type": string
          "maxLength": 10
          "x-lineageReferenceObject": SGRDISA.SGRDISA_MEDI_CODE
        spsrCode:
          "title": "Disablity Service Code"
          "description": "Disablity Service Code."
          "type": string
          "maxLength": 2
          "x-lineageReferenceObject": SGRDISA.SGRDISA_SPSR_CODE
        primaryInd:
          "title": "Primary Disability Indicator"
          "description": "Primary Disability Indicator."
          "type": string
          "maxLength": 1
          "x-lineageReferenceObject": SGRDISA.SGRDISA_PRIMARY_IND
        disaEffFromDate:
          "title": "disabilityEffectiveFromDate"
          "description": "The date from which the specific piece of data is valid."
          "type": string
          "x-lineageReferenceObject": SGRDISA.SGRDISA_DISA_EFF_FROM_DATE
        disaEffToDate:
          "title": "disabilityEffectiveToDate"
          "description": "The date up to which the specific piece of data is valid."
          "type": string
          "x-lineageReferenceObject": SGRDISA.SGRDISA_DISA_EFF_TO_DATE
        sserCode:
          "title": "Service Type Code"
          "description": "Service Type Code."
          "type": string
          "maxLength": 4
          "x-lineageReferenceObject": SGRDSER.SGRDSER_SSER_CODE
        nbrContacts:
          "title": "Number of Contacts for service"
          "description": "Number of Contacts for service."
          "type": string
          "x-lineageReferenceObject": SGRDSER.SGRDSER_NBR_CONTACTS
        sstCode:
          "title": "Service Status Code"
          "description": "Service Status Code."
          "type": string
          "maxLength": 2
          "x-lineageReferenceObject": SGRDSER.SGRDSER_SSST_CODE
        seprCode:
          "title": "Service Provided Code"
          "description": "Service Provided Code."
          "type": string
          "maxLength": 2
          "x-lineageReferenceObject": SGRDSER.SGRDSER_SEPR_CODE
        sprvCode:
          "title": "Service Provider Code"
          "description": "Service Provider Code."
          "type": string
          "maxLength": 6
          "x-lineageReferenceObject": SGRDSER.SGRDSER_SPRV_CODE
        ssepCode:
          "title": "Service Exemption Code"
          "description": "Service Exemption Code."
          "type": string
          "maxLength": 4
          "x-lineageReferenceObject": SGRDSER.SGRDSER_SSEP_CODE
        beginDate:
          "title": "Service Begin Date"
          "description": "Service Begin Date."
          "type": string
          "x-lineageReferenceObject": SGRDSER.SGRDSER_BEGIN_DATE
        endDate:
          "title": "Service End Date"
          "description": "Service End Date."
          "type": string
          "x-lineageReferenceObject": SGRDSER.SGRDSER_END_DATE
        ssrsCode:
          "title": "Service Result Code"
          "description": "Service Result Code."
          "type": string
          "maxLength": 2
          "x-lineageReferenceObject": SGRDSER.SGRDSER_SSRS_CODE
        origCode:
          "title": "Originator Code"
          "description": "Originator Code."
          "type": string
          "maxLength": 4
          "x-lineageReferenceObject": SGRDSER.SGRDSER_ORIG_CODE
        campCode:
          "title": "Campus Code"
          "description": "Campus Code."
          "type": string
          "maxLength": 3
          "x-lineageReferenceObject": SGRDSER.SGRDSER_CAMP_CODE
      required:
        - id
        - termCode
        - stuId
        - disaCode
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: The detailed actionable error message.
  securitySchemes:
    BasicAuth:
        type: http
        scheme: basic
    EthosIntegrationBearer:
        type: http
        scheme: bearer