openapi: 3.0.0
info:
  title: award-maintenance-disbursement-schedule
  description: API for RPAAWRD administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RPAAWRD
  x-source-domain: Financial Aid
  x-source-title: Award Maintenance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/award-maintenance-disbursement-schedule:
    get:
      tags:
        - award-maintenance-disbursement-schedule
      summary: Return resources from RPAAWRD
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: fundCode
          in: query
          required: false
          schema:
            type: string
        - name: period
          in: query
          required: false
          schema:
            type: string
        - name: scheduleDate
          in: query
          required: false
          schema:
            type: string
        - name: displayScheduleAmt
          in: query
          required: false
          schema:
            type: string
        - name: disbursePct
          in: query
          required: false
          schema:
            type: string
        - name: disburseLoadOpt
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/award-maintenance-disbursement-schedule-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/award-maintenance-disbursement-schedule:
    post:
      tags:
        - award-maintenance-disbursement-schedule QAPI (Query by POST)
      summary: Return resources from RPAAWRD
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/award-maintenance-disbursement-schedule-1.0.0_get_r\
                equest"
            example:
              keyblckAidyCode: 2122
              fundCode: AJASST
              id: GENSTU001
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/award-maintenance-disbursement-schedule-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    award-maintenance-disbursement-schedule-1.0.0_get_request:
      required:
        - fundCode
        - period
        - scheduleDate
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        period:
          title: Period
          maxLength: 30
          type: string
          description: "Lineage reference object : RPRADSB_PERIOD"
          x-lineageReferenceObject: RPRADSB_PERIOD
        fundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : RPRADSB_FUND_CODE, Lookup lineage
            reference object : rfrbase,rfraspc"
          x-lineageReferenceObject: RPRADSB_FUND_CODE
          x-lineageLookupReferenceObject: rfrbase,rfraspc
        disbursePct:
          title: Schedule Percent
          maxLength: 7
          type: number
          description: "Lineage reference object : RPRADSB_DISBURSE_PCT"
          x-lineageReferenceObject: RPRADSB_DISBURSE_PCT
        scheduleDate:
          title: Schedule Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RPRADSB_SCHEDULE_DATE"
          format: date-time
          x-lineageReferenceObject: RPRADSB_SCHEDULE_DATE
        disburseLoadOpt:
          title: Schedule Enrollment Option
          maxLength: 1
          type: string
          description: "Lineage reference object : RPRADSB_DISBURSE_LOAD_OPT"
          x-lineageReferenceObject: RPRADSB_DISBURSE_LOAD_OPT
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        displayScheduleAmt:
          title: Schedule Amount
          maxLength: 14
          type: number
      x-lineageReferenceObject: RPRADSB
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    award-maintenance-disbursement-schedule-1.0.0_get_response:
      type: object
      properties:
        rpradsb:
          type: array
          items:
            required:
              - fundCode
              - period
              - scheduleDate
            type: object
            properties:
              period:
                title: Period
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_PERIOD"
                x-lineageReferenceObject: RPRADSB_PERIOD
              disbursePct:
                title: Schedule Percent
                maxLength: 7
                type: number
                description: "Lineage reference object : RPRADSB_DISBURSE_PCT"
                x-lineageReferenceObject: RPRADSB_DISBURSE_PCT
              fundCode:
                title: Fund
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_FUND_CODE, Lookup lineage
                  reference object : rfrbase,rfraspc"
                x-lineageReferenceObject: RPRADSB_FUND_CODE
                x-lineageLookupReferenceObject: rfrbase,rfraspc
              disburseLoadOpt:
                title: Schedule Enrollment Option
                maxLength: 1
                type: string
                description: "Lineage reference object : RPRADSB_DISBURSE_LOAD_OPT"
                x-lineageReferenceObject: RPRADSB_DISBURSE_LOAD_OPT
              scheduleDate:
                title: Schedule Date
                maxLength: 11
                type: string
                description: "Lineage reference object : RPRADSB_SCHEDULE_DATE"
                format: date-time
                x-lineageReferenceObject: RPRADSB_SCHEDULE_DATE
              displayScheduleAmt:
                title: Schedule Amount
                maxLength: 14
                type: number
            x-lineageReferenceObject: rpradsb
        rpradsb_act:
          type: array
          items:
            required:
              - rpradsbFundCode
              - rpradsbPeriod
            type: object
            properties:
              rpradsbDisburseDate:
                maxLength: 11
                type: string
                description: "Lineage reference object : RPRADSB_DISBURSE_DATE"
                format: date-time
                x-lineageReferenceObject: RPRADSB_DISBURSE_DATE
              rpradsbTermCode:
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_TERM_CODE, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: RPRADSB_TERM_CODE
                x-lineageLookupReferenceObject: stvterm
              rpradsbDisburseLoad:
                maxLength: 1
                type: string
                description: "Lineage reference object : RPRADSB_DISBURSE_LOAD"
                x-lineageReferenceObject: RPRADSB_DISBURSE_LOAD
              rpradsbFundCode:
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_FUND_CODE, Lookup lineage
                  reference object : rfrbase,rfraspc"
                x-lineageReferenceObject: RPRADSB_FUND_CODE
                x-lineageLookupReferenceObject: rfrbase,rfraspc
              rpradsbTranNumber:
                maxLength: 8
                type: number
                description: "Lineage reference object : RPRADSB_TRAN_NUMBER"
                x-lineageReferenceObject: RPRADSB_TRAN_NUMBER
              rpradsbDisburseAmt:
                maxLength: 14
                type: number
                description: "Lineage reference object : RPRADSB_DISBURSE_AMT"
                x-lineageReferenceObject: RPRADSB_DISBURSE_AMT
              rpradsbPeriod:
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_PERIOD"
                x-lineageReferenceObject: RPRADSB_PERIOD
            x-lineageReferenceObject: rpradsb_act
        rpradsb_calc:
          type: array
          items:
            required:
              - rpradsbFundCode
              - rpradsbPeriod
            type: object
            properties:
              rpradsbFundCode:
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_FUND_CODE, Lookup lineage
                  reference object : rfrbase,rfraspc"
                x-lineageReferenceObject: RPRADSB_FUND_CODE
                x-lineageLookupReferenceObject: rfrbase,rfraspc
              rpradsbPellCalcDisbAmt:
                maxLength: 14
                type: number
                description: "Lineage reference object : RPRADSB_PELL_CALC_DISB_AMT"
                x-lineageReferenceObject: RPRADSB_PELL_CALC_DISB_AMT
              rpradsbPeriod:
                maxLength: 30
                type: string
                description: "Lineage reference object : RPRADSB_PERIOD"
                x-lineageReferenceObject: RPRADSB_PERIOD
              rpradsbPellcDisbLoadOpt:
                maxLength: 1
                type: string
                description: "Lineage reference object : RPRADSB_PELLC_DISB_LOAD_OPT"
                x-lineageReferenceObject: RPRADSB_PELLC_DISB_LOAD_OPT
              rpradsbPellcDisbLoad:
                maxLength: 1
                type: string
                description: "Lineage reference object : RPRADSB_PELLC_DISB_LOAD"
                x-lineageReferenceObject: RPRADSB_PELLC_DISB_LOAD
            x-lineageReferenceObject: rpradsb_calc
    award-maintenance-disbursement-schedule-1.0.0_qapi_post:
      type: object
      properties:
        keyblckAidyCode:
          type: string
        id:
          type: string
        fundCode:
          type: string
        period:
          type: string
        scheduleDate:
          type: string
        displayScheduleAmt:
          type: string
        disbursePct:
          type: string
        disburseLoadOpt:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
