openapi: 3.0.0
info:
  title: program-details-end
  description: API for SMAPFPA administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SMAPFPA
  x-source-domain: Student
  x-source-title: Program Detail Information
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: '{server_url}'
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/program-details-end:
    post:
      tags:
      - program-details-end
      summary: Creates a new resource in SMAPFPA
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/program-details-end-1.0.0_post_request"
            example:
              keyblckProgram: '0001'
              keyblckTermCodeEff: 222227
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/program-details-end-1.0.0_post_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/program-details-end: {}
components:
  schemas:
    program-details-end-1.0.0_post_request:
      type: object
      properties:
        keyblckProgram:
          title: Program
          maxLength: 12
          type: string
          description: "Lineage reference object : keyblckProgram, Lookup lineage\
            \ reference object : smrprle"
          x-lineageReferenceObject: keyblckProgram
          x-lineageLookupReferenceObject: smrprle
        keyblckTermCodeEff:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : keyblckTermCodeEff, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCodeEff
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: KEY_BLOCK
    program-details-end-1.0.0_post_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              keyblckProgram:
                title: Program
                maxLength: 12
                type: string
                description: "Lineage reference object : keyblckProgram, Lookup lineage\
                  \ reference object : smrprle"
                x-lineageReferenceObject: keyblckProgram
                x-lineageLookupReferenceObject: smrprle
              keyblckTermDesc:
                type: string
                description: "Lineage reference object : keyblckTermDesc"
                x-lineageReferenceObject: keyblckTermDesc
              keyblckProgramDesc:
                type: string
                description: "Lineage reference object : keyblckProgramDesc"
                x-lineageReferenceObject: keyblckProgramDesc
              keyblckTermCodeEff:
                title: Term
                maxLength: 6
                type: string
                description: "Lineage reference object : keyblckTermCodeEff, Lookup\
                  \ lineage reference object : stvterm"
                x-lineageReferenceObject: keyblckTermCodeEff
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: key_block
        smrpfpa_ctrl_block:
          type: array
          items:
            type: object
            properties:
              smrpfpaToTerm:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : smrpfpaToTerm"
                x-lineageReferenceObject: smrpfpaToTerm
              smrpfpaFromTerm:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : smrpfpaFromTerm"
                x-lineageReferenceObject: smrpfpaFromTerm
            x-lineageReferenceObject: smrpfpa_ctrl_block
        smrpfpa:
          type: array
          items:
            type: object
            properties:
              longProgramTitle:
                title: Program Title
                type: string
                description: "Lineage reference object : SMRPFPA_LONG_PROGRAM_TITLE"
                x-lineageReferenceObject: SMRPFPA_LONG_PROGRAM_TITLE
              accreditationStatement:
                maxLength: 32767
                type: string
                description: "Lineage reference object : SMRPFPA_ACCRED_STATEMENT"
                x-lineageReferenceObject: SMRPFPA_ACCRED_STATEMENT
              pathwayFurtherStudyStatement:
                maxLength: 32767
                type: string
                description: "Lineage reference object : SMRPFPA_PATH_STUDY_STATEMENT"
                x-lineageReferenceObject: SMRPFPA_PATH_STUDY_STATEMENT
              termEndcopy:
                maxLength: 30
                type: string
              programFeaturesStatement:
                maxLength: 32767
                type: string
                description: "Lineage reference object : SMRPFPA_FEATURES_STATEMENT"
                x-lineageReferenceObject: SMRPFPA_FEATURES_STATEMENT
              botpInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SMRPFPA_BOTP_IND"
                x-lineageReferenceObject: SMRPFPA_BOTP_IND
              programSummaryStatement:
                maxLength: 32767
                type: string
                description: "Lineage reference object : SMRPFPA_SUMMARY_STATEMENT"
                x-lineageReferenceObject: SMRPFPA_SUMMARY_STATEMENT
              artsExcludeInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SMRPFPA_ARTS_EXCLUDE_IND"
                x-lineageReferenceObject: SMRPFPA_ARTS_EXCLUDE_IND
              totalUnits:
                title: Number of units in Program
                maxLength: 3
                type: number
                description: "Lineage reference object : SMRPFPA_TOTAL_UNITS"
                x-lineageReferenceObject: SMRPFPA_TOTAL_UNITS
            x-lineageReferenceObject: smrpfpa
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer