openapi: 3.0.0
info:
  title: gpa-academic-standings
  description: |
    Retrieves the following information of the student.

      __Current Standing based on term__
      
      __Term GPA__
      
      __Level GPA__
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: GPA Academic Standings
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: gpa-academic-standings
paths:
  /api/students/{bannerId}/gpa-academic-standings:
    get:
      description: >
        The term is optional Url parameter to the API.

          If term is provided, the API fetches academic standing along with the term GPA for the provided term.

          
        If the term is not provided, the API fetches the academic standing along
        with the term GPA for each term the student has academic history.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_GPA_ACADEMIC_STANDINGS, API_STUDENTS
      tags:
        - gpa-academic-standings
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/vnd.hedtech.integration.v1.0.0+json
            ```
        - name: bannerId
          in: path
          required: true
          schema:
            type: string
          example: HOSH293
        - name: term
          in: query
          required: false
          schema:
            type: string
          example: "102896"
          description: Code value to identify the term
      responses:
        "200":
          description: Success
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/gpa-academic-standings"
            application/vnd.hedtech.integration.v1.0.0+xml:
              schema:
                type: object
                $ref: "#/components/schemas/gpa-academic-standings"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    gpa-academic-standings:
      type: array
      items:
        type: object
        properties:
          levelGPAs:
            type: array
            items:
              type: object
              properties:
                gpa:
                  type: string
                gpaHours:
                  type: number
                gpaTypeIndicator:
                  type: string
                gpaTypeIndicatorDescription:
                  type: string
                hoursAttempted:
                  type: number
                hoursEarned:
                  type: number
                hoursPassed:
                  type: number
                level:
                  type: string
                levelDescription:
                  type: string
                qualityPoints:
                  type: string
                term:
                  type: string
          studentTermGpaAcademicStandings:
            type: array
            items:
              type: object
              properties:
                academicStanding:
                  type: string
                academicStandingDescription:
                  type: string
                academicStandingTermDescription:
                  type: string
                deansList:
                  type: string
                deansListDescription:
                  type: string
                progressEvaluation:
                  type: string
                progressEvaluationDescription:
                  type: string
                term:
                  type: string
                termDescription:
                  type: string
                termGPAs:
                  type: array
                  items:
                    type: object
                    properties:
                      gpa:
                        type: string
                      gpaHours:
                        type: number
                      gpaTypeIndicator:
                        type: string
                      gpaTypeIndicatorDescription:
                        type: string
                      hoursAttempted:
                        type: number
                      hoursEarned:
                        type: number
                      hoursPassed:
                        type: number
                      level:
                        type: string
                      levelDescription:
                        type: string
                      qualityPoints:
                        type: string
                      term:
                        type: string
