openapi: 3.0.0
info:
  title: data-privacy-retention-collection-header-history
  description: API for GUIRTBH administrative page
  version: 0.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: GUIRTBH
  x-source-domain: Foundation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/data-privacy-retention-collection-header-history:
    get:
      tags:
        - data-privacy-retention-collection-header-history
      summary: Return resources from GUIRTBH
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckApplication
          in: query
          required: false
          schema:
            type: string
        - name: auditTime
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_AUDIT_TIME
        - name: auditAction
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_AUDIT_ACTION
        - name: retrCode
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_RETR_CODE
        - name: expireDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_EXPIRE_DATE
        - name: status
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_STATUS
        - name: creatorId
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_CREATOR_ID
        - name: ipaddr
          in: query
          required: false
          schema:
            type: string
        - name: comment
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_COMMENT
        - name: activityDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_ACTIVITY_DATE
        - name: userId
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURRTBH_USER_ID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-collection-header-history-0.\
                    1.0_get_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/data-privacy-retention-collection-header-history:
    post:
      tags:
        - data-privacy-retention-collection-header-history QAPI (Query by POST)
      summary: Return resources from GUIRTBH
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-retention-collection-header-history-0.\
                1.0_get_request"
            example:
              keyblckApplication: EXAMPLE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-collection-header-history-0.\
                    1.0_get_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    data-privacy-retention-collection-header-history-0.1.0_get_response:
      type: object
      properties:
        activityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRTBH_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GURRTBH_ACTIVITY_DATE
        auditTime:
          title: Audit Time
          maxLength: 26
          description: "Lineage reference object : GURRTBH_AUDIT_TIME"
          x-lineageReferenceObject: GURRTBH_AUDIT_TIME
        auditAction:
          title: Audit Action
          maxLength: 1
          type: string
          description: "Lineage reference object : GURRTBH_AUDIT_ACTION"
          x-lineageReferenceObject: GURRTBH_AUDIT_ACTION
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRTBH_CREATOR_ID"
          x-lineageReferenceObject: GURRTBH_CREATOR_ID
        ipAddress:
          maxLength: 50
          type: string
          description: "Lineage reference object : GURRTBH_IPADDR"
          x-lineageReferenceObject: GURRTBH_IPADDR
        comment:
          title: Comments
          maxLength: 10
          type: string
          description: "Lineage reference object : GURRTBH_COMMENT"
          x-lineageReferenceObject: GURRTBH_COMMENT
        expireDate:
          title: Expiration Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRTBH_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GURRTBH_EXPIRE_DATE
        retrCode:
          title: Retention Rule Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GURRTBH_RETR_CODE"
          x-lineageReferenceObject: GURRTBH_RETR_CODE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRTBH_USER_ID"
          x-lineageReferenceObject: GURRTBH_USER_ID
        status:
          title: Collection Status
          type: string
          description: "Lineage reference object : GURRTBH_STATUS"
          x-lineageReferenceObject: GURRTBH_STATUS
      x-lineageReferenceObject: gurrtbh
    data-privacy-retention-collection-header-history-0.1.0_qapi_post:
      type: object
      properties:
        keyblckApplication:
          type: string
        auditTime:
          title: Audit Time
          maxLength: 26
          description: "Lineage reference object : GURRTBH_AUDIT_TIME"
          x-lineageReferenceObject: GURRTBH_AUDIT_TIME
        auditAction:
          title: Audit Action
          maxLength: 1
          type: string
          description: "Lineage reference object : GURRTBH_AUDIT_ACTION"
          x-lineageReferenceObject: GURRTBH_AUDIT_ACTION
        retrCode:
          title: Retention Rule Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GURRTBH_RETR_CODE"
          x-lineageReferenceObject: GURRTBH_RETR_CODE
        expireDate:
          title: Expiration Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRTBH_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GURRTBH_EXPIRE_DATE
        status:
          title: Collection Status
          type: string
          description: "Lineage reference object : GURRTBH_STATUS"
          x-lineageReferenceObject: GURRTBH_STATUS
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRTBH_CREATOR_ID"
          x-lineageReferenceObject: GURRTBH_CREATOR_ID
        ipaddr:
          type: string
        comment:
          title: Comments
          maxLength: 10
          type: string
          description: "Lineage reference object : GURRTBH_COMMENT"
          x-lineageReferenceObject: GURRTBH_COMMENT
        activityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRTBH_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GURRTBH_ACTIVITY_DATE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRTBH_USER_ID"
          x-lineageReferenceObject: GURRTBH_USER_ID
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    data-privacy-retention-collection-header-history-0.1.0_get_request:
      type: object
      properties:
        activityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRTBH_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GURRTBH_ACTIVITY_DATE
        auditTime:
          title: Audit Time
          maxLength: 26
          description: "Lineage reference object : GURRTBH_AUDIT_TIME"
          x-lineageReferenceObject: GURRTBH_AUDIT_TIME
        keyblckApplication:
          title: Retention Collection
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckApplication, Lookup lineage
            reference object : gubretc"
          x-lineageReferenceObject: keyblckApplication
          x-lineageLookupReferenceObject: gubretc
        auditAction:
          title: Audit Action
          maxLength: 1
          type: string
          description: "Lineage reference object : GURRTBH_AUDIT_ACTION"
          x-lineageReferenceObject: GURRTBH_AUDIT_ACTION
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRTBH_CREATOR_ID"
          x-lineageReferenceObject: GURRTBH_CREATOR_ID
        retrCode:
          title: Retention Rule Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GURRTBH_RETR_CODE"
          x-lineageReferenceObject: GURRTBH_RETR_CODE
        expireDate:
          title: Expiration Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GURRTBH_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GURRTBH_EXPIRE_DATE
        comment:
          title: Comments
          maxLength: 10
          type: string
          description: "Lineage reference object : GURRTBH_COMMENT"
          x-lineageReferenceObject: GURRTBH_COMMENT
        ipaddr:
          maxLength: 50
          type: string
          description: "Lineage reference object : GURRTBH_IPADDR"
          x-lineageReferenceObject: GURRTBH_IPADDR
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GURRTBH_USER_ID"
          x-lineageReferenceObject: GURRTBH_USER_ID
        status:
          title: Collection Status
          type: string
          description: "Lineage reference object : GURRTBH_STATUS"
          x-lineageReferenceObject: GURRTBH_STATUS
      x-lineageReferenceObject: GURRTBH
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
