openapi: 3.0.0
info:
  title: section-restriction-campus-and-college
  description: API for SSARRES administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SSARRES
  x-source-domain: Student
  x-source-title: Schedule Restrictions
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/section-restriction-campus-and-college:
    get:
      tags:
        - section-restriction-campus-and-college
      summary: Return resources from SSARRES
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: ssasectTermCode
          in: query
          required: true
          schema:
            type: string
        - name: ssasectCrn
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-restriction-campus-and-college-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/section-restriction-campus-and-college:
    post:
      tags:
        - section-restriction-campus-and-college QAPI (Query by POST)
      summary: Return resources from SSARRES
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-restriction-campus-and-college-1.0.0_get_re\
                quest"
            example:
              ssasectTermCode: 1010
              ssasectCrn: 10014
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-restriction-campus-and-college-1.0.0_get_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    section-restriction-campus-and-college-1.0.0_get_response:
      type: object
      properties:
        ssrrcol:
          type: array
          items:
            type: object
            properties:
              collDescription:
                title: Description
                type: string
              collCode:
                title: College
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRCOL_COLL_CODE, Lookup lineage
                  reference object : stvcoll"
                x-lineageReferenceObject: SSRRCOL_COLL_CODE
                x-lineageLookupReferenceObject: stvcoll
            x-lineageReferenceObject: ssrrcol
        rcol_ctrl_block:
          type: array
          items:
            required:
              - ssrrcolCollInd
            type: object
            properties:
              ssrrcolCollInd:
                title: "Include/Exclude (I/E):"
                maxLength: 1
                type: string
                description: "Lineage reference object : ssrrcolCollInd"
                x-lineageReferenceObject: ssrrcolCollInd
            x-lineageReferenceObject: rcol_ctrl_block
        ssrrcmp:
          type: array
          items:
            type: object
            properties:
              campCode:
                title: Campus
                maxLength: 30
                type: string
                description: "Lineage reference object : SSRRCMP_CAMP_CODE, Lookup lineage
                  reference object : stvcamp"
                x-lineageReferenceObject: SSRRCMP_CAMP_CODE
                x-lineageLookupReferenceObject: stvcamp
              campDescription:
                title: Description
                type: string
            x-lineageReferenceObject: ssrrcmp
        rcmp_ctrl_block:
          type: array
          items:
            required:
              - ssrrcmpCampInd
            type: object
            properties:
              ssrrcmpCampInd:
                title: "Include/Exclude (I/E):"
                maxLength: 1
                type: string
                description: "Lineage reference object : ssrrcmpCampInd"
                x-lineageReferenceObject: ssrrcmpCampInd
            x-lineageReferenceObject: rcmp_ctrl_block
    section-restriction-campus-and-college-1.0.0_get_request:
      required:
        - ssasectTermCode
      type: object
      properties:
        ssasectTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: ssasectTermCode
          x-lineageLookupReferenceObject: stvterm
        ssasectCrn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectCrn"
          x-lineageReferenceObject: ssasectCrn
      x-lineageReferenceObject: KEY_BLOCK
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    section-restriction-campus-and-college-1.0.0_qapi_post:
      required:
        - ssasectTermCode
      type: object
      properties:
        ssasectTermCode:
          type: string
        ssasectCrn:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
