openapi: 3.0.0
info:
  title: prior-college-prior-college-address
  description: API for SOAPCOL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SOAPCOL
  x-source-domain: Student
  x-source-title: Prior College
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/prior-college-prior-college-address:
    get:
      tags:
        - prior-college-prior-college-address
      summary: Return resources from SOAPCOL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/prior-college-prior-college-address-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/prior-college-prior-college-address:
    post:
      tags:
        - prior-college-prior-college-address QAPI (Query by POST)
      summary: Return resources from SOAPCOL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/prior-college-prior-college-address-1.0.0_get_reque\
                st"
            example:
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/prior-college-prior-college-address-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    prior-college-prior-college-address-1.0.0_get_response:
      type: object
      properties:
        sobsbgiStatCode:
          title: State or Province
          maxLength: 3
          type: string
          description: "Lineage reference object : sobsbgiStatCode, Lookup lineage
            reference object : stvstat"
          x-lineageReferenceObject: sobsbgiStatCode
          x-lineageLookupReferenceObject: stvstat
        sobsbgiNatnCode:
          title: Nation
          maxLength: 6
          type: string
          description: "Lineage reference object : sobsbgiNatnCode, Lookup lineage
            reference object : stvnatn"
          x-lineageReferenceObject: sobsbgiNatnCode
          x-lineageLookupReferenceObject: stvnatn
        sobsbgiCntyCode:
          title: County
          maxLength: 5
          type: string
          description: "Lineage reference object : sobsbgiCntyCode, Lookup lineage
            reference object : stvcnty"
          x-lineageReferenceObject: sobsbgiCntyCode
          x-lineageLookupReferenceObject: stvcnty
        sobsbgiCity:
          title: City
          maxLength: 50
          type: string
          description: "Lineage reference object : sobsbgiCity"
          x-lineageReferenceObject: sobsbgiCity
        stvcntyDesc:
          type: string
          description: "Lineage reference object : stvcntyDesc"
          x-lineageReferenceObject: stvcntyDesc
        sobsbgiStreetLine1:
          title: Street Line 1
          maxLength: 75
          type: string
          description: "Lineage reference object : sobsbgiStreetLine1"
          x-lineageReferenceObject: sobsbgiStreetLine1
        sobsbgiZip:
          title: ZIP or Postal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : sobsbgiZip"
          x-lineageReferenceObject: sobsbgiZip
        stvstatDesc:
          title: State or Province Description
          type: string
          description: "Lineage reference object : stvstatDesc"
          x-lineageReferenceObject: stvstatDesc
        sobsbgiStreetLine2:
          title: Street Line 2
          maxLength: 75
          type: string
          description: "Lineage reference object : sobsbgiStreetLine2"
          x-lineageReferenceObject: sobsbgiStreetLine2
        sobsbgiStreetLine3:
          title: Street Line 3
          maxLength: 75
          type: string
          description: "Lineage reference object : sobsbgiStreetLine3"
          x-lineageReferenceObject: sobsbgiStreetLine3
        stvnatnDesc:
          title: Nation Description
          type: string
          description: "Lineage reference object : stvnatnDesc"
          x-lineageReferenceObject: stvnatnDesc
        addrDisp:
          maxLength: 1
          type: string
          description: "Lineage reference object : addrDisp"
          x-lineageReferenceObject: addrDisp
      x-lineageReferenceObject: ctrl_sobsbgi
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    prior-college-prior-college-address-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
    prior-college-prior-college-address-1.0.0_get_request:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
