openapi: 3.0.0
info:
  title: student-billing-mass-data-entry-deposits
  description: API for TSAMASS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TSAMASS
  x-source-domain: Student
  x-source-title: Billing Mass Data Entry Form - Student
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-billing-mass-data-entry-deposits:
    post:
      tags:
        - student-billing-mass-data-entry-deposits
      summary: Creates a new resource in TSAMASS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-billing-mass-data-entry-deposits-1.0.0_post\
                _request"
            example:
              keybloc2DetailCode: FDEP
              minAmount: 10
              amount: 250
              releaseDate: 2021-02-07
              keybloc2ExpirationDate: 2021-02-07
              keybloc2MinAmount: 10
              keybloc2TermCode: 201520
              keybloc2DocumentNumber: 1
              detailCodePayment: DCHK
              detailCodeDeposit: FDEP
              keybloc2Amount: 250
              keybloc2DetailCodePay: DCHK
              keybloc2ReleaseDate: 2021-02-07
              keybloc2EffDate: 2021-01-07
              id: 341819778
              desc: Fee Deposit
              termCode: 201520
              expirationDate: 2021-02-07
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-billing-mass-data-entry-deposits-1.0.0_post\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/student-billing-mass-data-entry-deposits: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    student-billing-mass-data-entry-deposits-1.0.0_post_request:
      required:
        - detailCodeDeposit
        - desc
        - detailCodePayment
        - termCode
        - amount
        - autoReleaseInd
        - receiptInd
      type: object
      properties:
        keybloc2DetailCode:
          title: Deposit Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keybloc2DetailCode"
          x-lineageReferenceObject: keybloc2DetailCode
        minAmount:
          title: Minimum
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRDEPO_MIN_AMOUNT"
          x-lineageReferenceObject: TBRDEPO_MIN_AMOUNT
        amount:
          title: Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRDEPO_AMOUNT"
          x-lineageReferenceObject: TBRDEPO_AMOUNT
        releaseDate:
          title: Release Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRDEPO_RELEASE_DATE"
          format: date-time
          x-lineageReferenceObject: TBRDEPO_RELEASE_DATE
        documentNumber:
          title: Document
          maxLength: 8
          type: string
          description: "Lineage reference object : TBRDEPO_DOCUMENT_NUMBER"
          x-lineageReferenceObject: TBRDEPO_DOCUMENT_NUMBER
        keybloc2ExpirationDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : keybloc2ExpirationDate"
          format: date-time
          x-lineageReferenceObject: keybloc2ExpirationDate
        keybloc2MinAmount:
          title: Minimum
          maxLength: 10
          type: number
          description: "Lineage reference object : keybloc2MinAmount"
          x-lineageReferenceObject: keybloc2MinAmount
        keybloc2TermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : keybloc2TermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keybloc2TermCode
          x-lineageLookupReferenceObject: stvterm
        keybloc2DocumentNumber:
          title: Document
          maxLength: 8
          type: string
          description: "Lineage reference object : keybloc2DocumentNumber"
          x-lineageReferenceObject: keybloc2DocumentNumber
        detailCodePayment:
          title: Payment Code
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRDEPO_DETAIL_CODE_PAYMENT, Lookup
            lineage reference object : tbbdetc"
          x-lineageReferenceObject: TBRDEPO_DETAIL_CODE_PAYMENT
          x-lineageLookupReferenceObject: tbbdetc
        receiptInd:
          title: Receipt
          maxLength: 1
          type: string
        detailCodeDeposit:
          title: Deposit Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBRDEPO_DETAIL_CODE_DEPOSIT"
          x-lineageReferenceObject: TBRDEPO_DETAIL_CODE_DEPOSIT
        autoReleaseInd:
          title: Release
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRDEPO_AUTO_RELEASE_IND"
          x-lineageReferenceObject: TBRDEPO_AUTO_RELEASE_IND
        keybloc2Amount:
          title: Amount
          maxLength: 10
          type: number
          description: "Lineage reference object : keybloc2Amount"
          x-lineageReferenceObject: keybloc2Amount
        keybloc2AutoReleaseInd:
          title: Auto Release
          maxLength: 1
          type: string
          description: "Lineage reference object : keybloc2AutoReleaseInd"
          x-lineageReferenceObject: keybloc2AutoReleaseInd
        keybloc2DetailCodePay:
          title: Payment Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keybloc2DetailCodePay, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: keybloc2DetailCodePay
          x-lineageLookupReferenceObject: tbbdetc
        keybloc2ReleaseDate:
          title: Release Date
          maxLength: 11
          type: string
          description: "Lineage reference object : keybloc2ReleaseDate"
          format: date-time
          x-lineageReferenceObject: keybloc2ReleaseDate
        keybloc2EffDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : keybloc2EffDate"
          format: date-time
          x-lineageReferenceObject: keybloc2EffDate
        id:
          title: ID
          maxLength: 9
          type: string
        desc:
          title: Deposit Code Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRDEPO_DESC"
          x-lineageReferenceObject: TBRDEPO_DESC
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : TBRDEPO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBRDEPO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        expirationDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRDEPO_EXPIRATION_DATE"
          format: date-time
          x-lineageReferenceObject: TBRDEPO_EXPIRATION_DATE
      x-lineageReferenceObject: TBRDEPO
    student-billing-mass-data-entry-deposits-1.0.0_post_response:
      type: object
      properties:
        tbrdepo:
          type: array
          items:
            required:
              - receiptInd
              - amount
              - autoReleaseInd
              - desc
              - detailCodeDeposit
              - detailCodePayment
              - termCode
            type: object
            properties:
              minAmount:
                title: Minimum
                maxLength: 9
                type: number
                description: "Lineage reference object : TBRDEPO_MIN_AMOUNT"
                x-lineageReferenceObject: TBRDEPO_MIN_AMOUNT
              amount:
                title: Amount
                maxLength: 9
                type: number
                description: "Lineage reference object : TBRDEPO_AMOUNT"
                x-lineageReferenceObject: TBRDEPO_AMOUNT
              releaseDate:
                title: Release Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRDEPO_RELEASE_DATE"
                format: date-time
                x-lineageReferenceObject: TBRDEPO_RELEASE_DATE
              documentNumber:
                title: Document
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRDEPO_DOCUMENT_NUMBER"
                x-lineageReferenceObject: TBRDEPO_DOCUMENT_NUMBER
              receiptInd:
                title: Receipt
                maxLength: 1
                type: string
              detailCodePayment:
                title: Payment Code
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRDEPO_DETAIL_CODE_PAYMENT, Lookup
                  lineage reference object : tbbdetc"
                x-lineageReferenceObject: TBRDEPO_DETAIL_CODE_PAYMENT
                x-lineageLookupReferenceObject: tbbdetc
              autoReleaseInd:
                title: Release
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRDEPO_AUTO_RELEASE_IND"
                x-lineageReferenceObject: TBRDEPO_AUTO_RELEASE_IND
              detailCodeDeposit:
                title: Deposit Code
                maxLength: 4
                type: string
                description: "Lineage reference object : TBRDEPO_DETAIL_CODE_DEPOSIT"
                x-lineageReferenceObject: TBRDEPO_DETAIL_CODE_DEPOSIT
              name:
                title: Name
                maxLength: 230
                type: string
              id:
                title: ID
                maxLength: 9
                type: string
              desc:
                title: Deposit Code Description
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRDEPO_DESC"
                x-lineageReferenceObject: TBRDEPO_DESC
              expirationDate:
                title: Expiration Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRDEPO_EXPIRATION_DATE"
                format: date-time
                x-lineageReferenceObject: TBRDEPO_EXPIRATION_DATE
              termCode:
                title: Term
                maxLength: 6
                type: string
                description: "Lineage reference object : TBRDEPO_TERM_CODE, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: TBRDEPO_TERM_CODE
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: tbrdepo
        key_block2:
          type: array
          items:
            type: object
            properties:
              keybloc2DetailCode:
                title: Deposit Code
                maxLength: 30
                type: string
                description: "Lineage reference object : keybloc2DetailCode"
                x-lineageReferenceObject: keybloc2DetailCode
              keybloc2Amount:
                title: Amount
                maxLength: 10
                type: number
                description: "Lineage reference object : keybloc2Amount"
                x-lineageReferenceObject: keybloc2Amount
              keybloc2AutoReleaseInd:
                title: Auto Release
                maxLength: 1
                type: string
                description: "Lineage reference object : keybloc2AutoReleaseInd"
                x-lineageReferenceObject: keybloc2AutoReleaseInd
              keybloc2DetailCodePay:
                title: Payment Code
                maxLength: 30
                type: string
                description: "Lineage reference object : keybloc2DetailCodePay, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: keybloc2DetailCodePay
                x-lineageLookupReferenceObject: tbbdetc
              keybloc2ExpirationDate:
                title: Expiration Date
                maxLength: 11
                type: string
                description: "Lineage reference object : keybloc2ExpirationDate"
                format: date-time
                x-lineageReferenceObject: keybloc2ExpirationDate
              keybloc2ReleaseDate:
                title: Release Date
                maxLength: 11
                type: string
                description: "Lineage reference object : keybloc2ReleaseDate"
                format: date-time
                x-lineageReferenceObject: keybloc2ReleaseDate
              keybloc2MinAmount:
                title: Minimum
                maxLength: 10
                type: number
                description: "Lineage reference object : keybloc2MinAmount"
                x-lineageReferenceObject: keybloc2MinAmount
              keybloc2EffDate:
                title: Effective Date
                maxLength: 11
                type: string
                description: "Lineage reference object : keybloc2EffDate"
                format: date-time
                x-lineageReferenceObject: keybloc2EffDate
              keybloc2TermCode:
                title: Term
                maxLength: 6
                type: string
                description: "Lineage reference object : keybloc2TermCode, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: keybloc2TermCode
                x-lineageLookupReferenceObject: stvterm
              keybloc2DocumentNumber:
                title: Document
                maxLength: 8
                type: string
                description: "Lineage reference object : keybloc2DocumentNumber"
                x-lineageReferenceObject: keybloc2DocumentNumber
            x-lineageReferenceObject: key_block2
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
