openapi: 3.0.1
info:
  title: direct-loan-origination-parent-plus
  description: A resource to represent information from rlrdldd, rlrdlor, rlrplus,
    rlrdbor and rlrcbid.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-source-name: RLRDLDD
  x-source-title: Direct Loan Origination Parent Plus
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Financial Aid
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-loan-origination-parent-plus:
    get:
      tags:
        - direct-loan-origination-parent-plus
      summary: Returns resources from rlrdldd, rlrdlor, rlrplus, rlrdbor and rlrcbid.
      description: Returns a paged view of the rlrdldd including data from rlrdlor,
        rlrplus, rlrdbor and rlrcbid.
      parameters:
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Must be a JSON
            representation of the properties as needed for the query.
          schema:
            type: string
            items:
              $ref: "#/components/schemas/direct-loan-origination-parent-plus_1_0_0_query_req\
                uest"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response.
              required: true
              schema:
                type: string
            X-Content-Restricted:
              description: If the resource is not a full representation of the resource,
                partial is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-origination-parent-plus_1_0_0_get_respo\
                    nse"
        "400":
          description: Failure. Bad Request. The server cannot or will not process the
            request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "401":
          description: Failure. Unauthorized
        "403":
          description: Failure. Forbidden. The user does not have the necessary
            permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "404":
          description: Failure. Not Found. Cannot map the URI to a resource.
        "405":
          description: Failure. Method Not Allowed. The client tried to use an HTTP method
            that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "406":
          description: Failure. Not Acceptable. Not able to generate any of the client’s
            preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "500":
          description: Server error, unexpected configuration or data
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
      security:
        - BasicAuth: []
          EthosIntegrationBearer: []
      x-method-permissions: API_DIR_LOAN_ORIG_PARENT_PLUS
components:
  schemas:
    direct-loan-origination-parent-plus_1_0_0_get_response:
      type: object
      properties:
        aidyCode:
          type: string
          description: rlrdldd_aidy_code
        arTranNumber:
          type: number
          description: rlrdldd_ar_tran_number
        borrowerBirthDate:
          type: string
          description: rlrcbid_birth_date
        borrowerEmail:
          type: string
          description: rlrdbor_email
        borrowerFirstName:
          type: string
          description: rlrdbor_first_name
        borrowerIdNo:
          type: string
          description: rlrplus_borrower_id_no
        borrowerLastName:
          type: string
          description: rlrcbid_last_name
        borrowerLocalAddress:
          type: string
          description: rlrdbor_local_address
        borrowerLocalAddrLine2:
          type: string
          description: rlrdbor_local_addr_line2
        borrowerLocalAddrLine3:
          type: string
          description: borrowerLocalAddrLine3
        borrowerLocalCity:
          type: string
          description: rlrdbor_local_city
        borrowerLocalCdntCode:
          type: string
          description: rlrdbor_local_cdnt_code
        borrowerLocalCdstCode:
          type: string
          description: rlrdbor_local_cdst_code
        borrowerLocalZip:
          type: string
          description: rlrdbor_local_zip
        borrowerMi:
          type: string
          description: rlrdbor_mi
        borrowerPermAddress:
          type: string
          description: rlrdbor_perm_address
        borrowerPermAddrLine2:
          type: string
          description: rlrdbor_perm_addr_line2
        borrowerPermAddrLine3:
          type: string
          description: rlrdbor_perm_addr_line3
        borrowerPermCity:
          type: string
          description: rlrdbor_perm_city
        borrowerPermCdntCode:
          type: string
          description: rlrdbor_perm_cdnt_code
        borrowerPermCdstCode:
          type: string
          description: rlrdbor_perm_cdst_code
        borrowerPermZip:
          type: string
          description: rlrdbor_perm_zip
        borrowerPhoneNo:
          type: string
          description: rlrdbor_phone_no
        borrowerSsn:
          type: string
          description: rlrcbid_ssn
        distNo:
          type: number
          description: rlrdldd_disb_no
        fundCode:
          type: string
          description: rlrdlor_fund_code
        id:
          type: string
          description: Student Banner ID from a join on rlrdldd_pidm
        loanId:
          type: string
          description: rlrdlor_loan_id
        plusAppId:
          type: number
          description: rlrplus_plus_app_id
        plusToStudent:
          type: string
          description: rlrplus_plus_to_student
        seqNo:
          type: number
          description: rlrdldd_seq_no
    direct-loan-origination-parent-plus_1_0_0_query_request:
      type: object
      properties:
        aidyCode:
          type: string
          description: rlrdldd_aidy_code
        arTranNumber:
          type: number
          description: rlrdldd_ar_tran_number
        borrowerBirthDate:
          type: string
          description: rlrcbid_birth_date
        borrowerEmail:
          type: string
          description: rlrdbor_email
        borrowerFirstName:
          type: string
          description: rlrdbor_first_name
        borrowerIdNo:
          type: string
          description: rlrplus_borrower_id_no
        borrowerLastName:
          type: string
          description: rlrcbid_last_name
        borrowerLocalAddress:
          type: string
          description: rlrdbor_local_address
        borrowerLocalAddrLine2:
          type: string
          description: rlrdbor_local_addr_line2
        borrowerLocalAddrLine3:
          type: string
          description: borrowerLocalAddrLine3
        borrowerLocalCity:
          type: string
          description: rlrdbor_local_city
        borrowerLocalCdntCode:
          type: string
          description: rlrdbor_local_cdnt_code
        borrowerLocalCdstCode:
          type: string
          description: rlrdbor_local_cdst_code
        borrowerLocalZip:
          type: string
          description: rlrdbor_local_zip
        borrowerMi:
          type: string
          description: rlrdbor_mi
        borrowerPermAddress:
          type: string
          description: rlrdbor_perm_address
        borrowerPermAddrLine2:
          type: string
          description: rlrdbor_perm_addr_line2
        borrowerPermAddrLine3:
          type: string
          description: rlrdbor_perm_addr_line3
        borrowerPermCity:
          type: string
          description: rlrdbor_perm_city
        borrowerPermCdntCode:
          type: string
          description: rlrdbor_perm_cdnt_code
        borrowerPermCdstCode:
          type: string
          description: rlrdbor_perm_cdst_code
        borrowerPermZip:
          type: string
          description: rlrdbor_perm_zip
        borrowerPhoneNo:
          type: string
          description: rlrdbor_phone_no
        borrowerSsn:
          type: string
          description: rlrcbid_ssn
        distNo:
          type: number
          description: rlrdldd_disb_no
        fundCode:
          type: string
          description: rlrdlor_fund_code
        id:
          type: string
          description: Student Banner ID from a join on rlrdldd_pidm
        loanId:
          type: string
          description: rlrdlor_loan_id
        plusAppId:
          type: number
          description: rlrplus_plus_app_id
        plusToStudent:
          type: string
          description: rlrplus_plus_to_student
        seqNo:
          type: number
          description: rlrdldd_seq_no
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EthosIntegrationBearer:
      type: http
      scheme: bearer
