openapi: 3.0.0
info:
  title: entity-name-id-search
  description: API for FTIIDEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FTIIDEN
  x-source-domain: Finance
  x-source-title: 'Entity Name/ID Search '
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/entity-name-id-search:
    get:
      tags:
      - entity-name-id-search
      summary: Return resources from FTIIDEN
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
      - name: queryVendor
        in: query
        required: false
        schema:
          type: string
      - name: queryTermVendor
        in: query
        required: false
        schema:
          type: string
      - name: queryGrntPersonnel
        in: query
        required: false
        schema:
          type: string
      - name: queryPropPersonnel
        in: query
        required: false
        schema:
          type: string
      - name: queryFinMgr
        in: query
        required: false
        schema:
          type: string
      - name: queryTermFinMgr
        in: query
        required: false
        schema:
          type: string
      - name: queryAgency
        in: query
        required: false
        schema:
          type: string
      - name: queryAll
        in: query
        required: false
        schema:
          type: string
      - name: id
        in: query
        description: ID
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SPRIDEN_ID
      - name: surnamePrefix
        in: query
        description: Last Name Prefix
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SPRIDEN_SURNAME_PREFIX
      - name: lastName
        in: query
        description: Last Name
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SPRIDEN_LAST_NAME
      - name: firstName
        in: query
        description: First Name
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SPRIDEN_FIRST_NAME
      - name: mi
        in: query
        description: Middle Name
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SPRIDEN_MI
      - name: spridenEntityInd
        in: query
        required: false
        schema:
          type: string
      - name: spridenChangeInd
        in: query
        required: false
        schema:
          type: string
      - name: entityInd
        in: query
        required: false
        schema:
          type: string
      - name: changeInd
        in: query
        required: false
        schema:
          type: string
      - name: ntypCode
        in: query
        description: Name Type
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SPRIDEN_NTYP_CODE
      - name: caseInsensitiveRg
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/entity-name-id-search-1.0.0_get_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/entity-name-id-search:
    post:
      tags:
      - entity-name-id-search QAPI (Query by POST)
      summary: Return resources from FTIIDEN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/entity-name-id-search-1.0.0_qapi_post_request"
            example:
              queryVendor: "Y"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/entity-name-id-search-1.0.0_qapi_post_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
components:
  schemas:
    entity-name-id-search-1.0.0_qapi_post_request:
      type: object
      properties:
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        spridenEntityInd:
          title: Entity Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SPRIDEN_ENTITY_IND"
          x-lineageReferenceObject: SPRIDEN_ENTITY_IND
        surnamePrefix:
          title: Last Name Prefix
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_SURNAME_PREFIX"
          x-lineageReferenceObject: SPRIDEN_SURNAME_PREFIX
        entityInd:
          maxLength: 1
          type: string
        caseInsensitiveRg:
          maxLength: 1
          type: string
          description: "Lineage reference object : caseInsensitiveRg"
          x-lineageReferenceObject: caseInsensitiveRg
        queryAgency:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryAgency"
          x-lineageReferenceObject: queryAgency
        queryAll:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryAll"
          x-lineageReferenceObject: queryAll
        queryVendor:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryVendor"
          x-lineageReferenceObject: queryVendor
        queryGrntPersonnel:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryGrntPersonnel"
          x-lineageReferenceObject: queryGrntPersonnel
        queryTermFinMgr:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryTermFinMgr"
          x-lineageReferenceObject: queryTermFinMgr
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        changeInd:
          maxLength: 1
          type: string
        ntypCode:
          title: Name Type
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
        spridenChangeInd:
          title: Change Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SPRIDEN_CHANGE_IND"
          x-lineageReferenceObject: SPRIDEN_CHANGE_IND
        queryPropPersonnel:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryPropPersonnel"
          x-lineageReferenceObject: queryPropPersonnel
        queryTermVendor:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryTermVendor"
          x-lineageReferenceObject: queryTermVendor
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        queryFinMgr:
          maxLength: 1
          type: string
          description: "Lineage reference object : queryFinMgr"
          x-lineageReferenceObject: queryFinMgr
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
      x-lineageReferenceObject: BUTTON_CONTROL_BLOCK
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
    entity-name-id-search-1.0.0_qapi_post_response:
      type: object
      properties:
        finMgrInd:
          title: Financial Manager
          maxLength: 1
          type: string
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        surnamePrefix:
          title: Last Name Prefix
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_SURNAME_PREFIX"
          x-lineageReferenceObject: SPRIDEN_SURNAME_PREFIX
        agencyInd:
          title: Agency
          maxLength: 1
          type: string
        entityInd:
          maxLength: 1
          type: string
        grantInd:
          title: Grant Personnel
          maxLength: 30
          type: string
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        changeInd:
          maxLength: 1
          type: string
        ntypCode:
          title: Name Type
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
        vendorInd:
          title: Vendor
          maxLength: 1
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
        piInd:
          title: Proposal Personnel
          maxLength: 1
          type: string
      x-lineageReferenceObject: spriden
    entity-name-id-search-1.0.0_get_response:
      type: object
      properties:
        finMgrInd:
          title: Financial Manager
          maxLength: 1
          type: string
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        surnamePrefix:
          title: Last Name Prefix
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_SURNAME_PREFIX"
          x-lineageReferenceObject: SPRIDEN_SURNAME_PREFIX
        agencyInd:
          title: Agency
          maxLength: 1
          type: string
        entityInd:
          maxLength: 1
          type: string
        grantInd:
          title: Grant Personnel
          maxLength: 30
          type: string
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        changeInd:
          maxLength: 1
          type: string
        ntypCode:
          title: Name Type
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
        vendorInd:
          title: Vendor
          maxLength: 1
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
        piInd:
          title: Proposal Personnel
          maxLength: 1
          type: string
      x-lineageReferenceObject: spriden
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer