openapi: 3.0.0
info:
  title: deposit-type-codes
  description: API for TTVDTYP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TTVDTYP
  x-source-domain: Student
  x-source-title: Deposit Type Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/deposit-type-codes:
    get:
      tags:
        - deposit-type-codes
      summary: Return resources from TTVDTYP
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        - name: code
          in: query
          description: Deposit Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TTVDTYP_CODE
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TTVDTYP_DESC
        - name: sysreqInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/deposit-type-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - deposit-type-codes
      summary: Updates an existing resource in TTVDTYP
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/deposit-type-codes-1.0.0_put_request"
            example:
              criteria.code: AP4
              sysreqInd: Y
              desc: test ap4
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/deposit-type-codes-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - deposit-type-codes
      summary: Creates a new resource in TTVDTYP
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/deposit-type-codes-1.0.0_post_request"
            example:
              code: AP4
              desc: Test API Four
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/deposit-type-codes-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/deposit-type-codes:
    post:
      tags:
        - deposit-type-codes QAPI (Query by POST)
      summary: Return resources from TTVDTYP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/deposit-type-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/deposit-type-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    deposit-type-codes-1.0.0_put_request:
      required:
        - criteria.code
        - criteria.desc
        - desc
      type: object
      properties:
        criteria.code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        criteria.activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVDTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        criteria.sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        criteria.desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
      x-lineageReferenceObject: TTVDTYP
    deposit-type-codes-1.0.0_qapi_post:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVDTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    deposit-type-codes-1.0.0_put_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVDTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
      x-lineageReferenceObject: ttvdtyp
    deposit-type-codes-1.0.0_post_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVDTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
      x-lineageReferenceObject: ttvdtyp
    deposit-type-codes-1.0.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVDTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
      x-lineageReferenceObject: ttvdtyp
    deposit-type-codes-1.0.0_get_request:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVDTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVDTYP_ACTIVITY_DATE
        code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
      x-lineageReferenceObject: TTVDTYP
    deposit-type-codes-1.0.0_post_request:
      required:
        - code
        - desc
      type: object
      properties:
        code:
          title: Deposit Type
          maxLength: 3
          type: string
          description: "Lineage reference object : TTVDTYP_CODE"
          x-lineageReferenceObject: TTVDTYP_CODE
        sysreqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TTVDTYP_SYSREQ_IND"
          x-lineageReferenceObject: TTVDTYP_SYSREQ_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVDTYP_DESC"
          x-lineageReferenceObject: TTVDTYP_DESC
      x-lineageReferenceObject: TTVDTYP
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
