openapi: 3.0.0
info:
  title: Buyers
  description: Purchasing agents for an institution. The API publishes the
    information on purchasing agents for an institution, whose duties may
    include ordering, bid processing, etc.
  version: "10.1.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Finance
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/buyers:
    get:
      summary: Returns all resources from FTVBUYR
      description: Returns all buyers records from FTVBUYR table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_BUYERS
      tags:
        - buyers
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v10.1.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set. The
            default limit is 500 and the maximum limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: |
            ### Code  
            A code that may be used to identify the buyer.
            ```
            /buyers?criteria={"code":"SUPP"}
            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-buyers.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v10.1.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/buyers/{id}:
    get:
      summary: Returns the requested resource from FTVBUYR
      description: Returns one buyer record from FTVBUYR table with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_BUYERS
      tags:
        - buyers
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Buyers for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v10.1.0+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v10.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v10.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-buyers.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-buyers.json:
      title: Buyers
      description: Purchasing agents for an institution.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the buyer.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: FTVBUYR_GUID(FTVBUYR)
        code:
          title: Code
          description: A code that may be used to identify the buyer.
          type: string
          x-lineageReferenceObject: FTVBUYR_CODE(FTVBUYR)
        buyer:
          title: Buyer
          description: The name or detail information of the buyer.
          oneOf:
            - title: name
              description: The name of the buyer.
              type: object
              properties:
                name:
                  title: Name
                  description: The name of the buyer.
                  type: string
                  minLength: 1
                  x-lineageReferenceObject: FTVBUYR(FTVBUYR)
              additionalProperties: false
              required:
                - name
            - title: person
              description: The individual who is the buyer.
              type: object
              properties:
                person:
                  title: Person
                  description: The individual who is the buyer.
                  type: object
                  properties:
                    id:
                      title: ID
                      description: The global identifier for the Person.
                      type: string
                      format: guid
                      pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                      x-lineageLookupReferenceObject: persons 
                      x-lineageReferenceObject: unsupported
                  additionalProperties: false
                  required:
                    - id
              additionalProperties: false
              required:
                - person
        startOn:
          title: Start On
          description: The earliest date when the buyer is active.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: FTVBUYR_EFF_DATE(FTVBUYR)
            - type: string
              maxLength: 0
        endOn:
          title: End On
          description: The last date when the buyer was active.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: FTVBUYR_TERM_DATE(FTVBUYR)
            - type: string
              maxLength: 0
        phone:
          title: Phone
          description: The phone number of the buyer.
          oneOf:
            - type: object
              properties:
                number:
                  title: Number
                  description: The number assigned to the phone.
                  type: string
                  minLength: 1
                  x-lineageReferenceObject: FTVBUYR_CTRY_CODE_PHONE(FTVBUYR) and FTVBUYR_PHONE_AREA(FTVBUYR) and FTVBUYR_PHONE_NUMBER(FTVBUYR)
                extension:
                  title: Extension
                  description: The extension used to connect to the phone when multiple phones
                    share the same primary number.
                  type: string
                  x-lineageReferenceObject: FTVBUYR_EXTENSION(FTVBUYR)
              additionalProperties: false
              required:
                - number
            - type: object
              maxProperties: 0
        purchasingLimit:
          title: Purchasing Limit
          description: The maximum amount of a purchase order to which a buyer may be
            assigned (i.e. LVPO - low value purchase order).
          oneOf:
            - type: object
              format: currency
              properties:
                value:
                  title: Value
                  description: The monetary value
                  type: number
                  x-lineageReferenceObject: FTVBUYR_LVPO_LIMIT(FTVBUYR)
                currency:
                  title: Currency
                  description: The ISO 4217 currency code
                  x-lineageReferenceObject: derived
                  x-lineageDerivedLogic: ISO code for GUBINST_BASE_CURR(GUBINST)
                  enum:
                    - AED
                    - AFN
                    - ALL
                    - AMD
                    - ANG
                    - AOA
                    - ARS
                    - AUD
                    - AWG
                    - AZN
                    - BAM
                    - BBD
                    - BDT
                    - BGN
                    - BHD
                    - BIF
                    - BMD
                    - BND
                    - BOB
                    - BRL
                    - BSD
                    - BTN
                    - BWP
                    - BYR
                    - BZD
                    - CAD
                    - CDF
                    - CHF
                    - CLP
                    - CNY
                    - COP
                    - CRC
                    - CUC
                    - CUP
                    - CVE
                    - CZK
                    - DJF
                    - DKK
                    - DOP
                    - DZD
                    - EGP
                    - ERN
                    - ETB
                    - EUR
                    - FJD
                    - FKP
                    - GBP
                    - GEL
                    - GHS
                    - GIP
                    - GMD
                    - GNF
                    - GTQ
                    - GYD
                    - HKD
                    - HNL
                    - HRK
                    - HTG
                    - HUF
                    - IDR
                    - ILS
                    - INR
                    - IQD
                    - IRR
                    - ISK
                    - JMD
                    - JOD
                    - JPY
                    - KES
                    - KGS
                    - KHR
                    - KMF
                    - KPW
                    - KRW
                    - KWD
                    - KYD
                    - KZT
                    - LAK
                    - LBP
                    - LKR
                    - LRD
                    - LSL
                    - LYD
                    - MAD
                    - MDL
                    - MGA
                    - MKD
                    - MMK
                    - MNT
                    - MOP
                    - MRO
                    - MUR
                    - MVR
                    - MWK
                    - MXN
                    - MYR
                    - MZN
                    - NAD
                    - NGN
                    - NIO
                    - NOK
                    - NPR
                    - NZD
                    - OMR
                    - PAB
                    - PEN
                    - PGK
                    - PHP
                    - PKR
                    - PLN
                    - PYG
                    - QAR
                    - RON
                    - RSD
                    - RUB
                    - RWF
                    - SAR
                    - SBD
                    - SCR
                    - SDG
                    - SEK
                    - SGD
                    - SHP
                    - SLL
                    - SOS
                    - SRD
                    - SSP
                    - STD
                    - SVC
                    - SYP
                    - SZL
                    - THB
                    - TJS
                    - TMT
                    - TND
                    - TOP
                    - TRY
                    - TTD
                    - TWD
                    - TZS
                    - UAH
                    - UGX
                    - USD
                    - UYU
                    - UZS
                    - VEF
                    - VND
                    - VUV
                    - WST
                    - XAF
                    - XCD
                    - XOF
                    - XPF
                    - YER
                    - ZAR
                    - ZMW
                    - ZWL
                  type: string
              additionalProperties: false
              required:
                - value
                - currency
            - type: object
              maxProperties: 0
        status:
          title: Status
          description: An indication of the buyer's status.
          x-lineageReferenceObject: derived  
          x-lineageDerivedLogic: If SYSDATE falls between start and end dates, display status as 'active', else display status as 'inactive'.
          oneOf:
            - type: string
              enum:
                - active
                - inactive
            - type: string
              maxLength: 0
      required:
        - id
        - buyer
      additionalProperties: false
