openapi: 3.0.0
info:
  title: Academic Credentials
  description: |
    An award that recognizes the completion of a specified course of study.
  version: "6.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/academic-credentials:
    get:
      summary: Returns resources from STVDPLM and STVDEGC
      description: >
        Returns a paged listing of all the academic credential records from
        STVDPLM and STVDEGC tables.


        The academic credential records of type diploma are retrieved from STVDPLM table. The academic credential records of type degree, honorary and certificate are retrieved from STVDEGC table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_CREDENTIALS
      tags:
        - academic-credentials
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Type  

            Returns all academic credentials for the specific credential type i.e. degree, honorary, diploma, certificate passed.

            ```

            /api/academic-credentials?type=degree

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-academic-credentials.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource in STVDPLM and STVDEGC
      description: >
        POST requests must include a nil GUID value
        ("00000000-0000-0000-0000-000000000000") for the root id property.


        In addition to the required properties defined in the data model, the following are required for a POST request: abbreviation


        Creates a new academic credentials record.


        If 'type' property in the POST request is sent as diploma, then the academic credential record in created in STVDPLM table. If 'type' property in the POST request is sent as degree, honorary or certificate, then the academic credential record in created in STVDEGC table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_CREDENTIALS
      tags:
        - academic-credentials
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-credentials.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-academic-credentials.json"
  /api/academic-credentials/{id}:
    get:
      summary: Return the requested resource
      description: >
        Returns a single academic credential record with the requested
        identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_CREDENTIALS
      tags:
        - academic-credentials
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-credentials.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource
      description: >
        Updates an existing academic credential record with the passed in
        identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_CREDENTIALS
      tags:
        - academic-credentials
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Academic Credentials for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-credentials.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-academic-credentials.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-academic-credentials.json:
      title: Academic Credentials
      description: An award that recognizes the completion of a specified course of study.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: A global identifier for an academic degree.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GORGUID_GUID(LDM_NAME= academic-credentials) 
          x-lineageDerivedLogic: where gorguid_ldm_name = 'academic-credentials' and gorguid_domain_key = STVDEGC_CODE
        title:
          title: Title
          description: The full name of an academic degree.
          type: string
          minLength: 1
          x-lineageReferenceObject: STVDEGC_DESC(STVDEGC) or STVDPLM_DESC(STVDPLM)
        abbreviation:
          title: Abbreviation
          description: An abbreviation used to identify an academic degree.
          type: string
          x-lineageReferenceObject: STVDEGC_CODE(STVDEGC) or STVDPLM_CODE(STVDPLM)
        description:
          title: Description
          description: A full description of an academic degree.
          type: string
          x-lineageReferenceObject: GORSDAV_VALUE(GORSDAV)
          x-lineageDerivedLogic: where GORSDAV_TABLE_NAME = 'STVDEGC' and GORSDAV_ATTR_NAME = 'HEDM_CREDENTIAL_DESCRIPTION' and GORSDAV_PK_PARENTTAB = STVDEGC_CODE
        type:
          title: Type
          description: A type of academic degree.
          x-lineageReferenceObject: GORSDAV_VALUE(GORSDAV)
          x-lineageDerivedLogic: where GORSDAV_TABLE_NAME = 'STVDEGC' and GORSDAV_ATTR_NAME = 'HEDM_CREDENTIAL_CATGORY' and GORSDAV_PK_PARENTTAB = STVDEGC_CODE
          enum:
            - degree
            - honorary
            - diploma
            - certificate
          type: string
      required:
        - id
        - title
        - type
      additionalProperties: false
