openapi: 3.0.0
info:
  title: applicant-requirements-direct-loan-mpns
  description: API for RRAAREQ administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: RRAAREQ
  x-source-domain: Financial Aid
  x-source-title: Applicant Requirements
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-requirements-direct-loan-mpns:
    get:
      tags:
        - applicant-requirements-direct-loan-mpns
      summary: Return resources from RRAAREQ
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckId
          in: query
          required: false
          schema:
            type: string
        - name: mpnType
          in: query
          description: MPN Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_MPN_TYPE
        - name: reqStatus
          in: query
          description: Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS
        - name: reqStatusDate
          in: query
          description: Status Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS_DATE
        - name: loanNo
          in: query
          description: Loan Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_LOAN_NO
        - name: rlrdlorFundCode
          in: query
          description: Fund Code
          required: false
          schema:
            type: string
        - name: fundTitle
          in: query
          required: false
          schema:
            type: string
        - name: instructions
          in: query
          description: Instructions
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_INSTRUCTIONS
        - name: satInd
          in: query
          description: Satisfied
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_SAT_IND
        - name: infoAccessInd
          in: query
          description: Information Access
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_INFO_ACCESS_IND
        - name: trkLtrInd
          in: query
          description: Letter
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RLRDMPR_TRK_LTR_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-requirements-direct-loan-mpns-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-requirements-direct-loan-mpns:
    post:
      tags:
        - applicant-requirements-direct-loan-mpns QAPI (Query by POST)
      summary: Return resources from RRAAREQ
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-requirements-direct-loan-mpns-1.0.0_get_r\
                equest"
            example:
              keyblckAidyCode: 2122
              keyblckId: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-requirements-direct-loan-mpns-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    applicant-requirements-direct-loan-mpns-1.0.0_qapi_post:
      type: object
      properties:
        keyblckAidyCode:
          type: string
        keyblckId:
          type: string
        mpnType:
          title: MPN Type
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRDMPR_MPN_TYPE"
          x-lineageReferenceObject: RLRDMPR_MPN_TYPE
        reqStatus:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRDMPR_REQ_STATUS"
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS
        reqStatusDate:
          title: Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RLRDMPR_REQ_STATUS_DATE"
          format: date-time
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS_DATE
        loanNo:
          title: Loan Number
          maxLength: 4
          type: number
          description: "Lineage reference object : RLRDMPR_LOAN_NO"
          x-lineageReferenceObject: RLRDMPR_LOAN_NO
        rlrdlorFundCode:
          title: Fund Code
          maxLength: 6
          type: string
        fundTitle:
          type: string
        instructions:
          title: Instructions
          type: string
          description: "Lineage reference object : RLRDMPR_INSTRUCTIONS"
          x-lineageReferenceObject: RLRDMPR_INSTRUCTIONS
        satInd:
          title: Satisfied
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_SAT_IND"
          x-lineageReferenceObject: RLRDMPR_SAT_IND
        infoAccessInd:
          title: Information Access
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_INFO_ACCESS_IND"
          x-lineageReferenceObject: RLRDMPR_INFO_ACCESS_IND
        trkLtrInd:
          title: Letter
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_TRK_LTR_IND"
          x-lineageReferenceObject: RLRDMPR_TRK_LTR_IND
    applicant-requirements-direct-loan-mpns-1.0.0_get_request:
      required:
        - reqStatusDate
        - loanNo
        - rlrdlorFundCode
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        instructions:
          title: Instructions
          type: string
          description: "Lineage reference object : RLRDMPR_INSTRUCTIONS"
          x-lineageReferenceObject: RLRDMPR_INSTRUCTIONS
        keyblckId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : keyblckId"
          x-lineageReferenceObject: keyblckId
        fundTitle:
          type: string
        reqStatus:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRDMPR_REQ_STATUS"
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS
        satInd:
          title: Satisfied
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_SAT_IND"
          x-lineageReferenceObject: RLRDMPR_SAT_IND
        loanNo:
          title: Loan Number
          maxLength: 4
          type: number
          description: "Lineage reference object : RLRDMPR_LOAN_NO"
          x-lineageReferenceObject: RLRDMPR_LOAN_NO
        rlrdlorFundCode:
          title: Fund Code
          maxLength: 6
          type: string
        infoAccessInd:
          title: Information Access
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_INFO_ACCESS_IND"
          x-lineageReferenceObject: RLRDMPR_INFO_ACCESS_IND
        trkLtrInd:
          title: Letter
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_TRK_LTR_IND"
          x-lineageReferenceObject: RLRDMPR_TRK_LTR_IND
        mpnType:
          title: MPN Type
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRDMPR_MPN_TYPE"
          x-lineageReferenceObject: RLRDMPR_MPN_TYPE
        reqStatusDate:
          title: Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RLRDMPR_REQ_STATUS_DATE"
          format: date-time
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS_DATE
      x-lineageReferenceObject: RLRDMPR
    applicant-requirements-direct-loan-mpns-1.0.0_get_response:
      required:
        - rlrdlorFundCode
        - loanNo
        - reqStatusDate
      type: object
      properties:
        instructions:
          title: Instructions
          type: string
          description: "Lineage reference object : RLRDMPR_INSTRUCTIONS"
          x-lineageReferenceObject: RLRDMPR_INSTRUCTIONS
        fundTitle:
          type: string
        reqStatus:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRDMPR_REQ_STATUS"
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS
        satInd:
          title: Satisfied
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_SAT_IND"
          x-lineageReferenceObject: RLRDMPR_SAT_IND
        loanNo:
          title: Loan Number
          maxLength: 4
          type: number
          description: "Lineage reference object : RLRDMPR_LOAN_NO"
          x-lineageReferenceObject: RLRDMPR_LOAN_NO
        rlrdlorFundCode:
          title: Fund Code
          maxLength: 6
          type: string
        infoAccessInd:
          title: Information Access
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_INFO_ACCESS_IND"
          x-lineageReferenceObject: RLRDMPR_INFO_ACCESS_IND
        trkLtrInd:
          title: Letter
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDMPR_TRK_LTR_IND"
          x-lineageReferenceObject: RLRDMPR_TRK_LTR_IND
        mpnType:
          title: MPN Type
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRDMPR_MPN_TYPE"
          x-lineageReferenceObject: RLRDMPR_MPN_TYPE
        reqStatusDate:
          title: Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RLRDMPR_REQ_STATUS_DATE"
          format: date-time
          x-lineageReferenceObject: RLRDMPR_REQ_STATUS_DATE
      x-lineageReferenceObject: rlrdmpr
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
