openapi: 3.0.0
info:
  title: system-control-fiscal-years
  description: API for FTVFSYR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FTVFSYR
  x-source-domain: Finance
  x-source-title: System Control Fiscal Year Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/system-control-fiscal-years:
    get:
      tags:
        - system-control-fiscal-years
      summary: Return resources from FTVFSYR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: currentPeriod
          in: query
          description: Periods
          required: false
          schema:
            type: string
        - name: earliestOpenPeriod
          in: query
          description: First Open Period
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          description: Last Activity
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVFSYR_ACTIVITY_DATE
        - name: coasCode
          in: query
          description: COA
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVFSYR_COAS_CODE
        - name: endDate
          in: query
          description: End Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVFSYR_END_DATE
        - name: eoyAccrStatusInd
          in: query
          description: Accrual Period Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVFSYR_EOY_ACCR_STATUS_IND
        - name: fsyrCode
          in: query
          description: Fiscal Year
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVFSYR_FSYR_CODE
        - name: startDate
          in: query
          description: Start Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVFSYR_START_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/system-control-fiscal-years-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/system-control-fiscal-years:
    post:
      tags:
        - system-control-fiscal-years QAPI (Query by POST)
      summary: Return resources from FTVFSYR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/system-control-fiscal-years-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/system-control-fiscal-years-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    system-control-fiscal-years-1.0.0_get_response:
      type: object
      properties:
        earliestOpenPeriod:
          title: First Open Period
          maxLength: 2
          type: string
        currentPeriodStartDate:
          title: Start Date
          maxLength: 11
          type: string
          format: date-time
        activityDate:
          title: Last Activity
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_ACTIVITY_DATE
        eoyAccrStatusInd:
          title: Accrual Period Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVFSYR_EOY_ACCR_STATUS_IND"
          x-lineageReferenceObject: FTVFSYR_EOY_ACCR_STATUS_IND
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_END_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_END_DATE
        currentPeriodEndDate:
          title: End Date
          maxLength: 11
          type: string
          format: date-time
        fsyrCode:
          title: Fiscal Year
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVFSYR_FSYR_CODE"
          x-lineageReferenceObject: FTVFSYR_FSYR_CODE
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVFSYR_COAS_CODE"
          x-lineageReferenceObject: FTVFSYR_COAS_CODE
        currentPeriod:
          title: Periods
          maxLength: 2
          type: string
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_START_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_START_DATE
      x-lineageReferenceObject: ftvfsyr
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    system-control-fiscal-years-1.0.0_qapi_post:
      type: object
      properties:
        currentPeriod:
          title: Periods
          maxLength: 2
          type: string
        earliestOpenPeriod:
          title: First Open Period
          maxLength: 2
          type: string
        activityDate:
          title: Last Activity
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_ACTIVITY_DATE
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVFSYR_COAS_CODE"
          x-lineageReferenceObject: FTVFSYR_COAS_CODE
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_END_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_END_DATE
        eoyAccrStatusInd:
          title: Accrual Period Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVFSYR_EOY_ACCR_STATUS_IND"
          x-lineageReferenceObject: FTVFSYR_EOY_ACCR_STATUS_IND
        fsyrCode:
          title: Fiscal Year
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVFSYR_FSYR_CODE"
          x-lineageReferenceObject: FTVFSYR_FSYR_CODE
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_START_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_START_DATE
    system-control-fiscal-years-1.0.0_get_request:
      type: object
      properties:
        earliestOpenPeriod:
          title: First Open Period
          maxLength: 2
          type: string
        activityDate:
          title: Last Activity
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_ACTIVITY_DATE
        eoyAccrStatusInd:
          title: Accrual Period Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVFSYR_EOY_ACCR_STATUS_IND"
          x-lineageReferenceObject: FTVFSYR_EOY_ACCR_STATUS_IND
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_END_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_END_DATE
        fsyrCode:
          title: Fiscal Year
          maxLength: 2
          type: string
          description: "Lineage reference object : FTVFSYR_FSYR_CODE"
          x-lineageReferenceObject: FTVFSYR_FSYR_CODE
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVFSYR_COAS_CODE"
          x-lineageReferenceObject: FTVFSYR_COAS_CODE
        currentPeriod:
          title: Periods
          maxLength: 2
          type: string
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVFSYR_START_DATE"
          format: date-time
          x-lineageReferenceObject: FTVFSYR_START_DATE
      x-lineageReferenceObject: FTVFSYR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
