openapi: 3.0.0
info:
  title: batch-update-of-delinquencies
  description: API for GJAPCTL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: GJAPCTL
  x-source-domain: Foundation
  x-source-title: Process Submission Controls
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/batch-update-of-delinquencies:
    put:
      tags:
        - batch-update-of-delinquencies
      summary: Updates an existing resource in GJAPCTL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/batch-update-of-delinquencies-1.0.0_put_request"
            example:
              value6: 1
              displayPrntCode: DATABASE
              value8: 1
              value4: 1
              keyblckJob: TGRDELI
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/batch-update-of-delinquencies-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/batch-update-of-delinquencies: {}
components:
  schemas:
    batch-update-of-delinquencies-1.0.0_put_response:
      type: object
      properties:
        jprmCode:
          title: Parameter Set
          maxLength: 15
          type: string
          description: "Lineage reference object : jprmCode"
          x-lineageReferenceObject: jprmCode
        jobTitle:
          maxLength: 30
          type: string
          description: "Lineage reference object : jobTitle"
          x-lineageReferenceObject: jobTitle
        keyblckJob:
          title: Process
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckJob"
          x-lineageReferenceObject: keyblckJob
      x-lineageReferenceObject: key_block
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    batch-update-of-delinquencies-1.0.0_put_request:
      required:
        - number1
        - number2
        - number3
        - number4
        - number5
        - number6
        - number7
        - number8
        - number9
        - number10
        - number11
        - number12
        - number13
      type: object
      properties:
        value6:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value5:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value8:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value7:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value2:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value1:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value4:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value3:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        displayPrntForm:
          title: Special Print
          maxLength: 30
          type: string
          description: "Lineage reference object : displayPrntForm"
          x-lineageReferenceObject: displayPrntForm
        number3:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number4:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number1:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number2:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        displayLineCount:
          title: Lines
          maxLength: 3
          description: "Lineage reference object : displayLineCount"
          x-lineageReferenceObject: displayLineCount
        number7:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number8:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        value9:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        number5:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number6:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        jprmCode:
          title: Parameter Set
          maxLength: 15
          type: string
          description: "Lineage reference object : jprmCode"
          x-lineageReferenceObject: jprmCode
        number9:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        displayPdfFont:
          title: PDF Font
          maxLength: 30
          type: string
          description: "Lineage reference object : displayPdfFont, Lookup lineage
            reference object : gtvpdft"
          x-lineageReferenceObject: displayPdfFont
          x-lineageLookupReferenceObject: gtvpdft
        displaySubmitTime:
          title: Submit Time
          maxLength: 5
          type: string
          description: "Lineage reference object : displaySubmitTime"
          x-lineageReferenceObject: displaySubmitTime
        displayFontSize:
          title: PDF Font Size
          maxLength: 2
          description: "Lineage reference object : displayFontSize"
          x-lineageReferenceObject: displayFontSize
        value11:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value10:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        value13:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        keyblckJob:
          title: Process
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckJob"
          x-lineageReferenceObject: keyblckJob
        value12:
          title: Values
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPRUN_VALUE, Lookup lineage reference
            object : gjbpval"
          x-lineageReferenceObject: GJBPRUN_VALUE
          x-lineageLookupReferenceObject: gjbpval
        number13:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number12:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number11:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        number10:
          title: Number
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPRUN_NUMBER"
          x-lineageReferenceObject: GJBPRUN_NUMBER
        displayPrntCode:
          title: Printer
          maxLength: 30
          type: string
          description: "Lineage reference object : displayPrntCode, Lookup lineage
            reference object : gtvprnt"
          x-lineageReferenceObject: displayPrntCode
          x-lineageLookupReferenceObject: gtvprnt
        displaySubmitInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : displaySubmitInd"
          x-lineageReferenceObject: displaySubmitInd
        displaySaveDefaults:
          title: Save Parameter Set as
          maxLength: 1
          type: string
          description: "Lineage reference object : displaySaveDefaults"
          x-lineageReferenceObject: displaySaveDefaults
        displayStorageDays:
          title: Delete After Days
          maxLength: 4
          description: "Lineage reference object : displayStorageDays"
          x-lineageReferenceObject: displayStorageDays
      x-lineageReferenceObject: SUBMIT_BLK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
