openapi: 3.0.0
info:
  title: applicant-requirements-perkins-mpn-detail
  description: API for RRAAREQ administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: RRAAREQ
  x-source-domain: Financial Aid
  x-source-title: Applicant Requirements
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-requirements-perkins-mpn-detail:
    get:
      tags:
        - applicant-requirements-perkins-mpn-detail
      summary: Return resources from RRAAREQ
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckId
          in: query
          required: false
          schema:
            type: string
        - name: displayActive
          in: query
          description: Active/Inactive Indicator
          required: false
          schema:
            type: string
        - name: rrrareqMpnFirstDisbDate
          in: query
          description: MPN First Disbursement Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_MPN_FIRST_DISB_DATE
        - name: rrrareqFundCode
          in: query
          description: Fund
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_FUND_CODE
        - name: rfrbaseFundTitle
          in: query
          required: false
          schema:
            type: string
        - name: rrrareqEstDate
          in: query
          description: Established Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_EST_DATE
        - name: rrrareqTreqCode
          in: query
          description: Requirement
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_TREQ_CODE
        - name: rrrareqTreqDesc
          in: query
          required: false
          schema:
            type: string
        - name: rrrareqStatDate
          in: query
          description: Requirement Status Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_STAT_DATE
        - name: rrrareqTrstCode
          in: query
          description: Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_TRST_CODE
        - name: rrrareqMpnSignedDate
          in: query
          description: Signed Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_MPN_SIGNED_DATE
        - name: rrrareqSatInd
          in: query
          description: Satisfied
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_SAT_IND
        - name: rrrareqSatisfiedDate
          in: query
          description: Satisfied Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_SATISFIED_DATE
        - name: rrrareqPerkMpnExpDate
          in: query
          description: Expiration Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RRRAREQ_PERK_MPN_EXP_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-requirements-perkins-mpn-detail-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-requirements-perkins-mpn-detail:
    post:
      tags:
        - applicant-requirements-perkins-mpn-detail QAPI (Query by POST)
      summary: Return resources from RRAAREQ
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-requirements-perkins-mpn-detail-1.0.0_get\
                _request"
            example:
              keyblckAidyCode: 2122
              keyblckId: A00030988
              rrrareqTreqCode: AJEXIT
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-requirements-perkins-mpn-detail-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    applicant-requirements-perkins-mpn-detail-1.0.0_qapi_post:
      type: object
      properties:
        keyblckAidyCode:
          type: string
        keyblckId:
          type: string
        displayActive:
          title: Active/Inactive Indicator
          type: string
        rrrareqMpnFirstDisbDate:
          title: MPN First Disbursement Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_MPN_FIRST_DISB_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_MPN_FIRST_DISB_DATE
        rrrareqFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_FUND_CODE"
          x-lineageReferenceObject: RRRAREQ_FUND_CODE
        rfrbaseFundTitle:
          type: string
        rrrareqEstDate:
          title: Established Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_EST_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_EST_DATE
        rrrareqTreqCode:
          title: Requirement
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_TREQ_CODE"
          x-lineageReferenceObject: RRRAREQ_TREQ_CODE
        rrrareqTreqDesc:
          type: string
        rrrareqStatDate:
          title: Requirement Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_STAT_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_STAT_DATE
        rrrareqTrstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_TRST_CODE, Lookup lineage
            reference object : rtvtrst"
          x-lineageReferenceObject: RRRAREQ_TRST_CODE
          x-lineageLookupReferenceObject: rtvtrst
        rrrareqMpnSignedDate:
          title: Signed Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_MPN_SIGNED_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_MPN_SIGNED_DATE
        rrrareqSatInd:
          title: Satisfied
          maxLength: 1
          type: string
          description: "Lineage reference object : RRRAREQ_SAT_IND"
          x-lineageReferenceObject: RRRAREQ_SAT_IND
        rrrareqSatisfiedDate:
          title: Satisfied Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_SATISFIED_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_SATISFIED_DATE
        rrrareqPerkMpnExpDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_PERK_MPN_EXP_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_PERK_MPN_EXP_DATE
    applicant-requirements-perkins-mpn-detail-1.0.0_get_request:
      type: object
      properties:
        rrrareqEstDate:
          title: Established Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_EST_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_EST_DATE
        rrrareqTreqCode:
          title: Requirement
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_TREQ_CODE"
          x-lineageReferenceObject: RRRAREQ_TREQ_CODE
        rrrareqPerkMpnExpDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_PERK_MPN_EXP_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_PERK_MPN_EXP_DATE
        displayActive:
          title: Active/Inactive Indicator
          type: string
        rrrareqFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_FUND_CODE"
          x-lineageReferenceObject: RRRAREQ_FUND_CODE
        rrrareqTreqDesc:
          type: string
        rrrareqTrstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_TRST_CODE, Lookup lineage
            reference object : rtvtrst"
          x-lineageReferenceObject: RRRAREQ_TRST_CODE
          x-lineageLookupReferenceObject: rtvtrst
        rrrareqSatisfiedDate:
          title: Satisfied Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_SATISFIED_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_SATISFIED_DATE
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        keyblckId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : keyblckId"
          x-lineageReferenceObject: keyblckId
        rfrbaseFundTitle:
          type: string
        rrrareqStatDate:
          title: Requirement Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_STAT_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_STAT_DATE
        rrrareqSatInd:
          title: Satisfied
          maxLength: 1
          type: string
          description: "Lineage reference object : RRRAREQ_SAT_IND"
          x-lineageReferenceObject: RRRAREQ_SAT_IND
        rrrareqMpnFirstDisbDate:
          title: MPN First Disbursement Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_MPN_FIRST_DISB_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_MPN_FIRST_DISB_DATE
        rrrareqMpnSignedDate:
          title: Signed Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_MPN_SIGNED_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_MPN_SIGNED_DATE
      x-lineageReferenceObject: RRRAREQ_3
    applicant-requirements-perkins-mpn-detail-1.0.0_get_response:
      type: object
      properties:
        rrrareqEstDate:
          title: Established Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_EST_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_EST_DATE
        rrrareqTreqCode:
          title: Requirement
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_TREQ_CODE"
          x-lineageReferenceObject: RRRAREQ_TREQ_CODE
        rrrareqPerkMpnExpDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_PERK_MPN_EXP_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_PERK_MPN_EXP_DATE
        displayActive:
          title: Active/Inactive Indicator
          type: string
        rrrareqFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_FUND_CODE"
          x-lineageReferenceObject: RRRAREQ_FUND_CODE
        rrrareqTreqDesc:
          type: string
        rrrareqTrstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RRRAREQ_TRST_CODE, Lookup lineage
            reference object : rtvtrst"
          x-lineageReferenceObject: RRRAREQ_TRST_CODE
          x-lineageLookupReferenceObject: rtvtrst
        rrrareqSatisfiedDate:
          title: Satisfied Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_SATISFIED_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_SATISFIED_DATE
        rfrbaseFundTitle:
          type: string
        rrrareqStatDate:
          title: Requirement Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_STAT_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_STAT_DATE
        rrrareqSatInd:
          title: Satisfied
          maxLength: 1
          type: string
          description: "Lineage reference object : RRRAREQ_SAT_IND"
          x-lineageReferenceObject: RRRAREQ_SAT_IND
        rrrareqMpnFirstDisbDate:
          title: MPN First Disbursement Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_MPN_FIRST_DISB_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_MPN_FIRST_DISB_DATE
        rtvtrstDesc:
          type: string
        rrrareqMpnSignedDate:
          title: Signed Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RRRAREQ_MPN_SIGNED_DATE"
          format: date-time
          x-lineageReferenceObject: RRRAREQ_MPN_SIGNED_DATE
      x-lineageReferenceObject: rrrareq_3
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
