openapi: 3.0.0
info:
  title: account-review-form-contracts
  description: API for TSAACCT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: TSAACCT
  x-source-domain: Student
  x-source-title: Account Review Form - Student
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/account-review-form-contracts:
    put:
      tags:
        - account-review-form-contracts
      summary: Updates an existing resource in TSAACCT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/account-review-form-contracts-1.0.0_put_request"
            example:
              authInd: Y
              criteria.authNumber: "1"
              stspKeySequence: "99"
              criteria.contractNumber: "1"
              criteria.tbbcstuDelInd: D
              tbbcstuMaxStudentAmount: "1000"
              studentContRollInd: N
              criteria.studentContRollInd: Y
              criteria.contractPriority: "1"
              contractPriority: "3"
              criteria.authInd: N
              criteria.tbbcstuMaxStudentAmount: "500"
              authNumber: "2"
              id: "210009103"
              criteria.tbbcstuTermCode: "201410"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/account-review-form-contracts-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/account-review-form-contracts: {}
components:
  schemas:
    account-review-form-contracts-1.0.0_put_response:
      required:
        - contId
        - contractNumber
        - contractPriority
        - termCode
      type: object
      properties:
        contractPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBCSTU_CONTRACT_PRIORITY"
          x-lineageReferenceObject: TBBCSTU_CONTRACT_PRIORITY
        authInd:
          title: Authorization
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_AUTH_IND"
          x-lineageReferenceObject: TBBCSTU_AUTH_IND
        contId:
          title: ID
          maxLength: 9
          type: string
        delInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_DEL_IND"
          x-lineageReferenceObject: TBBCSTU_DEL_IND
        stspKeySequence:
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBCSTU_STSP_KEY_SEQUENCE"
          x-lineageReferenceObject: TBBCSTU_STSP_KEY_SEQUENCE
        contDescription:
          title: Description
          maxLength: 30
          type: string
        maxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBCSTU_MAX_STUDENT_AMOUNT"
          x-lineageReferenceObject: TBBCSTU_MAX_STUDENT_AMOUNT
        studentContRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_STUDENT_CONT_ROLL_IND"
          x-lineageReferenceObject: TBBCSTU_STUDENT_CONT_ROLL_IND
        contName:
          maxLength: 230
          type: string
        authNumber:
          title: Authorization Number
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBCSTU_AUTH_NUMBER"
          x-lineageReferenceObject: TBBCSTU_AUTH_NUMBER
        contractNumber:
          title: Number
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBCSTU_CONTRACT_NUMBER"
          x-lineageReferenceObject: TBBCSTU_CONTRACT_NUMBER
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBCSTU_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBBCSTU_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: tbbcstu
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    account-review-form-contracts-1.0.0_put_request:
      type: object
      properties:
        authInd:
          title: Authorization
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_AUTH_IND"
          x-lineageReferenceObject: TBBCSTU_AUTH_IND
        criteria.authNumber:
          title: Authorization Number
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBCSTU_AUTH_NUMBER"
          x-lineageReferenceObject: TBBCSTU_AUTH_NUMBER
        stspKeySequence:
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBCSTU_STSP_KEY_SEQUENCE"
          x-lineageReferenceObject: TBBCSTU_STSP_KEY_SEQUENCE
        tbbcstuDelInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_DEL_IND"
          x-lineageReferenceObject: TBBCSTU_DEL_IND
        criteria.contractNumber:
          title: Number
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBCSTU_CONTRACT_NUMBER"
          x-lineageReferenceObject: TBBCSTU_CONTRACT_NUMBER
        criteria.tbbcstuDelInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_DEL_IND"
          x-lineageReferenceObject: TBBCSTU_DEL_IND
        tbbcstuMaxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBCSTU_MAX_STUDENT_AMOUNT"
          x-lineageReferenceObject: TBBCSTU_MAX_STUDENT_AMOUNT
        studentContRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_STUDENT_CONT_ROLL_IND"
          x-lineageReferenceObject: TBBCSTU_STUDENT_CONT_ROLL_IND
        criteria.studentContRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_STUDENT_CONT_ROLL_IND"
          x-lineageReferenceObject: TBBCSTU_STUDENT_CONT_ROLL_IND
        criteria.contractPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBCSTU_CONTRACT_PRIORITY"
          x-lineageReferenceObject: TBBCSTU_CONTRACT_PRIORITY
        criteria.stspKeySequence:
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBCSTU_STSP_KEY_SEQUENCE"
          x-lineageReferenceObject: TBBCSTU_STSP_KEY_SEQUENCE
        contractPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBCSTU_CONTRACT_PRIORITY"
          x-lineageReferenceObject: TBBCSTU_CONTRACT_PRIORITY
        criteria.authInd:
          title: Authorization
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBCSTU_AUTH_IND"
          x-lineageReferenceObject: TBBCSTU_AUTH_IND
        criteria.tbbcstuMaxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBCSTU_MAX_STUDENT_AMOUNT"
          x-lineageReferenceObject: TBBCSTU_MAX_STUDENT_AMOUNT
        authNumber:
          title: Authorization Number
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBCSTU_AUTH_NUMBER"
          x-lineageReferenceObject: TBBCSTU_AUTH_NUMBER
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.tbbcstuTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBCSTU_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBBCSTU_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: TBBCSTU
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
