openapi: 3.0.0
info:
  title: benefit-or-deduction-combined-limit-rules
  description: API for PTRBDCL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PTRBDCL
  x-source-domain: Human Resources
  x-source-title: Benefit/Deduction Combined Limit Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/benefit-or-deduction-combined-limit-rules:
    get:
      tags:
        - benefit-or-deduction-combined-limit-rules
      summary: Return resources from PTRBDCL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: code
          in: query
          description: Combined Limit Rule Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_CODE
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_DESC
        - name: emplLimit
          in: query
          description: Employee Limit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_EMPL_LIMIT
        - name: emprLimit
          in: query
          description: Employer Limit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_EMPR_LIMIT
        - name: emplEmprLimit
          in: query
          description: Combined Limit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_EMPL_EMPR_LIMIT
        - name: maxGross
          in: query
          description: Applicable Gross Limit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_MAX_GROSS
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDCL_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/benefit-or-deduction-combined-limit-rules-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/benefit-or-deduction-combined-limit-rules:
    post:
      tags:
        - benefit-or-deduction-combined-limit-rules QAPI (Query by POST)
      summary: Return resources from PTRBDCL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/benefit-or-deduction-combined-limit-rules-1.0.0_get\
                _request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/benefit-or-deduction-combined-limit-rules-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    benefit-or-deduction-combined-limit-rules-1.0.0_get_request:
      required:
        - code
        - desc
      type: object
      properties:
        maxGross:
          title: Applicable Gross Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_MAX_GROSS"
          x-lineageReferenceObject: PTRBDCL_MAX_GROSS
        emplLimit:
          title: Employee Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPL_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPL_LIMIT
        code:
          title: Combined Limit Rule Code
          maxLength: 8
          type: string
          description: "Lineage reference object : PTRBDCL_CODE"
          x-lineageReferenceObject: PTRBDCL_CODE
        emprLimit:
          title: Employer Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPR_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPR_LIMIT
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PTRBDCL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRBDCL_ACTIVITY_DATE
        emplEmprLimit:
          title: Combined Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPL_EMPR_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPL_EMPR_LIMIT
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRBDCL_DESC"
          x-lineageReferenceObject: PTRBDCL_DESC
      x-lineageReferenceObject: PTRBDCL
    benefit-or-deduction-combined-limit-rules-1.0.0_qapi_post:
      type: object
      properties:
        code:
          title: Combined Limit Rule Code
          maxLength: 8
          type: string
          description: "Lineage reference object : PTRBDCL_CODE"
          x-lineageReferenceObject: PTRBDCL_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRBDCL_DESC"
          x-lineageReferenceObject: PTRBDCL_DESC
        emplLimit:
          title: Employee Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPL_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPL_LIMIT
        emprLimit:
          title: Employer Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPR_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPR_LIMIT
        emplEmprLimit:
          title: Combined Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPL_EMPR_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPL_EMPR_LIMIT
        maxGross:
          title: Applicable Gross Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_MAX_GROSS"
          x-lineageReferenceObject: PTRBDCL_MAX_GROSS
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PTRBDCL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRBDCL_ACTIVITY_DATE
    benefit-or-deduction-combined-limit-rules-1.0.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        maxGross:
          title: Applicable Gross Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_MAX_GROSS"
          x-lineageReferenceObject: PTRBDCL_MAX_GROSS
        emplLimit:
          title: Employee Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPL_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPL_LIMIT
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PTRBDCL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRBDCL_ACTIVITY_DATE
        code:
          title: Combined Limit Rule Code
          maxLength: 8
          type: string
          description: "Lineage reference object : PTRBDCL_CODE"
          x-lineageReferenceObject: PTRBDCL_CODE
        emprLimit:
          title: Employer Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPR_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPR_LIMIT
        emplEmprLimit:
          title: Combined Limit
          maxLength: 23
          type: number
          description: "Lineage reference object : PTRBDCL_EMPL_EMPR_LIMIT"
          x-lineageReferenceObject: PTRBDCL_EMPL_EMPR_LIMIT
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRBDCL_DESC"
          x-lineageReferenceObject: PTRBDCL_DESC
      x-lineageReferenceObject: ptrbdcl
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
