openapi: 3.0.0
info:
  title: term-details
  description: >
    Retrieves detailed information about a particular term that the user has
    passed. The response includes details of part-of-term rules, faculty web
    security dates for the term and web registration dates for the term.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: Term Details
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: term-details
paths:
  /api/term-details/{termCode}:
    get:
      description: |
        Retrieves information about a particular term that the user has passed.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_TERM_DETAILS
      tags:
        - term-details
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/vnd.hedtech.integration.v1.0.0+json
            ```
        - name: termCode
          in: path
          required: true
          description: Code value to identify the term
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/term-details"
            application/vnd.hedtech.integration.v1.0.0+xml:
              schema:
                type: object
                $ref: "#/components/schemas/term-details"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    term-details:
      type: object
      properties:
        termBase:
          type: object
          properties:
            version:
              type: number
            id:
              type: number
            addDropWebUpdateIndicator:
              type: boolean
            adminDropCode:
              type: string
            approvalSeverity:
              type: string
            assessRegistrationGraceIndicator:
              type: boolean
            assessReverseNrfIndicator:
              type: boolean
            assessSwapIndicator:
              type: boolean
            attributeSeverity:
              type: string
            attributeWebSearchIndicator:
              type: boolean
            autoDropCode:
              type: string
            byCrnIndicatorFlag:
              type: string
            campusSeverity:
              type: string
            campusWebSearchIndicator:
              type: boolean
            capacitySeverity:
              type: string
            classListWebDisplayIndicator:
              type: boolean
            classSeverity:
              type: string
            closedSectionWebDisplayIndicator:
              type: boolean
            cohortSeverity:
              type: string
            collegeSeverity:
              type: string
            collegeWebCatalogSearchIndicator:
              type: boolean
            conditionalAddDropCode:
              type: string
            coreqSeverity:
              type: string
            courseReferenceNumberOneUp:
              type: number
            creditWebUpdateIndicator:
              type: boolean
            cutoffDate:
              type: string
              format: date
            degreeAuditPlanCode:
              type: string
            degreeSeverity:
              type: string
            departmentSeverity:
              type: string
            departmentWebCatalogSearchIndicator:
              type: boolean
            detailGradePublicationDate:
              type: string
              format: date
            divisionWebCatalogSearchIndicator:
              type: boolean
            dropLastClassAllowedCode:
              type: string
            duplicateSeverity:
              type: string
            durationWebSearchIndicator:
              type: boolean
            dynamicScheduleTermIndicator:
              type: boolean
            facultyScheduleWebDisplayIndicator:
              type: boolean
            feeAssessVoiceResponseFlag:
              type: string
            feeAssessmentEffectiveDate:
              type: string
              format: date
            feeAssessmentIndicator:
              type: boolean
            finalGradePublicationDate:
              type: string
              format: date
            gradeDetailWebIndicator:
              type: boolean
            gradingModeWebUpdateIndicator:
              type: boolean
            holdSeverity:
              type: string
            includeAttemptHoursIndicator:
              type: boolean
            inprogressUsageIndicator:
              type: boolean
            instructionalMethodWebSearchIndicator:
              type: boolean
            instructorWebSearchIndicator:
              type: boolean
            levelSeverity:
              type: string
            levelWebCatalogSearchIndicator:
              type: boolean
            levelWebSearchIndicator:
              type: boolean
            levelWebUpdateIndicator:
              type: boolean
            linkSeverity:
              type: string
            longCourseDescriptionWebCatalogDisplayIndicator:
              type: boolean
            longCourseTitleWebCatalogDisplayIndicator:
              type: boolean
            longSectionDescriptionWebDisplayIndicator:
              type: boolean
            longSectionTitleWebDisplayIndicator:
              type: boolean
            mailerWebIndicator:
              type: boolean
            majorSeverity:
              type: string
            maxHourSeverity:
              type: string
            maxPlans:
              type: integer
            meetingTimeSourceCode:
              type: string
            midTermWebIndicator:
              type: boolean
            minHourSeverity:
              type: string
            mutualExclusionSeverity:
              type: string
            overrideApprovalWebUpdateIndicator:
              type: boolean
            planDegreeAuditRegistrationAllowedCode:
              type: string
            planRegistrationAllowedCode:
              type: string
            planTermOpenCode:
              type: string
            prereqSeverity:
              type: string
            printBillVoiceResponseIndicator:
              type: boolean
            profileSendIndicator:
              type: boolean
            programAttributeWebCatalogSearchIndicator:
              type: boolean
            programSeverity:
              type: string
            reassessmentDetailGradePublicationDate:
              type: string
              format: date
            reassessmentGradePublicationDate:
              type: string
              format: date
            refundIndicatorFlag:
              type: string
            registrationAllowedIndicator:
              type: boolean
            repeatFutureIndicator:
              type: boolean
            repeatHourSeverity:
              type: string
            repeatSeverity:
              type: string
            scheduleTypeWebCatalogSearchIndicator:
              type: boolean
            scheduleWebSearchIndicator:
              type: boolean
            sectionAllowedPlanCode:
              type: string
            sectionFeeIndicator:
              type: boolean
            sessionWebSearchIndicator:
              type: boolean
            studyPathIndicator:
              type: boolean
            studyPathWebUpdateIndicator:
              type: boolean
            testSeverity:
              type: string
            timeSeverity:
              type: string
            timeStatusCalculationIndicator:
              type: boolean
            titleIVDateSource:
              type: string
            webCappCatalogIndicator:
              type: boolean
            webCappTermIndicator:
              type: boolean
        partOfTermRules:
          type: array
          items:
            type: object
            properties:
              version:
                type: number
              id:
                type: number
              census2Date:
                type: string
                format: date
              censusDate:
                type: string
                format: date
              description:
                type: string
              detailGradePublicationDate:
                type: string
                format: date
              endDate:
                type: string
                format: date
              finalGradePublicationDate:
                type: string
                format: date
              finalGradeWebUpdateIndicator:
                type: boolean
              incompleteExtensionDate:
                type: string
                format: date
              midTermGradeWebUpdateIndicator:
                type: boolean
              partOfTerm:
                type: object
                properties:
                  version:
                    type: number
                  id:
                    type: number
                  code:
                    type: number
                  description:
                    type: number
              reassessmentDetailGradePublicationDate:
                type: string
                format: date
              reassessmentGradePublicationDate:
                type: string
                format: date
              reassessmentScoreCutoffDate:
                type: string
                format: date
              reassessmentScoreOpenDate:
                type: string
                format: date
              scoreCutoffDate:
                type: string
                format: date
              scoreOpenDate:
                type: string
                format: date
              sectionOverIndicator:
                type: boolean
              startDate:
                type: string
                format: date
              waitlistWebDisplayIndicator:
                type: boolean
              weeks:
                type: number
        facultyWebSecurityDates:
          type: array
          items:
            type: object
            properties:
              version:
                type: integer
              id:
                type: integer
              endDate:
                type: string
                format: date
              menuIndicator:
                type: boolean
              sequenceNumber:
                type: integer
              startDate:
                type: string
                format: date
              termIndicator:
                type: boolean
        webRegistrationDates:
          type: array
          items:
            type: object
            properties:
              version:
                type: number
              id:
                type: number
              endDate:
                type: string
                format: date
              startDate:
                type: string
                format: date
