openapi: 3.0.0
info:
  title: satisfactory-academic-progress-statuses
  description: API for RTVSAPR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RTVSAPR
  x-source-domain: Financial Aid
  x-source-title: Satisfactory Academic Progress Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/satisfactory-academic-progress-statuses:
    get:
      tags:
        - satisfactory-academic-progress-statuses
      summary: Return resources from RTVSAPR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activeInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_ACTIVE_IND
        - name: aidType
          in: query
          description: Which Aid
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_AID_TYPE
        - name: code
          in: query
          description: SAP Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_CODE
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_DESC
        - name: disbInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_DISB_IND
        - name: letrCode
          in: query
          description: Letter Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_LETR_CODE
        - name: pckgInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_PCKG_IND
        - name: priority
          in: query
          description: Priority
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_PRIORITY
        - name: vrMsgNo
          in: query
          description: Message Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVSAPR_VR_MSG_NO
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/satisfactory-academic-progress-statuses-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/satisfactory-academic-progress-statuses:
    post:
      tags:
        - satisfactory-academic-progress-statuses QAPI (Query by POST)
      summary: Return resources from RTVSAPR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/satisfactory-academic-progress-statuses-1.0.0_get_r\
                equest"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/satisfactory-academic-progress-statuses-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    satisfactory-academic-progress-statuses-1.0.0_get_request:
      required:
        - aidType
        - code
        - desc
        - priority
      type: object
      properties:
        code:
          title: SAP Status
          maxLength: 6
          type: string
          description: "Lineage reference object : RTVSAPR_CODE"
          x-lineageReferenceObject: RTVSAPR_CODE
        aidType:
          title: Which Aid
          maxLength: 2
          type: number
          description: "Lineage reference object : RTVSAPR_AID_TYPE"
          x-lineageReferenceObject: RTVSAPR_AID_TYPE
        disbInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_DISB_IND"
          x-lineageReferenceObject: RTVSAPR_DISB_IND
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_ACTIVE_IND"
          x-lineageReferenceObject: RTVSAPR_ACTIVE_IND
        letrCode:
          title: Letter Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVSAPR_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: RTVSAPR_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        priority:
          title: Priority
          maxLength: 6
          type: number
          description: "Lineage reference object : RTVSAPR_PRIORITY"
          x-lineageReferenceObject: RTVSAPR_PRIORITY
        vrMsgNo:
          title: Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : RTVSAPR_VR_MSG_NO"
          x-lineageReferenceObject: RTVSAPR_VR_MSG_NO
        pckgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_PCKG_IND"
          x-lineageReferenceObject: RTVSAPR_PCKG_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVSAPR_DESC"
          x-lineageReferenceObject: RTVSAPR_DESC
      x-lineageReferenceObject: RTVSAPR
    satisfactory-academic-progress-statuses-1.0.0_get_response:
      required:
        - aidType
        - code
        - desc
        - priority
      type: object
      properties:
        code:
          title: SAP Status
          maxLength: 6
          type: string
          description: "Lineage reference object : RTVSAPR_CODE"
          x-lineageReferenceObject: RTVSAPR_CODE
        aidType:
          title: Which Aid
          maxLength: 2
          type: number
          description: "Lineage reference object : RTVSAPR_AID_TYPE"
          x-lineageReferenceObject: RTVSAPR_AID_TYPE
        disbInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_DISB_IND"
          x-lineageReferenceObject: RTVSAPR_DISB_IND
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_ACTIVE_IND"
          x-lineageReferenceObject: RTVSAPR_ACTIVE_IND
        letrCode:
          title: Letter Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVSAPR_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: RTVSAPR_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        priority:
          title: Priority
          maxLength: 6
          type: number
          description: "Lineage reference object : RTVSAPR_PRIORITY"
          x-lineageReferenceObject: RTVSAPR_PRIORITY
        vrMsgNo:
          title: Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : RTVSAPR_VR_MSG_NO"
          x-lineageReferenceObject: RTVSAPR_VR_MSG_NO
        pckgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_PCKG_IND"
          x-lineageReferenceObject: RTVSAPR_PCKG_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVSAPR_DESC"
          x-lineageReferenceObject: RTVSAPR_DESC
      x-lineageReferenceObject: rtvsapr
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    satisfactory-academic-progress-statuses-1.0.0_qapi_post:
      type: object
      properties:
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_ACTIVE_IND"
          x-lineageReferenceObject: RTVSAPR_ACTIVE_IND
        aidType:
          title: Which Aid
          maxLength: 2
          type: number
          description: "Lineage reference object : RTVSAPR_AID_TYPE"
          x-lineageReferenceObject: RTVSAPR_AID_TYPE
        code:
          title: SAP Status
          maxLength: 6
          type: string
          description: "Lineage reference object : RTVSAPR_CODE"
          x-lineageReferenceObject: RTVSAPR_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVSAPR_DESC"
          x-lineageReferenceObject: RTVSAPR_DESC
        disbInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_DISB_IND"
          x-lineageReferenceObject: RTVSAPR_DISB_IND
        letrCode:
          title: Letter Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVSAPR_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: RTVSAPR_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        pckgInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVSAPR_PCKG_IND"
          x-lineageReferenceObject: RTVSAPR_PCKG_IND
        priority:
          title: Priority
          maxLength: 6
          type: number
          description: "Lineage reference object : RTVSAPR_PRIORITY"
          x-lineageReferenceObject: RTVSAPR_PRIORITY
        vrMsgNo:
          title: Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : RTVSAPR_VR_MSG_NO"
          x-lineageReferenceObject: RTVSAPR_VR_MSG_NO
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
