openapi: 3.0.0
info:
  title: external-report-translation-codes
  description: API for FTVEELT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FTVEELT
  x-source-domain: Finance
  x-source-title: External Report Translation Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/external-report-translation-codes:
    get:
      tags:
      - external-report-translation-codes
      summary: Return resources from FTVEELT
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
      - name: coasCode
        in: query
        description: COA
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_COAS_CODE
      - name: eelcCode
        in: query
        description: Internal Element
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_EELC_CODE
      - name: eeliCode
        in: query
        description: "External\tCode"
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_EELI_CODE
      - name: eeltCode
        in: query
        description: Internal Code
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_EELT_CODE
      - name: eentCode
        in: query
        description: External Entity
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_EENT_CODE
      - name: effDate
        in: query
        description: Effective Date
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_EFF_DATE
      - name: statusInd
        in: query
        description: Status
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_STATUS_IND
      - name: termDate
        in: query
        description: Termination Date
        required: false
        schema:
          type: string
        x-lineageReferenceObject: FTVEELT_TERM_DATE
      - name: internalCodeTitle
        in: query
        description: Translation Title
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/external-report-translation-codes-1.0.0_get_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/external-report-translation-codes:
    post:
      tags:
      - external-report-translation-codes QAPI (Query by POST)
      summary: Return resources from FTVEELT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/external-report-translation-codes-1.0.0_qapi_post_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/external-report-translation-codes-1.0.0_qapi_post_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
components:
  schemas:
    external-report-translation-codes-1.0.0_get_response:
      type: object
      properties:
        eentCode:
          title: External Entity
          maxLength: 4
          type: string
          description: "Lineage reference object : FTVEELT_EENT_CODE"
          x-lineageReferenceObject: FTVEELT_EENT_CODE
        effDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVEELT_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVEELT_EFF_DATE
        internalCodeTitle:
          title: Translation Title
          maxLength: 35
          type: string
        eeliCode:
          title: "External\tCode"
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVEELT_EELI_CODE, Lookup lineage\
            \ reference object : ftveeli"
          x-lineageReferenceObject: FTVEELT_EELI_CODE
          x-lineageLookupReferenceObject: ftveeli
        statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVEELT_STATUS_IND"
          x-lineageReferenceObject: FTVEELT_STATUS_IND
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVEELT_COAS_CODE"
          x-lineageReferenceObject: FTVEELT_COAS_CODE
        termDate:
          title: Termination Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVEELT_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVEELT_TERM_DATE
        eelcCode:
          title: Internal Element
          maxLength: 4
          type: string
          description: "Lineage reference object : FTVEELT_EELC_CODE"
          x-lineageReferenceObject: FTVEELT_EELC_CODE
        eeltCode:
          title: Internal Code
          maxLength: 6
          type: string
          description: "Lineage reference object : FTVEELT_EELT_CODE"
          x-lineageReferenceObject: FTVEELT_EELT_CODE
      x-lineageReferenceObject: ftveelt
    external-report-translation-codes-1.0.0_qapi_post_request:
      type: object
      properties:
        eentCode:
          title: External Entity
          maxLength: 4
          type: string
          description: "Lineage reference object : FTVEELT_EENT_CODE"
          x-lineageReferenceObject: FTVEELT_EENT_CODE
        effDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVEELT_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVEELT_EFF_DATE
        internalCodeTitle:
          title: Translation Title
          maxLength: 35
          type: string
        eeliCode:
          title: "External\tCode"
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVEELT_EELI_CODE, Lookup lineage\
            \ reference object : ftveeli"
          x-lineageReferenceObject: FTVEELT_EELI_CODE
          x-lineageLookupReferenceObject: ftveeli
        statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVEELT_STATUS_IND"
          x-lineageReferenceObject: FTVEELT_STATUS_IND
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVEELT_COAS_CODE"
          x-lineageReferenceObject: FTVEELT_COAS_CODE
        termDate:
          title: Termination Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVEELT_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVEELT_TERM_DATE
        eelcCode:
          title: Internal Element
          maxLength: 4
          type: string
          description: "Lineage reference object : FTVEELT_EELC_CODE"
          x-lineageReferenceObject: FTVEELT_EELC_CODE
        eeltCode:
          title: Internal Code
          maxLength: 6
          type: string
          description: "Lineage reference object : FTVEELT_EELT_CODE"
          x-lineageReferenceObject: FTVEELT_EELT_CODE
      x-lineageReferenceObject: FTVEELT
    external-report-translation-codes-1.0.0_qapi_post_response:
      type: object
      properties:
        eentCode:
          title: External Entity
          maxLength: 4
          type: string
          description: "Lineage reference object : FTVEELT_EENT_CODE"
          x-lineageReferenceObject: FTVEELT_EENT_CODE
        effDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVEELT_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVEELT_EFF_DATE
        internalCodeTitle:
          title: Translation Title
          maxLength: 35
          type: string
        eeliCode:
          title: "External\tCode"
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVEELT_EELI_CODE, Lookup lineage\
            \ reference object : ftveeli"
          x-lineageReferenceObject: FTVEELT_EELI_CODE
          x-lineageLookupReferenceObject: ftveeli
        statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVEELT_STATUS_IND"
          x-lineageReferenceObject: FTVEELT_STATUS_IND
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FTVEELT_COAS_CODE"
          x-lineageReferenceObject: FTVEELT_COAS_CODE
        termDate:
          title: Termination Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVEELT_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVEELT_TERM_DATE
        eelcCode:
          title: Internal Element
          maxLength: 4
          type: string
          description: "Lineage reference object : FTVEELT_EELC_CODE"
          x-lineageReferenceObject: FTVEELT_EELC_CODE
        eeltCode:
          title: Internal Code
          maxLength: 6
          type: string
          description: "Lineage reference object : FTVEELT_EELT_CODE"
          x-lineageReferenceObject: FTVEELT_EELT_CODE
      x-lineageReferenceObject: ftveelt
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
