openapi: 3.0.0
info:
  title: Extension Mappings
  description: The Extension Mapping API provides functionality to manage
    extension mappings defined in the GOREXTM table. This API allows users to
    establish the baseline page and the extended table, enabling them to view,
    add, edit, or delete extended table data through the user interface in the
    More Info section.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/extension-mappings:
    get:
      summary: Return all resources
      description: Returns a paged listing of all the resources in the system.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_EXT_MAPPINGS
      tags:
        - extension-mappings
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Extended table Name  

            The name of the Extended table, which, when provided, causes the API to return only the extension mappings that match this filter criterion. 

            ```

            /extension-mappings?criteria={"extendedTableName":"XTESTDUP"}

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/extension-mappings.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    post:
      summary: Create a new resource
      description: Create a new resource
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_EXT_MAPPINGS
      tags:
        - extension-mappings
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/extension-mappings.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              type: object
              $ref: "#/components/schemas/extension-mappings.json"
  /api/extension-mappings/{id}:
    get:
      summary: Return the requested resource
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_EXT_MAPPINGS
      tags:
        - extension-mappings
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Custom Table Configurations for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/extension-mappings.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    delete:
      summary: Removes the requested resource
      tags:
        - extension-mappings
      description: >
        Deletes the existing custom table configuration record from GORCSTT
        table with the passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_EXT_MAPPINGS
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    extension-mappings.json:
      title: Extension Mappings
      description: The API returns the list of the extension mappings defined in
        GOREXTM table.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the extension-mappings.
          type: string
          format: guid
          pattern: ^a-f0-9]8(?:-a-f0-9]4)3-a-f0-9]12$
        baselineTable:
          title: Banner Table Name
          description: The name of the Banner table which is mapped with the extended table.
          type: string
        extendedTableName:
          title: Extended Table Name
          description: The name of the extended table which holds the extended data.
          type: string
        baselinePageName:
          title: Banner Page Name
          description: The name of the Banner page to surface the extended data.
          type: string
        supplementalDataResourceName:
          title: Secured Extended Table API Name
          description: The name of the extended table API name which will secure the extended data on the UI.
          type: string
        supplementalDataResourceSecurityObject:
          title: Extended Table API's security object
          description: The name of the extended table API's security object name which will secure the extended data on the UI.
          type: string
        apiRegistryDocument:
          title: API Registry Document identifier
          description: The document identifier of the endpoint specification registered in API Registry.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the API Registry Document.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
            
      required:
        - id
        - baselineTable
        - extendedTableName
        - baselinePageName
      additionalProperties: false