openapi: 3.0.0
info:
  title: billing-mass-data-entry-charges-payments
  description: API for TFAMASS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TFAMASS
  x-source-domain: Finance
  x-source-title: Billing Mass Data Entry Form - Finance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/billing-mass-data-entry-charges-payments:
    post:
      tags:
        - billing-mass-data-entry-charges-payments
      summary: Creates a new resource in TFAMASS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/billing-mass-data-entry-charges-payments-1.0.0_post\
                _request"
            example:
              amount: 1
              documentNumber: A
              keyblocEffDate: 2021-05-25
              keyblocAmount: 1
              detailCode: 0
              keyblocDocumentNumber: 1
              keyblocDetailCode: 0
              invoiceNumber: A
              id: 341819778
              receiptInd1: N
              atypCode: PR
              atypSeqno: 1
              desc: Shar Test11
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/billing-mass-data-entry-charges-payments-1.0.0_post\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/billing-mass-data-entry-charges-payments: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    billing-mass-data-entry-charges-payments-1.0.0_post_request:
      required:
        - detailCode
        - desc
        - amount
        - atypCode
        - atypSeqno
        - receiptInd1
      type: object
      properties:
        amount:
          title: Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : TBRACCD_AMOUNT"
          x-lineageReferenceObject: TBRACCD_AMOUNT
        documentNumber:
          title: Document
          maxLength: 8
          type: string
          description: "Lineage reference object : TBRACCD_DOCUMENT_NUMBER"
          x-lineageReferenceObject: TBRACCD_DOCUMENT_NUMBER
        keyblocEffDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : keyblocEffDate"
          format: date-time
          x-lineageReferenceObject: keyblocEffDate
        keyblocAmount:
          title: Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : keyblocAmount"
          x-lineageReferenceObject: keyblocAmount
        detailCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBRACCD_DETAIL_CODE, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: TBRACCD_DETAIL_CODE
          x-lineageLookupReferenceObject: tbbdetc
        keyblocDocumentNumber:
          title: Document
          maxLength: 8
          type: string
          description: "Lineage reference object : keyblocDocumentNumber"
          x-lineageReferenceObject: keyblocDocumentNumber
        keyblocDetailCode:
          title: Detail Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocDetailCode, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: keyblocDetailCode
          x-lineageLookupReferenceObject: tbbdetc
        invoiceNumber:
          title: Invoice
          maxLength: 8
          type: string
          description: "Lineage reference object : TBRACCD_INVOICE_NUMBER"
          x-lineageReferenceObject: TBRACCD_INVOICE_NUMBER
        id:
          title: ID
          maxLength: 9
          type: string
        receiptInd1:
          title: Receipt
          maxLength: 1
          type: string
        atypCode:
          title: Address Type
          maxLength: 2
          type: string
          description: "Lineage reference object : TBRACCD_ATYP_CODE"
          x-lineageReferenceObject: TBRACCD_ATYP_CODE
        atypSeqno:
          title: Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : TBRACCD_ATYP_SEQNO"
          x-lineageReferenceObject: TBRACCD_ATYP_SEQNO
        desc:
          title: Detail Code Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRACCD_DESC"
          x-lineageReferenceObject: TBRACCD_DESC
      x-lineageReferenceObject: TBRACCD
    billing-mass-data-entry-charges-payments-1.0.0_post_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              keyblocDocumentNumber:
                title: Document
                maxLength: 8
                type: string
                description: "Lineage reference object : keyblocDocumentNumber"
                x-lineageReferenceObject: keyblocDocumentNumber
              keyblocDetailCode:
                title: Detail Code
                maxLength: 30
                type: string
                description: "Lineage reference object : keyblocDetailCode, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: keyblocDetailCode
                x-lineageLookupReferenceObject: tbbdetc
              keyblocEffDate:
                title: Effective Date
                maxLength: 11
                type: string
                description: "Lineage reference object : keyblocEffDate"
                format: date-time
                x-lineageReferenceObject: keyblocEffDate
              runningDepoTotal:
                title: Deposit Total
                maxLength: 13
                type: number
                description: "Lineage reference object : runningDepoTotal"
                x-lineageReferenceObject: runningDepoTotal
              runningAccdTotal:
                title: Total
                maxLength: 16
                type: number
                description: "Lineage reference object : runningAccdTotal"
                x-lineageReferenceObject: runningAccdTotal
              keyblocAmount:
                title: Amount
                maxLength: 15
                type: number
                description: "Lineage reference object : keyblocAmount"
                x-lineageReferenceObject: keyblocAmount
              runningMemoTotal:
                title: Memo Total
                maxLength: 10
                type: number
                description: "Lineage reference object : runningMemoTotal"
                x-lineageReferenceObject: runningMemoTotal
            x-lineageReferenceObject: key_block
        tbraccd:
          type: array
          items:
            required:
              - receiptInd1
              - amount
              - atypCode
              - atypSeqno
              - desc
              - detailCode
            type: object
            properties:
              amount:
                title: Amount
                maxLength: 14
                type: number
                description: "Lineage reference object : TBRACCD_AMOUNT"
                x-lineageReferenceObject: TBRACCD_AMOUNT
              documentNumber:
                title: Document
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRACCD_DOCUMENT_NUMBER"
                x-lineageReferenceObject: TBRACCD_DOCUMENT_NUMBER
              invoiceNumber:
                title: Invoice
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRACCD_INVOICE_NUMBER"
                x-lineageReferenceObject: TBRACCD_INVOICE_NUMBER
              name:
                title: Name
                maxLength: 230
                type: string
              receiptInd1:
                title: Receipt
                maxLength: 1
                type: string
              id:
                title: ID
                maxLength: 9
                type: string
              detailCode:
                title: Detail Code
                maxLength: 4
                type: string
                description: "Lineage reference object : TBRACCD_DETAIL_CODE, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: TBRACCD_DETAIL_CODE
                x-lineageLookupReferenceObject: tbbdetc
              atypCode:
                title: Address Type
                maxLength: 2
                type: string
                description: "Lineage reference object : TBRACCD_ATYP_CODE"
                x-lineageReferenceObject: TBRACCD_ATYP_CODE
              atypSeqno:
                title: Sequence
                maxLength: 2
                type: number
                description: "Lineage reference object : TBRACCD_ATYP_SEQNO"
                x-lineageReferenceObject: TBRACCD_ATYP_SEQNO
              desc:
                title: Detail Code Description
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRACCD_DESC"
                x-lineageReferenceObject: TBRACCD_DESC
            x-lineageReferenceObject: tbraccd
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
