openapi: 3.0.0
info:
  title: ca-education-opportunity-batches
  description: Process to load Education Opportunity Programs and Services into SGBEOPS
  version: 1.0.0-beta
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: beta
  x-source-domain: Student
  x-source-title: CA Education Opportunity Batches
paths:
  /api/ca-education-opportunity-batches:
    put:
      tags:
        - ca-education-opportunity-batches
      summary: Update an existing record of SGBEOPS
      description: Update an existing record of SGBEOPS by Id
      operationId: updateCaEduOpporBatch
      requestBody:
        description: Update an existent ca-education-opportunity-batches in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CaEduOpporBatchRequest"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eopsResponse"
        "400":
          description: Invalid ID supplied
        "404":
          description: Not found
        "405":
          description: Validation exception
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_CA_EDU_OPPORTUNITY_BATCHES
    post:
      tags:
        - ca-education-opportunity-batches
      summary: Add a new CaEduOpporBatch to the store
      description: Add a new CaEduOpporBatch to the store
      operationId: addCaEduOpporBatch
      requestBody:
        description: Create a new CaEduOpporBatch in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CaEduOpporBatchRequest"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eopsResponse"
        "405":
          description: Invalid input
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_CA_EDU_OPPORTUNITY_BATCHES
components:
  schemas:
    CaEduOpporBatchRequest:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              educationalTerm:
                type: string
                description: Effective Term
                example: "202320"
              eops:
                type: array
                items:
                  type: object
                  properties:
                    edStudentId:
                      type: string
                      description: Student Id
                      example: A00000719
                    eopsStatus:
                      type: string
                      description: Education Opportunity Programs and Services Code
                      example: XE
                    stateFAID:
                      type: string
                      description: Represents the method which was used to determine that the student
                        was eligible for the EOPS program
                      example: A2
                    acceptanceReason:
                      type: string
                      description: EOPS Acceptance Period Code
                      example: APP
                    withdrawReason:
                      type: string
                      description: Withdrawal Reason.
                      example: A
                    plannedCredits:
                      type: string
                      description: EOPS Number of units the student plans to enroll in for the
                        reporting term
                      example: "10"
                    acceptanceDate:
                      type: string
                      description: The date the student was accepted into the EOPS program
                      example: 2012-12-12
                    acceptanceTerm:
                      type: string
                      description: Valid term
                      example: "202320"
                    dicdCode:
                      type: string
                      description: District Identifier which is linked to the CRNs via campus
                        validation.
                      example: "123"
      required:
        - educationalTerm
        - edStudentId
    eopsResponse:
      type: array
      items:
        type: object
        properties:
          eopsResponse:
            type: array
            items:
              type: object
              properties:
                edStudentId:
                  type: string
                eopsStatus:
                  type: string
                stateFinancial:
                  type: string
                acceptanceReason:
                  type: string
                withdrawalReason:
                  type: string
                planendCredits:
                  type: string
                acceptanceDate:
                  type: string
                acceptanceTerm:
                  type: string
                dicdCode:
                  type: string
                message:
                  type: string
  requestBodies:
    CaEduOpporBatchRequest:
      description: CaEduOpporBatch object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CaEduOpporBatchRequest"
  responses:
    "200":
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/eopsResponse"
    "400":
      description: Invalid ID supplied
    "404":
      description: Not found
    "405":
      description: Validation exception
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
