openapi: 3.0.0
info:
  title: finance-additional-identification
  description: API for FOAIDEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FOAIDEN
  x-source-domain: Finance
  x-source-title: Person Identification Form - Finance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/finance-additional-identification:
    post:
      tags:
        - finance-additional-identification
      summary: Creates a new resource in FOAIDEN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/finance-additional-identification-1.0.0_post_reques\
                t"
            example:
              additionalId: Sample Post
              adidCode: 1010
              id: 20
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finance-additional-identification-1.0.0_post_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/finance-additional-identification: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    finance-additional-identification-1.0.0_post_request:
      type: object
      properties:
        additionalId:
          title: Additional Identification
          maxLength: 50
          type: string
          description: "Lineage reference object : GORADID_ADDITIONAL_ID"
          x-lineageReferenceObject: GORADID_ADDITIONAL_ID
        adidCode:
          title: ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GORADID_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GORADID_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: GORADID
    finance-additional-identification-1.0.0_post_response:
      type: object
      properties:
        adidDesc:
          title: ID Type Description
          type: string
        additionalId:
          title: Additional Identification
          maxLength: 50
          type: string
          description: "Lineage reference object : GORADID_ADDITIONAL_ID"
          x-lineageReferenceObject: GORADID_ADDITIONAL_ID
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GORADID_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GORADID_ACTIVITY_DATE
        adidCode:
          title: ID Type
          maxLength: 4
          type: string
          description: "Lineage reference object : GORADID_ADID_CODE, Lookup lineage
            reference object : gtvadid"
          x-lineageReferenceObject: GORADID_ADID_CODE
          x-lineageLookupReferenceObject: gtvadid
        userId:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : GORADID_USER_ID"
          x-lineageReferenceObject: GORADID_USER_ID
      x-lineageReferenceObject: goradid
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
