openapi: 3.0.0
info:
  title: direct-loan-origination-plus-data-credit-data
  description: API for RLADLOR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RLADLOR
  x-source-domain: Financial Aid
  x-source-title: Direct Loan Origination
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-loan-origination-plus-data-credit-data:
    get:
      tags:
        - direct-loan-origination-plus-data-credit-data
      summary: Return resources from RLADLOR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-origination-plus-data-credit-data-1.0.0\
                    _get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/direct-loan-origination-plus-data-credit-data:
    post:
      tags:
        - direct-loan-origination-plus-data-credit-data QAPI (Query by POST)
      summary: Return resources from RLADLOR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-loan-origination-plus-data-credit-data-1.0.0\
                _get_request"
            example:
              keyblckAidyCode: 2122
              id: 204001
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-origination-plus-data-credit-data-1.0.0\
                    _get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    direct-loan-origination-plus-data-credit-data-1.0.0_get_response:
      type: object
      properties:
        plusCounselingComp:
          title: PLUS Counseling Complete
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRPLUS_PLUS_COUNSELING_COMP"
          x-lineageReferenceObject: RLRPLUS_PLUS_COUNSELING_COMP
        crCheckExpDate:
          title: Expiration Date
          type: string
          description: "Lineage reference object : RLRPLUS_CR_CHECK_EXP_DATE"
          format: date-time
          x-lineageReferenceObject: RLRPLUS_CR_CHECK_EXP_DATE
        origCreditStatus:
          title: Original Credit Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_ORIG_CREDIT_STATUS"
          x-lineageReferenceObject: RLRPLUS_ORIG_CREDIT_STATUS
        plusCounsCompDate:
          title: Counseling Complete Date
          type: string
          description: "Lineage reference object : RLRPLUS_PLUS_COUNS_COMP_DATE"
          format: date-time
          x-lineageReferenceObject: RLRPLUS_PLUS_COUNS_COMP_DATE
        crActionOpt:
          title: Credit Action Option
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_CR_ACTION_OPT"
          x-lineageReferenceObject: RLRPLUS_CR_ACTION_OPT
        creditCheckDate:
          title: Credit Status Date
          type: string
          description: "Lineage reference object : RLRPLUS_CREDIT_CHECK_DATE"
          format: date-time
          x-lineageReferenceObject: RLRPLUS_CREDIT_CHECK_DATE
        creditReqMet:
          title: Credit Requirements Met
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRPLUS_CREDIT_REQ_MET"
          x-lineageReferenceObject: RLRPLUS_CREDIT_REQ_MET
        csDocumentId:
          title: Credit Status Document ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_CS_DOCUMENT_ID"
          x-lineageReferenceObject: RLRPLUS_CS_DOCUMENT_ID
        endorserAmt:
          title: Endorser Amount
          maxLength: 12
          type: number
          description: "Lineage reference object : RLRPLUS_ENDORSER_AMT"
          x-lineageReferenceObject: RLRPLUS_ENDORSER_AMT
        endorserApproved:
          title: Endorser Approved
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRPLUS_ENDORSER_APPROVED"
          x-lineageReferenceObject: RLRPLUS_ENDORSER_APPROVED
        plusAppId:
          title: PLUS Application ID
          maxLength: 10
          type: number
          description: "Lineage reference object : RLRPLUS_PLUS_APP_ID, Lookup lineage
            reference object : RLRPAPP"
          x-lineageReferenceObject: RLRPLUS_PLUS_APP_ID
          x-lineageLookupReferenceObject: RLRPAPP
        requestAmt:
          title: Requested Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : RLRPLUS_REQUEST_AMT"
          x-lineageReferenceObject: RLRPLUS_REQUEST_AMT
        creditCheckInd:
          title: Credit Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_CREDIT_CHECK_IND"
          x-lineageReferenceObject: RLRPLUS_CREDIT_CHECK_IND
        plusToStudent:
          title: Parent PLUS to Student
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRPLUS_PLUS_TO_STUDENT"
          x-lineageReferenceObject: RLRPLUS_PLUS_TO_STUDENT
        crActionStatus:
          title: Credit Action Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_CR_ACTION_STATUS"
          x-lineageReferenceObject: RLRPLUS_CR_ACTION_STATUS
        reconsiderEligible:
          title: Reconsideration Eligible
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRPLUS_RECONSIDER_ELIGIBLE"
          x-lineageReferenceObject: RLRPLUS_RECONSIDER_ELIGIBLE
        crOverrideCde:
          title: Credit Override Code
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_CR_OVERRIDE_CDE"
          x-lineageReferenceObject: RLRPLUS_CR_OVERRIDE_CDE
        plusCounsExpDate:
          title: Counseling Expiration Date
          type: string
          description: "Lineage reference object : RLRPLUS_PLUS_COUNS_EXP_DATE"
          format: date-time
          x-lineageReferenceObject: RLRPLUS_PLUS_COUNS_EXP_DATE
        relationship:
          title: Relationship to Student
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_RELATIONSHIP"
          x-lineageReferenceObject: RLRPLUS_RELATIONSHIP
        borrowerIdNo:
          title: Borrower ID
          maxLength: 2
          type: string
          description: "Lineage reference object : RLRPLUS_BORROWER_ID_NO, Lookup lineage
            reference object : RLRDBOR,RLRCBID,RLRCBID"
          x-lineageReferenceObject: RLRPLUS_BORROWER_ID_NO
          x-lineageLookupReferenceObject: RLRDBOR,RLRCBID,RLRCBID
        crAppealStatus:
          title: Credit Appeal Status
          maxLength: 30
          type: string
          description: "Lineage reference object : RLRPLUS_CR_APPEAL_STATUS"
          x-lineageReferenceObject: RLRPLUS_CR_APPEAL_STATUS
      x-lineageReferenceObject: rlrplus
    direct-loan-origination-plus-data-credit-data-1.0.0_get_request:
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    direct-loan-origination-plus-data-credit-data-1.0.0_qapi_post:
      required:
        - id
        - keyblckAidyCode
      type: object
      properties:
        id:
          type: string
        keyblckAidyCode:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
