openapi: 3.0.0
info:
  title: ca-workforce-innovation-and-opportunity-act-copy
  description: API for SVAWIOA administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SVAWIOA
  x-source-domain: Student
  x-source-title: Workforce Innovation and Opportunity Act (WIOA) (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-workforce-innovation-and-opportunity-act-copy:
    post:
      tags:
        - ca-workforce-innovation-and-opportunity-act-copy
      summary: Creates a new resource in SVAWIOA
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-workforce-innovation-and-opportunity-act-copy-1.\
                0.0_post_request"
            example:
              svawioaTermCode: 201415
              svawioaDicdCode: 105
              id: 12
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-workforce-innovation-and-opportunity-act-copy-1.\
                    0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-workforce-innovation-and-opportunity-act-copy: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-workforce-innovation-and-opportunity-act-copy-1.0.0_post_response:
      type: object
      properties:
        ecdvDesc:
          title: Economically Disadvantaged Status Description
          type: string
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRECDV_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRECDV_ACTIVITY_DATE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRECDV_USER_ID"
          x-lineageReferenceObject: SVRECDV_USER_ID
        ecdvCode:
          title: Economically Disadvantaged Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRECDV_ECDV_CODE, Lookup lineage
            reference object : svvecdv"
          x-lineageReferenceObject: SVRECDV_ECDV_CODE
          x-lineageLookupReferenceObject: svvecdv
      x-lineageReferenceObject: svrecdv
    ca-workforce-innovation-and-opportunity-act-copy-1.0.0_post_request:
      type: object
      properties:
        svawioaTermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : svawioaTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svawioaTermCode
          x-lineageLookupReferenceObject: stvterm
        svawioaDicdCode:
          title: District ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svawioaDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svawioaDicdCode
          x-lineageLookupReferenceObject: gtvdicd
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
