openapi: 3.0.0
info:
  title: comment-billing-mass-data-entry
  description: API for TGACMAS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TGACMAS
  x-source-domain: Student
  x-source-title: Comment Mass Entry Form
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/comment-billing-mass-data-entry:
    post:
      tags:
        - comment-billing-mass-data-entry
      summary: Creates a new resource in TGACMAS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/comment-billing-mass-data-entry-1.0.0_post_request"
            example:
              keyblocOrigCode: ACCT
              keyblocComment: these are tests
              enddate: 2021-04-06
              commentCode: COLL
              keyblocTermCode: 201520
              keyblocTextCode: TEXT3
              keyblocCommentCode: COLL
              keyblocEnddate: 2021-04-06
              id: A00010003
              origCode: ACCT
              termCode: 201520
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/comment-billing-mass-data-entry-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/comment-billing-mass-data-entry: {}
components:
  schemas:
    comment-billing-mass-data-entry-1.0.0_post_request:
      required:
        - commentCode
      type: object
      properties:
        keyblocOrigCode:
          title: Originator
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocOrigCode, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: keyblocOrigCode
          x-lineageLookupReferenceObject: stvorig
        keyblocComment:
          title: Comment
          maxLength: 32000
          description: "Lineage reference object : keyblocComment"
          x-lineageReferenceObject: keyblocComment
        keyblocTermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : keyblocTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCode
          x-lineageLookupReferenceObject: stvterm
        keyblocTextCode:
          title: Text
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTextCode"
          x-lineageReferenceObject: keyblocTextCode
        restrictUpdateInd:
          title: Restrict Update
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCMNT_RESTRICT_UPDATE_IND"
          x-lineageReferenceObject: TBRCMNT_RESTRICT_UPDATE_IND
        keyblocCommentCode:
          title: Comment Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocCommentCode, Lookup lineage
            reference object : ttvcmnt"
          x-lineageReferenceObject: keyblocCommentCode
          x-lineageLookupReferenceObject: ttvcmnt
        purgeInd:
          title: Purge
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCMNT_PURGE_IND"
          x-lineageReferenceObject: TBRCMNT_PURGE_IND
        origCode:
          title: Originator
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRCMNT_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: TBRCMNT_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        keyblocUpdateInd:
          title: Restrict Update
          maxLength: 1
          type: string
          description: "Lineage reference object : keyblocRestrictUpdateInd"
          x-lineageReferenceObject: keyblocRestrictUpdateInd
        enddate:
          title: End Date
          maxLength: 26
          type: string
          description: "Lineage reference object : TBRCMNT_ENDDATE"
          format: date-time
          x-lineageReferenceObject: TBRCMNT_ENDDATE
        commentCode:
          title: Comment Type
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRCMNT_COMMENT_CODE, Lookup lineage
            reference object : ttvcmnt"
          x-lineageReferenceObject: TBRCMNT_COMMENT_CODE
          x-lineageLookupReferenceObject: ttvcmnt
        keyblocPurgeInd:
          title: Purge
          maxLength: 1
          type: string
          description: "Lineage reference object : keyblocPurgeInd"
          x-lineageReferenceObject: keyblocPurgeInd
        keyblocEnddate:
          title: End Date
          maxLength: 26
          type: string
          description: "Lineage reference object : keyblocEnddate"
          format: date-time
          x-lineageReferenceObject: keyblocEnddate
        id:
          title: ID
          maxLength: 9
          type: string
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRCMNT_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBRCMNT_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: TBRCMNT
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    comment-billing-mass-data-entry-1.0.0_post_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              keyblocOrigCode:
                title: Originator
                maxLength: 30
                type: string
                description: "Lineage reference object : keyblocOrigCode, Lookup lineage
                  reference object : stvorig"
                x-lineageReferenceObject: keyblocOrigCode
                x-lineageLookupReferenceObject: stvorig
              keyblocComment:
                title: Comment
                maxLength: 32000
                description: "Lineage reference object : keyblocComment"
                x-lineageReferenceObject: keyblocComment
              keyblocTermCode:
                title: Term
                maxLength: 6
                type: string
                description: "Lineage reference object : keyblocTermCode, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: keyblocTermCode
                x-lineageLookupReferenceObject: stvterm
              keyblocTextCode:
                title: Text
                maxLength: 30
                type: string
                description: "Lineage reference object : keyblocTextCode"
                x-lineageReferenceObject: keyblocTextCode
              keyblocPurgeInd:
                title: Purge
                maxLength: 1
                type: string
                description: "Lineage reference object : keyblocPurgeInd"
                x-lineageReferenceObject: keyblocPurgeInd
              keyblocCommentCode:
                title: Comment Type
                maxLength: 30
                type: string
                description: "Lineage reference object : keyblocCommentCode, Lookup lineage
                  reference object : ttvcmnt"
                x-lineageReferenceObject: keyblocCommentCode
                x-lineageLookupReferenceObject: ttvcmnt
              keyblocEnddate:
                title: End Date
                maxLength: 26
                type: string
                description: "Lineage reference object : keyblocEnddate"
                format: date-time
                x-lineageReferenceObject: keyblocEnddate
              keyblocRestrictUpdateInd:
                title: Restrict Update
                maxLength: 1
                type: string
                description: "Lineage reference object : keyblocRestrictUpdateInd"
                x-lineageReferenceObject: keyblocRestrictUpdateInd
            x-lineageReferenceObject: key_block
        tbrcmnt:
          type: array
          items:
            required:
              - commentCode
            type: object
            properties:
              enddate:
                title: End Date
                maxLength: 26
                type: string
                description: "Lineage reference object : TBRCMNT_ENDDATE"
                format: date-time
                x-lineageReferenceObject: TBRCMNT_ENDDATE
              commentCode:
                title: Comment Type
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRCMNT_COMMENT_CODE, Lookup lineage
                  reference object : ttvcmnt"
                x-lineageReferenceObject: TBRCMNT_COMMENT_CODE
                x-lineageLookupReferenceObject: ttvcmnt
              name:
                title: Name
                maxLength: 230
                type: string
              restrictUpdateInd:
                title: Restrict Update
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRCMNT_RESTRICT_UPDATE_IND"
                x-lineageReferenceObject: TBRCMNT_RESTRICT_UPDATE_IND
              id:
                title: ID
                maxLength: 9
                type: string
              purgeInd:
                title: Purge
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRCMNT_PURGE_IND"
                x-lineageReferenceObject: TBRCMNT_PURGE_IND
              origCode:
                title: Originator
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRCMNT_ORIG_CODE, Lookup lineage
                  reference object : stvorig"
                x-lineageReferenceObject: TBRCMNT_ORIG_CODE
                x-lineageLookupReferenceObject: stvorig
              termCode:
                title: Term
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRCMNT_TERM_CODE, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: TBRCMNT_TERM_CODE
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: tbrcmnt
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
