openapi: 3.0.0
info:
  title: history-jobs-inquiry
  description: API for PHIJOBS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PHIJOBS
  x-source-domain: Human Resources
  x-source-title: History Jobs Inquiry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/history-jobs-inquiry:
    get:
      tags:
        - history-jobs-inquiry
      summary: Return resources from PHIJOBS
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: year
          in: query
          required: true
          schema:
            type: string
        - name: pictCode
          in: query
          required: true
          schema:
            type: string
        - name: payno
          in: query
          required: true
          schema:
            type: string
        - name: coas
          in: query
          required: false
          schema:
            type: string
        - name: orgn
          in: query
          required: false
          schema:
            type: string
        - name: trCode
          in: query
          required: false
          schema:
            type: string
        - name: idSeq
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_ID_SEQ
        - name: lastNameSeq
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_LAST_NAME_SEQ
        - name: firstNameSeq
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_FIRST_NAME_SEQ
        - name: posn
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_POSN
        - name: suff
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_SUFF
        - name: effectiveDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_EFFECTIVE_DATE
        - name: disp
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHVJOBS_DISP
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/history-jobs-inquiry-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/history-jobs-inquiry:
    post:
      tags:
        - history-jobs-inquiry QAPI (Query by POST)
      summary: Return resources from PHIJOBS
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/history-jobs-inquiry-1.0.0_get_request"
            example:
              coas: B
              payno: 1
              pictCode: MN
              year: 2020
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/history-jobs-inquiry-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    history-jobs-inquiry-1.0.0_qapi_post:
      required:
        - payno
        - pictCode
        - year
      type: object
      properties:
        year:
          type: string
        pictCode:
          type: string
        payno:
          type: string
        coas:
          type: string
        orgn:
          type: string
        trCode:
          type: string
        idSeq:
          maxLength: 9
          type: string
          description: "Lineage reference object : PHVJOBS_ID_SEQ"
          x-lineageReferenceObject: PHVJOBS_ID_SEQ
        lastNameSeq:
          maxLength: 60
          type: string
          description: "Lineage reference object : PHVJOBS_LAST_NAME_SEQ"
          x-lineageReferenceObject: PHVJOBS_LAST_NAME_SEQ
        firstNameSeq:
          maxLength: 60
          type: string
          description: "Lineage reference object : PHVJOBS_FIRST_NAME_SEQ"
          x-lineageReferenceObject: PHVJOBS_FIRST_NAME_SEQ
        posn:
          maxLength: 6
          type: string
          description: "Lineage reference object : PHVJOBS_POSN"
          x-lineageReferenceObject: PHVJOBS_POSN
        suff:
          maxLength: 2
          type: string
          description: "Lineage reference object : PHVJOBS_SUFF"
          x-lineageReferenceObject: PHVJOBS_SUFF
        effectiveDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : PHVJOBS_EFFECTIVE_DATE"
          format: date-time
          x-lineageReferenceObject: PHVJOBS_EFFECTIVE_DATE
        disp:
          maxLength: 2
          type: string
          description: "Lineage reference object : PHVJOBS_DISP"
          x-lineageReferenceObject: PHVJOBS_DISP
    history-jobs-inquiry-1.0.0_get_response:
      type: object
      properties:
        idSeq:
          maxLength: 9
          type: string
          description: "Lineage reference object : PHVJOBS_ID_SEQ"
          x-lineageReferenceObject: PHVJOBS_ID_SEQ
        suff:
          maxLength: 2
          type: string
          description: "Lineage reference object : PHVJOBS_SUFF"
          x-lineageReferenceObject: PHVJOBS_SUFF
        hrs:
          maxLength: 7
          type: number
          description: "Lineage reference object : HRS"
          x-lineageReferenceObject: HRS
        units:
          maxLength: 7
          type: number
          description: "Lineage reference object : UNITS"
          x-lineageReferenceObject: UNITS
        disp:
          maxLength: 2
          type: string
          description: "Lineage reference object : PHVJOBS_DISP"
          x-lineageReferenceObject: PHVJOBS_DISP
        effectiveDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : PHVJOBS_EFFECTIVE_DATE"
          format: date-time
          x-lineageReferenceObject: PHVJOBS_EFFECTIVE_DATE
        lastNameSeq:
          maxLength: 60
          type: string
          description: "Lineage reference object : PHVJOBS_LAST_NAME_SEQ"
          x-lineageReferenceObject: PHVJOBS_LAST_NAME_SEQ
        posn:
          maxLength: 6
          type: string
          description: "Lineage reference object : PHVJOBS_POSN"
          x-lineageReferenceObject: PHVJOBS_POSN
        firstNameSeq:
          maxLength: 60
          type: string
          description: "Lineage reference object : PHVJOBS_FIRST_NAME_SEQ"
          x-lineageReferenceObject: PHVJOBS_FIRST_NAME_SEQ
      x-lineageReferenceObject: phvjobs
    history-jobs-inquiry-1.0.0_get_request:
      required:
        - year
        - pictCode
        - payno
      type: object
      properties:
        year:
          title: Year
          maxLength: 4
          type: string
          description: "Lineage reference object : year"
          x-lineageReferenceObject: year
        disp:
          maxLength: 2
          type: string
          description: "Lineage reference object : PHVJOBS_DISP"
          x-lineageReferenceObject: PHVJOBS_DISP
        lastNameSeq:
          maxLength: 60
          type: string
          description: "Lineage reference object : PHVJOBS_LAST_NAME_SEQ"
          x-lineageReferenceObject: PHVJOBS_LAST_NAME_SEQ
        posn:
          maxLength: 6
          type: string
          description: "Lineage reference object : PHVJOBS_POSN"
          x-lineageReferenceObject: PHVJOBS_POSN
        firstNameSeq:
          maxLength: 60
          type: string
          description: "Lineage reference object : PHVJOBS_FIRST_NAME_SEQ"
          x-lineageReferenceObject: PHVJOBS_FIRST_NAME_SEQ
        coas:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : coas"
          x-lineageReferenceObject: coas
        payno:
          title: Payroll Number
          maxLength: 3
          type: number
          description: "Lineage reference object : payno"
          x-lineageReferenceObject: payno
        idSeq:
          maxLength: 9
          type: string
          description: "Lineage reference object : PHVJOBS_ID_SEQ"
          x-lineageReferenceObject: PHVJOBS_ID_SEQ
        pictCode:
          title: Payroll ID
          maxLength: 2
          type: string
          description: "Lineage reference object : pictCode"
          x-lineageReferenceObject: pictCode
        trCode:
          title: Time Sheet Method
          maxLength: 1
          type: string
          description: "Lineage reference object : trCode"
          x-lineageReferenceObject: trCode
        suff:
          maxLength: 2
          type: string
          description: "Lineage reference object : PHVJOBS_SUFF"
          x-lineageReferenceObject: PHVJOBS_SUFF
        orgn:
          title: Organization
          maxLength: 6
          type: string
          description: "Lineage reference object : orgn"
          x-lineageReferenceObject: orgn
        effectiveDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : PHVJOBS_EFFECTIVE_DATE"
          format: date-time
          x-lineageReferenceObject: PHVJOBS_EFFECTIVE_DATE
      x-lineageReferenceObject: PHVJOBS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
