openapi: 3.0.0
info:
  title: student-course-registration-curricula-inactivate
  description: API for SFAREGS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SFAREGS
  x-source-domain: Student
  x-source-title: Student Course Registration
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-course-registration-curricula-inactivate:
    put:
      tags:
        - student-course-registration-curricula-inactivate
      summary: Updates an existing resource in SFAREGS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-course-registration-curricula-inactivate-1.\
                0.0_put_request"
            example:
              lfstCode: CONCENTRATION
              priorityNo: 3
              printBill: N
              printSchedule: Y
              term: 201410
              rstsEstsDate: 2022-02-16
              id: HOSWEB011
              majrCode: 102
              cactCode: ACTIVE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-course-registration-curricula-inactivate-1.\
                    0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/student-course-registration-curricula-inactivate: {}
components:
  schemas:
    student-course-registration-curricula-inactivate-1.0.0_put_response:
      type: object
      properties:
        termCodeCtlg:
          title: Catalog
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE_CTLG, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE_CTLG
          x-lineageLookupReferenceObject: stvterm
        majrCodeAttach:
          title: Attached to Major
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_MAJR_CODE_ATTACH, Lookup
            lineage reference object : sobcact,stvmajr,sotlfos,sotlfos"
          x-lineageReferenceObject: SOVLFOS_MAJR_CODE_ATTACH
          x-lineageLookupReferenceObject: sobcact,stvmajr,sotlfos,sotlfos
        seqno:
          title: Seq Num
          maxLength: 5
          type: number
          description: "Lineage reference object : SOVLFOS_SEQNO"
          x-lineageReferenceObject: SOVLFOS_SEQNO
        tmstDesc:
          title: Full or Part Time Description
          type: string
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SOVLFOS_END_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_END_DATE
        majrDesc:
          title: Field of Study Description
          type: string
        tmstCode:
          title: Full or Part Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TMST_CODE, Lookup lineage
            reference object : stvtmst"
          x-lineageReferenceObject: SOVLFOS_TMST_CODE
          x-lineageLookupReferenceObject: stvtmst
        lfosRolledInd:
          maxLength: 30
          type: string
        majrCode:
          title: Field of Study
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_MAJR_CODE, Lookup lineage
            reference object : stvmajr,sovlfos"
          x-lineageReferenceObject: SOVLFOS_MAJR_CODE
          x-lineageLookupReferenceObject: stvmajr,sovlfos
        termCodeEnd:
          title: End Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE_END, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE_END
          x-lineageLookupReferenceObject: stvterm
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_USER_ID"
          x-lineageReferenceObject: SOVLFOS_USER_ID
        currentInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOVLFOS_CURRENT_IND"
          x-lineageReferenceObject: SOVLFOS_CURRENT_IND
        lfstCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_LFST_CODE, Lookup lineage
            reference object : gtvlfst"
          x-lineageReferenceObject: SOVLFOS_LFST_CODE
          x-lineageLookupReferenceObject: gtvlfst
        activityDate:
          title: Created
          maxLength: 26
          type: string
          description: "Lineage reference object : SOVLFOS_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_ACTIVITY_DATE
        priorityNo:
          title: Priority
          maxLength: 5
          type: number
          description: "Lineage reference object : SOVLFOS_PRIORITY_NO"
          x-lineageReferenceObject: SOVLFOS_PRIORITY_NO
        attachConcDesc:
          title: Attached to Major Description
          type: string
        deptDesc:
          title: Department Description
          type: string
        cstsCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_CSTS_CODE, Lookup lineage
            reference object : stvcsts"
          x-lineageReferenceObject: SOVLFOS_CSTS_CODE
          x-lineageLookupReferenceObject: stvcsts
        deptCode:
          title: Department
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_DEPT_CODE, Lookup lineage
            reference object : stvdept"
          x-lineageReferenceObject: SOVLFOS_DEPT_CODE
          x-lineageLookupReferenceObject: stvdept
        lfstCodeDesc:
          title: Type Description
          type: string
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SOVLFOS_START_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_START_DATE
        cactCode:
          title: Activity
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_CACT_CODE, Lookup lineage
            reference object : stvcact,sobcact"
          x-lineageReferenceObject: SOVLFOS_CACT_CODE
          x-lineageLookupReferenceObject: stvcact,sobcact
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorlfos
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    student-course-registration-curricula-inactivate-1.0.0_put_request:
      type: object
      properties:
        criteria.userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_USER_ID"
          x-lineageReferenceObject: SOVLFOS_USER_ID
        criteria.activityDate:
          title: Created
          maxLength: 26
          type: string
          description: "Lineage reference object : SOVLFOS_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_ACTIVITY_DATE
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SOVLFOS_END_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_END_DATE
        printBill:
          title: Print Bill
          maxLength: 1
          type: string
          description: "Lineage reference object : printBill"
          x-lineageReferenceObject: printBill
        criteria.endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SOVLFOS_END_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_END_DATE
        criteria.lfosRolledInd:
          maxLength: 30
          type: string
        criteria.deptCode:
          title: Department
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_DEPT_CODE, Lookup lineage
            reference object : stvdept"
          x-lineageReferenceObject: SOVLFOS_DEPT_CODE
          x-lineageLookupReferenceObject: stvdept
        criteria.termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        criteria.startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SOVLFOS_START_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_START_DATE
        viewCurrent:
          title: View Current/Active Curricula
          maxLength: 30
          type: string
          description: "Lineage reference object : viewCurrent"
          x-lineageReferenceObject: viewCurrent
        criteria.termCodeEnd:
          title: End Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE_END, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE_END
          x-lineageLookupReferenceObject: stvterm
        majrCode:
          title: Field of Study
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_MAJR_CODE, Lookup lineage
            reference object : stvmajr,sovlfos"
          x-lineageReferenceObject: SOVLFOS_MAJR_CODE
          x-lineageLookupReferenceObject: stvmajr,sovlfos
        criteria.lfstCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_LFST_CODE, Lookup lineage
            reference object : gtvlfst"
          x-lineageReferenceObject: SOVLFOS_LFST_CODE
          x-lineageLookupReferenceObject: gtvlfst
        lfstCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_LFST_CODE, Lookup lineage
            reference object : gtvlfst"
          x-lineageReferenceObject: SOVLFOS_LFST_CODE
          x-lineageLookupReferenceObject: gtvlfst
        holdPassword:
          title: Holds
          maxLength: 3
          type: string
          description: "Lineage reference object : holdPassword"
          x-lineageReferenceObject: holdPassword
        priorityNo:
          title: Priority
          maxLength: 5
          type: number
          description: "Lineage reference object : SOVLFOS_PRIORITY_NO"
          x-lineageReferenceObject: SOVLFOS_PRIORITY_NO
        term:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : term, Lookup lineage reference object :
            stvterm"
          x-lineageReferenceObject: term
          x-lineageLookupReferenceObject: stvterm
        criteria.majrCode:
          title: Field of Study
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_MAJR_CODE, Lookup lineage
            reference object : stvmajr,sovlfos"
          x-lineageReferenceObject: SOVLFOS_MAJR_CODE
          x-lineageLookupReferenceObject: stvmajr,sovlfos
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        cstsCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_CSTS_CODE, Lookup lineage
            reference object : stvcsts"
          x-lineageReferenceObject: SOVLFOS_CSTS_CODE
          x-lineageLookupReferenceObject: stvcsts
        criteria.priorityNo:
          title: Priority
          maxLength: 5
          type: number
          description: "Lineage reference object : SOVLFOS_PRIORITY_NO"
          x-lineageReferenceObject: SOVLFOS_PRIORITY_NO
        criteria.termCodeCtlg:
          title: Catalog
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE_CTLG, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE_CTLG
          x-lineageLookupReferenceObject: stvterm
        cactCode:
          title: Activity
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_CACT_CODE, Lookup lineage
            reference object : stvcact,sobcact"
          x-lineageReferenceObject: SOVLFOS_CACT_CODE
          x-lineageLookupReferenceObject: stvcact,sobcact
        termCodeCtlg:
          title: Catalog
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE_CTLG, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE_CTLG
          x-lineageLookupReferenceObject: stvterm
        criteria.currentInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOVLFOS_CURRENT_IND"
          x-lineageReferenceObject: SOVLFOS_CURRENT_IND
        tmstCode:
          title: Full or Part Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TMST_CODE, Lookup lineage
            reference object : stvtmst"
          x-lineageReferenceObject: SOVLFOS_TMST_CODE
          x-lineageLookupReferenceObject: stvtmst
        printSchedule:
          title: Print Schedule
          maxLength: 1
          type: string
          description: "Lineage reference object : printSchedule"
          x-lineageReferenceObject: printSchedule
        criteria.cactCode:
          title: Activity
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_CACT_CODE, Lookup lineage
            reference object : stvcact,sobcact"
          x-lineageReferenceObject: SOVLFOS_CACT_CODE
          x-lineageLookupReferenceObject: stvcact,sobcact
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        termCodeEnd:
          title: End Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TERM_CODE_END, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SOVLFOS_TERM_CODE_END
          x-lineageLookupReferenceObject: stvterm
        criteria.cstsCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_CSTS_CODE, Lookup lineage
            reference object : stvcsts"
          x-lineageReferenceObject: SOVLFOS_CSTS_CODE
          x-lineageLookupReferenceObject: stvcsts
        criteria.majrCodeAttach:
          title: Attached to Major
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_MAJR_CODE_ATTACH, Lookup
            lineage reference object : sobcact,stvmajr,sotlfos,sotlfos"
          x-lineageReferenceObject: SOVLFOS_MAJR_CODE_ATTACH
          x-lineageLookupReferenceObject: sobcact,stvmajr,sotlfos,sotlfos
        rstsEstsDate:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : rstsEstsDate"
          format: date-time
          x-lineageReferenceObject: rstsEstsDate
        criteria.tmstCode:
          title: Full or Part Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_TMST_CODE, Lookup lineage
            reference object : stvtmst"
          x-lineageReferenceObject: SOVLFOS_TMST_CODE
          x-lineageLookupReferenceObject: stvtmst
        deptCode:
          title: Department
          maxLength: 30
          type: string
          description: "Lineage reference object : SOVLFOS_DEPT_CODE, Lookup lineage
            reference object : stvdept"
          x-lineageReferenceObject: SOVLFOS_DEPT_CODE
          x-lineageLookupReferenceObject: stvdept
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SOVLFOS_START_DATE"
          format: date-time
          x-lineageReferenceObject: SOVLFOS_START_DATE
      x-lineageReferenceObject: SORLFOS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
