openapi: 3.0.0
info:
  title: ca-schedule-academic-calender-rules
  description: API for SSAACRL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SSAACRL
  x-source-domain: Student
  x-source-title: Schedule Academic Calendar Rules (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-schedule-academic-calender-rules:
    get:
      tags:
        - ca-schedule-academic-calender-rules
      summary: Return resources from SSAACRL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckTermCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckAcclCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-schedule-academic-calender-rules-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - ca-schedule-academic-calender-rules
      summary: Updates an existing resource in SSAACRL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-schedule-academic-calender-rules-1.0.0_put_reque\
                st"
            example:
              keyblckAcclCode: A1
              keyblckTermCode: 200323
              census1Date: 06/09/2021
              enrlCutOffDate: 06/11/2021
              acadCutOffDate: 13/06/2021
              dropCutOffDate: 14/06/2021
              census2Date: 06/10/2021
              refundCutoffDate: 06/12/2021
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-schedule-academic-calender-rules-1.0.0_put_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-schedule-academic-calender-rules:
    post:
      tags:
        - ca-schedule-academic-calender-rules QAPI (Query by POST)
      summary: Return resources from SSAACRL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-schedule-academic-calender-rules-1.0.0_get_reque\
                st"
            example:
              keyblckAcclCode: AS
              keyblckTermCode: 200323
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-schedule-academic-calender-rules-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    ca-schedule-academic-calender-rules-1.0.0_get_response:
      type: object
      properties:
        percentToDrop:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_DROP"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_DROP
        percentToRefund:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_REFUND"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_REFUND
        percentToCensus2:
          title: Number of Days
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_CENSUS_2"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_CENSUS_2
        percentToCensus1:
          title: Percentage of Days
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_CENSUS_1"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_CENSUS_1
        percentToAcad:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_ACAD"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_ACAD
        daysToRefund:
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_REFUND"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_REFUND
        census2Date:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_CENSUS_2_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_CENSUS_2_DATE
        refundCutoffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_REFUND_CUTOFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_REFUND_CUTOFF_DATE
        percentToEnrl:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_ENRL"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_ENRL
        daysToDrop:
          title: Drop Without Penalty
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_DROP"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_DROP
        daysToCensus1:
          title: Census One
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_CENSUS_1"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_CENSUS_1
        daysToCensus2:
          title: Census Two
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_CENSUS_2"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_CENSUS_2
        census1Date:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_CENSUS_1_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_CENSUS_1_DATE
        daysToEnrl:
          title: Enrollment
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_ENRL"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_ENRL
        acadCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_ACAD_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_ACAD_CUT_OFF_DATE
        dropCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_DROP_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_DROP_CUT_OFF_DATE
        enrlCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_ENRL_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_ENRL_CUT_OFF_DATE
        daysToAcad:
          title: Record Academic History
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_ACAD"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_ACAD
      x-lineageReferenceObject: ssbacrl
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-schedule-academic-calender-rules-1.0.0_get_request:
      type: object
      properties:
        keyblckAcclCode:
          title: Calendar Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAcclCode, Lookup lineage
            reference object : stvaccl"
          x-lineageReferenceObject: keyblckAcclCode
          x-lineageLookupReferenceObject: stvaccl
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: KEY_BLOCK
    ca-schedule-academic-calender-rules-1.0.0_qapi_post:
      type: object
      properties:
        keyblckTermCode:
          type: string
        keyblckAcclCode:
          type: string
    ca-schedule-academic-calender-rules-1.0.0_put_response:
      type: object
      properties:
        percentToDrop:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_DROP"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_DROP
        percentToRefund:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_REFUND"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_REFUND
        percentToCensus2:
          title: Number of Days
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_CENSUS_2"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_CENSUS_2
        percentToCensus1:
          title: Percentage of Days
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_CENSUS_1"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_CENSUS_1
        percentToAcad:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_ACAD"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_ACAD
        daysToRefund:
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_REFUND"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_REFUND
        census2Date:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_CENSUS_2_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_CENSUS_2_DATE
        refundCutoffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_REFUND_CUTOFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_REFUND_CUTOFF_DATE
        percentToEnrl:
          maxLength: 7
          type: number
          description: "Lineage reference object : SSBACRL_PERCENT_TO_ENRL"
          x-lineageReferenceObject: SSBACRL_PERCENT_TO_ENRL
        daysToDrop:
          title: Drop Without Penalty
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_DROP"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_DROP
        daysToCensus1:
          title: Census One
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_CENSUS_1"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_CENSUS_1
        daysToCensus2:
          title: Census Two
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_CENSUS_2"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_CENSUS_2
        census1Date:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_CENSUS_1_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_CENSUS_1_DATE
        daysToEnrl:
          title: Enrollment
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_ENRL"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_ENRL
        acadCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_ACAD_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_ACAD_CUT_OFF_DATE
        dropCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_DROP_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_DROP_CUT_OFF_DATE
        enrlCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_ENRL_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_ENRL_CUT_OFF_DATE
        daysToAcad:
          title: Record Academic History
          maxLength: 5
          type: number
          description: "Lineage reference object : SSBACRL_DAYS_TO_ACAD"
          x-lineageReferenceObject: SSBACRL_DAYS_TO_ACAD
      x-lineageReferenceObject: ssbacrl
    ca-schedule-academic-calender-rules-1.0.0_put_request:
      type: object
      properties:
        keyblckAcclCode:
          title: Calendar Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAcclCode, Lookup lineage
            reference object : stvaccl"
          x-lineageReferenceObject: keyblckAcclCode
          x-lineageLookupReferenceObject: stvaccl
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        census1Date:
          title: Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_CENSUS_1_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_CENSUS_1_DATE
        enrlCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_ENRL_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_ENRL_CUT_OFF_DATE
        acadCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_ACAD_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_ACAD_CUT_OFF_DATE
        dropCutOffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_DROP_CUT_OFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_DROP_CUT_OFF_DATE
        census2Date:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_CENSUS_2_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_CENSUS_2_DATE
        refundCutoffDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SSBACRL_REFUND_CUTOFF_DATE"
          format: date-time
          x-lineageReferenceObject: SSBACRL_REFUND_CUTOFF_DATE
      x-lineageReferenceObject: SSBACRL
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
