openapi: 3.0.0
info:
  title: support-service-detail-service-assignment-copy
  description: API for SEADETL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SEADETL
  x-source-domain: Student
  x-source-title: Support Service Detail
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/support-service-detail-service-assignment-copy:
    post:
      tags:
        - support-service-detail-service-assignment-copy
      summary: Creates a new resource in SEADETL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/support-service-detail-service-assignment-copy-1.0.\
                0_post_request"
            example:
              termCodeEff: VUTE03
              ssgpCode: ADLT
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/support-service-detail-service-assignment-copy-1.0.\
                    0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/support-service-detail-service-assignment-copy: {}
components:
  schemas:
    support-service-detail-service-assignment-copy-1.0.0_post_request:
      type: object
      properties:
        termCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : seadetlTermCodeEff, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: seadetlTermCodeEff
          x-lineageLookupReferenceObject: stvterm
        ssgpCode:
          title: Service Group
          maxLength: 30
          type: string
          description: "Lineage reference object : seadetlSsgpCode, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: seadetlSsgpCode
          x-lineageLookupReferenceObject: stvssgp
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : seadetlId"
          x-lineageReferenceObject: seadetlId
      x-lineageReferenceObject: SEADETL_KEY_BLOCK
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    support-service-detail-service-assignment-copy-1.0.0_post_response:
      required:
        - sserCode
      type: object
      properties:
        seprCode:
          title: Service Provided
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SEPR_CODE, Lookup lineage
            reference object : stvsepr"
          x-lineageReferenceObject: SERDTSR_SEPR_CODE
          x-lineageLookupReferenceObject: stvsepr
        beginDate:
          title: Begin Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SERDTSR_BEGIN_DATE"
          format: date-time
          x-lineageReferenceObject: SERDTSR_BEGIN_DATE
        sserDescription:
          title: Description
          type: string
        endDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SERDTSR_END_DATE"
          format: date-time
          x-lineageReferenceObject: SERDTSR_END_DATE
        sprvCode:
          title: Service Provider
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SPRV_CODE, Lookup lineage
            reference object : stvsprv"
          x-lineageReferenceObject: SERDTSR_SPRV_CODE
          x-lineageLookupReferenceObject: stvsprv
        ssgpCode:
          title: Group
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SERDTSR_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        sserCode:
          title: Service
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SSER_CODE, Lookup lineage
            reference object : stvsser"
          x-lineageReferenceObject: SERDTSR_SSER_CODE
          x-lineageLookupReferenceObject: stvsser
        endcopy:
          maxLength: 1
          type: string
        ssstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SERDTSR_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
        ssrsCode:
          title: Result
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SSRS_CODE, Lookup lineage
            reference object : stvssrs"
          x-lineageReferenceObject: SERDTSR_SSRS_CODE
          x-lineageLookupReferenceObject: stvssrs
        origCode:
          title: Review
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SERDTSR_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        ssepCode:
          title: Exempt
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTSR_SSEP_CODE, Lookup lineage
            reference object : stvssep"
          x-lineageReferenceObject: SERDTSR_SSEP_CODE
          x-lineageLookupReferenceObject: stvssep
      x-lineageReferenceObject: serdtsr
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
