openapi: 3.0.0
info:
  title: direct-loan-originations-mpn
  description: API for RLADLOR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RLADLOR
  x-source-domain: Financial Aid
  x-source-title: Direct Loan Origination
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-loan-originations-mpn:
    get:
      tags:
        - direct-loan-originations-mpn
      summary: Return resources from RLADLOR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-mpn-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - direct-loan-originations-mpn
      summary: Updates an existing resource in RLADLOR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-loan-originations-mpn-1.0.0_put_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-mpn-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/direct-loan-originations-mpn:
    post:
      tags:
        - direct-loan-originations-mpn QAPI (Query by POST)
      summary: Return resources from RLADLOR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-loan-originations-mpn-1.0.0_get_request"
            example:
              keyblckAidyCode: 1718
              id: FASS30070
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-loan-originations-mpn-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    direct-loan-originations-mpn-1.0.0_get_response:
      type: object
      properties:
        rlrdlor2:
          type: array
          items:
            type: object
            properties:
              rlrdlorMpnId:
                title: MPN ID
                maxLength: 21
                type: string
                description: "Lineage reference object : RLRDLOR_MPN_ID, Lookup lineage
                  reference object : RLRDMPN,RFRASPC"
                x-lineageReferenceObject: RLRDLOR_MPN_ID
                x-lineageLookupReferenceObject: RLRDMPN,RFRASPC
              rlrdlorMpnLinkedInd:
                title: MPN Linked
                maxLength: 1
                type: string
                description: "Lineage reference object : RLRDLOR_MPN_LINKED_IND"
                x-lineageReferenceObject: RLRDLOR_MPN_LINKED_IND
            x-lineageReferenceObject: rlrdlor2
        rlrdmpn:
          type: array
          items:
            required:
              - borrowerFirstName
              - borrowerIdNo
              - firstName
            type: object
            properties:
              borrowerSsn:
                title: Social Security Number
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_BORROWER_SSN"
                x-lineageReferenceObject: RLRDMPN_BORROWER_SSN
              lastName:
                title: Last Name
                maxLength: 60
                type: string
                description: "Lineage reference object : RLRDMPN_LAST_NAME"
                x-lineageReferenceObject: RLRDMPN_LAST_NAME
              mpnStatusEffDate:
                title: MPN Status Date
                type: string
                description: "Lineage reference object : RLRDMPN_MPN_STATUS_EFF_DATE"
                format: date-time
                x-lineageReferenceObject: RLRDMPN_MPN_STATUS_EFF_DATE
              borrowerMi:
                title: Middle Initial
                maxLength: 60
                type: string
                description: "Lineage reference object : RLRDMPN_BORROWER_MI"
                x-lineageReferenceObject: RLRDMPN_BORROWER_MI
              seqNo:
                title: Sequence Number
                maxLength: 2
                type: number
                description: "Lineage reference object : RLRDMPN_SEQ_NO"
                x-lineageReferenceObject: RLRDMPN_SEQ_NO
              empnInd:
                title: E-MPN
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_EMPN_IND"
                x-lineageReferenceObject: RLRDMPN_EMPN_IND
              singleLoanInd:
                title: Single Loan
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_SINGLE_LOAN_IND"
                x-lineageReferenceObject: RLRDMPN_SINGLE_LOAN_IND
              expDesc:
                title: MPN Expiration Description
                maxLength: 70
                type: string
                description: "Lineage reference object : RLRDMPN_EXP_DESC"
                x-lineageReferenceObject: RLRDMPN_EXP_DESC
              birthDate:
                title: Date of Birth
                type: string
                description: "Lineage reference object : RLRDMPN_BIRTH_DATE"
                format: date-time
                x-lineageReferenceObject: RLRDMPN_BIRTH_DATE
              expDate:
                title: MPN Expiration Date
                type: string
                description: "Lineage reference object : RLRDMPN_EXP_DATE"
                format: date-time
                x-lineageReferenceObject: RLRDMPN_EXP_DATE
              borrowerBirthDate:
                title: Date of Birth
                type: string
                description: "Lineage reference object : RLRDMPN_BORROWER_BIRTH_DATE"
                format: date-time
                x-lineageReferenceObject: RLRDMPN_BORROWER_BIRTH_DATE
              ssn:
                title: Social Security Number
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_SSN"
                x-lineageReferenceObject: RLRDMPN_SSN
              expReason:
                title: MPN Expiration Reason
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_EXP_REASON"
                x-lineageReferenceObject: RLRDMPN_EXP_REASON
              firstName:
                title: First Name
                maxLength: 60
                type: string
                description: "Lineage reference object : RLRDMPN_FIRST_NAME"
                x-lineageReferenceObject: RLRDMPN_FIRST_NAME
              borrowerFirstName:
                title: First Name
                maxLength: 60
                type: string
                description: "Lineage reference object : RLRDMPN_BORROWER_FIRST_NAME"
                x-lineageReferenceObject: RLRDMPN_BORROWER_FIRST_NAME
              borrowerLastName:
                title: Last Name
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_BORROWER_LAST_NAME"
                x-lineageReferenceObject: RLRDMPN_BORROWER_LAST_NAME
              mpnType:
                title: MPN Type
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_MPN_TYPE"
                x-lineageReferenceObject: RLRDMPN_MPN_TYPE
              documentId:
                title: MPN Document ID
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_DOCUMENT_ID"
                x-lineageReferenceObject: RLRDMPN_DOCUMENT_ID
              mpnStatus:
                title: MPN Status
                maxLength: 30
                type: string
                description: "Lineage reference object : RLRDMPN_MPN_STATUS"
                x-lineageReferenceObject: RLRDMPN_MPN_STATUS
              expBatchId:
                title: MPN Batch ID
                maxLength: 23
                type: string
                description: "Lineage reference object : RLRDMPN_EXP_BATCH_ID"
                x-lineageReferenceObject: RLRDMPN_EXP_BATCH_ID
              mi:
                title: Middle Initial
                maxLength: 60
                type: string
                description: "Lineage reference object : RLRDMPN_MI"
                x-lineageReferenceObject: RLRDMPN_MI
              borrowerIdNo:
                title: PLUS Borrower ID Number
                maxLength: 2
                type: string
                description: "Lineage reference object : RLRDMPN_BORROWER_ID_NO"
                x-lineageReferenceObject: RLRDMPN_BORROWER_ID_NO
            x-lineageReferenceObject: rlrdmpn
    direct-loan-originations-mpn-1.0.0_put_request:
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        rlrdlorMpnLinkedInd:
          title: MPN Linked
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDLOR_MPN_LINKED_IND"
          x-lineageReferenceObject: RLRDLOR_MPN_LINKED_IND
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: RLRDLOR2
    direct-loan-originations-mpn-1.0.0_qapi_post:
      required:
        - id
        - keyblckAidyCode
      type: object
      properties:
        id:
          type: string
        keyblckAidyCode:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    direct-loan-originations-mpn-1.0.0_get_request:
      type: object
      properties:
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
    direct-loan-originations-mpn-1.0.0_put_response:
      type: object
      properties:
        rlrdlorMpnId:
          title: MPN ID
          maxLength: 21
          type: string
          description: "Lineage reference object : RLRDLOR_MPN_ID, Lookup lineage
            reference object : RLRDMPN,RFRASPC"
          x-lineageReferenceObject: RLRDLOR_MPN_ID
          x-lineageLookupReferenceObject: RLRDMPN,RFRASPC
        rlrdlorMpnLinkedInd:
          title: MPN Linked
          maxLength: 1
          type: string
          description: "Lineage reference object : RLRDLOR_MPN_LINKED_IND"
          x-lineageReferenceObject: RLRDLOR_MPN_LINKED_IND
      x-lineageReferenceObject: rlrdlor2
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
