openapi: 3.0.0
info:
  title: Students
  description: >-
    **API Deprecation Notice**



    Deprecated on: 30-Jun-2019



    Sunset on: 01-Jul-2021



    Description: V16.0.0 removes the measures object which is now reflected in student-grade-point-averages updates the type object to an array (renamed as types) updates the residency object to an array (renamed as residencies) and the cohort and tag objects in students were moved to student-cohort-assignments and student-tag-assignments respectfully so subscribers are able to associate changes specifically to a cohort or tag (attribute) assignment.



    ----


    Information about a person who is registered/enrolled in the institution as a student.
  version: "7.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Student
  x-deprecated-on: 2019-06-30
  x-sunset-on: 2021-07-01
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/students:
    get:
      summary: Return all resources
      description: This version of the resource uses a legacy filter format and cannot
        be displayed as a parameter.  Please refer to the API source
        documentation for more information.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENTS
      tags:
        - students
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-students.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      deprecated: true
  /api/students/{id}:
    get:
      summary: Return the requested resource
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENTS
      tags:
        - students
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Students for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v7.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-students.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      deprecated: true
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-students.json:
      title: Students
      description: Information about a person who is registered/enrolled in the
        institution as a student.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the student.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
        person:
          title: Person
          description: A reference to link a student to the common HEDM persons entity.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Person.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: persons
          additionalProperties: false
          required:
            - id
        type:
          title: Type
          description: The type of the student.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Type.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: student-types
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        cohorts:
          title: Cohorts
          description: Groupings of students for reporting/tracking purposes (cohorts) to
            which the student is associated.
          type: array
          items:
            title: Cohorts
            description: Groupings of students for reporting/tracking purposes (cohorts) to
              which the student is associated.
            type: object
            properties:
              id:
                title: ID
                description: The global identifier for the Cohorts.
                type: string
                format: guid
                pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                x-lineageLookupReferenceObject: student-cohorts
            additionalProperties: false
            required:
              - id
        tags:
          title: Tags
          description: A list of custom defined attributes or characteristics (tags)
            assigned to the student.
          type: array
          items:
            title: Tags
            description: A list of custom defined attributes or characteristics (tags)
              assigned to the student.
            type: object
            properties:
              id:
                title: ID
                description: The global identifier for the Tags.
                type: string
                format: guid
                pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                x-lineageLookupReferenceObject: student-tags
            additionalProperties: false
            required:
              - id
        residency:
          title: Residency
          description: "The residency type of the student (e.g.: international, in state,
            out of state, etc.)."
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Residency.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: residency-types
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        measures:
          title: Measures
          description: Measures (GPA, year classification) associated with the student by
            academic level.
          type: array
          items:
            type: object
            properties:
              level:
                title: Level
                description: The academic level associated with the student.
                type: object
                properties:
                  id:
                    title: ID
                    description: The global identifier for the Level.
                    type: string
                    format: guid
                    pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                    x-lineageLookupReferenceObject: academic-levels
                additionalProperties: false
                required:
                  - id
              performanceMeasure:
                title: Performance Measure
                description: Measurement of the student's performance by academic level. (e.g.
                  GPA).
                type: string
              classification:
                title: Classification
                description: The student's classification by academic level. (E.g Freshman,
                  Senior, ...)
                oneOf:
                  - type: object
                    properties:
                      id:
                        title: ID
                        description: The global identifier for the Classification.
                        type: string
                        format: guid
                        pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                        x-lineageLookupReferenceObject: student-classifications
                    additionalProperties: false
                    required:
                      - id
                  - type: object
                    maxProperties: 0
            additionalProperties: false
            required:
              - level
      required:
        - id
        - person
      additionalProperties: false
