openapi: 3.0.0
info:
  title: eu-ucas-applicant-selection
  description: API for SKAUAPP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SKAUAPP
  x-source-domain: Student
  x-source-title: UCAS Applicant Selection Form (Europe - UCAS)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/eu-ucas-applicant-selection:
    get:
      tags:
        - eu-ucas-applicant-selection
      summary: Return resources from SKAUAPP
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: skrsainApplicantNo
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SKRSAIN_APPLICANT_NO
        - name: skrsainPersonalid
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SKRSAIN_PERSONALID
        - name: skrsainAppSchemeCode
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SKRSAIN_APP_SCHEME_CODE
        - name: skrsainSource
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SKRSAIN_SOURCE
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-ucas-applicant-selection-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/eu-ucas-applicant-selection:
    post:
      tags:
        - eu-ucas-applicant-selection QAPI (Query by POST)
      summary: Return resources from SKAUAPP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/eu-ucas-applicant-selection-1.0.0_get_request"
            example:
              id: A00068666
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-ucas-applicant-selection-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    eu-ucas-applicant-selection-1.0.0_get_request:
      required:
        - id
      type: object
      properties:
        skrsainApplicantNo:
          title: Skrsain Ucasnum
          maxLength: 9
          type: string
          description: "Lineage reference object : SKRSAIN_APPLICANT_NO"
          x-lineageReferenceObject: SKRSAIN_APPLICANT_NO
        skrsainSource:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SKRSAIN_SOURCE"
          x-lineageReferenceObject: SKRSAIN_SOURCE
        skrsainAppSchemeCode:
          title: Application Scheme Code
          maxLength: 4
          type: string
          description: "Lineage reference object : SKRSAIN_APP_SCHEME_CODE"
          x-lineageReferenceObject: SKRSAIN_APP_SCHEME_CODE
        skrsainPersonalid:
          title: Personal Id
          maxLength: 30
          type: string
          description: "Lineage reference object : SKRSAIN_PERSONALID"
          x-lineageReferenceObject: SKRSAIN_PERSONALID
        name:
          maxLength: 230
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
      x-lineageReferenceObject: SKRSAIN_BLOCK
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    eu-ucas-applicant-selection-1.0.0_qapi_post:
      type: object
      properties:
        skrsainApplicantNo:
          title: Skrsain Ucasnum
          maxLength: 9
          type: string
          description: "Lineage reference object : SKRSAIN_APPLICANT_NO"
          x-lineageReferenceObject: SKRSAIN_APPLICANT_NO
        skrsainPersonalid:
          title: Personal Id
          maxLength: 30
          type: string
          description: "Lineage reference object : SKRSAIN_PERSONALID"
          x-lineageReferenceObject: SKRSAIN_PERSONALID
        skrsainAppSchemeCode:
          title: Application Scheme Code
          maxLength: 4
          type: string
          description: "Lineage reference object : SKRSAIN_APP_SCHEME_CODE"
          x-lineageReferenceObject: SKRSAIN_APP_SCHEME_CODE
        skrsainSource:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SKRSAIN_SOURCE"
          x-lineageReferenceObject: SKRSAIN_SOURCE
        id:
          title: ID
          maxLength: 9
          type: string
        name:
          type: string
    eu-ucas-applicant-selection-1.0.0_get_response:
      required:
        - id
      type: object
      properties:
        skrsainApplicantNo:
          title: Skrsain Ucasnum
          maxLength: 9
          type: string
          description: "Lineage reference object : SKRSAIN_APPLICANT_NO"
          x-lineageReferenceObject: SKRSAIN_APPLICANT_NO
        skrsainSource:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SKRSAIN_SOURCE"
          x-lineageReferenceObject: SKRSAIN_SOURCE
        skrsainAppSchemeCode:
          title: Application Scheme Code
          maxLength: 4
          type: string
          description: "Lineage reference object : SKRSAIN_APP_SCHEME_CODE"
          x-lineageReferenceObject: SKRSAIN_APP_SCHEME_CODE
        skrsainPersonalid:
          title: Personal Id
          maxLength: 30
          type: string
          description: "Lineage reference object : SKRSAIN_PERSONALID"
          x-lineageReferenceObject: SKRSAIN_PERSONALID
        rwname:
          maxLength: 230
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
      x-lineageReferenceObject: skrsain_block
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
