openapi: 3.0.0
info:
  title: Account Funds Available Transactions
  description: >-
    A check on the availability of funds for all accounts involved in
    transactions.


    Please refer to "API Integration Configuration Settings" section in the Banner Ethos API Handbook for details on API configuration settings that needs to be configured before using this QAPI.
  version: 11.1.0
  x-source-system: banner
  x-api-type: ethos
  x-source-domain: Finance
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /qapi/account-funds-available-transactions:
    post:
      summary: Checks for the availability of funds
      description: >-
        This is a QAPI and requires a /qapi in the route.


        The API allows the user to check on the availability of funds for all accounts involved in one or more transactions taking into account the net effect of the transactions.


        This QAPI supports below transaction types

        - travelEncumbranceCreate

        - travelEncumbranceAdjust

        - requisitions

        - purchase order (create order)

        - purchase order (change order)

        - travelExpense

        - otherInvoice
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACCOUNT_FUNDS_AVAILABLE
      tags:
        - account-funds-available-transactions
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-account-funds-available-transactions.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11.1.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v11+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-account-funds-available-transactions.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-account-funds-available-transactions.json:
      title: Account Funds Available Transactions
      description: A check on the availability of funds for all accounts involved in
        transactions.
      type: object
      properties:
        transactions:
          title: Transactions
          description: A list of associated general ledger transactions.
          type: array
          minItems: 1
          items:
            type: object
            properties:
              type:
                title: Type
                description: The type of the general ledger transaction (e.g. journal entry,
                  encumbrance, budget).
                enum:
                  - approvedBudget
                  - contingentBudget
                  - approvedBudgetAdjustment
                  - temporaryBudget
                  - temporaryBudgetAdjustment
                  - encumbranceOpenBalance
                  - generalEncumbranceCreate
                  - generalEncumbranceAdjust
                  - generalEncumbranceLiquidation
                  - generalEncumbranceClose
                  - payrollEncumbranceCreate
                  - payrollEncumbranceAdjust
                  - payrollEncumbranceLiquidation
                  - payrollEncumbranceClose
                  - travelEncumbranceCreate
                  - travelEncumbranceAdjust
                  - travelEncumbranceClose
                  - donation
                  - donationEndowed
                  - pledge
                  - pledgeEndowed
                  - financialAidTransmittal
                  - studentCharge
                  - studentInvoice
                  - studentPayment
                  - grantCharge
                  - grantInvoice
                  - grantPayment
                  - otherCharge
                  - otherInvoice
                  - otherPayment
                  - paymentAllocation
                  - depositAllocation
                  - miscCashReceipt
                  - cashDisbursement
                  - purchaseCardCharge
                  - miscGeneralLedgerTransaction
                  - purchaseJournal
                  - travelAdvance
                  - travelExpense
                  - yearEndCloseEntry
                  - payroll
                  - payrollWithLiquidation
                  - actualOpenBalance
                  - purchaseOrder
                  - requisition
                type: string
              transactionDate:
                title: Transaction Date
                description: The date on which the transaction is to occur.
                oneOf:
                  - type: string
                    format: date-time
                    pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                  - type: string
                    maxLength: 0
              transactionDetailLines:
                title: Transaction Detail Lines
                description: The detailed accounting lines associated with the transaction.
                type: array
                minItems: 1
                items:
                  type: object
                  properties:
                    accountingString:
                      title: Accounting String
                      description: The accounting string associated with the transaction detail line.
                      type: string
                      minLength: 1
                    fundsAvailable:
                      title: Funds Available
                      description: Status of the availability of funds.
                      oneOf:
                        - type: string
                          enum:
                            - available
                            - notAvailable
                            - overrideAvailable
                            - invalidAccountingString
                            - notApplicable
                        - type: string
                          maxLength: 0
                    type:
                      title: Type
                      description: The type of detailed accounting line (credit/debit).
                      enum:
                        - credit
                        - debit
                      type: string
                    amount:
                      title: Amount
                      description: The amount of the credit or debit.
                      format: currency
                      type: object
                      properties:
                        value:
                          title: Value
                          description: The monetary value
                          type: number
                        currency:
                          title: Currency
                          description: The ISO 4217 currency code
                          enum:
                            - AED
                            - AFN
                            - ALL
                            - AMD
                            - ANG
                            - AOA
                            - ARS
                            - AUD
                            - AWG
                            - AZN
                            - BAM
                            - BBD
                            - BDT
                            - BGN
                            - BHD
                            - BIF
                            - BMD
                            - BND
                            - BOB
                            - BRL
                            - BSD
                            - BTN
                            - BWP
                            - BYR
                            - BZD
                            - CAD
                            - CDF
                            - CHF
                            - CLP
                            - CNY
                            - COP
                            - CRC
                            - CUC
                            - CUP
                            - CVE
                            - CZK
                            - DJF
                            - DKK
                            - DOP
                            - DZD
                            - EGP
                            - ERN
                            - ETB
                            - EUR
                            - FJD
                            - FKP
                            - GBP
                            - GEL
                            - GHS
                            - GIP
                            - GMD
                            - GNF
                            - GTQ
                            - GYD
                            - HKD
                            - HNL
                            - HRK
                            - HTG
                            - HUF
                            - IDR
                            - ILS
                            - INR
                            - IQD
                            - IRR
                            - ISK
                            - JMD
                            - JOD
                            - JPY
                            - KES
                            - KGS
                            - KHR
                            - KMF
                            - KPW
                            - KRW
                            - KWD
                            - KYD
                            - KZT
                            - LAK
                            - LBP
                            - LKR
                            - LRD
                            - LSL
                            - LYD
                            - MAD
                            - MDL
                            - MGA
                            - MKD
                            - MMK
                            - MNT
                            - MOP
                            - MRO
                            - MUR
                            - MVR
                            - MWK
                            - MXN
                            - MYR
                            - MZN
                            - NAD
                            - NGN
                            - NIO
                            - NOK
                            - NPR
                            - NZD
                            - OMR
                            - PAB
                            - PEN
                            - PGK
                            - PHP
                            - PKR
                            - PLN
                            - PYG
                            - QAR
                            - RON
                            - RSD
                            - RUB
                            - RWF
                            - SAR
                            - SBD
                            - SCR
                            - SDG
                            - SEK
                            - SGD
                            - SHP
                            - SLL
                            - SOS
                            - SRD
                            - SSP
                            - STD
                            - SVC
                            - SYP
                            - SZL
                            - THB
                            - TJS
                            - TMT
                            - TND
                            - TOP
                            - TRY
                            - TTD
                            - TWD
                            - TZS
                            - UAH
                            - UGX
                            - USD
                            - UYU
                            - UZS
                            - VEF
                            - VND
                            - VUV
                            - WST
                            - XAF
                            - XCD
                            - XOF
                            - XPF
                            - YER
                            - ZAR
                            - ZMW
                            - ZWL
                          type: string
                      additionalProperties: false
                      required:
                        - value
                        - currency
                    submittedBy:
                      title: Submitted By
                      description: The person who made the submit request.
                      oneOf:
                        - type: object
                          properties:
                            id:
                              title: ID
                              description: The global identifier for the Submitted By.
                              type: string
                              format: guid
                              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                              x-lineageLookupReferenceObject: persons
                          additionalProperties: false
                          required:
                            - id
                        - type: object
                          maxProperties: 0
                    referenceDocument:
                      title: Reference Document
                      description: The reference document that may be liquidated or adjusted with the
                        account funds available transaction request.
                      oneOf:
                        - type: object
                          properties:
                            encumbranceNumber:
                              title: Encumbrance Number
                              description: The encumbrance number of the reference document.
                              type: string
                              minLength: 1
                            itemNumber:
                              title: Item Number
                              description: The item number of the reference document.
                              type: string
                            sequenceNumber:
                              title: Sequence Number
                              description: The sequence number of the reference document.
                              type: string
                          additionalProperties: false
                          required:
                            - encumbranceNumber
                        - type: object
                          maxProperties: 0
                  additionalProperties: false
                  required:
                    - accountingString
                    - type
                    - amount
            additionalProperties: false
            required:
              - type
              - transactionDetailLines
      required:
        - transactions
      additionalProperties: false
