openapi: 3.0.0
info:
  title: Subregions
  description: The valid list of subregions.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/subregions:
    get:
      summary: Return all resources from STVCNTY
      description: Returns a paged listing of all the subregion records from STVCNTY table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SUBREGIONS
      tags:
        - subregions
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-subregions.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/subregions/{id}:
    get:
      summary: Return the requested resource from STVCNTY
      description: Return the single subregion record with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SUBREGIONS
      tags:
        - subregions
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Subregions for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-subregions.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
    put:
      summary: Update the requested resource from STVCNTY
      description: >-
        Update the existing subregion record with the passed in identifier.


        Note that 'isoCode' is the only updatable property. If the ISO code sent in the update request is already assigned to another subregion code in STVCNTY then the API rejects the request with an error message.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SUBREGIONS
      tags:
        - subregions
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Subregions for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json 

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json 

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-subregions.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              type: object
              $ref: "#/components/schemas/schema-subregions.json"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-subregions.json:
      title: Subregions
      description: The valid list of subregions.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the subregion.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: STVCNTY_GUID(STVCNTY)
        title:
          title: Title
          description: The full name of the subregion.
          type: string
          minLength: 1
          x-lineageReferenceObject: STVCNTY_DESC(STVCNTY)
        code:
          title: Code
          description: The code used to identify the subregion.
          type: string
          x-lineageReferenceObject: STVCNTY_CODE(STVCNTY)
        isoCode:
          title: ISO Code
          description: The ISO code used to identify the subregion.
          type: string
          x-lineageReferenceObject: STVCNTY_SCOD_CODE_ISO(STVCNTY)
      required:
        - id
        - title
      additionalProperties: false

