openapi: 3.0.0
info:
  title: data-privacy-retention-rule-code-validation
  description: API for GTVRETR administrative page
  version: 0.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: GTVRETR
  x-source-domain: Foundation
  x-source-title: Data Privacy Retention Rule Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/data-privacy-retention-rule-code-validation:
    get:
      tags:
        - data-privacy-retention-rule-code-validation
      summary: Return resources from GTVRETR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: gtvretrCode
          in: query
          required: false
          schema:
            type: string
        - name: gtvretrDesc
          in: query
          required: false
          schema:
            type: string
        - name: gtvretrUserId
          in: query
          required: false
          schema:
            type: string
        - name: gtvretrActivityDate
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_g\
                    et_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - data-privacy-retention-rule-code-validation
      summary: Updates an existing resource in GTVRETR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_p\
                ut_request"
            example:
              criteria.code: TEST A
              desc: Editing for the recorder
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_p\
                    ut_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - data-privacy-retention-rule-code-validation
      summary: Creates a new resource in GTVRETR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_p\
                ost_request"
            example:
              code: D
              desc: Test Code 4
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_p\
                    ost_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/data-privacy-retention-rule-code-validation:
    post:
      tags:
        - data-privacy-retention-rule-code-validation QAPI (Query by POST)
      summary: Return resources from GTVRETR
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_g\
                et_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-retention-rule-code-validation-0.1.0_g\
                    et_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    data-privacy-retention-rule-code-validation-0.1.0_post_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GTVRETR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVRETR_ACTIVITY_DATE
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GTVRETR_CODE"
          x-lineageReferenceObject: GTVRETR_CODE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVRETR_USER_ID"
          x-lineageReferenceObject: GTVRETR_USER_ID
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
      x-lineageReferenceObject: gtvretr
    data-privacy-retention-rule-code-validation-0.1.0_qapi_post:
      type: object
      properties:
        gtvretrCode:
          type: string
        gtvretrDesc:
          type: string
        gtvretrUserId:
          type: string
        gtvretrActivityDate:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    data-privacy-retention-rule-code-validation-0.1.0_put_request:
      required:
        - criteria.code
        - criteria.desc
        - desc
      type: object
      properties:
        criteria.code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GTVRETR_CODE"
          x-lineageReferenceObject: GTVRETR_CODE
        criteria.userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVRETR_USER_ID"
          x-lineageReferenceObject: GTVRETR_USER_ID
        criteria.activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GTVRETR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVRETR_ACTIVITY_DATE
        criteria.desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
      x-lineageReferenceObject: GTVRETR
    data-privacy-retention-rule-code-validation-0.1.0_post_request:
      required:
        - code
        - desc
      type: object
      properties:
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GTVRETR_CODE"
          x-lineageReferenceObject: GTVRETR_CODE
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
      x-lineageReferenceObject: GTVRETR
    data-privacy-retention-rule-code-validation-0.1.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GTVRETR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVRETR_ACTIVITY_DATE
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GTVRETR_CODE"
          x-lineageReferenceObject: GTVRETR_CODE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVRETR_USER_ID"
          x-lineageReferenceObject: GTVRETR_USER_ID
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
      x-lineageReferenceObject: gtvretr
    data-privacy-retention-rule-code-validation-0.1.0_put_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GTVRETR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVRETR_ACTIVITY_DATE
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GTVRETR_CODE"
          x-lineageReferenceObject: GTVRETR_CODE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVRETR_USER_ID"
          x-lineageReferenceObject: GTVRETR_USER_ID
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
      x-lineageReferenceObject: gtvretr
    data-privacy-retention-rule-code-validation-0.1.0_get_request:
      required:
        - gtvretrCode
        - gtvretrDesc
      type: object
      properties:
        gtvretrDesc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GTVRETR_DESC"
          x-lineageReferenceObject: GTVRETR_DESC
        gtvretrUserId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVRETR_USER_ID"
          x-lineageReferenceObject: GTVRETR_USER_ID
        gtvretrActivityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : GTVRETR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVRETR_ACTIVITY_DATE
        gtvretrCode:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : GTVRETR_CODE"
          x-lineageReferenceObject: GTVRETR_CODE
      x-lineageReferenceObject: GTVRETR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
