openapi: 3.0.0
info:
  title: faculty-information-base-details-maintenance
  description: API for SIAINST administrative page
  version: 1.0.0
  x-source-name: SIAINST
  x-source-title: Faculty/Advisor Information
  x-source-system: banner
  x-api-type: bus-poc
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/faculty-information-base-details-maintenance:
    post:
      tags:
        - faculty-information-base-details-maintenance
      summary: Creates a new resource in SIAINST
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/faculty-information-base-details-maintenance-1.0.0_\
                post_request"
            example:
              advrInd: Y
              schdInd: Y
              overrideProcessInd: N
              keyblckTermCode: 201420
              id: A00046853
              fcstCode: AC
              fcstDate: 2011-06-03
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/faculty-information-base-details-maintenance-1.0.0_\
                    post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/faculty-information-base-details-maintenance: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    faculty-information-base-details-maintenance-1.0.0_post_response:
      type: object
      properties:
        sibinst_ctrl_block:
          type: array
          items:
            type: object
            properties:
              sibinstTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sibinstTermCodeFrom, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sibinstTermCodeFrom
                x-lineageLookupReferenceObject: stvterm
              sibinstTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sibinstTermCodeTo, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sibinstTermCodeTo
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: sibinst_ctrl_block
        sibinst:
          type: array
          items:
            required:
              - fcstCode
              - fcstDate
            type: object
            properties:
              fctgCode:
                title: Category
                maxLength: 30
                type: string
                description: "Lineage reference object : SIBINST_FCTG_CODE, Lookup lineage
                  reference object : stvfctg"
                x-lineageReferenceObject: SIBINST_FCTG_CODE
                x-lineageLookupReferenceObject: stvfctg
              overrideProcDate:
                title: Override Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SIBINST_OVERRIDE_PROC_DATE"
                format: date-time
                x-lineageReferenceObject: SIBINST_OVERRIDE_PROC_DATE
              wkldCode:
                title: Workload Rule
                maxLength: 30
                type: string
                description: "Lineage reference object : SIBINST_WKLD_CODE, Lookup lineage
                  reference object : stvwkld"
                x-lineageReferenceObject: SIBINST_WKLD_CODE
                x-lineageLookupReferenceObject: stvwkld
              fcstCode:
                title: Status
                maxLength: 30
                type: string
                description: "Lineage reference object : SIBINST_FCST_CODE, Lookup lineage
                  reference object : stvfcst"
                x-lineageReferenceObject: SIBINST_FCST_CODE
                x-lineageLookupReferenceObject: stvfcst
              appointDate:
                title: Appointment Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SIBINST_APPOINT_DATE"
                format: date-time
                x-lineageReferenceObject: SIBINST_APPOINT_DATE
              fcstDate:
                title: Status Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SIBINST_FCST_DATE"
                format: date-time
                x-lineageReferenceObject: SIBINST_FCST_DATE
              userId:
                title: User ID
                maxLength: 11
                type: string
                description: "Lineage reference object : SIBINST_USER_ID"
                x-lineageReferenceObject: SIBINST_USER_ID
              fcstDesc:
                type: string
              wkldDesc:
                type: string
              overrideProcUserid:
                title: Override User ID
                maxLength: 30
                type: string
                description: "Lineage reference object : SIBINST_OVERRIDE_PROC_USERID"
                x-lineageReferenceObject: SIBINST_OVERRIDE_PROC_USERID
              activityDate:
                title: Activity Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SIBINST_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SIBINST_ACTIVITY_DATE
              advrInd:
                title: Advisor
                maxLength: 1
                type: string
                description: "Lineage reference object : SIBINST_ADVR_IND"
                x-lineageReferenceObject: SIBINST_ADVR_IND
              fstpCode:
                title: Staff Type
                maxLength: 30
                type: string
                description: "Lineage reference object : SIBINST_FSTP_CODE, Lookup lineage
                  reference object : stvfstp"
                x-lineageReferenceObject: SIBINST_FSTP_CODE
                x-lineageLookupReferenceObject: stvfstp
              overrideProcessInd:
                title: Override Process Rule Security
                maxLength: 1
                type: string
                description: "Lineage reference object : SIBINST_OVERRIDE_PROCESS_IND"
                x-lineageReferenceObject: SIBINST_OVERRIDE_PROCESS_IND
              schdInd:
                title: Faculty
                maxLength: 1
                type: string
                description: "Lineage reference object : SIBINST_SCHD_IND"
                x-lineageReferenceObject: SIBINST_SCHD_IND
              fstpDesc:
                type: string
              fctgDesc:
                type: string
            x-lineageReferenceObject: sibinst
    faculty-information-base-details-maintenance-1.0.0_post_request:
      required:
        - keyblckTermCode
        - id
      type: object
      properties:
        fctgCode:
          title: Category
          maxLength: 30
          type: string
          description: "Lineage reference object : SIBINST_FCTG_CODE, Lookup lineage
            reference object : stvfctg"
          x-lineageReferenceObject: SIBINST_FCTG_CODE
          x-lineageLookupReferenceObject: stvfctg
        advrInd:
          title: Advisor
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBINST_ADVR_IND"
          x-lineageReferenceObject: SIBINST_ADVR_IND
        schdInd:
          title: Faculty
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBINST_SCHD_IND"
          x-lineageReferenceObject: SIBINST_SCHD_IND
        overrideProcessInd:
          title: Override Process Rule Security
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBINST_OVERRIDE_PROCESS_IND"
          x-lineageReferenceObject: SIBINST_OVERRIDE_PROCESS_IND
        fstpCode:
          title: Staff Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SIBINST_FSTP_CODE, Lookup lineage
            reference object : stvfstp"
          x-lineageReferenceObject: SIBINST_FSTP_CODE
          x-lineageLookupReferenceObject: stvfstp
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        wkldCode:
          title: Workload Rule
          maxLength: 30
          type: string
          description: "Lineage reference object : SIBINST_WKLD_CODE, Lookup lineage
            reference object : stvwkld"
          x-lineageReferenceObject: SIBINST_WKLD_CODE
          x-lineageLookupReferenceObject: stvwkld
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        fcstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : SIBINST_FCST_CODE, Lookup lineage
            reference object : stvfcst"
          x-lineageReferenceObject: SIBINST_FCST_CODE
          x-lineageLookupReferenceObject: stvfcst
        fcstDate:
          title: Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SIBINST_FCST_DATE"
          format: date-time
          x-lineageReferenceObject: SIBINST_FCST_DATE
        appointDate:
          title: Appointment Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SIBINST_APPOINT_DATE"
          format: date-time
          x-lineageReferenceObject: SIBINST_APPOINT_DATE
      x-lineageReferenceObject: SIBINST
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
