openapi: 3.0.0
info:
  title: Student Entitlement Limits
  description: This API returns the Student Entitlement Limits
  version: 1.0.0
  x-source-name: SVQ_STUDENT_APAC_LOAN_AMOUNT
  x-source-title: student-entitlement-limits
  x-source-system: Banner
  x-api-type: erp
  x-audience: all
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-entitlement-limits:
    get:
      tags:
        - student-entitlement-limits
      summary: Provide the list of student entitlement limit.
      description: Provide the list of student entitlement limit.
      parameters:
        - name: limit
          in: query
          description:
            The maximum number of resources requesting for this result set.
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student-entitlement-limits-1.0.0_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client's preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - BearerAuth: []
        - BasicAuth: []
      x-method-permission:
  /api/student-entitlement-limits/{id}:
    get:
      summary: Provide a student entitlement limit record for the given id.
      description: Provide a student entitlement limit record for the given id.
      tags:
        - student-entitlement-limits
      parameters:
        - name: id
          in: path
          required: true
          description: identification number used to access person on-line.
          schema:
            type: string
      responses:
       '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response.
              required: true
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                $ref: '#/components/schemas/student-entitlement-limits-1.0.0_response'
       '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '401':
          description: Failure. Unauthorized.
       '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
       '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '406':
          description: Failure. Not Acceptable. Unable to generate any of the client's preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
       '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
      - BearerAuth: []
      - BasicAuth: []
      x-method-permission:
components:
  schemas:
    student-entitlement-limits-1.0.0_response:
      type: object
      properties:
        id:
          "title": "studentId"
          "description": "identification number used to access person on-line."
          "type": string
          "maxLength": 9
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.STUDENT_ID
        lifeTimeLimit:
          "title": "lifetimeLimit"
          "description": "limit of any Commonwealth assistance that a person can have in their lifetime."
          "type": number
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.LIFETIME_LIMIT
        pendingBalance:
          "title": "pendingBalance"
          "description": "balance amount that is available in the lifetime limit."
          "type": number
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.PENDING_BALANCE
        availableBalance:
          "title": "availableBalance"
          "description": "balance of Commonwealth assistance that remains available for the person."
          "type": number
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.AVAILABLE_BALANCE
        maxHelpLoanAmount:
          "title": "maximumHelpLoanAmount"
          "description": "Maximum help loan amount used at the institution."
          "type": number
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.MAX_HELP_LOAN_AMOUNT
        loanAmount:
          "title": "loanAmount"
          "description": "total help loan amount used at the institution."
          "type": number
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.LOAN_AMOUNT
        limitChange:
          "title": "limitChange"
          "description": " Indicates if the lifetime limit changed for a student."
          "type": string
          "x-lineageReferenceObject": SVQ_STUDENT_APAC_LOAN_AMOUNT.LIMIT_CHANGE
      required:
        - studentId
        - lifeTimeLimit
        - pendingBalance
        - availableBalance
        - maxHelpLoanAmount
        - loanAmount
        - limitChange
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: The detailed actionable error message.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic
