openapi: 3.0.0
info:
  title: open-purchase-orders-by-foapal
  description: API for FPIOPOF administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FPIOPOF
  x-source-domain: Finance
  x-source-title: Open Purchase Orders by FOAPAL
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/open-purchase-orders-by-foapal:
    get:
      tags:
        - open-purchase-orders-by-foapal
      summary: Return resources from FPIOPOF
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: displayAcciCode
          in: query
          required: false
          schema:
            type: string
        - name: displayAcctCode
          in: query
          required: false
          schema:
            type: string
        - name: displayActvCode
          in: query
          required: false
          schema:
            type: string
        - name: displayCoasCode
          in: query
          required: true
          schema:
            type: string
        - name: displayFundCode
          in: query
          required: false
          schema:
            type: string
        - name: displayLocnCode
          in: query
          required: false
          schema:
            type: string
        - name: displayOrgnCode
          in: query
          required: false
          schema:
            type: string
        - name: displayProgCode
          in: query
          required: false
          schema:
            type: string
        - name: displayProjCode
          in: query
          required: false
          schema:
            type: string
        - name: commCode
          in: query
          description: Commodity
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FPRPODT_COMM_CODE
        - name: item
          in: query
          description: Item
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FPRPODT_ITEM
        - name: pohdCode
          in: query
          description: Purchase Order
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FPRPODT_POHD_CODE
        - name: qty
          in: query
          description: Quantity
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FPRPODT_QTY
        - name: unitPrice
          in: query
          description: Unit Price
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FPRPODT_UNIT_PRICE
        - name: uomsCode
          in: query
          description: U/M
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FPRPODT_UOMS_CODE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/open-purchase-orders-by-foapal-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/open-purchase-orders-by-foapal:
    post:
      tags:
        - open-purchase-orders-by-foapal QAPI (Query by POST)
      summary: Return resources from FPIOPOF
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/open-purchase-orders-by-foapal-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/open-purchase-orders-by-foapal-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    open-purchase-orders-by-foapal-1.0.0_get_request:
      required:
        - displayCoasCode
      type: object
      properties:
        unitPrice:
          title: Unit Price
          maxLength: 21
          type: number
          description: "Lineage reference object : FPRPODT_UNIT_PRICE"
          x-lineageReferenceObject: FPRPODT_UNIT_PRICE
        displayAcciCode:
          title: Index
          maxLength: 30
          type: string
          description: "Lineage reference object : displayAcciCode, Lookup lineage
            reference object : ftvacci"
          x-lineageReferenceObject: displayAcciCode
          x-lineageLookupReferenceObject: ftvacci
        displayProjCode:
          title: Proj
          maxLength: 30
          type: string
          description: "Lineage reference object : displayProjCode, Lookup lineage
            reference object : ftvproj"
          x-lineageReferenceObject: displayProjCode
          x-lineageLookupReferenceObject: ftvproj
        item:
          title: Item
          maxLength: 4
          type: number
          description: "Lineage reference object : FPRPODT_ITEM"
          x-lineageReferenceObject: FPRPODT_ITEM
        displayOrgnCode:
          title: Orgn
          maxLength: 30
          type: string
          description: "Lineage reference object : displayOrgnCode"
          x-lineageReferenceObject: displayOrgnCode
        displayLocnCode:
          title: Locn
          maxLength: 30
          type: string
          description: "Lineage reference object : displayLocnCode"
          x-lineageReferenceObject: displayLocnCode
        displayProgCode:
          title: Prog
          maxLength: 30
          type: string
          description: "Lineage reference object : displayProgCode"
          x-lineageReferenceObject: displayProgCode
        displayCoasCode:
          title: COA
          maxLength: 30
          type: string
          description: "Lineage reference object : displayCoasCode, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: displayCoasCode
          x-lineageLookupReferenceObject: ftvcoas
        commCode:
          title: Commodity
          maxLength: 10
          type: string
          description: "Lineage reference object : FPRPODT_COMM_CODE"
          x-lineageReferenceObject: FPRPODT_COMM_CODE
        displayAcctCode:
          title: Acct
          maxLength: 30
          type: string
          description: "Lineage reference object : displayAcctCode"
          x-lineageReferenceObject: displayAcctCode
        qty:
          title: Quantity
          maxLength: 25
          type: number
          description: "Lineage reference object : FPRPODT_QTY"
          x-lineageReferenceObject: FPRPODT_QTY
        pohdCode:
          title: Purchase Order
          maxLength: 8
          type: string
          description: "Lineage reference object : FPRPODT_POHD_CODE"
          x-lineageReferenceObject: FPRPODT_POHD_CODE
        displayActvCode:
          title: Actv
          maxLength: 30
          type: string
          description: "Lineage reference object : displayActvCode"
          x-lineageReferenceObject: displayActvCode
        displayFundCode:
          title: Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : displayFundCode"
          x-lineageReferenceObject: displayFundCode
        uomsCode:
          title: U/M
          maxLength: 3
          type: string
          description: "Lineage reference object : FPRPODT_UOMS_CODE, Lookup lineage
            reference object : ftvuoms"
          x-lineageReferenceObject: FPRPODT_UOMS_CODE
          x-lineageLookupReferenceObject: ftvuoms
      x-lineageReferenceObject: FPRPODT
    open-purchase-orders-by-foapal-1.0.0_get_response:
      type: object
      properties:
        unitPrice:
          title: Unit Price
          maxLength: 21
          type: number
          description: "Lineage reference object : FPRPODT_UNIT_PRICE"
          x-lineageReferenceObject: FPRPODT_UNIT_PRICE
        commCode:
          title: Commodity
          maxLength: 10
          type: string
          description: "Lineage reference object : FPRPODT_COMM_CODE"
          x-lineageReferenceObject: FPRPODT_COMM_CODE
        item:
          title: Item
          maxLength: 4
          type: number
          description: "Lineage reference object : FPRPODT_ITEM"
          x-lineageReferenceObject: FPRPODT_ITEM
        displayCommDesc:
          maxLength: 50
          type: string
        qty:
          title: Quantity
          maxLength: 25
          type: number
          description: "Lineage reference object : FPRPODT_QTY"
          x-lineageReferenceObject: FPRPODT_QTY
        pohdCode:
          title: Purchase Order
          maxLength: 8
          type: string
          description: "Lineage reference object : FPRPODT_POHD_CODE"
          x-lineageReferenceObject: FPRPODT_POHD_CODE
        displayVendName:
          title: Vendor
          maxLength: 230
          type: string
        uomsCode:
          title: U/M
          maxLength: 3
          type: string
          description: "Lineage reference object : FPRPODT_UOMS_CODE, Lookup lineage
            reference object : ftvuoms"
          x-lineageReferenceObject: FPRPODT_UOMS_CODE
          x-lineageLookupReferenceObject: ftvuoms
      x-lineageReferenceObject: fprpodt
    open-purchase-orders-by-foapal-1.0.0_qapi_post:
      required:
        - displayCoasCode
      type: object
      properties:
        displayAcciCode:
          type: string
        displayAcctCode:
          type: string
        displayActvCode:
          type: string
        displayCoasCode:
          type: string
        displayFundCode:
          type: string
        displayLocnCode:
          type: string
        displayOrgnCode:
          type: string
        displayProgCode:
          type: string
        displayProjCode:
          type: string
        commCode:
          title: Commodity
          maxLength: 10
          type: string
          description: "Lineage reference object : FPRPODT_COMM_CODE"
          x-lineageReferenceObject: FPRPODT_COMM_CODE
        item:
          title: Item
          maxLength: 4
          type: number
          description: "Lineage reference object : FPRPODT_ITEM"
          x-lineageReferenceObject: FPRPODT_ITEM
        pohdCode:
          title: Purchase Order
          maxLength: 8
          type: string
          description: "Lineage reference object : FPRPODT_POHD_CODE"
          x-lineageReferenceObject: FPRPODT_POHD_CODE
        qty:
          title: Quantity
          maxLength: 25
          type: number
          description: "Lineage reference object : FPRPODT_QTY"
          x-lineageReferenceObject: FPRPODT_QTY
        unitPrice:
          title: Unit Price
          maxLength: 21
          type: number
          description: "Lineage reference object : FPRPODT_UNIT_PRICE"
          x-lineageReferenceObject: FPRPODT_UNIT_PRICE
        uomsCode:
          title: U/M
          maxLength: 3
          type: string
          description: "Lineage reference object : FPRPODT_UOMS_CODE, Lookup lineage
            reference object : ftvuoms"
          x-lineageReferenceObject: FPRPODT_UOMS_CODE
          x-lineageLookupReferenceObject: ftvuoms
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
