openapi: 3.0.0
info:
  title: support-service-detail-need-assignment-copy
  description: API for SEADETL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SEADETL
  x-source-domain: Student
  x-source-title: Support Service Detail
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/support-service-detail-need-assignment-copy:
    post:
      tags:
        - support-service-detail-need-assignment-copy
      summary: Creates a new resource in SEADETL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/support-service-detail-need-assignment-copy-1.0.0_p\
                ost_request"
            example:
              termCodeEff: 999999
              ssgpCode: ADLT
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/support-service-detail-need-assignment-copy-1.0.0_p\
                    ost_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/support-service-detail-need-assignment-copy: {}
components:
  schemas:
    support-service-detail-need-assignment-copy-1.0.0_post_request:
      type: object
      properties:
        termCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : seadetlTermCodeEff, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: seadetlTermCodeEff
          x-lineageLookupReferenceObject: stvterm
        ssgpCode:
          title: Service Group
          maxLength: 30
          type: string
          description: "Lineage reference object : seadetlSsgpCode, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: seadetlSsgpCode
          x-lineageLookupReferenceObject: stvssgp
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : seadetlId"
          x-lineageReferenceObject: seadetlId
      x-lineageReferenceObject: SEADETL_KEY_BLOCK
    support-service-detail-need-assignment-copy-1.0.0_post_response:
      required:
        - needCode
      type: object
      properties:
        ndrfCode:
          title: Need Referral Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTND_NDRF_CODE, Lookup lineage
            reference object : stvndrf"
          x-lineageReferenceObject: SERDTND_NDRF_CODE
          x-lineageLookupReferenceObject: stvndrf
        needCode:
          title: Need
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTND_NEED_CODE, Lookup lineage
            reference object : stvneed"
          x-lineageReferenceObject: SERDTND_NEED_CODE
          x-lineageLookupReferenceObject: stvneed
        selfInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SERDTND_SELF_IND"
          x-lineageReferenceObject: SERDTND_SELF_IND
        ssgpCode:
          title: Group
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTND_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SERDTND_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        endcopy:
          maxLength: 1
          type: string
        needDescription:
          title: Description
          type: string
      x-lineageReferenceObject: serdtnd
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
