openapi: 3.0.0
info:
  title: role-definition-codes
  description: API for STVROLE administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: STVROLE
  x-source-domain: Student
  x-source-title: Role Definition Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/role-definition-codes:
    get:
      tags:
        - role-definition-codes
      summary: Return resources from STVROLE
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: stvroleActivityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVROLE_ACTIVITY_DATE
        - name: stvroleCode
          in: query
          description: Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVROLE_CODE
        - name: stvroleDescription
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVROLE_DESCRIPTION
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/role-definition-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/role-definition-codes:
    post:
      tags:
        - role-definition-codes QAPI (Query by POST)
      summary: Return resources from STVROLE
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/role-definition-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/role-definition-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    role-definition-codes-1.0.0_get_response:
      required:
        - stvroleCode
        - stvroleDescription
      type: object
      properties:
        stvroleDescription:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVROLE_DESCRIPTION"
          x-lineageReferenceObject: STVROLE_DESCRIPTION
        stvroleCode:
          title: Code
          maxLength: 15
          type: string
          description: "Lineage reference object : STVROLE_CODE"
          x-lineageReferenceObject: STVROLE_CODE
        stvroleActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVROLE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVROLE_ACTIVITY_DATE
      x-lineageReferenceObject: stvrole_block
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    role-definition-codes-1.0.0_get_request:
      required:
        - stvroleCode
        - stvroleDescription
      type: object
      properties:
        stvroleDescription:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVROLE_DESCRIPTION"
          x-lineageReferenceObject: STVROLE_DESCRIPTION
        stvroleCode:
          title: Code
          maxLength: 15
          type: string
          description: "Lineage reference object : STVROLE_CODE"
          x-lineageReferenceObject: STVROLE_CODE
        stvroleActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVROLE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVROLE_ACTIVITY_DATE
      x-lineageReferenceObject: STVROLE_BLOCK
    role-definition-codes-1.0.0_qapi_post:
      type: object
      properties:
        stvroleActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVROLE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVROLE_ACTIVITY_DATE
        stvroleCode:
          title: Code
          maxLength: 15
          type: string
          description: "Lineage reference object : STVROLE_CODE"
          x-lineageReferenceObject: STVROLE_CODE
        stvroleDescription:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVROLE_DESCRIPTION"
          x-lineageReferenceObject: STVROLE_DESCRIPTION
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
