openapi: 3.0.0
info:
  title: flexible-benefits-rule
  description: API for PTRFBEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PTRFBEN
  x-source-domain: Human Resources
  x-source-title: Flexible Benefits Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/flexible-benefits-rule:
    get:
      tags:
        - flexible-benefits-rule
      summary: Return resources from PTRFBEN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: bdcaCode
          in: query
          description: Benefit or Deduction Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_BDCA_CODE
        - name: planCode
          in: query
          description: Plan Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_PLAN_CODE
        - name: fsaInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_FSA_IND
        - name: fsaGracePeriodInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_FSA_GRACE_PERIOD_IND
        - name: availInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_AVAIL_IND
        - name: dednFreq
          in: query
          description: Deduction Frequency
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_DEDN_FREQ
        - name: premAmt
          in: query
          description: Premium Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_PREM_AMT
        - name: flexAmt
          in: query
          description: Flexible Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_FLEX_AMT
        - name: emplAmt
          in: query
          description: Employee Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRFBEN_EMPL_AMT
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/flexible-benefits-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/flexible-benefits-rule:
    post:
      tags:
        - flexible-benefits-rule QAPI (Query by POST)
      summary: Return resources from PTRFBEN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/flexible-benefits-rule-1.0.0_get_request"
            example:
              planCode: M1
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/flexible-benefits-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    flexible-benefits-rule-1.0.0_qapi_post:
      type: object
      properties:
        bdcaCode:
          title: Benefit or Deduction Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFBEN_BDCA_CODE"
          x-lineageReferenceObject: PTRFBEN_BDCA_CODE
        planCode:
          title: Plan Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFBEN_PLAN_CODE"
          x-lineageReferenceObject: PTRFBEN_PLAN_CODE
        fsaInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_FSA_IND"
          x-lineageReferenceObject: PTRFBEN_FSA_IND
        fsaGracePeriodInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_FSA_GRACE_PERIOD_IND"
          x-lineageReferenceObject: PTRFBEN_FSA_GRACE_PERIOD_IND
        availInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_AVAIL_IND"
          x-lineageReferenceObject: PTRFBEN_AVAIL_IND
        dednFreq:
          title: Deduction Frequency
          maxLength: 1
          type: number
          description: "Lineage reference object : PTRFBEN_DEDN_FREQ"
          x-lineageReferenceObject: PTRFBEN_DEDN_FREQ
        premAmt:
          title: Premium Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_PREM_AMT"
          x-lineageReferenceObject: PTRFBEN_PREM_AMT
        flexAmt:
          title: Flexible Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_FLEX_AMT"
          x-lineageReferenceObject: PTRFBEN_FLEX_AMT
        emplAmt:
          title: Employee Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_EMPL_AMT"
          x-lineageReferenceObject: PTRFBEN_EMPL_AMT
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    flexible-benefits-rule-1.0.0_get_request:
      required:
        - bdcaCode
        - dednFreq
      type: object
      properties:
        availInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_AVAIL_IND"
          x-lineageReferenceObject: PTRFBEN_AVAIL_IND
        flexAmt:
          title: Flexible Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_FLEX_AMT"
          x-lineageReferenceObject: PTRFBEN_FLEX_AMT
        bdcaCode:
          title: Benefit or Deduction Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFBEN_BDCA_CODE"
          x-lineageReferenceObject: PTRFBEN_BDCA_CODE
        emplAmt:
          title: Employee Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_EMPL_AMT"
          x-lineageReferenceObject: PTRFBEN_EMPL_AMT
        premAmt:
          title: Premium Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_PREM_AMT"
          x-lineageReferenceObject: PTRFBEN_PREM_AMT
        fsaInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_FSA_IND"
          x-lineageReferenceObject: PTRFBEN_FSA_IND
        fsaGracePeriodInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_FSA_GRACE_PERIOD_IND"
          x-lineageReferenceObject: PTRFBEN_FSA_GRACE_PERIOD_IND
        dednFreq:
          title: Deduction Frequency
          maxLength: 1
          type: number
          description: "Lineage reference object : PTRFBEN_DEDN_FREQ"
          x-lineageReferenceObject: PTRFBEN_DEDN_FREQ
        planCode:
          title: Plan Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFBEN_PLAN_CODE"
          x-lineageReferenceObject: PTRFBEN_PLAN_CODE
      x-lineageReferenceObject: PTRFBEN
    flexible-benefits-rule-1.0.0_get_response:
      required:
        - bdcaCode
        - dednFreq
      type: object
      properties:
        availInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_AVAIL_IND"
          x-lineageReferenceObject: PTRFBEN_AVAIL_IND
        flexAmt:
          title: Flexible Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_FLEX_AMT"
          x-lineageReferenceObject: PTRFBEN_FLEX_AMT
        bdcaCode:
          title: Benefit or Deduction Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFBEN_BDCA_CODE"
          x-lineageReferenceObject: PTRFBEN_BDCA_CODE
        emplAmt:
          title: Employee Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_EMPL_AMT"
          x-lineageReferenceObject: PTRFBEN_EMPL_AMT
        bdcaDesc:
          type: string
        premAmt:
          title: Premium Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRFBEN_PREM_AMT"
          x-lineageReferenceObject: PTRFBEN_PREM_AMT
        fsaInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_FSA_IND"
          x-lineageReferenceObject: PTRFBEN_FSA_IND
        dednFreq:
          title: Deduction Frequency
          maxLength: 1
          type: number
          description: "Lineage reference object : PTRFBEN_DEDN_FREQ"
          x-lineageReferenceObject: PTRFBEN_DEDN_FREQ
        fsaGracePeriodInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRFBEN_FSA_GRACE_PERIOD_IND"
          x-lineageReferenceObject: PTRFBEN_FSA_GRACE_PERIOD_IND
        planCode:
          title: Plan Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRFBEN_PLAN_CODE"
          x-lineageReferenceObject: PTRFBEN_PLAN_CODE
      x-lineageReferenceObject: ptrfben
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
