openapi: 3.0.0
info:
  title: support-service-detail-goal-assignments-copy
  description: API for SEADETL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SEADETL
  x-source-domain: Student
  x-source-title: Support Service Detail
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/support-service-detail-goal-assignments-copy:
    post:
      tags:
        - support-service-detail-goal-assignments-copy
      summary: Creates a new resource in SEADETL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/support-service-detail-goal-assignments-copy-1.0.0_\
                post_request"
            example:
              termCodeEff: 999999
              ssgpCode: ADLT
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/support-service-detail-goal-assignments-copy-1.0.0_\
                    post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/support-service-detail-goal-assignments-copy: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    support-service-detail-goal-assignments-copy-1.0.0_post_response:
      required:
        - goalCode
      type: object
      properties:
        goalDescription:
          title: Description
          type: string
        goalCode:
          title: Goal
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTGL_GOAL_CODE, Lookup lineage
            reference object : stvgoal"
          x-lineageReferenceObject: SERDTGL_GOAL_CODE
          x-lineageLookupReferenceObject: stvgoal
        ssgpCode:
          title: Group
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTGL_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SERDTGL_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        treqCode:
          title: Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTGL_TREQ_CODE, Lookup lineage
            reference object : stvtreq"
          x-lineageReferenceObject: SERDTGL_TREQ_CODE
          x-lineageLookupReferenceObject: stvtreq
        actualDate:
          title: Actual Completion Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SERDTGL_ACTUAL_DATE"
          format: date-time
          x-lineageReferenceObject: SERDTGL_ACTUAL_DATE
        endcopy:
          maxLength: 1
          type: string
        priorityNbr:
          title: Priority Number
          maxLength: 3
          type: number
          description: "Lineage reference object : SERDTGL_PRIORITY_NBR"
          x-lineageReferenceObject: SERDTGL_PRIORITY_NBR
        ssrsCode:
          title: Result
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTGL_SSRS_CODE, Lookup lineage
            reference object : stvssrs"
          x-lineageReferenceObject: SERDTGL_SSRS_CODE
          x-lineageLookupReferenceObject: stvssrs
        estimateDate:
          title: Estimated Completion Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SERDTGL_ESTIMATE_DATE"
          format: date-time
          x-lineageReferenceObject: SERDTGL_ESTIMATE_DATE
        origCode:
          title: Review
          maxLength: 30
          type: string
          description: "Lineage reference object : SERDTGL_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SERDTGL_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
      x-lineageReferenceObject: serdtgl
    support-service-detail-goal-assignments-copy-1.0.0_post_request:
      type: object
      properties:
        termCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : seadetlTermCodeEff, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: seadetlTermCodeEff
          x-lineageLookupReferenceObject: stvterm
        ssgpCode:
          title: Service Group
          maxLength: 30
          type: string
          description: "Lineage reference object : seadetlSsgpCode, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: seadetlSsgpCode
          x-lineageLookupReferenceObject: stvssgp
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : seadetlId"
          x-lineageReferenceObject: seadetlId
      x-lineageReferenceObject: SEADETL_KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
