openapi: 3.0.0
info:
  title: ca-mis-special-historical-data-foster-youth
  description: API for SVAMISH administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SVAMISH
  x-source-domain: Student
  x-source-title: Student MIS Special Historical Data (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-mis-special-historical-data-foster-youth:
    get:
      tags:
        - ca-mis-special-historical-data-foster-youth
      summary: Return resources from SVAMISH
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: svamishEffTerm
          in: query
          required: false
          schema:
            type: string
        - name: svamishDicdCode
          in: query
          required: false
          schema:
            type: string
        - name: homeCode
          in: query
          required: false
          schema:
            type: string
        - name: svbsfysHomeCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_g\
                    et_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - ca-mis-special-historical-data-foster-youth
      summary: Updates an existing resource in SVAMISH
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_p\
                ut_request"
            example:
              homeCode: D
              fystCode: B
              id: A00036215
              svamishEffTerm: 202210
              svamishDicdCode: 106
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_p\
                    ut_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - ca-mis-special-historical-data-foster-youth
      summary: Creates a new resource in SVAMISH
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_p\
                ost_request"
            example:
              homeCode: D
              fystCode: B
              id: A00036216
              studentActiveInd: Y
              svamishEffTerm: 202210
              svamishDicdCode: 106
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_p\
                    ost_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-mis-special-historical-data-foster-youth:
    post:
      tags:
        - ca-mis-special-historical-data-foster-youth QAPI (Query by POST)
      summary: Return resources from SVAMISH
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_g\
                et_request"
            example:
              homeCode: D
              fystCode: B
              id: A00036215
              svamishEffTerm: 202210
              svamishDicdCode: 106
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-special-historical-data-foster-youth-1.0.0_g\
                    et_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    ca-mis-special-historical-data-foster-youth-1.0.0_post_request:
      type: object
      properties:
        homeCode:
          title: Homeless Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSFYS_HOME_CODE"
          x-lineageReferenceObject: SVBSFYS_HOME_CODE
        fystCode:
          title: Foster Youth Status
          maxLength: 6
          type: string
          description: "Lineage reference object : SVBSFYS_FYST_CODE"
          x-lineageReferenceObject: SVBSFYS_FYST_CODE
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        svamishEffTerm:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : svamishEffTerm, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svamishEffTerm
          x-lineageLookupReferenceObject: stvterm
        svamishDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamishDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svamishDicdCode
          x-lineageLookupReferenceObject: gtvdicd
      x-lineageReferenceObject: SVBSFYS
    ca-mis-special-historical-data-foster-youth-1.0.0_put_response:
      type: object
      properties:
        homeCode:
          title: Homeless Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSFYS_HOME_CODE"
          x-lineageReferenceObject: SVBSFYS_HOME_CODE
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SVBSFYS_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVBSFYS_ACTIVITY_DATE
        fystCodeSt:
          type: string
        fystCode:
          title: Foster Youth Status
          maxLength: 6
          type: string
          description: "Lineage reference object : SVBSFYS_FYST_CODE"
          x-lineageReferenceObject: SVBSFYS_FYST_CODE
        homeCodeSt:
          type: string
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SVBSFYS_USER_ID"
          x-lineageReferenceObject: SVBSFYS_USER_ID
      x-lineageReferenceObject: svbsfys
    ca-mis-special-historical-data-foster-youth-1.0.0_get_response:
      type: object
      properties:
        svbsfys:
          type: array
          items:
            type: object
            properties:
              homeCode:
                title: Homeless Status
                maxLength: 2
                type: string
                description: "Lineage reference object : SVBSFYS_HOME_CODE"
                x-lineageReferenceObject: SVBSFYS_HOME_CODE
              activityDate:
                maxLength: 11
                type: string
                description: "Lineage reference object : SVBSFYS_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SVBSFYS_ACTIVITY_DATE
              fystCodeSt:
                type: string
              fystCode:
                title: Foster Youth Status
                maxLength: 6
                type: string
                description: "Lineage reference object : SVBSFYS_FYST_CODE"
                x-lineageReferenceObject: SVBSFYS_FYST_CODE
              homeCodeSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SVBSFYS_USER_ID"
                x-lineageReferenceObject: SVBSFYS_USER_ID
            x-lineageReferenceObject: svbsfys
        sfys_ctrl_block:
          type: array
          items:
            type: object
            properties:
              svbsfysTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : svbsfysTermCodeFrom"
                x-lineageReferenceObject: svbsfysTermCodeFrom
              svbsfysTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : svbsfysTermCodeTo"
                x-lineageReferenceObject: svbsfysTermCodeTo
            x-lineageReferenceObject: sfys_ctrl_block
    ca-mis-special-historical-data-foster-youth-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        svamishEffTerm:
          type: string
        svamishDicdCode:
          type: string
        homeCode:
          type: string
        svbsfysHomeCode:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-mis-special-historical-data-foster-youth-1.0.0_put_request:
      type: object
      properties:
        homeCode:
          title: Homeless Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSFYS_HOME_CODE"
          x-lineageReferenceObject: SVBSFYS_HOME_CODE
        fystCode:
          title: Foster Youth Status
          maxLength: 6
          type: string
          description: "Lineage reference object : SVBSFYS_FYST_CODE"
          x-lineageReferenceObject: SVBSFYS_FYST_CODE
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        svamishEffTerm:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : svamishEffTerm, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svamishEffTerm
          x-lineageLookupReferenceObject: stvterm
        svamishDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamishDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svamishDicdCode
          x-lineageLookupReferenceObject: gtvdicd
      x-lineageReferenceObject: SVBSFYS
    ca-mis-special-historical-data-foster-youth-1.0.0_post_response:
      type: object
      properties:
        homeCode:
          title: Homeless Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSFYS_HOME_CODE"
          x-lineageReferenceObject: SVBSFYS_HOME_CODE
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SVBSFYS_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVBSFYS_ACTIVITY_DATE
        fystCodeSt:
          type: string
        fystCode:
          title: Foster Youth Status
          maxLength: 6
          type: string
          description: "Lineage reference object : SVBSFYS_FYST_CODE"
          x-lineageReferenceObject: SVBSFYS_FYST_CODE
        homeCodeSt:
          type: string
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SVBSFYS_USER_ID"
          x-lineageReferenceObject: SVBSFYS_USER_ID
      x-lineageReferenceObject: svbsfys
    ca-mis-special-historical-data-foster-youth-1.0.0_get_request:
      type: object
      properties:
        homeCode:
          title: Homeless Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSFYS_HOME_CODE"
          x-lineageReferenceObject: SVBSFYS_HOME_CODE
        svbsfysHomeCode:
          title: Homeless Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSFYS_HOME_CODE"
          x-lineageReferenceObject: SVBSFYS_HOME_CODE
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        svamishEffTerm:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : svamishEffTerm, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svamishEffTerm
          x-lineageLookupReferenceObject: stvterm
        svamishDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamishDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svamishDicdCode
          x-lineageLookupReferenceObject: gtvdicd
      x-lineageReferenceObject: SVBSFYS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
