openapi: 3.0.0
info:
  title: course-detail-information-degree-attributes-end
  description: API for SCADETL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SCADETL
  x-source-domain: Student
  x-source-title: Course Detail Information Form
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: '{server_url}'
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/course-detail-information-degree-attributes-end:
    post:
      tags:
      - course-detail-information-degree-attributes-end
      summary: Creates a new resource in SCADETL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/course-detail-information-degree-attributes-end-1.0.0_post_request"
            example:
              crseNumb: M1800
              termCodeEff: 290010
              subjCode: M180
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/course-detail-information-degree-attributes-end-1.0.0_post_response"
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/course-detail-information-degree-attributes-end: {}
components:
  schemas:
    course-detail-information-degree-attributes-end-1.0.0_post_request:
      type: object
      properties:
        crseNumb:
          title: Course
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseCrseNumb"
          x-lineageReferenceObject: scacrseCrseNumb
        termCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseTermCodeEff, Lookup lineage\
            \ reference object : stvterm,scbcrky,scbcrky"
          x-lineageReferenceObject: scacrseTermCodeEff
          x-lineageLookupReferenceObject: "stvterm,scbcrky,scbcrky"
        subjCode:
          title: Subject
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseSubjCode, Lookup lineage\
            \ reference object : stvsubj"
          x-lineageReferenceObject: scacrseSubjCode
          x-lineageLookupReferenceObject: stvsubj
      x-lineageReferenceObject: SCACRSE_KEY_BLOCK
    course-detail-information-degree-attributes-end-1.0.0_post_response:
      type: object
      properties:
        scacrse_key_block:
          type: array
          items:
            type: object
            properties:
              crseTitle:
                title: Course Title
                type: string
                description: "Lineage reference object : crseTitle"
                x-lineageReferenceObject: crseTitle
              scacrseCrseNumb:
                title: Course
                maxLength: 30
                type: string
                description: "Lineage reference object : scacrseCrseNumb"
                x-lineageReferenceObject: scacrseCrseNumb
              subjDescription:
                type: string
                description: "Lineage reference object : subjDescription"
                x-lineageReferenceObject: subjDescription
              scacrseSubjCode:
                title: Subject
                maxLength: 30
                type: string
                description: "Lineage reference object : scacrseSubjCode, Lookup lineage\
                  \ reference object : stvsubj"
                x-lineageReferenceObject: scacrseSubjCode
                x-lineageLookupReferenceObject: stvsubj
              scacrseCourseAlias:
                title: Course Alias
                maxLength: 50
                type: string
                description: "Lineage reference object : scacrseCourseAlias"
                x-lineageReferenceObject: scacrseCourseAlias
              scacrseTermCodeEff:
                title: Term
                maxLength: 30
                type: string
                description: "Lineage reference object : scacrseTermCodeEff, Lookup\
                  \ lineage reference object : stvterm,scbcrky,scbcrky"
                x-lineageReferenceObject: scacrseTermCodeEff
                x-lineageLookupReferenceObject: "stvterm,scbcrky,scbcrky"
            x-lineageReferenceObject: scacrse_key_block
        attr_ctrl_block:
          type: array
          items:
            type: object
            properties:
              scrattrTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : scrattrTermCodeFrom, Lookup\
                  \ lineage reference object : stvterm"
                x-lineageReferenceObject: scrattrTermCodeFrom
                x-lineageLookupReferenceObject: stvterm
              scrattrTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : scrattrTermCodeTo, Lookup\
                  \ lineage reference object : stvterm"
                x-lineageReferenceObject: scrattrTermCodeTo
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: attr_ctrl_block
        scrattr:
          type: array
          items:
            required:
            - attrCode
            type: object
            properties:
              attrCode:
                title: Attribute
                maxLength: 30
                type: string
                description: "Lineage reference object : SCRATTR_ATTR_CODE, Lookup\
                  \ lineage reference object : stvattr"
                x-lineageReferenceObject: SCRATTR_ATTR_CODE
                x-lineageLookupReferenceObject: stvattr
              attrDescription:
                type: string
            x-lineageReferenceObject: scrattr
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer