openapi: 3.0.0
info:
  title: registration-section-detail
  description: >
    The section detail API is an optional to get the full detail for a
    particular section. The API may be called to get details about a section the
    student is currently registered.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: Registration Section Details
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: registration-section-detail
paths:
  /api/registration-section-detail:
    get:
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_REGSTATUS
      tags:
        - registration-section-detail
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/json
            ```
        - name: term
          in: query
          required: true
          schema:
            type: string
          example: "202014"
          description: Code value to identify the term
        - name: courseReferenceNumber
          in: query
          required: true
          schema:
            type: string
          example: "2001"
          description: Description of the term associated with the term code
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/registration-section-detail"
            application/xml:
              schema:
                type: object
                $ref: "#/components/schemas/registration-section-detail"
          headers:
            X-Media-Type:
              description: application/json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    registration-section-detail:
      type: array
      items:
        type: object
        properties:
          billHours:
            type: number
          contactHours:
            type: number
          creditHours:
            type: number
          crossList:
            type: string
          crossListAvailable:
            type: integer
          crossListCapacity:
            type: integer
          durationUnit:
            type: string
          durationUnitDescription:
            type: string
          term:
            type: string
          campus:
            type: string
          campusDescription:
            type: string
          college:
            type: string
          courseNumber:
            type: string
          courseReferenceNumber:
            type: string
          courseTitle:
            type: string
          creditHourHigh:
            type: number
            format: double
          creditHourIndicator:
            type: string
          creditHourLow:
            type: number
            format: double
          department:
            type: string
          enrollment:
            type: integer
          id:
            type: integer
            format: int64
          maximumEnrollment:
            type: integer
          partOfTerm:
            type: string
          partOfTermEndDate:
            type: string
            format: date
          partOfTermStartDate:
            type: string
            format: date
          partOfTermWeeks:
            type: integer
          scheduleType:
            type: string
          scheduleTypeDescription:
            type: string
          seatsAvailable:
            type: string
          sectionStatus:
            type: string
          sequenceNumber:
            type: string
          subject:
            type: string
          subjectDescription:
            type: string
          termDesc:
            type: string
          waitAvailable:
            type: integer
          waitCapacity:
            type: integer
          waitCount:
            type: integer
          faculty:
            type: array
            items:
              type: object
              properties:
                bannerId:
                  type: string
                category:
                  type: string
                courseReferenceNumber:
                  type: string
                displayName:
                  type: string
                emailAddress:
                  type: string
                primaryIndicator:
                  type: boolean
                term:
                  type: string
          gradingMode:
            type: string
          gradingModeDescription:
            type: string
          instructionalMethod:
            type: string
          instructionalMethodDescription:
            type: string
          isSectionLinked:
            type: boolean
          labHours:
            type: number
          learnerRegStartFromDate:
            type: string
            format: date
          learnerRegStartToDate:
            type: string
            format: date
          lectureHours:
            type: number
          linkIdentifier:
            type: string
          meetingTimes:
            type: array
            items:
              type: object
              properties:
                beginTime:
                  type: string
                category:
                  type: string
                courseReferenceNumber:
                  type: string
                creditHourSession:
                  type: string
                endDate:
                  type: string
                  format: date
                endTime:
                  type: string
                friday:
                  type: boolean
                hoursWeek:
                  type: number
                  format: int64
                meetingScheduleType:
                  type: string
                meetingType:
                  type: string
                meetingTypeDescription:
                  type: string
                monday:
                  type: boolean
                saturday:
                  type: boolean
                startDate:
                  type: string
                  format: date
                sunday:
                  type: boolean
                term:
                  type: string
                thursday:
                  type: boolean
                tuesday:
                  type: boolean
                wednesday:
                  type: boolean
          numberOfUnits:
            type: number
          openSection:
            type: boolean
          otherHours:
            type: number
          prerequisiteCheckMethod:
            type: string
          registrationFromDate:
            type: string
            format: date
          registrationToDate:
            type: string
            format: date
          sectionAttributes:
            type: object
            properties:
              code:
                type: string
              courseReferenceNumber:
                type: string
              description:
                type: string
              isZTCAttribute:
                type: boolean
              termCode:
                type: string
          sectionSession:
            type: string
          sectionTitle:
            type: string
          totalCreditHours:
            type: number
          waitListPosition:
            type: string
          waitListPriority:
            type: number
          waitListPriorityEndDate:
            type: string
