openapi: 3.0.0
info:
  title: section-assigned-instructors
  description: API for SSASECT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SSASECT
  x-source-domain: Student
  x-source-title: Schedule
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/section-assigned-instructors:
    get:
      tags:
        - section-assigned-instructors
      summary: Return resources from SSASECT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          required: false
          schema:
            type: string
        - name: crn
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-assigned-instructors-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - section-assigned-instructors
      summary: Updates an existing resource in SSASECT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-assigned-instructors-1.0.0_put_request"
            example:
              percentResponse: 100
              overRide: Y
              category: 1
              idno: SYS000001
              crn: 10009
              percentSess: 100
              termCode: 1010
              primaryInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-assigned-instructors-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - section-assigned-instructors
      summary: Creates a new resource in SSASECT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-assigned-instructors-1.0.0_post_request"
            example:
              percentResponse: 100
              overRide: Y
              category: 2
              idno: A00036242
              crn: 10009
              percentSess: 100
              termCode: 1010
              primaryInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-assigned-instructors-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/section-assigned-instructors:
    post:
      tags:
        - section-assigned-instructors QAPI (Query by POST)
      summary: Return resources from SSASECT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/section-assigned-instructors-1.0.0_get_request"
            example:
              crn: 10009
              termCode: 1010
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/section-assigned-instructors-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    section-assigned-instructors-1.0.0_get_request:
      type: object
      properties:
        crn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectCrn"
          x-lineageReferenceObject: ssasectCrn
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: ssasectTermCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: KEY_BLOCK
    section-assigned-instructors-1.0.0_qapi_post:
      type: object
      properties:
        termCode:
          type: string
        crn:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    section-assigned-instructors-1.0.0_post_request:
      required:
        - category
      type: object
      properties:
        percentResponse:
          title: Percent of Responsibility
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_RESPONSE"
          x-lineageReferenceObject: SIRASGN_PERCENT_RESPONSE
        overRide:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_OVER_RIDE"
          x-lineageReferenceObject: SIRASGN_OVER_RIDE
        category:
          title: Session Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : SIRASGN_CATEGORY"
          x-lineageReferenceObject: SIRASGN_CATEGORY
        idno:
          title: ID
          maxLength: 9
          type: string
        crn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectCrn"
          x-lineageReferenceObject: ssasectCrn
        percentSess:
          title: Percent of Session
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_SESS"
          x-lineageReferenceObject: SIRASGN_PERCENT_SESS
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: ssasectTermCode
          x-lineageLookupReferenceObject: stvterm
        primaryInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_PRIMARY_IND"
          x-lineageReferenceObject: SIRASGN_PRIMARY_IND
      x-lineageReferenceObject: SIRASGN
    section-assigned-instructors-1.0.0_put_response:
      required:
        - category
      type: object
      properties:
        percentResponse:
          title: Percent of Responsibility
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_RESPONSE"
          x-lineageReferenceObject: SIRASGN_PERCENT_RESPONSE
        overRide:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_OVER_RIDE"
          x-lineageReferenceObject: SIRASGN_OVER_RIDE
        rwname:
          maxLength: 230
          type: string
        workload:
          title: Instructional Workload
          maxLength: 10
          type: number
        category:
          title: Session Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : SIRASGN_CATEGORY"
          x-lineageReferenceObject: SIRASGN_CATEGORY
        idno:
          title: ID
          maxLength: 9
          type: string
        percentSess:
          title: Percent of Session
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_SESS"
          x-lineageReferenceObject: SIRASGN_PERCENT_SESS
        primaryInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_PRIMARY_IND"
          x-lineageReferenceObject: SIRASGN_PRIMARY_IND
      x-lineageReferenceObject: sirasgn
    section-assigned-instructors-1.0.0_put_request:
      required:
        - category
      type: object
      properties:
        percentResponse:
          title: Percent of Responsibility
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_RESPONSE"
          x-lineageReferenceObject: SIRASGN_PERCENT_RESPONSE
        overRide:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_OVER_RIDE"
          x-lineageReferenceObject: SIRASGN_OVER_RIDE
        category:
          title: Session Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : SIRASGN_CATEGORY"
          x-lineageReferenceObject: SIRASGN_CATEGORY
        idno:
          title: ID
          maxLength: 9
          type: string
        crn:
          title: CRN
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectCrn"
          x-lineageReferenceObject: ssasectCrn
        percentSess:
          title: Percent of Session
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_SESS"
          x-lineageReferenceObject: SIRASGN_PERCENT_SESS
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : ssasectTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: ssasectTermCode
          x-lineageLookupReferenceObject: stvterm
        primaryInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_PRIMARY_IND"
          x-lineageReferenceObject: SIRASGN_PRIMARY_IND
      x-lineageReferenceObject: SIRASGN
    section-assigned-instructors-1.0.0_get_response:
      required:
        - category
      type: object
      properties:
        percentResponse:
          title: Percent of Responsibility
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_RESPONSE"
          x-lineageReferenceObject: SIRASGN_PERCENT_RESPONSE
        overRide:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_OVER_RIDE"
          x-lineageReferenceObject: SIRASGN_OVER_RIDE
        rwname:
          maxLength: 230
          type: string
        workload:
          title: Instructional Workload
          maxLength: 10
          type: number
        category:
          title: Session Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : SIRASGN_CATEGORY"
          x-lineageReferenceObject: SIRASGN_CATEGORY
        idno:
          title: ID
          maxLength: 9
          type: string
        percentSess:
          title: Percent of Session
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_SESS"
          x-lineageReferenceObject: SIRASGN_PERCENT_SESS
        primaryInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_PRIMARY_IND"
          x-lineageReferenceObject: SIRASGN_PRIMARY_IND
      x-lineageReferenceObject: sirasgn
    section-assigned-instructors-1.0.0_post_response:
      required:
        - category
      type: object
      properties:
        percentResponse:
          title: Percent of Responsibility
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_RESPONSE"
          x-lineageReferenceObject: SIRASGN_PERCENT_RESPONSE
        overRide:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_OVER_RIDE"
          x-lineageReferenceObject: SIRASGN_OVER_RIDE
        rwname:
          maxLength: 230
          type: string
        workload:
          title: Instructional Workload
          maxLength: 10
          type: number
        category:
          title: Session Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : SIRASGN_CATEGORY"
          x-lineageReferenceObject: SIRASGN_CATEGORY
        idno:
          title: ID
          maxLength: 9
          type: string
        percentSess:
          title: Percent of Session
          maxLength: 3
          type: number
          description: "Lineage reference object : SIRASGN_PERCENT_SESS"
          x-lineageReferenceObject: SIRASGN_PERCENT_SESS
        primaryInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIRASGN_PRIMARY_IND"
          x-lineageReferenceObject: SIRASGN_PRIMARY_IND
      x-lineageReferenceObject: sirasgn
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
