openapi: 3.0.0
info:
  title: general-student-veteran
  description: API for SGASTDN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SGASTDN
  x-source-domain: Student
  x-source-title: General Student
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/general-student-veteran:
    get:
      tags:
        - general-student-veteran
      summary: Return resources from SGASTDN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: stvtermTermCode
          in: query
          required: false
          schema:
            type: string
        - name: vetcCode
          in: query
          description: Veteran Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SGRVETN_VETC_CODE
        - name: termCodeVa
          in: query
          description: Term
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-student-veteran-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - general-student-veteran
      summary: Updates an existing resource in SGASTDN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-student-veteran-1.0.0_put_request"
            example:
              certDate: 2023-02-02
              certHours: 2
              id: A00000737
              stvtermTermCode: VUTE03
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-student-veteran-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - general-student-veteran
      summary: Creates a new resource in SGASTDN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-student-veteran-1.0.0_post_request"
            example:
              termCodeVa: VUTE03
              certDate: 2022-02-02
              certHours: 1
              id: A00000737
              stvtermTermCode: VUTE03
              vetcCode: 1
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-student-veteran-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/general-student-veteran:
    post:
      tags:
        - general-student-veteran QAPI (Query by POST)
      summary: Return resources from SGASTDN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-student-veteran-1.0.0_get_request"
            example:
              id: A00000737
              stvtermTermCode: VUTE03
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-student-veteran-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    general-student-veteran-1.0.0_get_request:
      type: object
      properties:
        termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        stvtermTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : stvtermTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: stvtermTermCode
          x-lineageLookupReferenceObject: stvterm
        vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
      x-lineageReferenceObject: SGRVETN
    general-student-veteran-1.0.0_post_response:
      type: object
      properties:
        termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
        stvvetcDesc:
          title: Description
          type: string
        certDate:
          title: Certification Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SGRVETN_CERT_DATE"
          format: date-time
          x-lineageReferenceObject: SGRVETN_CERT_DATE
        certHours:
          title: Certification Credit Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SGRVETN_CERT_HOURS"
          x-lineageReferenceObject: SGRVETN_CERT_HOURS
        vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
      x-lineageReferenceObject: sgrvetn
    general-student-veteran-1.0.0_post_request:
      type: object
      properties:
        termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
        certDate:
          title: Certification Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SGRVETN_CERT_DATE"
          format: date-time
          x-lineageReferenceObject: SGRVETN_CERT_DATE
        certHours:
          title: Certification Credit Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SGRVETN_CERT_HOURS"
          x-lineageReferenceObject: SGRVETN_CERT_HOURS
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        stvtermTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : stvtermTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: stvtermTermCode
          x-lineageLookupReferenceObject: stvterm
        vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
      x-lineageReferenceObject: SGRVETN
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    general-student-veteran-1.0.0_put_request:
      type: object
      properties:
        certDate:
          title: Certification Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SGRVETN_CERT_DATE"
          format: date-time
          x-lineageReferenceObject: SGRVETN_CERT_DATE
        criteria.vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
        certHours:
          title: Certification Credit Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SGRVETN_CERT_HOURS"
          x-lineageReferenceObject: SGRVETN_CERT_HOURS
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        stvtermTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : stvtermTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: stvtermTermCode
          x-lineageLookupReferenceObject: stvterm
        criteria.termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SGRVETN
    general-student-veteran-1.0.0_get_response:
      type: object
      properties:
        termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
        stvvetcDesc:
          title: Description
          type: string
        certDate:
          title: Certification Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SGRVETN_CERT_DATE"
          format: date-time
          x-lineageReferenceObject: SGRVETN_CERT_DATE
        certHours:
          title: Certification Credit Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SGRVETN_CERT_HOURS"
          x-lineageReferenceObject: SGRVETN_CERT_HOURS
        vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
      x-lineageReferenceObject: sgrvetn
    general-student-veteran-1.0.0_put_response:
      type: object
      properties:
        termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
        stvvetcDesc:
          title: Description
          type: string
        certDate:
          title: Certification Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SGRVETN_CERT_DATE"
          format: date-time
          x-lineageReferenceObject: SGRVETN_CERT_DATE
        certHours:
          title: Certification Credit Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SGRVETN_CERT_HOURS"
          x-lineageReferenceObject: SGRVETN_CERT_HOURS
        vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
      x-lineageReferenceObject: sgrvetn
    general-student-veteran-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        stvtermTermCode:
          type: string
        vetcCode:
          title: Veteran Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_VETC_CODE, Lookup lineage
            reference object : stvvetc"
          x-lineageReferenceObject: SGRVETN_VETC_CODE
          x-lineageLookupReferenceObject: stvvetc
        termCodeVa:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRVETN_TERM_CODE_VA, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SGRVETN_TERM_CODE_VA
          x-lineageLookupReferenceObject: stvterm
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
