openapi: 3.0.0
info:
  title: payment-management-system-code-maintenance
  description: API for FRVPMSC administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FRVPMSC
  x-source-domain: Finance
  x-source-title: Payment Management System Code Maintenance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/payment-management-system-code-maintenance:
    get:
      tags:
        - payment-management-system-code-maintenance
      summary: Return resources from FRVPMSC
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: acctCodeReceipts
          in: query
          description: Undistributed Cash Account
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_ACCT_CODE_RECEIPTS
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_ACTIVITY_DATE
        - name: agencyCode
          in: query
          description: Agency
          required: false
          schema:
            type: string
        - name: coasCode
          in: query
          description: Chart of Accounts
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_COAS_CODE
        - name: code
          in: query
          description: PMS Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_CODE
        - name: desc
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_DESC
        - name: lastInvSeqNo
          in: query
          description: Last Invoice Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_LAST_INV_SEQ_NO
        - name: locFundCode
          in: query
          description: Letter of Credit Fund
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_LOC_FUND_CODE
        - name: locLimit
          in: query
          description: Letter of Credit Limit
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_LOC_LIMIT
        - name: locNo
          in: query
          description: Letter of Credit Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FRVPMSC_LOC_NO
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/payment-management-system-code-maintenance-1.0.0_ge\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/payment-management-system-code-maintenance:
    post:
      tags:
        - payment-management-system-code-maintenance QAPI (Query by POST)
      summary: Return resources from FRVPMSC
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/payment-management-system-code-maintenance-1.0.0_ge\
                t_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/payment-management-system-code-maintenance-1.0.0_ge\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    payment-management-system-code-maintenance-1.0.0_get_response:
      required:
        - acctCodeReceipts
        - activityDate
        - agencyCode
        - coasCode
        - code
        - desc
        - lastInvSeqNo
        - locFundCode
      type: object
      properties:
        displayFundDesc:
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FRVPMSC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: FRVPMSC_ACTIVITY_DATE
        code:
          title: PMS Code
          maxLength: 16
          type: string
          description: "Lineage reference object : FRVPMSC_CODE"
          x-lineageReferenceObject: FRVPMSC_CODE
        locNo:
          title: Letter of Credit Number
          maxLength: 15
          type: string
          description: "Lineage reference object : FRVPMSC_LOC_NO"
          x-lineageReferenceObject: FRVPMSC_LOC_NO
        coasCode:
          title: Chart of Accounts
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_COAS_CODE, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: FRVPMSC_COAS_CODE
          x-lineageLookupReferenceObject: ftvcoas
        locLimit:
          title: Letter of Credit Limit
          maxLength: 15
          type: number
          description: "Lineage reference object : FRVPMSC_LOC_LIMIT"
          x-lineageReferenceObject: FRVPMSC_LOC_LIMIT
        acctCodeReceipts:
          title: Undistributed Cash Account
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_ACCT_CODE_RECEIPTS"
          x-lineageReferenceObject: FRVPMSC_ACCT_CODE_RECEIPTS
        agencyCode:
          title: Agency
          maxLength: 9
          type: string
        lastInvSeqNo:
          title: Last Invoice Number
          maxLength: 5
          type: number
          description: "Lineage reference object : FRVPMSC_LAST_INV_SEQ_NO"
          x-lineageReferenceObject: FRVPMSC_LAST_INV_SEQ_NO
        agencyName:
          maxLength: 230
          type: string
        locFundCode:
          title: Letter of Credit Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_LOC_FUND_CODE"
          x-lineageReferenceObject: FRVPMSC_LOC_FUND_CODE
        desc:
          maxLength: 35
          type: string
          description: "Lineage reference object : FRVPMSC_DESC"
          x-lineageReferenceObject: FRVPMSC_DESC
      x-lineageReferenceObject: frvpmsc
    payment-management-system-code-maintenance-1.0.0_get_request:
      required:
        - acctCodeReceipts
        - activityDate
        - agencyCode
        - coasCode
        - code
        - desc
        - lastInvSeqNo
        - locFundCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FRVPMSC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: FRVPMSC_ACTIVITY_DATE
        code:
          title: PMS Code
          maxLength: 16
          type: string
          description: "Lineage reference object : FRVPMSC_CODE"
          x-lineageReferenceObject: FRVPMSC_CODE
        locNo:
          title: Letter of Credit Number
          maxLength: 15
          type: string
          description: "Lineage reference object : FRVPMSC_LOC_NO"
          x-lineageReferenceObject: FRVPMSC_LOC_NO
        coasCode:
          title: Chart of Accounts
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_COAS_CODE, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: FRVPMSC_COAS_CODE
          x-lineageLookupReferenceObject: ftvcoas
        locLimit:
          title: Letter of Credit Limit
          maxLength: 15
          type: number
          description: "Lineage reference object : FRVPMSC_LOC_LIMIT"
          x-lineageReferenceObject: FRVPMSC_LOC_LIMIT
        acctCodeReceipts:
          title: Undistributed Cash Account
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_ACCT_CODE_RECEIPTS"
          x-lineageReferenceObject: FRVPMSC_ACCT_CODE_RECEIPTS
        agencyCode:
          title: Agency
          maxLength: 9
          type: string
        lastInvSeqNo:
          title: Last Invoice Number
          maxLength: 5
          type: number
          description: "Lineage reference object : FRVPMSC_LAST_INV_SEQ_NO"
          x-lineageReferenceObject: FRVPMSC_LAST_INV_SEQ_NO
        locFundCode:
          title: Letter of Credit Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_LOC_FUND_CODE"
          x-lineageReferenceObject: FRVPMSC_LOC_FUND_CODE
        desc:
          maxLength: 35
          type: string
          description: "Lineage reference object : FRVPMSC_DESC"
          x-lineageReferenceObject: FRVPMSC_DESC
      x-lineageReferenceObject: FRVPMSC
    payment-management-system-code-maintenance-1.0.0_qapi_post:
      type: object
      properties:
        acctCodeReceipts:
          title: Undistributed Cash Account
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_ACCT_CODE_RECEIPTS"
          x-lineageReferenceObject: FRVPMSC_ACCT_CODE_RECEIPTS
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FRVPMSC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: FRVPMSC_ACTIVITY_DATE
        agencyCode:
          title: Agency
          maxLength: 9
          type: string
        coasCode:
          title: Chart of Accounts
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_COAS_CODE, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: FRVPMSC_COAS_CODE
          x-lineageLookupReferenceObject: ftvcoas
        code:
          title: PMS Code
          maxLength: 16
          type: string
          description: "Lineage reference object : FRVPMSC_CODE"
          x-lineageReferenceObject: FRVPMSC_CODE
        desc:
          maxLength: 35
          type: string
          description: "Lineage reference object : FRVPMSC_DESC"
          x-lineageReferenceObject: FRVPMSC_DESC
        lastInvSeqNo:
          title: Last Invoice Number
          maxLength: 5
          type: number
          description: "Lineage reference object : FRVPMSC_LAST_INV_SEQ_NO"
          x-lineageReferenceObject: FRVPMSC_LAST_INV_SEQ_NO
        locFundCode:
          title: Letter of Credit Fund
          maxLength: 30
          type: string
          description: "Lineage reference object : FRVPMSC_LOC_FUND_CODE"
          x-lineageReferenceObject: FRVPMSC_LOC_FUND_CODE
        locLimit:
          title: Letter of Credit Limit
          maxLength: 15
          type: number
          description: "Lineage reference object : FRVPMSC_LOC_LIMIT"
          x-lineageReferenceObject: FRVPMSC_LOC_LIMIT
        locNo:
          title: Letter of Credit Number
          maxLength: 15
          type: string
          description: "Lineage reference object : FRVPMSC_LOC_NO"
          x-lineageReferenceObject: FRVPMSC_LOC_NO
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
