openapi: 3.0.0
info:
  title: parameter-definition
  description: API for GJAPDEF administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: GJAPDEF
  x-source-domain: Foundation
  x-source-title: Parameter Definitions
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/parameter-definition:
    get:
      tags:
        - parameter-definition
      summary: Return resources from GJAPDEF
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckJob
          in: query
          required: false
          schema:
            type: string
        - name: number
          in: query
          description: Parameter
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_NUMBER
        - name: desc
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_DESC
        - name: singleInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_SINGLE_IND
        - name: typeInd
          in: query
          description: Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_TYPE_IND
        - name: listValues
          in: query
          description: List
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_LIST_VALUES
        - name: length
          in: query
          description: Length
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_LENGTH
        - name: lowRange
          in: query
          description: Low
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_LOW_RANGE
        - name: validation
          in: query
          description: Validation
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_VALIDATION
        - name: highRange
          in: query
          description: High
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_HIGH_RANGE
        - name: helpText
          in: query
          description: Help
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_HELP_TEXT
        - name: optionalInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GJBPDEF_OPTIONAL_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/parameter-definition-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/parameter-definition:
    post:
      tags:
        - parameter-definition QAPI (Query by POST)
      summary: Return resources from GJAPDEF
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/parameter-definition-1.0.0_get_request"
            example:
              keyblckJob: TGRDELI
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/parameter-definition-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    parameter-definition-1.0.0_get_request:
      required:
        - number
        - desc
        - singleInd
        - typeInd
        - length
        - optionalInd
      type: object
      properties:
        number:
          title: Parameter
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPDEF_NUMBER"
          x-lineageReferenceObject: GJBPDEF_NUMBER
        listValues:
          title: List
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_LIST_VALUES"
          x-lineageReferenceObject: GJBPDEF_LIST_VALUES
        typeInd:
          title: Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_TYPE_IND"
          x-lineageReferenceObject: GJBPDEF_TYPE_IND
        helpText:
          title: Help
          maxLength: 78
          type: string
          description: "Lineage reference object : GJBPDEF_HELP_TEXT"
          x-lineageReferenceObject: GJBPDEF_HELP_TEXT
        optionalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_OPTIONAL_IND"
          x-lineageReferenceObject: GJBPDEF_OPTIONAL_IND
        length:
          title: Length
          maxLength: 2
          type: number
          description: "Lineage reference object : GJBPDEF_LENGTH"
          x-lineageReferenceObject: GJBPDEF_LENGTH
        highRange:
          title: High
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_HIGH_RANGE"
          x-lineageReferenceObject: GJBPDEF_HIGH_RANGE
        singleInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_SINGLE_IND"
          x-lineageReferenceObject: GJBPDEF_SINGLE_IND
        lowRange:
          title: Low
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_LOW_RANGE"
          x-lineageReferenceObject: GJBPDEF_LOW_RANGE
        validation:
          title: Validation
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_VALIDATION"
          x-lineageReferenceObject: GJBPDEF_VALIDATION
        keyblckJob:
          title: Process
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckJob"
          x-lineageReferenceObject: keyblckJob
        desc:
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_DESC"
          x-lineageReferenceObject: GJBPDEF_DESC
      x-lineageReferenceObject: GJBPDEF
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    parameter-definition-1.0.0_qapi_post:
      type: object
      properties:
        keyblckJob:
          type: string
        number:
          title: Parameter
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPDEF_NUMBER"
          x-lineageReferenceObject: GJBPDEF_NUMBER
        desc:
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_DESC"
          x-lineageReferenceObject: GJBPDEF_DESC
        singleInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_SINGLE_IND"
          x-lineageReferenceObject: GJBPDEF_SINGLE_IND
        typeInd:
          title: Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_TYPE_IND"
          x-lineageReferenceObject: GJBPDEF_TYPE_IND
        listValues:
          title: List
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_LIST_VALUES"
          x-lineageReferenceObject: GJBPDEF_LIST_VALUES
        length:
          title: Length
          maxLength: 2
          type: number
          description: "Lineage reference object : GJBPDEF_LENGTH"
          x-lineageReferenceObject: GJBPDEF_LENGTH
        lowRange:
          title: Low
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_LOW_RANGE"
          x-lineageReferenceObject: GJBPDEF_LOW_RANGE
        validation:
          title: Validation
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_VALIDATION"
          x-lineageReferenceObject: GJBPDEF_VALIDATION
        highRange:
          title: High
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_HIGH_RANGE"
          x-lineageReferenceObject: GJBPDEF_HIGH_RANGE
        helpText:
          title: Help
          maxLength: 78
          type: string
          description: "Lineage reference object : GJBPDEF_HELP_TEXT"
          x-lineageReferenceObject: GJBPDEF_HELP_TEXT
        optionalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_OPTIONAL_IND"
          x-lineageReferenceObject: GJBPDEF_OPTIONAL_IND
    parameter-definition-1.0.0_get_response:
      required:
        - desc
        - length
        - number
        - optionalInd
        - singleInd
        - typeInd
      type: object
      properties:
        listValues:
          title: List
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_LIST_VALUES"
          x-lineageReferenceObject: GJBPDEF_LIST_VALUES
        number:
          title: Parameter
          maxLength: 2
          type: string
          description: "Lineage reference object : GJBPDEF_NUMBER"
          x-lineageReferenceObject: GJBPDEF_NUMBER
        helpText:
          title: Help
          maxLength: 78
          type: string
          description: "Lineage reference object : GJBPDEF_HELP_TEXT"
          x-lineageReferenceObject: GJBPDEF_HELP_TEXT
        typeInd:
          title: Type
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_TYPE_IND"
          x-lineageReferenceObject: GJBPDEF_TYPE_IND
        optionalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_OPTIONAL_IND"
          x-lineageReferenceObject: GJBPDEF_OPTIONAL_IND
        defaultValue:
          title: Default
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : gjbpval"
          x-lineageLookupReferenceObject: gjbpval
        highRange:
          title: High
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_HIGH_RANGE"
          x-lineageReferenceObject: GJBPDEF_HIGH_RANGE
        length:
          title: Length
          maxLength: 2
          type: number
          description: "Lineage reference object : GJBPDEF_LENGTH"
          x-lineageReferenceObject: GJBPDEF_LENGTH
        lowRange:
          title: Low
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_LOW_RANGE"
          x-lineageReferenceObject: GJBPDEF_LOW_RANGE
        singleInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : GJBPDEF_SINGLE_IND"
          x-lineageReferenceObject: GJBPDEF_SINGLE_IND
        validation:
          title: Validation
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_VALIDATION"
          x-lineageReferenceObject: GJBPDEF_VALIDATION
        desc:
          maxLength: 30
          type: string
          description: "Lineage reference object : GJBPDEF_DESC"
          x-lineageReferenceObject: GJBPDEF_DESC
      x-lineageReferenceObject: gjbpdef
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
