openapi: 3.0.0
info:
  title: Budget Phase Line Items
  description: Budget details separated by line.
  version: "12.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Finance
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/budget-phase-line-items:
    get:
      summary: Return all resources from FBBBLIN
      description: Returns a paged listing of all the budget phase line item records
        from FBBBLIN table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_BUDGET_PHASE_LINE_ITEMS
      tags:
        - budget-phase-line-items
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v12+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Budget Phase  

            Returns all the budget phase line items for the given budgetPhase id

            ```

            /budget-phase-line-items?criteria={"budgetPhase":{"id":"3710f96e-3fd0-44d5-9535-85c2ca0d8700"}}

            ```

            ### Accounting String Component Values  

            Returns all the budget phase line items for the given accountingStringComponentValue list

            ```

            /budget-phase-line-items?criteria={"accountingStringComponentValues":[{"id":"5eb33af8-eb9c-4c70-af42-93312dc9ac67"}]}

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-budget-phase-line-items.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v12+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/budget-phase-line-items/{id}:
    get:
      summary: Return the requested resource from FBBBLIN
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_BUDGET_PHASE_LINE_ITEMS
      tags:
        - budget-phase-line-items
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Budget Phase Line Items for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v12+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v12+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v12+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-budget-phase-line-items.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-budget-phase-line-items.json:
      title: Budget Phase Line Items
      description: Budget details separated by line.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the budget phase line item.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: FBBBLIN_GUID(FBBBLIN)
        budgetPhase:
          title: Budget Phase
          description: The budget phase to which the line item belongs.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Budget Phase.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: budget-phases 
              x-lineageReferenceObject: FBBBLIN_OBPH_CODE(FBBBLIN)
          additionalProperties: false
          required:
            - id
        accountingStringComponentValues:
          title: Accounting String Component Values
          description: The accounting string details of the line item.
          type: array
          items:
            title: Accounting String Component Values
            description: The accounting string details of the line item.
            type: object
            properties:
              id:
                title: ID
                description: The global identifier for the Accounting String Component Values.
                type: string
                format: guid
                pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                x-lineageLookupReferenceObject: accounting-string-component-values 
                x-lineageReferenceObject: FBBBLIN_COAS_CODE(FBBBLIN) or FBBBLIN_ORGN_CODE(FBBBLIN) or FBBBLIN_ACCT_CODE(FBBBLIN) or 
                  FBBBLIN_FUND_CODE(FBBBLIN) or FBBBLIN_PROG_CODE(FBBBLIN) or FBBBLIN_ACTV_CODE(FBBBLIN) or FBBBLIN_LOCN_CODE(FBBBLIN)
            additionalProperties: false
            required:
              - id
        amount:
          title: Amount
          description: The amount associated with the line item.
          oneOf:
            - type: object
              format: currency
              properties:
                value:
                  title: Value
                  description: The monetary value
                  type: number
                  x-lineageReferenceObject: FBBBLIN_BUDG_AMT(FBBBLIN)
                currency:
                  title: Currency
                  description: The ISO 4217 currency code
                  x-lineageReferenceObject: derived
                  x-lineageDerivedLogic: For the institution base currency code, ISO currency code is displayed
                  enum:
                    - AED
                    - AFN
                    - ALL
                    - AMD
                    - ANG
                    - AOA
                    - ARS
                    - AUD
                    - AWG
                    - AZN
                    - BAM
                    - BBD
                    - BDT
                    - BGN
                    - BHD
                    - BIF
                    - BMD
                    - BND
                    - BOB
                    - BRL
                    - BSD
                    - BTN
                    - BWP
                    - BYR
                    - BZD
                    - CAD
                    - CDF
                    - CHF
                    - CLP
                    - CNY
                    - COP
                    - CRC
                    - CUC
                    - CUP
                    - CVE
                    - CZK
                    - DJF
                    - DKK
                    - DOP
                    - DZD
                    - EGP
                    - ERN
                    - ETB
                    - EUR
                    - FJD
                    - FKP
                    - GBP
                    - GEL
                    - GHS
                    - GIP
                    - GMD
                    - GNF
                    - GTQ
                    - GYD
                    - HKD
                    - HNL
                    - HRK
                    - HTG
                    - HUF
                    - IDR
                    - ILS
                    - INR
                    - IQD
                    - IRR
                    - ISK
                    - JMD
                    - JOD
                    - JPY
                    - KES
                    - KGS
                    - KHR
                    - KMF
                    - KPW
                    - KRW
                    - KWD
                    - KYD
                    - KZT
                    - LAK
                    - LBP
                    - LKR
                    - LRD
                    - LSL
                    - LYD
                    - MAD
                    - MDL
                    - MGA
                    - MKD
                    - MMK
                    - MNT
                    - MOP
                    - MRO
                    - MUR
                    - MVR
                    - MWK
                    - MXN
                    - MYR
                    - MZN
                    - NAD
                    - NGN
                    - NIO
                    - NOK
                    - NPR
                    - NZD
                    - OMR
                    - PAB
                    - PEN
                    - PGK
                    - PHP
                    - PKR
                    - PLN
                    - PYG
                    - QAR
                    - RON
                    - RSD
                    - RUB
                    - RWF
                    - SAR
                    - SBD
                    - SCR
                    - SDG
                    - SEK
                    - SGD
                    - SHP
                    - SLL
                    - SOS
                    - SRD
                    - SSP
                    - STD
                    - SVC
                    - SYP
                    - SZL
                    - THB
                    - TJS
                    - TMT
                    - TND
                    - TOP
                    - TRY
                    - TTD
                    - TWD
                    - TZS
                    - UAH
                    - UGX
                    - USD
                    - UYU
                    - UZS
                    - VEF
                    - VND
                    - VUV
                    - WST
                    - XAF
                    - XCD
                    - XOF
                    - XPF
                    - YER
                    - ZAR
                    - ZMW
                    - ZWL
                  type: string
              additionalProperties: false
              required:
                - value
                - currency
            - type: object
              maxProperties: 0
        comment:
          title: Comment
          description: The comment associated with the line item.
          type: string
          x-lineageReferenceObject: derived
          x-lineageDerivedLogic: For the FOBTEXT record corresponding to the FBBBLIN record, concatenate all the comments for all the FOBTEXT_SEQ_NUM and display the concatenated text.
      required:
        - id
        - budgetPhase
      additionalProperties: false
