openapi: 3.0.0
info:
  title: Student Academic Credentials
  description: The academic credentials the student has been awarded.
  version: 1.0.0
  x-source-system: banner
  x-api-type: ethos
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-academic-credentials:
    get:
      summary: Return all resources from SORLCUR
      description: Returns a paged listing of all the outcome curriculum records
        associated with an awarded degree/outcome record. In addition to
        publishing the current and active programs from SORLCUR table and
        associated fields of study from SORLFOS table, graduation and honors
        information are also retrieved from SHRDGMR table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUD_ACAD_CREDS
      tags:
        - student-academic-credentials
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Student  

            The student who has been awarded an academic credential.

            ```

            /student-academic-credentials?criteria={"student":{"id":"4a0c95f7-0903-408a-8694-77b313809909"}}

            ```

            ### Student Program  

            The academic program associated with the academic credential.

            ```

            /student-academic-credentials?criteria={"studentProgram":{"id":"3efc95f7-0903-408a-8694-77b313806639"}}

            ```

            ### Academic Level  

            The academic level associated with the academic credential.

            ```

            /student-academic-credentials?criteria={"academicLevel":{"id":"8tfc95f7-0903-408a-8694-77b313806609"}}

            ```

            ### Credentials  

            The academic credential that has been awarded.

            ```

            /student-academic-credentials?criteria={"credentials":[{"credential":{"id":"7a6e9b82-e78b-47db-9f30-5becff004921"}}]}

            ```

            ### Graduation Academic Period  

            The academic period in which the student graduated.

            ```

            /student-academic-credentials?criteria={"graduationAcademicPeriod":{"id":"b24b5455-e030-4035-88a0-ef999e9d4171"}}

            ```

            ### Graduated On  

            Supported operators are $gt, $gte, $lt, $lte, or the default of equals if operator is not specified.


            Returns all student academic credentials for the graduated on date passed.

            ```

            /student-academic-credentials?criteria={"graduatedOn":"1995-02-06"}

            ```

            ```

            /student-academic-credentials?criteria={"graduatedOn":{"$eq":"1995-01-01"}}

            ```

            Returns all student academic credentials with graduated on date less than the graduated on date passed.

            ```

            /student-academic-credentials?criteria={"graduatedOn":{"$lt":"1995-01-01"}}

            ```

            Returns all student academic credentials with graduated on date less than equals to the graduated on date passed.

            ```

            /student-academic-credentials?criteria={"graduatedOn":{"$lte":"1995-01-01"}}

            ```

            Returns all student academic credentials with graduated on date greater than the graduated on date passed.

            ```

            /student-academic-credentials?criteria={"graduatedOn":{"$gt":"1995-01-01"}}

            ```

            Returns all student academic credentials with graduated on date greater than equals to the graduated on date passed.

            ```

            /student-academic-credentials?criteria={"graduatedOn":{"$gte":"1995-01-01"}}

            ```
        - name: personFilter
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Person Filter  

            Retrieve information for a specified population.

            ```

            /student-academic-credentials?personFilter={"personFilter":{"id":"349de286-6c25-494c-b602-57d348bd67aa"}}

            ```
        - name: academicPrograms
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Academic Programs  

            Filter to return student academic credentials by academic program.

            ```

            /student-academic-credentials?academicPrograms={"academicPrograms":{"id":"800b6a3a-01eb-458f-a855-9d6a03d524c8"}}

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-student-academic-credentials.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/student-academic-credentials/{id}:
    get:
      summary: Return the requested resource from SORLCUR
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUD_ACAD_CREDS
      tags:
        - student-academic-credentials
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Student Academic Credentials for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-student-academic-credentials.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-student-academic-credentials.json:
      title: Student Academic Credentials
      description: The academic credentials the student has been awarded.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the student academic credential.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: SORLCUR_OUTCOME_GUID(SORLCUR)
        student:
          title: Student
          description: The student who has been awarded an academic credential.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Student.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: persons 
              x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = persons) 
              x-lineageDerivedLogic: A record in GORGUID where GORGUID_LDM_NAME = 'persons' and GORGUID_DOMAIN_KEY = SORLCUR_PIDM
          additionalProperties: false
          required:
            - id
        studentProgram:
          title: Student Program
          description: The student academic program associated with the academic credential.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Student Program.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: student-academic-programs 
                  x-lineageReferenceObject: SORLCUR_GUID(SORLCUR)
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        academicLevel:
          title: Academic Level
          description: The academic level associated with the academic credential.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Academic Level.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-levels 
                  x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = academic-levels) 
                  x-lineageDerivedLogic: A record in GORGUID where GORGUID_LDM_NAME = 'academic-levels' and GORGUID_DOMAIN_KEY = SORLCUR_LEVL_CODE.
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        credentials:
          title: Credentials
          description: The academic credentials awarded to the student.
          type: array
          items:
            type: object
            properties:
              credential:
                title: Credential
                description: The academic credential that has been awarded.
                type: object
                properties:
                  id:
                    title: ID
                    description: The global identifier for the Credential.
                    type: string
                    format: guid
                    pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                    x-lineageLookupReferenceObject: academic-credentials 
                    x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = academic-credentials) 
                    x-lineageDerivedLogic: A record in GORGUID where GORGUID_LDM_NAME = 'academic-credentials' and GORGUID_DOMAIN_KEY =SORLCUR_DEGC_CODE.
                additionalProperties: false
                required:
                  - id
              earnedOn:
                title: Earned On
                description: The date when the person earned the credential.
                oneOf:
                  - type: string
                    format: date
                    pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
                    x-lineageReferenceObject: SHRDGMR_GRAD_DATE(SHRDGMR)
                  - type: string
                    maxLength: 0
            additionalProperties: false
            required:
              - credential
        disciplines:
          title: Disciplines
          description: The disciplines associated with the awarded credentials.
          type: array
          items:
            title: Disciplines
            description: The disciplines associated with the awarded credentials.
            type: object
            properties:
              id:
                title: ID
                description: The global identifier for the Disciplines.
                type: string
                format: guid
                pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                x-lineageLookupReferenceObject: academic-disciplines 
                x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = academic-disciplines) 
                x-lineageDerivedLogic: A record in GORGUID where GORGUID_LDM_NAME = 'academic-disciplines' and GORGUID_DOMAIN_KEY = SORLFOS_MAJR_CODE + SORLFOS_LFST_CODE (lower case)
            additionalProperties: false
            required:
              - id
        recognitions:
          title: Recognitions
          description: A list of academic recognitions the student has received.
          type: array
          items:
            title: Recognitions
            description: A list of academic recognitions the student has received.
            type: object
            properties:
              id:
                title: ID
                description: The global identifier for the Recognitions.
                type: string
                format: guid
                pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                x-lineageLookupReferenceObject: academic-honors 
                x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = institutional-honors) or GORGUID_GUID(LDM_NAME = departmental-honors)
                x-lineageDerivedLogic: A record in GORGUID where GORGUID_LDM_NAME = 'institutional-honors'and GORGUID_DOMAIN_KEY = SHRDGIH_HONR_CODE and SHRDGIH_DGMR_SEQ_NO = SHRDGMR_SEQ_NO of the record being processed) and SORLCUR_KEY_SEQNO = SHRDGMR_SEQ_NO. A record in GORGUID where GORGUID_LDM_NAME = 'departmental-honors'and GORGUID_DOMAIN_KEY = SHRDGDH_HOND_CODE and SHRDGDH_DGMR_SEQ_NO = SHRDGMR_SEQ_NO of the record being processed and SORLCUR_KEY_SEQNO = SHRDGMR_SEQ_NO
            additionalProperties: false
            required:
              - id
        graduatedOn:
          title: Graduated On
          description: The date the student graduated from the program.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: SHRDGMR_GRAD_DATE(SHRDGMR)
            - type: string
              maxLength: 0
        thesisTitle:
          title: Thesis Title
          description: The title of the thesis (dissertation).
          type: string
          x-lineageReferenceObject: unsupported
        graduationAcademicPeriod:
          title: Graduation Academic Period
          description: The academic period in which the student graduated.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Graduation Academic Period.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-periods 
                  x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = term) 
                  x-lineageDerivedLogic: A record in GORGUID where GORGUID_LDM_NAME = 'academic-periods' and GORGUID_DOMAIN_KEY = SHRDGMR_TERM_CODE_GRAD
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        graduationYear:
          title: Graduation Year
          description: The year in which the student graduated.
          type: string
          x-lineageReferenceObject: SHRDGMR_ACYR_CODE(SHRDGMR)
      required:
        - id
        - student
        - credentials
      additionalProperties: false
