openapi: 3.0.0
info:
  title: Academic Catalogs
  description: All academic catalog identifiers defined by the institution that
    represents the student's academic catalog term on program and field of study
    records.
  version: 6.1.0
  x-source-system: banner
  x-api-type: ethos
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/academic-catalogs:
    get:
      summary: Returns all resources from STVTERM.
      description: Returns all academic catalog records from STVTERM table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_CATALOGS
      tags:
        - academic-catalogs
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: |
            ### N/A  
        - name: sort
          in: query
          required: false
          schema:
            type: object
          description: |
            ### N/A  
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-academic-catalogs.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.1.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/academic-catalogs/{id}:
    get:
      summary: Returns the requested resource from STVTERM
      description: Returns an academic catalog record from STVTERM table for the
        passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ACADEMIC_CATALOGS
      tags:
        - academic-catalogs
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of an academic catalog for use in all external
            references.
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.1.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6.1.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-academic-catalogs.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-academic-catalogs.json:
      title: Academic Catalogs
      description: A catalog listing of the courses offered by an organization.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: A global identifier of an academic catalog for use in all external
            references.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: STVTERM_CATALOG_GUID(STVTERM)
        title:
          title: Title
          description: The full name of an academic catalog.
          type: string
          minLength: 1
          x-lineageReferenceObject: STVTERM_DESC(STVTERM)
        description:
          title: Description
          description: A full description of an academic catalog.
          type: string
          x-lineageReferenceObject: unsupported
        code:
          title: Code
          description: The code that identifies an academic catalog.
          type: string
          x-lineageReferenceObject: STVTERM_CODE
        startOn:
          title: Start Date
          description: The beginning date for when an academic catalog takes effect.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
              x-lineageReferenceObject: STVTERM_START_DATE(STVTERM)
            - type: string
              maxLength: 0
        endOn:
          title: End Date
          description: The ending date for when an academic catalog is no longer in effect.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
              x-lineageReferenceObject: unsupported
            - type: string
              maxLength: 0
        status:
          title: Status
          description: A status of an academic catalog. Not currently in use.
          x-lineageReferenceObject: unsupported
          oneOf:
            - type: string
              enum:
                - active
                - inactive
            - type: string
              maxLength: 0
        institution:
          title: Institution
          description: The educational institution that owns the academic catalog
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Institution.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: educational-institutions 
                  x-lineageReferenceObject: derived
                  x-lineageDerivedLogic: A record in GORGUID for GORGUID_LDM_NAME = 'institutional-description' for the home institution.
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        academicPrograms:
          title: Academic Programs
          description: Academic programs that make up the catalog.
          type: array
          items:
            title: Academic Programs
            description: Academic programs that make up the catalog.
            type: object
            properties:
              id:
                title: ID
                description: The global identifier for the Academic Programs.
                type: string
                format: guid
                pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                x-lineageLookupReferenceObject: academic-programs 
                x-lineageReferenceObject: unsupported
            additionalProperties: false
            required:
              - id
      required:
        - id
        - title
      additionalProperties: false
