openapi: 3.0.0
info:
  title: account-review-form-exemptions
  description: API for TSAACCT administrative page
  version: 1.0.0
  extensions:
    x-audience: all
    x-release-status: ga
    x-source-name: TSAACCT
    x-source-domain: Student
    x-source-title: Account Review Form
    x-source-system: banner
    x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/account-review-form-exemptions:
    put:
      tags:
      - account-review-form-exemptions
      summary: Updates an existing resource in TSAACCT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/account-review-form-exemptions-1.0.0_put_request"
              exampleSetFlag: false
            example:
              exemptionCode: 77
              criteria.exemptionCode: 66
              stspKeySequence: 99
              criteria.exemptionPriority: 1
              criteria.studentExptRollInd: "N"
              exemptionPriority: 2
              criteria.termCode: 666666
              delInd: D
              studentExptRollInd: "Y"
              maxStudentAmount: 1000
              id: 210009103
              criteria.maxStudentAmount: 500
              termCode: 777777
            exampleSetFlag: true
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
                exampleSetFlag: false
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
                exampleSetFlag: false
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
                exampleSetFlag: false
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/account-review-form-exemptions-1.0.0_put_response"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
    post:
      tags:
      - account-review-form-exemptions
      summary: Creates a new resource in TSAACCT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/account-review-form-exemptions-1.0.0_post_request"
              exampleSetFlag: false
            example:
              exemptionCode: 10000001
              delInd: D
              studentExptRollInd: "N"
              maxStudentAmount: 1111
              id: HOSMC0004
              exemptionPriority: 3
              termCode: 201920
            exampleSetFlag: true
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
                exampleSetFlag: false
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
                exampleSetFlag: false
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
                exampleSetFlag: false
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/account-review-form-exemptions-1.0.0_post_response"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
                  exampleSetFlag: false
                types:
                - array
              exampleSetFlag: false
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/account-review-form-exemptions: {}
components:
  schemas:
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          exampleSetFlag: false
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
                exampleSetFlag: false
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
                exampleSetFlag: false
              code:
                type: string
                description: The error message code used to describe the error details.
                exampleSetFlag: false
              description:
                type: string
                description: The error description used to describe the error details.
                exampleSetFlag: false
              message:
                type: string
                description: 'The detailed actionable error message. '
                exampleSetFlag: false
            exampleSetFlag: false
            types:
            - object
          types:
          - array
      exampleSetFlag: false
      types:
      - object
    account-review-form-exemptions-1.0.0_post_request:
      required:
      - exemptionCode
      - termCode
      - exemptionPriority
      type: object
      properties:
        exemptionCode:
          title: Code
          maxLength: 8
          type: string
          description: "Lineage reference object : TBBESTU_EXEMPTION_CODE"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_CODE
          exampleSetFlag: false
        delInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_DEL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_DEL_IND
          exampleSetFlag: false
        stspKeySequence:
          title: Study Path
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBESTU_STSP_KEY_SEQUENCE"
          extensions:
            x-lineageReferenceObject: TBBESTU_STSP_KEY_SEQUENCE
          exampleSetFlag: false
        studentExptRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_STUDENT_EXPT_ROLL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_STUDENT_EXPT_ROLL_IND
          exampleSetFlag: false
        maxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBESTU_MAX_STUDENT_AMOUNT"
          extensions:
            x-lineageReferenceObject: TBBESTU_MAX_STUDENT_AMOUNT
          exampleSetFlag: false
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          extensions:
            x-lineageReferenceObject: id
          exampleSetFlag: false
        exemptionPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBESTU_EXEMPTION_PRIORITY"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_PRIORITY
          exampleSetFlag: false
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBESTU_TERM_CODE, Lookup lineage\
            \ reference object : stvterm"
          extensions:
            x-lineageReferenceObject: TBBESTU_TERM_CODE
            x-lineageLookupReferenceObject: stvterm
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: TBBESTU
      exampleSetFlag: false
    account-review-form-exemptions-1.0.0_put_request:
      required:
      - criteria.exemptionCode
      - criteria.termCode
      - criteria.exemptionPriority
      - exemptionCode
      - termCode
      - exemptionPriority
      type: object
      properties:
        exemptionCode:
          title: Code
          maxLength: 8
          type: string
          description: "Lineage reference object : TBBESTU_EXEMPTION_CODE"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_CODE
          exampleSetFlag: false
        criteria.exemptionCode:
          title: Code
          maxLength: 8
          type: string
          description: "Lineage reference object : TBBESTU_EXEMPTION_CODE"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_CODE
          exampleSetFlag: false
        stspKeySequence:
          title: Study Path
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBESTU_STSP_KEY_SEQUENCE"
          extensions:
            x-lineageReferenceObject: TBBESTU_STSP_KEY_SEQUENCE
          exampleSetFlag: false
        criteria.exemptionPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBESTU_EXEMPTION_PRIORITY"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_PRIORITY
          exampleSetFlag: false
        criteria.studentExptRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_STUDENT_EXPT_ROLL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_STUDENT_EXPT_ROLL_IND
          exampleSetFlag: false
        exemptionPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBESTU_EXEMPTION_PRIORITY"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_PRIORITY
          exampleSetFlag: false
        criteria.termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBESTU_TERM_CODE, Lookup lineage\
            \ reference object : stvterm"
          extensions:
            x-lineageReferenceObject: TBBESTU_TERM_CODE
            x-lineageLookupReferenceObject: stvterm
          exampleSetFlag: false
        criteria.stspKeySequence:
          title: Study Path
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBESTU_STSP_KEY_SEQUENCE"
          extensions:
            x-lineageReferenceObject: TBBESTU_STSP_KEY_SEQUENCE
          exampleSetFlag: false
        criteria.delInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_DEL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_DEL_IND
          exampleSetFlag: false
        delInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_DEL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_DEL_IND
          exampleSetFlag: false
        studentExptRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_STUDENT_EXPT_ROLL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_STUDENT_EXPT_ROLL_IND
          exampleSetFlag: false
        maxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBESTU_MAX_STUDENT_AMOUNT"
          extensions:
            x-lineageReferenceObject: TBBESTU_MAX_STUDENT_AMOUNT
          exampleSetFlag: false
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          extensions:
            x-lineageReferenceObject: id
          exampleSetFlag: false
        criteria.maxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBESTU_MAX_STUDENT_AMOUNT"
          extensions:
            x-lineageReferenceObject: TBBESTU_MAX_STUDENT_AMOUNT
          exampleSetFlag: false
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBESTU_TERM_CODE, Lookup lineage\
            \ reference object : stvterm"
          extensions:
            x-lineageReferenceObject: TBBESTU_TERM_CODE
            x-lineageLookupReferenceObject: stvterm
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: TBBESTU
      exampleSetFlag: false
    account-review-form-exemptions-1.0.0_put_response:
      required:
      - exemptionCode
      - exemptionPriority
      - termCode
      type: object
      properties:
        exemptionCode:
          title: Code
          maxLength: 8
          type: string
          description: "Lineage reference object : TBBESTU_EXEMPTION_CODE"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_CODE
          exampleSetFlag: false
        delInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_DEL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_DEL_IND
          exampleSetFlag: false
        stspKeySequence:
          title: Study Path
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBESTU_STSP_KEY_SEQUENCE"
          extensions:
            x-lineageReferenceObject: TBBESTU_STSP_KEY_SEQUENCE
          exampleSetFlag: false
        studentExptRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_STUDENT_EXPT_ROLL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_STUDENT_EXPT_ROLL_IND
          exampleSetFlag: false
        maxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBESTU_MAX_STUDENT_AMOUNT"
          extensions:
            x-lineageReferenceObject: TBBESTU_MAX_STUDENT_AMOUNT
          exampleSetFlag: false
        tbbexptDesc:
          maxLength: 30
          type: string
          exampleSetFlag: false
        exemptionPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBESTU_EXEMPTION_PRIORITY"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_PRIORITY
          exampleSetFlag: false
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBESTU_TERM_CODE, Lookup lineage\
            \ reference object : stvterm"
          extensions:
            x-lineageReferenceObject: TBBESTU_TERM_CODE
            x-lineageLookupReferenceObject: stvterm
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: tbbestu
      exampleSetFlag: false
    account-review-form-exemptions-1.0.0_post_response:
      required:
      - exemptionCode
      - exemptionPriority
      - termCode
      type: object
      properties:
        exemptionCode:
          title: Code
          maxLength: 8
          type: string
          description: "Lineage reference object : TBBESTU_EXEMPTION_CODE"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_CODE
          exampleSetFlag: false
        delInd:
          title: Delete Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_DEL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_DEL_IND
          exampleSetFlag: false
        stspKeySequence:
          title: Study Path
          maxLength: 30
          type: number
          description: "Lineage reference object : TBBESTU_STSP_KEY_SEQUENCE"
          extensions:
            x-lineageReferenceObject: TBBESTU_STSP_KEY_SEQUENCE
          exampleSetFlag: false
        studentExptRollInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBESTU_STUDENT_EXPT_ROLL_IND"
          extensions:
            x-lineageReferenceObject: TBBESTU_STUDENT_EXPT_ROLL_IND
          exampleSetFlag: false
        maxStudentAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBBESTU_MAX_STUDENT_AMOUNT"
          extensions:
            x-lineageReferenceObject: TBBESTU_MAX_STUDENT_AMOUNT
          exampleSetFlag: false
        tbbexptDesc:
          maxLength: 30
          type: string
          exampleSetFlag: false
        exemptionPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBBESTU_EXEMPTION_PRIORITY"
          extensions:
            x-lineageReferenceObject: TBBESTU_EXEMPTION_PRIORITY
          exampleSetFlag: false
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBESTU_TERM_CODE, Lookup lineage\
            \ reference object : stvterm"
          extensions:
            x-lineageReferenceObject: TBBESTU_TERM_CODE
            x-lineageLookupReferenceObject: stvterm
          exampleSetFlag: false
      extensions:
        x-lineageReferenceObject: tbbestu
      exampleSetFlag: false
  securitySchemes:
    BasicAuth:
      type: HTTP
      scheme: basic
    EllucianOAuthUserToken:
      type: HTTP
      scheme: bearer
