openapi: 3.0.0
info:
  title: UCAS Subtest Types
  description: The UCAS Subtest Types API fetches all UCAS subtest types.
  version: 1.0.0
  x-source-name: SKBUEBL, SKBUEXA, SKBUSUB, STVTADM, STVTESC
  x-source-title: UCAS Subtest Types
  x-source-domain: Student
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ucas-subtest-types:
    get:
      tags:
        - ucas-subtest-types
      summary: Returns UCAS subtest types.
      description: Returns resources from SKBUEBL, SKBUEXA, SKBUSUB, STVTADM and STVTESC.
      x-method-permissions: API_UCAS_SUBTEST_TYPES
      parameters:
        - name: limit
          in: query
          description: |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
            $ref: "#/components/schemas/ucas-subtest-types-v1.0.0_response"
          description: >
            ### Year

            Returns the UCAS subtest types for the specified year.

            ```

            /ucas-subtest-types?criteria={"year":"2023"}

            ```

            ### Sitting Code

            Returns the list of ucas subtest types with information on key indicators
            having specific sitting code.

            ```

            /ucas-subtest-types?criteria={"sitting":["A","S","W"]}

            ```
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a
                partial representation is returned. Otherwise, this header is
                not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ucas-subtest-types-v1.0.0_response"
        "400":
          description: Failure. Bad Request. The server cannot process the request due to
            something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "401":
          description: Failure. Unauthorized.
        "403":
          description: Failure. Forbidden. The user does not have the required permissions
            for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "404":
          description: Failure. Not Found. Cannot map the URI to a resource.
        "405":
          description: Failure. Method Not Allowed. The client tried to use an HTTP method
            that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "406":
          description: Failure. Not Acceptable. Unable to generate any of the client’s
            preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
        "500":
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors_2_0_0"
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    ucas-subtest-types-v1.0.0_response:
      type: object
      properties:
        testTypeCode:
          title: Test Type Code
          maxLength: 10
          type: string
          description: The code for the level of examination.
          x-lineageReferenceObject: SKBUEBL_EXAMLEVEL
        subTestTypeCode:
          title: Subtest Type Code
          maxLength: 6
          type: string
          description: Enquiry Based Learning subject associated with the UCAS subject.
          x-lineageReferenceObject: SKBUSUB_EBL_SUBJ
        subTestTypeName:
          title: Subtest Type Name
          maxLength: 250
          type: string
          description: UCAS subject description.
          x-lineageReferenceObject: SKBUSUB_SUBJTEXT
        erpSubTestTypeName:
          title: ERP Subtest Name
          maxLength: 30
          type: string
          description: The test (e.g. SAT Verbal, ACT Composite, Graduate Record Exam) associated with the test code.
          x-lineageReferenceObject: STVTESC_DESC
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: The detailed actionable error message.
