openapi: 3.0.0
info:
  title: pay-event-list
  description: API for PHILIST administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PHILIST
  x-source-domain: Human Resources
  x-source-title: Pay Event List
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/pay-event-list:
    get:
      tags:
        - pay-event-list
      summary: Return resources from PHILIST
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: year
          in: query
          description: Year
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_YEAR
        - name: pictCode
          in: query
          description: Payroll ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_PICT_CODE
        - name: payno
          in: query
          description: Payroll Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_PAYNO
        - name: seqNo
          in: query
          description: Sequence Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_SEQ_NO
        - name: typeInd
          in: query
          description: Event Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_TYPE_IND
        - name: disp
          in: query
          description: Disposition
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_DISP
        - name: eventDate
          in: query
          description: History Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_EVENT_DATE
        - name: gross
          in: query
          description: Gross
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_GROSS
        - name: net
          in: query
          description: Net
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_NET
        - name: adjsSeqNo
          in: query
          description: Sequence Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_ADJS_SEQ_NO
        - name: adjsDate
          in: query
          description: Adjusts Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_ADJS_DATE
        - name: adjBySeqNo
          in: query
          description: Sequence Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_ADJ_BY_SEQ_NO
        - name: adjByDate
          in: query
          description: Adjusted By Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_ADJ_BY_DATE
        - name: postingOverrideDate
          in: query
          description: Posting Override Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_POSTING_OVERRIDE_DATE
        - name: commentInd
          in: query
          required: false
          schema:
            type: string
        - name: userId
          in: query
          description: User ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PHRHIST_USER_ID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/pay-event-list-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/pay-event-list:
    post:
      tags:
        - pay-event-list QAPI (Query by POST)
      summary: Return resources from PHILIST
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/pay-event-list-1.0.0_get_request"
            example:
              id: 12
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/pay-event-list-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    pay-event-list-1.0.0_get_response:
      type: object
      properties:
        adjBySeqNo:
          title: Sequence Number
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_ADJ_BY_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_ADJ_BY_SEQ_NO
        adjsSeqNo:
          title: Sequence Number
          maxLength: 2
          type: number
          description: "Lineage reference object : PHRHIST_ADJS_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_ADJS_SEQ_NO
        typeInd:
          title: Event Type
          maxLength: 1
          type: string
          description: "Lineage reference object : PHRHIST_TYPE_IND"
          x-lineageReferenceObject: PHRHIST_TYPE_IND
        typeDesc:
          title: Description
          maxLength: 13
          type: string
        gross:
          title: Gross
          maxLength: 14
          type: number
          description: "Lineage reference object : PHRHIST_GROSS"
          x-lineageReferenceObject: PHRHIST_GROSS
        seqNo:
          title: Sequence Number
          maxLength: 2
          type: number
          description: "Lineage reference object : PHRHIST_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_SEQ_NO
        year:
          title: Year
          maxLength: 4
          type: string
          description: "Lineage reference object : PHRHIST_YEAR"
          x-lineageReferenceObject: PHRHIST_YEAR
        adjsDate:
          title: Adjusts Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_ADJS_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ADJS_DATE
        adjByDate:
          title: Adjusted By Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_ADJ_BY_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ADJ_BY_DATE
        disp:
          title: Disposition
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_DISP"
          x-lineageReferenceObject: PHRHIST_DISP
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : PHRHIST_USER_ID"
          x-lineageReferenceObject: PHRHIST_USER_ID
        payno:
          title: Payroll Number
          maxLength: 3
          type: number
          description: "Lineage reference object : PHRHIST_PAYNO"
          x-lineageReferenceObject: PHRHIST_PAYNO
        postingOverrideDate:
          title: Posting Override Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_POSTING_OVERRIDE_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_POSTING_OVERRIDE_DATE
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PHRHIST_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ACTIVITY_DATE
        pictCode:
          title: Payroll ID
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_PICT_CODE"
          x-lineageReferenceObject: PHRHIST_PICT_CODE
        commentInd:
          maxLength: 1
          type: string
        net:
          title: Net
          maxLength: 14
          type: number
          description: "Lineage reference object : PHRHIST_NET"
          x-lineageReferenceObject: PHRHIST_NET
        eventDate:
          title: History Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_EVENT_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_EVENT_DATE
      x-lineageReferenceObject: phrhist
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    pay-event-list-1.0.0_get_request:
      type: object
      properties:
        adjBySeqNo:
          title: Sequence Number
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_ADJ_BY_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_ADJ_BY_SEQ_NO
        adjsSeqNo:
          title: Sequence Number
          maxLength: 2
          type: number
          description: "Lineage reference object : PHRHIST_ADJS_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_ADJS_SEQ_NO
        typeInd:
          title: Event Type
          maxLength: 1
          type: string
          description: "Lineage reference object : PHRHIST_TYPE_IND"
          x-lineageReferenceObject: PHRHIST_TYPE_IND
        seqNo:
          title: Sequence Number
          maxLength: 2
          type: number
          description: "Lineage reference object : PHRHIST_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_SEQ_NO
        gross:
          title: Gross
          maxLength: 14
          type: number
          description: "Lineage reference object : PHRHIST_GROSS"
          x-lineageReferenceObject: PHRHIST_GROSS
        year:
          title: Year
          maxLength: 4
          type: string
          description: "Lineage reference object : PHRHIST_YEAR"
          x-lineageReferenceObject: PHRHIST_YEAR
        disp:
          title: Disposition
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_DISP"
          x-lineageReferenceObject: PHRHIST_DISP
        adjsDate:
          title: Adjusts Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_ADJS_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ADJS_DATE
        adjByDate:
          title: Adjusted By Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_ADJ_BY_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ADJ_BY_DATE
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : PHRHIST_USER_ID"
          x-lineageReferenceObject: PHRHIST_USER_ID
        payno:
          title: Payroll Number
          maxLength: 3
          type: number
          description: "Lineage reference object : PHRHIST_PAYNO"
          x-lineageReferenceObject: PHRHIST_PAYNO
        postingOverrideDate:
          title: Posting Override Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_POSTING_OVERRIDE_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_POSTING_OVERRIDE_DATE
        pictCode:
          title: Payroll ID
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_PICT_CODE"
          x-lineageReferenceObject: PHRHIST_PICT_CODE
        commentInd:
          maxLength: 1
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        net:
          title: Net
          maxLength: 14
          type: number
          description: "Lineage reference object : PHRHIST_NET"
          x-lineageReferenceObject: PHRHIST_NET
        eventDate:
          title: History Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_EVENT_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_EVENT_DATE
      x-lineageReferenceObject: PHRHIST
    pay-event-list-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        year:
          title: Year
          maxLength: 4
          type: string
          description: "Lineage reference object : PHRHIST_YEAR"
          x-lineageReferenceObject: PHRHIST_YEAR
        pictCode:
          title: Payroll ID
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_PICT_CODE"
          x-lineageReferenceObject: PHRHIST_PICT_CODE
        payno:
          title: Payroll Number
          maxLength: 3
          type: number
          description: "Lineage reference object : PHRHIST_PAYNO"
          x-lineageReferenceObject: PHRHIST_PAYNO
        seqNo:
          title: Sequence Number
          maxLength: 2
          type: number
          description: "Lineage reference object : PHRHIST_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_SEQ_NO
        typeInd:
          title: Event Type
          maxLength: 1
          type: string
          description: "Lineage reference object : PHRHIST_TYPE_IND"
          x-lineageReferenceObject: PHRHIST_TYPE_IND
        disp:
          title: Disposition
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_DISP"
          x-lineageReferenceObject: PHRHIST_DISP
        eventDate:
          title: History Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_EVENT_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_EVENT_DATE
        gross:
          title: Gross
          maxLength: 14
          type: number
          description: "Lineage reference object : PHRHIST_GROSS"
          x-lineageReferenceObject: PHRHIST_GROSS
        net:
          title: Net
          maxLength: 14
          type: number
          description: "Lineage reference object : PHRHIST_NET"
          x-lineageReferenceObject: PHRHIST_NET
        adjsSeqNo:
          title: Sequence Number
          maxLength: 2
          type: number
          description: "Lineage reference object : PHRHIST_ADJS_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_ADJS_SEQ_NO
        adjsDate:
          title: Adjusts Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_ADJS_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ADJS_DATE
        adjBySeqNo:
          title: Sequence Number
          maxLength: 2
          type: string
          description: "Lineage reference object : PHRHIST_ADJ_BY_SEQ_NO"
          x-lineageReferenceObject: PHRHIST_ADJ_BY_SEQ_NO
        adjByDate:
          title: Adjusted By Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_ADJ_BY_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_ADJ_BY_DATE
        postingOverrideDate:
          title: Posting Override Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PHRHIST_POSTING_OVERRIDE_DATE"
          format: date-time
          x-lineageReferenceObject: PHRHIST_POSTING_OVERRIDE_DATE
        commentInd:
          maxLength: 1
          type: string
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : PHRHIST_USER_ID"
          x-lineageReferenceObject: PHRHIST_USER_ID
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
