openapi: 3.0.0
info:
  title: proxy-access-management-access-list
  description: API for GPAPRXY administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: GPAPRXY
  x-source-domain: Foundation
  x-source-title: Proxy Access Management Form
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/proxy-access-management-access-list:
    get:
      tags:
        - proxy-access-management-access-list
      summary: Return resources from GPAPRXY
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/proxy-access-management-access-list-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/proxy-access-management-access-list:
    post:
      tags:
        - proxy-access-management-access-list QAPI (Query by POST)
      summary: Return resources from GPAPRXY
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/proxy-access-management-access-list-1.0.0_get_reque\
                st"
            example:
              id: HOS00001
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/proxy-access-management-access-list-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    proxy-access-management-access-list-1.0.0_get_request:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
    proxy-access-management-access-list-1.0.0_get_response:
      type: object
      properties:
        proxy:
          type: array
          items:
            type: object
            properties:
              recCount:
                title: of
                maxLength: 30
                type: number
              gpbprxyPinDisabledInd:
                title: PIN Disabled
                maxLength: 1
                type: string
                description: "Lineage reference object : GPBPRXY_PIN_DISABLED_IND"
                x-lineageReferenceObject: GPBPRXY_PIN_DISABLED_IND
              curRec:
                title: Record
                maxLength: 30
                type: string
              gtvretpDesc:
                title: Relationship
                maxLength: 60
                type: string
                description: "Lineage reference object : GTVRETP_DESC"
                x-lineageReferenceObject: GTVRETP_DESC
              gprxrefPassphrase:
                title: "Passphrase:"
                maxLength: 256
                type: string
                description: "Lineage reference object : GPRXREF_PASSPHRASE"
                x-lineageReferenceObject: GPRXREF_PASSPHRASE
              gprxrefStopDate:
                title: Stop Date
                maxLength: 11
                type: string
                description: "Lineage reference object : GPRXREF_STOP_DATE"
                format: date-time
                x-lineageReferenceObject: GPRXREF_STOP_DATE
              gpbprxyPinExpDate:
                title: PIN Expire Date
                maxLength: 11
                type: string
                description: "Lineage reference object : GPBPRXY_PIN_EXP_DATE"
                format: date-time
                x-lineageReferenceObject: GPBPRXY_PIN_EXP_DATE
              gprxrefProxyDesc:
                title: Proxy Desc
                maxLength: 120
                type: string
                description: "Lineage reference object : GPRXREF_PROXY_DESC"
                x-lineageReferenceObject: GPRXREF_PROXY_DESC
              fullname:
                title: Name
                maxLength: 130
                type: string
                description: "Lineage reference object : FULLNAME"
                x-lineageReferenceObject: FULLNAME
              gprxrefStartDate:
                title: "Start Date:"
                maxLength: 11
                type: string
                description: "Lineage reference object : GPRXREF_START_DATE"
                format: date-time
                x-lineageReferenceObject: GPRXREF_START_DATE
              gpbprxyEmailAddress:
                title: Email
                maxLength: 128
                type: string
                description: "Lineage reference object : GPBPRXY_EMAIL_ADDRESS"
                x-lineageReferenceObject: GPBPRXY_EMAIL_ADDRESS
            x-lineageReferenceObject: proxy
        gprhist:
          type: array
          items:
            type: object
            properties:
              activityDate:
                title: Date
                maxLength: 11
                type: string
                description: "Lineage reference object : GPRHIST_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: GPRHIST_ACTIVITY_DATE
              action:
                title: Action
                maxLength: 30
                type: string
              pageName:
                title: Page Name
                maxLength: 120
                type: string
                description: "Lineage reference object : GPRHIST_PAGE_NAME"
                x-lineageReferenceObject: GPRHIST_PAGE_NAME
            x-lineageReferenceObject: gprhist
    proxy-access-management-access-list-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
