openapi: 3.0.0
info:
  title: section-registration-information
  description: |
    Retrieves the list of section registration information.
  version: 1.0.0-beta
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: beta
  x-source-domain: Student
  x-source-title: Section Registration Information
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: section-registration-information
paths:
  /api/section-registration-information:
    get:
      description: >
        __Paging__ Pagination is supported using parameters limit and offset.
        Default value for limit is 500 and upper limit is 1000.

          __Sorting__ NA

        __Filtering__ Filtering is supported using url parameters
        [‘registrantId’, ‘startDateRange’, ‘endDateRange’].
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_SECTION_REG_INFORMATION
      tags:
        - section-registration-information
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version. See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/vnd.hedtech.integration.v1+json
            ```
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Registrant Id  

            Returns all section-registration-information for the registrant id
            passed.

            ```

            /section-registration-information?criteria={"registrantId":"9844ed40-2005-4167-a7f8-40648989eed8"}

            ```

            ### Start Date Range  

            Returns all section-registration-information for the start date
            range passed.

            ```

            /section-registration-information?criteria={"startDateRange":"2009-12-22"}

            ```

            ### End Date Range  

            Returns all section-registration-information for the end date range
            passed.

            ```

            /section-registration-information?criteria={"endDateRange":"2023-12-22"}

            ```
      responses:
        "200":
          description: Success
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: object
                $ref: "#/components/schemas/section-registration-information"
              examples:
                section-registration-information:
                  $ref: "#/components/examples/section-registration-information"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    section-registration-information:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
            description: The unique identifier for section registration information.
            x-lineageReferenceObject: SFRSTCR_SURROGATE_ID
          sectionRegistrationsId:
            type: string
            description: The global identifier of the section registration.
            x-lineageReferenceObject: SFRRGID_GUID
          registrantId:
            type: string
            description: The global identifier for the Registrant.
            x-lineageReferenceObject: GORGUID_GUID
          sectionId:
            type: string
            description: The global identifier for the Section.
            x-lineageReferenceObject: SSBSGID_GUID
          sectionReportingAcademicPeriodId:
            type: string
            description: The global identifier for the Reporting Academic Period associated
              with a section.
            x-lineageReferenceObject: GORGUID_GUID
          sectionReportingAcademicPeriodCode:
            type: string
            description: A code that identifies an reporting academic period.
            x-lineageReferenceObject: STVTERM_CODE
          sectionReportingAcademicPeriodTitle:
            type: string
            description: The full name of an reporting academic period (for example, 'Fall
              2014').
            x-lineageReferenceObject: STVTERM_DESC
          sectionReportingAcademicPeriodStartOn:
            type: string
            description: The date on which an reporting academic period begins.
            x-lineageReferenceObject: STVTERM_START_DATE
          sectionReportingAcademicPeriodEndOn:
            type: string
            description: The date on which an reporting academic period ends.
            x-lineageReferenceObject: STVTERM_END_DATE
          registrationStatus:
            type: string
            description: The status of the person's registration in the section. enums
              supported are registered and notRegistered.
            x-lineageReferenceObject: SFRSTCR_RSTS_CODE
          registrationCredit:
            type: number
            description: The credits that the student could potentially earn.
            x-lineageReferenceObject: SFRSTCR_CREDIT_HR
          studentTranscriptGradeId:
            type: string
            description: The global identifier for the Student Transcript Grade.
            x-lineageReferenceObject: SHRGDID_GUID
          studentTranscriptGradeCode:
            type: string
            description: A code that identifies the Student Transcript Grade.
            x-lineageReferenceObject: SHRTCKG_GRDE_CODE_FINAL
  examples:
    section-registration-information:
      value: >-
        [
          {
              "id": 1,
              "sectionRegistrationsId": "097168ac-96f8-4c4b-a91b-38dce1f1713d",
              "registrantId": "de3d5c28-af08-482e-9a77-de88f51e3244",
              "sectionId": "fcdf4931-172d-43a0-87c5-08a083f79503",
              "sectionReportingAcademicPeriodId": "87737a3e-643e-4844-938d-f233183bb369",
              "sectionReportingAcademicPeriodCode": "202310",
              "sectionReportingAcademicPeriodTitle": "Fall 2023",
              "sectionReportingAcademicPeriodStartOn": "2021-05-05T04:00:00Z",
              "sectionReportingAcademicPeriodEndOn": "2024-05-05T04:00:00Z",
              "registrationStatus": "registered",
              "registrationCredit": 10,
              "studentTranscriptGradeId": "41b14d6f-9cd8-45ff-a6ba-87db0a44647d",
              "studentTranscriptGradeCode": "A"
          }
        ]