openapi: 3.0.0
info:
  title: PayStub Web Rules
  description: API for PTRWSTB Administrative page configuration for displaying of pay stub.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: beta
  x-source-domain: Human Resources
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/paystub-web-rules:
    get:
      summary: Return data from the PTRWSTB page
      description: Display instruction for the Pay stub based on the configuration on
        admin page PTRWSTB.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PAYSTUB_WEB_RULES
      tags:
        - paystub-web-rules
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-paystub-web-rules.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-paystub-web-rules.json:
      title: Pay Stub Web Rules
      description: Deatils of Pay stubs rules from admin page PTRWSTB.
      type: object
      properties:
        code:
          title: Rule Code
          description: Web Pay Stub Rule Code. Default value is WEBPAYSTUB.
          type: string
        dataOrigin:
          title: Data Origin
          description: Source system that created or updated the data.
          type: string
        displayBannerId:
          title: Display ID Indicator
          description: Indicator that determines if the Banner ID will display on the pay
            stub on the web. Valid values are (Y)es or (N)o.  Default value is
            Y.
          type: boolean
        displayCheckDdInformation:
          title: Display Check and Direct Deposit Information Indicator
          description: Determines if the Check and Direct Deposit documents associated
            with the pay event will display. Valid values are (Y)es or (N)o.
            Default value is Y.
          type: boolean
        displayEarningsDeductionAmount:
          title: Display YTD Amounts
          description: Controls the display of YTD Earnings and Benefits/Deductions on the
            Web Pay Stub. YTD Employer Deduction Amounts will only display if
            the Display Employer Amounts is Y. Valid values are (Y)es or (N)o.
            Default value is N.
          type: boolean
        displayEmployeeAddress:
          title: Display Address Indicator
          description: Indicator that determines if the Employee Address will display on
            the pay stub on the web.  Valid values are (Y)es or (N)o.  Default
            value is Y.
          type: boolean
        displayEmployeeName:
          title: Display Name Indicator
          description: Indicator that determines if the Employee Name, from PPAIDEN, will
            display on the pay stub on the web.  Valid values are (Y)es or
            (N)o.  Default value is Y.
          type: boolean
        displayEmployerAddress:
          title: Display Employer Address Indicator
          description: Indicator that determines if Employer Address will display on the
            pay stub on the web. Valid values are (Y)es or (N)o.  Default value
            is Y.
          type: boolean
        displayEmployerDeductionAmount:
          title: Display Employer Amount Indicator
          description: Indicator that determines if the employer deduction amounts
            (contributions) will be displayed for all benefits/deductions on the
            pay stub on the web.  Valid values are (Y)es or (N)o.  Default value
            is Y.
          type: boolean
        displayEmployerName:
          title: Display Employer Name Indicator
          description: Indicator that determines if Employer Name will display on the pay
            stub on the web. Valid values are (Y)es or (N)o.  Default value is
            Y.
          type: boolean
        displayEmployerPhone:
          title: Display Employer Phone Indicator
          description: Indicator that determines if Employer Phone will display on the pay
            stub on the web. Valid values are (Y)es or (N)o.  Default value is
            Y.
          type: boolean
        displayFederalLocalWithHoldings:
          title: Display Federal, State and Local Withholding Indicator
          description: Determine if the employee's withholding selections for Federal and
            State taxes will be displayed. Valid values are (Y)es or (N)o.
            Default value is N.
          type: boolean
        displayJobTitle:
          title: Display Job Title Indicator
          description: Indicator that determines if the Job Title associated with the
            employee's earnings will display on the pay stub on the web.  Valid
            values are (Y)es or (N)o.  Default value is Y.
          type: boolean
        displayPayIdPayNumber:
          title: Display Pay ID and Number Indicator
          description: Indicator that determines if the Pay ID and Pay Number will display
            on the pay stub on the web.  Valid values are (Y)es or
            (N)o.  Default value is N.
          type: boolean
        displayPayPeriodRange:
          title: Display Pay start and end dates indicator
          description: Indicator that determines if the Pay Period Start and End Date will
            display on the pay stub on the web.  Valid values are (Y)es or
            (N)o.  Default value is Y.
          type: boolean
        displayPayStub:
          title: Display Pay Stubs
          description: Controls the display of web-based pay stubs.  Administrators would
            have the ability to either allow or not allow the employee to view
            the pay stub before the pay date. Valid values are I or P.
          type: string
        displayPositionSuffixCodes:
          title: Display Position and Suffix Indicator
          description: Indicator that determines if the Employee Position-Suffix
            associated with the employee's earnings will display on the pay stub
            on the web.  Valid values are (Y)es or (N)o.  Default value is N.
          type: boolean
        displaySsn:
          title: Display SSN/SIN/TIN Indicator
          description: Indicator that determines if the SIN/SIN/TIN will display on the
            pay stub on the web. Valid values are (Y)es or (N)o.  Default value
            is Y.
          type: boolean
        displayTotalEmployerContributions:
          title: Display Employer Total Summary Indicator
          description: Indicator that determines if Employer Total Contribution amount
            will display in the Payment Summary section on the pay stub on the
            web. Valid values are (Y)es or (N)o.  Default value is Y.
          type: boolean
        id:
          title: ID
          description: Immutable Unique Key.
          type: string
        labelForId:
          title: ID Label
          description: The value of the field label for the ID on the pay stub on the web.
            This only prints if DISPLAY ID INDICATOR field is also Y.
          type: string
        labelForSsn:
          title: SSN/SIN/TIN Label
          description: The value of the field label for the SSN/SIN/TIN on the pay stub on
            the web. This only prints if DISPLAY SSN/SIN/TIN INDICATOR field is
            also Y.
          type: string
        lastModified:
          title: Activity Date
          description: The date that information in this record was entered or last updated.
          type: string
        lastModifiedBy:
          title: User ID
          description: The user ID of the person who inserted or last updated this record.
          type: string
        payStubEmployer:
          title: Display Employer Address and logo location
          description: The location on the web pay stub where the Employer Address and
            logo will display.  Valid values are URIGHT=Upper Right, ULEFT=Upper
            Left, LRIGHT=Lower Right, and LLEFT=Lower Left. Default value is
            ULEFT
          type: string
        version:
          title: Version
          description: The optimistic lock token for this record.
          type: string
      additionalProperties: false
