openapi: 3.0.0
info:
  title: batch-check-print
  description: API for FAABATC administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FAABATC
  x-source-domain: Finance
  x-source-title: Batch Check Print
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/batch-check-print:
    get:
      tags:
        - batch-check-print
      summary: Return resources from FAABATC
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: bankCode
          in: query
          required: false
          schema:
            type: string
        - name: radioGroupPaymentmode
          in: query
          required: false
          schema:
            type: string
        - name: runDate
          in: query
          description: Check Date
          required: false
          schema:
            type: string
        - name: lastChkNoAn
          in: query
          description: Last GOOD Check Number
          required: false
          schema:
            type: string
        - name: startChkNoAn
          in: query
          description: STARTING Check Number
          required: false
          schema:
            type: string
        - name: restartChkNoAn
          in: query
          description: RESTART Check Number
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/batch-check-print-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/batch-check-print:
    post:
      tags:
        - batch-check-print QAPI (Query by POST)
      summary: Return resources from FAABATC
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/batch-check-print-1.0.0_get_request"
            example:
              bankCode: A1
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/batch-check-print-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    batch-check-print-1.0.0_get_response:
      required:
        - runDate
      type: object
      properties:
        runDate:
          title: Check Date
          maxLength: 11
          type: string
          format: date-time
        startChkNoAn:
          title: STARTING Check Number
          maxLength: 8
          type: string
        lastChkNoAn:
          title: Last GOOD Check Number
          maxLength: 8
          type: string
        restartChkNoAn:
          title: RESTART Check Number
          maxLength: 8
          type: string
      x-lineageReferenceObject: parm_entry
    batch-check-print-1.0.0_get_request:
      required:
        - bankCode
        - runDate
      type: object
      properties:
        bankCode:
          title: Bank
          maxLength: 30
          type: string
          description: "Lineage reference object : faabatcBankCode, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: faabatcBankCode
          x-lineageLookupReferenceObject: gxvbank
        runDate:
          title: Check Date
          maxLength: 11
          type: string
          format: date-time
        startChkNoAn:
          title: STARTING Check Number
          maxLength: 8
          type: string
        radioGroupPaymentmode:
          maxLength: 30
          type: string
          description: "Lineage reference object : radioGroupPaymentmode"
          x-lineageReferenceObject: radioGroupPaymentmode
        lastChkNoAn:
          title: Last GOOD Check Number
          maxLength: 8
          type: string
        restartChkNoAn:
          title: RESTART Check Number
          maxLength: 8
          type: string
      x-lineageReferenceObject: PARM_ENTRY
    batch-check-print-1.0.0_qapi_post:
      type: object
      properties:
        bankCode:
          type: string
        radioGroupPaymentmode:
          type: string
        runDate:
          title: Check Date
          maxLength: 11
          type: string
          format: date-time
        lastChkNoAn:
          title: Last GOOD Check Number
          maxLength: 8
          type: string
        startChkNoAn:
          title: STARTING Check Number
          maxLength: 8
          type: string
        restartChkNoAn:
          title: RESTART Check Number
          maxLength: 8
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
