openapi: 3.0.0
info:
  title: stores-inventory-codes
  description: API for FTVINVM administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: FTVINVM
  x-source-domain: Finance
  x-source-title: Stores Inventory Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/stores-inventory-codes:
    get:
      tags:
        - stores-inventory-codes
      summary: Return resources from FTVINVM
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: displayFtvcommDesc
          in: query
          description: Description
          required: false
          schema:
            type: string
        - name: commCode
          in: query
          description: |-
            Commodity  
            Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVINVM_COMM_CODE
        - name: effDate
          in: query
          description: |-
            Effective  
            Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVINVM_EFF_DATE
        - name: termDate
          in: query
          description: |-
            Termination
            Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVINVM_TERM_DATE
        - name: uomsCodeIssd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVINVM_UOMS_CODE_ISSD
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/stores-inventory-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/stores-inventory-codes:
    post:
      tags:
        - stores-inventory-codes QAPI (Query by POST)
      summary: Return resources from FTVINVM
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/stores-inventory-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/stores-inventory-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    stores-inventory-codes-1.0.0_qapi_post:
      type: object
      properties:
        displayFtvcommDesc:
          title: Description
          maxLength: 50
          type: string
        commCode:
          title: |-
            Commodity  
            Code
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVINVM_COMM_CODE"
          x-lineageReferenceObject: FTVINVM_COMM_CODE
        effDate:
          title: |-
            Effective  
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVINVM_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVINVM_EFF_DATE
        termDate:
          title: |-
            Termination
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVINVM_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVINVM_TERM_DATE
        uomsCodeIssd:
          maxLength: 3
          type: string
          description: "Lineage reference object : FTVINVM_UOMS_CODE_ISSD"
          x-lineageReferenceObject: FTVINVM_UOMS_CODE_ISSD
    stores-inventory-codes-1.0.0_get_response:
      type: object
      properties:
        commCode:
          title: |-
            Commodity  
            Code
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVINVM_COMM_CODE"
          x-lineageReferenceObject: FTVINVM_COMM_CODE
        effDate:
          title: |-
            Effective  
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVINVM_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVINVM_EFF_DATE
        displayFtvcommDesc:
          title: Description
          maxLength: 50
          type: string
        termDate:
          title: |-
            Termination
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVINVM_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVINVM_TERM_DATE
        uomsCodeIssd:
          maxLength: 3
          type: string
          description: "Lineage reference object : FTVINVM_UOMS_CODE_ISSD"
          x-lineageReferenceObject: FTVINVM_UOMS_CODE_ISSD
      x-lineageReferenceObject: ftvinvm
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    stores-inventory-codes-1.0.0_get_request:
      type: object
      properties:
        commCode:
          title: |-
            Commodity  
            Code
          maxLength: 10
          type: string
          description: "Lineage reference object : FTVINVM_COMM_CODE"
          x-lineageReferenceObject: FTVINVM_COMM_CODE
        effDate:
          title: |-
            Effective  
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVINVM_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: FTVINVM_EFF_DATE
        displayFtvcommDesc:
          title: Description
          maxLength: 50
          type: string
        termDate:
          title: |-
            Termination
            Date
          maxLength: 11
          type: string
          description: "Lineage reference object : FTVINVM_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: FTVINVM_TERM_DATE
        uomsCodeIssd:
          maxLength: 3
          type: string
          description: "Lineage reference object : FTVINVM_UOMS_CODE_ISSD"
          x-lineageReferenceObject: FTVINVM_UOMS_CODE_ISSD
      x-lineageReferenceObject: FTVINVM
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
