openapi: 3.0.0
info:
  title: ethnic-codes
  description: API for STVETHN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: STVETHN
  x-source-domain: Student
  x-source-title: Ethnic Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ethnic-codes:
    get:
      tags:
        - ethnic-codes
      summary: Return resources from STVETHN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_ACTIVITY_DATE
        - name: code
          in: query
          description: Ethnic Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_CODE
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_DESC
        - name: ediEquiv
          in: query
          description: EDI Equivalent
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_EDI_EQUIV
        - name: etctCode
          in: query
          description: IPEDS Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_ETCT_CODE
        - name: ethnCde
          in: query
          description: New Ethnicity
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_ETHN_CDE
        - name: lmsEquiv
          in: query
          description: LMS Equivalent
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_LMS_EQUIV
        - name: raceCde
          in: query
          description: Institution Race Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVETHN_RACE_CDE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ethnic-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ethnic-codes:
    post:
      tags:
        - ethnic-codes QAPI (Query by POST)
      summary: Return resources from STVETHN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ethnic-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ethnic-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ethnic-codes-1.0.0_get_request:
      required:
        - code
        - desc
      type: object
      properties:
        lmsEquiv:
          title: LMS Equivalent
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_LMS_EQUIV"
          x-lineageReferenceObject: STVETHN_LMS_EQUIV
        etctCode:
          title: IPEDS Code
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_ETCT_CODE, Lookup lineage
            reference object : stvetct"
          x-lineageReferenceObject: STVETHN_ETCT_CODE
          x-lineageLookupReferenceObject: stvetct
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVETHN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVETHN_ACTIVITY_DATE
        code:
          title: Ethnic Code
          maxLength: 2
          type: string
          description: "Lineage reference object : STVETHN_CODE"
          x-lineageReferenceObject: STVETHN_CODE
        ediEquiv:
          title: EDI Equivalent
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_EDI_EQUIV"
          x-lineageReferenceObject: STVETHN_EDI_EQUIV
        ethnCde:
          title: New Ethnicity
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_ETHN_CDE"
          x-lineageReferenceObject: STVETHN_ETHN_CDE
        raceCde:
          title: Institution Race Code
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_RACE_CDE, Lookup lineage
            reference object : gorrace"
          x-lineageReferenceObject: STVETHN_RACE_CDE
          x-lineageLookupReferenceObject: gorrace
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_DESC"
          x-lineageReferenceObject: STVETHN_DESC
      x-lineageReferenceObject: STVETHN
    ethnic-codes-1.0.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        lmsEquiv:
          title: LMS Equivalent
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_LMS_EQUIV"
          x-lineageReferenceObject: STVETHN_LMS_EQUIV
        etctCode:
          title: IPEDS Code
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_ETCT_CODE, Lookup lineage
            reference object : stvetct"
          x-lineageReferenceObject: STVETHN_ETCT_CODE
          x-lineageLookupReferenceObject: stvetct
        raceDesc:
          title: Institution Race Description
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVETHN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVETHN_ACTIVITY_DATE
        code:
          title: Ethnic Code
          maxLength: 2
          type: string
          description: "Lineage reference object : STVETHN_CODE"
          x-lineageReferenceObject: STVETHN_CODE
        ediEquiv:
          title: EDI Equivalent
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_EDI_EQUIV"
          x-lineageReferenceObject: STVETHN_EDI_EQUIV
        ethnCde:
          title: New Ethnicity
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_ETHN_CDE"
          x-lineageReferenceObject: STVETHN_ETHN_CDE
        raceCde:
          title: Institution Race Code
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_RACE_CDE, Lookup lineage
            reference object : gorrace"
          x-lineageReferenceObject: STVETHN_RACE_CDE
          x-lineageLookupReferenceObject: gorrace
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_DESC"
          x-lineageReferenceObject: STVETHN_DESC
      x-lineageReferenceObject: stvethn
    ethnic-codes-1.0.0_qapi_post:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVETHN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVETHN_ACTIVITY_DATE
        code:
          title: Ethnic Code
          maxLength: 2
          type: string
          description: "Lineage reference object : STVETHN_CODE"
          x-lineageReferenceObject: STVETHN_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_DESC"
          x-lineageReferenceObject: STVETHN_DESC
        ediEquiv:
          title: EDI Equivalent
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_EDI_EQUIV"
          x-lineageReferenceObject: STVETHN_EDI_EQUIV
        etctCode:
          title: IPEDS Code
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_ETCT_CODE, Lookup lineage
            reference object : stvetct"
          x-lineageReferenceObject: STVETHN_ETCT_CODE
          x-lineageLookupReferenceObject: stvetct
        ethnCde:
          title: New Ethnicity
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_ETHN_CDE"
          x-lineageReferenceObject: STVETHN_ETHN_CDE
        lmsEquiv:
          title: LMS Equivalent
          maxLength: 1
          type: string
          description: "Lineage reference object : STVETHN_LMS_EQUIV"
          x-lineageReferenceObject: STVETHN_LMS_EQUIV
        raceCde:
          title: Institution Race Code
          maxLength: 30
          type: string
          description: "Lineage reference object : STVETHN_RACE_CDE, Lookup lineage
            reference object : gorrace"
          x-lineageReferenceObject: STVETHN_RACE_CDE
          x-lineageLookupReferenceObject: gorrace
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
