openapi: 3.0.0
info:
  title: Student Cohorts
  description: |
    The list of valid student cohorts.
  version: 7.2.0
  x-source-system: banner
  x-api-type: ethos
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-cohorts:
    get:
      summary: Returns resources from STVCHRT
      description: >
        Returns a paged list of all the institutionally defined cohort codes
        from STVCHRT table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENT_COHORTS
      tags:
        - student-cohorts
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Code  

            Returns the matching student cohort record for the code sent in the request

            ```

            /student-cohorts?criteria={"code":"AUST"}

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-student-cohorts.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.2.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/student-cohorts/{id}:
    get:
      summary: Return the requested resource from STVCHRT
      description: |
        Returns a single cohort code from STVCHRT with the requested identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENT_COHORTS
      tags:
        - student-cohorts
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v7+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v7.2.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v7.2.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-student-cohorts.json"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-student-cohorts.json:
      title: Student Cohorts
      description: The list of valid student cohorts.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the student cohort.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: STVCHRT_GUID(STVCHRT)
        title:
          title: Title
          description: The full name of the student cohort.
          type: string
          minLength: 1
          x-lineageReferenceObject: STVCHRT_DESC(STVCHRT)
        description:
          title: Description
          description: The description of the student cohort.
          type: string
          x-lineageReferenceObject: unsupported
        code:
          title: Code
          description: The code that identifies the student cohort.
          type: string
          x-lineageReferenceObject: STVCHRT_CODE(STVCHRT)
        startOn:
          title: Start On
          description: The first date when when students may be assigned to the cohort.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: Display STVTERM_START_DATE where STVTERM_CODE = STVCHRT_TERM_CODE_START
            - type: string
              maxLength: 0
        endOn:
          title: End On
          description: The last date when when students may be assigned to the cohort.
          oneOf:
            - type: string
              format: date
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: Display STVTERM_END_DATE where STVTERM_CODE = STVCHRT_TERM_CODE_END
            - type: string
              maxLength: 0
        initialAcademicPeriod:
          title: Initial Academic Period
          description: The first academic period when students may be assigned to the
            cohort.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Initial Academic Period.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-periods 
                  x-lineageReferenceObject: STVCHRT_TERM_CODE_START(STVCHRT)
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        finalAcademicPeriod:
          title: Final Academic Period
          description: The last academic period when students may be assigned to the cohort.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Final Academic Period.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-periods 
                  x-lineageReferenceObject: STVCHRT_TERM_CODE_END(STVCHRT)
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        type:
          title: Type
          description: The type of cohort (e.g. federal).
          oneOf:
            - type: string
              enum:
                - federal
              x-lineageReferenceObject: derived  
              x-lineageDerivedLogic: If STVCHRT_RIGHT_IND = 'Y', publish federal;else don't publish
            - type: string
              maxLength: 0
      required:
        - id
        - title
      additionalProperties: false
