openapi: 3.0.0
info:
  title: electronic-document-status-codes
  description: API for STVDSTS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: STVDSTS
  x-source-domain: Student
  x-source-title: Electronic Document Status Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/electronic-document-status-codes:
    get:
      tags:
        - electronic-document-status-codes
      summary: Return resources from STVDSTS
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: acrecUdeInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_ACREC_UDE_IND
        - name: archInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_ARCH_IND
        - name: code
          in: query
          description: Status Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_CODE
        - name: courseUdeInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_COURSE_UDE_IND
        - name: defPriority
          in: query
          description: Priority
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_DEF_PRIORITY
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_DESC
        - name: immunizationInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_IMMUNIZATION_IND
        - name: mainUdeInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_MAIN_UDE_IND
        - name: studentUdeInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_STUDENT_UDE_IND
        - name: taInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_TA_IND
        - name: testsInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVDSTS_TESTS_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/electronic-document-status-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/electronic-document-status-codes:
    post:
      tags:
        - electronic-document-status-codes QAPI (Query by POST)
      summary: Return resources from STVDSTS
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/electronic-document-status-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/electronic-document-status-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    electronic-document-status-codes-1.0.0_get_response:
      required:
        - code
        - defPriority
        - desc
      type: object
      properties:
        archInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_ARCH_IND"
          x-lineageReferenceObject: STVDSTS_ARCH_IND
        code:
          title: Status Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVDSTS_CODE"
          x-lineageReferenceObject: STVDSTS_CODE
        acrecUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_ACREC_UDE_IND"
          x-lineageReferenceObject: STVDSTS_ACREC_UDE_IND
        immunizationInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_IMMUNIZATION_IND"
          x-lineageReferenceObject: STVDSTS_IMMUNIZATION_IND
        studentUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_STUDENT_UDE_IND"
          x-lineageReferenceObject: STVDSTS_STUDENT_UDE_IND
        mainUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_MAIN_UDE_IND"
          x-lineageReferenceObject: STVDSTS_MAIN_UDE_IND
        courseUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_COURSE_UDE_IND"
          x-lineageReferenceObject: STVDSTS_COURSE_UDE_IND
        taInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_TA_IND"
          x-lineageReferenceObject: STVDSTS_TA_IND
        testsInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_TESTS_IND"
          x-lineageReferenceObject: STVDSTS_TESTS_IND
        defPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : STVDSTS_DEF_PRIORITY"
          x-lineageReferenceObject: STVDSTS_DEF_PRIORITY
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVDSTS_DESC"
          x-lineageReferenceObject: STVDSTS_DESC
      x-lineageReferenceObject: stvdsts
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    electronic-document-status-codes-1.0.0_qapi_post:
      type: object
      properties:
        acrecUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_ACREC_UDE_IND"
          x-lineageReferenceObject: STVDSTS_ACREC_UDE_IND
        archInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_ARCH_IND"
          x-lineageReferenceObject: STVDSTS_ARCH_IND
        code:
          title: Status Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVDSTS_CODE"
          x-lineageReferenceObject: STVDSTS_CODE
        courseUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_COURSE_UDE_IND"
          x-lineageReferenceObject: STVDSTS_COURSE_UDE_IND
        defPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : STVDSTS_DEF_PRIORITY"
          x-lineageReferenceObject: STVDSTS_DEF_PRIORITY
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVDSTS_DESC"
          x-lineageReferenceObject: STVDSTS_DESC
        immunizationInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_IMMUNIZATION_IND"
          x-lineageReferenceObject: STVDSTS_IMMUNIZATION_IND
        mainUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_MAIN_UDE_IND"
          x-lineageReferenceObject: STVDSTS_MAIN_UDE_IND
        studentUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_STUDENT_UDE_IND"
          x-lineageReferenceObject: STVDSTS_STUDENT_UDE_IND
        taInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_TA_IND"
          x-lineageReferenceObject: STVDSTS_TA_IND
        testsInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_TESTS_IND"
          x-lineageReferenceObject: STVDSTS_TESTS_IND
    electronic-document-status-codes-1.0.0_get_request:
      required:
        - code
        - defPriority
        - desc
      type: object
      properties:
        archInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_ARCH_IND"
          x-lineageReferenceObject: STVDSTS_ARCH_IND
        code:
          title: Status Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVDSTS_CODE"
          x-lineageReferenceObject: STVDSTS_CODE
        acrecUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_ACREC_UDE_IND"
          x-lineageReferenceObject: STVDSTS_ACREC_UDE_IND
        immunizationInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_IMMUNIZATION_IND"
          x-lineageReferenceObject: STVDSTS_IMMUNIZATION_IND
        studentUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_STUDENT_UDE_IND"
          x-lineageReferenceObject: STVDSTS_STUDENT_UDE_IND
        mainUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_MAIN_UDE_IND"
          x-lineageReferenceObject: STVDSTS_MAIN_UDE_IND
        courseUdeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_COURSE_UDE_IND"
          x-lineageReferenceObject: STVDSTS_COURSE_UDE_IND
        taInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_TA_IND"
          x-lineageReferenceObject: STVDSTS_TA_IND
        testsInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVDSTS_TESTS_IND"
          x-lineageReferenceObject: STVDSTS_TESTS_IND
        defPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : STVDSTS_DEF_PRIORITY"
          x-lineageReferenceObject: STVDSTS_DEF_PRIORITY
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVDSTS_DESC"
          x-lineageReferenceObject: STVDSTS_DESC
      x-lineageReferenceObject: STVDSTS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
