openapi: 3.0.0
info:
  title: general-information-drivers-license
  description: API for PPAGENL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: PPAGENL
  x-source-domain: Human Resources
  x-source-title: General Information
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/general-information-drivers-license:
    get:
      tags:
        - general-information-drivers-license
      summary: Return resources from PPAGENL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: sbgiCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-information-drivers-license-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/general-information-drivers-license:
    post:
      tags:
        - general-information-drivers-license QAPI (Query by POST)
      summary: Return resources from PPAGENL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/general-information-drivers-license-1.0.0_get_reque\
                st"
            example:
              id: A00010003
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/general-information-drivers-license-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    general-information-drivers-license-1.0.0_get_response:
      required:
        - driverLicense
        - issueDate
        - status
      type: object
      properties:
        nationDesc:
          type: string
        activityDate:
          title: Pprdlic Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PPRDLIC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PPRDLIC_ACTIVITY_DATE
        natnCodeDriver:
          title: Nation
          maxLength: 30
          type: string
          description: "Lineage reference object : PPRDLIC_NATN_CODE_DRIVER, Lookup
            lineage reference object : stvnatn"
          x-lineageReferenceObject: PPRDLIC_NATN_CODE_DRIVER
          x-lineageLookupReferenceObject: stvnatn
        stateDesc:
          title: Description
          type: string
        skilCode:
          title: Type
          maxLength: 30
          type: string
          description: "Lineage reference object : PPRDLIC_SKIL_CODE, Lookup lineage
            reference object : ptrskil"
          x-lineageReferenceObject: PPRDLIC_SKIL_CODE
          x-lineageLookupReferenceObject: ptrskil
        driverLicense:
          title: License Number
          maxLength: 20
          type: string
          description: "Lineage reference object : PPRDLIC_DRIVER_LICENSE"
          x-lineageReferenceObject: PPRDLIC_DRIVER_LICENSE
        expireDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PPRDLIC_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: PPRDLIC_EXPIRE_DATE
        ptrskilDesc:
          type: string
        statCodeDriver:
          title: State or Province
          maxLength: 30
          type: string
          description: "Lineage reference object : PPRDLIC_STAT_CODE_DRIVER, Lookup
            lineage reference object : stvstat"
          x-lineageReferenceObject: PPRDLIC_STAT_CODE_DRIVER
          x-lineageLookupReferenceObject: stvstat
        issueDate:
          title: Issue Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PPRDLIC_ISSUE_DATE"
          format: date-time
          x-lineageReferenceObject: PPRDLIC_ISSUE_DATE
        userId:
          title: Pprdlic User Id
          maxLength: 30
          type: string
          description: "Lineage reference object : PPRDLIC_USER_ID"
          x-lineageReferenceObject: PPRDLIC_USER_ID
        status:
          title: License Status
          maxLength: 1
          type: string
          description: "Lineage reference object : PPRDLIC_STATUS"
          x-lineageReferenceObject: PPRDLIC_STATUS
      x-lineageReferenceObject: pprdlic
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    general-information-drivers-license-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        sbgiCode:
          type: string
    general-information-drivers-license-1.0.0_get_request:
      required:
        - sbgiCode
      type: object
      properties:
        sbgiCode:
          title: Prior College
          maxLength: 20
          type: string
          description: "Lineage reference object : SORPCOL_SBGI_CODE, Lookup lineage
            reference object : stvsbgi"
          x-lineageReferenceObject: SORPCOL_SBGI_CODE
          x-lineageLookupReferenceObject: stvsbgi
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: SORPCOL
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
