openapi: 3.0.0
info:
  title: Races
  description: The categorization scheme based on human genetic markers such as
    blood groups, distinct culture, or other physical characteristics.
  version: "6.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/races:
    get:
      summary: Return all resources from GORRACE
      description: Returns a paged listing of all the races records from GORRACE.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_RACES
      tags:
        - races
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-races.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/races/{id}:
    get:
      summary: Return the requested resource from GORRACE
      description: Return the single race record with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_RACES
      tags:
        - races
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Races for use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-races.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-races.json:
      title: Races
      description: The categorization scheme based on human genetic markers such as
        blood groups, distinct culture, or other physical characteristics.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of a race to be used in all external
            references to a race.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GORGUID_GUID(LDM_NAME= races) 
          x-lineageDerivedLogic: A record in GORGUID with GORGUID_LDM_NAME as 'races' will refer to each GORRACE_RACE_CDE in GORRACE
        title:
          title: Title
          description: The full name of a racial category.
          type: string
          minLength: 1
          x-lineageReferenceObject: GORRACE_DESC(GORRACE)
        code:
          title: Code
          description: Human-readable code that identifies a racial category.
          type: string
          x-lineageReferenceObject: GORRACE_RACE_CDE(GORRACE)
        description:
          title: Description
          description: The description of a racial category.
          type: string
          x-lineageReferenceObject: unsupported
        reporting:
          title: Reporting
          description: Properties required for governmental or other reporting.
          type: array
          items:
            type: object
            properties:
              country:
                title: Country
                description: The country with specific reporting requirements.
                oneOf:
                  - title: USA
                    description: Reporting requirements for the United States of America
                    type: object
                    properties:
                      code:
                        title: Code
                        description: The country code for the United States of America.
                        enum:
                          - USA
                        type: string
                        x-lineageReferenceObject: derived  
                        x-lineageDerivedLogic: The country code for the United States of America
                      racialCategory:
                        title: Racial Category
                        description: The IPEDS racial category to which the race belongs.
                        enum:
                          - americanIndianOrAlaskaNative
                          - asian
                          - blackOrAfricanAmerican
                          - hawaiianOrPacificIslander
                          - white
                        type: string
                        x-lineageReferenceObject: GORICCR_TRANSLATION_VALUE(GORICCR)
                    additionalProperties: false
                    required:
                      - code
                      - racialCategory
            additionalProperties: false
      required:
        - id
        - title
      additionalProperties: false

