openapi: 3.0.0
info:
  title: student-billing-mass-data-entry-memos
  description: API for TSAMASS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TSAMASS
  x-source-domain: Student
  x-source-title: Billing Mass Data Entry Form - Student
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-billing-mass-data-entry-memos:
    post:
      tags:
        - student-billing-mass-data-entry-memos
      summary: Creates a new resource in TSAMASS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-billing-mass-data-entry-memos-1.0.0_post_re\
                quest"
            example:
              amount: 100
              keybloc3DetailCode: 0
              keybloc3TermCode: 201520
              keybloc3BillingInd: Y
              id: 341819778
              keybloc3ExpDate: 2021-02-07
              detailCode: 0
              keybloc3Amount: 100
              desc: Pat test
              termCode: 201520
              expirationDate: 2021-02-07
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-billing-mass-data-entry-memos-1.0.0_post_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/student-billing-mass-data-entry-memos: {}
components:
  schemas:
    student-billing-mass-data-entry-memos-1.0.0_post_response:
      type: object
      properties:
        tbrmemo:
          type: array
          items:
            required:
              - amount
              - billingInd
              - desc
              - detailCode
            type: object
            properties:
              amount:
                title: Amount
                maxLength: 9
                type: number
                description: "Lineage reference object : TBRMEMO_AMOUNT"
                x-lineageReferenceObject: TBRMEMO_AMOUNT
              name:
                title: Name
                maxLength: 230
                type: string
              id:
                title: ID
                maxLength: 9
                type: string
              billingInd:
                title: Bill
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRMEMO_BILLING_IND"
                x-lineageReferenceObject: TBRMEMO_BILLING_IND
              detailCode:
                title: Detail Code
                maxLength: 4
                type: string
                description: "Lineage reference object : TBRMEMO_DETAIL_CODE, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: TBRMEMO_DETAIL_CODE
                x-lineageLookupReferenceObject: tbbdetc
              desc:
                title: Description
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRMEMO_DESC"
                x-lineageReferenceObject: TBRMEMO_DESC
              expirationDate:
                title: Expiration Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRMEMO_EXPIRATION_DATE"
                format: date-time
                x-lineageReferenceObject: TBRMEMO_EXPIRATION_DATE
              termCode:
                title: Term
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRMEMO_TERM_CODE, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: TBRMEMO_TERM_CODE
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: tbrmemo
        key_block3:
          type: array
          items:
            type: object
            properties:
              keybloc3DetailCode:
                title: Detail Code
                maxLength: 30
                type: string
                description: "Lineage reference object : keybloc3DetailCode, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: keybloc3DetailCode
                x-lineageLookupReferenceObject: tbbdetc
              keybloc3TermCode:
                title: Term
                maxLength: 6
                type: string
                description: "Lineage reference object : keybloc3TermCode, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: keybloc3TermCode
                x-lineageLookupReferenceObject: stvterm
              keybloc3BillingInd:
                title: Bill Indicator
                maxLength: 1
                type: string
                description: "Lineage reference object : keybloc3BillingInd"
                x-lineageReferenceObject: keybloc3BillingInd
              keybloc3ExpDate:
                title: Expiration Date
                maxLength: 11
                type: string
                description: "Lineage reference object : keybloc3ExpDate"
                format: date-time
                x-lineageReferenceObject: keybloc3ExpDate
              keybloc3Amount:
                title: Amount
                maxLength: 9
                type: number
                description: "Lineage reference object : keybloc3Amount"
                x-lineageReferenceObject: keybloc3Amount
            x-lineageReferenceObject: key_block3
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    student-billing-mass-data-entry-memos-1.0.0_post_request:
      required:
        - detailCode
        - desc
        - amount
        - billingInd
      type: object
      properties:
        amount:
          title: Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRMEMO_AMOUNT"
          x-lineageReferenceObject: TBRMEMO_AMOUNT
        keybloc3DetailCode:
          title: Detail Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keybloc3DetailCode, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: keybloc3DetailCode
          x-lineageLookupReferenceObject: tbbdetc
        keybloc3TermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : keybloc3TermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keybloc3TermCode
          x-lineageLookupReferenceObject: stvterm
        keybloc3BillingInd:
          title: Bill Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : keybloc3BillingInd"
          x-lineageReferenceObject: keybloc3BillingInd
        id:
          title: ID
          maxLength: 9
          type: string
        keybloc3ExpDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : keybloc3ExpDate"
          format: date-time
          x-lineageReferenceObject: keybloc3ExpDate
        detailCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBRMEMO_DETAIL_CODE, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: TBRMEMO_DETAIL_CODE
          x-lineageLookupReferenceObject: tbbdetc
        billingInd:
          title: Bill
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRMEMO_BILLING_IND"
          x-lineageReferenceObject: TBRMEMO_BILLING_IND
        keybloc3Amount:
          title: Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : keybloc3Amount"
          x-lineageReferenceObject: keybloc3Amount
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_DESC"
          x-lineageReferenceObject: TBRMEMO_DESC
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBRMEMO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: TBRMEMO
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
