openapi: 3.0.0
info:
  title: ca-ccpg-income-by-household-size-rule
  description: API for RVAINCR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RVAINCR
  x-source-domain: Financial Aid
  x-source-title: CCPG Income by Household Size Rule (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-ccpg-income-by-household-size-rule:
    get:
      tags:
        - ca-ccpg-income-by-household-size-rule
      summary: Return resources from RVAINCR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: aidyCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_get_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - ca-ccpg-income-by-household-size-rule
      summary: Updates an existing resource in RVAINCR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_put_req\
                uest"
            example:
              hhSizeMaxIncome: 2500
              aidyCode: 2021
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_put_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - ca-ccpg-income-by-household-size-rule
      summary: Creates a new resource in RVAINCR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_post_re\
                quest"
            example:
              hhSizeMaxIncome: 2500
              aidyCode: 2021
              hhNumberDesc: Maximum income of 21
              hhNumber: 21
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_post_re\
                    sponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-ccpg-income-by-household-size-rule:
    post:
      tags:
        - ca-ccpg-income-by-household-size-rule QAPI (Query by POST)
      summary: Return resources from RVAINCR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_get_req\
                uest"
            example:
              aidyCode: 2021
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-ccpg-income-by-household-size-rule-1.0.0_get_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    ca-ccpg-income-by-household-size-rule-1.0.0_put_response:
      required:
        - hhNumber
        - hhNumberDesc
        - hhSizeMaxIncome
      type: object
      properties:
        hhSizeMaxIncome:
          title: Maximum Income
          maxLength: 10
          type: number
          description: "Lineage reference object : RVRGINC_HH_SIZE_MAX_INCOME"
          x-lineageReferenceObject: RVRGINC_HH_SIZE_MAX_INCOME
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RVRGINC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RVRGINC_ACTIVITY_DATE
        hhNumberDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_HH_NUMBER_DESC"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER_DESC
        hhNumber:
          title: Number in Household
          maxLength: 2
          type: number
          description: "Lineage reference object : RVRGINC_HH_NUMBER"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_USER_ID"
          x-lineageReferenceObject: RVRGINC_USER_ID
      x-lineageReferenceObject: rvrginc
    ca-ccpg-income-by-household-size-rule-1.0.0_post_request:
      required:
        - hhNumber
        - hhNumberDesc
        - hhSizeMaxIncome
      type: object
      properties:
        hhSizeMaxIncome:
          title: Maximum Income
          maxLength: 10
          type: number
          description: "Lineage reference object : RVRGINC_HH_SIZE_MAX_INCOME"
          x-lineageReferenceObject: RVRGINC_HH_SIZE_MAX_INCOME
        aidyCode:
          title: Aid Year
          maxLength: 4
          type: string
          description: "Lineage reference object : aidyCode, Lookup lineage reference
            object : robinst,rvbbogw"
          x-lineageReferenceObject: aidyCode
          x-lineageLookupReferenceObject: robinst,rvbbogw
        hhNumberDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_HH_NUMBER_DESC"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER_DESC
        hhNumber:
          title: Number in Household
          maxLength: 2
          type: number
          description: "Lineage reference object : RVRGINC_HH_NUMBER"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER
      x-lineageReferenceObject: RVRGINC
    ca-ccpg-income-by-household-size-rule-1.0.0_put_request:
      required:
        - criteria.rvrgincHhNumber
        - criteria.rvrgincHhNumberDesc
        - criteria.rvrgincHhSizeMaxIncome
        - hhNumberDesc
        - hhSizeMaxIncome
      type: object
      properties:
        hhSizeMaxIncome:
          title: Maximum Income
          maxLength: 10
          type: number
          description: "Lineage reference object : RVRGINC_HH_SIZE_MAX_INCOME"
          x-lineageReferenceObject: RVRGINC_HH_SIZE_MAX_INCOME
        aidyCode:
          title: Aid Year
          maxLength: 4
          type: string
          description: "Lineage reference object : aidyCode, Lookup lineage reference
            object : robinst,rvbbogw"
          x-lineageReferenceObject: aidyCode
          x-lineageLookupReferenceObject: robinst,rvbbogw
        criteria.rvrgincHhNumber:
          title: Number in Household
          maxLength: 2
          type: number
          description: "Lineage reference object : RVRGINC_HH_NUMBER"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER
        criteria.rvrgincHhSizeMaxIncome:
          title: Maximum Income
          maxLength: 10
          type: number
          description: "Lineage reference object : RVRGINC_HH_SIZE_MAX_INCOME"
          x-lineageReferenceObject: RVRGINC_HH_SIZE_MAX_INCOME
        hhNumberDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_HH_NUMBER_DESC"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER_DESC
        criteria.rvrgincUserId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_USER_ID"
          x-lineageReferenceObject: RVRGINC_USER_ID
        criteria.rvrgincActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RVRGINC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RVRGINC_ACTIVITY_DATE
        criteria.rvrgincHhNumberDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_HH_NUMBER_DESC"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER_DESC
      x-lineageReferenceObject: RVRGINC
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-ccpg-income-by-household-size-rule-1.0.0_get_request:
      type: object
      properties:
        aidyCode:
          title: Aid Year
          maxLength: 4
          type: string
          description: "Lineage reference object : aidyCode, Lookup lineage reference
            object : robinst,rvbbogw"
          x-lineageReferenceObject: aidyCode
          x-lineageLookupReferenceObject: robinst,rvbbogw
      x-lineageReferenceObject: KEY_BLOCK
    ca-ccpg-income-by-household-size-rule-1.0.0_post_response:
      required:
        - hhNumber
        - hhNumberDesc
        - hhSizeMaxIncome
      type: object
      properties:
        hhSizeMaxIncome:
          title: Maximum Income
          maxLength: 10
          type: number
          description: "Lineage reference object : RVRGINC_HH_SIZE_MAX_INCOME"
          x-lineageReferenceObject: RVRGINC_HH_SIZE_MAX_INCOME
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RVRGINC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RVRGINC_ACTIVITY_DATE
        hhNumberDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_HH_NUMBER_DESC"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER_DESC
        hhNumber:
          title: Number in Household
          maxLength: 2
          type: number
          description: "Lineage reference object : RVRGINC_HH_NUMBER"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_USER_ID"
          x-lineageReferenceObject: RVRGINC_USER_ID
      x-lineageReferenceObject: rvrginc
    ca-ccpg-income-by-household-size-rule-1.0.0_get_response:
      required:
        - hhNumber
        - hhNumberDesc
        - hhSizeMaxIncome
      type: object
      properties:
        hhSizeMaxIncome:
          title: Maximum Income
          maxLength: 10
          type: number
          description: "Lineage reference object : RVRGINC_HH_SIZE_MAX_INCOME"
          x-lineageReferenceObject: RVRGINC_HH_SIZE_MAX_INCOME
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RVRGINC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RVRGINC_ACTIVITY_DATE
        hhNumberDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_HH_NUMBER_DESC"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER_DESC
        hhNumber:
          title: Number in Household
          maxLength: 2
          type: number
          description: "Lineage reference object : RVRGINC_HH_NUMBER"
          x-lineageReferenceObject: RVRGINC_HH_NUMBER
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : RVRGINC_USER_ID"
          x-lineageReferenceObject: RVRGINC_USER_ID
      x-lineageReferenceObject: rvrginc
    ca-ccpg-income-by-household-size-rule-1.0.0_qapi_post:
      type: object
      properties:
        aidyCode:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
