openapi: 3.0.0
info:
  title: Security STP Identifiers
  description: >
    The Security STP Identifiers API provides the list of valid Banner Shared Technology Platform (formerly refered to as MEP) Identifiers.


    Note: To maintain strict access control, the required security object must be assigned directly to individual users. 
    Assignment via security classes is not supported for this API.
  version: 1.0.0
  x-api-type: erp
  x-release-status: ga
  x-source-system: banner
  x-audience: all
  x-source-domain: Foundation
  x-source-name: GSAVPDI
  x-source-title: null
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/security-stp-identifiers:
    get:
      tags:
      - security-stp-identifiers
      summary: Returns Security STP identifier details.
      description: Returns resources from GTVVPDI.
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          description:  |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object  
          description: >
            ### STP Identifier

            Returns all records for the STP Identifer passed.

            ```

            /stp-institutions?criteria={"stpIdentifer":"INST"}

            ```    

            ### System Default Indicator

            Returns all records for the System Default Indicator passed.

            ```

            /stp-institutions?criteria={"systemDefaultInd":"true"}

            ``` 
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/security-stp-identifiers-1.0.0_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client’s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_SECURITY_STP_IDENTIFIERS
  /api/security-stp-identifiers/{id}:
    get:
      summary: Returns the requested resource from GTVVPDI.
      description: |
        Returns a record from GTVVPDI with the passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SECURITY_STP_IDENTIFIERS
      tags:
        - security-stp-identifiers
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v16.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/security-stp-identifiers-1.0.0_response"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data      
components:
  schemas:
    security-stp-identifiers-1.0.0_response:
      type: object
      required:
        - id
        - securityClass 
        - owner    
      properties:
        id:
          title: STP Identifier ID
          description: "Unique identifier for the STP institution."
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GTVVPDI_GUID
          example: 49eqfc68-3t89-4036-852c-341aa9d8501a          
          maxLength: 36
        stpIdentifier:
          title: STP Identifier Code
          description: "The STP Identifier code."
          type: string
          x-lineageReferenceObject: GTVVPDI_CODE
          example: "INST"
          maxLength: 6   
        description:
          title: STP Identifier Description
          description: "Description of the STP Identifier code."
          type: string
          x-lineageReferenceObject: GTVVPDI_DESC
          example: 'Institution'
          maxLength: 30                
        systemDefaultInd:
          title: System Default Indicator
          description: "Indicates the default institution for the Banner system.  This field will be used to associate an institution to a user that has not been assigned one on GSAVPDI. Valid values are Y and N."
          type: boolean
          x-lineageReferenceObject: GTVVPDI_SYS_DEF_INST_IND
          example: "true"                                 
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
              type: object
              properties:
                id:
                  type: string
                  description: The global identifier of the resource in error.
                sourceId:
                  type: string
                  description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
                code:
                  type: string
                  description: The error message code used to describe the error details.
                description:
                  type: string
                  description: The error description used to describe the error details.
                message:
                  type: string
                  description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic