openapi: 3.0.0
info:
  title: term-control-projected-registration
  description: API for SOATERM administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SOATERM
  x-source-domain: Student
  x-source-title: Term Control
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/term-control-projected-registration:
    get:
      tags:
        - term-control-projected-registration
      summary: Return resources from SOATERM
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: xxxxxxxTermCode
          in: query
          required: false
          schema:
            type: string
        - name: copyBtn
          in: query
          required: false
          schema:
            type: string
        - name: crnOneup
          in: query
          required: false
          schema:
            type: string
        - name: ptrmCode
          in: query
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/term-control-projected-registration-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/term-control-projected-registration:
    post:
      tags:
        - term-control-projected-registration QAPI (Query by POST)
      summary: Return resources from SOATERM
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/term-control-projected-registration-1.0.0_get_reque\
                st"
            example:
              xxxxxxxTermCode: 201410
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/term-control-projected-registration-1.0.0_get_respo\
                    nse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    term-control-projected-registration-1.0.0_qapi_post:
      type: object
      properties:
        xxxxxxxTermCode:
          type: string
        copyBtn:
          type: string
        crnOneup:
          type: string
        ptrmCode:
          type: string
        startDate:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    term-control-projected-registration-1.0.0_get_request:
      required:
        - crnOneup
        - ptrmCode
        - startDate
      type: object
      properties:
        ptrmCode:
          title: Part of Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBPTRM_PTRM_CODE, Lookup lineage
            reference object : stvptrm"
          x-lineageReferenceObject: SOBPTRM_PTRM_CODE
          x-lineageLookupReferenceObject: stvptrm
        xxxxxxxTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : xxxxxxxTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: xxxxxxxTermCode
          x-lineageLookupReferenceObject: stvterm
        crnOneup:
          title: CRN Starting Sequence Number
          maxLength: 5
          type: number
          description: "Lineage reference object : SOBTERM_CRN_ONEUP"
          x-lineageReferenceObject: SOBTERM_CRN_ONEUP
        startDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORFTRM_START_DATE"
          format: date-time
          x-lineageReferenceObject: SORFTRM_START_DATE
      x-lineageReferenceObject: SORFTRM
    term-control-projected-registration-1.0.0_get_response:
      type: object
      properties:
        projElecRegCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_ELEC_REG_CDE"
          x-lineageReferenceObject: SOBPROJ_PROJ_ELEC_REG_CDE
        attrCode:
          title: Section Attribute for Elective Pool
          maxLength: 4
          type: string
          description: "Lineage reference object : SOBPROJ_ATTR_CODE, Lookup lineage
            reference object : stvattr"
          x-lineageReferenceObject: SOBPROJ_ATTR_CODE
          x-lineageLookupReferenceObject: stvattr
        failedMostprobInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_FAILED_MOSTPROB_IND"
          x-lineageReferenceObject: SOBPROJ_FAILED_MOSTPROB_IND
        projPassedCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_PASSED_CDE"
          x-lineageReferenceObject: SOBPROJ_PROJ_PASSED_CDE
        inclFailedInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_INCL_FAILED_IND"
          x-lineageReferenceObject: SOBPROJ_INCL_FAILED_IND
        projMandRegCde:
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_MAND_REG_CDE"
          x-lineageReferenceObject: SOBPROJ_PROJ_MAND_REG_CDE
        projWebInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_WEB_IND"
          x-lineageReferenceObject: SOBPROJ_PROJ_WEB_IND
        userId:
          type: string
          description: "Lineage reference object : SOBPROJ_USER_ID"
          x-lineageReferenceObject: SOBPROJ_USER_ID
        stvrestDesc:
          type: string
        projTransferredCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_TRANSFERRED_CDE"
          x-lineageReferenceObject: SOBPROJ_PROJ_TRANSFERRED_CDE
        activityDate:
          type: string
          description: "Lineage reference object : SOBPROJ_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SOBPROJ_ACTIVITY_DATE
        projInprogressCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_INPROGRESS_CDE"
          x-lineageReferenceObject: SOBPROJ_PROJ_INPROGRESS_CDE
        electiveRuleKey:
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBPROJ_ELECTIVE_RULE_KEY"
          x-lineageReferenceObject: SOBPROJ_ELECTIVE_RULE_KEY
        dataOrigin:
          type: string
          description: "Lineage reference object : SOBPROJ_DATA_ORIGIN"
          x-lineageReferenceObject: SOBPROJ_DATA_ORIGIN
        nullProjRestrictInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_NULL_PROJ_RESTRICT_IND"
          x-lineageReferenceObject: SOBPROJ_NULL_PROJ_RESTRICT_IND
        projRollToAhCde:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_ROLL_TO_AH_CDE"
          x-lineageReferenceObject: SOBPROJ_PROJ_ROLL_TO_AH_CDE
        restCode:
          title: External API
          maxLength: 4
          type: string
          description: "Lineage reference object : SOBPROJ_REST_CODE, Lookup lineage
            reference object : stvrest"
          x-lineageReferenceObject: SOBPROJ_REST_CODE
          x-lineageLookupReferenceObject: stvrest
        mandatoryRuleKey:
          maxLength: 30
          type: string
          description: "Lineage reference object : SOBPROJ_MANDATORY_RULE_KEY"
          x-lineageReferenceObject: SOBPROJ_MANDATORY_RULE_KEY
        projRestrictInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SOBPROJ_PROJ_RESTRICT_IND"
          x-lineageReferenceObject: SOBPROJ_PROJ_RESTRICT_IND
        stvattrDesc:
          type: string
        termCode:
          type: string
          description: "Lineage reference object : SOBPROJ_TERM_CODE"
          x-lineageReferenceObject: SOBPROJ_TERM_CODE
      x-lineageReferenceObject: sobproj
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
