openapi: 3.0.0
info:
  title: Security Object Details
  description: >
    The Security Object Details API provides information about Banner Security Objects as shown on the Objects tab on the GSASECR administrative page in Banner Access Management.


    Note: To maintain strict access control, the required security object must be assigned directly to individual users. 
    Assignment via security classes is not supported for this API.
  version: 1.0.0
  x-api-type: erp
  x-release-status: ga
  x-source-system: banner
  x-audience: all
  x-source-domain: Foundation
  x-source-name: GSASECR
  x-source-title: null
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/security-object-details:
    get:
      tags:
      - security-object-details
      summary: Returns security object details.
      description: Returns resources from GURAOBJ.
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          description:  |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object   
          description: >
            ### Security Object

            Returns all records for the Security Object passed.

            ```

            /security-object-details?criteria={"securityObject":"75TESTPROC"}

            ```

            ### Default Role

            Returns all security object records for the Default Role passed.

            ```

            /security-object-details?criteria={"defaultRole":"BAN_DEFAULT_M"}

            ```                

            ### System Type

            Returns all security object records for the System Type passed.

            ```

            /security-object-details?criteria={"systemType":"G"}

            ```          
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/security-object-details-1.0.0_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the clientâ€™s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_SECURITY_OBJECT_DETAILS
  /api/security-object-details/{id}:
    get:
      summary: Returns the requested resource from GURAOBJ.
      description: |
        Returns a record from GURAOBJ with the passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SECURITY_OBJECT_DETAILS
      tags:
        - security-object-details
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v16.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/security-object-details-1.0.0_response"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data        
components:
  schemas:
    security-object-details-1.0.0_response:
      type: object
      required:
        - id
        - securityObject
        - defaultRole  
        - systemType
      properties:
        id:
          title: Security Object ID
          description: "Unique identifier for the security object."
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GURAOBJ_GUID
          example: 49eqfc68-3t89-4036-852c-341aa9d8501a          
          maxLength: 36
        securityObject:
          title: Security Object Code
          description: "The name of the security object."
          type: string
          x-lineageReferenceObject: GURAOBJ_OBJECT
          example: "75TESTPROC"
          maxLength: 30   
        defaultRole:
          title: Default Role
          description: "The default role of the security object."
          type: string
          x-lineageReferenceObject: GURAOBJ_OBJECT
          example: "BAN_DEFAULT_M"
          maxLength: 30             
        systemType:
          title: System Type 
          description: "The system that a security object is associated with."
          type: string
          x-lineageReferenceObject: GURAOBJ_SYSI_CODE
          x-lineageLookupReferenceObject: gtvsysi  
          example: 'G'
          maxLength: 2                 
        owner:
          title: Owner
          description: "The owner of the security object."
          type: string
          x-lineageReferenceObject: GURAOBJ_OWNER
          example: "BANSECR"
          maxLength: 30
        comment:
          title: Comment
          description: "The comment related to the security object."
          type: string
          x-lineageReferenceObject: GURAOBJ_COMMENTS
          example: "Test class 1234"
          maxLength: 4000      
        accessTrackingInd:
          title: Access Tracking Indicator
          description: "Indicator to identify whether access to this form or job should occur if GUBIPRF_ACCESS_TRACKING=S. Valid values: N-Do not track; Y-Track access."
          type: string
          x-lineageReferenceObject: GURAOBJ_ACCESS_TRACKING_IND
          example: "Y"
          maxLength: 1                                
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
              type: object
              properties:
                id:
                  type: string
                  description: The global identifier of the resource in error.
                sourceId:
                  type: string
                  description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
                code:
                  type: string
                  description: The error message code used to describe the error details.
                description:
                  type: string
                  description: The error description used to describe the error details.
                message:
                  type: string
                  description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic