openapi: 3.0.0
info:
  title: Student Academic Periods
  description: Information about a student for a specified academic period. The
    API provides the information of students term enrollment details based on an
    academic period from Banner.
  version: 1.0.0
  x-source-system: banner
  x-api-type: ethos
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-academic-periods:
    get:
      summary: Returns all resources from SFBETRM
      description: Returns a paged listing of all the term enrollment information of
        all students from SFBETRM table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENT_ACADEMIC_PERIODS
      tags:
        - student-academic-periods
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Person  

            The person who is associated with the academic period.

            ```

            /student-academic-periods?criteria={"person": {"id": $id}}

            ```

            ### Academic Period  

            The academic period to which the student has been associated.

            ```

            /student-academic-periods?criteria={"academicPeriod": {"id": $id}}

            ```

            ### Academic Period Status  

            The student academic status for the period as established by the institution.

            ```

            /student-academic-periods?criteria={"academicStatuses": [{"academicPeriodStatus": {"id": $id}}]}

            ```
        - name: personFilter
          in: query
          required: false
          schema:
            type: object
          description: |
            ### Person Filter  
            Retrieve information for a specified population.
            ```
            /student-academic-periods?personFilter={"personFilter": {"id": $id}}
            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-student-academic-periods.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/student-academic-periods/{id}:
    get:
      summary: Returns the requested resource from SFBETRM
      description: Returns a student's term enrollment record from SFBETRM based on an
        academic period with the requested identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENT_ACADEMIC_PERIODS
      tags:
        - student-academic-periods
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Student Academic Periods for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-student-academic-periods.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-student-academic-periods.json:
      title: Student Academic Periods
      description: Information about a student for a specified academic period.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the student academic period.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: SFBETRM_STU_ACAD_PERD_GUID(SFBETRM)
        person:
          title: Person
          description: The person who is associated with the academic period.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Person.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: persons 
              x-lineageReferenceObject: SFBETRM_PIDM(SFBETRM)
          additionalProperties: false
          required:
            - id
        academicPeriod:
          title: Academic Period
          description: The academic period to which the student has been associated.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Academic Period.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: academic-periods 
              x-lineageReferenceObject: SFBETRM_TERM_CODE(SFBETRM)
          additionalProperties: false
          required:
            - id
        academicLevels:
          title: Academic Levels
          description: The distinct academic levels associated with the student for this
            period.
          type: array
          minItems: 1
          items:
            type: object
            properties:
              academicLevel:
                title: Academic Level
                description: The distinct academic level associated with the student for this
                  period.
                type: object
                properties:
                  id:
                    title: ID
                    description: The global identifier for the Academic Level.
                    type: string
                    format: guid
                    pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                    x-lineageLookupReferenceObject: academic-levels 
                    x-lineageReferenceObject: unsupported
                additionalProperties: false
                required:
                  - id
              priority:
                title: Priority
                description: An indicator as to whether the academic level is the primary for
                  the student.
                oneOf:
                  - type: string
                    enum:
                      - primary
                    x-lineageReferenceObject: derived  
                    x-lineageDerivedLogic: If the level code being published is the level code associated with the lowest priority number for all current and active curriculum records for the term code and student being processed then publish "primary" otherwise do not publish a value.
                  - type: string
                    maxLength: 0
            additionalProperties: false
            required:
              - academicLevel
        academicStatuses:
          title: Academic Statuses
          description: The student academic statuses for the period.
          type: array
          items:
            type: object
            properties:
              basis:
                title: Basis
                description: An indicator as to whether the academic status is established for
                  the student overall or specific to a student's academic level.
                enum:
                  - byLevel
                  - overall
                type: string
                x-lineageReferenceObject: derived  
                x-lineageDerivedLogic: Always overall is displayed.
              academicLevel:
                title: Academic Level
                description: The academic level associated with the academic period status.
                oneOf:
                  - type: object
                    properties:
                      id:
                        title: ID
                        description: The global identifier for the Academic Level.
                        type: string
                        format: guid
                        pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                        x-lineageLookupReferenceObject: academic-levels 
                        x-lineageReferenceObject: unsupported
                    additionalProperties: false
                    required:
                      - id
                  - type: object
                    maxProperties: 0
              academicPeriodStatus:
                title: Academic Period Status
                description: The student academic status for the period as established by the
                  institution.
                type: object
                properties:
                  id:
                    title: ID
                    description: The global identifier for the Academic Period Status.
                    type: string
                    format: guid
                    pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                    x-lineageLookupReferenceObject: student-academic-period-statuses 
                    x-lineageReferenceObject: SFBETRM_ESTS_CODE(SFBETRM)
                additionalProperties: false
                required:
                  - id
            additionalProperties: false
            required:
              - basis
              - academicPeriodStatus
        academicLoads:
          title: Academic Loads
          description: The student calculated academic loads for the period.
          type: array
          items:
            type: object
            properties:
              basis:
                title: Basis
                description: An indicator as to whether the academic load is established for the
                  student overall or specific to a student's academic level.
                enum:
                  - byLevel
                  - overall
                type: string
                x-lineageReferenceObject: derived  
                x-lineageDerivedLogic: Always overall is displayed
              academicLevel:
                title: Academic Level
                description: The academic level associated with the academic load.
                oneOf:
                  - type: object
                    properties:
                      id:
                        title: ID
                        description: The global identifier for the Academic Level.
                        type: string
                        format: guid
                        pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                        x-lineageLookupReferenceObject: academic-levels 
                        x-lineageReferenceObject: derived  
                        x-lineageDerivedLogic: A record in GORGUID with GORGUID_LDM_NAME as 'academic-levels' will refer to each distinct level of the active, current learner records in SORLCUR for the term being processed.
                    additionalProperties: false
                    required:
                      - id
                  - type: object
                    maxProperties: 0
              academicLoad:
                title: Academic Load
                description: The student calculated academic load for the period.
                enum:
                  - partTime
                  - overload
                  - fullTime
                type: string
                x-lineageReferenceObject: derived  
                x-lineageDerivedLogic: Displayed based on the SFBETRM_TMST_CODE mapped in API configuration setting STUDENT.ACADEMICLOAD.CODE.
            additionalProperties: false
            required:
              - basis
              - academicLoad
      required:
        - id
        - person
        - academicPeriod
        - academicLevels
      additionalProperties: false
