openapi: 3.0.0
info:
  title: proxy-student-memos
  description: This API is used to retrieve, update and insert student memo details to the TBRMEMO table. This API allows an API USER to post a transaction on behalf of a “user” who has a SPRIDEN ID and has Banner security access to post the transaction. The “user” field requires either the SPRIDEN ID or the Principal User ID from GOAEACC. The user is case sensitive and must match the record in Banner.
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: TBRMEMO
  x-source-domain: Student
  x-source-title: Student Account Detail
  x-source-system: banner
  x-api-type: erp
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/proxy-student-memos/{id}:  
    get:
      tags:
        - proxy-student-memos
      summary: Return resources from TBRMEMO
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/proxy-student-memos-1.0.0_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
      x-method-permissions: API_PROXY_STUDENT_MEMOS
    put:
      tags:
        - proxy-student-memos
      summary: Updates an existing resource in TBRMEMO

      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/proxy-student-memos-1.0.0_put_request"
            example:
              transNumber: 12
              documentNumber: 2
              desc: Refund Code - Manuals
              origChgInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/proxy-student-memos-1.0.0_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
      x-method-permissions: API_PROXY_STUDENT_MEMOS    
    delete:
      tags:
        - proxy-student-memos
      summary: Deletes an existing resource in TBRMEMO
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: tranNumber
          in: query
          required: true
          schema:
            type: number            
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
      x-method-permissions: API_PROXY_STUDENT_MEMOS        
  /api/proxy-student-memos:          
    post:
      tags:
        - proxy-student-memos
      summary: Creates a new resource in TBRMEMO
      parameters: []
      requestBody:
        required: false
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/proxy-student-memos-1.0.0_post_request"
            example:
              amount: "3"
              srceCode: T
              overrideHold: Y
              billingInd: Y
              expirationDate: "2021-05-20"
              id: A00022293
              detailCode: T101
              desc: "description"
              user: "user"
              termCode: "201010"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/proxy-student-memos-1.0.0_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
      x-method-permissions: API_PROXY_STUDENT_MEMOS    
components:
  schemas:
    proxy-student-memos-1.0.0_post_request:
      required:
        - id
        - detailCode
        - amount
        - termCode
        - srceCode
        - billingInd
        - user
      type: object
      properties:
        amount:
          title: Amount
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRMEMO_AMOUNT"
          x-lineageReferenceObject: TBRMEMO_AMOUNT
        srceCode:
          title: Source Code
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRMEMO_SRCE_CODE, Lookup lineage
            reference object : ttvsrce"
          x-lineageReferenceObject: TBRMEMO_SRCE_CODE
          x-lineageLookupReferenceObject: ttvsrce
        detailCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBRMEMO_DETAIL_CODE, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: TBRMEMO_DETAIL_CODE
          x-lineageLookupReferenceObject: tbbdetc
        overrideHold:
          title: Holds
          maxLength: 3
          type: string
          description: "Lineage reference object : overrideHold"
          x-lineageReferenceObject: overrideHold
        billingInd:
          title: Billing Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRMEMO_BILLING_IND"
          x-lineageReferenceObject: TBRMEMO_BILLING_IND
        expirationDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRMEMO_EXPIRATION_DATE"
          format: date
          x-lineageReferenceObject: TBRMEMO_EXPIRATION_DATE
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        desc:
          title: Detail Code Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_DESC"
          x-lineageReferenceObject: TBRMEMO_DESC
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBRMEMO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_USER"
          x-lineageReferenceObject: TBRMEMO_USER  
      x-lineageReferenceObject: TBRMEMO            
    proxy-student-memos-1.0.0_response:
      required:
        - amount
        - billingInd
        - detailCode
        - srceCode
        - user
        - termCode
        - tranNumber
      type: object
      properties:
        srceCode:
          title: Source
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRMEMO_SRCE_CODE, Lookup lineage
            reference object : ttvsrce"
          x-lineageReferenceObject: TBRMEMO_SRCE_CODE
          x-lineageLookupReferenceObject: ttvsrce
        billingInd:
          title: billing Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRMEMO_BILLING_IND"
          x-lineageReferenceObject: TBRMEMO_BILLING_IND
        dataOrigin:  
          title: Data Origin
          maxLength: 20
          type: string
          description: "Lineage reference object : TBRMEMO_DATA_ORIGIN"
          x-lineageReferenceObject: TBRMEMO_DATA_ORIGIN
        expirationDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRMEMO_EXPIRATION_DATE"
          format: date
          x-lineageReferenceObject: TBRMEMO_EXPIRATION_DATE
        amount:
          title: Amount
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRMEMO_AMOUNT"
          x-lineageReferenceObject: TBRMEMO_AMOUNT
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRMEMO_ACTIVITY_DATE"
          format: date
          x-lineageReferenceObject: TBRMEMO_ACTIVITY_DATE
        tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRMEMO_TRAN_NUMBER"
          x-lineageReferenceObject: TBRMEMO_TRAN_NUMBER
        detailCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBRMEMO_DETAIL_CODE, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: TBRMEMO_DETAIL_CODE
          x-lineageLookupReferenceObject: tbbdetc
        user:
          title: User
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_USER"
          x-lineageReferenceObject: TBRMEMO_USER
        desc:
          title: Detail Code Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_DESC"
          x-lineageReferenceObject: TBRMEMO_DESC
        termCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: TBRMEMO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm      
    proxy-student-memos-1.0.0_put_request:
      required:
        - id
        - tranNumber
      type: object
      properties:
        desc:
          title: Detail Code Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRMEMO_DESC"
          x-lineageReferenceObject: TBRMEMO_DESC
        tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRMEMO_TRAN_NUMBER"
          x-lineageReferenceObject: TBRMEMO_TRAN_NUMBER
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        expirationDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRMEMO_EXPIRATION_DATE"
          format: date
          x-lineageReferenceObject: TBRMEMO_EXPIRATION_DATE
      x-lineageReferenceObject: TBRMEMO
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
