openapi: 3.0.0
info:
  title: Student Academic Standings
  description: The calculated academic standings of students.
  version: "8.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-academic-standings:
    get:
      summary: Return all resources from SHRTTRM
      description: Returns a paged listing of all the student academic standing
        records from SHRTTRM table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENT_ACADEMIC_STANDINGS
      tags:
        - student-academic-standings
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v8+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-student-academic-standings.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v8+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/student-academic-standings/{id}:
    get:
      summary: Return the requested resource from SHRTTRM
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_STUDENT_ACADEMIC_STANDINGS
      tags:
        - student-academic-standings
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Student Academic Standings for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v8+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v8+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v8+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-student-academic-standings.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-student-academic-standings.json:
      title: Student Academic Standings
      description: The calculated academic standings of students.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the student academic standing.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: SHRTTRM_GUID(SHRTTRM)
        student:
          title: Student
          description: The student associated with the academic standing.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Student.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: persons 
              x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = persons) 
              x-lineageDerivedLogic: Display GUID from GORGUID where GORGUID_LDM_NAME is 'persons' and GORGUID_DOMAIN_KEY matches SHRTTRM_PIDM
          additionalProperties: false
          required:
            - id
        type:
          title: Type
          description: The type of academic standing calculation used to determine the
            student academic standing (e.g. level, program, academicPeriod).
          enum:
            - level
            - program
            - academicPeriod
          type: string
          x-lineageReferenceObject: derived  
          x-lineageDerivedLogic: Always display as 'academicPeriod'. type 'level' and 'program' not supported
        level:
          title: Level
          description: The academic level associated with the student academic standing.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Level.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-levels 
                  x-lineageReferenceObject: unsupported
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        program:
          title: Program
          description: The academic program associated with the student academic standing.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Program.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-programs 
                  x-lineageReferenceObject: unsupported
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        academicPeriod:
          title: Academic Period
          description: The academic period associated with the student academic standing.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Academic Period.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-periods 
                  x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = term) 
                  x-lineageDerivedLogic: Display GUID from GORGUID where GORGUID_LDM_NAME is 'term' and GORGUID_DOMAIN_KEY matches SHRTTRM_TERM_CODE
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        standing:
          title: Standing
          description: The academic standing calculated for the student.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Standing.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: academic-standings 
              x-lineageReferenceObject: SHRTTRM_ASTD_CODE_END_OF_TERM(SHRTTRM)
          additionalProperties: false
          required:
            - id
        overrideStanding:
          title: Override Standing
          description: A manually entered override of the calculated academic standing.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Override Standing.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-standings 
                  x-lineageReferenceObject: STVASTD_GUID(STVASTD)
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        overrideReason:
          title: Override Reason
          description: The reason the calculated academic standing was overridden.
          type: string
          x-lineageReferenceObject: unsupported
      required:
        - id
        - student
        - type
        - standing
      additionalProperties: false
