openapi: 3.0.0
info:
  title: section-schedule-information
  description: |
    Retrieves the list of section schedule information.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: Section Schedule Information
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: section-schedule-information
paths:
  /api/section-schedule-information:
    get:
      description: >
        __Paging__ Pagination is supported using parameters limit and offset.
        Default value for limit is 100 and upper limit is 250.

          __Sorting__ NA

        __Filtering__ Filtering is supported using url parameters
        [‘sectionsId’].
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_SECTION_SCH_INFORMATION
      tags:
        - section-schedule-information
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version. See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/vnd.hedtech.integration.v1+json
            ```
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Sections Id  

            Returns all section-schedule-information for the sections id passed.

            ```

            /section-schedule-information?criteria={"sectionsId":"9844ed40-2005-4167-a7f8-40648989eed8"}

            ```
      responses:
        "200":
          description: Success
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/section-schedule-information"
              examples:
                section-schedule-information:
                  $ref: "#/components/examples/section-schedule-information"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    section-schedule-information:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
            description: The unique identifier for section schedule information.
            x-lineageReferenceObject: SSBSECT_SURROGATE_ID
          sectionsId:
            type: string
            description: A globally unique identifier of a section to be used in all
              external references.
            x-lineageReferenceObject: SSBSGID_GUID
          sectionTypeTitles:
            type: array
            description: The type of course title (e.g. short title, long title).
            items:
              type: object
              properties:
                typeId:
                  type: string
                  description: The global identifier for the Type.
                  x-lineageReferenceObject: STVSTTPE_GUID
                typeTitle:
                  type: string
                  description: The full name of the section title type.
                  x-lineageReferenceObject: STVSTTPE_TITLE
                typeCode:
                  type: string
                  description: The code used to identify the section title type.
                  x-lineageReferenceObject: STVSTTPE_CODE
                typeValue:
                  type: string
                  description: The title for the section associated with the type.
                  x-lineageReferenceObject: SSBSECT_CRSE_TITLE, SSRSYLN_LONG_COURSE_TITLE, SCBCRSE_TITLE, SCRSYLN_LONG_COURSE_TITLE
          sectionStartOn:
            type: string
            description: The starting date at which a section may be scheduled to be taken.
            x-lineageReferenceObject: SSBSECT_PTRM_START_DATE, SSBSECT_LEARNER_REGSTART_FDATE
          sectionEndOn:
            type: string
            description: The ending date at which a section may no longer be scheduled to be
              taken.
            x-lineageReferenceObject: SSBSECT_PTRM_END_DATE, SSBSECT_LEARNER_REGSTART_TDATE
          sectionCode:
            type: string
            description: The human-readable identifier of a section. It is generally unique
              within an academic period.
            x-lineageReferenceObject: SSBSECT_CRN
          sectionNumber:
            type: string
            description: A numbering scheme or other mark that distinguishes between
              multiple sections. It is generally unique within an academic
              period and course.
            x-lineageReferenceObject: SSBSECT_SEQ_NUMB
          sectionReportingAcademicPeriodId:
            type: string
            description: The global identifier for the Reporting Academic Period associated
              with a section.
            x-lineageReferenceObject: GORGUID_GUID
          courseId:
            type: string
            description: The global identifier for the Course.
            x-lineageReferenceObject: SCBCGID_GUID
          courseNumber:
            type: string
            description: The course number associated with the subject of the course.
            x-lineageReferenceObject: SCBCRSE_CRSE_NUMB
          courseTypeTitles:
            type: array
            description: The type of course title (e.g. short title, long title).
            items:
              type: object
              properties:
                typeId:
                  type: string
                  description: The global identifier for the Type.
                  x-lineageReferenceObject: STVSTTPE_GUID
                typeTitle:
                  type: string
                  description: The full name of the course title type.
                  x-lineageReferenceObject: STVCTTPE_TITLE
                typeCode:
                  type: string
                  description: A code used to identify the course title type.
                  x-lineageReferenceObject: STVCTTPE_CODE
                typeValue:
                  type: string
                  description: The title for the course associated with the type.
                  x-lineageReferenceObject: SCBCRSE_TITLE, SCRSYLN_LONG_COURSE_TITLE
          subjectId:
            type: string
            description: The global identifier for the Subject.
            x-lineageReferenceObject: GORGUID_GUID
          subjectAbbreviation:
            type: string
            description: Human-readable abbraviated name to a subject.
            x-lineageReferenceObject: STVSUBJ_CODE
          subjectTitle:
            type: string
            description: The full name of a subject.
            x-lineageReferenceObject: STVSUBJ_DESC
          instructionalEvents:
            type: array
            description: Instructional events details for each Section.
            items:
              type: object
              properties:
                instructionalEventId:
                  type: string
                  description: The global identifier of the instructional event.
                  x-lineageReferenceObject: GORGUID_GUID
                recurrenceRepeatRuleEndDate:
                  type: string
                  description: The date after which to stop repeating.
                  x-lineageReferenceObject: SSRMEET_END_DATE
                recurrenceRepeatRuleInterval:
                  type: number
                  description: Number of days between each repetition.
                  x-lineageReferenceObject: derived  
                  x-lineageDerivedLogic: Display 1
                recurrenceRepeatRuleType:
                  type: string
                  description: Type of the repeated rule.
                  enum:
                    - weekly
                  x-lineageReferenceObject: derived  
                  x-lineageDerivedLogic: Display weekly
                recurrenceRepeatRuleDaysOfWeek:
                  type: array
                  description: The days of the week on which to repeat the event.
                  items:
                    type: string
                    enum:
                      - sunday
                      - monday
                      - tuesday
                      - wednesday
                      - thursday
                      - friday
                      - saturday
                  x-lineageReferenceObject: SSRMEET_SAT_DAY(SSRMEET) or  SSRMEET_SUN_DAY(SSRMEET) or  SSRMEET_WED_DAY(SSRMEET) or  SSRMEET_THU_DAY(SSRMEET) or  SSRMEET_FRI_DAY(SSRMEET) or  SSRMEET_MON_DAY(SSRMEET) or  SSRMEET_TUE_DAY(SSRMEET)  
                recurrenceStartOn:
                  type: string
                  description: The beginning of the time period being repeated.
                  x-lineageReferenceObject: derived  
                  x-lineageDerivedLogic: Display the concatenated value of 'SSRMEET_START_DATE and SSRMEET_BEGIN_TIME'
                recurrenceEndOn:
                  type: string
                  description: The end of the time period being repeated.
                  x-lineageReferenceObject: derived  
                  x-lineageDerivedLogic: Display the concatenated value of 'SSRMEET_END_DATE  and  SSRMEET_END_TIME'
                locations:
                  type: array
                  description: The locations where the instructional event will take place.
                  items:
                    type: object
                    properties:
                      locationType:
                        type: string
                        description: The type of location (i.e. room).
                        x-lineageReferenceObject: derived  
                        x-lineageDerivedLogic: Display room. The only room type processed in Banner is 'classroom'
                      locationRoomId:
                        type: string
                        description: The global identifier for the Room.
                        x-lineageReferenceObject: GORGUID_GUID
                      locationRoomNumber:
                        type: string
                        description: A numbering scheme to distinguish different buildings, floors, and
                          rooms located in the same site.
                        x-lineageReferenceObject: SLBRDEF_ROOM_NUMBER
                      locationRoomBuildingId:
                        type: string
                        description: The global identifier for the Building.
                        x-lineageReferenceObject: GORGUID_GUID
                      locationRoomBuildingCode:
                        type: string
                        description: A code that identifies the building.
                        x-lineageReferenceObject: SLBBLDG_BLDG_CODE
                      locationRoomBuildingTitle:
                        type: string
                        description: The full name of the building.
                        x-lineageReferenceObject: STVBLDG_DESC          
  examples:
    section-schedule-information:
      value: >-
        [
          {
            "id": 1,
            "sectionsId": "097168ac-96f8-4c4b-a91b-38dce1f1713d",
            "sectionTypeTitles": [
              {
                "typeId": "8823903e-yta6-2o87-1709-at63782hw234",
                "typeTitle": "Short Section Title",
                "typeCode": "short",
                "typeValue": "Basic Writing"
              },
              {
                "typeId": "6674563e-tyk7-7h84-2311-ti098348vj908",
                "typeTitle": "Long Section Title",
                "typeCode": "long",
                "typeValue": "Computers and Information Processing"
              }
            ],
            "sectionStartOn": "2021-08-29",
            "sectionEndOn": "2024-12-16",
            "sectionCode": "20021",
            "sectionNumber": "001",
            "sectionReportingAcademicPeriodId": "87737a3e-643e-4844-938d-f233183bb369",
            "courseId": "4336e927-6fba-4fee-8530-bd0daafc09d5",
            "courseNumber": "101",
            "courseTypeTitles": [
              {
                "typeId": "477a67ca-3c77-4050-8024-2e33eaf6c5a6",
                "typeTitle": "Short Course Title",
                "typeCode": "short",
                "typeValue": "Technical Writing"
              },
              {
                "typeId": "bf6896d6-6fd4-4e1e-8e1e-263c28f08ada",
                "typeTitle": "Long Course Title",
                "typeCode": "long",
                "typeValue": "Business and Economic Statistics"
              }
            ],
            "subjectId": "f455a278-9a6f-474f-a2dd-0e6508edf955",
            "subjectAbbreviation": "MATH",
            "subjectTitle": "Mathematics",
            "instructionalEvents": [
              {
                "instructionalEventId": "2ebfb9af-3f3b-4994-a54c-d7291f18d9e2",
                "recurrenceRepeatRuleEndDate": "1994-12-09",
                "recurrenceRepeatRuleInterval": 1,
                "recurrenceRepeatRuleType": "weekly",
                "recurrenceRepeatRuleDaysOfWeek": ["tuesday", "thursday"],
                "recurrenceStartOn": "1994-08-29T13:00:00-04:00",
                "recurrenceEndOn": "1994-12-09T13:50:00-05:00",
                "locations": [
                  {
                    "locationType": "room",
                    "locationRoomId": "2292feff-9891-451c-ab65-1a8fd307cefe",
                    "locationRoomNumber": "101",
                    "locationRoomBuildingId": "3fbdf2b6-be1e-4dd4-acce-6cb611919faf",
                    "locationRoomBuildingCode": "CSB",
                    "locationRoomBuildingTitle": "Computer Science Building"
                  }
                ]
              }
            ]
          }
        ]