openapi: 3.0.0
info:
  title: Direct Reporters
  description: Reportees details of the Supervisor to create hierarchy.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Human Resources
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-reporters:
    get:
      summary: Direct Reporters hierarchy
      description: Reportees details of the Supervisor to create hierarchy.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_DIRECT_REPORTERS
      tags:
        - direct-reporters
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: bannerId
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: string
          description: |
            ### bannerId  
            Returns all the direct reportees for the bannerId
            ```
            /direct-reporters?bannerId="HOSH111111"
            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-direct-reportees.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "201":
          description: Failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "#/components/schemas/ErrorsObj"
              examples:
                MandtoryFieldsMissing:
                  $ref: "#/components/examples/MandtoryFieldsMissing"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-direct-reportees.json:
      title: Direct Reporters
      description: Reportees details of the Supervisor to create hierarchy.
      type: object
      properties:
        fullName:
          title: Full Name
          description: Employee full Name that is displayed based on the hierarchy
            configured by the user.
          type: string
        firstName:
          title: First Name
          description: First Name of an employee.
          type: string
        lastName:
          title: Last Name
          description: Last Name of an employee.
          type: string
        middleName:
          title: Middle Name
          description: Middle Name of an employee.
          type: string
        preferredFirstName:
          title: Preferred First Name
          description: Preferred First Name of an employee defined in the SPAIDEN.
          type: string
        bannerId:
          title: Banner ID
          description: Banner ID of an employee.
          type: string
        jobTitle:
          title: Job Title
          description: Title of the employee's job.
          type: string
        positionCode:
          title: Position Code
          description: Position number of the employee's job.
          type: string
        parentPosition:
          title: Parent Position Code
          description: Position number for the employee's supervisor job.
          type: string
        suffix:
          title: Suffix
          description: Position suffix of the employee's job.
          type: string
        locationCode:
          title: Location code
          description: Job Location Code attached to the job.
          type: string
        location:
          title: Location
          description: Location description of the job/hiring location.
          type: string
        organizationCode:
          title: Organization Code
          description: Organization code where time sheet is sent for this job.
          type: string
        organizationDescription:
          title: Organization Description
          description: The hierarchy description or title appropriate for this level.
          type: string
        namePrefix:
          title: Name Prefix
          description: Defines the prefix (Mr, Mrs, etc) used before person name.
          type: string
        nameSuffix:
          title: Name Suffix
          description: Defines the suffix (Jr, Sr, etc) used after person name.
          type: string
        personPositionId:
          title: Person Position ID
          description: Unique Identifier for the person's position code.
          type: string
        parentPersonPositionId:
          title: Parent Person Position ID
          description: Unique Identifier for the supervisors position code.
          type: string
        directReportersCount:
          title: Direct Reporters Count
          description: Number of reportees reporting to the supervisor.
          type: integer
        supervisorId:
          title: Supervisor ID
          description: Banner ID of the Supervisor.
          type: string
        gender:
          title: Gender
          description: Returns the sex of person. Valid values are, M - Male, F - Female,
            N - Unknown.
          type: string
    ErrorsObj:
      type: object
      properties:
        failure:
          type: string
        error:
          type: object
          properties:
            message:
              type: string
        sampleRequest:
          type: object
          properties:
            bannerId:
              type: string
  examples:
    MandtoryFieldsMissing:
      value: |-
        {
           "failure": true,
            "sampleRequest": {
               "bannerId": "string"
            },
           "error": {
               "message": "Missing one or more mandatory parameters."
           }
        }
