openapi: 3.0.0
info:
  title: multiple-detail-codes-currency-and-tax-profile
  description: API for TVAMCTX administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TVAMCTX
  x-source-domain: Student
  x-source-title: Multiple Detail Codes and Tax Profile
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/multiple-detail-codes-currency-and-tax-profile:
    get:
      tags:
        - multiple-detail-codes-currency-and-tax-profile
      summary: Return resources from TVAMCTX
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: detailCode
          in: query
          required: false
          schema:
            type: string
        - name: desc
          in: query
          required: false
          schema:
            type: string
        - name: taxProfile
          in: query
          required: false
          schema:
            type: string
        - name: taxProfileStatus
          in: query
          required: false
          schema:
            type: string
        - name: taxMethod
          in: query
          required: false
          schema:
            type: string
        - name: typeInd
          in: query
          required: false
          schema:
            type: string
        - name: priority
          in: query
          required: false
          schema:
            type: string
        - name: dcatCode
          in: query
          required: false
          schema:
            type: string
        - name: tbrdcurCurrCode
          in: query
          required: false
          schema:
            type: string
        - name: txprCode
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRDCTX_TXPR_CODE
        - name: effDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRDCTX_EFF_DATE
        - name: termDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRDCTX_TERM_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/multiple-detail-codes-currency-and-tax-profile-1.0.\
                    0_get_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/multiple-detail-codes-currency-and-tax-profile:
    post:
      tags:
        - multiple-detail-codes-currency-and-tax-profile QAPI (Query by POST)
      summary: Return resources from TVAMCTX
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/multiple-detail-codes-currency-and-tax-profile-1.0.\
                0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/multiple-detail-codes-currency-and-tax-profile-1.0.\
                    0_get_response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    multiple-detail-codes-currency-and-tax-profile-1.0.0_get_response:
      type: object
      properties:
        tbbdetc:
          type: array
          items:
            required:
              - desc
              - detailCode
              - priority
              - typeInd
            type: object
            properties:
              taxCalculation:
                title: Tax Calculation Method
                maxLength: 30
                type: string
              typeInd:
                title: Type
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBDETC_TYPE_IND"
                x-lineageReferenceObject: TBBDETC_TYPE_IND
              taxProfileDescription:
                type: string
              taxProfileStatus:
                maxLength: 1
                type: string
              taxMethod:
                maxLength: 1
                type: string
              taxProfile:
                type: string
              dcatCode:
                title: Category
                maxLength: 30
                type: string
                description: "Lineage reference object : TBBDETC_DCAT_CODE, Lookup lineage
                  reference object : TTVDCAT"
                x-lineageReferenceObject: TBBDETC_DCAT_CODE
                x-lineageLookupReferenceObject: TTVDCAT
              priority:
                title: Priority
                maxLength: 3
                type: string
                description: "Lineage reference object : TBBDETC_PRIORITY"
                x-lineageReferenceObject: TBBDETC_PRIORITY
              detailCode:
                title: Detail Code
                maxLength: 4
                type: string
                description: "Lineage reference object : TBBDETC_DETAIL_CODE"
                x-lineageReferenceObject: TBBDETC_DETAIL_CODE
              tbrdCurrCode:
                title: Currency Code
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRDCUR_CURR_CODE"
                x-lineageReferenceObject: TBRDCUR_CURR_CODE
              desc:
                title: Description
                maxLength: 30
                type: string
                description: "Lineage reference object : TBBDETC_DESC"
                x-lineageReferenceObject: TBBDETC_DESC
            x-lineageReferenceObject: tbbdetc
        tbrdctx:
          type: array
          items:
            required:
              - effDate
              - txprCode
            type: object
            properties:
              effDate:
                title: Effective Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRDCTX_EFF_DATE"
                format: date-time
                x-lineageReferenceObject: TBRDCTX_EFF_DATE
              taxCalculation:
                title: Tax Calculation Method
                type: string
              displayNchgDate:
                maxLength: 11
                type: string
                format: date-time
              txprCode:
                title: Tax Profile
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRDCTX_TXPR_CODE, Lookup lineage
                  reference object :
                  NEW,TVRTXPR_DATE_TO,NEW,TVRTXPR_TAX_ESTIMATION_MODE,FROM,NEW,\
                  TVVTXPR,TRUNC,SYSDATE,AND,TRUNC,NEW,TVRTXPR_DATE_TO,TRUNC,SYS\
                  DATE,OR,TVRTXPR_DATE_TO,NULL,AND,NEW,TVRTXPR_DATE_FROM,SELECT\
                  ,TRUNC,OLD,TVRTXPR_DATE_FROM,FROM,OLD"
                x-lineageReferenceObject: TBRDCTX_TXPR_CODE
                x-lineageLookupReferenceObject: NEW,TVRTXPR_DATE_TO,NEW,TVRTXPR_TAX_ESTIMATION_MODE,FROM,NEW,TVVTXPR,TRUNC,SYSDATE,AND,TRUNC,NEW,TVRTXPR_DATE_TO,TRUNC,SYSDATE,OR,TVRTXPR_DATE_TO,NULL,AND,NEW,TVRTXPR_DATE_FROM,SELECT,TRUNC,OLD,TVRTXPR_DATE_FROM,FROM,OLD
              tvvtxprDesc:
                title: Tax Profile Description
                type: string
              termDate:
                title: Termination Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRDCTX_TERM_DATE"
                format: date-time
                x-lineageReferenceObject: TBRDCTX_TERM_DATE
              detcCode:
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRDCTX_DETC_CODE"
                x-lineageReferenceObject: TBRDCTX_DETC_CODE
            x-lineageReferenceObject: tbrdctx
    multiple-detail-codes-currency-and-tax-profile-1.0.0_qapi_post:
      type: object
      properties:
        detailCode:
          type: string
        desc:
          type: string
        taxProfile:
          type: string
        taxProfileStatus:
          type: string
        taxMethod:
          type: string
        typeInd:
          type: string
        priority:
          type: string
        dcatCode:
          type: string
        tbrdcurCurrCode:
          type: string
        txprCode:
          title: Tax Profile
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRDCTX_TXPR_CODE, Lookup lineage
            reference object :
            NEW,TVRTXPR_DATE_TO,NEW,TVRTXPR_TAX_ESTIMATION_MODE,FROM,NEW,TVVTXP\
            R,TRUNC,SYSDATE,AND,TRUNC,NEW,TVRTXPR_DATE_TO,TRUNC,SYSDATE,OR,TVRT\
            XPR_DATE_TO,NULL,AND,NEW,TVRTXPR_DATE_FROM,SELECT,TRUNC,OLD,TVRTXPR\
            _DATE_FROM,FROM,OLD"
          x-lineageReferenceObject: TBRDCTX_TXPR_CODE
          x-lineageLookupReferenceObject: NEW,TVRTXPR_DATE_TO,NEW,TVRTXPR_TAX_ESTIMATION_MODE,FROM,NEW,TVVTXPR,TRUNC,SYSDATE,AND,TRUNC,NEW,TVRTXPR_DATE_TO,TRUNC,SYSDATE,OR,TVRTXPR_DATE_TO,NULL,AND,NEW,TVRTXPR_DATE_FROM,SELECT,TRUNC,OLD,TVRTXPR_DATE_FROM,FROM,OLD
        effDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRDCTX_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: TBRDCTX_EFF_DATE
        termDate:
          title: Termination Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRDCTX_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: TBRDCTX_TERM_DATE
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    multiple-detail-codes-currency-and-tax-profile-1.0.0_get_request:
      required:
        - detailCode
        - desc
        - typeInd
        - priority
        - txprCode
        - effDate
      type: object
      properties:
        effDate:
          title: Effective Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRDCTX_EFF_DATE"
          format: date-time
          x-lineageReferenceObject: TBRDCTX_EFF_DATE
        typeInd:
          title: Type
          maxLength: 1
          type: string
          description: "Lineage reference object : TBBDETC_TYPE_IND"
          x-lineageReferenceObject: TBBDETC_TYPE_IND
        taxProfileStatus:
          maxLength: 1
          type: string
        taxMethod:
          maxLength: 1
          type: string
        taxProfile:
          type: string
        dcatCode:
          title: Category
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBDETC_DCAT_CODE, Lookup lineage
            reference object : TTVDCAT"
          x-lineageReferenceObject: TBBDETC_DCAT_CODE
          x-lineageLookupReferenceObject: TTVDCAT
        txprCode:
          title: Tax Profile
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRDCTX_TXPR_CODE, Lookup lineage
            reference object :
            NEW,TVRTXPR_DATE_TO,NEW,TVRTXPR_TAX_ESTIMATION_MODE,FROM,NEW,TVVTXP\
            R,TRUNC,SYSDATE,AND,TRUNC,NEW,TVRTXPR_DATE_TO,TRUNC,SYSDATE,OR,TVRT\
            XPR_DATE_TO,NULL,AND,NEW,TVRTXPR_DATE_FROM,SELECT,TRUNC,OLD,TVRTXPR\
            _DATE_FROM,FROM,OLD"
          x-lineageReferenceObject: TBRDCTX_TXPR_CODE
          x-lineageLookupReferenceObject: NEW,TVRTXPR_DATE_TO,NEW,TVRTXPR_TAX_ESTIMATION_MODE,FROM,NEW,TVVTXPR,TRUNC,SYSDATE,AND,TRUNC,NEW,TVRTXPR_DATE_TO,TRUNC,SYSDATE,OR,TVRTXPR_DATE_TO,NULL,AND,NEW,TVRTXPR_DATE_FROM,SELECT,TRUNC,OLD,TVRTXPR_DATE_FROM,FROM,OLD
        priority:
          title: Priority
          maxLength: 3
          type: string
          description: "Lineage reference object : TBBDETC_PRIORITY"
          x-lineageReferenceObject: TBBDETC_PRIORITY
        termDate:
          title: Termination Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBRDCTX_TERM_DATE"
          format: date-time
          x-lineageReferenceObject: TBRDCTX_TERM_DATE
        detailCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : TBBDETC_DETAIL_CODE"
          x-lineageReferenceObject: TBBDETC_DETAIL_CODE
        tbrdcurCurrCode:
          title: Currency Code
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRDCUR_CURR_CODE"
          x-lineageReferenceObject: TBRDCUR_CURR_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBDETC_DESC"
          x-lineageReferenceObject: TBBDETC_DESC
      x-lineageReferenceObject: TBRDCTX
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
