openapi: 3.0.0
info:
  title: faculty-information-colleges-and-departments-copy
  description: API for SIAINST administrative page
  version: 1.0.0
  x-source-name: SIAINST
  x-source-title: Faculty/Advisor Information
  x-source-system: banner
  x-api-type: bus-poc
  x-source-domain: Student
  x-audience: all
  x-release-status: ga
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/faculty-information-colleges-and-departments-copy:
    post:
      tags:
        - faculty-information-colleges-and-departments-copy
      summary: Creates a new resource in SIAINST
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/faculty-information-colleges-and-departments-copy-1\
                .0.0_post_request"
            example:
              keyblckTermCode: 201520
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/faculty-information-colleges-and-departments-copy-1\
                    .0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/faculty-information-colleges-and-departments-copy: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    faculty-information-colleges-and-departments-copy-1.0.0_post_request:
      required:
        - keyblckTermCode
        - id
      type: object
      properties:
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
    faculty-information-colleges-and-departments-copy-1.0.0_post_response:
      type: object
      properties:
        sirdpcl_ctrl_block:
          type: array
          items:
            type: object
            properties:
              sirdpclTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sirdpclTermCodeTo, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sirdpclTermCodeTo
                x-lineageLookupReferenceObject: stvterm
              sirdpclTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sirdpclTermCodeFrom, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sirdpclTermCodeFrom
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: sirdpcl_ctrl_block
        sirdpcl:
          type: array
          items:
            type: object
            properties:
              homeInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : SIRDPCL_HOME_IND"
                x-lineageReferenceObject: SIRDPCL_HOME_IND
              percentage:
                title: Percentage
                maxLength: 3
                type: number
                description: "Lineage reference object : SIRDPCL_PERCENTAGE"
                x-lineageReferenceObject: SIRDPCL_PERCENTAGE
              collDesc:
                type: string
              deptDesc:
                type: string
              collCode:
                title: College
                maxLength: 30
                type: string
                description: "Lineage reference object : SIRDPCL_COLL_CODE, Lookup lineage
                  reference object : stvcoll"
                x-lineageReferenceObject: SIRDPCL_COLL_CODE
                x-lineageLookupReferenceObject: stvcoll
              deptCode:
                title: Department
                maxLength: 30
                type: string
                description: "Lineage reference object : SIRDPCL_DEPT_CODE, Lookup lineage
                  reference object : stvdept"
                x-lineageReferenceObject: SIRDPCL_DEPT_CODE
                x-lineageLookupReferenceObject: stvdept
            x-lineageReferenceObject: sirdpcl
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
