openapi: 3.0.0
info:
  title: geographic-region-rules
  description: API for SOAGEOR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SOAGEOR
  x-source-domain: Student
  x-source-title: Geographic Region Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/geographic-region-rules:
    get:
      tags:
        - geographic-region-rules
      summary: Return resources from SOAGEOR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: georCode
          in: query
          required: false
          schema:
            type: string
        - name: geodCode
          in: query
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORGEOR_TYPE
        - name: startRange
          in: query
          description: Value A
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORGEOR_START_RANGE
        - name: endRange
          in: query
          description: Value B
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORGEOR_END_RANGE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/geographic-region-rules-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - geographic-region-rules
      summary: Updates an existing resource in SOAGEOR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/geographic-region-rules-1.0.0_put_request"
            example:
              georCode: BALT/WASH
              startRange: 100
              endRange: 2
              geodCode: ALUM
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/geographic-region-rules-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - geographic-region-rules
      summary: Creates a new resource in SOAGEOR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/geographic-region-rules-1.0.0_post_request"
            example:
              georCode: BALT/WASH
              startRange: 1000
              endRange: 2
              geodCode: ALUM
              type: CITY
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/geographic-region-rules-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/geographic-region-rules:
    post:
      tags:
        - geographic-region-rules QAPI (Query by POST)
      summary: Return resources from SOAGEOR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/geographic-region-rules-1.0.0_get_request"
            example:
              georCode: BALT/WASH
              geodCode: ALUM
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/geographic-region-rules-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    geographic-region-rules-1.0.0_post_response:
      required:
        - startRange
        - type
      type: object
      properties:
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
      x-lineageReferenceObject: sorgeor
    geographic-region-rules-1.0.0_get_request:
      required:
        - type
        - startRange
      type: object
      properties:
        georCode:
          title: Region
          maxLength: 30
          type: string
          description: "Lineage reference object : georCode, Lookup lineage reference
            object : stvgeor"
          x-lineageReferenceObject: georCode
          x-lineageLookupReferenceObject: stvgeor
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        geodCode:
          title: Division
          maxLength: 30
          type: string
          description: "Lineage reference object : geodCode, Lookup lineage reference
            object : stvgeod"
          x-lineageReferenceObject: geodCode
          x-lineageLookupReferenceObject: stvgeod
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
      x-lineageReferenceObject: SORGEOR
    geographic-region-rules-1.0.0_put_response:
      required:
        - startRange
        - type
      type: object
      properties:
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
      x-lineageReferenceObject: sorgeor
    geographic-region-rules-1.0.0_qapi_post:
      type: object
      properties:
        georCode:
          type: string
        geodCode:
          type: string
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    geographic-region-rules-1.0.0_get_response:
      required:
        - startRange
        - type
      type: object
      properties:
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
      x-lineageReferenceObject: sorgeor
    geographic-region-rules-1.0.0_post_request:
      required:
        - type
        - startRange
      type: object
      properties:
        georCode:
          title: Region
          maxLength: 30
          type: string
          description: "Lineage reference object : georCode, Lookup lineage reference
            object : stvgeor"
          x-lineageReferenceObject: georCode
          x-lineageLookupReferenceObject: stvgeor
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        geodCode:
          title: Division
          maxLength: 30
          type: string
          description: "Lineage reference object : geodCode, Lookup lineage reference
            object : stvgeod"
          x-lineageReferenceObject: geodCode
          x-lineageLookupReferenceObject: stvgeod
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
      x-lineageReferenceObject: SORGEOR
    geographic-region-rules-1.0.0_put_request:
      required:
        - criteria.type
        - criteria.startRange
        - type
        - startRange
      type: object
      properties:
        georCode:
          title: Region
          maxLength: 30
          type: string
          description: "Lineage reference object : georCode, Lookup lineage reference
            object : stvgeor"
          x-lineageReferenceObject: georCode
          x-lineageLookupReferenceObject: stvgeor
        startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
        criteria.endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        endRange:
          title: Value B
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_END_RANGE"
          x-lineageReferenceObject: SORGEOR_END_RANGE
        geodCode:
          title: Division
          maxLength: 30
          type: string
          description: "Lineage reference object : geodCode, Lookup lineage reference
            object : stvgeod"
          x-lineageReferenceObject: geodCode
          x-lineageLookupReferenceObject: stvgeod
        type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
        criteria.type:
          title: Type
          maxLength: 10
          type: string
          description: "Lineage reference object : SORGEOR_TYPE"
          x-lineageReferenceObject: SORGEOR_TYPE
        criteria.startRange:
          title: Value A
          maxLength: 20
          type: string
          description: "Lineage reference object : SORGEOR_START_RANGE"
          x-lineageReferenceObject: SORGEOR_START_RANGE
      x-lineageReferenceObject: SORGEOR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
