openapi: 3.0.0
info:
  title: Security Owner Details
  description: >
  
    The Security Owner Details API provides information about Banner Security Owners as shown on the Objects tab on the GSASECR administrative page in Banner Access Management.


    Note: To maintain strict access control, the required security object must be assigned directly to individual users. 
    Assignment via security classes is not supported for this API.
  version: 1.0.0
  x-api-type: erp
  x-release-status: ga
  x-source-system: banner
  x-audience: all
  x-source-domain: Foundation
  x-source-name: GSASECR
  x-source-title: null
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/security-owner-details:
    get:
      tags:
      - security-owner-details
      summary: Returns Security Owner Details.
      description: Returns resources from GUROWNR.
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          description:  |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object   
          description: >
            ### Owned Object

            Returns all records for the Owned Object passed.

            ```

            /security-owner-details?criteria={"ownedObject":"FOIIDEN"}

            ```

            ### Object Type

            Returns all security owner records for the Object Type passed.

            ```

            /security-owner-details?criteria={"objectType":"object"}

            ```      

            ### Security Owner

            Returns all security owner records for the Security Owner passed.

            ```

            /security-owner-details?criteria={"securityOwner":"BANSECR"}

            ```                            
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/security-owner-details-1.0.0_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the clientâ€™s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_SECURITY_OWNER_DETAILS
  /api/security-owner-details/{id}:
    get:
      summary: Returns the requested resource from GUROWNR.
      description: |
        Returns a record from GUROWNR with the passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SECURITY_OWNER_DETAILS
      tags:
        - security-owner-details
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v16.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/security-owner-details-1.0.0_response"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data        
components:
  schemas:
    security-owner-details-1.0.0_response:
      type: object
      required:
        - id
        - ownedObject
        - objectType
        - ownerPrivilegeDetails
        - securityOwner
        - grantor
        - canGrantPrivileges
        - canAssignGrantPrivilege
        - canRevokePrivileges
        - canRevokeGrantPrivilege
        - canDelete
        - canAssignDeletePrivilege
        - canModify
        - canAssignModifyPrivilege          
      properties:
        id:
          title: Security Owner ID
          description: "Unique identifier for the security owner."
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GUROWNR_GUID
          example: 49fzfc68-3t89-4036-822c-341aa9d8501q          
          maxLength: 36
        ownedObject:
          title: Owned Object
          description: "The owned object for which access is being defined."
          type: string
          x-lineageReferenceObject: GUROWNR_OBJECT
          example: "FOIIDEN"
          maxLength: 30   
        objectType:
          title: Object Type
          description: "The type of object. C-Class, G-Distributed Security Groups, O-Object, P-Profile, R-Role, S-Security Groups."
          type: string
          x-lineageReferenceObject: GUROWNR_OBJECT_TYPE
          enum:
            - class
            - distributedSecurityGroups
            - object
            - profile
            - role
            - securityGroups
          example: "object"
          maxLength: 1      
        securityOwner:
          title: Security Owner
          description: "The distributed security user of the object."
          type: string
          x-lineageReferenceObject: GUROWNR_OWNER
          example: 'PUBLIC'
          maxLength: 30                 
        grantor:
          title: Grantor
          description: "The distributed user that granted the permissions."
          type: string
          x-lineageReferenceObject: GUROWNR_GRANTOR
          example: "BANSECR"
          maxLength: 30
        canGrantPrivileges:
          title: Can Grant Privileges Indicator
          description: "Ability to grant or add this object to an end user / class / profile / role."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_GRANT
          example: true
          maxLength: 1  
        canAssignGrantPrivilege:
          title: Can Assign Granting Privileges Indicator
          description: "Ability to assign the granting privilege of this object to another distributed user."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_GRANT_ASSIGN
          example: true
          maxLength: 1 
        canRevokePrivileges:
          title: Can Revoke Privileges Indicator
          description: "Ability to revoke or remove access to this object to an end user / class / profile / role."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_REVOKE
          example: false
          maxLength: 1  
        canRevokeGrantPrivilege:
          title: Can Revoke Granting Privileges Indicator
          description: "Ability to revoke the granting privilege of this object from another distributed user."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_REVOKE_ASSIGN
          example: false
          maxLength: 1 
        canDelete:
          title: Can Delete Indicator
          description: "Ability to delete this object."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_DELETE
          example: false
          maxLength: 1  
        canAssignDeletePrivilege:
          title: Can Assign Delete Privileges Indicator
          description: "Ability to assign the delete privilege of this object to another distributed user."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_DELETE_ASSIGN
          example: false
          maxLength: 1  
        canModify:
          title: Can Modify Indicator
          description: "Ability to modify this object."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_MODIFY
          example: true
          maxLength: 1  
        canAssignModifyPrivilege:
          title: Can Assign Modify Privileges Indicator
          description: "Ability to assign the modify privilege of this object to another distributed user."
          type: boolean
          x-lineageReferenceObject: GUROWNR_PRIV_MODIFY_ASSIGN
          example: true
          maxLength: 1                                                                               
        comment:
          title: Comment
          description: "Comments related to this ownership relationship."
          type: string
          x-lineageReferenceObject: GUROWNR_COMMENTS
          example: "Test owner comment"
          maxLength: 4000                                    
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
              type: object
              properties:
                id:
                  type: string
                  description: The global identifier of the resource in error.
                sourceId:
                  type: string
                  description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
                code:
                  type: string
                  description: The error message code used to describe the error details.
                description:
                  type: string
                  description: The error description used to describe the error details.
                message:
                  type: string
                  description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic