openapi: 3.0.0
info:
  title: alternate-personal-identification-numbers
  description: API for SPAAPIN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SPAAPIN
  x-source-domain: Student
  x-source-title: Alternate Personal Identification Number
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/alternate-personal-identification-numbers:
    get:
      tags:
        - alternate-personal-identification-numbers
      summary: Return resources from SPAAPIN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          description: Term Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
        - name: id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - alternate-personal-identification-numbers
      summary: Updates an existing resource in SPAAPIN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_put\
                _request"
            example:
              pin: 12345
              termCodeKey: ZZZZ59
              id: A00031927
              criteria.termCode: ZZZZ59
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_put\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - alternate-personal-identification-numbers
      summary: Creates a new resource in SPAAPIN
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_pos\
                t_request"
            example:
              pin: 1234
              processName: test
              termCodeKey: ZZZZ59
              id: A00031927
              termCode: ZZZZ59
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_pos\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/alternate-personal-identification-numbers:
    post:
      tags:
        - alternate-personal-identification-numbers QAPI (Query by POST)
      summary: Return resources from SPAAPIN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_get\
                _request"
            example:
              id: A00031927
              termCode: ZZZZ59
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/alternate-personal-identification-numbers-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    alternate-personal-identification-numbers-1.0.0_put_request:
      required:
        - criteria.termCode
        - criteria.processName
        - criteria.pin
        - termCode
        - pin
      type: object
      properties:
        criteria.activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SPRAPIN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRAPIN_ACTIVITY_DATE
        pin:
          title: Alternate PIN
          maxLength: 6
          type: string
          description: "Lineage reference object : SPRAPIN_PIN"
          x-lineageReferenceObject: SPRAPIN_PIN
        criteria.pin:
          title: Alternate PIN
          maxLength: 6
          type: string
          description: "Lineage reference object : SPRAPIN_PIN"
          x-lineageReferenceObject: SPRAPIN_PIN
        criteria.processName:
          title: Process Name
          maxLength: 15
          type: string
          description: "Lineage reference object : SPRAPIN_PROCESS_NAME"
          x-lineageReferenceObject: SPRAPIN_PROCESS_NAME
        termCodeKey:
          title: From Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SPRAPIN
    alternate-personal-identification-numbers-1.0.0_get_response:
      required:
        - pin
        - processName
        - termCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SPRAPIN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRAPIN_ACTIVITY_DATE
        pin:
          title: Alternate PIN
          maxLength: 6
          type: string
          description: "Lineage reference object : SPRAPIN_PIN"
          x-lineageReferenceObject: SPRAPIN_PIN
        processName:
          title: Process Name
          maxLength: 15
          type: string
          description: "Lineage reference object : SPRAPIN_PROCESS_NAME"
          x-lineageReferenceObject: SPRAPIN_PROCESS_NAME
        termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sprapin
    alternate-personal-identification-numbers-1.0.0_qapi_post:
      type: object
      properties:
        termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        id:
          type: string
    alternate-personal-identification-numbers-1.0.0_put_response:
      required:
        - pin
        - processName
        - termCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SPRAPIN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRAPIN_ACTIVITY_DATE
        pin:
          title: Alternate PIN
          maxLength: 6
          type: string
          description: "Lineage reference object : SPRAPIN_PIN"
          x-lineageReferenceObject: SPRAPIN_PIN
        processName:
          title: Process Name
          maxLength: 15
          type: string
          description: "Lineage reference object : SPRAPIN_PROCESS_NAME"
          x-lineageReferenceObject: SPRAPIN_PROCESS_NAME
        termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sprapin
    alternate-personal-identification-numbers-1.0.0_post_request:
      required:
        - termCode
        - processName
        - pin
      type: object
      properties:
        pin:
          title: Alternate PIN
          maxLength: 6
          type: string
          description: "Lineage reference object : SPRAPIN_PIN"
          x-lineageReferenceObject: SPRAPIN_PIN
        processName:
          title: Process Name
          maxLength: 15
          type: string
          description: "Lineage reference object : SPRAPIN_PROCESS_NAME"
          x-lineageReferenceObject: SPRAPIN_PROCESS_NAME
        termCodeKey:
          title: From Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SPRAPIN
    alternate-personal-identification-numbers-1.0.0_post_response:
      required:
        - pin
        - processName
        - termCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SPRAPIN_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SPRAPIN_ACTIVITY_DATE
        pin:
          title: Alternate PIN
          maxLength: 6
          type: string
          description: "Lineage reference object : SPRAPIN_PIN"
          x-lineageReferenceObject: SPRAPIN_PIN
        processName:
          title: Process Name
          maxLength: 15
          type: string
          description: "Lineage reference object : SPRAPIN_PROCESS_NAME"
          x-lineageReferenceObject: SPRAPIN_PROCESS_NAME
        termCode:
          title: Term Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRAPIN_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SPRAPIN_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sprapin
    alternate-personal-identification-numbers-1.0.0_get_request:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        termCode:
          title: From Term
          maxLength: 30
          type: string
          description: "Lineage reference object : termCode, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCode
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
