openapi: 3.0.0
info:
  title: employee-status-change-emcumbrance
  description: API for PEAESCH administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: PEAESCH
  x-source-domain: Human Resources
  x-source-title: Employee Status Change
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/employee-status-change-emcumbrance:
    get:
      tags:
        - employee-status-change-emcumbrance
      summary: Return resources from PEAESCH
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: actionList
          in: query
          required: true
          schema:
            type: string
        - name: allCbox
          in: query
          required: false
          schema:
            type: string
        - name: actionDate
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/employee-status-change-emcumbrance-1.0.0_get_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/employee-status-change-emcumbrance:
    post:
      tags:
        - employee-status-change-emcumbrance QAPI (Query by POST)
      summary: Return resources from PEAESCH
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/employee-status-change-emcumbrance-1.0.0_get_reques\
                t"
            example:
              allCbox: Y
              actionList: L
              lreaCode: Y
              id: Z001
              actionDate: 2021-01-07
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/employee-status-change-emcumbrance-1.0.0_get_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    employee-status-change-emcumbrance-1.0.0_get_request:
      required:
        - actionList
      type: object
      properties:
        allCbox:
          title: All Records
          maxLength: 1
          type: string
          description: "Lineage reference object : allCbox"
          x-lineageReferenceObject: allCbox
        actionList:
          title: Action
          maxLength: 1
          type: string
          description: "Lineage reference object : actionList"
          x-lineageReferenceObject: actionList
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        actionDate:
          title: Personnel Date
          maxLength: 11
          type: string
          description: "Lineage reference object : actionDate"
          format: date-time
          x-lineageReferenceObject: actionDate
      x-lineageReferenceObject: KEY_BLOCK
    employee-status-change-emcumbrance-1.0.0_qapi_post:
      required:
        - actionList
      type: object
      properties:
        id:
          type: string
        actionList:
          type: string
        allCbox:
          type: string
        actionDate:
          type: string
    employee-status-change-emcumbrance-1.0.0_get_response:
      type: object
      properties:
        pebempl:
          type: array
          items:
            type: object
            properties:
              firstWorkDate:
                title: First Work Day
                maxLength: 11
                type: string
                description: "Lineage reference object : PEBEMPL_FIRST_WORK_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_FIRST_WORK_DATE
              lreaDesc:
                maxLength: 30
                type: string
              termBargCbox:
                title: Terminate Bargaining Units
                maxLength: 1
                type: string
              currentHireDate:
                title: Current Hire Date
                maxLength: 11
                type: string
                description: "Lineage reference object : PEBEMPL_CURRENT_HIRE_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_CURRENT_HIRE_DATE
              adjServiceDate:
                title: Adjusted Service Date
                maxLength: 11
                type: string
                description: "Lineage reference object : PEBEMPL_ADJ_SERVICE_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_ADJ_SERVICE_DATE
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : PEBEMPL_USER_ID"
                x-lineageReferenceObject: PEBEMPL_USER_ID
              loaBegDate:
                title: Leave Begin Date
                maxLength: 11
                type: string
                description: "Lineage reference object : PEBEMPL_LOA_BEG_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_LOA_BEG_DATE
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : PEBEMPL_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_ACTIVITY_DATE
              perbargEndDate:
                title: Bargaining Units End Date
                maxLength: 11
                type: string
                format: date-time
              treaDesc:
                maxLength: 30
                type: string
              lastWorkDate:
                title: Last Work Day
                maxLength: 11
                type: string
                description: "Lineage reference object : PEBEMPL_LAST_WORK_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_LAST_WORK_DATE
              loaEndDate:
                title: Leave End Date
                maxLength: 11
                type: string
                description: "Lineage reference object : PEBEMPL_LOA_END_DATE"
                format: date-time
                x-lineageReferenceObject: PEBEMPL_LOA_END_DATE
              treaCode:
                title: Termination Reason
                maxLength: 2
                type: string
                description: "Lineage reference object : PEBEMPL_TREA_CODE"
                x-lineageReferenceObject: PEBEMPL_TREA_CODE
              lreaCode:
                title: Leave Reason
                maxLength: 2
                type: string
                description: "Lineage reference object : PEBEMPL_LREA_CODE"
                x-lineageReferenceObject: PEBEMPL_LREA_CODE
            x-lineageReferenceObject: pebempl
        form_header:
          type: array
          items:
            type: object
            properties:
              salaryEncumbrance:
                title: Current Fiscal Year
                maxLength: 14
                type: number
                description: "Lineage reference object : salaryEncumbrance"
                x-lineageReferenceObject: salaryEncumbrance
              detailEncumbranceHrs:
                title: Encumbrance Hours
                maxLength: 14
                type: number
                description: "Lineage reference object : detailEncumbranceHrs"
                x-lineageReferenceObject: detailEncumbranceHrs
              dataSeparatorLine1:
                type: string
                description: "Lineage reference object : dataSeparatorLine1"
                x-lineageReferenceObject: dataSeparatorLine1
              contractBeginDate:
                title: Start Date
                maxLength: 11
                type: string
                description: "Lineage reference object : contractBeginDate"
                format: date-time
                x-lineageReferenceObject: contractBeginDate
              totalSalaryEnc:
                title: Total Encumbrance
                maxLength: 23
                type: number
                description: "Lineage reference object : totalSalaryEnc"
                x-lineageReferenceObject: totalSalaryEnc
              dataSeparatorLine0:
                type: string
                description: "Lineage reference object : dataSeparatorLine0"
                x-lineageReferenceObject: dataSeparatorLine0
              contractEndDate:
                title: End Date
                maxLength: 11
                type: string
                description: "Lineage reference object : contractEndDate"
                format: date-time
                x-lineageReferenceObject: contractEndDate
              totalContractHrs:
                title: Total Contract Hours
                maxLength: 8
                type: number
                description: "Lineage reference object : totalContractHrs"
                x-lineageReferenceObject: totalContractHrs
              futureSalaryEnc:
                title: Future Years
                type: number
                description: "Lineage reference object : futureSalaryEnc"
                x-lineageReferenceObject: futureSalaryEnc
              totalEncumbranceHrs:
                title: Total Encumbrance Hours
                maxLength: 8
                type: number
                description: "Lineage reference object : totalEncumbranceHrs"
                x-lineageReferenceObject: totalEncumbranceHrs
            x-lineageReferenceObject: form_header
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
