openapi: 3.0.0
info:
  title: faculty-schedules
  description: |
    Retrieves the faculty schedule details based on the active terms.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: Faculty Schedules
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: faculty-schedules
paths:
  /api/faculty-schedules/{id}:
    get:
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: [ ]
      x-method-permissions: API_FACULTY_SCHEDULES
      tags:
        - faculty-schedules
      parameters:
        - name: id
          in: path
          required: true
          example: 710000028
          schema:
            type: string
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version.
                        
            ```
             application/vnd.hedtech.integration.v1.0.0+json
             ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/faculty-schedules"
            application/xml:
              schema:
                type: object
                $ref: "#/components/schemas/faculty-schedules"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    faculty-schedules:
      type: object
      properties:
        courseSchedule:
          type: array
          items:
            type: object
            properties:
              academicYear:
                type: string
              academicYearDescription:
                type: string
              bannerId:
                type: string
              catalogTitle:
                type: string
              censusEnrollmentDate:
                type: string
                format: date
              college:
                type: string
              courseNumber:
                type: string
              courseReferenceNumber:
                type: string
              courseTitle:
                type: string
              endDate:
                type: string
                format: date
              gradingModeDescription:
                type: string
              meetingTime:
                type: array
                items:
                  type: object
                  properties:
                    beginTime:
                      type: string
                    building:
                      type: string
                    buildingDescription:
                      type: string
                    endDate:
                      type: string
                      format: date
                    endTime:
                      type: string
                    room:
                      type: string
                    startDate:
                      type: string
                      format: date
                    sunday:
                      type: boolean
                    monday:
                      type: boolean
                    tuesday:
                      type: boolean
                    wednesday:
                      type: boolean
                    thursday:
                      type: boolean
                    friday:
                      type: boolean
                    saturday:
                      type: boolean
              overrideDurationIndicator:
                type: boolean
              partOfTerm:
                type: string
              registrationAuthorizationActiveCode:
                type: string
              reservedIndicator:
                type: boolean
              scheduleTypeDescription:
                type: string
              sectionTitle:
                type: string
              sequenceNumber:
                type: string
              startDate:
                type: string
                format: date
              subject:
                type: string
              subjectDescription:
                type: string
              term:
                type: string
              termDescription:
                type: string
