openapi: 3.0.0
info:
  title: life-insurance-rule
  description: API for PTRLIFI administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: PTRLIFI
  x-source-domain: Human Resources
  x-source-title: Life Insurance Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/life-insurance-rule:
    get:
      tags:
        - life-insurance-rule
      summary: Return resources from PTRLIFI
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: bdcaCode
          in: query
          description: Benefit or Deduction
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_BDCA_CODE
        - name: inclPrimaryJobInd
          in: query
          description: Primary
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_INCL_PRIMARY_JOB_IND
        - name: inclSecJobInd
          in: query
          description: Secondary
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_INCL_SEC_JOB_IND
        - name: inclOverloadJobInd
          in: query
          description: Overload
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_INCL_OVERLOAD_JOB_IND
        - name: covMinAmt
          in: query
          description: Coverage Minimum Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_COV_MIN_AMT
        - name: bdplCode
          in: query
          description: Plan
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_BDPL_CODE
        - name: roundingInd
          in: query
          description: Rounding
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_ROUNDING_IND
        - name: covMaxAmt
          in: query
          description: Coverage Maximum Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_COV_MAX_AMT
        - name: emplEmprInd
          in: query
          description: Deduction Indicator
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_EMPL_EMPR_IND
        - name: roundingAmt
          in: query
          description: Coverage Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_ROUNDING_AMT
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRLIFI_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/life-insurance-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/life-insurance-rule:
    post:
      tags:
        - life-insurance-rule QAPI (Query by POST)
      summary: Return resources from PTRLIFI
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/life-insurance-rule-1.0.0_get_request"
            example:
              bdcaCode: L51
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/life-insurance-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    life-insurance-rule-1.0.0_get_request:
      required:
        - bdcaCode
        - covMinAmt
        - roundingInd
        - covMaxAmt
        - emplEmprInd
        - roundingAmt
        - activityDate
      type: object
      properties:
        inclOverloadJobInd:
          title: Overload
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_OVERLOAD_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_OVERLOAD_JOB_IND
        covMaxAmt:
          title: Coverage Maximum Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_COV_MAX_AMT"
          x-lineageReferenceObject: PTRLIFI_COV_MAX_AMT
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRLIFI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRLIFI_ACTIVITY_DATE
        bdcaCode:
          title: Benefit or Deduction
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRLIFI_BDCA_CODE"
          x-lineageReferenceObject: PTRLIFI_BDCA_CODE
        roundingAmt:
          title: Coverage Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_ROUNDING_AMT"
          x-lineageReferenceObject: PTRLIFI_ROUNDING_AMT
        covMinAmt:
          title: Coverage Minimum Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_COV_MIN_AMT"
          x-lineageReferenceObject: PTRLIFI_COV_MIN_AMT
        bdplCode:
          title: Plan
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRLIFI_BDPL_CODE"
          x-lineageReferenceObject: PTRLIFI_BDPL_CODE
        inclSecJobInd:
          title: Secondary
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_SEC_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_SEC_JOB_IND
        roundingInd:
          title: Rounding
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_ROUNDING_IND"
          x-lineageReferenceObject: PTRLIFI_ROUNDING_IND
        inclPrimaryJobInd:
          title: Primary
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_PRIMARY_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_PRIMARY_JOB_IND
        emplEmprInd:
          title: Deduction Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_EMPL_EMPR_IND"
          x-lineageReferenceObject: PTRLIFI_EMPL_EMPR_IND
      x-lineageReferenceObject: PTRLIFI
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    life-insurance-rule-1.0.0_qapi_post:
      type: object
      properties:
        bdcaCode:
          title: Benefit or Deduction
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRLIFI_BDCA_CODE"
          x-lineageReferenceObject: PTRLIFI_BDCA_CODE
        inclPrimaryJobInd:
          title: Primary
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_PRIMARY_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_PRIMARY_JOB_IND
        inclSecJobInd:
          title: Secondary
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_SEC_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_SEC_JOB_IND
        inclOverloadJobInd:
          title: Overload
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_OVERLOAD_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_OVERLOAD_JOB_IND
        covMinAmt:
          title: Coverage Minimum Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_COV_MIN_AMT"
          x-lineageReferenceObject: PTRLIFI_COV_MIN_AMT
        bdplCode:
          title: Plan
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRLIFI_BDPL_CODE"
          x-lineageReferenceObject: PTRLIFI_BDPL_CODE
        roundingInd:
          title: Rounding
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_ROUNDING_IND"
          x-lineageReferenceObject: PTRLIFI_ROUNDING_IND
        covMaxAmt:
          title: Coverage Maximum Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_COV_MAX_AMT"
          x-lineageReferenceObject: PTRLIFI_COV_MAX_AMT
        emplEmprInd:
          title: Deduction Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_EMPL_EMPR_IND"
          x-lineageReferenceObject: PTRLIFI_EMPL_EMPR_IND
        roundingAmt:
          title: Coverage Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_ROUNDING_AMT"
          x-lineageReferenceObject: PTRLIFI_ROUNDING_AMT
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRLIFI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRLIFI_ACTIVITY_DATE
    life-insurance-rule-1.0.0_get_response:
      required:
        - activityDate
        - bdcaCode
        - covMaxAmt
        - covMinAmt
        - emplEmprInd
        - roundingAmt
        - roundingInd
      type: object
      properties:
        inclOverloadJobInd:
          title: Overload
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_OVERLOAD_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_OVERLOAD_JOB_IND
        covMaxAmt:
          title: Coverage Maximum Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_COV_MAX_AMT"
          x-lineageReferenceObject: PTRLIFI_COV_MAX_AMT
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRLIFI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRLIFI_ACTIVITY_DATE
        bdcaCode:
          title: Benefit or Deduction
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRLIFI_BDCA_CODE"
          x-lineageReferenceObject: PTRLIFI_BDCA_CODE
        roundingAmt:
          title: Coverage Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_ROUNDING_AMT"
          x-lineageReferenceObject: PTRLIFI_ROUNDING_AMT
        bdplCode:
          title: Plan
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRLIFI_BDPL_CODE"
          x-lineageReferenceObject: PTRLIFI_BDPL_CODE
        covMinAmt:
          title: Coverage Minimum Amount
          maxLength: 14
          type: number
          description: "Lineage reference object : PTRLIFI_COV_MIN_AMT"
          x-lineageReferenceObject: PTRLIFI_COV_MIN_AMT
        inclSecJobInd:
          title: Secondary
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_SEC_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_SEC_JOB_IND
        roundingInd:
          title: Rounding
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_ROUNDING_IND"
          x-lineageReferenceObject: PTRLIFI_ROUNDING_IND
        emplEmprInd:
          title: Deduction Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_EMPL_EMPR_IND"
          x-lineageReferenceObject: PTRLIFI_EMPL_EMPR_IND
        inclPrimaryJobInd:
          title: Primary
          maxLength: 1
          type: string
          description: "Lineage reference object : PTRLIFI_INCL_PRIMARY_JOB_IND"
          x-lineageReferenceObject: PTRLIFI_INCL_PRIMARY_JOB_IND
      x-lineageReferenceObject: ptrlifi
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
