openapi: 3.0.0
info:
  title: social-economic-identity-report-codes
  description: API for GTVSEIR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: GTVSEIR
  x-source-domain: Foundation
  x-source-title: Social Economic Identity Report
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/social-economic-identity-report-codes:
    get:
      tags:
        - social-economic-identity-report-codes
      summary: Return resources from GTVSEIR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_ACTIVITY_DATE
        - name: code
          in: query
          description: Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_CODE
        - name: dataOrigin
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_DATA_ORIGIN
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_DESC
        - name: surrogateId
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_SURROGATE_ID
        - name: userId
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_USER_ID
        - name: version
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_VERSION
        - name: vpdiCode
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GTVSEIR_VPDI_CODE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/social-economic-identity-report-codes-1.0.0_get_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/social-economic-identity-report-codes:
    post:
      tags:
        - social-economic-identity-report-codes QAPI (Query by POST)
      summary: Return resources from GTVSEIR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/social-economic-identity-report-codes-1.0.0_get_req\
                uest"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/social-economic-identity-report-codes-1.0.0_get_res\
                    ponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    social-economic-identity-report-codes-1.0.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : GTVSEIR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVSEIR_ACTIVITY_DATE
        code:
          title: Code
          type: string
          description: "Lineage reference object : GTVSEIR_CODE"
          x-lineageReferenceObject: GTVSEIR_CODE
        surrogateId:
          type: number
          description: "Lineage reference object : GTVSEIR_SURROGATE_ID"
          x-lineageReferenceObject: GTVSEIR_SURROGATE_ID
        dataOrigin:
          type: string
          description: "Lineage reference object : GTVSEIR_DATA_ORIGIN"
          x-lineageReferenceObject: GTVSEIR_DATA_ORIGIN
        vpdiCode:
          type: string
          description: "Lineage reference object : GTVSEIR_VPDI_CODE"
          x-lineageReferenceObject: GTVSEIR_VPDI_CODE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVSEIR_USER_ID"
          x-lineageReferenceObject: GTVSEIR_USER_ID
        version:
          type: number
          description: "Lineage reference object : GTVSEIR_VERSION"
          x-lineageReferenceObject: GTVSEIR_VERSION
        desc:
          title: Description
          type: string
          description: "Lineage reference object : GTVSEIR_DESC"
          x-lineageReferenceObject: GTVSEIR_DESC
      x-lineageReferenceObject: gtvseir
    social-economic-identity-report-codes-1.0.0_qapi_post:
      type: object
      properties:
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : GTVSEIR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVSEIR_ACTIVITY_DATE
        code:
          title: Code
          type: string
          description: "Lineage reference object : GTVSEIR_CODE"
          x-lineageReferenceObject: GTVSEIR_CODE
        dataOrigin:
          type: string
          description: "Lineage reference object : GTVSEIR_DATA_ORIGIN"
          x-lineageReferenceObject: GTVSEIR_DATA_ORIGIN
        desc:
          title: Description
          type: string
          description: "Lineage reference object : GTVSEIR_DESC"
          x-lineageReferenceObject: GTVSEIR_DESC
        surrogateId:
          type: number
          description: "Lineage reference object : GTVSEIR_SURROGATE_ID"
          x-lineageReferenceObject: GTVSEIR_SURROGATE_ID
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVSEIR_USER_ID"
          x-lineageReferenceObject: GTVSEIR_USER_ID
        version:
          type: number
          description: "Lineage reference object : GTVSEIR_VERSION"
          x-lineageReferenceObject: GTVSEIR_VERSION
        vpdiCode:
          type: string
          description: "Lineage reference object : GTVSEIR_VPDI_CODE"
          x-lineageReferenceObject: GTVSEIR_VPDI_CODE
    social-economic-identity-report-codes-1.0.0_get_request:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : GTVSEIR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GTVSEIR_ACTIVITY_DATE
        code:
          title: Code
          type: string
          description: "Lineage reference object : GTVSEIR_CODE"
          x-lineageReferenceObject: GTVSEIR_CODE
        surrogateId:
          type: number
          description: "Lineage reference object : GTVSEIR_SURROGATE_ID"
          x-lineageReferenceObject: GTVSEIR_SURROGATE_ID
        dataOrigin:
          type: string
          description: "Lineage reference object : GTVSEIR_DATA_ORIGIN"
          x-lineageReferenceObject: GTVSEIR_DATA_ORIGIN
        vpdiCode:
          type: string
          description: "Lineage reference object : GTVSEIR_VPDI_CODE"
          x-lineageReferenceObject: GTVSEIR_VPDI_CODE
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : GTVSEIR_USER_ID"
          x-lineageReferenceObject: GTVSEIR_USER_ID
        version:
          type: number
          description: "Lineage reference object : GTVSEIR_VERSION"
          x-lineageReferenceObject: GTVSEIR_VERSION
        desc:
          title: Description
          type: string
          description: "Lineage reference object : GTVSEIR_DESC"
          x-lineageReferenceObject: GTVSEIR_DESC
      x-lineageReferenceObject: GTVSEIR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
