openapi: 3.0.0
info:
  title: major-minor-concentration-codes
  description: API for STVMAJR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: STVMAJR
  x-source-domain: Student
  x-source-title: Major, Minor, Concentration Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/major-minor-concentration-codes:
    get:
      tags:
        - major-minor-concentration-codes
      summary: Return resources from STVMAJR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_ACTIVITY_DATE
        - name: aidEligibilityInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_AID_ELIGIBILITY_IND
        - name: cipcCode
          in: query
          description: CIPC
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_CIPC_CODE
        - name: code
          in: query
          description: Major Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_CODE
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_DESC
        - name: occupationInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_OCCUPATION_IND
        - name: sevisEquiv
          in: query
          description: SEVIS Equivalent
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_SEVIS_EQUIV
        - name: systemReqInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_SYSTEM_REQ_IND
        - name: validConcentratnInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_VALID_CONCENTRATN_IND
        - name: validMajorInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_VALID_MAJOR_IND
        - name: validMinorInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_VALID_MINOR_IND
        - name: vrMsgNo
          in: query
          description: Voice Response Message Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVMAJR_VR_MSG_NO
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/major-minor-concentration-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/major-minor-concentration-codes:
    post:
      tags:
        - major-minor-concentration-codes QAPI (Query by POST)
      summary: Return resources from STVMAJR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/major-minor-concentration-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/major-minor-concentration-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    major-minor-concentration-codes-1.0.0_qapi_post:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVMAJR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVMAJR_ACTIVITY_DATE
        aidEligibilityInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_AID_ELIGIBILITY_IND"
          x-lineageReferenceObject: STVMAJR_AID_ELIGIBILITY_IND
        cipcCode:
          title: CIPC
          maxLength: 30
          type: string
          description: "Lineage reference object : STVMAJR_CIPC_CODE, Lookup lineage
            reference object : stvcipc"
          x-lineageReferenceObject: STVMAJR_CIPC_CODE
          x-lineageLookupReferenceObject: stvcipc
        code:
          title: Major Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVMAJR_CODE"
          x-lineageReferenceObject: STVMAJR_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVMAJR_DESC"
          x-lineageReferenceObject: STVMAJR_DESC
        occupationInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_OCCUPATION_IND"
          x-lineageReferenceObject: STVMAJR_OCCUPATION_IND
        sevisEquiv:
          title: SEVIS Equivalent
          maxLength: 6
          type: string
          description: "Lineage reference object : STVMAJR_SEVIS_EQUIV"
          x-lineageReferenceObject: STVMAJR_SEVIS_EQUIV
        systemReqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_SYSTEM_REQ_IND"
          x-lineageReferenceObject: STVMAJR_SYSTEM_REQ_IND
        validConcentratnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_CONCENTRATN_IND"
          x-lineageReferenceObject: STVMAJR_VALID_CONCENTRATN_IND
        validMajorInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_MAJOR_IND"
          x-lineageReferenceObject: STVMAJR_VALID_MAJOR_IND
        validMinorInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_MINOR_IND"
          x-lineageReferenceObject: STVMAJR_VALID_MINOR_IND
        vrMsgNo:
          title: Voice Response Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : STVMAJR_VR_MSG_NO"
          x-lineageReferenceObject: STVMAJR_VR_MSG_NO
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    major-minor-concentration-codes-1.0.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        cipcCode:
          title: CIPC
          maxLength: 30
          type: string
          description: "Lineage reference object : STVMAJR_CIPC_CODE, Lookup lineage
            reference object : stvcipc"
          x-lineageReferenceObject: STVMAJR_CIPC_CODE
          x-lineageLookupReferenceObject: stvcipc
        occupationInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_OCCUPATION_IND"
          x-lineageReferenceObject: STVMAJR_OCCUPATION_IND
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVMAJR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVMAJR_ACTIVITY_DATE
        code:
          title: Major Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVMAJR_CODE"
          x-lineageReferenceObject: STVMAJR_CODE
        systemReqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_SYSTEM_REQ_IND"
          x-lineageReferenceObject: STVMAJR_SYSTEM_REQ_IND
        aidEligibilityInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_AID_ELIGIBILITY_IND"
          x-lineageReferenceObject: STVMAJR_AID_ELIGIBILITY_IND
        validMajorInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_MAJOR_IND"
          x-lineageReferenceObject: STVMAJR_VALID_MAJOR_IND
        validConcentratnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_CONCENTRATN_IND"
          x-lineageReferenceObject: STVMAJR_VALID_CONCENTRATN_IND
        vrMsgNo:
          title: Voice Response Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : STVMAJR_VR_MSG_NO"
          x-lineageReferenceObject: STVMAJR_VR_MSG_NO
        sevisEquiv:
          title: SEVIS Equivalent
          maxLength: 6
          type: string
          description: "Lineage reference object : STVMAJR_SEVIS_EQUIV"
          x-lineageReferenceObject: STVMAJR_SEVIS_EQUIV
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVMAJR_DESC"
          x-lineageReferenceObject: STVMAJR_DESC
        validMinorInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_MINOR_IND"
          x-lineageReferenceObject: STVMAJR_VALID_MINOR_IND
      x-lineageReferenceObject: stvmajr
    major-minor-concentration-codes-1.0.0_get_request:
      required:
        - code
        - desc
      type: object
      properties:
        cipcCode:
          title: CIPC
          maxLength: 30
          type: string
          description: "Lineage reference object : STVMAJR_CIPC_CODE, Lookup lineage
            reference object : stvcipc"
          x-lineageReferenceObject: STVMAJR_CIPC_CODE
          x-lineageLookupReferenceObject: stvcipc
        occupationInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_OCCUPATION_IND"
          x-lineageReferenceObject: STVMAJR_OCCUPATION_IND
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVMAJR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVMAJR_ACTIVITY_DATE
        code:
          title: Major Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVMAJR_CODE"
          x-lineageReferenceObject: STVMAJR_CODE
        systemReqInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_SYSTEM_REQ_IND"
          x-lineageReferenceObject: STVMAJR_SYSTEM_REQ_IND
        aidEligibilityInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_AID_ELIGIBILITY_IND"
          x-lineageReferenceObject: STVMAJR_AID_ELIGIBILITY_IND
        validMajorInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_MAJOR_IND"
          x-lineageReferenceObject: STVMAJR_VALID_MAJOR_IND
        validConcentratnInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_CONCENTRATN_IND"
          x-lineageReferenceObject: STVMAJR_VALID_CONCENTRATN_IND
        vrMsgNo:
          title: Voice Response Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : STVMAJR_VR_MSG_NO"
          x-lineageReferenceObject: STVMAJR_VR_MSG_NO
        sevisEquiv:
          title: SEVIS Equivalent
          maxLength: 6
          type: string
          description: "Lineage reference object : STVMAJR_SEVIS_EQUIV"
          x-lineageReferenceObject: STVMAJR_SEVIS_EQUIV
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVMAJR_DESC"
          x-lineageReferenceObject: STVMAJR_DESC
        validMinorInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVMAJR_VALID_MINOR_IND"
          x-lineageReferenceObject: STVMAJR_VALID_MINOR_IND
      x-lineageReferenceObject: STVMAJR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
