openapi: 3.0.0
info:
  title: contract-person
  description: API for TSICONT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TSICONT
  x-source-domain: Student
  x-source-title: Contract Person Query
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/contract-person:
    get:
      tags:
        - contract-person
      summary: Return resources from TSICONT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: contractNumber
          in: query
          required: false
          schema:
            type: string
        - name: keyblocTermCode
          in: query
          required: false
          schema:
            type: string
        - name: tbvcstuStuId
          in: query
          description: ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_STU_ID
        - name: tbvcstuStuName
          in: query
          description: Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_STU_NAME
        - name: tbvcstuAuthInd
          in: query
          description: Authorize
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_AUTH_IND
        - name: tbvcstuAuthNumber
          in: query
          description: Authorization Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_AUTH_NUMBER
        - name: tbvcstuContractPriority
          in: query
          description: Priority
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_CONTRACT_PRIORITY
        - name: tbvcstuDelInd
          in: query
          description: Delete Indicator
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_DEL_IND
        - name: tbvcstuActivityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBVCSTU_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-person-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/contract-person:
    post:
      tags:
        - contract-person QAPI (Query by POST)
      summary: Return resources from TSICONT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/contract-person-1.0.0_get_request"
            example:
              tbvcstuStuId: HOSFA001
              keyblocTermCode: 201410
              contractNumber: 1
              id: HOSR54321
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-person-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    contract-person-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        contractNumber:
          type: string
        keyblocTermCode:
          type: string
        tbvcstuStuId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : TBVCSTU_STU_ID"
          x-lineageReferenceObject: TBVCSTU_STU_ID
        tbvcstuStuName:
          title: Name
          maxLength: 183
          type: string
          description: "Lineage reference object : TBVCSTU_STU_NAME"
          x-lineageReferenceObject: TBVCSTU_STU_NAME
        tbvcstuAuthInd:
          title: Authorize
          maxLength: 1
          type: string
          description: "Lineage reference object : TBVCSTU_AUTH_IND"
          x-lineageReferenceObject: TBVCSTU_AUTH_IND
        tbvcstuAuthNumber:
          title: Authorization Number
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVCSTU_AUTH_NUMBER"
          x-lineageReferenceObject: TBVCSTU_AUTH_NUMBER
        tbvcstuContractPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBVCSTU_CONTRACT_PRIORITY"
          x-lineageReferenceObject: TBVCSTU_CONTRACT_PRIORITY
        tbvcstuDelInd:
          title: Delete Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : TBVCSTU_DEL_IND"
          x-lineageReferenceObject: TBVCSTU_DEL_IND
        tbvcstuActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVCSTU_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TBVCSTU_ACTIVITY_DATE
    contract-person-1.0.0_get_response:
      required:
        - tbvcstuContractPriority
      type: object
      properties:
        tbvcstuStuId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : TBVCSTU_STU_ID"
          x-lineageReferenceObject: TBVCSTU_STU_ID
        tbvcstuDelInd:
          title: Delete Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : TBVCSTU_DEL_IND"
          x-lineageReferenceObject: TBVCSTU_DEL_IND
        tbvcstuStuName:
          title: Name
          maxLength: 183
          type: string
          description: "Lineage reference object : TBVCSTU_STU_NAME"
          x-lineageReferenceObject: TBVCSTU_STU_NAME
        tbvcstuAuthNumber:
          title: Authorization Number
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVCSTU_AUTH_NUMBER"
          x-lineageReferenceObject: TBVCSTU_AUTH_NUMBER
        tbvcstuActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVCSTU_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TBVCSTU_ACTIVITY_DATE
        tbvcstuContractPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBVCSTU_CONTRACT_PRIORITY"
          x-lineageReferenceObject: TBVCSTU_CONTRACT_PRIORITY
        tbvcstuAuthInd:
          title: Authorize
          maxLength: 1
          type: string
          description: "Lineage reference object : TBVCSTU_AUTH_IND"
          x-lineageReferenceObject: TBVCSTU_AUTH_IND
      x-lineageReferenceObject: tbvcstu2
    contract-person-1.0.0_get_request:
      required:
        - tbvcstuContractPriority
      type: object
      properties:
        tbvcstuStuId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : TBVCSTU_STU_ID"
          x-lineageReferenceObject: TBVCSTU_STU_ID
        keyblocTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCode
          x-lineageLookupReferenceObject: stvterm
        tbvcstuDelInd:
          title: Delete Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : TBVCSTU_DEL_IND"
          x-lineageReferenceObject: TBVCSTU_DEL_IND
        tbvcstuStuName:
          title: Name
          maxLength: 183
          type: string
          description: "Lineage reference object : TBVCSTU_STU_NAME"
          x-lineageReferenceObject: TBVCSTU_STU_NAME
        tbvcstuAuthNumber:
          title: Authorization Number
          maxLength: 30
          type: string
          description: "Lineage reference object : TBVCSTU_AUTH_NUMBER"
          x-lineageReferenceObject: TBVCSTU_AUTH_NUMBER
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Lineage reference object : contractNumber"
          x-lineageReferenceObject: contractNumber
        id:
          title: Contract ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        tbvcstuActivityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TBVCSTU_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TBVCSTU_ACTIVITY_DATE
        tbvcstuContractPriority:
          title: Priority
          maxLength: 2
          type: number
          description: "Lineage reference object : TBVCSTU_CONTRACT_PRIORITY"
          x-lineageReferenceObject: TBVCSTU_CONTRACT_PRIORITY
        tbvcstuAuthInd:
          title: Authorize
          maxLength: 1
          type: string
          description: "Lineage reference object : TBVCSTU_AUTH_IND"
          x-lineageReferenceObject: TBVCSTU_AUTH_IND
      x-lineageReferenceObject: TBVCSTU2
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
