openapi: 3.0.0
info:
  title: Currency ISO Codes
  description: The valid list of ISO 4217 currency codes.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/currency-iso-codes:
    get:
      summary: Return all resources from GTVSCODS
      description: Returns a paged listing of all the currency ISO code records from
        GTVSCODS table where GTVSCODS_ISO_STD is 4217.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_CURRENCY_ISO_CODES
      tags:
        - currency-iso-codes
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-currency-iso-codes.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/currency-iso-codes/{id}:
    get:
      summary: Return the requested resource from GTVSCODS
      description: Return the single currency ISO code record with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_CURRENCY_ISO_CODES
      tags:
        - currency-iso-codes
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Currency ISO Codes for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-currency-iso-codes.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-currency-iso-codes.json:
      title: Currency ISO Codes
      description: The valid list of ISO 4217 currency codes.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the currency ISO code.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GTVSCOD_GUID(GTVSCOD)
          x-lineageDerivedLogic: For the GTVSCOD_ELEMENT_ID '0100' and GTVSCOD_CODE, display all the records from GTVSCODS where GTVSCODS_ISO_STD is 4217.
        title:
          title: Title
          description: The full name of the currency represented by the ISO code.
          type: string
          minLength: 1
          x-lineageReferenceObject: GTVSCOD_DESC(GTVSCOD)
        isoCode:
          title: ISO Code
          description: The ISO 4217 code associated with the currency.
          type: string
          minLength: 1
          x-lineageReferenceObject: GTVSCOD_CODE(GTVSCOD)
        status:
          title: Status
          description: An indicator as to whether the ISO code is currently in use or was
            previously used to represent a currency.
          x-lineageReferenceObject: derived  
          x-lineageDerivedLogic: Always display as 'active'.
          enum:
            - active
            - inactive
          type: string
      required:
        - id
        - title
        - isoCode
        - status
      additionalProperties: false

