openapi: 3.0.0
info:
  title: budget-type-codes
  description: API for RTVBTYP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: RTVBTYP
  x-source-domain: Financial Aid
  x-source-title: Budget Type Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/budget-type-codes:
    get:
      tags:
        - budget-type-codes
      summary: Return resources from RTVBTYP
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_ACTIVITY_DATE
        - name: campInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_CAMP_IND
        - name: code
          in: query
          description: Type Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_CODE
        - name: defaultTfcInd
          in: query
          description: Default EFC
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_DEFAULT_TFC_IND
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_DESC
        - name: instInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_INST_IND
        - name: othrInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_OTHR_IND
        - name: pellInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_PELL_IND
        - name: statInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: RTVBTYP_STAT_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/budget-type-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/budget-type-codes:
    post:
      tags:
        - budget-type-codes QAPI (Query by POST)
      summary: Return resources from RTVBTYP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/budget-type-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/budget-type-codes-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    budget-type-codes-1.0.0_get_response:
      required:
        - code
        - defaultTfcInd
        - desc
      type: object
      properties:
        statInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_STAT_IND"
          x-lineageReferenceObject: RTVBTYP_STAT_IND
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RTVBTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RTVBTYP_ACTIVITY_DATE
        code:
          title: Type Code
          maxLength: 4
          type: string
          description: "Lineage reference object : RTVBTYP_CODE"
          x-lineageReferenceObject: RTVBTYP_CODE
        instInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_INST_IND"
          x-lineageReferenceObject: RTVBTYP_INST_IND
        othrInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_OTHR_IND"
          x-lineageReferenceObject: RTVBTYP_OTHR_IND
        campInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_CAMP_IND"
          x-lineageReferenceObject: RTVBTYP_CAMP_IND
        defaultTfcInd:
          title: Default EFC
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_DEFAULT_TFC_IND"
          x-lineageReferenceObject: RTVBTYP_DEFAULT_TFC_IND
        pellInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_PELL_IND"
          x-lineageReferenceObject: RTVBTYP_PELL_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVBTYP_DESC"
          x-lineageReferenceObject: RTVBTYP_DESC
      x-lineageReferenceObject: rtvbtyp
    budget-type-codes-1.0.0_qapi_post:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RTVBTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RTVBTYP_ACTIVITY_DATE
        campInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_CAMP_IND"
          x-lineageReferenceObject: RTVBTYP_CAMP_IND
        code:
          title: Type Code
          maxLength: 4
          type: string
          description: "Lineage reference object : RTVBTYP_CODE"
          x-lineageReferenceObject: RTVBTYP_CODE
        defaultTfcInd:
          title: Default EFC
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_DEFAULT_TFC_IND"
          x-lineageReferenceObject: RTVBTYP_DEFAULT_TFC_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVBTYP_DESC"
          x-lineageReferenceObject: RTVBTYP_DESC
        instInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_INST_IND"
          x-lineageReferenceObject: RTVBTYP_INST_IND
        othrInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_OTHR_IND"
          x-lineageReferenceObject: RTVBTYP_OTHR_IND
        pellInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_PELL_IND"
          x-lineageReferenceObject: RTVBTYP_PELL_IND
        statInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_STAT_IND"
          x-lineageReferenceObject: RTVBTYP_STAT_IND
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    budget-type-codes-1.0.0_get_request:
      required:
        - code
        - defaultTfcInd
        - desc
      type: object
      properties:
        statInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_STAT_IND"
          x-lineageReferenceObject: RTVBTYP_STAT_IND
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : RTVBTYP_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: RTVBTYP_ACTIVITY_DATE
        code:
          title: Type Code
          maxLength: 4
          type: string
          description: "Lineage reference object : RTVBTYP_CODE"
          x-lineageReferenceObject: RTVBTYP_CODE
        instInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_INST_IND"
          x-lineageReferenceObject: RTVBTYP_INST_IND
        othrInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_OTHR_IND"
          x-lineageReferenceObject: RTVBTYP_OTHR_IND
        campInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_CAMP_IND"
          x-lineageReferenceObject: RTVBTYP_CAMP_IND
        defaultTfcInd:
          title: Default EFC
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_DEFAULT_TFC_IND"
          x-lineageReferenceObject: RTVBTYP_DEFAULT_TFC_IND
        pellInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : RTVBTYP_PELL_IND"
          x-lineageReferenceObject: RTVBTYP_PELL_IND
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : RTVBTYP_DESC"
          x-lineageReferenceObject: RTVBTYP_DESC
      x-lineageReferenceObject: RTVBTYP
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
