openapi: 3.0.0
info:
  title: admission-request-checklist-codes
  description: API for STVADMR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: STVADMR
  x-source-domain: Student
  x-source-title: Admission Request Checklist Code Validation
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/admission-request-checklist-codes:
    get:
      tags:
        - admission-request-checklist-codes
      summary: Return resources from STVADMR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_ACTIVITY_DATE
        - name: code
          in: query
          description: Request Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_CODE
        - name: desc
          in: query
          description: Description
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_DESC
        - name: dispWebInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_DISP_WEB_IND
        - name: tableName
          in: query
          description: Cross Reference Table Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_TABLE_NAME
        - name: vrEligInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_VR_ELIG_IND
        - name: vrMsgNo
          in: query
          description: Voice Response Message Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: STVADMR_VR_MSG_NO
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/admission-request-checklist-codes-1.0.0_get_respons\
                    e"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/admission-request-checklist-codes:
    post:
      tags:
        - admission-request-checklist-codes QAPI (Query by POST)
      summary: Return resources from STVADMR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/admission-request-checklist-codes-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/admission-request-checklist-codes-1.0.0_get_respons\
                    e"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    admission-request-checklist-codes-1.0.0_get_request:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVADMR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVADMR_ACTIVITY_DATE
        code:
          title: Request Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVADMR_CODE"
          x-lineageReferenceObject: STVADMR_CODE
        dispWebInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVADMR_DISP_WEB_IND"
          x-lineageReferenceObject: STVADMR_DISP_WEB_IND
        vrEligInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVADMR_VR_ELIG_IND"
          x-lineageReferenceObject: STVADMR_VR_ELIG_IND
        vrMsgNo:
          title: Voice Response Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : STVADMR_VR_MSG_NO"
          x-lineageReferenceObject: STVADMR_VR_MSG_NO
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVADMR_DESC"
          x-lineageReferenceObject: STVADMR_DESC
        tableName:
          title: Cross Reference Table Name
          maxLength: 7
          type: string
          description: "Lineage reference object : STVADMR_TABLE_NAME"
          x-lineageReferenceObject: STVADMR_TABLE_NAME
      x-lineageReferenceObject: STVADMR
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    admission-request-checklist-codes-1.0.0_get_response:
      required:
        - code
        - desc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVADMR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVADMR_ACTIVITY_DATE
        code:
          title: Request Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVADMR_CODE"
          x-lineageReferenceObject: STVADMR_CODE
        dispWebInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVADMR_DISP_WEB_IND"
          x-lineageReferenceObject: STVADMR_DISP_WEB_IND
        vrEligInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVADMR_VR_ELIG_IND"
          x-lineageReferenceObject: STVADMR_VR_ELIG_IND
        vrMsgNo:
          title: Voice Response Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : STVADMR_VR_MSG_NO"
          x-lineageReferenceObject: STVADMR_VR_MSG_NO
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVADMR_DESC"
          x-lineageReferenceObject: STVADMR_DESC
        tableName:
          title: Cross Reference Table Name
          maxLength: 7
          type: string
          description: "Lineage reference object : STVADMR_TABLE_NAME"
          x-lineageReferenceObject: STVADMR_TABLE_NAME
      x-lineageReferenceObject: stvadmr
    admission-request-checklist-codes-1.0.0_qapi_post:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : STVADMR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: STVADMR_ACTIVITY_DATE
        code:
          title: Request Code
          maxLength: 4
          type: string
          description: "Lineage reference object : STVADMR_CODE"
          x-lineageReferenceObject: STVADMR_CODE
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : STVADMR_DESC"
          x-lineageReferenceObject: STVADMR_DESC
        dispWebInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVADMR_DISP_WEB_IND"
          x-lineageReferenceObject: STVADMR_DISP_WEB_IND
        tableName:
          title: Cross Reference Table Name
          maxLength: 7
          type: string
          description: "Lineage reference object : STVADMR_TABLE_NAME"
          x-lineageReferenceObject: STVADMR_TABLE_NAME
        vrEligInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : STVADMR_VR_ELIG_IND"
          x-lineageReferenceObject: STVADMR_VR_ELIG_IND
        vrMsgNo:
          title: Voice Response Message Number
          maxLength: 6
          type: number
          description: "Lineage reference object : STVADMR_VR_MSG_NO"
          x-lineageReferenceObject: STVADMR_VR_MSG_NO
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
