openapi: 3.0.0
info:
  title: registration-fee-assessment-audit-history
  description: API for SFAFAUD administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SFAFAUD
  x-source-domain: Student
  x-source-title: Registration Fee Assessment Audit History
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/registration-fee-assessment-audit-history:
    get:
      tags:
        - registration-fee-assessment-audit-history
      summary: Return resources from SFAFAUD
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          description: Term
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_TERM_CODE
        - name: activityDay
          in: query
          description: Activity Day
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_DAY
        - name: activityTime
          in: query
          description: Time
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_TIME
        - name: seqno
          in: query
          description: Sequence Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_SEQNO
        - name: detlCode
          in: query
          description: Detail Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_DETL_CODE
        - name: dcatCode
          in: query
          description: Detail Code Category
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_DCAT_CODE
        - name: accdTranNumber
          in: query
          description: Account Transaction Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_ACCD_TRAN_NUMBER
        - name: charge
          in: query
          description: Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SFVFAUD_CHARGE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/registration-fee-assessment-audit-history-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/registration-fee-assessment-audit-history:
    post:
      tags:
        - registration-fee-assessment-audit-history QAPI (Query by POST)
      summary: Return resources from SFAFAUD
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/registration-fee-assessment-audit-history-1.0.0_get\
                _request"
            example:
              id: FASS30001
              termCode: 201910
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/registration-fee-assessment-audit-history-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    registration-fee-assessment-audit-history-1.0.0_get_response:
      required:
        - refundBy
        - assessmentSource
        - assessByCourseInd
        - dcatCode
        - detlCode
        - seqno
        - termCode
        - userId
      type: object
      properties:
        note:
          title: Audit Note
          maxLength: 120
          type: string
          description: "Lineage reference object : SFVFAUD_NOTE"
          x-lineageReferenceObject: SFVFAUD_NOTE
        dispPerCredCharge:
          title: At
          maxLength: 14
          type: number
        totPerCredCharge:
          title: Per Hour Charge
          maxLength: 14
          type: number
          description: "Lineage reference object : SFVFAUD_TOT_PER_CRED_CHARGE"
          x-lineageReferenceObject: SFVFAUD_TOT_PER_CRED_CHARGE
        detlCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : SFVFAUD_DETL_CODE"
          x-lineageReferenceObject: SFVFAUD_DETL_CODE
        estsCode:
          title: Enrollment Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SFVFAUD_ESTS_CODE"
          x-lineageReferenceObject: SFVFAUD_ESTS_CODE
        estsDate:
          title: Enrollment Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFVFAUD_ESTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFVFAUD_ESTS_DATE
        flatFeeAmount:
          title: Flat Fee Charge
          maxLength: 14
          type: number
          description: "Lineage reference object : SFVFAUD_FLAT_FEE_AMOUNT"
          x-lineageReferenceObject: SFVFAUD_FLAT_FEE_AMOUNT
        rstsCode:
          title: Registration Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SFVFAUD_RSTS_CODE"
          x-lineageReferenceObject: SFVFAUD_RSTS_CODE
        rstsDate:
          title: Registration Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFVFAUD_RSTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFVFAUD_RSTS_DATE
        overloadPerCredCharge:
          title: At
          maxLength: 14
          type: number
        crseOverloadHrs:
          title: Overload Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SFVFAUD_CRSE_OVERLOAD_HRS"
          x-lineageReferenceObject: SFVFAUD_CRSE_OVERLOAD_HRS
        activityDay:
          title: Activity Day
          maxLength: 11
          type: string
          description: "Lineage reference object : SFVFAUD_ACTIVITY_DAY"
          format: date-time
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_DAY
        crn:
          title: CRN
          maxLength: 5
          type: string
          description: "Lineage reference object : SFVFAUD_CRN"
          x-lineageReferenceObject: SFVFAUD_CRN
        refundBy:
          title: Refund By
          maxLength: 30
          type: string
        charge:
          title: Amount
          maxLength: 18
          type: number
          description: "Lineage reference object : SFVFAUD_CHARGE"
          x-lineageReferenceObject: SFVFAUD_CHARGE
        rgfeType:
          title: Rule Type
          maxLength: 16
          type: string
          description: "Lineage reference object : SFVFAUD_RGFE_TYPE"
          x-lineageReferenceObject: SFVFAUD_RGFE_TYPE
        rgfeSeqno:
          title: Rule Sequence Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_RGFE_SEQNO"
          x-lineageReferenceObject: SFVFAUD_RGFE_SEQNO
        seqno:
          title: Sequence Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_SEQNO"
          x-lineageReferenceObject: SFVFAUD_SEQNO
        rgfeRuleValue:
          title: Value
          maxLength: 30
          type: string
          description: "Lineage reference object : SFVFAUD_RGFE_RULE_VALUE"
          x-lineageReferenceObject: SFVFAUD_RGFE_RULE_VALUE
        ruleLiableBillHrs:
          title: Rule Liable Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SFVFAUD_RULE_LIABLE_BILL_HRS"
          x-lineageReferenceObject: SFVFAUD_RULE_LIABLE_BILL_HRS
        activityTime:
          title: Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SFVFAUD_ACTIVITY_TIME"
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_TIME
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SFVFAUD_USER_ID"
          x-lineageReferenceObject: SFVFAUD_USER_ID
        assessByCourseInd:
          title: Assessed by Course
          maxLength: 1
          type: string
          description: "Lineage reference object : SFVFAUD_ASSESS_BY_COURSE_IND"
          x-lineageReferenceObject: SFVFAUD_ASSESS_BY_COURSE_IND
        ruleLiableStudHrs:
          title: Rule Student Hours
          maxLength: 10
          type: number
          description: "Lineage reference object : SFVFAUD_RULE_LIABLE_STUD_HRS"
          x-lineageReferenceObject: SFVFAUD_RULE_LIABLE_STUD_HRS
        dispFromFlatHrs:
          title: Rule Flat Hour Range
          maxLength: 10
          type: number
        dispStudypathName:
          title: Study Path Name
          maxLength: 4000
          type: string
        dcatCode:
          title: Detail Code Category
          maxLength: 3
          type: string
          description: "Lineage reference object : SFVFAUD_DCAT_CODE"
          x-lineageReferenceObject: SFVFAUD_DCAT_CODE
        rgfeRuleValue2:
          title: Value 2
          maxLength: 15
          type: string
          description: "Lineage reference object : SFVFAUD_RGFE_RULE_VALUE_2"
          x-lineageReferenceObject: SFVFAUD_RGFE_RULE_VALUE_2
        accdTranNumber:
          title: Account Transaction Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_ACCD_TRAN_NUMBER"
          x-lineageReferenceObject: SFVFAUD_ACCD_TRAN_NUMBER
        assessmentSource:
          title: Assessment Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SFVFAUD_ASSESSMENT_SOURCE"
          x-lineageReferenceObject: SFVFAUD_ASSESSMENT_SOURCE
        dispToFlatHrs:
          title: "-"
          maxLength: 10
          type: number
        crseOverloadCharge:
          title: Overload Charge
          maxLength: 14
          type: number
          description: "Lineage reference object : SFVFAUD_CRSE_OVERLOAD_CHARGE"
          x-lineageReferenceObject: SFVFAUD_CRSE_OVERLOAD_CHARGE
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SFVFAUD_TERM_CODE"
          x-lineageReferenceObject: SFVFAUD_TERM_CODE
      x-lineageReferenceObject: sfvfaud
    registration-fee-assessment-audit-history-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SFVFAUD_TERM_CODE"
          x-lineageReferenceObject: SFVFAUD_TERM_CODE
        activityDay:
          title: Activity Day
          maxLength: 11
          type: string
          description: "Lineage reference object : SFVFAUD_ACTIVITY_DAY"
          format: date-time
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_DAY
        activityTime:
          title: Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SFVFAUD_ACTIVITY_TIME"
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_TIME
        seqno:
          title: Sequence Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_SEQNO"
          x-lineageReferenceObject: SFVFAUD_SEQNO
        detlCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : SFVFAUD_DETL_CODE"
          x-lineageReferenceObject: SFVFAUD_DETL_CODE
        dcatCode:
          title: Detail Code Category
          maxLength: 3
          type: string
          description: "Lineage reference object : SFVFAUD_DCAT_CODE"
          x-lineageReferenceObject: SFVFAUD_DCAT_CODE
        accdTranNumber:
          title: Account Transaction Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_ACCD_TRAN_NUMBER"
          x-lineageReferenceObject: SFVFAUD_ACCD_TRAN_NUMBER
        charge:
          title: Amount
          maxLength: 18
          type: number
          description: "Lineage reference object : SFVFAUD_CHARGE"
          x-lineageReferenceObject: SFVFAUD_CHARGE
    registration-fee-assessment-audit-history-1.0.0_get_request:
      required:
        - termCode
        - seqno
        - detlCode
        - dcatCode
      type: object
      properties:
        charge:
          title: Amount
          maxLength: 18
          type: number
          description: "Lineage reference object : SFVFAUD_CHARGE"
          x-lineageReferenceObject: SFVFAUD_CHARGE
        seqno:
          title: Sequence Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_SEQNO"
          x-lineageReferenceObject: SFVFAUD_SEQNO
        dcatCode:
          title: Detail Code Category
          maxLength: 3
          type: string
          description: "Lineage reference object : SFVFAUD_DCAT_CODE"
          x-lineageReferenceObject: SFVFAUD_DCAT_CODE
        activityTime:
          title: Time
          maxLength: 30
          type: string
          description: "Lineage reference object : SFVFAUD_ACTIVITY_TIME"
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_TIME
        detlCode:
          title: Detail Code
          maxLength: 4
          type: string
          description: "Lineage reference object : SFVFAUD_DETL_CODE"
          x-lineageReferenceObject: SFVFAUD_DETL_CODE
        accdTranNumber:
          title: Account Transaction Number
          maxLength: 9
          type: number
          description: "Lineage reference object : SFVFAUD_ACCD_TRAN_NUMBER"
          x-lineageReferenceObject: SFVFAUD_ACCD_TRAN_NUMBER
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        activityDay:
          title: Activity Day
          maxLength: 11
          type: string
          description: "Lineage reference object : SFVFAUD_ACTIVITY_DAY"
          format: date-time
          x-lineageReferenceObject: SFVFAUD_ACTIVITY_DAY
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SFVFAUD_TERM_CODE"
          x-lineageReferenceObject: SFVFAUD_TERM_CODE
      x-lineageReferenceObject: SFVFAUD
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
