openapi: 3.0.0
info:
  title: person-search
  description: API for SOAIDEN administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SOAIDEN
  x-source-domain: Student
  x-source-title: Person Search
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/person-search:
    get:
      tags:
        - person-search
      summary: Return resources from SOAIDEN
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          description: ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_ID
        - name: lastName
          in: query
          description: Last Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        - name: firstName
          in: query
          description: First Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        - name: mi
          in: query
          description: Middle Name
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_MI
        - name: birthdate
          in: query
          description: Birth Date
          required: false
          schema:
            type: string
        - name: changeInd
          in: query
          description: Change Indicator
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_CHANGE_IND
        - name: namePrefix
          in: query
          description: Prefix
          required: false
          schema:
            type: string
        - name: nameSuffix
          in: query
          description: Suffix
          required: false
          schema:
            type: string
        - name: ntypCode
          in: query
          description: Name Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/person-search-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/person-search:
    post:
      tags:
        - person-search QAPI (Query by POST)
      summary: Return resources from SOAIDEN
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/person-search-1.0.0_get_request"
            example:
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/person-search-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    person-search-1.0.0_qapi_post:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
        birthdate:
          title: Birth Date
          maxLength: 11
          type: string
          format: date-time
        changeInd:
          title: Change Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SPRIDEN_CHANGE_IND"
          x-lineageReferenceObject: SPRIDEN_CHANGE_IND
        namePrefix:
          title: Prefix
          maxLength: 60
          type: string
        nameSuffix:
          title: Suffix
          maxLength: 60
          type: string
        ntypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage
            reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    person-search-1.0.0_get_request:
      type: object
      properties:
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        changeInd:
          title: Change Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SPRIDEN_CHANGE_IND"
          x-lineageReferenceObject: SPRIDEN_CHANGE_IND
        ntypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage
            reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        birthdate:
          title: Birth Date
          maxLength: 11
          type: string
          format: date-time
        namePrefix:
          title: Prefix
          maxLength: 60
          type: string
        nameSuffix:
          title: Suffix
          maxLength: 60
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
      x-lineageReferenceObject: SPRIDEN
    person-search-1.0.0_get_response:
      type: object
      properties:
        firstName:
          title: First Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_FIRST_NAME"
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
        lastName:
          title: Last Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_LAST_NAME"
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
        changeInd:
          title: Change Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SPRIDEN_CHANGE_IND"
          x-lineageReferenceObject: SPRIDEN_CHANGE_IND
        ntypCode:
          title: Name Type
          maxLength: 30
          type: string
          description: "Lineage reference object : SPRIDEN_NTYP_CODE, Lookup lineage
            reference object : gtvntyp"
          x-lineageReferenceObject: SPRIDEN_NTYP_CODE
          x-lineageLookupReferenceObject: gtvntyp
        birthdate:
          title: Birth Date
          maxLength: 11
          type: string
          format: date-time
        namePrefix:
          title: Prefix
          maxLength: 60
          type: string
        nameSuffix:
          title: Suffix
          maxLength: 60
          type: string
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : SPRIDEN_ID"
          x-lineageReferenceObject: SPRIDEN_ID
        mi:
          title: Middle Name
          maxLength: 60
          type: string
          description: "Lineage reference object : SPRIDEN_MI"
          x-lineageReferenceObject: SPRIDEN_MI
      x-lineageReferenceObject: spriden
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
