openapi: 3.0.0
info:
  title: data-privacy-locked-retention-collections
  description: API for GUARCMC administrative page
  version: 0.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: GUARCMC
  x-source-domain: Foundation
  x-source-title: Data Privacy Locked Retention Collections
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/data-privacy-locked-retention-collections:
    get:
      tags:
        - data-privacy-locked-retention-collections
      summary: Return resources from GUARCMC
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: collection
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GUBRETC_COLLECTION
        - name: desc
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GUBRETC_DESC
        - name: expireDate
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
        - name: status
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GUBRETC_STATUS
        - name: creatorId
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GUBRETC_CREATOR_ID
        - name: comment
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GUBRETC_COMMENT
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-locked-retention-collections-0.1.0_get\
                    _response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - data-privacy-locked-retention-collections
      summary: Updates an existing resource in GUARCMC
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-locked-retention-collections-0.1.0_put\
                _request"
            example:
              criteria.collection: 03ZH01
              comment: Test comment
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-locked-retention-collections-0.1.0_put\
                    _response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/data-privacy-locked-retention-collections:
    post:
      tags:
        - data-privacy-locked-retention-collections QAPI (Query by POST)
      summary: Return resources from GUARCMC
      requestBody:
        content:
          application/vnd.hedtech.integration.v0.1.0+json:
            schema:
              $ref: "#/components/schemas/data-privacy-locked-retention-collections-0.1.0_get\
                _request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v0.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/data-privacy-locked-retention-collections-0.1.0_get\
                    _response"
        "401":
          description: Failure. Unauthorized
        "500":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    data-privacy-locked-retention-collections-0.1.0_get_request:
      type: object
      properties:
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_CREATOR_ID"
          x-lineageReferenceObject: GUBRETC_CREATOR_ID
        expireDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
        comment:
          maxLength: 4000
          type: string
          description: "Lineage reference object : GUBRETC_COMMENT"
          x-lineageReferenceObject: GUBRETC_COMMENT
        collection:
          title: Retention Collection
          maxLength: 10
          type: string
          description: "Lineage reference object : GUBRETC_COLLECTION"
          x-lineageReferenceObject: GUBRETC_COLLECTION
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GUBRETC_DESC"
          x-lineageReferenceObject: GUBRETC_DESC
        status:
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_STATUS"
          x-lineageReferenceObject: GUBRETC_STATUS
      x-lineageReferenceObject: GUBRETC
    data-privacy-locked-retention-collections-0.1.0_put_response:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_ACTIVITY_DATE
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_CREATOR_ID"
          x-lineageReferenceObject: GUBRETC_CREATOR_ID
        comment:
          maxLength: 4000
          type: string
          description: "Lineage reference object : GUBRETC_COMMENT"
          x-lineageReferenceObject: GUBRETC_COMMENT
        expireDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
        collection:
          title: Retention Collection
          maxLength: 10
          type: string
          description: "Lineage reference object : GUBRETC_COLLECTION"
          x-lineageReferenceObject: GUBRETC_COLLECTION
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_USER_ID"
          x-lineageReferenceObject: GUBRETC_USER_ID
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GUBRETC_DESC"
          x-lineageReferenceObject: GUBRETC_DESC
        status:
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_STATUS"
          x-lineageReferenceObject: GUBRETC_STATUS
      x-lineageReferenceObject: gubretc
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    data-privacy-locked-retention-collections-0.1.0_get_response:
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_ACTIVITY_DATE
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_CREATOR_ID"
          x-lineageReferenceObject: GUBRETC_CREATOR_ID
        comment:
          maxLength: 4000
          type: string
          description: "Lineage reference object : GUBRETC_COMMENT"
          x-lineageReferenceObject: GUBRETC_COMMENT
        expireDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
        collection:
          title: Retention Collection
          maxLength: 10
          type: string
          description: "Lineage reference object : GUBRETC_COLLECTION"
          x-lineageReferenceObject: GUBRETC_COLLECTION
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_USER_ID"
          x-lineageReferenceObject: GUBRETC_USER_ID
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GUBRETC_DESC"
          x-lineageReferenceObject: GUBRETC_DESC
        status:
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_STATUS"
          x-lineageReferenceObject: GUBRETC_STATUS
      x-lineageReferenceObject: gubretc
    data-privacy-locked-retention-collections-0.1.0_put_request:
      type: object
      properties:
        criteria.collection:
          title: Retention Collection
          maxLength: 10
          type: string
          description: "Lineage reference object : GUBRETC_COLLECTION"
          x-lineageReferenceObject: GUBRETC_COLLECTION
        criteria.creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_CREATOR_ID"
          x-lineageReferenceObject: GUBRETC_CREATOR_ID
        criteria.status:
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_STATUS"
          x-lineageReferenceObject: GUBRETC_STATUS
        comment:
          maxLength: 4000
          type: string
          description: "Lineage reference object : GUBRETC_COMMENT"
          x-lineageReferenceObject: GUBRETC_COMMENT
        criteria.expireDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
        criteria.comment:
          maxLength: 4000
          type: string
          description: "Lineage reference object : GUBRETC_COMMENT"
          x-lineageReferenceObject: GUBRETC_COMMENT
        criteria.desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GUBRETC_DESC"
          x-lineageReferenceObject: GUBRETC_DESC
      x-lineageReferenceObject: GUBRETC
    data-privacy-locked-retention-collections-0.1.0_qapi_post:
      type: object
      properties:
        collection:
          title: Retention Collection
          maxLength: 10
          type: string
          description: "Lineage reference object : GUBRETC_COLLECTION"
          x-lineageReferenceObject: GUBRETC_COLLECTION
        desc:
          title: Description
          maxLength: 300
          type: string
          description: "Lineage reference object : GUBRETC_DESC"
          x-lineageReferenceObject: GUBRETC_DESC
        expireDate:
          title: Expiration Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GUBRETC_EXPIRE_DATE"
          format: date-time
          x-lineageReferenceObject: GUBRETC_EXPIRE_DATE
        status:
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_STATUS"
          x-lineageReferenceObject: GUBRETC_STATUS
        creatorId:
          title: Creator ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GUBRETC_CREATOR_ID"
          x-lineageReferenceObject: GUBRETC_CREATOR_ID
        comment:
          maxLength: 4000
          type: string
          description: "Lineage reference object : GUBRETC_COMMENT"
          x-lineageReferenceObject: GUBRETC_COMMENT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
