openapi: 3.0.0
info:
  title: Security STP User Assignments
  description: >
    The Security STP User Assignments API provides the list of defined Banner Shared Technology Platform (formerly referred to as MEP) users and their assigned identifiers.


    STP User Assignments can be created, updated or deleted using security-stp-user-assignments-submissions-process.

     Note: To maintain strict access control, the required security object must be assigned directly to individual users. 
    Assignment via security classes is not supported for this API.


  version: 1.0.0
  x-api-type: erp
  x-release-status: ga
  x-source-system: banner
  x-audience: all
  x-source-domain: Foundation
  x-source-name: GURUSRI
  x-source-title: null
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/security-stp-user-assignments:
    get:
      tags:
      - security-stp-user-assignments
      summary: Returns Security STP User Assignment details.
      description: Returns resources from GURUSRI.
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          description:  |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object  
          description: >
            ### STP User ID

            Returns all records for the STP User Identifer passed.

            ```

            /security-stp-user-assignments?criteria={"userId":"BSMITH"}

            ```    

            ### STP Identifier

            Returns all records for the STP Identifier passed.

            ```

            /security-stp-user-assignments?criteria={"stpIdentifer":"INST"}

            ``` 

            ### User Default STP Identifier Indicator

            Returns all records for the User Default STP Identifier Indicator passed.

            ```

            /security-stp-user-assignments?criteria={"userDefaultStpIdentifier":true}

            ```             
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/security-stp-user-assignments-1.0.0_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the client’s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_SECURITY_STP_USER_ASSGMT
  /api/security-stp-user-assignments/{id}:
    get:
      summary: Returns the requested resource from GURUSRI.
      description: |
        Returns a record from GURUSRI with the passed in identifier.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SECURITY_STP_USER_ASSGMT
      tags:
        - security-stp-user-assignments
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of the resource for use in all external references.
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v16.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/security-stp-user-assignments-1.0.0_response"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data      
components:
  schemas:
    security-stp-user-assignments-1.0.0_response:
      type: object
      required:
        - id
        - userId
        - stpIdentifier
        - userDefaultStpIdentifier    
      properties:
        id:
          title: STP User Assignment ID
          description: "Unique identifier for the STP User Assignment."
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GURUSRI_GUID
          example: 4feqfc68-3t74-4036-852c-341zz9d5501a          
          maxLength: 36
        userId:
          title: STP User ID
          description: "The Oracle ID or Principal User ID of the STP user."
          type: string
          x-lineageReferenceObject: GURUSRI_VPDI_USER_ID
          example: "BSMITH"
          maxLength: 30  
        stpIdentifier:
          title: STP Identifier Code
          description: "The STP Identifier code."
          type: string
          x-lineageReferenceObject: GURUSRI_VPDI_CODE
          example: "INST"
          maxLength: 6   
          x-lineageLookupReferenceObject: GTVVPDI 
        description:
          title: STP Identifier Description
          description: "Description of the STP Identifier code."
          type: string
          x-lineageReferenceObject: GTVVPDI_DESC
          example: 'Institution'
          maxLength: 30                
        isUserDefaultStpIdentifier:
          title: User Default STP Identifier Indicator
          description: "Indicates the default STP identifier for the user.  Each user must have a default identifier."
          type: boolean
          x-lineageReferenceObject: GURUSRI_USER_DEF_INST_IND
          example: "true"              
        modifiedOn:
          title: Modified On
          maxLength: 11
          type: string
          format: date-time
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          description: "Most current date the record was created or changed."
          x-lineageReferenceObject: GURUSRI_ACTIVITY_DATE
          example: 2024-07-05T04:00:00Z   
        modifiedBy:
          title: Modified By User ID
          maxLength: 30
          type: string
          description: "User who inserted or last updated the data."
          x-lineageReferenceObject: GURUSRI_USER_ID
          example: SYSTEST08                                  
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
              type: object
              properties:
                id:
                  type: string
                  description: The global identifier of the resource in error.
                sourceId:
                  type: string
                  description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
                code:
                  type: string
                  description: The error message code used to describe the error details.
                description:
                  type: string
                  description: The error description used to describe the error details.
                message:
                  type: string
                  description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic