openapi: 3.0.0
info:
  title: ca-faculty-id-term-specific-load-limits
  description: API for SVALOLI administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SVALOLI
  x-source-domain: Student
  x-source-title: Faculty ID/Term-Specific Load Limits (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-faculty-id-term-specific-load-limits:
    get:
      tags:
        - ca-faculty-id-term-specific-load-limits
      summary: Return resources from SVALOLI
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - ca-faculty-id-term-specific-load-limits
      summary: Updates an existing resource in SVALOLI
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_put_r\
                equest"
            example:
              loadLimit: 1.6
              id: 210009506
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_put_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - ca-faculty-id-term-specific-load-limits
      summary: Creates a new resource in SVALOLI
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_post_\
                request"
            example:
              loadLimit: 1.3
              id: 210009506
              termCode: 201410
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_post_\
                    response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-faculty-id-term-specific-load-limits:
    post:
      tags:
        - ca-faculty-id-term-specific-load-limits QAPI (Query by POST)
      summary: Return resources from SVALOLI
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_get_r\
                equest"
            example:
              id: 210009506
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-faculty-id-term-specific-load-limits-1.0.0_get_r\
                    esponse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    ca-faculty-id-term-specific-load-limits-1.0.0_get_request:
      type: object
      properties:
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
    ca-faculty-id-term-specific-load-limits-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-faculty-id-term-specific-load-limits-1.0.0_post_response:
      required:
        - loadLimit
        - termCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SVRLOLI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRLOLI_ACTIVITY_DATE
        sibtermLoadActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBTERM_LOAD_ACTIVE_IND"
          x-lineageReferenceObject: SIBTERM_LOAD_ACTIVE_IND
        stvtermDesc:
          title: Description
          type: string
          description: "Lineage reference object : STVTERM_DESC"
          x-lineageReferenceObject: STVTERM_DESC
        loadLimit:
          title: ID Load Limit For Term (FTE)
          maxLength: 7
          type: number
          description: "Lineage reference object : SVRLOLI_LOAD_LIMIT"
          x-lineageReferenceObject: SVRLOLI_LOAD_LIMIT
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRLOLI_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SVRLOLI_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: svrloli
    ca-faculty-id-term-specific-load-limits-1.0.0_put_request:
      required:
        - criteria.termCode
        - criteria.loadLimit
        - loadLimit
      type: object
      properties:
        criteria.stvtermDesc:
          title: Description
          type: string
          description: "Lineage reference object : STVTERM_DESC"
          x-lineageReferenceObject: STVTERM_DESC
        criteria.activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SVRLOLI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRLOLI_ACTIVITY_DATE
        criteria.loadLimit:
          title: ID Load Limit For Term (FTE)
          maxLength: 7
          type: number
          description: "Lineage reference object : SVRLOLI_LOAD_LIMIT"
          x-lineageReferenceObject: SVRLOLI_LOAD_LIMIT
        loadLimit:
          title: ID Load Limit For Term (FTE)
          maxLength: 7
          type: number
          description: "Lineage reference object : SVRLOLI_LOAD_LIMIT"
          x-lineageReferenceObject: SVRLOLI_LOAD_LIMIT
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.sibtermLoadActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBTERM_LOAD_ACTIVE_IND"
          x-lineageReferenceObject: SIBTERM_LOAD_ACTIVE_IND
        criteria.termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRLOLI_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SVRLOLI_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SVRLOLI
    ca-faculty-id-term-specific-load-limits-1.0.0_put_response:
      required:
        - loadLimit
        - termCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SVRLOLI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRLOLI_ACTIVITY_DATE
        sibtermLoadActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBTERM_LOAD_ACTIVE_IND"
          x-lineageReferenceObject: SIBTERM_LOAD_ACTIVE_IND
        stvtermDesc:
          title: Description
          type: string
          description: "Lineage reference object : STVTERM_DESC"
          x-lineageReferenceObject: STVTERM_DESC
        loadLimit:
          title: ID Load Limit For Term (FTE)
          maxLength: 7
          type: number
          description: "Lineage reference object : SVRLOLI_LOAD_LIMIT"
          x-lineageReferenceObject: SVRLOLI_LOAD_LIMIT
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRLOLI_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SVRLOLI_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: svrloli
    ca-faculty-id-term-specific-load-limits-1.0.0_get_response:
      required:
        - loadLimit
        - termCode
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : SVRLOLI_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRLOLI_ACTIVITY_DATE
        sibtermLoadActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SIBTERM_LOAD_ACTIVE_IND"
          x-lineageReferenceObject: SIBTERM_LOAD_ACTIVE_IND
        stvtermDesc:
          title: Description
          type: string
          description: "Lineage reference object : STVTERM_DESC"
          x-lineageReferenceObject: STVTERM_DESC
        loadLimit:
          title: ID Load Limit For Term (FTE)
          maxLength: 7
          type: number
          description: "Lineage reference object : SVRLOLI_LOAD_LIMIT"
          x-lineageReferenceObject: SVRLOLI_LOAD_LIMIT
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRLOLI_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SVRLOLI_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: svrloli
    ca-faculty-id-term-specific-load-limits-1.0.0_post_request:
      required:
        - termCode
        - loadLimit
      type: object
      properties:
        loadLimit:
          title: ID Load Limit For Term (FTE)
          maxLength: 7
          type: number
          description: "Lineage reference object : SVRLOLI_LOAD_LIMIT"
          x-lineageReferenceObject: SVRLOLI_LOAD_LIMIT
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRLOLI_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SVRLOLI_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SVRLOLI
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
