openapi: 3.0.0
info:
  title: foapal-attribute-association-query
  description: API for FTIFATA administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FTIFATA
  x-source-domain: Finance
  x-source-title: FOAPAL Attribute Association Query
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/foapal-attribute-association-query:
    get:
      tags:
        - foapal-attribute-association-query
      summary: Return resources from FTIFATA
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: coasCode
          in: query
          required: false
          schema:
            type: string
        - name: foapalType
          in: query
          required: false
          schema:
            type: string
        - name: queryBy
          in: query
          required: false
          schema:
            type: string
        - name: ftvsatvFoapalCode
          in: query
          description: Ftvsatv Foapal Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSATV_FOAPAL_CODE
        - name: ftvsatvFoapalTitle
          in: query
          description: Ftvsatv Foapal Title
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSATV_FOAPAL_TITLE
        - name: ftvsatvAtttCode
          in: query
          description: Ftvsatv Attt Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSATV_ATTT_CODE
        - name: ftvsatvAtttDesc
          in: query
          description: Ftvsatv Attt Desc
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSATV_ATTT_DESC
        - name: ftvsatvAttvCode
          in: query
          description: Ftvsatv Attv Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: FTVSATV_ATTV_CODE
        - name: tempAttvDesc
          in: query
          description: Ftvsatv Attv Desc
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/foapal-attribute-association-query-1.0.0_get_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/foapal-attribute-association-query:
    post:
      tags:
        - foapal-attribute-association-query QAPI (Query by POST)
      summary: Return resources from FTIFATA
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/foapal-attribute-association-query-1.0.0_get_reques\
                t"
            example:
              queryBy: T
              foapalType: F
              coasCode: B
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/foapal-attribute-association-query-1.0.0_get_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    foapal-attribute-association-query-1.0.0_get_response:
      type: object
      properties:
        ftvsatvAtttDesc:
          title: Ftvsatv Attt Desc
          maxLength: 50
          type: string
          description: "Lineage reference object : FTVSATV_ATTT_DESC"
          x-lineageReferenceObject: FTVSATV_ATTT_DESC
        ftvsatvAttvCode:
          title: Ftvsatv Attv Code
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSATV_ATTV_CODE, Lookup lineage
            reference object : ftvfatv"
          x-lineageReferenceObject: FTVSATV_ATTV_CODE
          x-lineageLookupReferenceObject: ftvfatv
        ftvsatvAtttCode:
          title: Ftvsatv Attt Code
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSATV_ATTT_CODE, Lookup lineage
            reference object : ftvsatv"
          x-lineageReferenceObject: FTVSATV_ATTT_CODE
          x-lineageLookupReferenceObject: ftvsatv
        tempAttvDesc:
          title: Ftvsatv Attv Desc
          maxLength: 50
          type: string
        ftvsatvFoapalTitle:
          title: Ftvsatv Foapal Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVSATV_FOAPAL_TITLE"
          x-lineageReferenceObject: FTVSATV_FOAPAL_TITLE
        ftvsatvFoapalCode:
          title: Ftvsatv Foapal Code
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVSATV_FOAPAL_CODE"
          x-lineageReferenceObject: FTVSATV_FOAPAL_CODE
        ftvsatvSetCode:
          title: Ftvsatv Set Code
          maxLength: 8
          type: string
          description: "Lineage reference object : FTVSATV_SET_CODE"
          x-lineageReferenceObject: FTVSATV_SET_CODE
      x-lineageReferenceObject: ftvsatv_type
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    foapal-attribute-association-query-1.0.0_qapi_post:
      type: object
      properties:
        coasCode:
          type: string
        foapalType:
          type: string
        queryBy:
          type: string
        ftvsatvFoapalCode:
          title: Ftvsatv Foapal Code
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVSATV_FOAPAL_CODE"
          x-lineageReferenceObject: FTVSATV_FOAPAL_CODE
        ftvsatvFoapalTitle:
          title: Ftvsatv Foapal Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVSATV_FOAPAL_TITLE"
          x-lineageReferenceObject: FTVSATV_FOAPAL_TITLE
        ftvsatvAtttCode:
          title: Ftvsatv Attt Code
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSATV_ATTT_CODE, Lookup lineage
            reference object : ftvsatv"
          x-lineageReferenceObject: FTVSATV_ATTT_CODE
          x-lineageLookupReferenceObject: ftvsatv
        ftvsatvAtttDesc:
          title: Ftvsatv Attt Desc
          maxLength: 50
          type: string
          description: "Lineage reference object : FTVSATV_ATTT_DESC"
          x-lineageReferenceObject: FTVSATV_ATTT_DESC
        ftvsatvAttvCode:
          title: Ftvsatv Attv Code
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSATV_ATTV_CODE, Lookup lineage
            reference object : ftvfatv"
          x-lineageReferenceObject: FTVSATV_ATTV_CODE
          x-lineageLookupReferenceObject: ftvfatv
        tempAttvDesc:
          title: Ftvsatv Attv Desc
          maxLength: 50
          type: string
    foapal-attribute-association-query-1.0.0_get_request:
      required:
        - coasCode
      type: object
      properties:
        ftvsatvAtttDesc:
          title: Ftvsatv Attt Desc
          maxLength: 50
          type: string
          description: "Lineage reference object : FTVSATV_ATTT_DESC"
          x-lineageReferenceObject: FTVSATV_ATTT_DESC
        ftvsatvAttvCode:
          title: Ftvsatv Attv Code
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSATV_ATTV_CODE, Lookup lineage
            reference object : ftvfatv"
          x-lineageReferenceObject: FTVSATV_ATTV_CODE
          x-lineageLookupReferenceObject: ftvfatv
        queryBy:
          maxLength: 30
          type: string
          description: "Lineage reference object : queryBy"
          x-lineageReferenceObject: queryBy
        ftvsatvAtttCode:
          title: Ftvsatv Attt Code
          maxLength: 30
          type: string
          description: "Lineage reference object : FTVSATV_ATTT_CODE, Lookup lineage
            reference object : ftvsatv"
          x-lineageReferenceObject: FTVSATV_ATTT_CODE
          x-lineageLookupReferenceObject: ftvsatv
        tempAttvDesc:
          title: Ftvsatv Attv Desc
          maxLength: 50
          type: string
        foapalType:
          maxLength: 30
          type: string
          description: "Lineage reference object : foapalType"
          x-lineageReferenceObject: foapalType
        ftvsatvFoapalTitle:
          title: Ftvsatv Foapal Title
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVSATV_FOAPAL_TITLE"
          x-lineageReferenceObject: FTVSATV_FOAPAL_TITLE
        ftvsatvFoapalCode:
          title: Ftvsatv Foapal Code
          maxLength: 35
          type: string
          description: "Lineage reference object : FTVSATV_FOAPAL_CODE"
          x-lineageReferenceObject: FTVSATV_FOAPAL_CODE
        coasCode:
          title: Chart of Accounts
          maxLength: 30
          type: string
          description: "Lineage reference object : coasCode, Lookup lineage reference
            object : ftvcoas"
          x-lineageReferenceObject: coasCode
          x-lineageLookupReferenceObject: ftvcoas
      x-lineageReferenceObject: FTVSATV_TYPE
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
