openapi: 3.0.0
info:
  title: Admission Application Supporting Items
  description: Supporting items required for application of student admission
  version: "6.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Recruitment
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/admission-application-supporting-items:
    get:
      summary: Return all resources
      description: Returns a paged listing of all the resources in the system.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ADM_APPL_SUPP_ITEMS
      tags:
        - admission-application-supporting-items
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/admission-application-supporting-items/{id}:
    get:
      summary: Return the requested resource
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_ADM_APPL_SUPP_ITEMS
      tags:
        - admission-application-supporting-items
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Admission Application Supporting Items for
            use in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v6+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v6.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v6.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-admission-application-supporting-items.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-admission-application-supporting-items.json:
      title: Admission Application Supporting Items
      description: Supporting items required for application of student admission
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the
            admission-application-supplementary-items.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
        title:
          title: Title
          description: The full name of the admission-application-supplementary-items.
          type: string
        application:
          title: Application
          description: The application that supplementary items are required for.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Application.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: admission-applications
          additionalProperties: false
          required:
            - id
        type:
          title: Type
          description: The type of supplementary item.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Type.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: admission-application-supporting-item-types
          additionalProperties: false
          required:
            - id
        receivedOn:
          title: Received On
          description: Date the supplementary items was received.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
            - type: string
              maxLength: 0
        required:
          title: Required
          description: Requiredness of the supplementary item.
          enum:
            - mandatory
            - optional
          type: string
        requiredByDate:
          title: Required By Date
          description: The date the supplementary item is required by.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
            - type: string
              maxLength: 0
        firstRequestedOn:
          title: First Requested On
          description: First time the supplementary item was requested on.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
            - type: string
              maxLength: 0
        lastRequestedOn:
          title: Last Requested On
          description: Last time the supplementary items was requested on.
          oneOf:
            - type: string
              format: date-time
              pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
            - type: string
              maxLength: 0
        externalReference:
          title: External Reference
          description: External reference of the supplementary item.
          type: string
        status:
          title: Status
          description: Status of the supplementary item.
          type: object
          properties:
            type:
              title: Type
              description: Status type of the supplementary item.
              enum:
                - incomplete
                - received
                - waived
              type: string
            details:
              title: Details
              description: Detail status type of the supplementary item.
              type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Details.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: admission-application-supporting-item-statuses
              additionalProperties: false
              required:
                - id
          additionalProperties: false
          required:
            - type
      required:
        - id
        - title
        - application
        - type
        - required
        - status
      additionalProperties: false
