openapi: 3.0.0
info:
  title: life-insurance-coverage-rule
  description: API for PTRCOVR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PTRCOVR
  x-source-domain: Human Resources
  x-source-title: Life Insurance Coverage Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/life-insurance-coverage-rule:
    get:
      tags:
        - life-insurance-coverage-rule
      summary: Return resources from PTRCOVR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: bdcaCode
          in: query
          description: Deduction
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRCOVR_BDCA_CODE
        - name: bdplCode
          in: query
          description: Plan
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRCOVR_BDPL_CODE
        - name: fromSalary
          in: query
          description: Salary From
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRCOVR_FROM_SALARY
        - name: toSalary
          in: query
          description: Salary To
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRCOVR_TO_SALARY
        - name: covAmt
          in: query
          description: Coverage Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRCOVR_COV_AMT
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRCOVR_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/life-insurance-coverage-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/life-insurance-coverage-rule:
    post:
      tags:
        - life-insurance-coverage-rule QAPI (Query by POST)
      summary: Return resources from PTRCOVR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/life-insurance-coverage-rule-1.0.0_get_request"
            example:
              fromSalary: 10000
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/life-insurance-coverage-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    life-insurance-coverage-rule-1.0.0_get_response:
      required:
        - activityDate
        - bdcaCode
        - covAmt
        - fromSalary
        - toSalary
      type: object
      properties:
        toSalary:
          title: Salary To
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_TO_SALARY"
          x-lineageReferenceObject: PTRCOVR_TO_SALARY
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PTRCOVR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRCOVR_ACTIVITY_DATE
        bdcaCode:
          title: Deduction
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRCOVR_BDCA_CODE"
          x-lineageReferenceObject: PTRCOVR_BDCA_CODE
        fromSalary:
          title: Salary From
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_FROM_SALARY"
          x-lineageReferenceObject: PTRCOVR_FROM_SALARY
        bdplCode:
          title: Plan
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRCOVR_BDPL_CODE"
          x-lineageReferenceObject: PTRCOVR_BDPL_CODE
        covAmt:
          title: Coverage Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_COV_AMT"
          x-lineageReferenceObject: PTRCOVR_COV_AMT
      x-lineageReferenceObject: ptrcovr
    life-insurance-coverage-rule-1.0.0_qapi_post:
      type: object
      properties:
        bdcaCode:
          title: Deduction
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRCOVR_BDCA_CODE"
          x-lineageReferenceObject: PTRCOVR_BDCA_CODE
        bdplCode:
          title: Plan
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRCOVR_BDPL_CODE"
          x-lineageReferenceObject: PTRCOVR_BDPL_CODE
        fromSalary:
          title: Salary From
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_FROM_SALARY"
          x-lineageReferenceObject: PTRCOVR_FROM_SALARY
        toSalary:
          title: Salary To
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_TO_SALARY"
          x-lineageReferenceObject: PTRCOVR_TO_SALARY
        covAmt:
          title: Coverage Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_COV_AMT"
          x-lineageReferenceObject: PTRCOVR_COV_AMT
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PTRCOVR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRCOVR_ACTIVITY_DATE
    life-insurance-coverage-rule-1.0.0_get_request:
      required:
        - bdcaCode
        - fromSalary
        - toSalary
        - covAmt
        - activityDate
      type: object
      properties:
        toSalary:
          title: Salary To
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_TO_SALARY"
          x-lineageReferenceObject: PTRCOVR_TO_SALARY
        activityDate:
          title: Activity Date
          maxLength: 26
          type: string
          description: "Lineage reference object : PTRCOVR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRCOVR_ACTIVITY_DATE
        bdcaCode:
          title: Deduction
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRCOVR_BDCA_CODE"
          x-lineageReferenceObject: PTRCOVR_BDCA_CODE
        fromSalary:
          title: Salary From
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_FROM_SALARY"
          x-lineageReferenceObject: PTRCOVR_FROM_SALARY
        bdplCode:
          title: Plan
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRCOVR_BDPL_CODE"
          x-lineageReferenceObject: PTRCOVR_BDPL_CODE
        covAmt:
          title: Coverage Amount
          maxLength: 15
          type: number
          description: "Lineage reference object : PTRCOVR_COV_AMT"
          x-lineageReferenceObject: PTRCOVR_COV_AMT
      x-lineageReferenceObject: PTRCOVR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
