openapi: 3.0.0
info:
  title: Advisor Advisee Term Profiles
  description: This API retrieves student information like student ids, student names, academic programs, classifications, gpas - belonging to given advisor for a term.  
  version: 1.0.0
  x-api-type: erp
  x-release-status: ga
  x-source-system: banner
  x-audience: all
  x-source-domain: Student
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /qapi/advisor-advisee-term-profiles:
    post:
      tags:
      - advisor-advisee-term-profiles QAPI
      summary: Returns resources from SMRPRLE, SORLCUR, SPRIDEN, STVCLAS, SHRLGPA SGRADVR, STVADVR, GORGUID and GORICCR
      description: Queries for the student personal and student academic information based on assigned advisor for a term.     
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```

            application/vnd.hedtech.integration.v1.0.0+json

            ```
          schema:
            type: string
        - name: content type
          in: header
          required: true
          description: >
            The version of the resource supplied in the request. Please refer to
            the API source documentation for detailed support information.
            Prefer to use only the whole MAJOR version. 

            ```

            application/json

            ```
          schema:
            type: string             
        - name: max
          in: query
          description:  |
            The maximum number of resources requesting for this result set.\
            The default limit is 500 and the maximum limit is 1000.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: sortColumn
          in: query
          description: The attribute name by which API response is sorted.
          required: false
          schema:
            type: string
        - name: searchParam
          in: query
          description: The search attribute name against which the API response.
          required: false
          schema:
            type: string    
      requestBody:
        required: true
        content:
          application/vnd.hedtech.integration.v1+json:
            schema:
              type: object
              $ref: "#/components/schemas/advisor-advisee-term-profiles-1.0.0_qapi_post_request"            
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
            X-Content-Restricted:
              description: If the response is not a full representation of the resource, a partial representation is returned. Otherwise, this header is not included.
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
            X-Max-Page-Size:
              description: Specifies the maximum number of resources returned in a response.
              schema:
                type: integer
          content:
            application/vnd.hedtech.integration.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/advisor-advisee-term-profiles-1.0.0_qapi_post_response'
        '400':
          description: Failure. Bad Request. The server cannot process the request due to something that is perceived to be a client error.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '401':
          description: Failure. Unauthorized.
        '403':
          description: Failure. Forbidden. The user does not have the required permissions for the resource.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '404':
          description: Failure. Not Found. Cannot map the URI to a resource.
        '405':
          description: Failure. Method Not Allowed. The client tried to use an HTTP method that the resource does not allow.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '406':
          description: Failure. Not Acceptable. Unable to generate any of the clientâ€™s preferred media types, as indicated by the Accept request header.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
        '500':
          description: Server error. Unexpected configuration or data.
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors_2_0_0'
      security:
        - EthosIntegrationBearer: []
        - BasicAuth: []
      x-method-permissions: API_ADVISOR_ADVISEE_TERM_PROFL
components:
  schemas:
    advisor-advisee-term-profiles-1.0.0_qapi_post_request:
      type: object
      properties:
        advisor:
          title: Advisor Id
          type: string
          description: "The GORGUID_GUID of an advisor"
          x-lineageReferenceObject: GORGUID_GUID
          example: da1fb7fe-c23a-4d9a-8736-9b45f962e72c
        term:
          title: Term Id
          type: string
          description: "The GORGUID_GUID of a term associated with advisor."
          x-lineageLookupReferenceObject: GORGUID
          example: 2591108f-403d-457a-ada0-064597415c55   
      required:
       - advisor
       - term
    advisor-advisee-term-profiles-1.0.0_qapi_post_response:
      type: object
      required: 
      - advisor
      - term
      - studentId
      - studentErpId
      - advisorType
      - programId
      - programTitle
      properties:
        advisor:
          title: Advisor Id
          type: string
          description: "The GORGUID_GUID of an advisor"
          x-lineageReferenceObject: GORGUID_GUID
          example: da1fb7fe-c23a-4d9a-8736-9b45f962e72c
        term:
          title: Term Id
          type: string
          description: "The GORGUID_GUID of a term associated with advisor."
          x-lineageReferenceObject: GORGUID_GUID
          example: 2591108f-403d-457a-ada0-064597415c55      
        studentId:
          title: Student GUID
          type: string
          description: "The GORGUID_GUID associated with student."
          x-lineageReferenceObject: GORGUID_GUID
          example: dd88c4e2-3d8b-4789-ab3b-268c4aa4da8c
        studentErpId:
          title: Student banner id 
          type: string
          description: "The Banner id associated with student."
          x-lineageReferenceObject: SPRIDEN_ID
          example: A00277848
        studentFirstName:
          title: Student first name 
          type: string
          description: "The first name of student in Banner."
          x-lineageReferenceObject: SPRIDEN_FIRST_NAME
          example: Henry 
        studentMiddleName:
          title: Student middle name 
          type: string
          description: "The middle name of student in Banner."
          x-lineageReferenceObject: SPRIDEN_MI_NAME
          example: Richards
        studentLastName:
          title: Student last name 
          type: string
          description: "The last name of student in Banner."
          x-lineageReferenceObject: SPRIDEN_LAST_NAME
          example: James
        advisorType:
          title: Advisor Type 
          type: string
          description: "Advisor type of the given advisor."
          x-lineageReferenceObject: STVADVR_DESC
          example: Primary Advisor
        programId:
          title: Program GUID 
          type: string
          description: "GUID associated with academic program."
          x-lineageReferenceObject: SMRPRLE_GUID
          example: 21bcf878-5cbc-435d-bf13-6329b4c35efe
        programTitle:
          title: Academic Program 
          type: string
          description: "Academic program associated with student."
          x-lineageReferenceObject: SORLCUR_PROGRAM
          example: BA-ART
        classificationId:
          title: Student Classification GUID 
          type: string
          description: "GUID associated with student classification."
          x-lineageReferenceObject: STVCLAS_GUID
          example: f980ae00-ee79-4d4f-9aad-54735babb9d0
        classificationTitle:
          title: Student Classification title 
          type: string
          description: "Title of student classification."
          x-lineageReferenceObject: STVCLAS_DESC
          example: First Year Law
        gpaValue:
          title: Cumulative GPA 
          type: string
          description: "The cumulative GPA earned by student."
          x-lineageReferenceObject: SHRLGPA_GPA
          example: 8.25
        nameType:
          title: Student Name Type 
          type: string
          description: "Ethos name type associated with student."
          x-lineageReferenceObject: GORICCR_TRANSLATION_VALUE
          example: Legal  
    errors_2_0_0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
              type: object
              properties:
                id:
                  type: string
                  description: The global identifier of the resource in error.
                sourceId:
                  type: string
                  description: The source applications data reference identifier for the primary data entity used to create the resource. This is useful for referencing the source item through the applications administrative user interface.
                code:
                  type: string
                  description: The error message code used to describe the error details.
                description:
                  type: string
                  description: The error description used to describe the error details.
                message:
                  type: string
                  description: The detailed actionable error message.
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
    BasicAuth:
      type: http
      scheme: basic
