openapi: 3.0.0
info:
  title: journal-voucher-mass-entry-header
  description: API for FGAJVCM administrative page
  version: 1.1.0
  x-audience: all
  x-release-status: beta
  x-source-name: FGAJVCM
  x-source-domain: Finance
  x-source-title: Journal Voucher Mass Entry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/journal-voucher-mass-entry-header:
    put:
      tags:
        - journal-voucher-mass-entry-header
      summary: Updates an existing resource in FGAJVCM
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.1.0+json:
            schema:
              $ref: "#/components/schemas/journal-voucher-mass-entry-header-1.1.0_put_request"
            example:
              documentNumber: J0000001
              transDate: 2022-10-25
              docAmt: "800"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.1.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/journal-voucher-mass-entry-header-1.1.0_put_respons\
                    e"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/journal-voucher-mass-entry-header: {}
components:
  schemas:
    journal-voucher-mass-entry-header-1.1.0_put_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              documentNumber:
                title: Document Number
                maxLength: 8
                type: string
                description: "Lineage reference object : documentNumber"
                x-lineageReferenceObject: documentNumber
            x-lineageReferenceObject: key_block
        fgbjvch:
          type: array
          items:
            required:
              - transDate
            type: object
            properties:
              defRuclCode:
                title: Type
                maxLength: 4
                type: string
                description: "Lookup lineage reference object : ftvrucl"
                x-lineageLookupReferenceObject: ftvrucl
              editDeferInd:
                title: Deferred Edit
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBJVCH_EDIT_DEFER_IND"
                x-lineageReferenceObject: FGBJVCH_EDIT_DEFER_IND
              defDepNum:
                title: Deposit
                maxLength: 8
                type: string
              defTransDesc:
                title: Description
                maxLength: 35
                type: string
                description: "Lookup lineage reference object : ftvrucl"
                x-lineageLookupReferenceObject: ftvrucl
              defBankCode:
                title: Bank
                maxLength: 2
                type: string
                description: "Lookup lineage reference object : gxvbank"
                x-lineageLookupReferenceObject: gxvbank
              transDate:
                title: Transaction Date
                maxLength: 26
                type: string
                description: "Lineage reference object : FGBJVCH_TRANS_DATE"
                format: date-time
                x-lineageReferenceObject: FGBJVCH_TRANS_DATE
              defBudgetPeriod:
                title: Budget Period
                maxLength: 2
                type: string
              nsfOnOffInd:
                title: NSF Checking
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBJVCH_NSF_ON_OFF_IND"
                x-lineageReferenceObject: FGBJVCH_NSF_ON_OFF_IND
              defCurrCode:
                title: Currency
                maxLength: 4
                type: string
                description: "Lookup lineage reference object : gtvcurr"
                x-lineageLookupReferenceObject: gtvcurr
              docAmt:
                title: Document Total
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBJVCH_DOC_AMT"
                x-lineageReferenceObject: FGBJVCH_DOC_AMT
            x-lineageReferenceObject: fgbjvch
    journal-voucher-mass-entry-header-1.1.0_put_request:
      required:
        - transDate
      type: object
      properties:
        editDeferInd:
          title: Deferred Edit
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBJVCH_EDIT_DEFER_IND"
          x-lineageReferenceObject: FGBJVCH_EDIT_DEFER_IND
        documentNumber:
          title: Document Number
          maxLength: 8
          type: string
          description: "Lineage reference object : documentNumber"
          x-lineageReferenceObject: documentNumber
        transDate:
          title: Transaction Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FGBJVCH_TRANS_DATE"
          format: date-time
          x-lineageReferenceObject: FGBJVCH_TRANS_DATE
        nsfOnOffInd:
          title: NSF Checking
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBJVCH_NSF_ON_OFF_IND"
          x-lineageReferenceObject: FGBJVCH_NSF_ON_OFF_IND
        docAmt:
          title: Document Total
          maxLength: 25
          type: number
          description: "Lineage reference object : FGBJVCH_DOC_AMT"
          x-lineageReferenceObject: FGBJVCH_DOC_AMT
      x-lineageReferenceObject: FGBJVCH
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
