openapi: 3.0.0
info:
  title: benefit-payroll-frequency-rule
  description: API for PTRBDFQ administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PTRBDFQ
  x-source-domain: Human Resources
  x-source-title: Benefit Payroll Frequency Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/benefit-payroll-frequency-rule:
    get:
      tags:
        - benefit-payroll-frequency-rule
      summary: Return resources from PTRBDFQ
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: bdcaCode
          in: query
          description: Benefit Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDFQ_BDCA_CODE
        - name: month
          in: query
          description: Month
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDFQ_MONTH
        - name: numberOfPays
          in: query
          description: Frequency
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDFQ_NUMBER_OF_PAYS
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: PTRBDFQ_ACTIVITY_DATE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/benefit-payroll-frequency-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/benefit-payroll-frequency-rule:
    post:
      tags:
        - benefit-payroll-frequency-rule QAPI (Query by POST)
      summary: Return resources from PTRBDFQ
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/benefit-payroll-frequency-rule-1.0.0_get_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/benefit-payroll-frequency-rule-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    benefit-payroll-frequency-rule-1.0.0_qapi_post:
      type: object
      properties:
        bdcaCode:
          title: Benefit Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRBDFQ_BDCA_CODE"
          x-lineageReferenceObject: PTRBDFQ_BDCA_CODE
        month:
          title: Month
          maxLength: 2
          type: number
          description: "Lineage reference object : PTRBDFQ_MONTH"
          x-lineageReferenceObject: PTRBDFQ_MONTH
        numberOfPays:
          title: Frequency
          maxLength: 3
          type: number
          description: "Lineage reference object : PTRBDFQ_NUMBER_OF_PAYS"
          x-lineageReferenceObject: PTRBDFQ_NUMBER_OF_PAYS
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRBDFQ_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRBDFQ_ACTIVITY_DATE
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    benefit-payroll-frequency-rule-1.0.0_get_response:
      required:
        - bdcaCode
        - month
        - numberOfPays
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRBDFQ_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRBDFQ_ACTIVITY_DATE
        bdcaCode:
          title: Benefit Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRBDFQ_BDCA_CODE"
          x-lineageReferenceObject: PTRBDFQ_BDCA_CODE
        month:
          title: Month
          maxLength: 2
          type: number
          description: "Lineage reference object : PTRBDFQ_MONTH"
          x-lineageReferenceObject: PTRBDFQ_MONTH
        bdcaDesc:
          title: Description
          type: string
        numberOfPays:
          title: Frequency
          maxLength: 3
          type: number
          description: "Lineage reference object : PTRBDFQ_NUMBER_OF_PAYS"
          x-lineageReferenceObject: PTRBDFQ_NUMBER_OF_PAYS
      x-lineageReferenceObject: ptrbdfq
    benefit-payroll-frequency-rule-1.0.0_get_request:
      required:
        - bdcaCode
        - month
        - numberOfPays
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : PTRBDFQ_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: PTRBDFQ_ACTIVITY_DATE
        bdcaCode:
          title: Benefit Code
          maxLength: 30
          type: string
          description: "Lineage reference object : PTRBDFQ_BDCA_CODE"
          x-lineageReferenceObject: PTRBDFQ_BDCA_CODE
        month:
          title: Month
          maxLength: 2
          type: number
          description: "Lineage reference object : PTRBDFQ_MONTH"
          x-lineageReferenceObject: PTRBDFQ_MONTH
        numberOfPays:
          title: Frequency
          maxLength: 3
          type: number
          description: "Lineage reference object : PTRBDFQ_NUMBER_OF_PAYS"
          x-lineageReferenceObject: PTRBDFQ_NUMBER_OF_PAYS
      x-lineageReferenceObject: PTRBDFQ
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
