openapi: 3.0.0
info:
  title: ca-mis-special-historical-data-guardian-information-copy
  description: API for SVAMISH administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SVAMISH
  x-source-domain: Student
  x-source-title: Student MIS Special Historical Data (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-mis-special-historical-data-guardian-information-copy:
    post:
      tags:
        - ca-mis-special-historical-data-guardian-information-copy
      summary: Creates a new resource in SVAMISH
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-special-historical-data-guardian-information\
                -copy-1.0.0_post_request"
            example:
              guard1GedlCode: "7"
              guard2GedlCode: "8"
              id: A00036216
              svamishEffTerm: TERM19
              svamishDicdCode: "104"
              svbsgpdGuard2GedlCode: "7"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-special-historical-data-guardian-information\
                    -copy-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-mis-special-historical-data-guardian-information-copy: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-mis-special-historical-data-guardian-information-copy-1.0.0_post_response:
      type: object
      properties:
        guard1GedlCode:
          title: First Guardian (Parent) Education Level
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSGPD_GUARD_1_GEDL_CODE, Lookup
            lineage reference object : SVVGEDL"
          x-lineageReferenceObject: SVBSGPD_GUARD_1_GEDL_CODE
          x-lineageLookupReferenceObject: SVVGEDL
        guard2GedlCode:
          title: Second Guardian (Parent) Education Level
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSGPD_GUARD_2_GEDL_CODE, Lookup
            lineage reference object : SVVGEDL"
          x-lineageReferenceObject: SVBSGPD_GUARD_2_GEDL_CODE
          x-lineageLookupReferenceObject: SVVGEDL
        activityDate:
          maxLength: 11
          type: string
          description: "Lineage reference object : SVBSGPD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVBSGPD_ACTIVITY_DATE
        guard2GedlDesc:
          type: string
        guard1GedlDesc:
          type: string
        userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SVBSGPD_USER_ID"
          x-lineageReferenceObject: SVBSGPD_USER_ID
      x-lineageReferenceObject: svbsgpd
    ca-mis-special-historical-data-guardian-information-copy-1.0.0_post_request:
      type: object
      properties:
        guard1GedlCode:
          title: First Guardian (Parent) Education Level
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSGPD_GUARD_1_GEDL_CODE, Lookup
            lineage reference object : SVVGEDL"
          x-lineageReferenceObject: SVBSGPD_GUARD_1_GEDL_CODE
          x-lineageLookupReferenceObject: SVVGEDL
        guard2GedlCode:
          title: Second Guardian (Parent) Education Level
          maxLength: 2
          type: string
          description: "Lineage reference object : SVBSGPD_GUARD_2_GEDL_CODE, Lookup
            lineage reference object : SVVGEDL"
          x-lineageReferenceObject: SVBSGPD_GUARD_2_GEDL_CODE
          x-lineageLookupReferenceObject: SVVGEDL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : ID"
          x-lineageReferenceObject: ID
        svamishEffTerm:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : SVAMISH_EFF_TERM, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SVAMISH_EFF_TERM
          x-lineageLookupReferenceObject: stvterm
        svamishDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : SVAMISH_DICD_CODE"
          x-lineageReferenceObject: SVAMISH_DICD_CODE
      x-lineageReferenceObject: SVBSGPD
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
