openapi: 3.0.0
info:
  title: applicant-requirements-mass-entry
  description: API for RRAMASS administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: RRAMASS
  x-source-domain: Financial Aid
  x-source-title: Applicant Requirements Mass Entry
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-requirements-mass-entry:
    post:
      tags:
        - applicant-requirements-mass-entry
      summary: Creates a new resource in RRAMASS
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-requirements-mass-entry-1.0.0_post_reques\
                t"
            example:
              keyblckFundCode: A05
              keyblckAidyCode: 2122
              keyblckTreqCode: ADMIT
              keyblckPeriod: 202215
              keyblckTrstCode: 0
              displayStudCode: A00010003
              keyblckStatDate: 2021-06-07
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-requirements-mass-entry-1.0.0_post_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-requirements-mass-entry: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    applicant-requirements-mass-entry-1.0.0_post_request:
      required:
        - displayStudCode
        - rrrareqTreqCode
      type: object
      properties:
        keyblckFundCode:
          title: Fund Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckFundCode, Lookup lineage
            reference object : rfrbase,rfraspc"
          x-lineageReferenceObject: keyblckFundCode
          x-lineageLookupReferenceObject: rfrbase,rfraspc
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        keyblckTreqCode:
          title: Requirement Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTreqCode"
          x-lineageReferenceObject: keyblckTreqCode
        keyblckPeriod:
          title: Period
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckPeriod, Lookup lineage reference
            object : robprds"
          x-lineageReferenceObject: keyblckPeriod
          x-lineageLookupReferenceObject: robprds
        rrrareqTreqCode:
          title: Requirement Code
          maxLength: 30
          type: string
        keyblckTrstCode:
          title: Status Code
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTrstCode, Lookup lineage
            reference object : rtvtrst"
          x-lineageReferenceObject: keyblckTrstCode
          x-lineageLookupReferenceObject: rtvtrst
        rrrareqFundCode:
          title: Fund Code
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : rfrbase,rfraspc"
          x-lineageLookupReferenceObject: rfrbase,rfraspc
        rrrareqPeriod:
          title: Period
          maxLength: 15
          type: string
          description: "Lookup lineage reference object : robprds"
          x-lineageLookupReferenceObject: robprds
        displayStudCode:
          title: Student ID
          maxLength: 9
          type: string
        keyblckStatDate:
          title: Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : keyblckStatDate"
          format: date-time
          x-lineageReferenceObject: keyblckStatDate
      x-lineageReferenceObject: RPRBAKO
    applicant-requirements-mass-entry-1.0.0_post_response:
      required:
        - displayStudCode
        - rrrareqStatDate
        - rrrareqTreqCode
        - rrrareqTrstCode
      type: object
      properties:
        rrrareqStatDate:
          title: Status Date
          maxLength: 11
          type: string
          format: date-time
        rrrareqTreqCode:
          title: Requirement Code
          maxLength: 30
          type: string
        displayStudName:
          title: Student Name
          maxLength: 230
          type: string
        rrrareqFundCode:
          title: Fund Code
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : rfrbase,rfraspc"
          x-lineageLookupReferenceObject: rfrbase,rfraspc
        rrrareqPeriod:
          title: Period
          maxLength: 15
          type: string
          description: "Lookup lineage reference object : robprds"
          x-lineageLookupReferenceObject: robprds
        displayTreqDesc:
          type: string
        displayStudCode:
          title: Student ID
          maxLength: 9
          type: string
        rrrareqTrstCode:
          title: Status Code
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : rtvtrst"
          x-lineageLookupReferenceObject: rtvtrst
      x-lineageReferenceObject: rprbako
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
