openapi: 3.0.0
info:
  title: course-search
  description: API for SCASRCH administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SCASRCH
  x-source-domain: Student
  x-source-title: Course Search
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/course-search:
    get:
      tags:
      - course-search
      summary: Return resources from SCASRCH
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
      - name: scacrseSubjCode
        in: query
        required: false
        schema:
          type: string
      - name: scacrseCrseNumb
        in: query
        required: false
        schema:
          type: string
      - name: scacrseStartDate
        in: query
        required: false
        schema:
          type: string
      - name: scacrseEndDate
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/course-search-1.0.0_get_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/course-search:
    post:
      tags:
      - course-search QAPI (Query by POST)
      summary: Return resources from SCASRCH
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/course-search-1.0.0_qapi_post_request'
            example:
              scacrseCrseNumb: ISE
              scacrseSubjCode: '006'
              scacrseStartDate: 2021-05-20
              scacrseEndDate: 2021-05-20
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/course-search-1.0.0_qapi_post_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
components:
  schemas:
    course-search-1.0.0_qapi_post_request:
      type: object
      properties:
        scacrseCrseNumb:
          title: Course
          maxLength: 30
          type: string
          description: "Lineage reference object : scacrseCrseNumb"
          x-lineageReferenceObject: scacrseCrseNumb
        scacrseSubjCode:
          title: Subject
          maxLength: 40
          type: string
          description: "Lineage reference object : scacrseSubjCode, Lookup lineage\
            \ reference object : stvsubj"
          x-lineageReferenceObject: scacrseSubjCode
          x-lineageLookupReferenceObject: stvsubj
        scacrseStartDate:
          title: From  Date
          maxLength: 11
          type: string
          description: "Lineage reference object : scacrseStartDate"
          format: date-time
          x-lineageReferenceObject: scacrseStartDate
        scacrseEndDate:
          title: To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : scacrseEndDate"
          format: date-time
          x-lineageReferenceObject: scacrseEndDate
      x-lineageReferenceObject: SCACRSE_KEY_BLOCK
    course-search-1.0.0_get_response:
      type: object
      properties:
        scacrse_key_block:
          type: array
          items:
            type: object
            properties:
              scacrseCrseNumb:
                title: Course
                maxLength: 30
                type: string
                description: "Lineage reference object : scacrseCrseNumb"
                x-lineageReferenceObject: scacrseCrseNumb
              subjDescription:
                title: Subj Description
                type: string
                description: "Lineage reference object : subjDescription"
                x-lineageReferenceObject: subjDescription
              scacrseSubjCode:
                title: Subject
                maxLength: 40
                type: string
                description: "Lineage reference object : scacrseSubjCode, Lookup lineage\
                  \ reference object : stvsubj"
                x-lineageReferenceObject: scacrseSubjCode
                x-lineageLookupReferenceObject: stvsubj
              scacrseCourseAlias:
                title: Course Alias
                maxLength: 50
                type: string
                description: "Lineage reference object : scacrseCourseAlias"
                x-lineageReferenceObject: scacrseCourseAlias
              scacrseStartDate:
                title: From  Date
                maxLength: 11
                type: string
                description: "Lineage reference object : scacrseStartDate"
                format: date-time
                x-lineageReferenceObject: scacrseStartDate
              scacrseEndDate:
                title: To Date
                maxLength: 11
                type: string
                description: "Lineage reference object : scacrseEndDate"
                format: date-time
                x-lineageReferenceObject: scacrseEndDate
            x-lineageReferenceObject: scacrse_key_block
        scbcrse:
          type: array
          items:
            type: object
            properties:
              crseNumb:
                title: Course Number
                maxLength: 30
                type: string
                description: "Lineage reference object : SCBCRSE_CRSE_NUMB"
                x-lineageReferenceObject: SCBCRSE_CRSE_NUMB
              termTo:
                maxLength: 6
                type: string
              creditHrHigh:
                title: High
                maxLength: 9
                type: number
                description: "Lineage reference object : SCBCRSE_CREDIT_HR_HIGH"
                x-lineageReferenceObject: SCBCRSE_CREDIT_HR_HIGH
              subjCode:
                title: Subject
                maxLength: 30
                type: string
                description: "Lineage reference object : SCBCRSE_SUBJ_CODE"
                x-lineageReferenceObject: SCBCRSE_SUBJ_CODE
              courseAlias:
                title: Course Alias
                maxLength: 20
                type: string
              creditHrLow:
                title: Low
                maxLength: 9
                type: number
                description: "Lineage reference object : SCBCRSE_CREDIT_HR_LOW"
                x-lineageReferenceObject: SCBCRSE_CREDIT_HR_LOW
              effTerm:
                maxLength: 6
                type: string
                description: "Lineage reference object : SCBCRSE_EFF_TERM"
                x-lineageReferenceObject: SCBCRSE_EFF_TERM
              creditHrInd:
                title: Credit Hours Or/To
                maxLength: 2
                type: string
                description: "Lineage reference object : SCBCRSE_CREDIT_HR_IND"
                x-lineageReferenceObject: SCBCRSE_CREDIT_HR_IND
              title:
                title: Description
                type: string
                description: "Lineage reference object : SCBCRSE_TITLE"
                x-lineageReferenceObject: SCBCRSE_TITLE
            x-lineageReferenceObject: scbcrse
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
    course-search-1.0.0_qapi_post_response:
      type: object
      properties:
        scacrse_key_block:
          type: array
          items:
            type: object
            properties:
              scacrseCrseNumb:
                title: Course
                maxLength: 30
                type: string
                description: "Lineage reference object : scacrseCrseNumb"
                x-lineageReferenceObject: scacrseCrseNumb
              subjDescription:
                title: Subj Description
                type: string
                description: "Lineage reference object : subjDescription"
                x-lineageReferenceObject: subjDescription
              scacrseSubjCode:
                title: Subject
                maxLength: 40
                type: string
                description: "Lineage reference object : scacrseSubjCode, Lookup lineage\
                  \ reference object : stvsubj"
                x-lineageReferenceObject: scacrseSubjCode
                x-lineageLookupReferenceObject: stvsubj
              scacrseCourseAlias:
                title: Course Alias
                maxLength: 50
                type: string
                description: "Lineage reference object : scacrseCourseAlias"
                x-lineageReferenceObject: scacrseCourseAlias
              scacrseStartDate:
                title: From  Date
                maxLength: 11
                type: string
                description: "Lineage reference object : scacrseStartDate"
                format: date-time
                x-lineageReferenceObject: scacrseStartDate
              scacrseEndDate:
                title: To Date
                maxLength: 11
                type: string
                description: "Lineage reference object : scacrseEndDate"
                format: date-time
                x-lineageReferenceObject: scacrseEndDate
            x-lineageReferenceObject: scacrse_key_block
        scbcrse:
          type: array
          items:
            type: object
            properties:
              crseNumb:
                title: Course Number
                maxLength: 30
                type: string
                description: "Lineage reference object : SCBCRSE_CRSE_NUMB"
                x-lineageReferenceObject: SCBCRSE_CRSE_NUMB
              termTo:
                maxLength: 6
                type: string
              creditHrHigh:
                title: High
                maxLength: 9
                type: number
                description: "Lineage reference object : SCBCRSE_CREDIT_HR_HIGH"
                x-lineageReferenceObject: SCBCRSE_CREDIT_HR_HIGH
              subjCode:
                title: Subject
                maxLength: 30
                type: string
                description: "Lineage reference object : SCBCRSE_SUBJ_CODE"
                x-lineageReferenceObject: SCBCRSE_SUBJ_CODE
              courseAlias:
                title: Course Alias
                maxLength: 20
                type: string
              creditHrLow:
                title: Low
                maxLength: 9
                type: number
                description: "Lineage reference object : SCBCRSE_CREDIT_HR_LOW"
                x-lineageReferenceObject: SCBCRSE_CREDIT_HR_LOW
              effTerm:
                maxLength: 6
                type: string
                description: "Lineage reference object : SCBCRSE_EFF_TERM"
                x-lineageReferenceObject: SCBCRSE_EFF_TERM
              creditHrInd:
                title: Credit Hours Or/To
                maxLength: 2
                type: string
                description: "Lineage reference object : SCBCRSE_CREDIT_HR_IND"
                x-lineageReferenceObject: SCBCRSE_CREDIT_HR_IND
              title:
                title: Description
                type: string
                description: "Lineage reference object : SCBCRSE_TITLE"
                x-lineageReferenceObject: SCBCRSE_TITLE
            x-lineageReferenceObject: scbcrse
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer