openapi: 3.0.0
info:
  title: registration-status
  description: >
    The get student's registration status is an optional API to return the data
    available on the Registration Status Self-Service page.  The data includes
    academic standing; student status;  class assignment;  curriculum; general
    student;  re-admit information; time ticket information. The response can be
    used to show the student their current standing and student information.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: erp
  x-release-status: ga
  x-source-domain: Student
  x-source-title: Registration Status
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
tags:
  - name: registration-status
paths:
  /api/registration-status:
    get:
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_REGSTATUS
      tags:
        - registration-status
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information.

            ```
              application/json
            ```
        - name: term
          in: query
          required: true
          schema:
            type: string
          example: "202014"
          description: Code value to identify the term
        - name: bannerId
          in: query
          required: true
          schema:
            type: string
          example: HOS03822
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/registration-status"
            application/xml:
              schema:
                type: object
                $ref: "#/components/schemas/registration-status"
          headers:
            X-Media-Type:
              description: application/json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Permission Denied
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    registration-status:
      type: array
      items:
        type: object
        properties:
          academicStandingSuccess:
            type: boolean
          academicStatusMessage:
            type: string
          curriculumProfile:
            type: object
            properties:
              classCode:
                type: string
              classDescription:
                type: string
              keySequenceNumber:
                type: integer
              learnerModuleDescription:
                type: string
              learnerModuleType:
                type: string
              primaryCurriculum:
                type: object
                properties:
                  admitType:
                    type: string
                  admitTypeCode:
                    type: string
                  campus:
                    type: string
                  campusCode:
                    type: string
                  concentrationFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode:
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          type: array
                          items:
                            type: object
                  college:
                    type: string
                  collegeCode:
                    type: string
                  degree:
                    type: string
                  degreeCode:
                    type: string
                  keySequenceNumber:
                    type: number
                  level:
                    type: string
                  levelCode:
                    type: string
                  majorFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode ":
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          type: array
                          items:
                            type: object
                  minorFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode ":
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          items:
                            type: object
                  otherFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode ":
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          items:
                            type: object
                  program:
                    type: string
                  programCode:
                    type: string
                  studyPathDescription:
                    type: string
                  termAdmit:
                    type: string
                  termAdmitCode:
                    type: string
                  termCatalog:
                    type: string
                  termCatalogCode:
                    type: string
                  termMatriculate:
                    type: string
                  termMatriculateCode:
                    type: string
              secondaryCurricula:
                type: object
                properties:
                  admitType:
                    type: string
                  admitTypeCode:
                    type: string
                  campus:
                    type: string
                  campusCode:
                    type: string
                  concentrationFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode:
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          items:
                            type: object
                  college:
                    type: string
                  collegeCode:
                    type: string
                  degree:
                    type: string
                  degreeCode:
                    type: string
                  keySequenceNumber:
                    type: number
                  level:
                    type: string
                  levelCode:
                    type: string
                  majorFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode ":
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          items:
                            type: object
                  minorFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode ":
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          items:
                            type: object
                  otherFieldsOfStudy:
                    type: array
                    items:
                      type: object
                      properties:
                        department:
                          type: string
                        departmentCode:
                          type: string
                        learnerFieldStudy:
                          type: string
                        learnerFieldStudyCode:
                          type: string
                        major:
                          type: string
                        majorAttach:
                          type: string
                        majorAttachCode ":
                          type: string
                        majorCode:
                          type: string
                        majorConcentrations:
                          items:
                            type: object
                  program:
                    type: string
                  programCode:
                    type: string
                  studyPathDescription:
                    type: string
                  termAdmit:
                    type: string
                  termAdmitCode:
                    type: string
                  termCatalog:
                    type: string
                  termCatalogCode:
                    type: string
                  termMatriculate:
                    type: string
                  termMatriculateCode:
                    type: string
              status:
                type: string
              statusObject:
                type: object
                properties:
                  systemRequiredIndicator:
                    type: boolean
                  code:
                    type: string
                  curriculumStatus:
                    type: object
                    properties:
                      _link:
                        type: string
                  version:
                    type: number
                  registrationIndicator:
                    type: boolean
                  description:
                    type: string
              studentObject:
                type: object
                properties:
                  castPreventReg:
                    type: string
                  id:
                    type: string
                  academicStanding:
                    type: string
                  apprenticeship:
                    type: string
                  basicSkill:
                    type: string
                  block:
                    type: string
                  careerPlanning:
                    type: string
                  collegeDual:
                    type: string
                  combinedAcademicStanding:
                    type: string
                  degreeDual:
                    type: string
                  departmentDual:
                    type: string
                  educationGoal:
                    type: string
                  educationLevel:
                    type: string
                  employmentExpectation:
                    type: string
                  expectedGradDate:
                    type: string
                    format: date
                  feeAssessmentRate:
                    type: string
                  fullPartIndicator:
                    type: string
                  gainStatus:
                    type: string
                  gradCreditApprIndicator:
                    type: string
                  incomeRange:
                    type: string
                  leaveFromDate:
                    type: string
                    format: date
                  leaveOfAbsence:
                    type: string
                  leaveToDate:
                    type: string
                    format: date
                  levelDual:
                    type: string
                  majorMinorConcentrationDual:
                    type: string
                  orientationSession:
                    type: string
                  practicalTraining:
                    type: string
                  progressEvaluation:
                    type: string
                  session:
                    type: string
                  site:
                    type: string
                  studentCentricPeriodCycleValidation:
                    type: string
                  termAcademicStanding:
                    type: string
                  termCast:
                    type: string
                  termProgressEvaluation:
                    type: string
                  transferCenter:
                    type: string
                  vocationalEducation:
                    type: string
                  studentStatus:
                    type: string
                  astdPreventReg:
                    type: string
                  residency:
                    type: string
                  version:
                    type: number
                  termGraduation:
                    type: string
                  termEffective:
                    type: string
                  studentType:
                    type: string
                  academicYear:
                    type: string
                  statusAllowReg:
                    type: string
              term:
                type: string
          holdMessage:
            type: string
          holds:
            type: array
            items:
              type: object
          holdSuccess:
            type: boolean
          permitOverride:
            type: array
            items:
              type: object
          hoursEarned:
            type: array
            items:
              type: object
              properties:
                institutionHours:
                  type: number
                levelDescription:
                  type: string
                transferHours:
                  type: number
          readmitSuccess:
            type: boolean
          readmitStatusMessage:
            type: string
          studentStatusMessage:
            type: string
          studentStatusSuccess:
            type: string
          studyPathInformation:
            type: array
            items:
              type: object
              properties:
                studyPathMessage:
                  type: string
                studyPathSuccess:
                  type: string
          termDescription:
            type: string
          timeTicketSuccess:
            type: string
          timeTickets:
            type: array
            items:
              type: object
          validStudent:
            type: boolean
