openapi: 3.0.0
info:
  title: cross-list-meeting-time-instructor-query
  description: API for SSAXMTI administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SSAXMTI
  x-source-domain: Student
  x-source-title: Cross List Meeting Time/Instructor Query
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/cross-list-meeting-time-instructor-query:
    get:
      tags:
        - cross-list-meeting-time-instructor-query
      summary: Return resources from SSAXMTI
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblocTermCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblocXlstGroup
          in: query
          required: false
          schema:
            type: string
        - name: criteria.meetCrn
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetStartDate
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetEndDate
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetMtypCode
          in: query
          required: false
          schema:
            type: string
        - name: criteria.meetDays
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetBeginTime
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetEndTime
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetBldgCode
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetRoomCode
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetSchdCode
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetOverRide
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetCreditHrSess
          in: query
          required: false
          schema:
            type: string
        - name: criteria.ssrmeetCatagory
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cross-list-meeting-time-instructor-query-1.0.0_get_\
                    response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/cross-list-meeting-time-instructor-query:
    post:
      tags:
        - cross-list-meeting-time-instructor-query QAPI (Query by POST)
      summary: Return resources from SSAXMTI
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/cross-list-meeting-time-instructor-query-1.0.0_get_\
                request"
            example:
              keyblocXlstGroup: 1
              keyblocTermCode: 201510
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cross-list-meeting-time-instructor-query-1.0.0_get_\
                    response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    cross-list-meeting-time-instructor-query-1.0.0_get_request:
      type: object
      properties:
        criteria.ssrmeetStartDate:
          title: Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSRMEET_START_DATE"
          format: date-time
          x-lineageReferenceObject: SSRMEET_START_DATE
        criteria.ssrmeetSchdCode:
          title: Schedule Type
          maxLength: 3
          type: string
          description: "Lineage reference object : SSRMEET_SCHD_CODE, Lookup lineage
            reference object : stvschd"
          x-lineageReferenceObject: SSRMEET_SCHD_CODE
          x-lineageLookupReferenceObject: stvschd
        criteria.ssrmeetCatagory:
          title: Session Indicator
          maxLength: 2
          type: string
          description: "Lineage reference object : SSRMEET_CATAGORY"
          x-lineageReferenceObject: SSRMEET_CATAGORY
        criteria.meetCrn:
          title: CRN
          maxLength: 5
          type: string
        criteria.meetDays:
          title: Days
          maxLength: 7
          type: string
        keyblocXlstGroup:
          title: Cross List Group Identifier
          maxLength: 15
          type: string
          description: "Lineage reference object : keyblocXlstGroup"
          x-lineageReferenceObject: keyblocXlstGroup
        criteria.ssrmeetEndDate:
          title: End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SSRMEET_END_DATE"
          format: date-time
          x-lineageReferenceObject: SSRMEET_END_DATE
        keyblocTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCode
          x-lineageLookupReferenceObject: stvterm
        criteria.ssrmeetMtypCode:
          title: Meeting Type
          maxLength: 4
          type: string
          description: "Lineage reference object : SSRMEET_MTYP_CODE, Lookup lineage
            reference object : gtvmtyp"
          x-lineageReferenceObject: SSRMEET_MTYP_CODE
          x-lineageLookupReferenceObject: gtvmtyp
        criteria.ssrmeetBeginTime:
          title: Begin Time
          maxLength: 4
          type: string
          description: "Lineage reference object : SSRMEET_BEGIN_TIME"
          x-lineageReferenceObject: SSRMEET_BEGIN_TIME
        criteria.ssrmeetRoomCode:
          title: Room
          maxLength: 10
          type: string
          description: "Lineage reference object : SSRMEET_ROOM_CODE"
          x-lineageReferenceObject: SSRMEET_ROOM_CODE
        criteria.ssrmeetCreditHrSess:
          title: Session Credits
          maxLength: 9
          type: number
          description: "Lineage reference object : SSRMEET_CREDIT_HR_SESS"
          x-lineageReferenceObject: SSRMEET_CREDIT_HR_SESS
        criteria.ssrmeetOverRide:
          title: Override
          maxLength: 1
          type: string
          description: "Lineage reference object : SSRMEET_OVER_RIDE"
          x-lineageReferenceObject: SSRMEET_OVER_RIDE
        criteria.ssrmeetBldgCode:
          title: Building
          maxLength: 6
          type: string
          description: "Lineage reference object : SSRMEET_BLDG_CODE, Lookup lineage
            reference object : stvbldg"
          x-lineageReferenceObject: SSRMEET_BLDG_CODE
          x-lineageLookupReferenceObject: stvbldg
        criteria.ssrmeetEndTime:
          title: End Time
          maxLength: 4
          type: string
          description: "Lineage reference object : SSRMEET_END_TIME"
          x-lineageReferenceObject: SSRMEET_END_TIME
      x-lineageReferenceObject: SSVXMTI
    cross-list-meeting-time-instructor-query-1.0.0_qapi_post:
      type: object
      properties:
        keyblocTermCode:
          type: string
        keyblocXlstGroup:
          type: string
        criteria.meetCrn:
          type: string
        criteria.ssrmeetStartDate:
          type: string
        criteria.ssrmeetEndDate:
          type: string
        criteria.ssrmeetMtypCode:
          type: string
        criteria.meetDays:
          type: string
        criteria.ssrmeetBeginTime:
          type: string
        criteria.ssrmeetEndTime:
          type: string
        criteria.ssrmeetBldgCode:
          type: string
        criteria.ssrmeetRoomCode:
          type: string
        criteria.ssrmeetSchdCode:
          type: string
        criteria.ssrmeetOverRide:
          type: string
        criteria.ssrmeetCreditHrSess:
          type: string
        criteria.ssrmeetCatagory:
          type: string
    cross-list-meeting-time-instructor-query-1.0.0_get_response:
      type: object
      properties:
        ssvxmti:
          type: array
          items:
            type: object
            properties:
              ssrmeetBeginTime:
                title: Begin Time
                maxLength: 4
                type: string
                description: "Lineage reference object : SSRMEET_BEGIN_TIME"
                x-lineageReferenceObject: SSRMEET_BEGIN_TIME
              ssrmeetRoomCode:
                title: Room
                maxLength: 10
                type: string
                description: "Lineage reference object : SSRMEET_ROOM_CODE"
                x-lineageReferenceObject: SSRMEET_ROOM_CODE
              ssrmeetEndTime:
                title: End Time
                maxLength: 4
                type: string
                description: "Lineage reference object : SSRMEET_END_TIME"
                x-lineageReferenceObject: SSRMEET_END_TIME
              ssrmeetCreditHrSess:
                title: Session Credits
                maxLength: 9
                type: number
                description: "Lineage reference object : SSRMEET_CREDIT_HR_SESS"
                x-lineageReferenceObject: SSRMEET_CREDIT_HR_SESS
              ssrmeetStartDate:
                title: Start Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SSRMEET_START_DATE"
                format: date-time
                x-lineageReferenceObject: SSRMEET_START_DATE
              ssrmeetOverRide:
                title: Override
                maxLength: 1
                type: string
                description: "Lineage reference object : SSRMEET_OVER_RIDE"
                x-lineageReferenceObject: SSRMEET_OVER_RIDE
              meetDays:
                title: Days
                maxLength: 7
                type: string
              ssrmeetEndDate:
                title: End Date
                maxLength: 11
                type: string
                description: "Lineage reference object : SSRMEET_END_DATE"
                format: date-time
                x-lineageReferenceObject: SSRMEET_END_DATE
              ssrmeetBldgCode:
                title: Building
                maxLength: 6
                type: string
                description: "Lineage reference object : SSRMEET_BLDG_CODE, Lookup lineage
                  reference object : stvbldg"
                x-lineageReferenceObject: SSRMEET_BLDG_CODE
                x-lineageLookupReferenceObject: stvbldg
              ssrmeetMtypCode:
                title: Meeting Type
                maxLength: 4
                type: string
                description: "Lineage reference object : SSRMEET_MTYP_CODE, Lookup lineage
                  reference object : gtvmtyp"
                x-lineageReferenceObject: SSRMEET_MTYP_CODE
                x-lineageLookupReferenceObject: gtvmtyp
              ssrmeetCatagory:
                title: Session Indicator
                maxLength: 2
                type: string
                description: "Lineage reference object : SSRMEET_CATAGORY"
                x-lineageReferenceObject: SSRMEET_CATAGORY
              ssrmeetSchdCode:
                title: Schedule Type
                maxLength: 3
                type: string
                description: "Lineage reference object : SSRMEET_SCHD_CODE, Lookup lineage
                  reference object : stvschd"
                x-lineageReferenceObject: SSRMEET_SCHD_CODE
                x-lineageLookupReferenceObject: stvschd
              meetCrn:
                title: CRN
                maxLength: 5
                type: string
              meetInd:
                maxLength: 1
                type: string
            x-lineageReferenceObject: ssvxmti
        sirasgn:
          type: array
          items:
            type: object
            properties:
              percentResponse:
                title: Percent
                maxLength: 5
                type: number
                description: "Lineage reference object : SIRASGN_PERCENT_RESPONSE"
                x-lineageReferenceObject: SIRASGN_PERCENT_RESPONSE
              overRide:
                title: Override Indicator
                maxLength: 1
                type: string
                description: "Lineage reference object : SIRASGN_OVER_RIDE"
                x-lineageReferenceObject: SIRASGN_OVER_RIDE
              name:
                title: Name
                maxLength: 230
                type: string
              category:
                title: Session Indicator
                maxLength: 2
                type: string
                description: "Lineage reference object : SIRASGN_CATEGORY"
                x-lineageReferenceObject: SIRASGN_CATEGORY
              idno:
                title: ID
                maxLength: 9
                type: string
              percentSess:
                title: Percent Session
                maxLength: 5
                type: number
                description: "Lineage reference object : SIRASGN_PERCENT_SESS"
                x-lineageReferenceObject: SIRASGN_PERCENT_SESS
              primaryInd:
                title: Primary Indicator
                maxLength: 1
                type: string
                description: "Lineage reference object : SIRASGN_PRIMARY_IND"
                x-lineageReferenceObject: SIRASGN_PRIMARY_IND
            x-lineageReferenceObject: sirasgn
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
