openapi: 3.0.0
info:
  title: eu-hesa-student-cohort
  description: API for SGACHRT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SGACHRT
  x-source-domain: Student
  x-source-title: Student Cohort (Europe - Hesa)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/eu-hesa-student-cohort:
    post:
      tags:
        - eu-hesa-student-cohort
      summary: Creates a new resource in SGACHRT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/eu-hesa-student-cohort-1.0.0_post_request"
            example:
              chrtCode: 3
              termCodeEff: 201510
              bannerId: A00000718
              sgrchrtTermCodeEff: 201510
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-hesa-student-cohort-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/eu-hesa-student-cohort: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    eu-hesa-student-cohort-1.0.0_post_response:
      type: object
      properties:
        termCodeTo:
          title: To Term
          maxLength: 6
          type: string
        creaCode:
          title: Reason
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRCHRT_CREA_CODE, Lookup lineage
            reference object : stvcrea"
          x-lineageReferenceObject: SGRCHRT_CREA_CODE
          x-lineageLookupReferenceObject: stvcrea
        stspKeySequence:
          title: Study Path
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRCHRT_STSP_KEY_SEQUENCE, Lookup
            lineage reference object : sgvstsp,sgrstsp"
          x-lineageReferenceObject: SGRCHRT_STSP_KEY_SEQUENCE
          x-lineageLookupReferenceObject: sgvstsp,sgrstsp
        termCodeEff:
          title: From Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SGRCHRT_TERM_CODE_EFF"
          x-lineageReferenceObject: SGRCHRT_TERM_CODE_EFF
        bannerId:
          title: ID
          maxLength: 9
          type: string
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SGRCHRT_ACTIVE_IND"
          x-lineageReferenceObject: SGRCHRT_ACTIVE_IND
        bannerName:
          title: Name
          maxLength: 230
          type: string
      x-lineageReferenceObject: sgrchrt
    eu-hesa-student-cohort-1.0.0_post_request:
      type: object
      properties:
        chrtCode:
          title: Cohort Code
          maxLength: 10
          type: string
          description: "Lineage reference object : chrtCode, Lookup lineage reference
            object : stvchrt"
          x-lineageReferenceObject: chrtCode
          x-lineageLookupReferenceObject: stvchrt
        termCodeEff:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : termCodeEff, Lookup lineage reference
            object : stvterm"
          x-lineageReferenceObject: termCodeEff
          x-lineageLookupReferenceObject: stvterm
        creaCode:
          title: Reason
          maxLength: 30
          type: string
          description: "Lineage reference object : SGRCHRT_CREA_CODE, Lookup lineage
            reference object : stvcrea"
          x-lineageReferenceObject: SGRCHRT_CREA_CODE
          x-lineageLookupReferenceObject: stvcrea
        bannerId:
          title: ID
          maxLength: 9
          type: string
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SGRCHRT_ACTIVE_IND"
          x-lineageReferenceObject: SGRCHRT_ACTIVE_IND
        sgrchrtTermCodeEff:
          title: From Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SGRCHRT_TERM_CODE_EFF"
          x-lineageReferenceObject: SGRCHRT_TERM_CODE_EFF
        sgrchrtActiveInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SGRCHRT_ACTIVE_IND"
          x-lineageReferenceObject: SGRCHRT_ACTIVE_IND
      x-lineageReferenceObject: SGRCHRT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
