openapi: 3.0.0
info:
  title: finance-application-distribution-single-payment
  description: API for TFAADSP administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: TFAADSP
  x-source-domain: Finance
  x-source-title: Application Distribution of Single Payment - Finance
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/finance-application-distribution-single-payment:
    get:
      tags:
        - finance-application-distribution-single-payment
      summary: Return resources from TFAADSP
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: amount
          in: query
          required: false
          schema:
            type: string
        - name: addressCode
          in: query
          required: false
          schema:
            type: string
        - name: detailCode
          in: query
          description: Detail Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRACCD_DETAIL_CODE
        - name: tagOption
          in: query
          required: false
          schema:
            type: string
        - name: addressSeqno
          in: query
          required: false
          schema:
            type: string
        - name: invNumberPaid
          in: query
          description: Invoice Number Paid
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRACCD_INV_NUMBER_PAID
        - name: paymentId
          in: query
          required: false
          schema:
            type: string
        - name: documentNumber
          in: query
          description: Document
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRACCD_DOCUMENT_NUMBER
        - name: holdPassword
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finance-application-distribution-single-payment-1.0\
                    .0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/finance-application-distribution-single-payment:
    post:
      tags:
        - finance-application-distribution-single-payment QAPI (Query by POST)
      summary: Return resources from TFAADSP
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/finance-application-distribution-single-payment-1.0\
                .0_get_request"
            example:
              addressCode: BI
              amount: 100
              id: A00075953
              addressSeqno: 1
              detailCode: 0TV
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finance-application-distribution-single-payment-1.0\
                    .0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    finance-application-distribution-single-payment-1.0.0_get_response:
      type: object
      properties:
        tbrcrcp:
          type: array
          items:
            type: object
            properties:
              message:
                maxLength: 1
                type: string
            x-lineageReferenceObject: tbrcrcp
        tbraccd:
          type: array
          items:
            required:
              - desc
              - detailCode
              - effectiveDate
              - srceCode
            type: object
            properties:
              srceCode:
                title: Source
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRACCD_SRCE_CODE, Lookup lineage
                  reference object : ttvsrce"
                x-lineageReferenceObject: TBRACCD_SRCE_CODE
                x-lineageLookupReferenceObject: ttvsrce
              documentNumber:
                title: Document
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRACCD_DOCUMENT_NUMBER"
                x-lineageReferenceObject: TBRACCD_DOCUMENT_NUMBER
              dueDate:
                title: Due Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRACCD_DUE_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_DUE_DATE
              statementDate:
                title: Statement Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRACCD_STATEMENT_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_STATEMENT_DATE
              paymentAmount:
                title: Split Payment
                maxLength: 17
                type: number
              activityDate:
                title: Activity Date
                maxLength: 26
                type: string
                description: "Lineage reference object : TBRACCD_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_ACTIVITY_DATE
              balance:
                title: Balance
                maxLength: 17
                type: number
                description: "Lineage reference object : TBRACCD_BALANCE"
                x-lineageReferenceObject: TBRACCD_BALANCE
              crossrefNumber:
                title: Cross Reference Num
                maxLength: 8
                type: number
                description: "Lineage reference object : TBRACCD_CROSSREF_NUMBER"
                x-lineageReferenceObject: TBRACCD_CROSSREF_NUMBER
              acctFeedInd:
                title: Feed Indicator
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRACCD_ACCT_FEED_IND"
                x-lineageReferenceObject: TBRACCD_ACCT_FEED_IND
              invoiceNumber:
                title: Invoice Number
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRACCD_INVOICE_NUMBER"
                x-lineageReferenceObject: TBRACCD_INVOICE_NUMBER
              transDate:
                title: Transaction Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRACCD_TRANS_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_TRANS_DATE
              chargeAmount:
                title: Charge
                maxLength: 17
                type: number
              tranNumberPaid:
                title: Transaction Number Paid
                maxLength: 8
                type: number
                description: "Lineage reference object : TBRACCD_TRAN_NUMBER_PAID"
                x-lineageReferenceObject: TBRACCD_TRAN_NUMBER_PAID
              checkTpay:
                maxLength: 3
                type: string
              receiptNumber:
                title: Receipt
                maxLength: 8
                type: number
                description: "Lineage reference object : TBRACCD_RECEIPT_NUMBER"
                x-lineageReferenceObject: TBRACCD_RECEIPT_NUMBER
              feedDate:
                title: Feed Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRACCD_FEED_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_FEED_DATE
              cshrEndDate:
                title: Session End Date
                maxLength: 17
                type: string
                description: "Lineage reference object : TBRACCD_CSHR_END_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_CSHR_END_DATE
              tranNumber:
                title: Transaction Number
                maxLength: 8
                type: number
                description: "Lineage reference object : TBRACCD_TRAN_NUMBER"
                x-lineageReferenceObject: TBRACCD_TRAN_NUMBER
              billDate:
                title: Bill Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRACCD_BILL_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_BILL_DATE
              invNumberPaid:
                title: Invoice Number Paid
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRACCD_INV_NUMBER_PAID"
                x-lineageReferenceObject: TBRACCD_INV_NUMBER_PAID
              crossrefId:
                title: Cross Reference ID
                maxLength: 9
                type: string
              detailCode:
                title: Detail Code
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRACCD_DETAIL_CODE, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: TBRACCD_DETAIL_CODE
                x-lineageLookupReferenceObject: tbbdetc
              feedDocCode:
                title: Feed Document
                maxLength: 8
                type: string
                description: "Lineage reference object : TBRACCD_FEED_DOC_CODE"
                x-lineageReferenceObject: TBRACCD_FEED_DOC_CODE
              sessionNumber:
                title: Session Number
                maxLength: 38
                type: number
                description: "Lineage reference object : TBRACCD_SESSION_NUMBER"
                x-lineageReferenceObject: TBRACCD_SESSION_NUMBER
              user:
                title: User ID
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRACCD_USER"
                x-lineageReferenceObject: TBRACCD_USER
              effectiveDate:
                title: Effective Date
                maxLength: 11
                type: string
                description: "Lineage reference object : TBRACCD_EFFECTIVE_DATE"
                format: date-time
                x-lineageReferenceObject: TBRACCD_EFFECTIVE_DATE
              desc:
                title: Description
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRACCD_DESC"
                x-lineageReferenceObject: TBRACCD_DESC
            x-lineageReferenceObject: tbraccd
    finance-application-distribution-single-payment-1.0.0_get_request:
      type: object
      properties:
        addressCode:
          title: Address Type
          maxLength: 2
          type: string
          description: "Lineage reference object : addressCode"
          x-lineageReferenceObject: addressCode
        amount:
          title: Amount
          maxLength: 17
          type: number
          description: "Lineage reference object : amount"
          x-lineageReferenceObject: amount
        holdPassword:
          title: Holds
          maxLength: 3
          type: string
          description: "Lineage reference object : holdPassword"
          x-lineageReferenceObject: holdPassword
        paymentId:
          title: Payment Number
          maxLength: 20
          type: string
          description: "Lineage reference object : paymentId"
          x-lineageReferenceObject: paymentId
        documentNumber:
          title: Document
          maxLength: 8
          type: string
          description: "Lineage reference object : documentNumber"
          x-lineageReferenceObject: documentNumber
        tagOption:
          maxLength: 1
          type: number
          description: "Lineage reference object : tagOption"
          x-lineageReferenceObject: tagOption
        invNumberPaid:
          title: Invoice Paid Number
          maxLength: 8
          type: string
          description: "Lineage reference object : invNumberPaid"
          x-lineageReferenceObject: invNumberPaid
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        addressSeqno:
          title: Sequence
          maxLength: 2
          type: number
          description: "Lineage reference object : addressSeqno"
          x-lineageReferenceObject: addressSeqno
        detailCode:
          title: Detail Code
          maxLength: 30
          type: string
          description: "Lineage reference object : detailCode, Lookup lineage reference
            object : tbbdetc"
          x-lineageReferenceObject: detailCode
          x-lineageLookupReferenceObject: tbbdetc
      x-lineageReferenceObject: KEY_BLOCK
    finance-application-distribution-single-payment-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        amount:
          type: string
        addressCode:
          type: string
        detailCode:
          title: Detail Code
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRACCD_DETAIL_CODE, Lookup lineage
            reference object : tbbdetc"
          x-lineageReferenceObject: TBRACCD_DETAIL_CODE
          x-lineageLookupReferenceObject: tbbdetc
        tagOption:
          type: string
        addressSeqno:
          type: string
        invNumberPaid:
          title: Invoice Number Paid
          maxLength: 8
          type: string
          description: "Lineage reference object : TBRACCD_INV_NUMBER_PAID"
          x-lineageReferenceObject: TBRACCD_INV_NUMBER_PAID
        paymentId:
          type: string
        documentNumber:
          title: Document
          maxLength: 8
          type: string
          description: "Lineage reference object : TBRACCD_DOCUMENT_NUMBER"
          x-lineageReferenceObject: TBRACCD_DOCUMENT_NUMBER
        holdPassword:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
