openapi: 3.0.0
info:
  title: aid-year-based-designators
  description: API for TTVTEXT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: TTVTEXT
  x-source-domain: Student
  x-source-title: Comment Text Validation Form
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/aid-year-based-designators:
    put:
      tags:
        - aid-year-based-designators
      summary: Updates an existing resource in TTVTEXT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/aid-year-based-designators-1.0.0_put_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/aid-year-based-designators-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - aid-year-based-designators
      summary: Creates a new resource in TTVTEXT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/aid-year-based-designators-1.0.0_post_request"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/aid-year-based-designators-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/aid-year-based-designators: {}
components:
  schemas:
    aid-year-based-designators-1.0.0_post_request:
      required:
        - code
        - shortDesc
        - comment
      type: object
      properties:
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : TTVTEXT_CODE"
          x-lineageReferenceObject: TTVTEXT_CODE
        shortDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_SHORT_DESC"
          x-lineageReferenceObject: TTVTEXT_SHORT_DESC
        comment:
          title: Comment
          maxLength: 32000
          type: string
          description: "Lineage reference object : TTVTEXT_COMMENT"
          x-lineageReferenceObject: TTVTEXT_COMMENT
      x-lineageReferenceObject: TTVTEXT
    aid-year-based-designators-1.0.0_put_response:
      required:
        - code
        - comment
        - shortDesc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVTEXT_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVTEXT_ACTIVITY_DATE
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : TTVTEXT_CODE"
          x-lineageReferenceObject: TTVTEXT_CODE
        comment:
          title: Comment
          maxLength: 32000
          type: string
          description: "Lineage reference object : TTVTEXT_COMMENT"
          x-lineageReferenceObject: TTVTEXT_COMMENT
        shortDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_SHORT_DESC"
          x-lineageReferenceObject: TTVTEXT_SHORT_DESC
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_USER_ID"
          x-lineageReferenceObject: TTVTEXT_USER_ID
      x-lineageReferenceObject: ttvtext
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    aid-year-based-designators-1.0.0_post_response:
      required:
        - code
        - comment
        - shortDesc
      type: object
      properties:
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : TTVTEXT_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: TTVTEXT_ACTIVITY_DATE
        code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : TTVTEXT_CODE"
          x-lineageReferenceObject: TTVTEXT_CODE
        comment:
          title: Comment
          maxLength: 32000
          type: string
          description: "Lineage reference object : TTVTEXT_COMMENT"
          x-lineageReferenceObject: TTVTEXT_COMMENT
        shortDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_SHORT_DESC"
          x-lineageReferenceObject: TTVTEXT_SHORT_DESC
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_USER_ID"
          x-lineageReferenceObject: TTVTEXT_USER_ID
      x-lineageReferenceObject: ttvtext
    aid-year-based-designators-1.0.0_put_request:
      required:
        - criteria.code
        - criteria.shortDesc
        - criteria.comment
        - shortDesc
        - comment
      type: object
      properties:
        criteria.code:
          title: Code
          maxLength: 10
          type: string
          description: "Lineage reference object : TTVTEXT_CODE"
          x-lineageReferenceObject: TTVTEXT_CODE
        criteria.shortDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_SHORT_DESC"
          x-lineageReferenceObject: TTVTEXT_SHORT_DESC
        shortDesc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TTVTEXT_SHORT_DESC"
          x-lineageReferenceObject: TTVTEXT_SHORT_DESC
        comment:
          title: Comment
          maxLength: 32000
          type: string
          description: "Lineage reference object : TTVTEXT_COMMENT"
          x-lineageReferenceObject: TTVTEXT_COMMENT
        criteria.comment:
          title: Comment
          maxLength: 32000
          type: string
          description: "Lineage reference object : TTVTEXT_COMMENT"
          x-lineageReferenceObject: TTVTEXT_COMMENT
      x-lineageReferenceObject: TTVTEXT
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
