openapi: 3.0.0
info:
  title: area-requirements-area-group-attachment-rules
  description: API for SMAAREA administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SMAAREA
  x-source-domain: Student
  x-source-title: Area Requirements
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/area-requirements-area-group-attachment-rules:
    get:
      tags:
        - area-requirements-area-group-attachment-rules
      summary: Return resources from SMAAREA
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: area
          in: query
          required: false
          schema:
            type: string
        - name: keyblckTermCode
          in: query
          required: false
          schema:
            type: string
        - name: rule
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/area-requirements-area-group-attachment-rules-1.0.0\
                    _get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/area-requirements-area-group-attachment-rules:
    post:
      tags:
        - area-requirements-area-group-attachment-rules QAPI (Query by POST)
      summary: Return resources from SMAAREA
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/area-requirements-area-group-attachment-rules-1.0.0\
                _get_request"
            example:
              area: HRZNREGPQG
              keyblckTermCode: 201410
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/area-requirements-area-group-attachment-rules-1.0.0\
                    _get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    area-requirements-area-group-attachment-rules-1.0.0_qapi_post:
      required:
        - rule
      type: object
      properties:
        area:
          type: string
        keyblckTermCode:
          type: string
        rule:
          type: string
    area-requirements-area-group-attachment-rules-1.0.0_get_response:
      type: object
      properties:
        smbagrl:
          type: array
          items:
            required:
              - desc
              - keyRule
            type: object
            properties:
              reqNumbCond:
                title: Required Number of Conditions
                maxLength: 5
                type: number
                description: "Lineage reference object : SMBAGRL_REQ_NUMB_COND"
                x-lineageReferenceObject: SMBAGRL_REQ_NUMB_COND
              desc:
                title: Description
                maxLength: 30
                type: string
                description: "Lineage reference object : SMBAGRL_DESC"
                x-lineageReferenceObject: SMBAGRL_DESC
              keyRule:
                title: Rule
                maxLength: 10
                type: string
                description: "Lineage reference object : SMBAGRL_KEY_RULE"
                x-lineageReferenceObject: SMBAGRL_KEY_RULE
            x-lineageReferenceObject: smbagrl
        smbagrl_ctrl_block:
          type: array
          items:
            type: object
            properties:
              smaagrlTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : SMAAGRL_TERM_CODE_TO"
                x-lineageReferenceObject: SMAAGRL_TERM_CODE_TO
              smaagrlTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : SMAAGRL_TERM_CODE_FROM"
                x-lineageReferenceObject: SMAAGRL_TERM_CODE_FROM
            x-lineageReferenceObject: smbagrl_ctrl_block
        smragrl:
          type: array
          items:
            required:
              - attrReuseInd
              - crseReuseInd
            type: object
            properties:
              set:
                title: Set
                maxLength: 3
                type: string
                description: "Lineage reference object : SMRAGRL_SET"
                x-lineageReferenceObject: SMRAGRL_SET
              crseReuseInd:
                title: Course Re-Use
                maxLength: 1
                type: string
                description: "Lineage reference object : SMRAGRL_CRSE_REUSE_IND"
                x-lineageReferenceObject: SMRAGRL_CRSE_REUSE_IND
              withinInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : SMRAGRL_WITHIN_IND"
                x-lineageReferenceObject: SMRAGRL_WITHIN_IND
              asterisk:
                title: "*"
                maxLength: 1
                type: string
              rule:
                title: Rule
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRAGRL_RULE"
                x-lineageReferenceObject: SMRAGRL_RULE
              cond:
                title: Condition
                maxLength: 3
                type: number
              attrReuseInd:
                title: Attribute Re-Use
                maxLength: 1
                type: string
                description: "Lineage reference object : SMRAGRL_ATTR_REUSE_IND"
                x-lineageReferenceObject: SMRAGRL_ATTR_REUSE_IND
              subset:
                title: Subset
                maxLength: 3
                type: number
                description: "Lineage reference object : SMRAGRL_SUBSET"
                x-lineageReferenceObject: SMRAGRL_SUBSET
              yearRule:
                title: Year Rule
                maxLength: 2
                type: number
                description: "Lineage reference object : SMRAGRL_YEAR_RULE"
                x-lineageReferenceObject: SMRAGRL_YEAR_RULE
              group:
                title: Group
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRAGRL_GROUP"
                x-lineageReferenceObject: SMRAGRL_GROUP
            x-lineageReferenceObject: smragrl
        smragrt:
          type: array
          items:
            type: object
            properties:
              prntCode:
                title: Print
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRAGRT_PRNT_CODE, Lookup lineage
                  reference object : stvprnt"
                x-lineageReferenceObject: SMRAGRT_PRNT_CODE
                x-lineageLookupReferenceObject: stvprnt
              text:
                title: Text
                maxLength: 60
                type: string
                description: "Lineage reference object : SMRAGRT_TEXT"
                x-lineageReferenceObject: SMRAGRT_TEXT
            x-lineageReferenceObject: smragrt
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    area-requirements-area-group-attachment-rules-1.0.0_get_request:
      type: object
      properties:
        area:
          title: Area
          maxLength: 30
          type: string
          description: "Lineage reference object : AREA, Lookup lineage reference object :
            smbagen,smralib"
          x-lineageReferenceObject: AREA
          x-lineageLookupReferenceObject: smbagen,smralib
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : KEYBLCK_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: KEYBLCK_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        rule:
          title: Rule
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRAGAM_RULE"
          x-lineageReferenceObject: SMRAGAM_RULE
      x-lineageReferenceObject: SMRAGAM
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
