openapi: 3.0.0
info:
  title: block-schedule-section-query
  description: API for SSABSCQ administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SSABSCQ
  x-source-domain: Student
  x-source-title: Block Schedule Section Query
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/block-schedule-section-query:
    get:
      tags:
      - block-schedule-section-query
      summary: Return resources from SSABSCQ
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
      - name: keyblocTermCode
        in: query
        required: false
        schema:
          type: string
      - name: keyblocBlckCode
        in: query
        required: false
        schema:
          type: string
      - name: queryCrn
        in: query
        description: CRN
        required: false
        schema:
          type: string
      - name: multiBlock
        in: query
        description: Multiple Blocks
        required: false
        schema:
          type: string
      - name: ssbsectSubjCode
        in: query
        description: Subject
        required: false
        schema:
          type: string
      - name: ssbsectCrseNumb
        in: query
        description: Course
        required: false
        schema:
          type: string
      - name: ssbsectSeqNumb
        in: query
        description: Section
        required: false
        schema:
          type: string
      - name: ssbsectSstsCode
        in: query
        description: Status
        required: false
        schema:
          type: string
      - name: ssbsectPtrmCode
        in: query
        description: Part of Term
        required: false
        schema:
          type: string
      - name: ssbsectCreditHrs
        in: query
        description: Credit Hours
        required: false
        schema:
          type: string
      - name: ssbsectBillHrs
        in: query
        description: Billing Hours
        required: false
        schema:
          type: string
      - name: ssbsectGmodCode
        in: query
        description: Grade Mode
        required: false
        schema:
          type: string
      - name: apprInd
        in: query
        description: Special Approval
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SSRBLCK_APPR_IND
      - name: ssbsectCampCode
        in: query
        description: Campus
        required: false
        schema:
          type: string
      - name: ssbsectLinkIdent
        in: query
        description: Link Identifier
        required: false
        schema:
          type: string
      - name: xlstGroup
        in: query
        description: Cross List
        required: false
        schema:
          type: string
      - name: ssbsectSchdCode
        in: query
        description: Schedule Type
        required: false
        schema:
          type: string
      - name: ssbsectInsmCode
        in: query
        description: Instructional Method
        required: false
        schema:
          type: string
      - name: ssbsectRegFromDate
        in: query
        description: Registration From Date
        required: false
        schema:
          type: string
      - name: ssbsectRegToDate
        in: query
        description: Registration To Date
        required: false
        schema:
          type: string
      - name: ssbsectMaxEnrl
        in: query
        description: Maximum Enrollment
        required: false
        schema:
          type: string
      - name: ssbsectEnrl
        in: query
        description: Actual Enrollment
        required: false
        schema:
          type: string
      - name: ssbsectSeatsAvail
        in: query
        description: Remaining Enrollment
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/block-schedule-section-query-1.0.0_get_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/block-schedule-section-query:
    post:
      tags:
      - block-schedule-section-query QAPI (Query by POST)
      summary: Return resources from SSABSCQ
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/block-schedule-section-query-1.0.0_qapi_post_request'
            example:
              keyblocTermCode: 201520
              keyblocBlckCode: 11
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/block-schedule-section-query-1.0.0_qapi_post_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
components:
  schemas:
    block-schedule-section-query-1.0.0_get_response:
      type: object
      properties:
        queryCrn:
          title: CRN
          maxLength: 5
          type: string
        ssbsectCreditHrs:
          title: Credit Hours
          maxLength: 9
          type: number
        xlstGroup:
          title: Cross List
          maxLength: 15
          type: string
        ssbsectSeqNumb:
          title: Section
          maxLength: 3
          type: string
        multiBlock:
          title: Multiple Blocks
          maxLength: 1
          type: string
        ssbsectSubjCode:
          title: Subject
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvsubj"
          x-lineageLookupReferenceObject: stvsubj
        ssbsectCrseNumb:
          title: Course
          maxLength: 5
          type: string
        ssbsectSchdCode:
          title: Schedule Type
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvschd"
          x-lineageLookupReferenceObject: stvschd
        ssbsectSeatsAvail:
          title: Remaining Enrollment
          maxLength: 4
        ssbsectSstsCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvssts"
          x-lineageLookupReferenceObject: stvssts
        ssbsectCampCode:
          title: Campus
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvcamp"
          x-lineageLookupReferenceObject: stvcamp
        ssbsectEnrl:
          title: Actual Enrollment
          maxLength: 4
        ssbsectPtrmCode:
          title: Part of Term
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvptrm"
          x-lineageLookupReferenceObject: stvptrm
        apprInd:
          title: Special Approval
          maxLength: 1
          type: string
          description: "Lineage reference object : SSRBLCK_APPR_IND"
          x-lineageReferenceObject: SSRBLCK_APPR_IND
        courseAlias:
          title: Course Alias
          maxLength: 20
          type: string
        ssbsectMaxEnrl:
          title: Maximum Enrollment
          maxLength: 4
        ssbsectRegFromDate:
          title: Registration From Date
          maxLength: 11
          type: string
          format: date-time
        ssbsectRegToDate:
          title: Registration To Date
          maxLength: 11
          type: string
          format: date-time
        ssbsectGmodCode:
          title: Grade Mode
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvgmod"
          x-lineageLookupReferenceObject: stvgmod
        ssbsectLinkIdent:
          title: Link Identifier
          maxLength: 2
          type: string
        ssbsectBillHrs:
          title: Billing Hours
          maxLength: 9
          type: number
        ssbsectInsmCode:
          title: Instructional Method
          maxLength: 5
          type: string
      x-lineageReferenceObject: ssrblck
    block-schedule-section-query-1.0.0_qapi_post_request:
      type: object
      properties:
        queryCrn:
          title: CRN
          maxLength: 5
          type: string
        ssbsectCreditHrs:
          title: Credit Hours
          maxLength: 9
          type: number
        xlstGroup:
          title: Cross List
          maxLength: 15
          type: string
        keyblocTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTermCode, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCode
          x-lineageLookupReferenceObject: stvterm
        ssbsectSeqNumb:
          title: Section
          maxLength: 3
          type: string
        multiBlock:
          title: Multiple Blocks
          maxLength: 1
          type: string
        ssbsectSubjCode:
          title: Subject
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvsubj"
          x-lineageLookupReferenceObject: stvsubj
        keyblocBlckCode:
          title: Block
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocBlckCode, Lookup lineage\
            \ reference object : stvblck"
          x-lineageReferenceObject: keyblocBlckCode
          x-lineageLookupReferenceObject: stvblck
        ssbsectCrseNumb:
          title: Course
          maxLength: 5
          type: string
        ssbsectSstsCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvssts"
          x-lineageLookupReferenceObject: stvssts
        ssbsectSchdCode:
          title: Schedule Type
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvschd"
          x-lineageLookupReferenceObject: stvschd
        ssbsectSeatsAvail:
          title: Remaining Enrollment
          maxLength: 4
        ssbsectCampCode:
          title: Campus
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvcamp"
          x-lineageLookupReferenceObject: stvcamp
        ssbsectPtrmCode:
          title: Part of Term
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvptrm"
          x-lineageLookupReferenceObject: stvptrm
        apprInd:
          title: Special Approval
          maxLength: 1
          type: string
          description: "Lineage reference object : SSRBLCK_APPR_IND"
          x-lineageReferenceObject: SSRBLCK_APPR_IND
        ssbsectEnrl:
          title: Actual Enrollment
          maxLength: 4
        ssbsectRegFromDate:
          title: Registration From Date
          maxLength: 11
          type: string
          format: date-time
        ssbsectMaxEnrl:
          title: Maximum Enrollment
          maxLength: 4
        ssbsectRegToDate:
          title: Registration To Date
          maxLength: 11
          type: string
          format: date-time
        ssbsectGmodCode:
          title: Grade Mode
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvgmod"
          x-lineageLookupReferenceObject: stvgmod
        ssbsectLinkIdent:
          title: Link Identifier
          maxLength: 2
          type: string
        ssbsectBillHrs:
          title: Billing Hours
          maxLength: 9
          type: number
        ssbsectInsmCode:
          title: Instructional Method
          maxLength: 5
          type: string
      x-lineageReferenceObject: SSRBLCK
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
    block-schedule-section-query-1.0.0_qapi_post_response:
      type: object
      properties:
        queryCrn:
          title: CRN
          maxLength: 5
          type: string
        ssbsectCreditHrs:
          title: Credit Hours
          maxLength: 9
          type: number
        xlstGroup:
          title: Cross List
          maxLength: 15
          type: string
        ssbsectSeqNumb:
          title: Section
          maxLength: 3
          type: string
        multiBlock:
          title: Multiple Blocks
          maxLength: 1
          type: string
        ssbsectSubjCode:
          title: Subject
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvsubj"
          x-lineageLookupReferenceObject: stvsubj
        ssbsectCrseNumb:
          title: Course
          maxLength: 5
          type: string
        ssbsectSchdCode:
          title: Schedule Type
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvschd"
          x-lineageLookupReferenceObject: stvschd
        ssbsectSeatsAvail:
          title: Remaining Enrollment
          maxLength: 4
        ssbsectSstsCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvssts"
          x-lineageLookupReferenceObject: stvssts
        ssbsectCampCode:
          title: Campus
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvcamp"
          x-lineageLookupReferenceObject: stvcamp
        ssbsectEnrl:
          title: Actual Enrollment
          maxLength: 4
        ssbsectPtrmCode:
          title: Part of Term
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvptrm"
          x-lineageLookupReferenceObject: stvptrm
        apprInd:
          title: Special Approval
          maxLength: 1
          type: string
          description: "Lineage reference object : SSRBLCK_APPR_IND"
          x-lineageReferenceObject: SSRBLCK_APPR_IND
        courseAlias:
          title: Course Alias
          maxLength: 20
          type: string
        ssbsectMaxEnrl:
          title: Maximum Enrollment
          maxLength: 4
        ssbsectRegFromDate:
          title: Registration From Date
          maxLength: 11
          type: string
          format: date-time
        ssbsectRegToDate:
          title: Registration To Date
          maxLength: 11
          type: string
          format: date-time
        ssbsectGmodCode:
          title: Grade Mode
          maxLength: 30
          type: string
          description: "Lookup lineage reference object : stvgmod"
          x-lineageLookupReferenceObject: stvgmod
        ssbsectLinkIdent:
          title: Link Identifier
          maxLength: 2
          type: string
        ssbsectBillHrs:
          title: Billing Hours
          maxLength: 9
          type: number
        ssbsectInsmCode:
          title: Instructional Method
          maxLength: 5
          type: string
      x-lineageReferenceObject: ssrblck
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer