openapi: 3.0.0
info:
  title: Student Financial Aid Award Payments
  description: >-
    Financial aid award payments applied to students&#x27; accounts.


    Please refer to "API Integration Configuration Settings" section in the Banner Ethos API Handbook for details on API configuration settings that needs to be configured for this API.
  version: "11.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Financial Aid
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-financial-aid-award-payments:
    get:
      summary: Return all resources from TBRACCD
      description: Returns a paged listing of all the student financial aid award
        payments from TBRACCD table where the award fund (RPRAWRD_FUND_CODE)
        associated with the payment is assigned to a fund category
        (RFRFCAT_FCAT_CODE) that is mapped as 'nonRestricted' in the API
        configuration setting 'FINANCIAL.AID.FUNDS.PRIVACY'.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_S_F_AID_AWARD_PAYMENTS
      tags:
        - student-financial-aid-award-payments
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-student-financial-aid-award-payments.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/student-financial-aid-award-payments/{id}:
    get:
      summary: Return the requested resource from TBRACCD
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_S_F_AID_AWARD_PAYMENTS
      tags:
        - student-financial-aid-award-payments
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Student Financial Aid Award Payments for use
            in all external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v11+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-student-financial-aid-award-payments.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-student-financial-aid-award-payments.json:
      title: Student Financial Aid Award Payments
      description: Financial aid award payments applied to students' accounts.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the student financial aid award payment.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: TSRTGID_AWARD_GUID(TSRTGID)
        award:
          title: Award
          description: The financial aid award associated with the payment.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Award.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: student-financial-aid-awards 
              x-lineageReferenceObject: RPRAWRD_GUID(RPRAWRD)
          additionalProperties: false
          required:
            - id
        fundingDestination:
          title: Funding Destination
          description: The accounting code of the funding destination associated with the
            payment.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Funding Destination.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: accounting-codes 
                  x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = accounting-codes) 
                  x-lineageDerivedLogic: Display the fundingDestination GUID from GORGUID where GORGUID_LDM_NAME is 'accounting-codes' and GORGUID_DOMAIN_KEY = TBRACCD_DETAIL_CODE
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        paidOn:
          title: Paid On
          description: The date of the payment.
          type: string
          format: date
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])$
          x-lineageReferenceObject: TBRACCD_EFFECTIVE_DATE(TBRACCD)
        amount:
          title: Amount
          description: The amount of the payment.
          format: currency
          type: object
          properties:
            value:
              title: Value
              description: The monetary value
              type: number
              x-lineageReferenceObject: TBRACCD_AMOUNT(TBRACCD)
            currency:
              title: Currency
              description: The ISO 4217 currency code
              enum:
                - AED
                - AFN
                - ALL
                - AMD
                - ANG
                - AOA
                - ARS
                - AUD
                - AWG
                - AZN
                - BAM
                - BBD
                - BDT
                - BGN
                - BHD
                - BIF
                - BMD
                - BND
                - BOB
                - BRL
                - BSD
                - BTN
                - BWP
                - BYR
                - BZD
                - CAD
                - CDF
                - CHF
                - CLP
                - CNY
                - COP
                - CRC
                - CUC
                - CUP
                - CVE
                - CZK
                - DJF
                - DKK
                - DOP
                - DZD
                - EGP
                - ERN
                - ETB
                - EUR
                - FJD
                - FKP
                - GBP
                - GEL
                - GHS
                - GIP
                - GMD
                - GNF
                - GTQ
                - GYD
                - HKD
                - HNL
                - HRK
                - HTG
                - HUF
                - IDR
                - ILS
                - INR
                - IQD
                - IRR
                - ISK
                - JMD
                - JOD
                - JPY
                - KES
                - KGS
                - KHR
                - KMF
                - KPW
                - KRW
                - KWD
                - KYD
                - KZT
                - LAK
                - LBP
                - LKR
                - LRD
                - LSL
                - LYD
                - MAD
                - MDL
                - MGA
                - MKD
                - MMK
                - MNT
                - MOP
                - MRO
                - MUR
                - MVR
                - MWK
                - MXN
                - MYR
                - MZN
                - NAD
                - NGN
                - NIO
                - NOK
                - NPR
                - NZD
                - OMR
                - PAB
                - PEN
                - PGK
                - PHP
                - PKR
                - PLN
                - PYG
                - QAR
                - RON
                - RSD
                - RUB
                - RWF
                - SAR
                - SBD
                - SCR
                - SDG
                - SEK
                - SGD
                - SHP
                - SLL
                - SOS
                - SRD
                - SSP
                - STD
                - SVC
                - SYP
                - SZL
                - THB
                - TJS
                - TMT
                - TND
                - TOP
                - TRY
                - TTD
                - TWD
                - TZS
                - UAH
                - UGX
                - USD
                - UYU
                - UZS
                - VEF
                - VND
                - VUV
                - WST
                - XAF
                - XCD
                - XOF
                - XPF
                - YER
                - ZAR
                - ZMW
                - ZWL
              type: string
              x-lineageReferenceObject: GUBINST_BASE_CURR_CODE(GUBINST)
          additionalProperties: false
          required:
            - value
            - currency
        academicPeriod:
          title: Academic Period
          description: The academic period associated with the payment.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Academic Period.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: academic-periods 
                  x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = term) 
                  x-lineageDerivedLogic: Display the academicPeriod GUID from GORGUID where GORGUID_LDM_NAME is 'terms' and GORGUID_DOMAIN_KEY = TBRACCD_TERM_CODE
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        awardPeriod:
          title: Award Period
          description: The financial aid award period associated with the payment.
          type: object
          properties:
            id:
              title: ID
              description: The global identifier for the Award Period.
              type: string
              format: guid
              pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
              x-lineageLookupReferenceObject: financial-aid-award-periods 
              x-lineageReferenceObject: RORTPRD_GUID(RORTPRD)
          additionalProperties: false
          required:
            - id
      required:
        - id
        - award
        - paidOn
        - amount
        - awardPeriod
      additionalProperties: false
