openapi: 3.0.0
info:
  title: benefit-or-deduction-grouping-rule
  description: API for PTRBDPG administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: PTRBDPG
  x-source-domain: Human Resources
  x-source-title: Benefit/Deduction Grouping Rules
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/benefit-or-deduction-grouping-rule:
    get:
      tags:
        - benefit-or-deduction-grouping-rule
      summary: Return resources from PTRBDPG
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: bdpgCode
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/benefit-or-deduction-grouping-rule-1.0.0_get_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/benefit-or-deduction-grouping-rule:
    post:
      tags:
        - benefit-or-deduction-grouping-rule QAPI (Query by POST)
      summary: Return resources from PTRBDPG
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/benefit-or-deduction-grouping-rule-1.0.0_get_reques\
                t"
            example:
              bdpgCode: HL
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/benefit-or-deduction-grouping-rule-1.0.0_get_respon\
                    se"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    benefit-or-deduction-grouping-rule-1.0.0_get_response:
      type: object
      properties:
        ptrbdsg:
          type: array
          items:
            required:
              - code
              - desc
            type: object
            properties:
              webCvgUpdInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_CVG_UPD_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_CVG_UPD_IND
              webCvgSelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_CVG_SEL_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_CVG_SEL_IND
              webEmprInd:
                title: Display Employer Amounts
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_EMPR_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_EMPR_IND
              code:
                title: Secondary Group
                maxLength: 4
                type: string
                description: "Lineage reference object : PTRBDSG_CODE"
                x-lineageReferenceObject: PTRBDSG_CODE
              webOpenInd:
                title: Include in Open and New Hire Enrollment
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_OPEN_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_OPEN_IND
              webSelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_SEL_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_SEL_IND
              webCvgInsInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_CVG_INS_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_CVG_INS_IND
              webUpdInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_UPD_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_UPD_IND
              webCvgDelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_CVG_DEL_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_CVG_DEL_IND
              webInsInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_INS_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_INS_IND
              webDelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDSG_WEB_DEL_IND"
                x-lineageReferenceObject: PTRBDSG_WEB_DEL_IND
              desc:
                maxLength: 30
                type: string
                description: "Lineage reference object : PTRBDSG_DESC"
                x-lineageReferenceObject: PTRBDSG_DESC
            x-lineageReferenceObject: ptrbdsg
        ptrbdpg:
          type: array
          items:
            type: object
            properties:
              webCvgUpdInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_CVG_UPD_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_CVG_UPD_IND
              webCvgSelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_CVG_SEL_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_CVG_SEL_IND
              webEmprInd:
                title: Display Employer Amounts
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_EMPR_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_EMPR_IND
              webOpenInd:
                title: Include in Open and New Hire Enrollment
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_OPEN_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_OPEN_IND
              webSelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_SEL_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_SEL_IND
              webCvgInsInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_CVG_INS_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_CVG_INS_IND
              webUpdInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_UPD_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_UPD_IND
              webCvgDelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_CVG_DEL_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_CVG_DEL_IND
              webInsInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_INS_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_INS_IND
              priority:
                title: Benefit Enrollment Priority
                maxLength: 3
                type: number
                description: "Lineage reference object : PTRBDPG_PRIORITY"
                x-lineageReferenceObject: PTRBDPG_PRIORITY
              webDelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDPG_WEB_DEL_IND"
                x-lineageReferenceObject: PTRBDPG_WEB_DEL_IND
            x-lineageReferenceObject: ptrbdpg
        ptrbdgm:
          type: array
          items:
            required:
              - bdcaCode
            type: object
            properties:
              webCvgSelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_CVG_SEL_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_CVG_SEL_IND
              webEmprInd:
                title: Display Employer Amounts
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_EMPR_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_EMPR_IND
              bdcaCode:
                title: Benefit or Deduction
                maxLength: 30
                type: string
                description: "Lineage reference object : PTRBDGM_BDCA_CODE"
                x-lineageReferenceObject: PTRBDGM_BDCA_CODE
              webBalcDelInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_BALC_DEL_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_BALC_DEL_IND
              webOpenInd:
                title: Include in Open and New Hire Enrollment
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_OPEN_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_OPEN_IND
              webCvgInsInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_CVG_INS_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_CVG_INS_IND
              webUpdInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_UPD_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_UPD_IND
              webCvgUpdInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_CVG_UPD_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_CVG_UPD_IND
              webBalcUpdInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_BALC_UPD_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_BALC_UPD_IND
              webSelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_SEL_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_SEL_IND
              bdcaDesc:
                type: string
              webCvgDelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_CVG_DEL_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_CVG_DEL_IND
              webInsInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_INS_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_INS_IND
              webBalcSelInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_BALC_SEL_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_BALC_SEL_IND
              webDelInd:
                maxLength: 3
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_DEL_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_DEL_IND
              webBalcInsInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : PTRBDGM_WEB_BALC_INS_IND"
                x-lineageReferenceObject: PTRBDGM_WEB_BALC_INS_IND
            x-lineageReferenceObject: ptrbdgm
    benefit-or-deduction-grouping-rule-1.0.0_get_request:
      required:
        - bdpgCode
      type: object
      properties:
        bdpgCode:
          title: Primary Group
          maxLength: 30
          type: string
          description: "Lineage reference object : bdpgCode"
          x-lineageReferenceObject: bdpgCode
      x-lineageReferenceObject: KEY_BLOCK
    benefit-or-deduction-grouping-rule-1.0.0_qapi_post:
      required:
        - bdpgCode
      type: object
      properties:
        bdpgCode:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
