openapi: 3.0.0
info:
  title: additional-student-information-attribute-end
  description: API for SGASADD administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SGASADD
  x-source-domain: Student
  x-source-title: Additional Student Information
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/additional-student-information-attribute-end:
    post:
      tags:
        - additional-student-information-attribute-end
      summary: Creates a new resource in SGASADD
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/additional-student-information-attribute-end-1.0.0_\
                post_request"
            example:
              sgastdnId: APITEST
              sgastdnTermCodeEff: 201430
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/additional-student-information-attribute-end-1.0.0_\
                    post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/additional-student-information-attribute-end: {}
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    additional-student-information-attribute-end-1.0.0_post_request:
      type: object
      properties:
        sgastdnId:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : sgastdnId"
          x-lineageReferenceObject: sgastdnId
        sgastdnTermCodeEff:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : sgastdnTermCodeEff, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: sgastdnTermCodeEff
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SGASTDN_KEY_BLOCK
    additional-student-information-attribute-end-1.0.0_post_response:
      type: object
      properties:
        sgastdn_key_block:
          type: array
          items:
            type: object
            properties:
              sgastdnId:
                title: ID
                maxLength: 9
                type: string
                description: "Lineage reference object : sgastdnId"
                x-lineageReferenceObject: sgastdnId
              sgastdnTermCodeEff:
                title: Term
                maxLength: 30
                type: string
                description: "Lineage reference object : sgastdnTermCodeEff, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sgastdnTermCodeEff
                x-lineageLookupReferenceObject: stvterm
              sgastdnName:
                maxLength: 230
                type: string
                description: "Lineage reference object : sgastdnName"
                x-lineageReferenceObject: sgastdnName
              confidInfo:
                maxLength: 30
                type: string
                description: "Lineage reference object : confidInfo"
                x-lineageReferenceObject: confidInfo
              deceasedInd:
                maxLength: 30
                type: string
                description: "Lineage reference object : deceasedInd"
                x-lineageReferenceObject: deceasedInd
            x-lineageReferenceObject: sgastdn_key_block
        attr_ctrl_block:
          type: array
          items:
            type: object
            properties:
              sgrsattTermCodeTo:
                title: To Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sgrsattTermCodeTo, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sgrsattTermCodeTo
                x-lineageLookupReferenceObject: stvterm
              sgrsattTermCodeFrom:
                title: From Term
                maxLength: 6
                type: string
                description: "Lineage reference object : sgrsattTermCodeFrom, Lookup lineage
                  reference object : stvterm"
                x-lineageReferenceObject: sgrsattTermCodeFrom
                x-lineageLookupReferenceObject: stvterm
            x-lineageReferenceObject: attr_ctrl_block
        sgrsatt:
          type: array
          items:
            required:
              - attsCode
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SGRSATT_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SGRSATT_ACTIVITY_DATE
              stspKeySequence:
                title: Study Path
                maxLength: 30
                type: number
                description: "Lineage reference object : SGRSATT_STSP_KEY_SEQUENCE, Lookup
                  lineage reference object : sgvstsp,sgrstsp"
                x-lineageReferenceObject: SGRSATT_STSP_KEY_SEQUENCE
                x-lineageLookupReferenceObject: sgvstsp,sgrstsp
              attsCode:
                title: Attribute Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SGRSATT_ATTS_CODE, Lookup lineage
                  reference object : stvatts"
                x-lineageReferenceObject: SGRSATT_ATTS_CODE
                x-lineageLookupReferenceObject: stvatts
              sgvstspDesc:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SGRSATT_USER_ID"
                x-lineageReferenceObject: SGRSATT_USER_ID
              attrDesc:
                title: Description
                type: string
            x-lineageReferenceObject: sgrsatt
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
