openapi: 3.0.0
info:
  title: faculty-advisor-query
  description: API for SIAIQRY administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SIAIQRY
  x-source-domain: Student
  x-source-title: Faculty/Advisor Query
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/faculty-advisor-query:
    get:
      tags:
        - faculty-advisor-query
      summary: Return resources from SIAIQRY
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckTermCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckSchdInd
          in: query
          required: false
          schema:
            type: string
        - name: keyblckAdvrInd
          in: query
          required: false
          schema:
            type: string
        - name: keyblckFctgCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckFstpCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckTenrCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblckFcstCode
          in: query
          required: false
          schema:
            type: string
        - name: faclId
          in: query
          description: ID
          required: false
          schema:
            type: string
        - name: faclLastName
          in: query
          description: Last Name
          required: false
          schema:
            type: string
        - name: faclFirstName
          in: query
          description: First Name
          required: false
          schema:
            type: string
        - name: faclMi
          in: query
          description: Middle Name
          required: false
          schema:
            type: string
        - name: faclSchdInd
          in: query
          required: false
          schema:
            type: string
        - name: faclAdvrInd
          in: query
          required: false
          schema:
            type: string
        - name: sirdpclCollCode
          in: query
          description: College
          required: false
          schema:
            type: string
        - name: sirdpclDeptCode
          in: query
          description: Department
          required: false
          schema:
            type: string
        - name: faclDummy
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/faculty-advisor-query-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/faculty-advisor-query:
    post:
      tags:
        - faculty-advisor-query QAPI (Query by POST)
      summary: Return resources from SIAIQRY
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/faculty-advisor-query-1.0.0_get_request"
            example:
              keyblckSchdInd: Y
              keyblckTermCode: 201010
              faclId: A00031928
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/faculty-advisor-query-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    faculty-advisor-query-1.0.0_get_response:
      type: object
      properties:
        faclMi:
          title: Middle Name
          maxLength: 60
          type: string
        sirdpclCollCode:
          title: College
          maxLength: 2
          type: string
          description: "Lookup lineage reference object : stvcoll"
          x-lineageLookupReferenceObject: stvcoll
        sirdpclDeptCode:
          title: Department
          maxLength: 4
          type: string
          description: "Lookup lineage reference object : stvdept"
          x-lineageLookupReferenceObject: stvdept
        faclFirstName:
          title: First Name
          maxLength: 60
          type: string
        faclSchdInd:
          maxLength: 1
          type: string
        faclAdvrInd:
          maxLength: 1
          type: string
        faclLastName:
          title: Last Name
          maxLength: 60
          type: string
        faclDummy:
          maxLength: 1
          type: string
          description: "Lookup lineage reference object : sirdpcl,sirdpcl"
          x-lineageLookupReferenceObject: sirdpcl,sirdpcl
        faclId:
          title: ID
          maxLength: 9
          type: string
      x-lineageReferenceObject: sivfacq
    faculty-advisor-query-1.0.0_get_request:
      type: object
      properties:
        keyblckFcstCode:
          title: Status
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckFcstCode, Lookup lineage
            reference object : stvfcst"
          x-lineageReferenceObject: keyblckFcstCode
          x-lineageLookupReferenceObject: stvfcst
        sirdpclDeptCode:
          title: Department
          maxLength: 4
          type: string
          description: "Lookup lineage reference object : stvdept"
          x-lineageLookupReferenceObject: stvdept
        keyblckTenrCode:
          title: Tenure Status
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTenrCode"
          x-lineageReferenceObject: keyblckTenrCode
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        keyblckAdvrInd:
          title: Advisor
          maxLength: 1
          type: string
          description: "Lineage reference object : keyblckAdvrInd"
          x-lineageReferenceObject: keyblckAdvrInd
        faclSchdInd:
          maxLength: 1
          type: string
        faclLastName:
          title: Last Name
          maxLength: 60
          type: string
        faclAdvrInd:
          maxLength: 1
          type: string
        faclId:
          title: ID
          maxLength: 9
          type: string
        faclMi:
          title: Middle Name
          maxLength: 60
          type: string
        sirdpclCollCode:
          title: College
          maxLength: 2
          type: string
          description: "Lookup lineage reference object : stvcoll"
          x-lineageLookupReferenceObject: stvcoll
        keyblckFctgCode:
          title: Category
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckFctgCode, Lookup lineage
            reference object : stvfctg"
          x-lineageReferenceObject: keyblckFctgCode
          x-lineageLookupReferenceObject: stvfctg
        keyblckSchdInd:
          title: Faculty
          maxLength: 1
          type: string
          description: "Lineage reference object : keyblckSchdInd"
          x-lineageReferenceObject: keyblckSchdInd
        faclFirstName:
          title: First Name
          maxLength: 60
          type: string
        keyblckFstpCode:
          title: Staff Type
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckFstpCode, Lookup lineage
            reference object : stvfstp"
          x-lineageReferenceObject: keyblckFstpCode
          x-lineageLookupReferenceObject: stvfstp
        faclDummy:
          maxLength: 1
          type: string
          description: "Lookup lineage reference object : sirdpcl,sirdpcl"
          x-lineageLookupReferenceObject: sirdpcl,sirdpcl
      x-lineageReferenceObject: SIVFACQ
    faculty-advisor-query-1.0.0_qapi_post:
      type: object
      properties:
        keyblckTermCode:
          type: string
        keyblckSchdInd:
          type: string
        keyblckAdvrInd:
          type: string
        keyblckFctgCode:
          type: string
        keyblckFstpCode:
          type: string
        keyblckTenrCode:
          type: string
        keyblckFcstCode:
          type: string
        faclId:
          title: ID
          maxLength: 9
          type: string
        faclLastName:
          title: Last Name
          maxLength: 60
          type: string
        faclFirstName:
          title: First Name
          maxLength: 60
          type: string
        faclMi:
          title: Middle Name
          maxLength: 60
          type: string
        faclSchdInd:
          maxLength: 1
          type: string
        faclAdvrInd:
          maxLength: 1
          type: string
        sirdpclCollCode:
          title: College
          maxLength: 2
          type: string
          description: "Lookup lineage reference object : stvcoll"
          x-lineageLookupReferenceObject: stvcoll
        sirdpclDeptCode:
          title: Department
          maxLength: 4
          type: string
          description: "Lookup lineage reference object : stvdept"
          x-lineageLookupReferenceObject: stvdept
        faclDummy:
          maxLength: 1
          type: string
          description: "Lookup lineage reference object : sirdpcl,sirdpcl"
          x-lineageLookupReferenceObject: sirdpcl,sirdpcl
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
