openapi: 3.0.0
info:
  title: Person Matching Requests
  description: >-
    Information about new person requests that are processed through duplicate
    prevention matching rules.


    The person-matching-requests API tracks the status of the duplicate checking process that will begin with a person-matching-requests-initiations-prospects POST request submitted by an integrating system to create a new prospective student person record.


    Please refer to "Person matching process" section in the Banner Ethos API Handbook for additional processing details on this API.
  version: 1.0.0
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Foundation
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/person-matching-requests:
    get:
      summary: Return all resources from GOBPMRQ
      description: Returns a paged listing of all the person matching request records
        from GOBPMRQ table.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_MATCHING_REQUESTS
      tags:
        - person-matching-requests
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
        - name: criteria
          in: query
          required: false
          schema:
            type: object
          description: >
            ### Outcomes Type  

            Returns all person matching requests for the type passed. The type of outcome (initial or final).

            ```

            /person-matching-requests?criteria={"outcomes":[{"type":"initial"}]}

            ```

            ### Outcomes Status  

            Returns all person matching requests for the status passed.

            ```

            /person-matching-requests?criteria={"outcomes":[{"status":"newPerson"}]}

            ```

            ### Originator  

            Returns all person matching requests for the originator passed.

            ```

            /person-matching-requests?criteria={"originator":"GRAILS_USER"}

            ```
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-person-matching-requests.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/person-matching-requests/{id}:
    get:
      summary: Return the requested resource from GOBPMRQ
      description: Return the one resource with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_PERSON_MATCHING_REQUESTS
      tags:
        - person-matching-requests
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Person Matching Requests for use in all
            external references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v1+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v1.0.0+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-person-matching-requests.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-person-matching-requests.json:
      title: Person Matching Requests
      description: Information about new person requests that are processed through
        duplicate prevention matching rules.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the person matching request.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: GOBPMRQ_GUID(GOBPMRQ)
        person:
          title: Person
          description: The new or matched person record.
          oneOf:
            - type: object
              properties:
                id:
                  title: ID
                  description: The global identifier for the Person.
                  type: string
                  format: guid
                  pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
                  x-lineageLookupReferenceObject: persons 
                  x-lineageReferenceObject: GORGUID_GUID(LDM_NAME = persons) 
                  x-lineageDerivedLogic: Display the GUID from GORGUID table where GORGUID_LDM_NAME='persons' and GORGUID_DOMAIN_KEY matches the GOBPMRQ_PIDM
              additionalProperties: false
              required:
                - id
            - type: object
              maxProperties: 0
        outcomes:
          title: Outcomes
          description: The outcome of the person matching request.
          type: array
          items:
            type: object
            properties:
              type:
                title: Type
                description: The type of outcome (initial or final).
                enum:
                  - initial
                  - final
                type: string
                x-lineageReferenceObject: derived  
                x-lineageDerivedLogic: Display as 'initial' if GOBPMRQ_INIT_STATUS value is displayed as 'outcomes.status'. Display as 'final' if GOBPMRQ_FINAL_STATUS value is displayed as 'outcomes.status'
              status:
                title: Status
                description: The outcome status of the person matching request.
                enum:
                  - newPerson
                  - existingPerson
                  - reviewRequired
                  - rejectedRequest
                type: string
                x-lineageReferenceObject: GOBPMRQ_FINAL_STATUS(GOBPMRQ) or  GOBPMRQ_INIT_STATUS(GOBPMRQ)
              date:
                title: Date
                description: The date and time associated with the status of the person matching
                  request.
                type: string
                format: date-time
                pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                x-lineageReferenceObject: GOBPMRQ_FINAL_STATUS_DATE(GOBPMRQ) or  GOBPMRQ_INIT_STATUS_DATE(GOBPMRQ)
            additionalProperties: false
            required:
              - type
              - status
              - date
        originator:
          title: Originator
          description: The originator (user or system) of the person matching request.
          type: string
          x-lineageReferenceObject: GOBPMRQ_ORIGINATOR(GOBPMRQ)
      required:
        - id
        - outcomes
      additionalProperties: false

