openapi: 3.0.0
info:
  title: Section Statuses
  description: >-
    The list of user defined statuses that may be applied to a section.


    Please refer to "API Integration Configuration Settings" section in the Banner Ethos API Handbook for details on API configuration settings that needs to be configured for this API.
  version: "11.0"
  x-audience: all
  x-source-system: banner
  x-api-type: ethos
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/section-statuses:
    get:
      summary: Return all resources from STVSSTS
      description: >-
        Returns a paged listing of all the section status records from STVSSTS
        table.


        The 'category' property is retrieved based on the STVSSTS_CODE mapping to 'open', 'closed', 'cancelled' in the API configuration setting 'SECTIONDETAIL.STATUS.V4'. If there is no mapping established, then 'category' is retrieved based on the indicators STVSSTS_ACTIVE_IND and STVSSTS_REG_IND.
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SECTION_STATUSES
      tags:
        - section-statuses
      parameters:
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Prefer to use only the whole
            MAJOR version.  See the semantic versioning topic in the API
            Standards from more information. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: The maximum number of resources requesting for this result set.
            Default page limit is 500 and upper limit is 1000.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The 0 based index for a collection of resources for the page
            requested.
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/schema-section-statuses.json"
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
            X-Total-Count:
              description: Specifies the total number of resources that satisfy the query.
              schema:
                type: integer
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
  /api/section-statuses/{id}:
    get:
      summary: Return the requested resource from STVSSTS
      description: Return the single section status record with the passed in identifier
      security:
        - EthosIntegrationBearer: []
      x-method-permissions: API_SECTION_STATUSES
      tags:
        - section-statuses
      parameters:
        - name: id
          in: path
          required: true
          description: A global identifier of Section Statuses for use in all external
            references
          schema:
            type: string
            format: GUID
            minimum: 1
        - name: accept
          in: header
          required: true
          description: >
            The version of the resource requested. Please refer to the API
            source documentation for detailed support information. Prefer to use
            only the whole MAJOR version. 

            ```

            application/vnd.hedtech.integration.v11+json

            ```
          schema:
            type: string
      responses:
        "200":
          description: Success
          headers:
            X-Media-Type:
              description: application/vnd.hedtech.integration.v11+json
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v11+json:
              schema:
                type: object
                $ref: "#/components/schemas/schema-section-statuses.json"
        "401":
          description: Unauthorized
        "404":
          description: Resource not found
        "500":
          description: Server error, unexpected configuration or data
components:
  securitySchemes:
    EthosIntegrationBearer:
      type: http
      scheme: bearer
  schemas:
    schema-section-statuses.json:
      title: Section Statuses
      description: The list of user defined statuses that may be applied to a section.
      type: object
      properties:
        metadata:
          title: Metadata
          description: Metadata about the JSON payload
          type: object
          properties:
            createdBy:
              title: Created By
              description: The name of the originator (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            createdOn:
              title: Created On
              description: The date and time when the entity instance was created
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
            modifiedBy:
              title: Modified By
              description: The name of the modifier (user or system) of the data. This is
                informational only, do not use in business logic!
              type: string
            modifiedOn:
              title: Modified On
              description: The date and time when the entity instance was last modified
              oneOf:
                - type: string
                  format: date-time
                  pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
                - type: string
                  maxLength: 0
          additionalProperties: false
        id:
          title: ID
          description: The global identifier of the section status.
          type: string
          format: guid
          pattern: ^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$
          x-lineageReferenceObject: STVSSTS_GUID(STVSSTS)
        title:
          title: Title
          description: The full name of the section status.
          type: string
          minLength: 1
          x-lineageReferenceObject: STVSSTS_DESC(STVSSTS)
        description:
          title: Description
          description: The description of the section status.
          type: string
          x-lineageReferenceObject: unsupported
        category:
          title: Category
          description: The category of the section status.
          enum:
            - open
            - closed
            - pending
            - cancelled
          type: string
          x-lineageReferenceObject: derived  
          x-lineageDerivedLogic: Category is derived based on the STVSSTS_CODE mapping to 'open', 'closed', 'cancelled'  in SECTIONDETAIL.STATUS.V4 setting. If above  mapping is not established, then category is derived based on the following criteria- Display 'open' if STVSSTS_CODE has STVSSTS_ACTIVE_IND = 'A' and STVSSTS_REG_IND = 'Y'. Display 'closed' if STVSSTS_CODE has STVSSTS_ACTIVE_IND = 'A' and STVSSTS_REG_IND = 'N'. Display 'cancelled' if STVSSTS_CODE has STVSSTS_ACTIVE_IND = 'I' and STVSSTS_REG_IND = 'N'
        code:
          title: Code
          description: The code that may be used to identify the section status.
          type: string
          x-lineageReferenceObject: STVSSTS_CODE(STVSSTS)
      required:
        - id
        - title
        - category
      additionalProperties: false
